### ISSUE TITLE
thgss.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1001]
### Test link (required):
http://thgss.com/index.php?p=download

### Screenshot of the web page (including address bar and extension icons) (required):
![2018-11-09_184639](https://user-images.githubusercontent.com/2828165/48276132-ec21fd80-e44f-11e8-85bc-470c9643c17d.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2018-11-09_184715](https://user-images.githubusercontent.com/2828165/48276137-f217de80-e44f-11e8-836c-d079c03aca32.png)

### Environment (Required):

Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.75+Nano Defender 15.0.0.71

#### Your filter lists (Required):

**Built-in (10/11)**
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

**Multipurpose (2/5)**
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (2/36)**
ARA: Liste AR
IRN: Adblock-Iran

**Custom (2/3)**
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt​​​​​https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt

**Comment by titosalah** [comment]
@jspenguin2017  thank you very much ... Not working  even when disable Nano Adblocker+Nano Defender  >> and disable kaspersky website told me disable adblock 
internet explorer >>same problem disable adblock massage appeared without any adblock addons installed
 
firefox 64.0b6 x64bit (ublock origin+ nano defender 15.0.0.67 ) not work 

![2018-11-14_204926](https://user-images.githubusercontent.com/2828165/48505074-e14fda00-e84e-11e8-8753-568d324f3ad6.png)
![2018-11-14_204943](https://user-images.githubusercontent.com/2828165/48505089-e876e800-e84e-11e8-8381-392112cd03f4.png)

do u have solution to this problem
thank you very much

**Comment by jspenguin2017** [comment]
Works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/48508257-54cff800-e80b-11e8-894b-7bd30afdfc88.png)

**Comment by titosalah** [comment]
@jspenguin2017  I know site works with you. I just ask you because you are more experienced. What is the cause of this problem and how to fix
thank you bro

**Comment by jspenguin2017** [comment]
I don't know, it's up to you to investigate on your side.

**Comment by titosalah** [comment]
now i  download palemoon newest version without addons >> and same problem
i think kaspersky or my connection >> i don't know 
![2018-11-14_235631](https://user-images.githubusercontent.com/2828165/48515460-6c3dce00-e869-11e8-9db6-d4f025253213.png)

**Comment by titosalah** [comment]
Problem Solved >> when i disable Kaspersky working 
thank you bro

**Comment by titosalah** [comment]
@jspenguin2017 solution for kaspersky without disable Antivirus
![2018-11-15_001111](https://user-images.githubusercontent.com/2828165/48516268-9bedd580-e86b-11e8-9ece-f21baf585ba1.png)
