### ISSUE TITLE
leakish.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1002]
### Test link (required):
https://www.leakish.com/learn-advanced-seo-from-scratchcomplete-seo-training-course-free/

### Screenshot of the web page (including address bar and extension icons) (required):
![2018-11-15_225114](https://user-images.githubusercontent.com/2828165/48581016-555eb080-e929-11e8-8f52-279d2c85bd46.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2018-11-15_225332](https://user-images.githubusercontent.com/2828165/48581024-5bed2800-e929-11e8-9295-dd06b5284f66.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 70.0.3538.102 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.75+Nano Defender 15.0.0.71

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

**Multipurpose (2/5)**
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (2/36)**
ARA: Liste AR
IRN: Adblock-Iran

**Custom (2/3)**
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt​​​​​https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt

**Comment by jspenguin2017** [comment]
Can't reproduce -- disable your anti-social filters. 

@okiehsch Social locker, can you pick it? 

![image](https://user-images.githubusercontent.com/7283682/48581278-9c738400-e8de-11e8-9711-ff39c391f1e0.png)

**Comment by okiehsch** [comment]
No.

**Comment by jspenguin2017** [comment]
Yea, it's kind of hard to pick. The link is: `https://www.udemy.com/learn-advanced-seo-from-scratch/`.
