### ISSUE TITLE
flexydrive.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1010]
### Test link (required):
http://flexydrive.com/4yeakn6c4op1

### Screenshot of the web page (including address bar and extension icons) (required):
![2018-12-12_103115](https://user-images.githubusercontent.com/2828165/49856798-b2df0380-fde8-11e8-864c-8b50182e548d.png)
### Screenshot of the console (press `F12` to bring up the console) (required):
![2018-12-12_103253](https://user-images.githubusercontent.com/2828165/49856809-bc686b80-fde8-11e8-8377-5c55f99d18f7.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 71.0.3578.80 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.81+Nano Defender 15.0.0.80

**Your filter lists (Required):**
**Built-in (10/11)**
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

**Multipurpose (2/5)**
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Custom**
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt​​​​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt​​​​​​​​​​
https://zerodot1.gitlab.io/CoinBlockerLists/hosts​​​​​
https://zerodot1.gitlab.io/CoinBlockerLists/MiningServerIPList.txt
https://www.dshield.org/feeds/suspiciousdomains_High.txt​​​​​
https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt​​

**Comment by jspenguin2017** [comment]
It's a text node, which is difficult to hide. I opened a tracking issue for it: https://github.com/NanoMeow/QuickReports/issues/436
