### ISSUE TITLE
file-up.org

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1013]
### Test link (required):
https://www.file-up.org/o7963xxzv1xn

**After click Free Download**

### Screenshot of the web page (including address bar and extension icons) (required):
![2018-12-20_084621](https://user-images.githubusercontent.com/2828165/50268599-147c1f00-0434-11e9-8f2a-00594c301c9e.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2018-12-20_084653](https://user-images.githubusercontent.com/2828165/50268609-1d6cf080-0434-11e9-8f3f-e6cfbf047ce1.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 71.0.3578.80 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.81+Nano Defender 15.0.0.80

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

Malware domains (2/4)
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

**Multipurpose (2/5)**
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Custom**
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt​​​​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt​​​​​​​​​​
https://zerodot1.gitlab.io/CoinBlockerLists/hosts​​​​​
https://zerodot1.gitlab.io/CoinBlockerLists/MiningServerIPList.txt
https://www.dshield.org/feeds/suspiciousdomains_High.txt​​​​​
https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt​​

**Comment by jspenguin2017** [comment]
It was fixed, update your filters.

**Comment by titosalah** [comment]
@jspenguin2017  thank you very much bro

**Comment by titosalah** [comment]
@jspenguin2017 Hi Bro 
this site update . and countdown not working and stuck 

url
https://www.file-up.org/l9urr5pzos7c

![2020-02-27_215247](https://user-images.githubusercontent.com/2828165/75481406-acb45300-59ab-11ea-9930-6d5a113c57b6.png)

![2020-02-27_215313](https://user-images.githubusercontent.com/2828165/75481415-b1790700-59ab-11ea-9b92-e0ee9bb69a6f.png)

thank u

**Comment by jspenguin2017** [comment]
Could reproduce ads placeholders but countdown works fine for me. 

https://github.com/NanoMeow/QuickReports/issues/3157

---

Do not dig up old issues, open new issues for new problems.
