### ISSUE TITLE
[Question] timer bypass

### ISSUE THREAD

**Issue by sliperhr** [jspenguin2017/uBlockProtector#1014]
is the timer bypass gone or just been updated into a new name or list?

**Comment by jspenguin2017** [comment]
It's merged into uBlock filters.

**Comment by Piter432** [comment]
@jspenguin2017: Which one (name)?

**Comment by jspenguin2017** [comment]
The base filter. It doesn't always work, if the timer is checked on server side, it can't be skipped.
