### ISSUE TITLE
sh.st

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#1015]
Test Link: http://sh.st/vYTB3
Expected Result: Since it's a URL shortening service we expect it to take us to destination url. Instead it's throw a error.

Screenshot: https://s.put.re/ZZK66K2N.png

If Nano Adblocker is disabled then it's works fine, if it's active then it's throws the error.

**Comment by jspenguin2017** [comment]
Looks like rate limiting, if you refresh it works fine. 
Seems to be related to the Shortest bypasser.

**Comment by jspenguin2017** [comment]
I'll disable the rule for now.
