### ISSUE TITLE
theverge.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#1019]
### Test link (required):
https://www.theverge.com/

### Screenshot of the console (press `F12` to bring up the console) (required):
![capture](https://user-images.githubusercontent.com/15007183/50662598-f99dc480-0f74-11e9-9485-3a1aa0a55dab.PNG)

### Environment (Required):

- Operating System and Version: win7pro
- Browser and Version: chrome 71
- Adblocker and Version: ubo 1.17.4

#### Your filter lists (Required):
ubo reg + pl list

**Comment by jspenguin2017** [comment]
@okiehsch Annoyance.
