### ISSUE TITLE
uploadproper.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#1022]
Test link: https://uploadproper.com/m340rfwnhj7j

Patch timer? and **untick** "Use Our Download Manager" by default?

**Comment by ghajini** [comment]
@mapx- is it somewhat 
https://github.com/uBlockOrigin/uAssets/issues/5469#issuecomment-487555110

**Comment by mapx-** [comment]
something like
```
uploadproper.net###dvPassport:style(display: block !important)
uploadproper.net##label
```

**Comment by ghajini** [comment]
Great, I can download the file

**Comment by llacb47** [comment]
Can this be closed?

**Comment by jspenguin2017** [comment]
Was it fixed?

**Comment by jspenguin2017** [comment]
Moving this to QuickReport repository. 
https://github.com/NanoMeow/QuickReports/issues/3775
