### ISSUE TITLE
gorillavid.in

### ISSUE THREAD

**Issue by JohnMiller9898** [jspenguin2017/uBlockProtector#1026]
### Screenshot of the web page (including address bar and extension icons) (required):
![capture](https://user-images.githubusercontent.com/13141946/51099080-d8d43b00-17ce-11e9-9df8-21d353eebdbf.JPG)

### Screenshot of the console (press `F12` to bring up the console) (required):
![console 1](https://user-images.githubusercontent.com/13141946/51099172-6f086100-17cf-11e9-8ec2-d49ba1893b6c.JPG)
![console 2](https://user-images.githubusercontent.com/13141946/51099173-6fa0f780-17cf-11e9-9839-7f61fb8fa7f6.JPG)

### Environment (Required):

- Operating System and Version: Windows 10, latest
- Browser and Version: Chrome, latest
- Adblocker and Version: uBlock Origin, latest

**Comment by jspenguin2017** [comment]
The video does not play for me even if I use a browser without extensions.

**Comment by jspenguin2017** [comment]
@mapx- Maybe GeoLock, can you test?

**Comment by mapx-** [comment]
tested, flash required but even disabling uBo I get no video
