### ISSUE TITLE
imdb.com

### ISSUE THREAD

**Issue by JohnMiller9898** [jspenguin2017/uBlockProtector#1032]
### Screenshot of the web page (including address bar and extension icons) (required):
![imdb](https://user-images.githubusercontent.com/13141946/51758515-29e50880-20c6-11e9-9275-ca1fbda569dc.JPG)
Ghostery (other extension) is disabled

### Screenshot of the console (press `F12` to bring up the console) (required):
![capture](https://user-images.githubusercontent.com/13141946/51758654-76c8df00-20c6-11e9-8d65-c2b9b9977b9e.JPG)

### Environment (Required):

- Operating System and Version: Windows 10
- Browser and Version: Chrome, latest
- Adblocker and Version: Ublock Origin, latest

**Comment by jspenguin2017** [comment]
Can't reproduce, it works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/51781091-77b33e00-20d1-11e9-98fc-b7f8e2fedbae.png)

**Comment by JohnMiller9898** [comment]
fixed it. thanks. keep the AMAZING work. EXTREMELY THANKFUL.
