### ISSUE TITLE
easy-coin.cf

### ISSUE THREAD

**Issue by thienha1** [jspenguin2017/uBlockProtector#1034]
### Test link (required):

http://easy-coin.cf/
### Screenshot of the web page (including address bar and extension icons) (required):

<img src="https://www.upsieutoc.com/images/2019/01/29/Untitledb8dd337c9b79c82b.png" alt="Untitledb8dd337c9b79c82b.png" border="0" />

### Screenshot of the console (press `F12` to bring up the console) (required):

<img src="https://www.upsieutoc.com/images/2019/01/29/Untitledd6143807886b5ed1.png" alt="Untitledd6143807886b5ed1.png" border="0" />

### Environment (Required):

- Operating System and Version: WIN 10 Pro 64BIT
- Browser and Version: Google Chrome v71.0.3578.98 (Official Version) (64-bit)
- Adblocker and Version: Nano Adblocker 1.0.0.86 + Nano Defender 15.0.0.89

#### Your filter lists (Required):

**Built in**
Nano Defender Integration Used 2,553 on 2,671
Nano filters Used 174 of 177
Nano filters - Whitelist Used 0 of 1
uBlock filters Used 13,245 out of 13,256
uBlock filters - Badware risks Used 49 of 49
uBlock filters - Privacy Used 158 out of 159
uBlock filters - Resource abuse Used 279 of 279
uBlock filters - Unbreak Used 780 on 782
**Advertising (2/5)**
Adblock Warning Removal List Used 601 of 608
EasyList Used 87.106 on 87.236
**Private (1/3)**
EasyPrivacy Used 16,223 on 16,435
**Dangerous domain names (2/4)**
Malware Domain List Used 1,094 on 1,109
Malware domains Used 26,874 on 26.874
**Uncomfortable (0/6)**
**Multi-function (1/5)**
Peter Lowe's Ad and tracking server list Already used 2,973 on 2,973
**Area, language (1/38)**
VIE: ABPVN List Used 875 on 884

**Comment by mapx-** [comment]
fixed
