### ISSUE TITLE
sardeath.com

### ISSUE THREAD

**Issue by kirbyfan64** [jspenguin2017/uBlockProtector#1039]
### Test link (required):
https://sardeath.com/fate-extella-link-original-soundtrack-mp3-zip/

### Screenshot of the web page (including address bar and extension icons) (required):
![screenshot from 2019-02-14 12-36-07](https://user-images.githubusercontent.com/1690697/52809115-23a6d400-3055-11e9-871b-fd8e569278dc.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![screenshot from 2019-02-14 12-36-35](https://user-images.githubusercontent.com/1690697/52809146-33261d00-3055-11e9-89db-f92bbd7571a4.png)

### Explain what was not right (optional if obvious):
obvious

### Reproduction steps (optional if trivial):
obvious

### Environment (Required):

- Operating System and Version: Fedora Silverblue 29.
- Browser and Version: Chrome 72.
- Adblocker and Version: Nano Adblocker v1.0.0.87

#### Your filter lists (Required):
I have the default set of filter lists.

#### Your custom filters (Required if you have any):
None.

### Add everything else that you believe to be useful below (optional):

[Adguard has fixed this](https://github.com/AdguardTeam/AdguardFilters/commit/4d48897ba780e8100040c49abeba6d83b63df547).

**Comment by mapx-** [comment]
fixed
