### ISSUE TITLE
Adding to adguard (Android)

### ISSUE THREAD

**Issue by d0x360** [jspenguin2017/uBlockProtector#1040]
Is there any way to add this to adguard for Android or Windows?

If not could you contact the adguard people and see If they will add the filter list to adguard?  It would be awesome because the old method is as we know broken.

Thanks!

**Comment by jspenguin2017** [comment]
Nano Defender does not support AdGuard.

**Comment by d0x360** [comment]
I know that it's not directly compatibile but when I made the post it was something to look at so adguard could be made to work with an anti adblock killer list... Right now adguard blocks less and less by the week

It doesn't matter, I talked to someone and they told me an update coming in spring will do what this does.

**Comment by Bluscream** [comment]
Yes make this now or delete yourself
