### ISSUE TITLE
windowscentral.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#1042]
### Test link (required):
https://www.windowscentral.com/how-set-and-use-nextpvr-windows-10

### Screenshot of the console (press `F12` to bring up the console) (required):
![capture](https://user-images.githubusercontent.com/15007183/52912609-97c5bf80-3281-11e9-9eaf-f273c0a24284.PNG)

### Environment (Required):

- Operating System and Version: win7pro
- Browser and Version: chrome Version 72.0.3626.109 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.18.4

#### Your filter lists (Required):
stock ubo + pl filters

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/52917684-a32de080-32ab-11e9-9db0-0f991c2f6767.png)
