### ISSUE TITLE
lewat.in

### ISSUE THREAD

**Issue by 3xploiton3** [jspenguin2017/uBlockProtector#1043]
### Test link (required):
https://lewat.in/amazing-gadgets/

### Screenshot of the web page (including address bar and extension icons) (required):
https://i.imgur.com/lhcSpmK.png

### Screenshot of the console (press `F12` to bring up the console) (required):
https://i.imgur.com/aRfm99y.png

### Environment (Required):

- Operating System and Version: windows 10
- Browser and Version: chrome
- Adblocker and Version: ublock origin latest version

#### Your filter lists (Required):
 https://i.imgur.com/nsrkY2x.png

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/52917669-75489c00-32ab-11e9-9609-d814d5b69086.png)

**Comment by 3xploiton3** [comment]
i'm using UBO, how to fix it?

**Comment by jspenguin2017** [comment]
You have way too many filters enabled, you need to figure out which one is causing the problem. 

The website works fine with default filters.

**Comment by 3xploiton3** [comment]
what filter do you used sir? 
i see 4 notif in your nano, me just 3 notif

**Comment by jspenguin2017** [comment]
This is the default setup. For uBO, you'll have 3 custom filters. 
![image](https://user-images.githubusercontent.com/7283682/52918187-99a77700-32b1-11e9-90ff-8fecac079768.png)

**Comment by 3xploiton3** [comment]
thx, now it work 
i will fix my filter if has bad rule
![image](https://user-images.githubusercontent.com/19517680/52918480-08c0b200-332a-11e9-908f-7b66bbbea4e2.png)

**Comment by 3xploiton3** [comment]
i found the problem is, it because AdGuard Base filter
