### ISSUE TITLE
tcpvpn.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1044]
### Test link (required):
https://www.tcpvpn.com/

### Screenshot of the web page (including address bar and extension icons) (required):
![2019-02-28_114613](https://user-images.githubusercontent.com/2828165/53557496-ba43bc80-3b4e-11e9-91db-d86e05022197.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2019-02-28_114631](https://user-images.githubusercontent.com/2828165/53557515-c29bf780-3b4e-11e9-9c5c-276a89ae8c12.png)

**One More Error with Nano Adblocker
Now I can't Edit My filter Links >>Add Or Remove Links  From it 
Why??** 
![2019-02-28_115333](https://user-images.githubusercontent.com/2828165/53557860-81f0ae00-3b4f-11e9-9a3a-6e2fd921137f.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 72.0.3626.109 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.89+Nano Defender 15.0.0.102

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

**Multipurpose (2/5)**
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Custom**
[https://zerodot1.gitlab.io/CoinBlockerLists/list.txt​​​​​](https://zerodot1.gitlab.io/CoinBlockerLists/list.txt%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B)
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt
[https://zerodot1.gitlab.io/CoinBlockerLists/list.txt​​​​​​​​​​](https://zerodot1.gitlab.io/CoinBlockerLists/list.txt%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B)
[https://zerodot1.gitlab.io/CoinBlockerLists/hosts​​​​​](https://zerodot1.gitlab.io/CoinBlockerLists/hosts%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B)
https://zerodot1.gitlab.io/CoinBlockerLists/MiningServerIPList.txt
[https://www.dshield.org/feeds/suspiciousdomains_High.txt​​​​​](https://www.dshield.org/feeds/suspiciousdomains_High.txt%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B%E2%80%8B)
https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
[https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt​​](https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt%E2%80%8B%E2%80%8B)

**Comment by det427** [comment]
Works OK for me. I just have the default filters.

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/53611334-6a371b00-3b8b-11e9-814a-cd1cc424294a.png)

**Comment by jspenguin2017** [comment]
> Now I can't Edit My filter Links

You can only edit your filters in the dashboard, not the assets viewer.

**Comment by titosalah** [comment]
@jspenguin2017   thank you very much
