### ISSUE TITLE
idfl.top

### ISSUE THREAD

**Issue by surya27895** [jspenguin2017/uBlockProtector#1047]
### Test link (required):
http://idfl.top/

### Screenshot of the web page (including address bar and extension icons) (required):
![Image](https://i.imgur.com/DPgDAgn.jpg)

### Screenshot of the console (press `F12` to bring up the console) (required):
![image](https://i.imgur.com/38zk4l7.jpg)

### Environment (Required):

- Operating System and Version:  Windows 10 x64
- Browser and Version:  Google Chrome 72.0.3626.121 x64
- Adblocker and Version:  Nano Adblocker 1.0.0.92
- Nano Defender Version : 15.0.0.108

#### Your filter lists (Required):
Built-in (8/11)
Nano Defender Integration​​​​​2,623 used out of 2,671​​​​
Nano filters​​​​​186 used out of 189​​​​
Nano filters – Whitelist​​​​​0 used out of 1​​​​
uBlock filters​​​​​14,113 used out of 14,128​​​​
uBlock filters – Badware risks​​​​​67 used out of 67​​​​
uBlock filters – Privacy​​​​​156 used out of 157​​​​
uBlock filters – Resource abuse​​​​​281 used out of 281​​​​
uBlock filters – Unbreak​​​​​863 used out of 865​​​​
Ads (2/5)
Adblock Warning Removal List​​​​​607 used out of 626​​​​
EasyList​​​​​87,962 used out of 88,164​​​​
Privacy (1/3)
EasyPrivacy​​​​​16,427 used out of 16,639​​​​
Malware domains (2/4)
Malware Domain List​​​​​1,090 used out of 1,105​​​​
Malware domains​​​​​26,913 used out of 26,913​​​​
Annoyances (0/6)
Multipurpose (1/5)
Peter Lowe's Ad and tracking server list​​​​​2,949 used out of 2,949​​​​
Regions, languages (1/37)
IDN, MYS: ABPindo​​​​​6,994 used out of 7,043​​​​
Custom (2/2)
Anti popads.net​​​​​890 used out of 7,179​​​​
CHEF-KOCH's PopAds Filter List​​​​​9,030 used out of 9,046​​​​

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/NanoAdblocker/NanoFilters/issues/285
