### ISSUE TITLE
adnangamer.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1048]
### Test link (required):
https://adnangamer.com/7Wzc

**i disabled nano adblocker to see adsense ADS Can you bypass this ad to Get link 
You must copy url of ads and paste it in empty form and click submit 
ads open in new tabs not one time 3 or more without get any link**

### Screenshot of the web page (including address bar and extension icons) (required):
![OpenedWithImage (2)](https://user-images.githubusercontent.com/2828165/54309244-6cac6280-45d8-11e9-8e83-f444a91f2d69.jpg)

### Screenshot of the console (press `F12` to bring up the console) (required):
![Annotation](https://user-images.githubusercontent.com/2828165/54308484-c6139200-45d6-11e9-90ae-70b6605e8020.png)

### Explain what was not right (optional if obvious):
Can You bypass Ads

**Environment (Required):**
Operating System and Version: WIN10 64BIT
Browser and Version: Chrome Version 73.0.3683.75 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.92+Nano Defender 15.0.0.108

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Custom**
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt​​​​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt​​​​​​​​​​
https://zerodot1.gitlab.io/CoinBlockerLists/hosts​​​​​
https://zerodot1.gitlab.io/CoinBlockerLists/MiningServerIPList.txt
https://www.dshield.org/feeds/suspiciousdomains_High.txt​​​​​
https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt​​

**Comment by jspenguin2017** [comment]
@okiehsch @mapx-

**Comment by okiehsch** [comment]
I am not sure I understand the issue are you saying that you have to copy the url of ads and paste it in empty form in the screenshot to make the shortener work?

**Comment by titosalah** [comment]
@okiehsch  No Captcha in this site

**Comment by okiehsch** [comment]
Scroll down the page and you will see the captcha or update your filter list, I removed the "Blog Post", so the captcha should be easier to see.

**Comment by titosalah** [comment]
@okiehsch  thank you very much  >> now see captcha
