### ISSUE TITLE
egy.best

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1055]
### Test link (required):
https://egy.best/

### Screenshot of the web page (including address bar and extension icons) (required):
![2019-04-15_205937](https://user-images.githubusercontent.com/2828165/56158244-d9dd5a00-5fc1-11e9-92eb-ac430aef93ca.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2019-04-15_210019](https://user-images.githubusercontent.com/2828165/56158283-e9f53980-5fc1-11e9-9958-98853c05ce91.png)

**Environment (Required):**
Operating System and Version: WIN10 64BIT
Browser and Version: Chrome Version  73.0.3683.103 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.103+Nano Defender 15.0.0.125

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/56174804-8e22b480-5fb1-11e9-808b-745a935a91a3.png)

**Comment by titosalah** [comment]
**thank you 
but everything work  very good on firefox with any extension installed
i don't know what the problem with chrome browser  (with nano adblocker Default filters )**

**Firefox**
![2019-04-16_095207](https://user-images.githubusercontent.com/2828165/56191802-5eb18d80-602d-11e9-8e8a-5bbe235049ee.png)

**Chrome**
![2019-04-16_095059](https://user-images.githubusercontent.com/2828165/56191822-6a04b900-602d-11e9-91ee-a7c77d0051be.png)

**i hope i can fix this problem with chrome**

**Comment by jspenguin2017** [comment]
I tested on Chrome, it works fine for me.

**Comment by titosalah** [comment]
@jspenguin2017  can you fix this website again please ??

**Comment by jspenguin2017** [comment]
Another issue was opened: https://github.com/NanoAdblocker/NanoFilters/issues/373

**Comment by jspenguin2017** [comment]
See: https://github.com/NanoAdblocker/NanoFilters/issues/373
