### ISSUE TITLE
go4gold.uol.com.br

### ISSUE THREAD

**Issue by xitero** [jspenguin2017/uBlockProtector#1058]
### Test link (required):
https://go4gold.uol.com.br/pt-br/login

### Screenshot of the web page (including address bar and extension icons) (required):
![image](https://user-images.githubusercontent.com/28655175/57578105-a543ad80-745c-11e9-9494-4611b9d40669.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
Your screenshot should look something like this: https://i.imgur.com/qnVB0K7.png
![image](https://user-images.githubusercontent.com/28655175/57578125-dde38700-745c-11e9-9dbd-590df7099b90.png)

### Explain what was not right (optional if obvious):
I can not log into my account on this site with Nano Adblocker / Defender enabled. It's just "loading". I tested with both extensions disabled, in anonymous tab and in another browser, in all cases I entered normally.

### Environment (Required):

- Operating System and Version: Windows 10
- Browser and Version: Edge Chromium (Canary)
- Adblocker and Version: Nano Adblocker
1.0.0.107
Nano Defender
15.0.0.140

**Comment by jspenguin2017** [comment]
Removed legacy rules. If that did not help, I would need a test account.

**Comment by xitero** [comment]
@jspenguin2017 Still having the same issue.
Test account:
User: penguingo4gold@emailo.pro
Pass: One23456

**Comment by jspenguin2017** [comment]
Works fine for me, I can login without issue. Make sure you have everything (extensions, filter lists, etc.) updated. 
![image](https://user-images.githubusercontent.com/7283682/57589322-84706c00-74df-11e9-9831-2975bf1ccf38.png)
