### ISSUE TITLE
extra.com.br

### ISSUE THREAD

**Issue by xitero** [jspenguin2017/uBlockProtector#1059]
### Test link (required):
https://www.extra.com.br#login

### Screenshot of the web page (including address bar and extension icons) (required):
![image](https://user-images.githubusercontent.com/28655175/57580024-02e6f280-747b-11e9-8586-2be79f4607d3.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![image](https://user-images.githubusercontent.com/28655175/57580032-1c883a00-747b-11e9-9d4d-d98497759f8a.png)
![image](https://user-images.githubusercontent.com/28655175/57580039-25790b80-747b-11e9-909c-a4ce900045e0.png)

### Explain what was not right (optional if obvious):
I can not log into my account on this site with Nano Adblocker / Defender enabled. It's just "loading". I tested with both extensions disabled, in anonymous tab and in another browser, in all cases I entered normally. 
PS: The difference of the problem of this site for the go4gold is that if I give F5 in the extra.com.br, I am logged in the site.

### Environment (Required):

- Operating System and Version: Windows 10
- Browser and Version: Edge Chromium (Canary)
- Adblocker and Version: Nano Adblocker
1.0.0.107
Nano Defender
15.0.0.140

**Comment by jspenguin2017** [comment]
@okiehsch `@@||js.allowme.com.br/analytics$script,domain=extra.com.br`

**Comment by okiehsch** [comment]
Fixed, thanks.
