### ISSUE TITLE
hackintosh.computer

### ISSUE THREAD

**Issue by mikhoul** [jspenguin2017/uBlockProtector#1061]
### Screenshot of the web page (including address bar and extension icons) (required):

![image](https://user-images.githubusercontent.com/5678673/57713066-c1537480-763f-11e9-99a8-ec5c9ed75ff6.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![image](https://user-images.githubusercontent.com/5678673/57713335-43dc3400-7640-11e9-9a26-2fc8dce3056e.png)

### Environment (Required):

- Operating System and Version:  Win 7 pro
- Browser and Version:  Latest Chrome

#### Your filter lists (Required):

![image](https://user-images.githubusercontent.com/5678673/57713422-72f2a580-7640-11e9-8ab9-5107a1164a52.png)

**Comment by jspenguin2017** [comment]
Not much we can do, they are watching us. 
See: https://github.com/NanoMeow/QuickReports/issues/1199
