### ISSUE TITLE
njiir.com

### ISSUE THREAD

**Issue by RaveN0X87** [jspenguin2017/uBlockProtector#1062]
Example Link :
https://www.njiir.com/p/geotechnical-mapping-of-underground.html?url=IyNERSU1QyU0MCUwNk1EQU4lMDdSY3olNjBHQWpDJTA3JTVFJTA3RUdLJTA2TVpJJTQwJTVCUVhYQVIlMDYlMUVfX18lMDclMDclMTIlNUJYJTVDJTVDJTQwIyM%3D
https://www.njiir.com/p/stress-measurements-using-oriented-core.html?url=IyNyWXklNUNPJTFGS0liY28lMUJYYiUwNWF%2BJTdDWXJQJTdCeSU2MHFsTm0lMUVlZkklMTklMTVMQSUxN0ZNWEclMDdFR0slMDZNRE9HR08lMDZNJTVFQVpMJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj
https://www.njiir.com/p/factors-controlling-stope-wall-behavior.html?url=IyMlNUVDRSUwNn4lN0MlMDYlN0RjaWxpJTYwbWVpJTdCJTA1WCUxOCUxMCUxOCUxOSUwNSUxRCUxMCUxMCUwNXhnJTA3aiUxMSU1Q2UlMUElMDclNUNNRiUwNlglNURJT01FJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj
https://www.njiir.com/p/stress-measurements-using-oriented-core.html?url=IyMlNUVDRSUwNn4lN0MlMDYlN0RjaWxpJTYwbWVpJTdCJTA1WCUxOCUxQSUxRiUwNSUxRCUxMCUxMCUwNXhnJTA3XyUxMSU1Q2UlMUElMDclNUNNRiUwNlglNURJT01FJTA3JTA3JTEyJTVCWCU1QyU1QyU0MCMj
![screencapture-njiir-p-stress-measurements-using-oriented-core-html-2019-05-19-14_10_09](https://user-images.githubusercontent.com/39649317/57978931-2b08bf80-7a40-11e9-85cf-91b69d0fede0.png)

i disabled nano adblocker to see visit link

![screencapture-njiir-p-stress-measurements-using-oriented-core-html-2019-05-19-14_09_40](https://user-images.githubusercontent.com/39649317/57978937-470c6100-7a40-11e9-8f9e-2382f4507025.png)
![screencapture-njiir-p-stress-measurements-using-oriented-core-html-2019-05-19-14_09_01](https://user-images.githubusercontent.com/39649317/57978945-6a371080-7a40-11e9-9134-de6bc86f9214.png)

**Comment by mapx-** [comment]
It was fixed days ago

**Comment by jspenguin2017** [comment]
Works fine for me. Closing as invalid as you did not fill the template. 
![image](https://user-images.githubusercontent.com/7283682/57985562-dc026080-7a26-11e9-8e08-fa66ba52e469.png)

**Comment by RaveN0X87** [comment]
@jspenguin2017 google chrome Version 74.0.3729.157 (Official Build) (64-bit) Nano Adblocker 1.0.0.110 nano defender 15.0.0.147
![Annotation 2019-05-21 214208](https://user-images.githubusercontent.com/39649317/58105897-71614880-7c11-11e9-926e-24dfd37a98bd.png)

**Comment by mapx-** [comment]
check the logger:

do you see
`njiir.com##+js(set-constant.js, safelink.adblock, false)`

?

If isnt there just update the lists or add the filter in your custom filters

**Comment by RaveN0X87** [comment]
@mapx-  how to update the lists?
![Annotation 2019-05-21 220243](https://user-images.githubusercontent.com/39649317/58107531-40cede00-7c14-11e9-9590-7cc0ef2ecefa.png)
![Annotation 2019-05-21 215657](https://user-images.githubusercontent.com/39649317/58107552-4af0dc80-7c14-11e9-946e-a4dea5b9f483.png)

**Comment by jspenguin2017** [comment]
Still works fine for me. You need to fill the template. 
![image](https://user-images.githubusercontent.com/7283682/58139435-d5771300-7bf7-11e9-88e5-ad027ad185f7.png)

**Comment by RaveN0X87** [comment]
@jspenguin2017 sorry for the problem 
i try uninstall and install again nano adblocker. fixed
i think because my filter
