### ISSUE TITLE
getintopc.com

### ISSUE THREAD

**Issue by PuluSatapathy** [jspenguin2017/uBlockProtector#1063]
website llink-
https://getintopc.com/

screenshot-
https://drive.google.com/open?id=1MJqugwtHzwvOSXTRQMDB4_bb4Y1EULnc

**Comment by jspenguin2017** [comment]
Seems to work fine for me. 
![image](https://user-images.githubusercontent.com/7283682/58528534-18a32a00-8194-11e9-844a-a193ce0afff1.png)
