### ISSUE TITLE
upload-earn.com

### ISSUE THREAD

**Issue by adctea** [jspenguin2017/uBlockProtector#1065]
### Screenshot of the web page (including address bar and extension icons) (required):
![Capture](https://user-images.githubusercontent.com/35037514/58747070-96f91800-8483-11e9-93da-121d6a322824.PNG)

### Screenshot of the console (press `F12` to bring up the console) (required):
![gtahn](https://user-images.githubusercontent.com/35037514/58747075-9d878f80-8483-11e9-8645-5c8a8c83c169.PNG)

### Environment (Required):

- Operating System and Version: Windows 7 x64 Ultimate
- Browser and Version: Chrome 73.0.3683.75 
- Adblocker and Version: nano adblocker 1.0.0.112

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/58752512-17604e80-846d-11e9-8faa-fd9141d7426c.png)

**Comment by adctea** [comment]
It starts when you complete the captcha and click on the next page @jspenguin2017

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/NanoMeow/QuickReports/issues/1323
