### ISSUE TITLE
tunein.com

### ISSUE THREAD

**Issue by mikhoul** [jspenguin2017/uBlockProtector#1069]
### Test link (required):
https://tunein.com/radio/ICI-Radio-Canada-Premire---Montral-951-s31098/

### Screenshot of the web page:

![image](https://user-images.githubusercontent.com/5678673/59880347-cf04c400-937a-11e9-9f5d-77bacf1d9bdd.png)

### Screenshot of the console (press `F12` to bring up the console) (required):

![image](https://user-images.githubusercontent.com/5678673/59880580-5a7e5500-937b-11e9-84bb-15a9659ab585.png)

### Explain what was not right (optional if obvious):
Player don't play until you deactivate Nano

### Environment (Required):

- Operating System and Version:  Win 7 64
- Browser and Version:  Latest Chromium
- Adblocker and Version:  Latest Nano

#### Your filter lists (Required):

![image](https://user-images.githubusercontent.com/5678673/59880774-e1333200-937b-11e9-8171-f6cd38c88a76.png)

Regards :octocat:

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/59890480-4bed6900-938e-11e9-85fa-d809dc977854.png)

**Comment by mikhoul** [comment]
You're right I've tried on my other computer to be sure and it work despite having the same profile so something is wrong on my main computer with my chromium installation.

I will have to see if something is corrupted in my profile.

Regards :octocat:
