### ISSUE TITLE
download.mokeedev.com

### ISSUE THREAD

**Issue by eromoe** [jspenguin2017/uBlockProtector#1070]
### Test link (required):

https://download.mokeedev.com/ido/file/MK71.2-ido-190228-HISTORY.zip/download

I have installed nano defender, but can't cope this site .

**Comment by jspenguin2017** [comment]
@okiehsch Current rules may need an update. Anti-adblock solution no longer seem to work. Also has empty ads placeholders. Not sure if the timer is validated on server side, if it's not, maybe also remove that.

**Comment by okiehsch** [comment]
I am open for suggestions.

**Comment by llacb47** [comment]
There is also admiral anti-adblock on that site.
```
!(function(o,n,t){t=o.createElement(n),o=o.getElementsByTagName(n)[0],t.async=1,t.src="https://plainplayground.com/v2/0/ctrV7kEPgWlSFSUWdTGTeTzuA9Pk4JK5lCN-edR-iks9Y40FCGabWGxsb-iEtxaiR9a",o.parentNode.insertBefore(t,o)})(document,"script"),(function(o,n){o[n]=o[n]||function(){(o[n].q=o[n].q||[]).push(arguments)}})(window,"admiral");!(function(n,e,r,t){function o(){if((function o(t){try{return(t=localStorage.getItem("v4ac1eiZr0"))&&0<t.split(",")[4]}catch(n){}return!1})()){var t=n[e].pubads();typeof t.setTargeting===r&&t.setTargeting("admiral-engaged","true")}}(t=n[e]=n[e]||{}).cmd=t.cmd||[],typeof t.pubads===r?o():typeof t.cmd.unshift===r?t.cmd.unshift(o):t.cmd.push(o)})(window,"googletag","function");;;;;
```
Have you guys ever considered adding a regex filter for admiral like https://github.com/bogachenko/fuckfuckadblock does? That list uses this filter:
`/^https:\/\/.*?\/v2\/0\/[a-zA-Z0-9_-]{30,}$/$third-party,script`

**Comment by jspenguin2017** [comment]
I'm worried that the RegExp filter will have too much false positives.

**Comment by okiehsch** [comment]
Disabling that does nothing as far as the specific anti adblock message of the site is concerned.

> Have you guys ever considered adding a regex filter for admiral like 

Will not be added to uBO-filters because many of the admiral domains are only annoayances as far as uBO is concerned.

**Comment by jspenguin2017** [comment]
Blocking the domain removes the soft anti-adblock.

**Comment by okiehsch** [comment]
What soft anti-adblock?
![image](https://user-images.githubusercontent.com/16838044/61425237-95da5800-a916-11e9-8892-cc5ece93f582.png)

**Comment by llacb47** [comment]
Huh, I reproduced it once...

**Comment by jspenguin2017** [comment]
How about 
````
download.mokeedev.com##+js(set-constant.js, admiral, noopFunc)
download.mokeedev.com##+js(set-constant.js, adVerified, false)
```

**Comment by llacb47** [comment]
Seems to work

**Comment by jspenguin2017** [comment]
As for the timer, it's using `Date`, which is kinda hard to boost.

**Comment by okiehsch** [comment]
I still don't get any admiral message.

`download.mokeedev.com##+js(set-constant.js, adVerified, false)`
works for me too will add it thanks.

**Comment by jspenguin2017** [comment]
Ah, actually just the second rule also works.

**Comment by okiehsch** [comment]
Added.

**Comment by jspenguin2017** [comment]
Confirmed the timer is validated on server side, can't skip timer.
