### ISSUE TITLE
tvguide.com

### ISSUE THREAD

**Issue by shirtjs** [jspenguin2017/uBlockProtector#1076]
### Explain what was not right (optional if obvious):
No TV listings load and the URL gets messed up.

### Reproduction steps (optional if trivial):
Go to https://www.tvguide.com/listings

### Environment (Required):

- Operating System and Version: Windows 10, 1903
- Browser and Version: Brave 69, Chromium 67
- Adblocker and Version: Nano Adblocker 1.0.0.123

#### Your filter lists (Required):

Default filters
https://i.imgur.com/xZpaSBc.png

#### Your other extensions (Required if you have any):
Tampermonkey, Proxy SwitchyOmega, Real-Debrid, EditThisCookie, Bitwarden, ShareX, ModHeader

### Add everything else that you believe to be useful below (optional):

This is caused by Nano Defender, not the adblocker.

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/62825276-7675ca00-bb66-11e9-91e4-957fbcf89b7c.png)

**Comment by llacb47** [comment]
Maybe A/B testing of Instart?

**Comment by shirtjs** [comment]
Yes that's what it looks like to me.

**Comment by jspenguin2017** [comment]
Still works fine for me.

**Comment by shirtjs** [comment]
Seems to have been fixed for me too.
