### ISSUE TITLE
4lpha.one

### ISSUE THREAD

**Issue by nik2143** [jspenguin2017/uBlockProtector#1077]
### Screenshot of the web page (including address bar and extension icons) (required):
![H62f9Fs - Imgur](https://user-images.githubusercontent.com/44278678/62905139-71cd3380-bd69-11e9-9b74-04a009a359fb.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![Cattura2](https://user-images.githubusercontent.com/44278678/62905149-80b3e600-bd69-11e9-9d33-3cb5f5f6a62a.PNG)

### Explain what was not right (optional if obvious):
When you try to download or upload something you get a popup who tell you to disable adblock

### Reproduction steps (optional if trivial):
1.Go to 4lpha.one
2.Press upload button

### Environment (Required):

- Operating System and Version: Windows 10 Ver, 1903
- Browser and Version: chrome latest version
- Adblocker and Version: Nano AdBlocker 1.0.0.123

#### Your filter lists (Required):
![Cattura](https://user-images.githubusercontent.com/44278678/62905118-56fabf00-bd69-11e9-8521-734d6317cf60.PNG)

#### Your other extensions (Required if you have any):
Nano Defender 15.0.0.160, Universal Bypass, Poper Blocker, Keepa, Buster: Captcha Solver for Humans 

### Add everything else that you believe to be useful below (optional):
In upload.js there is a check that is window.adsbygoogle.loaded
if return false make an alert with message and lock upload
For the download button there is a script that is this
`    <script>
		if (!window.adsbygoogle.loaded) {
			alert("Please turn adblock and reload the page. Servers ain't free");
		} else {
		 var str = window.location.pathname;
		 var split = str.split("/");
		 document.getElementById("dlButton").onclick=function() { window.location.href="//4lpha.one/files/download/" + split[2]; };
		}
		 </script>
`

**Comment by llacb47** [comment]
`4lpha.one##+js(set-constant, adsbygoogle.loaded, true)`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
