### ISSUE TITLE
kachelmannwetter.com

### ISSUE THREAD

**Issue by cobrafast** [jspenguin2017/uBlockProtector#1078]
### Screenshot of the web page (including address bar and extension icons) (required):

https://x.ezl.re/20190814_143909.png

### Screenshot of the console (press `F12` to bring up the console) (required):

https://x.ezl.re/20190814_144026.png

### Explain what was not right (optional if obvious):
At first, red boxes with the adblockuser text pop up, then one gets redirected to the adblockuser page.

### Reproduction steps (optional if trivial):
—

### Environment (Required):

- Operating System and Version: Windows 10 1903 64-bit
- Browser and Version: Firefox 68.0.1 64-bit
- Adblocker and Version: uBlock Origin 1.21.2

#### Your filter lists (Required):

https://x.ezl.re/20190814_144238.png

#### Your custom filters (Required if you have any): 
PiHole

#### Your other extensions (Required if you have any):
Absolute Enable Right Click & Copy, cookies.txt, Copy ShortURL, Dark Reader, Decentraleyes, Firefox Mulit-Account Containers, Geschlossenen Tab wiederherstellen, Google search link fix, Google Unlocked, HTTPS Everywhere, Imagus, Nano Defender, Open With, SoundFixer, Tampermonkey, Textarea Tabbing, uBlock Origin, YouTube Repeat Button, CSS Reloader

### Add everything else that you believe to be useful below (optional):
Whitelisting like so https://x.ezl.re/20190814_143036.png seems to restore a functional website while still not displaying any ads.

**Comment by llacb47** [comment]
I can reproduce

**Comment by cobrafast** [comment]
After some trial and error, and contrary to my previous remark about whitelisting, it seems to be enough to add a local green box to "mairdumont.com" and "md-nx.com" only, as a workaround.

**Comment by cobrafast** [comment]
Thank you @mapx-, that worked. 😃

**Comment by cobrafast** [comment]
The problem appears to be back.

**Comment by jspenguin2017** [comment]
Can't reproduce.

**Comment by cobrafast** [comment]
Seems to have been bouncing between working and not working the past couple days, but now seems to be consistently blocked again (i.e. the problem is back).
Perhaps some servers served old scripts while they rolled out a new version? Would appreciate if you could check again.

**Comment by jspenguin2017** [comment]
It's still working for me.

**Comment by cobrafast** [comment]
Hmm, there's also a PiHole running in my current network. Maybe that has something to do with it.

**Comment by jspenguin2017** [comment]
Nano Defender does not support PiHole.

**Comment by cobrafast** [comment]
The following userscript prevents the most annoying part: the redirection to the adblock info page.
However, some red adblock warning boxes remain:

```
(function() {
    // old workaround
    document.getElementById('paywall-account-type')
      .setAttribute('data-value', 'payaccount');

    // new workaround
    var stopAdblock = document.createElement("div");
    stopAdblock.setAttribute("id", "stop-redirect");
    stopAdblock.setAttribute("data-value", "true");
    document.body.prepend(stopAdblock);
})();
```

**Comment by jspenguin2017** [comment]
I can't reproduce the issue on standard setup.
