### ISSUE TITLE
cyberspace.world

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1079]
### Test link (required):
https://www.cyberspace.world/2019/07/adobe-master-collection-cc-2019-50.html

### Screenshot of the web page (including address bar and extension icons) (required):
![2019-08-18_075916](https://user-images.githubusercontent.com/2828165/63220749-61182580-c18e-11e9-8958-4568917cd2c1.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2019-08-18_075938](https://user-images.githubusercontent.com/2828165/63220751-670e0680-c18e-11e9-9628-19f966ad56f6.png)

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.123+Nano Defender 15.0.0.160

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by jspenguin2017** [comment]
Works fine with latest filters.
