### ISSUE TITLE
mysterious-dev.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1080]
### Test link (required):
https://www.mysterious-dev.com/2019/08/download-miracle-thunder-282-crack-fix.html

### Screenshot of the web page (including address bar and extension icons) (required):
![2019-08-17_005705](https://user-images.githubusercontent.com/2828165/63220800-0fbc6600-c18f-11e9-9ac3-2f0b1cb3bd29.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2019-08-17_005730](https://user-images.githubusercontent.com/2828165/63220801-164add80-c18f-11e9-8c6c-4b9939461a88.png)

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 76.0.3809.100 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.123+Nano Defender 15.0.0.160

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by mapx-** [comment]
fixed
