### ISSUE TITLE
How to verify if my Nano Defender is configured correctly?

### ISSUE THREAD

**Issue by onmyouji** [jspenguin2017/uBlockProtector#1081]
Hi all,

I use uBlock Origin and Nano Defender, and I already followed the extra installation steps. Is there any way to verify if my Nano Defender is working and configured correctly?

**Comment by llacb47** [comment]
Go to a website and open the console

**Comment by jspenguin2017** [comment]
If you followed the steps you should be fine. You can also go test it on demo pages like `https://fuckadblock.sitexw.fr/`.

**Comment by onmyouji** [comment]
Thanks!
