### ISSUE TITLE
popsci.com

### ISSUE THREAD

**Issue by nitrocode** [jspenguin2017/uBlockProtector#1082]
### Test link (required):
https://www.popsci.com/best-places-to-live-in-america-in-2100-ad-0/

### Screenshot of the web page (including address bar and extension icons) (required):

![ff-popsci-block](https://user-images.githubusercontent.com/7775707/65687639-b3731e80-e037-11e9-9ba8-8f5f00001be7.PNG)

### Screenshot of the console (press `F12` to bring up the console) (required):

![ff-console](https://user-images.githubusercontent.com/7775707/65687647-b837d280-e037-11e9-93db-a1303066b09c.PNG)

### Environment (Required):

- Operating System and Version: windows 10
- Browser and Version: ff 69.0.1
- Adblocker and Version: ublockorigin

#### Your filter lists (Required):

default

#### Your custom filters (Required if you have any):

none

#### Your other extensions (Required if you have any):

nanodefender
ublockorigin

**Comment by mapx-** [comment]
I get only a blank page due to taboola blocking
