### ISSUE TITLE
techsighter.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1083]
### Test link (required):
https://www.techsighter.com/threads/udemy-the-complete-ebay-dropshipping-course-step-by-step-in-2019-course-coupon.467/

### Screenshot of the web page (including address bar and extension icons) (required):
![2019-09-29_193036](https://user-images.githubusercontent.com/2828165/65836197-04ad3780-e2f0-11e9-8d49-363f2c85e3b3.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2019-09-29_193055](https://user-images.githubusercontent.com/2828165/65836201-0a0a8200-e2f0-11e9-883e-0e99862d2fe0.png)

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.127+Nano Defender 15.0.0.168

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by mapx-** [comment]
fixed
