### ISSUE TITLE
arabic.cnn.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1085]
### Test link (required):
https://arabic.cnn.com/middle-east/article/2019/10/04/bassem-yousif-amr-adeeb-jordanians-released-demonstrations

### Screenshot of the web page (including address bar and extension icons) (required):
![2019-10-04_093346](https://user-images.githubusercontent.com/2828165/66189623-7687d700-e68a-11e9-9ccb-3a4c2bb1d087.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2019-10-04_093158](https://user-images.githubusercontent.com/2828165/66189643-80113f00-e68a-11e9-841e-3cb76773a34b.png)

### Explain what was not right (optional if obvious):
All Videos Not working when Nano Adblocker enabled

Nano enabled
![2019-10-04_094038](https://user-images.githubusercontent.com/2828165/66189997-51479880-e68b-11e9-8678-0c9d525ae403.png)

Nano adblocker disabled
![2019-10-04_093018](https://user-images.githubusercontent.com/2828165/66190062-73d9b180-e68b-11e9-8991-1ddc017c1cfa.png)

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 77.0.3865.90 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.127+Nano Defender 15.0.0.168

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by mapx-** [comment]
fixed
