### ISSUE TITLE
Filtering console log messages - readme

### ISSUE THREAD

**Issue by pavelloz** [jspenguin2017/uBlockProtector#1088]
Readme instruction:

![image](https://user-images.githubusercontent.com/546845/66873403-a5fee380-efa8-11e9-8273-dafd8a504ac9.png)

Reality:
![image](https://user-images.githubusercontent.com/546845/66873427-b0b97880-efa8-11e9-825c-b1cec5de1754.png)
![image](https://user-images.githubusercontent.com/546845/66873438-b8791d00-efa8-11e9-8461-3805ecd9039f.png)

Browser: Firefox 69+

**Comment by jspenguin2017** [comment]
I don't maintain the Firefox build. This definitely works in Chrome, for Firefox-specific issues, report to https://github.com/LiCybora/NanoDefenderFirefox/issues

**Comment by pavelloz** [comment]
Do you think firefox extension codebase will be able to fix readme to help firefox users how to filter out log messages?

**Comment by LiCybora** [comment]
If you install it from AMO, you can turn off the console until browser session restart.

![image](https://user-images.githubusercontent.com/40160522/66934327-e0ca4f80-f06c-11e9-8964-e6c441e98444.png)

Just uncheck it and all consoles are gone.

> Do you think firefox extension codebase will be able to fix readme to help firefox users how to filter out log messages?

I do have a readme with screenshot showing above image, but I may better instruct for that. However,  the one your image pointing to is homepage and I don't even have one.

**Comment by pavelloz** [comment]
Image that i pasted is from webpage that you can access by clicking "Home Page" from your screenshot :)

I just assumed that since it is under https://jspenguin2017.github.io/uBlockProtector/ - this will be the best place to report inconsistencies (i forgot chrome is the browser king nowadays and assumed instruction should work on Fx)
