### ISSUE TITLE
NSFW! 21roles.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1090]
### Test link (required):
https://21roles.com/

### Screenshot of the web page (including address bar and extension icons) (required):
![2019-10-19_082908](https://user-images.githubusercontent.com/2828165/67138963-de255100-f24a-11e9-9dbb-03ad6d7c8739.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2019-10-19_082929](https://user-images.githubusercontent.com/2828165/67138964-e4b3c880-f24a-11e9-9ad4-7b585d445944.png)

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 77.0.3865.120 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.128+Nano Defender 15.0.0.168

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by jspenguin2017** [comment]
I can't reproduce.

**Comment by llacb47** [comment]
Maybe caused by the "anti-virus" that is logged in the console?
