### ISSUE TITLE
gsmcracktools.blogspot.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1091]
### Test link (required):
https://gsmcracktools.blogspot.com/2019/11/huawei-frp-tool-pro-version-one-click.html

### Screenshot of the web page (including address bar and extension icons) (required):
![2019-11-03_075445](https://user-images.githubusercontent.com/2828165/68081009-786ec280-fe0f-11e9-91a0-96dce4f5df65.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2019-11-03_075510](https://user-images.githubusercontent.com/2828165/68081010-7c024980-fe0f-11e9-8b43-a4aa6f62b373.png)

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 78.0.3904.87 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.128+Nano Defender 15.0.0.168

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/68086633-f2e91380-fe0a-11e9-8e92-aaa79d31195c.png)
