### ISSUE TITLE
nulledpremium.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1092]
### Test link (required):
https://nulledpremium.com/

### Screenshot of the web page (including address bar and extension icons) (required):
![2019-11-10_230832](https://user-images.githubusercontent.com/2828165/68550836-642e5500-040f-11ea-836b-d14377551164.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2019-11-10_230931](https://user-images.githubusercontent.com/2828165/68550838-67294580-040f-11ea-9117-dd0e0357af00.png)

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 78.0.3904.87 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.128+Nano Defender 15.0.0.168

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by mapx-** [comment]
You should update all the lists, it was fixed recently

**Comment by jspenguin2017** [comment]
I was only able to reproduce ads placeholders, fixed in Placeholder Buster list.
