### ISSUE TITLE
lapresse.ca

### ISSUE THREAD

**Issue by mikhoul** [jspenguin2017/uBlockProtector#1093]
### Screenshot of the web page (including address bar and extension icons) (required):

![image](https://user-images.githubusercontent.com/5678673/68863917-43d7f200-06be-11ea-9387-e2ef884e9b3f.png)

### Screenshot of the console (press `F12` to bring up the console) (required):

![image](https://user-images.githubusercontent.com/5678673/68864006-65d17480-06be-11ea-92e5-915a9f0f11d3.png)

### Environment (Required):

- Operating System and Version:  Win 7 64bit
- Browser and Version: Brave
Version 1.0.0 Chromium: 78.0.3904.97 (Build officiel) (32 bits)
- Adblocker and Version:  Latest version

#### Your filter lists (Required):

![image](https://user-images.githubusercontent.com/5678673/68864192-b2b54b00-06be-11ea-88d3-daa30ae09aef.png)

**Comment by jspenguin2017** [comment]
I can't reproduce.

**Comment by mikhoul** [comment]
Sorry it was a bug with Brave Shield, that activated the Brave Shield again after disabling it so it triggered the error message.
