### ISSUE TITLE
lapresse.ca

### ISSUE THREAD

**Issue by mikhoul** [jspenguin2017/uBlockProtector#1094]
### Screenshot of the web page (including address bar and extension icons) (required):

![image](https://user-images.githubusercontent.com/5678673/69883298-79c1cc80-12a1-11ea-80a8-93f8a15e34bd.png)

### Screenshot of the console (press `F12` to bring up the console) (required):

![image](https://user-images.githubusercontent.com/5678673/69883319-9827c800-12a1-11ea-9771-312a043eee45.png)

### Environment (Required):

Operating System and Version: Win 7 64bit
Browser and Version: Brave
Version 1.0.0 Chromium: 78.0.3904.97 (Build officiel) (32 bits)
Adblocker and Version: Latest version

#### Your filter lists (Required):

![image](https://user-images.githubusercontent.com/5678673/69883338-b2fa3c80-12a1-11ea-9199-3663ff304570.png)

**Comment by jspenguin2017** [comment]
Can't reproduce. You're on a non-standard setup, try on default settings.
