### ISSUE TITLE
onlystream.tv

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1095]
### Test link (required):
**User Control panel**
https://onlystream.tv/videos

### Screenshot of the web page (including address bar and extension icons) (required):
**Hidden Menu**
![2019-12-04_101426](https://user-images.githubusercontent.com/2828165/70125474-810d1f80-167f-11ea-9545-d97f2bf550f1.png)

**Upload not Work**
![2019-12-04_101140](https://user-images.githubusercontent.com/2828165/70125502-908c6880-167f-11ea-9e01-291f74092ecb.png)

**Search Videos Not work**
![2019-12-04_101052](https://user-images.githubusercontent.com/2828165/70125526-9eda8480-167f-11ea-8437-54bd66bf66d0.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2019-12-04_101116](https://user-images.githubusercontent.com/2828165/70125556-b154be00-167f-11ea-87db-f21ac878aaef.png)

### Explain what was not right (optional if obvious):
Nano Adblocker Break Website 

**username password to test**
User: test2020
Pass: test2020

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 78.0.3904.108 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.130+Nano Defender 15.0.0.170

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by mapx-** [comment]
I did a test of uploading, all fine on my end.
The search working fine, the menu is hidden even disabling uBo.
Tested in firefox.

**Comment by titosalah** [comment]
@mapx-  thanks bro try after search play video .. not work when adblocker enabled

**Comment by mapx-** [comment]
search "telenoche" is working (getting my video) then play it => running fine.

You should start by keeping only the default lists, test again .. then adding one by one the other custom lists to get the "bad" one

**Comment by jspenguin2017** [comment]
Works fine on default configuration.
