### ISSUE TITLE
[feature] console messages

### ISSUE THREAD

**Issue by zdm** [jspenguin2017/uBlockProtector#1098]
Hi.
Thank you for a great product.
I am developer and constantly use browser console in my work. It is really annoying to see nano messages there million times per day.
Could you please add an option to turn them off?

**Comment by jspenguin2017** [comment]
https://jspenguin2017.github.io/uBlockProtector/#common-questions-and-issues

**Comment by zdm** [comment]
I can enable it if I will have issues.

**Comment by jspenguin2017** [comment]
It's not possible to implement with current browser API. You'll have to fork.

**Comment by zdm** [comment]
Maybe you can remove console logs for domains, where ad blocker is disabled?

**Comment by jspenguin2017** [comment]
As I said before, it's not possible to configure content scripts dynamically with current extension APIs of Chromium-based browsers.
