### ISSUE TITLE
shadowhackr.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1101]
### Test link (required):
https://www.shadowhackr.com/2020/01/open-port-vpn.html

### Screenshot of the web page (including address bar and extension icons) (required):
![2020-01-30_193449](https://user-images.githubusercontent.com/2828165/73474883-e0de2900-4397-11ea-92d3-c08b4cd9921b.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2020-01-30_193512](https://user-images.githubusercontent.com/2828165/73474894-e76ca080-4397-11ea-8e6a-199048279e6e.png)

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 79.0.3945.130  (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.135+Nano Defender 15.0.0.180

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by mapx-** [comment]
fixed
