### ISSUE TITLE
upload-earn.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1105]
### Test link (required):
https://upload-earn.com/NmVWsKqPQa

### Screenshot of the web page (including address bar and extension icons) (required):
![2020-02-05_090913](https://user-images.githubusercontent.com/2828165/74010764-e25ab300-498e-11ea-99d6-3c501e47eb0e.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2020-02-07_094620](https://user-images.githubusercontent.com/2828165/74010770-e981c100-498e-11ea-95e6-ff1d9c9d2291.png)

### Explain what was not right (optional if obvious):
**You can close turnoff adblock message before complete capatcha and click next page
but when countdown from 19 seconds to zero you must turnoff  adblocker**

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 79.0.3945.130  (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.135+Nano Defender 15.0.0.180

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by jspenguin2017** [comment]
Can't reproduce.

**Comment by titosalah** [comment]
@jspenguin2017  work with you 
and problem from filters ????

**Comment by jspenguin2017** [comment]
It works fine on default settings.
