### ISSUE TITLE
uploadship.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#1106]
### Test link (required):
https://www.uploadship.com/251b72730db4186c

### Screenshot of the web page (including address bar and extension icons) (required):
**When Nano Adblocker Active**
![2020-02-19_074904](https://user-images.githubusercontent.com/2828165/74806001-7a409100-52ed-11ea-8d60-8dbcf365e88c.png)

**Nano  Adblocker turned off** 
![FireShot Capture 010 - GSE SMART IPTV v7 4  Unlocked apk - UploadShip - www uploadship com](https://user-images.githubusercontent.com/2828165/74806041-8cbaca80-52ed-11ea-9106-a075b6e48975.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2020-02-19_075102](https://user-images.githubusercontent.com/2828165/74806058-95ab9c00-52ed-11ea-93cc-b2581ad41a14.png)

**Environment (Required):**
Operating System and Version: WIN 7 64BIT
Browser and Version: Chrome Version 79.0.3945.130  (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.135+Nano Defender 15.0.0.180

**Your filter lists (Required):**
Built-in (10/11)
Nano Defender Integration​​​​​
Nano filters​​​​​
Nano filters – Annoyance
Nano filters – Whitelist​​​​​
uBlock filters​​​​​
uBlock filters – Annoyances​​​​​
uBlock filters – Badware risks​​​​​
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak

**Ads (2/4)**
Adblock Warning Removal List​​​​​
EasyList​​​​​

**Privacy (1/3)**
EasyPrivacy​​​​​

**Malware domains (2/4)**
Malware Domain List​​​​​
Malware domains​​​​​

**Annoyances (3/5)**
Adguard’s Annoyance List​​​​​
Fanboy’s Annoyance List​​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​​​​​
Fanboy’s Cookiemonster List​​​​​​​​​
Fanboy’s Social Blocking List​​​​​

Multipurpose (2/5)
NoCoin Filter List
Peter Lowe’s Ad and tracking server list

**Regions, languages (3/36)**
ARA: Liste AR
IRN: Adblock-Iran
RUS: RU AdList

**Comment by jspenguin2017** [comment]
Could not reproduce breakage, has some ads though: https://github.com/NanoMeow/QuickReports/issues/2280
