### ISSUE TITLE
tomshw.it

### ISSUE THREAD

**Issue by gabri25ele** [jspenguin2017/uBlockProtector#1112]
Test link (required):
https://www.tomshw.it/hardware/raspberry-pi-4-puo-diventare-un-centro-multimediale-gratuito-per-la-tv-ecco-come/

Screenshot of the web page (including address bar and extension icons) (required):
![sshot-1](https://user-images.githubusercontent.com/33927879/78037826-56508080-736c-11ea-864d-76cc57b44a29.png)

Screenshot of the console (press F12 to bring up the console) (required):
![sshot-2](https://user-images.githubusercontent.com/33927879/78037991-8f88f080-736c-11ea-83de-2b97d85731a1.png)

Environment (Required):
Operating System and Version: WIN 10 64-bit
Browser and Version: Firefox 73.0.1 64-bit
Adblocker and Version: ublock origin 1.25.0 + Nano Defender 15.0.0.180

Your filter lists (Required):
uBlock filters​​​​​
uBlock filters – Badware risks​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​

Adblock Warning Removal​​​​​
​Fanboy’s Enhanced Tracking List​
Malware Domain List​​​​​1.104 usati su 1.104​​
Malware domains​
​​​​AdGuard Annoyances​
AdGuard Social Media​
Fanboy’s Annoyance​
uBlock filters – Annoyances​​​​​
​​ITA: EasyList Italy​
AdGuard Annoyances filter​​
​​​AdGuard Base filter​​
​​​AdGuard Social Media filter​​
AdGuard Tracking Protection filter​​
​​​EasyPrivacy​​
Nano Defender Integration​​
Nano Filters​​
Nano Filters - Whitelist​​
NoCoin Filter List​​
​​​X Files: NoFacebookAds​​

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/commit/6a33420e23d5d132abe2780836d7baafe6a6b647
