### ISSUE TITLE
fifaultimateteam.it

### ISSUE THREAD

**Issue by gabri25ele** [jspenguin2017/uBlockProtector#1113]
Test link (required):
https://www.fifaultimateteam.it/

Screenshot of the web page (including address bar and extension icons) (required):
![sshot-1](https://user-images.githubusercontent.com/33927879/78367630-ad4f9300-75c2-11ea-960b-a380fe4374e0.png)

Screenshot of the console (press F12 to bring up the console) (required):
![sshot-2](https://user-images.githubusercontent.com/33927879/78367700-ce17e880-75c2-11ea-91b1-a0382ce2699f.png)

Environment (Required):
Operating System and Version: WIN 10 64-bit
Browser and Version: Firefox 73.0.1 64-bit
Adblocker and Version: ublock origin 1.25.0 + Nano Defender 15.0.0.180

Your filter lists (Required):
uBlock filters​​​​​
uBlock filters – Badware risks​
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse​​​​​
uBlock filters – Unbreak​​​​

Adblock Warning Removal​​​​​
​Fanboy’s Enhanced Tracking List​
Malware Domain List​​​​​1.104 usati su 1.104​​
Malware domains​
​​​​AdGuard Annoyances​
AdGuard Social Media​
Fanboy’s Annoyance​
uBlock filters – Annoyances​​​​​
​​ITA: EasyList Italy​
AdGuard Annoyances filter​​
​​​AdGuard Base filter​​
​​​AdGuard Social Media filter​​
AdGuard Tracking Protection filter​​
​​​EasyPrivacy​​
Nano Defender Integration​​
Nano Filters​​
Nano Filters - Whitelist​​
NoCoin Filter List​​
​​​X Files: NoFacebookAds​​

**Comment by llacb47** [comment]
`fifaultimateteam.it##+js(aopr, AiCookies)`
