### ISSUE TITLE
knights-table.net

### ISSUE THREAD

**Issue by ExtendLord** [jspenguin2017/uBlockProtector#1114]
### Test link (required):
https://knights-table.net/

### Screenshot of the web page (including address bar and extension icons) (required):
![image](https://user-images.githubusercontent.com/26222159/80548281-3fc93380-89c3-11ea-8d4b-4f42ce909913.png)

### Environment (Required):

- Operating System and Version: Windows 10 1909
- Browser and Version: Chromium 81.0.4044.129 (64-bit)
- Adblocker and Version: uBlock Origin v1.26.0

#### Your filter lists (Required):
![image](https://user-images.githubusercontent.com/26222159/80548308-51124000-89c3-11ea-9c15-571b552aa4c6.png)

#### Your other extensions (Required if you have any):
![image](https://user-images.githubusercontent.com/26222159/80548254-3049ea80-89c3-11ea-9bae-5d36bc0e4ae8.png)

**Comment by jspenguin2017** [comment]
@okiehsch Hard anti-adblock. Comes up after a refresh.

**Comment by okiehsch** [comment]
Fixed.
