### ISSUE TITLE
[Feature] Add a way to make some rules optional

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#1116]
Add a way to make some rules optional, at the cost of possible race conditions. This is suitable for annoyance and maybe experimental rules. 

For example, there are a large amount of websites that have the same anti-select and anti-right-click annoyance: 
`https://publicwww.com/websites/%22wpcp_disable_selection%22+%22wpcp_disable_Right_Click%22/`

Related: https://github.com/uBlockOrigin/uAssets/issues/7468

**Comment by jspenguin2017** [comment]
Or maybe we could allow generic script snippet injection for privileged filters.

**Comment by jspenguin2017** [comment]
Or maybe it would be better to just allow generic script snippet injection for privileged filters?

**Comment by krystian3w** [comment]
`*##+js(ra, class|id)`

maybe scriplets need exclude.

**Comment by jspenguin2017** [comment]
Oh, right. Script snippet injections can already be generic. I totally forgot that. 
I think I just need to add a script snippet that can abort script by ID.

**Comment by kulfoon** [comment]
> I totally forgot that ...

Just like me and perhaps 100 other people as well, if something is never used it's being forgotten - I didn't found a single `*##` filter in any uBO / AdGuard list.

Also the WIKI seems to be outdated / confusing, as usual, coz it still says that:
> Generic `+js` filters are ignored: those filters must be specific, i.e. they must apply to specific hostnames, e.g. `example.com##+js(nobab)`

Perhaps something changed and was mentioned in some old and forgotten commit / release description or at the bottom of the Pacific Ocean.

`+` for https://github.com/jspenguin2017/uBlockProtector/issues/1116#issuecomment-635156684 for finding out that we can use generic js, however, his soultions can be fine-tuned:

As for `:has-text(/[\w\W]{286,303}/)`  is kinda weird
- the starting range is bad, it must be not bigger than 246 so we get ==> `:has-text(/[\w\W]{246,303}/)`
- the closing range is redundant so we get ==> `:has-text(/[\w\W]{246}/)`
- further it can be converted to [a dedicated solution](https://github.com/gorhill/uBlock/wiki/Procedural-cosmetic-filters#subjectmin-text-lengthn) so we get ==> `:min-text-length(246)`
- further it can be converted to a single chain regex so we get ==> 
`*##^head style:has-text(/\.unselectable[\w\W]{246}/)`

As for: `*##^script[id^="wpcp_disable_"], script[id^="wpcp_css_disable_"]` seems ok, if one is looking for an alternative, can check this one, a shorter and wider (but risky? doesn't seem so but it's better to make sure): `*##^script[id^="wpcp_"][id*="_disable_"]`

**Comment by jspenguin2017** [comment]
It's not documented in the wiki probably to deter people from using it. It's a really big hammer and things can go wrong if used improperly. 

As for the rules, I'll do something different. Looks like this works: 
```
*##+js(nano-abort-inline-scripts-by-id, /^wpcp_(?:(?:css_)?disable_selection|disable_Right_Click)$/)
*##style:has-text(.unselectable):remove()
```

I do need a whitelist system though, as the second rule has quite a high chance to break things. I'm also considering a specific script snippet for this issue.

**Comment by jspenguin2017** [comment]
After tweaking the rules, I think this should work: 
```
*##+js(nano-abort-inline-scripts-by-id, /^wpcp_disable_(?:selection|Right_Click)$/)
*##script#wpcp_css_disable_selection:xpath(preceding-sibling::style[contains(text(), ".unselectable")]):remove()
```

**Comment by jspenguin2017** [comment]
Either way, let's continue the discussion in the NanoFilters repository.

**Comment by jspenguin2017** [comment]
Duplicate of: https://github.com/NanoAdblocker/NanoFilters/issues/510

**Comment by krystian3w** [comment]
> is kinda weird

this is enter charactes, sometimes is not compressed into one line.

`303` if someone use Windows Server (<kbd>CR</kbd><kbd>LF</kbd>) and if available in `view-source`.

**Comment by kulfoon** [comment]
I'm aware, but in your regex you use ranges wrong way to the actual case (which I realised just now by the way), in such broken regex the closing range is redundant, try this to actually make the closing range working as intended and not being redundant: `:has-text(/^[\w\W]{259,303}$/)`
