### ISSUE TITLE
[BUG] uBlockProtector Prevent iCloud Notes from Loading!

### ISSUE THREAD

**Issue by Y0usefmahdi** [jspenguin2017/uBlockProtector#1119]
### Environment (Required):

- Operating System and Version: MacOS Mojave 10.14.6
- Browser and Version:  Google Chrome 81.0.4044.138 (Official Build) (64-bit)
- Adblocker and Version:  uBlock Origin 1.27.10

**Comment by llacb47** [comment]
Can you fill in the template?

**Comment by jspenguin2017** [comment]
You need to fill the template.

**Comment by Y0usefmahdi** [comment]
> You need to fill the template. Specifically, I need a test link and screenshots.

What Test link mean?

**Comment by jspenguin2017** [comment]
A link where I can test this. I can't fix bugs that I can't reproduce.

**Comment by Y0usefmahdi** [comment]
About screenshot:

[with uBlock](https://i.imgur.com/1mM62sU.png)
[Without uBlock](https://i.imgur.com/JlozYGf.png)

**Comment by jspenguin2017** [comment]
Works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/84092450-9b201580-a9b4-11ea-91c7-28c459f419fe.png)

**Comment by llacb47** [comment]
There is no issue on default filters. You must allow `icloud.com/system/ct-fonts/*` so maybe try that.
