### ISSUE TITLE
aternos.org

### ISSUE THREAD

**Issue by llacb47** [jspenguin2017/uBlockProtector#1121]
### Test link (required):

https://aternos.org/server/

Test credentials sent on Slack

### Screenshot of the web page (including address bar and extension icons) (required):

![image](https://user-images.githubusercontent.com/16567977/87988534-7f795600-caae-11ea-9407-d7f16545b258.png)

### Screenshot of the console (press `F12` to bring up the console) (required):

![image](https://user-images.githubusercontent.com/16567977/87988570-90c26280-caae-11ea-821b-b1095e8c7116.png)

### Explain what was not right (optional if obvious):
Anti-adblock

### Reproduction steps (optional if trivial):
Login to the website, visit the page.

### Environment (Required):

- Operating System and Version: N/A
- Browser and Version: N/A
- Adblocker and Version: N/A
- Nano Defender Version: N/A

#### Your filter lists (Required):

N/A

#### Your custom filters (Required if you have any):
N/A

#### Your other extensions (Required if you have any):
N/A

### Add everything else that you believe to be useful below (optional):

This is more of a request than an issue report. I wrote a userscript to deal with anti-adblock on this site. Since this site quickly patches the fixes added to uAssets/Adguard, I think the fix should be implemented in a similar way that you dealt with this issue: https://github.com/jspenguin2017/uBlockProtector/issues/478#issuecomment-330270213. (heavily obfuscated etc.) This fix also would require a couple of filters to be added to Nano Defender Integration list. I will DM you those filters on Slack as well.

Let me know if this is something you'd like to implement. If not, I totally understand, it may be more effort than it's worth.

Reference links: 
```
https://github.com/uBlockOrigin/uAssets/issues?q=aternos
https://github.com/AdguardTeam/AdguardFilters/issues?q=aternos
```

**Comment by jspenguin2017** [comment]
The infrastructure for proprietary solutions (the previous solution for the issue you linked) was teared down a long time ago, and I have no plan in bringing it back. Currently, solutions for extra sticky sites are in a private extension (unlisted and link not shared). 

---

Main issue: https://github.com/NanoMeow/QuickReports/issues/1643
