### ISSUE TITLE
hotslogs.com

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#121]
https://github.com/reek/anti-adblock-killer/issues/2988

```JavaScript
a.win.MonkeyBroker = {};
a.noAccess("MonkeyBroker.regSlotsMap");
```

**Comment by uBlock-user** [comment]
Present solution works as expected FYI

**Comment by X01X012013** [comment]
Good, added to Script. We'll see how long this lasts.

**Comment by simonvanderveldt** [comment]
@jspenguin2017 @uBlock-user is this still working for you? The hotslogs.com works for me, but any other page like https://www.hotslogs.com/Sitewide/HeroDetails redirects me to the adblock detected page

**Comment by jspenguin2017** [comment]
This should fix it. The call to `a.noAccess` was bad.

**Comment by simonvanderveldt** [comment]
It works, thanks!
