### ISSUE TITLE
gry.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#132]
do we have detection for https://getadmiral.com/

https://github.com/uBlockOrigin/uAssets/issues/343

test link:

http://www.gry.pl/gra/1001-arabian-nights-7

**Comment by X01X012013** [comment]
Hum... we don't have a generic Admiral killer, usually we use `$third-party` to kill the bootstrapper. I'll have a look.

**Comment by xxcriticxx** [comment]
Thx

**Comment by uBlock-user** [comment]
It's a third-party script, just block the domain from where it's coming or block all third-party scripts and make exceptions wherever needed.

**Comment by X01X012013** [comment]
Fixed by List.

**Comment by adreporter** [comment]
@jspenguin2017 
Test link: http://www.gry.pl/gra/agar

Screenshot of the web page:
<img width="644" alt="dfwefe" src="https://user-images.githubusercontent.com/18214146/27017659-656f1248-4f2a-11e7-8a09-be2c2b703957.PNG">

Screenshot of the console:
<img width="960" alt="przechwytywaniessf" src="https://user-images.githubusercontent.com/18214146/27017739-feb99dc4-4f2a-11e7-8527-8f0c591830aa.PNG">

You have to scroll down a little bit to see the antiadblock message.

**Comment by jspenguin2017** [comment]
@adreporter I don't see it. Scrolled to the bottom. 
![image](https://user-images.githubusercontent.com/7283682/27017909-71f7da22-4ee9-11e7-920a-81ce0fa5be81.png)

**Comment by adreporter** [comment]
@jspenguin2017 For me, the antiadblock message is just above the comments.

**Comment by adreporter** [comment]
@jspenguin2017 I see this:
<img width="960" alt="sasa" src="https://user-images.githubusercontent.com/18214146/27018084-f42addd4-4f2d-11e7-8377-9ebae0b00fb4.PNG">

**Comment by jspenguin2017** [comment]
@adreporter Huh, it came up the second time...
