### ISSUE TITLE
nbc.com

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#143]
http://www.nbc.com/

https://github.com/reek/anti-adblock-killer/issues/2952

**Comment by uBlock-user** [comment]
They also have a Geo-Lock which comes after anti adblock check FYI.

**Comment by jspenguin2017** [comment]
Fixed. Thanks for the solution.

**Comment by uBlock-user** [comment]
Ofcourse it's not. Also anyone with a US ISP based IP should be able to access it.

**Comment by jspenguin2017** [comment]
Looks good. Closing.

**Comment by lain566** [comment]
@jspenguin2017 I think it's broken, video doesn't load or play

Test links
https://www.nbc.com/emerald-city/video/they-came-first/3463424
https://www.nbc.com/grimm/video/zerstorer-shrugged/3485869
https://www.nbc.com/the-blacklist-redemption/video/whitehall/3493073
https://www.nbc.com/dateline/video/the-target/3580147

**Comment by jspenguin2017** [comment]
I'll disable the rule for now.

**Comment by jspenguin2017** [comment]
Breaking `mps` seems to break login button, need a slightly more complex patching logic. This white list works for now (just temporary until we fix the other problem): 
```
@@||pubads.g.doubleclick.net/gampad/ad?$domain=nbc.com
@@||tpc.googlesyndication.com/pagead/imgad?id=$domain=nbc.com
```

Also, the video player refuse to load real content until ads from FreeWheel is loaded. Need to do a loopback somewhere to get pass that.

**Comment by uBlock-user** [comment]
`nbc.com##script:inject(abort-on-property-read.js, mps._ab)`

Works for me, I don't see any anti adblock message.

**Comment by jspenguin2017** [comment]
Nope, video still doesn't play.

**Comment by lain566** [comment]
@jspenguin2017 Can you play the video from here?
`player.theplatform.com/p/HNK2IC/y9LXf40HJyoN/select/media/guid/2410887629/3580147`

This is the video
https://www.nbc.com/dateline/video/the-target/3580147

**Comment by jspenguin2017** [comment]
I plan on looping back the ads request XML, I'll get to this.

**Comment by lain566** [comment]
Maybe the problem is the autoplay.

**Comment by jspenguin2017** [comment]
This is harder than I thought...

**Comment by jspenguin2017** [comment]
Looks like with that scriptlet rule, the video plays now, except that the preroll somehow gets through.

**Comment by jspenguin2017** [comment]
I honestly don't know what this and `fox.com` are doing, I just can't touch the request...
