### ISSUE TITLE
tv.aftonbladet.se

### ISSUE THREAD

**Issue by lassekongo83** [jspenguin2017/uBlockProtector#163]
Ad-reinsertion

Example video: http://tv.aftonbladet.se/abtv/articles/214827

Chromium 57
uBlock Origin 1.12.1
Tampermonkey 4.2.7

![ab](https://cloud.githubusercontent.com/assets/7415624/25375180/2d3255ac-29a0-11e7-8cd7-f22f4ff1fe4c.png)

Preroll HTML5 ad around 20-30 secs and after that another small sponsored message. Looks like they use JW player.

Blocking the domain the ad is loaded from `(ssl.3.damoh.aftonbladet.se)` prevents the normal video from working properly. (Just get a black video that plays.) Try a Swedish VPN/Proxy if it's geo-locked.

**Comment by uBlock-user** [comment]
Yes, the ads are stitched and are loaded as `media` files.

Add this filter - `||damoh.*^$media`

**Comment by lassekongo83** [comment]
With that filter I get: _"An error ocured when loading the player. Please review your connection settings and try again."_

**Comment by uBlock-user** [comment]
add- `||cloudfront.net^$domain=aftonbladet.se` and `adv_partner`

PS - This is a filter list issue, rather than anti adblock one. You should notify Easylist forums about this. They're the ones supposed to handling this.

**Comment by uBlock-user** [comment]
> With that filter I get: "An error ocured when loading the player. Please review your connection settings and try again."

Cannot reproduce that, works fine for me.

**Comment by lassekongo83** [comment]
Roger that.

**Comment by uBlock-user** [comment]
Remove all cache and cookies and try again. You're probably being served a cached page.

**Comment by lassekongo83** [comment]
Since the issue was reopened. FYI the filters from https://forums.lanik.us/viewtopic.php?f=62&t=31008 does not work. Blocking only $media gives me the error message. Blocking everything else from that domain gives me a black video player that plays but without any image. Tested in Firefox with cache disabled. Flash not installed. Default uBO filters. Also cleared cookies.

As suggested in that thread, the addon [Flashstopper](https://addons.mozilla.org/firefox/addon/flashstopper/) for Firefox seems to block the ad just fine. There's a similar project on Chrome called [Autoplaystopper](https://chrome.google.com/webstore/detail/autoplaystopper/ejddcgojdblidajhngkogefpkknnebdh). It seems to block the ad but there's a long delay where the ad is supposed to be. Can't find the source for these addons though, so I don't know if there's anything that can be added to the script there.

**Comment by uBlock-user** [comment]
> FYI the filters from https://forums.lanik.us/viewtopic.php?f=62&t=31008 does not work. Blocking only $media gives me the error message

For you, not for everyone. I cannot reproduce the issue you're facing if I use the filter I posted. The filter I posted doesn't allow to load the video ad, nothing more, nothing else.

**Comment by jspenguin2017** [comment]
Yea, simply `||damoh.*^$media` works for me... I guess you have some other configuration issue. 
@uBlock-user Thanks for the rule, it's added to List.

**Comment by uBlock-user** [comment]
If you have Flash Player installed, then it might be serving flash player ads, in that case, my filter won't work. You can either uninstall Flash Player like I did as it's worthless as this juncture or use another filter like `||damoh.*$object` or `||damoh.*/*.swf` Lastly, for the sake of argument, this isn't ad reinsertation, it's no reinserting anything, it's just a case of unblocked video ads because of negligence on Easylist's side as usual. They're the ones suppose to deal with this stuff.

**Comment by lassekongo83** [comment]
@uBlock-user 
"Ad-reinsertion" is used by the Swedish media. It's what they call it and it's their so called plan for 2017 against users with adblockers. But agreed, it's just first party advertising really. It will most likely get harder for Easylist to handle ads like these because there are very little information that identifies them.

As for the filter, still can't get it to work with a stock browser and no other extensions or blocks in the network. (No flash installed.) Maybe it's a regional issue as this solution seems to have stopped working for some Swedish users. Just waiting for more confirmation from those users, and then I'll know for sure.

**Comment by uBlock-user** [comment]
Have you tried updating Chromium to version 58 which is the latest stable version ? I'm on Chromium 60 btw.

**Comment by lain566** [comment]
@jspenguin2017 It's broken

**Comment by lassekongo83** [comment]
@lain566: Filter list solution that works for me:
`||ooul.tv/contrib/se-aftonbladet/aab/aftonbladet_plugin.js$script,redirect=noopjs,domain=aftonbladet.se
||ooul.tv/nocache/se-aftonbladet/aab/aftonbladet_config.js$script,redirect=noopjs,domain=aftonbladet.se`

**Comment by jspenguin2017** [comment]
Yep, that works. Patched.

**Comment by datamaskinen** [comment]
not working any more ... getting black screen and only the sound

||ooul.tv/contrib/se-aftonbladet/aab/aftonbladet_plugin.js$script,redirect=noopjs,domain=aftonbladet.se

||ooul.tv/nocache/se-aftonbladet/aab/aftonbladet_config.js$script,redirect=noopjs,domain=aftonbladet.se
