### ISSUE TITLE
urle.co

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#183]
http://urle.co/bra3UFdTw
Could you please fix it?

**Comment by jspenguin2017** [comment]
We have a solution for the main problem: 
```JavaScript
if (a.domCmp(["urle.co"])) {
    a.filter("setTimeout", /captchaCheckAdblockUser\(\)\;/);
}
```

I'll see if I can remove the popup too.

**Comment by uBlock-user** [comment]
Anti adblock - `@@||urle.co^$elemhide`

**Comment by jspenguin2017** [comment]
@uBlock-user I didn't get the second part, what do you mean by sends you to ad server first?

**Comment by uBlock-user** [comment]
Click on Get Link and you will be sent to http://178.32.87.115/jetapi/mali.php?go=aHR0cDovL2xpbmtzaHJpbmsubmV0LzkxNHNz <--- That's some ad service/server, once you're there, that forwards to the real link.

**Comment by jspenguin2017** [comment]
@uBlock-user Hum, but it doesn't display anything nor it gives any popup. I'd say that's fine.

**Comment by uBlock-user** [comment]
Sure if you're okay with it.

**Comment by jspenguin2017** [comment]
@uBlock-user I the redirect is not secure, we can patch it... 
![image](https://cloud.githubusercontent.com/assets/7283682/25821596/0282e508-33f3-11e7-9fc8-8562c32371e2.png)

**Comment by uBlock-user** [comment]
Hmm, so removing `atob` would work ?

**Comment by jspenguin2017** [comment]
@uBlock-user No, if we want to skip the redirection, we need to use `atob` to parse the URL.

**Comment by uBlock-user** [comment]
Ah, I understand now.

**Comment by jspenguin2017** [comment]
Looks like this issue is resolved. Please let me know if it breaks again. 

@uBlock-user Thanks for sharing your discovery about the link jumping through another server, we will keep it in mind if the server starts to misbehave.

**Comment by jspenguin2017** [comment]
I think this broke again... The Captcha box doesn't load...

**Comment by jspenguin2017** [comment]
They uses imgur to host their ads... WOW
![image](https://cloud.githubusercontent.com/assets/7283682/26036680/a386b83e-389f-11e7-9c81-54a2f0823c8e.png)
And this div isn't initializing... 
![image](https://cloud.githubusercontent.com/assets/7283682/26036686/c01c7204-389f-11e7-89cf-eeaad7292bf6.png)

**Comment by lain566** [comment]
@jspenguin2017 They switched captcha

**Comment by jspenguin2017** [comment]
@lain566 Thanks. I just found out that my rule is blocking a script, this works: 
`@@||api.solvemedia.com^$domain=urle.co`
But looks like my rule is only blocking this one script, so I'm removing my rule.

**Comment by jspenguin2017** [comment]
Yep, looks like the old rule `*$script,third-party,domain=urle.co` is causing problems, it is now removed.

**Comment by adreporter** [comment]
@jspenguin2017 Unfortunately the antiadblock message appears again, could you please fix it?

**Comment by adreporter** [comment]
@jspenguin2017 It's broken, could you please fix it?

**Comment by jspenguin2017** [comment]
What is broken? I can't reproduce.

**Comment by adreporter** [comment]
@jspenguin2017 The "Click here to continue" doesn't work for me

**Comment by jspenguin2017** [comment]
Works for me: 
![image](https://user-images.githubusercontent.com/7283682/31310634-c37ad05e-ab58-11e7-880a-5ab57feacfd2.png)

**Comment by adreporter** [comment]
@uBlock-user 
http://urle.co/bra3UFdTw
Could you please check if you can click the "Click here to continue" button?

**Comment by adreporter** [comment]
Adding these rules solved the problem
```
@@||urle.co/js/ads.js$script
$xmlhttprequest,script,third-party,domain=urle.co
```

**Comment by jspenguin2017** [comment]
Did you install Extension?

**Comment by adreporter** [comment]
Yes, I did.

**Comment by adreporter** [comment]
@jspenguin2017 I don't understand...I thought these rules helped me out, but now I cleared cookies and cache and refreshed the page and the button doesn't work anymore.
Screenshot of the console:
<img width="960" alt="1" src="https://user-images.githubusercontent.com/18214146/31311172-bdbbf7e4-aba6-11e7-88b4-a5812b9c6330.PNG">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/18214146/31311173-c32e9d6c-aba6-11e7-9d93-9ca23d97e08a.PNG">
My extensions are: uBlock Origin and uBlock Protector Extension.
Could you please help me?

**Comment by jspenguin2017** [comment]
Still can't reproduce.

**Comment by lain566** [comment]
I can reproduce, that button is not clickable.

**Comment by jspenguin2017** [comment]
It's perfectly clickable for me. 
![image](https://user-images.githubusercontent.com/7283682/31311602-073ff210-ab6d-11e7-8e2c-71bcd9ca95d0.png)

**Comment by lain566** [comment]
Works if I click on the button 2 times in a row, Is this the expected behavior?
<details><summary>Screenshot</summary>

![2017-10-07_22-45-19](https://user-images.githubusercontent.com/27441315/31311681-cf132b9c-abb1-11e7-8af1-043ac3a01ce2.gif)
</details>

**Comment by adreporter** [comment]
Unfortunately even If I click 100 times, it doesn't work.

**Comment by adreporter** [comment]
@jspenguin2017 Could you please go to uBlock Origin, purge all caches and update all your filters? If you can't reproduce, I give up then.

**Comment by jspenguin2017** [comment]
@lain566 That sometime happens, the first time triggers a popup which is blocked. I consider that good enough. 
@adreporter I'll do that tomorrow.

**Comment by lain566** [comment]
@adreporter This fixes it
`urle.co##script:inject(abort-on-property-read.js, open)`

**Comment by jspenguin2017** [comment]
Reloaded all the filters, updated everything, still works as expected for me.

**Comment by ghajini** [comment]
https://urle.co/fODv3hZ
@jspenguin2017 
after bypassing timer ,other page come which says
` 'DON't try to cheat us!! we are smarter than you!!`

**Comment by jspenguin2017** [comment]
The redirection target is broken.
