### ISSUE TITLE
vidlox.tv

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#209]
test link:

https://vidlox.tv/embed-516hlnsyw96c.html

![capture](https://cloud.githubusercontent.com/assets/15007183/26106284/65af9a2e-3a13-11e7-825f-da4e3b437ce6.PNG)

**Comment by jspenguin2017** [comment]
`a.readOnly("adb", 0);`

**Comment by uBlock-user** [comment]
Doesn't work, checks for multiple variables to be undefined or not.

**Comment by jspenguin2017** [comment]
It works for me. Let me push the changes. 
![image](https://cloud.githubusercontent.com/assets/7283682/26115156/74785ede-3a1c-11e7-8f74-8a68c311ca63.png)

**Comment by xxcriticxx** [comment]
@jspenguin2017 did you try pressing play button? because nothing happens when i push start movie wont play

**Comment by jspenguin2017** [comment]
@xxcriticxx Does it work with uBO off?

**Comment by xxcriticxx** [comment]
maybe link went dead

**Comment by jspenguin2017** [comment]
Do you have another link to test?

**Comment by xxcriticxx** [comment]
https://vidlox.tv/xxlqm9zqtfav
https://vidlox.tv/uywf75vt681w
https://vidlox.tv/td89jqmyo6gx
https://vidlox.tv/foxp8hwy0arx

**Comment by jspenguin2017** [comment]
@xxcriticxx Looks like the media file is returning 403 at the moment, but it seems with uBO on, some main scripts are blocked and the media file isn't even requested. Let's wait a bit until they fixes their server and see what happens.

**Comment by uBlock-user** [comment]
It works fine, 

![](https://i.gyazo.com/631143bb53f370f414a846260bc11f7f.jpg)

**Comment by jspenguin2017** [comment]
@uBlock-user Does the video play?

**Comment by uBlock-user** [comment]
@jspenguin2017 Yes, but there's the popup issue still lingering. I forgot to mention that previously.

Filter - `vidlox.tv##script:inject(noeval.js)`

**Comment by xxcriticxx** [comment]
i cant get to play i cant even grab it with jdownloader

**Comment by jspenguin2017** [comment]
It doesn't quite play for me, I added the rule that removes popup. The media file seems to return 403...

**Comment by xxcriticxx** [comment]
i push play i get three dots they blink white once and disappear nothing happens after that

**Comment by uBlock-user** [comment]
I get 3 dots, they blink twice or thrice and then the play begins

Test URL - https://vidlox.tv/xxlqm9zqtfav

![](https://i.gyazo.com/482ebeb061d78b00472a229278fe8162.png)

**Comment by xxcriticxx** [comment]
no go with us ip

**Comment by xxcriticxx** [comment]
works if i turn off ublocko

**Comment by jspenguin2017** [comment]
@xxcriticxx 
It doesn't work at all, uBO on or off. 
The server returns 403: 
![image](https://cloud.githubusercontent.com/assets/7283682/26259038/759a49ac-3c84-11e7-9f24-55c1bd68ba5d.png)

**Comment by jspenguin2017** [comment]
I assume it's Geo Lock then.

**Comment by uBlock-user** [comment]
Yep that's probably the issue you're facing, can we manipulate headers ?

**Comment by jspenguin2017** [comment]
@uBlock-user Your location is not sent with HTTP header, and we can't really change it anyway...

**Comment by xxcriticxx** [comment]
@jspenguin2017 can you vpn and try with us ip?

**Comment by jspenguin2017** [comment]
@xxcriticxx I don't really think that will make a difference...

**Comment by xxcriticxx** [comment]
i dont think you geo lock must be something else. i can watch with ublocko off but i cant download with jdownloader. are we missing something?

**Comment by jspenguin2017** [comment]
Maybe...

**Comment by jspenguin2017** [comment]
It's working now, looks like they fixed their server: 
![image](https://cloud.githubusercontent.com/assets/7283682/26428580/bc743c74-409f-11e7-9918-6807da4a9194.png)

**Comment by xxcriticxx** [comment]
still wont play by me

**Comment by xxcriticxx** [comment]
@jspenguin2017 there is no firefox section on that list

**Comment by jspenguin2017** [comment]
@xxcriticxx Yes, we have dropped support for FireFox, this project is now strictly for Chrome, uBO, and Violentmonkey. If you don't want to switch, please check out AAK-Cont: https://xuhaiyang1234.gitlab.io/AAK-Cont/

Since this issue is fixed on the standard setup, I'll close it now.

**Comment by lain566** [comment]
@xxcriticxx It works for me with Firefox :sunglasses:
![watch_fifty_shades_darker_2017_webrip_x264_stutter_2017-06-01_00-59-31](https://cloud.githubusercontent.com/assets/27441315/26657685/bb202b8c-4665-11e7-8234-ee3355d78ed0.png)

**Comment by ale5000-git** [comment]
@xxcriticxx: Firefox isn't supported but if you use the script inside [Violentmonkey](https://addons.mozilla.org/it/firefox/addon/violentmonkey/) in Firefox it should work.

**Comment by lain566** [comment]
@jspenguin2017 is broken, I can't play any video

**Comment by jspenguin2017** [comment]
Someone broke CSP, let me check...

**Comment by jspenguin2017** [comment]
Eh...
```
! https://github.com/uBlockOrigin/uAssets/issues/394#issuecomment-304461367
||videotoolbox.com^$csp=script-src 'self' * 'unsafe-inline'
```

**Comment by jspenguin2017** [comment]
@gorhill Is there a way to override this filter? My extension has no race condition, even if `eval` is first line I can still block it.

**Comment by uBlock-user** [comment]
Easylist's filter is breaking it - https://i.gyazo.com/94373e4ae7ea7c69b7cf7c941ab5c2be.png

**Comment by uBlock-user** [comment]
You can whitelist it with `@@` or use `$badfilter` directive.

**Comment by jspenguin2017** [comment]
`badfilter doesn't work... I tried...

**Comment by jspenguin2017** [comment]
`@@` works if I paste the exact line... That removed a bit more than just that site, and it will break again when the line is updated. 
`no-eval.js` rule is replaced by `a.filter("eval")`. 
The server is returning 403 even after I removed the two `csp` rules...

**Comment by uBlock-user** [comment]
Hmmm, `$badfilter` should work, it's a network filter after all.

**Comment by jspenguin2017** [comment]
I guess the implementation is different, I was digging in uBO source and I think `csp` is handled quite differently...

**Comment by uBlock-user** [comment]
Also triggering popups from random domains, filter - `vidlox.tv##a[href^="//"]`

**Comment by jspenguin2017** [comment]
Did you update my extension? Popups should been fixed already.

**Comment by uBlock-user** [comment]
Yep the updating the extension took care of that.

**Comment by uBlock-user** [comment]
Using `default-src` like this is a terrible mistake, that one filter will break lots of functionalities on numerous websites.

**Comment by jspenguin2017** [comment]
I can't seem to override that header with `webRequest`, it seems like uBO runs after my extension and nuke my changes.

**Comment by uBlock-user** [comment]
Video still won't play as the CSP policy is still being applied.

**Comment by jspenguin2017** [comment]
Yea, I'm not sure how to remove the policy.

**Comment by jspenguin2017** [comment]
uBO doesn't remove existing CSP, why on Earth can I not add CSP rules from my extension... 
https://github.com/gorhill/uBlock/blob/1581ec20d87713ff31ec6a3da4f84650b5f4b6ca/src/js/traffic.js#L555

**Comment by uBlock-user** [comment]
You will have to use `@@||$csp,domain=vidlox.tv`, that's the only way currently to counter CSP filter from Easylist.

**Comment by jspenguin2017** [comment]
Oh wow, that works!

**Comment by jspenguin2017** [comment]
The 403 from the server must be something else, maybe Geo Lock, probably unrelated, I'll mark this one as fixed then.

**Comment by uBlock-user** [comment]
Still we shouldn't need to use whitelisting filters for CSP, it's not supposed to be, but once again, Easylist maintainers managed to screw it up and now we have another job at our hands...

**Comment by jspenguin2017** [comment]
CSP rules are fragile, like I said before, it can blow things up easily and it's hard to fix. I have access to `webRequest` from my extension, there are much more I can do, I can inject CSP from other places if required.

**Comment by uBlock-user** [comment]
I tested `||$csp=script-src 'self' * 'unsafe-inline' 'unsafe-eval',domain=vidlox.tv`. Works perfectly. Instead of default-src, they should be using `script-src`rather

**Comment by jspenguin2017** [comment]
@uBlock-user We don't need CSP for this site, it is originally used to block `eval`, but my extension does not have race condition and can block `eval` without CSP. 
Also, it looks like only one CSP rule can apply, this system is really fragile, let's not use it if possible.

**Comment by jspenguin2017** [comment]
Just a side thought, should I add `a.noop` that can be a light weight version of `a.filter` when I want to block everything? It's quite rare that I need `a.filter` to actually apply a filter and the overhead is kind of large...

**Comment by gorhill** [comment]
>  it is originally used to block `eval`

Not at all, the purpose is to be able to control a variety of network requests/behaviors through CSP. The actual original reason was me seeking a way to block shared workers, and I decided to implement this through CSP rather than yet-another-resource-type, as there are many other issues which can be solved through CSPs (for example, forbid `data:` URIs), including promising planned future ones (for example, `navigation-to`).

**Comment by jspenguin2017** [comment]
@gorhill It looks like only one CSP rule can apply and `badfilter` doesn't work on it, is that intended or it's just temporary? It can be used for many things but it's hard to control...

**Comment by gorhill** [comment]
> It looks like only one CSP rule can apply

I don't understand what you mean, you can apply as many as you wish.

> `badfilter` doesn't work on it

Yes, not implemented for `csp=`, I try to focus on fixing thing which are most likely to be used out there.

**Comment by jspenguin2017** [comment]
@gorhill I mean, can one domain have 2 different CSP rules applied to it?

**Comment by gorhill** [comment]
> can one domain have 2 different CSP rules applied to it?

    ||example.com^$csp=script-src=*
    ||example.com^$csp=frame-src='none'

**Comment by jspenguin2017** [comment]
OK, thanks, I guess my rules were wrong...
