### ISSUE TITLE
receive-sms-online.info

### ISSUE THREAD

**Issue by Phlipout** [jspenguin2017/uBlockProtector#211]
view site
click on a phone number

https://www.receive-sms-online.info/read-sms.php?phone=14083896925

<details>

expected:

![screen shot 2017-05-16 at 6 04 46 pm](https://cloud.githubusercontent.com/assets/28744287/26134257/4a98a664-3a62-11e7-9865-8e57b883e2fb.png)

But a populated middle column.  Is it blank because I have blocked the inline-script?

`||www.receive-sms-online.info/read-sms.php?phone=14083896925$inline-script,domain=www.receive-sms-online.info`

not blocking that shows obstructionism

![screen shot 2017-05-16 at 6 06 13 pm](https://cloud.githubusercontent.com/assets/28744287/26134292/6b82dfca-3a62-11e7-8ef3-27c84fdd2dbb.png)

I usually write such whiners a letter indicating I only whitelist sites with 1st party, non-active ad content.

These filters 

![screen shot 2017-05-16 at 6 09 24 pm](https://cloud.githubusercontent.com/assets/28744287/26134348/d3273608-3a62-11e7-8063-aa9e2e0fea1f.png)

uBlock origin, greasemonkey, stylish.  Only those 3 extensions.  Stylish is only used to style outlook.com 
waterfox 53.0.1, 

also Iridium 58 (chromium): ublock origin, ublock origin extra, tampermonkey

https://iridiumbrowser.de/index.html#about

</details>

**Comment by jspenguin2017** [comment]
OK, I'll fix it.

**Comment by jspenguin2017** [comment]
Does https://github.com/jspenguin2017/AdBlockProtector/commit/793bd5aeb06b7a770db726022ad1fe450b3ef0b5 fixes it?

**Comment by Phlipout** [comment]
:1st_place_medal:  yes, that is marvelous, thank you much

![smile09](https://cloud.githubusercontent.com/assets/28744287/26135933/aa51c24c-3a6d-11e7-958f-0c3acd15bbde.jpeg)

What can I read to educate myself to the point of understanding the changes you made? Let's assume I am 99% javascript illiterate.

**Comment by jspenguin2017** [comment]
@Phlipout I started by coding client side website, I think of what I want, and Google what I need to make that working. 
If you just want to be able to fix websites, have a look at our Core library, it offers many high level API that are easy to use: https://github.com/jspenguin2017/AdBlockProtector/blob/master/Script%20Compiler/Core.js

**Comment by jspenguin2017** [comment]
Looks like it's still working. Closing this issue.
Let me know if it breaks again.

**Comment by lain566** [comment]
@jspenguin2017 Is broken .... maybe

**Comment by jspenguin2017** [comment]
Yep, it's broken.
