### ISSUE TITLE
download.themeslide.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#228]
http://download.themeslide.com/ezjwq

`download.themeslide.com.net##script:inject(bab-defuser.js)
download.themeslide.com.net##script:inject(noeval.js)`

Both does not work.

uBlock Origin + Chrome + AB Protector

**Comment by uBlock-user** [comment]
Add - `themeslide.com.net##script:inject(noeval.js)`

**Comment by uBlock-user** [comment]
@jspenguin2017 There's a 10 sec timer that needs patching.

![](https://i.gyazo.com/474f3af44ad1be954701be514d96e2fa.png)

**Comment by jspenguin2017** [comment]
@uBlock-user Thanks. Both BAB and timer are patched.

**Comment by lain566** [comment]
@jspenguin2017 is broken again

**Comment by jspenguin2017** [comment]
This should fix it...

**Comment by jspenguin2017** [comment]
The link expired, that's not a problem with uBlock Protector.

**Comment by lain566** [comment]
https://www.themeslide.com/

![themeslide_ _download_wordpress_themes_ _plugins_-_2017-06-28_19-49-36](https://user-images.githubusercontent.com/27441315/27655968-9ce9234c-5c47-11e7-94aa-edc02d928ff3.png)

**Comment by jspenguin2017** [comment]
This should fix it for real...

**Comment by lain566** [comment]
@jspenguin2017 Yes, is fixed
