### ISSUE TITLE
hackinformer.com

### ISSUE THREAD

**Issue by Zhangsun321** [jspenguin2017/uBlockProtector#232]
https://hackinformer.com/

ublock origin
tampermonkey
chrome
http://prntscr.com/fbkgra
http://prntscr.com/fbkh5c
screen shots of lists used
ty

**Comment by SilicaAndPina** [comment]
there using an inline script >_> i mannaged to bypass it on firefox with 
hackinformer.com##script:contains(window.location)
unfortunately chrome dont allow you to block inline scripts.

**Comment by jspenguin2017** [comment]
Hum, somehow `abort-on-property-read.js` doesn't work on this one... Could be some tight race condition... 
Since the script is first party, and only contains one variable declaration, I'll white list it. 
`@@||hackinformer.com/wp-content/plugins/detect-adblock/js/ads.js|$script,first-party`

**Comment by jspenguin2017** [comment]
FireFox is dropping `onbeforescriptexecute` event, so soon it won't work on FireFox neither.

**Comment by uBlock-user** [comment]
Has second anti adblock script - https://hackinformer.com/wp-content/uploads/oYMMBOWcnXUs/ZwaoOUfUMaqB.js

**Comment by uBlock-user** [comment]
Race condition is the core issue here.

**Comment by jspenguin2017** [comment]
@uBlock-user Do you have a test page where the second script triggers?

**Comment by uBlock-user** [comment]
@jspenguin2017 The second script won't trigger for me because I use - `/wp-content/uploads/*.js` filter globally.

**Comment by uBlock-user** [comment]
Anyways that's the last thing you should worry about. That race condition is troubling.

**Comment by jspenguin2017** [comment]
Yea... There isn't much we can do about that... It's a first party script, so I guess just white list it...

**Comment by jspenguin2017** [comment]
Solution for 2nd script: 
```
hackinformer.com##script:inject(abort-on-property-write, anOptions)
hackinformer.com##script:inject(setTimeout-defuser.js, an_message_display)
```
```JavaScript
if(a.domCmp(["hackinformer.com"])){
  a.ready(()=>{
    a.$(".special-message-wrapper:contains(your ad blocker)").remove()
  });
}
```
I'll push the changes out later.

**Comment by jspenguin2017** [comment]
This should be fixed for good now.

**Comment by uBlock-user** [comment]
@SilicaAndPina FYI `onbeforescriptexecute` is not present in WebExtensions API, so the filter won't work within the next months as with the release of newer versions of FF.

**Comment by jspenguin2017** [comment]
Looks like it's still working. Closing.

**Comment by jspenguin2017** [comment]
The new solution in Extension is able to win this race condition, the whitelist is removed.
