### ISSUE TITLE
forum.outerspace.com.br

### ISSUE THREAD

**Issue by ialexsilva** [jspenguin2017/uBlockProtector#236]
Before opening an issue, you MUST read the contribution guideline. Failure to do so may result in a ban. 

Test link: http://forum.outerspace.com.br/index.php?threads/forza-horizon-3-offline-vale-a-pena.484724/

Screenshot: 
![capturar](https://cloud.githubusercontent.com/assets/6363160/26450615/c50eabd2-412e-11e7-866b-aaa57f3af4b0.PNG)

Add everything else that you believe to be useful below: 

Google Chrome Version 58.0.3029.110 (64-bit)
uBlock Origin v1.12.4

**Comment by uBlock-user** [comment]
Patched via Script.

You haven't installed the Adblock Protector Script via TamperMonkey, that's why it's happening to you. 

Complete the installation first.

**Comment by jspenguin2017** [comment]
Have you installed Script? 
![image](https://cloud.githubusercontent.com/assets/7283682/26457442/5703b840-412d-11e7-99dc-979c363f93bd.png)

**Comment by uBlock-user** [comment]
He hasn't installed TamperMonkey installation either, so obviously no Script. Also there's no point in opening issues here if you're not going to install the Script.

**Comment by jspenguin2017** [comment]
Looks like it still works. Closing.
