### ISSUE TITLE
[Announcement] What happened recently and why the name change

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#237]
Hi everyone. A lot of things have happened in the past few days, let me explain what happened, why it happened, what does this mean for you, and what to expect for the future. 

Let's start with some back stories. 

It was June 2016, I discovered Anti-Adblock Killer (AAK), by that time, Reek was still actively maintaining the project. He submit one patch every month and I felt the delay is a bit long. So I started this project, it was called AdBlock Protector, since I was using Adblock Plus by that time. The project was designed to run alongside AAK. 3 months... 4 months have passed, and we are starting to question the future of AAK. And Reek comes back, submitting two patches in a row... and he is gone again. 2 months... 3 months... I started to lose hope and I decided to update this project so it is no longer dependent on AAK. I read over the AAK Userscript code and have found that it has a lot of code that are weird and long which can be replaced by something much simpler. I tested it out in my browser, and it worked. What I didn't know at that time is that this would break compatibility, like break it really hard. The project was more for myself, so I decided to rewrote the code to remove all the weird and redundant part, and it ended up only working on my setup. A few people gets interested and come to my repository, and I didn't mind helping and explaining as there are maybe one or two issues per week. 

Then I discovered uBlock Origin, after testing out its amazing features, I decided to switch to it, which also means the project, AdBlock Protector, starts to include filters that only work in uBlock Origin. More and more people discovered the project and instead of one or two issues per week, we start to receive one or two issues a day. At first, I was patient in explaining why this project doesn't work properly on another setup, but slowly, I start to lose patience. As more and more people come to my repository, I start to have problem maintaining it. I have assignments and exams, and I don't have that much time left to manage this project. I still tried to resolve issues as fast as possible, and I ended up getting a lower grade for the semester. 

It's now summer vacation, I finally have time to clean up issues that are stockpiled over the exam session. It took me two days to clean things up. Everything should be good now... except that I start to receive more and more complains about the project not working on their setup. I ended up discovering that Adguard developers have put this project in their database. As I never intended to support Adguard, I decided to ask Adguard developers to remove the entry. It should been nice and easy, right? But it was not. One Adguard developer told me that they can't remove the entry, closed the issue, and locked it (maybe by accident as it is unlocked soon after). I took this as a middle finger and I can't stand this. With some bad timings and miscommunication, this escalated to what some of you may know. But what exactly happened doesn't matter, only the result does. 

Now, Adguard team and me are enemies, you have to make a choice: go with Adguard team, go on your own, or still stay with me. 

If you wish to go with Adguard team, don't say anything, just leave. This might be the best choice for you as their team is bigger and your issues would be handled nice and fast. 

If you wish to go on your own, the same, don't say anything, just leave. And good luck. 

If you still want to stay with me, now let's talk about the name change and the future. 

This project is renamed to uBlock Protector to reflect what it actually does, it will also be strictly for the setup I use. I mean, strict. I will be dropping ban hammers. More information can be found in the contribution guideline, make sure to read it if you choose to stay with me here. Those rules are ridiculous? Wait, I have another option for you later. By the way, the name change means you have to reinstall this project. Once school starts again, I will still try to resolve issues that are opened in this repository in a timely manner. If you with to stay with me here, don't make me disappointed, keep those issues high quality. I won't have as much patience. 

Now let's talk about the other option. If you are using another setup and you still want to stay with me, you can head over to AAK-Cont repository, the link is at the end. I will try to bootstrap that project this summer, and I will be expecting the community to take over once school starts again. Don't worry, I'm not going to dissappear, I will still be resolving Merge Requests and do some general maintenance. 

Still not satisfied? Unfortunately, that is the best I can offer, if you are not satisfied, you can go back to pick another option. I don't want discussion about what exactly happened or who is right, show that with your actions. 

Here is the link to AAK-Cont repository: https://gitlab.com/xuhaiyang1234/AAK-Cont/

**Comment by uBlock-user** [comment]
> Now, Adguard team and me are enemies, you have to make a choice: go with Adguard team, go on your own, or still stay with me.

Wow, I had no idea that something like that was taking birth behind the scenes as I recall they were very assistive when it came to helping us, specifically during that Instart Logic issue.

**Comment by BooBerry** [comment]
> Now, Adguard team and me are enemies, you have to make a choice: go with Adguard team, go on your own, or still stay with me.

This seems a bit harsh, considering the whole situation was one giant misunderstanding that spiraled out of control. It also seems that this idea of enemies is one sided, since @ameshkov posted this comment;

> Let me please emphasize one thing -- I don't have a problem with @jspenguin2017. As I've said, it is his product, his rules, he does a good thing after all. Heck, I don't mind helping to resolve some issues even now. When I did it last time I was well-aware that he does not support AG and I don't care because the issue research/resolution benefits everybody.

Can I offer one last thought? I don't believe it's too late for some kind of peace here between you guys. In fact, if you and @ameshkov are open to it I bet you both could hold a private discussion somewhere which could hopefully lead to some sort of peace.

Fighting really isn't worth it, especially when everyone has the same goal in the end.

**Comment by jspenguin2017** [comment]
@BooBerry 

<details>

I haven't banned him, he can still do what he want here as long as he follows the rules. He will be treated like a normal user. It's not like we'll try to take him down or anything. The only change is that we will no longer tolerate Adguard users (as well as users using other setup) *opening* issues here. If you are sure that the issue can be reproduced on my setup then that's an exception. 

I'm not going to talk to him on what happened, and I don't care about his opinion, also I still don't respect SMed79 opening garbage pull request nor the fact ameshkov defended him. I don't care if he manages filter lists or Linux kernel, opening that pull request doesn't deserve respect. 

Also, I don't respect ameshkov more because he is developer of Adguard, developing proprietary software does not deserve extra respect. He is just another developer on the Internet, just another normal person. 

</details>

**Comment by Piter432** [comment]
Is Tampermonkey then unsupported? Why Violentmonkey, a worse user javascript manager?

**Comment by jspenguin2017** [comment]
@Piter432 That's my choice.

**Comment by Piter432** [comment]
@jspenguin2017: But is TM unsupported or what?

**Comment by jspenguin2017** [comment]
@Piter432 It probably will still work, but yes, it is unsupported.

**Comment by Piter432** [comment]
@jspenguin2017: Then why not cooperate with AAK-Cont creators/contributors to support more browsers, user javascript managers and other ad blocks with uBO?

**Comment by jspenguin2017** [comment]
@Piter432 I am the AAK-Cont repository master.

**Comment by uBlock-user** [comment]
> a worse user javascript manager?

That's an irony coming from you who used to contribute to VM 3 years back - https://github.com/violentmonkey/violentmonkey/commits?author=Piter432

**Comment by mozkan007** [comment]
@jspenguin2017  I really liked this project.Thus I am so sad now because you were working hard.I will continue this new project but it would be better if tampermonkey support did not end.Anyway I wish you good luck for the new project.Thanks.

**Comment by Piter432** [comment]
@jspenguin2017: I think I'm looking bad, cause I see only one Master member of AAK-Cont 😕

**Comment by jspenguin2017** [comment]
@Piter432 That's me. 
![image](https://cloud.githubusercontent.com/assets/7283682/26508129/afae2082-4210-11e7-88d5-bcca167ac4d3.png)

**Comment by Piter432** [comment]
@uBlock-user: Then, if I remember correctly, I didn't know about TM or maybe I knew about TM, but it was too advanced for me, I don't remember. However, VM was for me better than GM in that time. Otherwise, there was 1 user javascript manager for browser if I remember well (GM for Firefox, TM for Chrome, VM for Opera & ChrOpera [Opera on Chromium]).

I still remember very well, however, that I proposed TM'a creator to add option to export user javascript, its data (settings) and TM's data (settings) and after he did it, I promised that when I will have money, I will donate his extension, but that's another story 😛

**Comment by Piter432** [comment]
@jspenguin2017: Okay, nice to meet you, Mr Hugo 😃

But is AAK-Cont actively developed by you like your uBlock Protector?

**Comment by jspenguin2017** [comment]
@Piter432 For now yes, but probably not in the long run.

**Comment by uBlock-user** [comment]
@Piter432 That still doesn't justify how it is "a worse user javascript manager" in your words ? You dislike something about it ?

**Comment by Piter432** [comment]
@jspenguin2017: Then keep looking for new contributors for AAK-Cont. I can help you in AAK-Cont, 'cause I'm a*s, not the programmer 😞
___

@uBlock-user: When comparing VM to TM – yes, VM is worse mostly because of what settings VM have.
When comparing VM to GM – no, VM is better, 'cause I can do a little bit more than in GM (mostly I can export user javascript with its data [I think? I'm not sure.] and easily edit installed user javascripts).

**Comment by jspenguin2017** [comment]
@Piter432 You can customize Violentmonkey the way you want, you can change its source code, add *any* settings you want. You can't compare open source to proprietary. Also, VM's autocomplete is better than TM. 

BTW, I have to use Windows because the tools I use, I have Linux whenever possible. I'm not using Chromium because it's a pain to get it set up on Windows (on Linux all you have to do is `sudo apt install chromium-browser`).

**Comment by jspenguin2017** [comment]
I have to say, I actually considered to make this project private so I don't need to deal with websites I never use. It's really hard to keep things going, no wonder why Reek quite and there is no successor. It's really boring and I'm not learning a lot from it anymore, I guess every project will have an end, but as I still need to use this daily, I'm not going to fully give up, but I will be very strict on what is allowed in this repository. 

Keep in mind that it is for **this** repository only, the rules don't apply to my other repositories.

**Comment by Saucermote** [comment]
I'm thankful for this project, and your updates.

---

Might I suggest a package manager such as Chocolatey for windows if you want to use Chromium (or lots of other programs). 

Then it is as simple as: 

`Choco install chromium`

and:

`Choco upgrade chromium`

**Comment by jspenguin2017** [comment]
@Saucermote I know Chorolatery... Might try it sometime...

**Comment by jspenguin2017** [comment]
uBlock Origin has support URL pointing directly to contribution guideline 😄 
I guess life is good again 😄

**Comment by uBlock-user** [comment]
Installing Chromium or updating is quite easy if you simply use ![chrlauncher](https://github.com/henrypp/chrlauncher), only has to setup once and forget it OR use a semi-portable 
 archives of Chromium from http://chromium.woolyss.com/

**Comment by flak0r** [comment]
im just a normal user (no coding knowledge at all) who somehow found his way from anti-adblock killer to this project, and i just want to say thank you for the effort you invest in this! keep up the good work!

**Comment by Piter432** [comment]
@jspenguin2017: I mean the settings in the extension, not what dev can do. Btw., autocomplete _maybe_ is better in VM than TM, but that doesn't convince me.

Maybe I'll return to VM. Maybe, 'cause I'm very attached to TM so will be hard to move to VM, but who knows 😛

**Comment by jspenguin2017** [comment]
@Piter432 I use Visual Studio to format the code, but when I'm developing a solution, I need to code it in the editor, VM also let you edit in another editor, which is awesome. TM on the other hand, will not auto-match brackets, so the code will end up not working because of simple mistakes.

**Comment by jspenguin2017** [comment]
Another reason is that VM is open source, so I can go read its source and know how exactly it works, this will help me optimize my code as I know what the wrapper is doing. This will also help when something is not working, as I can debug my own code as well as VM itself, and I can know where the issue is.

**Comment by Piter432** [comment]
@jspenguin2017: Hmm, indeed. TM isn't fully open source (there is however TM's repo, but from the old version of TM), only language files are newest, 'cause u know 😜

Okay, if uBP (uBlock Protector) script will stop working some day in TM (at least most of its code), then I'll check VM, but I guess the functions for normal users will be limited, 'cause originally VM appeared as Opera's/ChrOpera's (Opera on Chromium) extension and I don't think so, that VM's author will expand/add VM's functions for normal users just for one browser (Chrome) 😕


PS Sorry for bumping the thread 😛

**Comment by jspenguin2017** [comment]
@Piter432 GitHub issues are not bumpable. Also keep in mind that users using Tampermonkey are not allowed to open issue here. You can always open issue in AAK-Cont repository though.

**Comment by jspenguin2017** [comment]
@Piter432 He is not adding functionalities for just one browser, it's for all browsers that support WebExtension, which is pretty much every modern browsers out there.

**Comment by Piter432** [comment]
> You can always open issues in AAK-Cont repository though.

Since we are at AAK-Cont thread stage, why you made AAK-Cont repo on GitLab? Is it better than GitHub or maybe you don't want to have a mess on your GitHub account? Or maybe you have different reason?
____________

> he is not adding functionalities for just one browser, it's for all browsers that support WebExtension, which is pretty much every modern browsers out there.

I meant that not all APIs, which have ChrOpera (Opera on Chromium)/Opera are in Chrome/Firefox and vice versa, don't mention about unique functions in ChrOpera which Chrome probably will never have (in the long future, of course).

**Comment by jspenguin2017** [comment]
@Piter432 I have way more control over the repository on GitLab, this include deleting issues, marking issues as confidential, give someone white access to only a few files, etc. The drawback is GitLab is kind of slow. But for a community project, those extra functionalities is mandatory. 

Violentmonkey is good or bad doesn't matter anymore because Script will hit end of life very soon.

**Comment by jspenguin2017** [comment]
@Piter432 Also, you can have free private repositories on GitLab, if you are wondering where is the extension I'm developing, now you know.

**Comment by Piter432** [comment]
@jspenguin2017: Okay, that makes sense. Also I saw that you've locked some folders/files in AAK-Cont repo, so I just wanted to know more about GitLab. Only this UI of the website... meh 😕

**Comment by jspenguin2017** [comment]
@Piter432 The UI is different, personally I like GitLab's UI more.

**Comment by Piter432** [comment]
@jspenguin2017: I meant, of course, the issues list (especially colour of the font, except labels) and the look of first post in the thread (I mean issue) 😜 The rest is okay/better than in GitHub 😃

**Comment by jspenguin2017** [comment]
That's personal taste, it really doesn't matter, what matters is GitLab let me do more, it doesn't affect normal users but it does affect me.
