### ISSUE TITLE
kardiolo.pl

### ISSUE THREAD

**Issue by mirrorsmm** [jspenguin2017/uBlockProtector#238]
Hello. On page www.kardiolo.pl uBlock detection during trying 
reproduction video.
Exemplary link:
 http://www.kardiolo.pl/zawal.htm
 http://www.kardiolo.pl/kardiochirurgia.htm
etc...

Please fix the problem

**Comment by jspenguin2017** [comment]
This should be fixed now.

**Comment by jspenguin2017** [comment]
Looks like it's still working. Closing.
