### ISSUE TITLE
teleshow.wp.pl

### ISSUE THREAD

**Issue by mirrorsmm** [jspenguin2017/uBlockProtector#239]
Hello. 
uBlock discovered 6 Seconds After beginning of transmission .

https://teleshow.wp.pl/za-kulisami-nowego-teledysku-eweliny-lisowskiej-sexy-6127268417857665a

Sorry, It is weak my english .

**Comment by jspenguin2017** [comment]
I think the player is reading the ads itself... I guess we have to patch the player... 
![image](https://cloud.githubusercontent.com/assets/7283682/26529990/7beb29aa-4389-11e7-826a-2a3e07581e0f.png)

**Comment by jspenguin2017** [comment]
Looks like it's still working. Closing.
