### ISSUE TITLE
Who add list in uBlock to Ads seciton?

### ISSUE THREAD

**Issue by uBlock-magic** [jspenguin2017/uBlockProtector#240]
![image](https://cloud.githubusercontent.com/assets/29037222/26544376/e6e5dba0-4461-11e7-95d6-4e9602c97084.png)

I could do with code from uBlock Origin detect instaled script if possible?

**Comment by uBlock-user** [comment]
gorhill did. If you don't want it, uncheck it and remove the cache.

**Comment by jspenguin2017** [comment]
It should not be checked by default. You will need to install Violentmonkey and the Script for it to work properly.
