### ISSUE TITLE
NSFW! javsex.net

### ISSUE THREAD

**Issue by LaxusiC** [jspenguin2017/uBlockProtector#244]
Test link:  http://javsex.net/watch-movie-mds-857-gakuen-position-cute-class-president-is-much-pretty-hagi-cum-insanely-etch.html

Screenshot: http://prntscr.com/fdt4gb

Not sure if you do bypass the detector on porn site, if not just delete this, don't ban me please :)

**Comment by uBlock-user** [comment]
```javascript
document.write('<div style="text-align:center">Please turn off Adblock to watch this video !</div>');
```

**Comment by uBlock-user** [comment]
Whitelisting http://yamvideo.com/pop1/jwplayer.js works but it might bring ads too.

**Comment by uBlock-user** [comment]
The notice is placed such a way that if the player is BLOCKED, then only you will see the notice, so the player is superimposed on the notice.

**Comment by jspenguin2017** [comment]
Huh, that is an unconditional write, that link gives a slightly obfuscated code, the strings are: 
![image](https://cloud.githubusercontent.com/assets/7283682/26588056/6b5d4f30-4511-11e7-8a1a-25c37037b992.png)
Doesn't look like a real player to me...

**Comment by jspenguin2017** [comment]
It POST to a php file to retrieve the real player... it seems...

**Comment by uBlock-user** [comment]
> that is an unconditional write

Yes, that's the case. It doesn't check for anything.

**Comment by jspenguin2017** [comment]
It POST to `http://javhdx.com/appvideo/jw_ads.php` and retrieve a HTML snippet, and paste that into the video container... Now I need to find out what that HTML is.

**Comment by jspenguin2017** [comment]
The `iframe` at the end tries to load ads, but it is already taken care by some other rules. The video file source is returned from the PHP API call, so enforcing the integrity of `/pop1/jwplayer.js` won't help. I'll just white list it. 
`@@||yamvideo.com/pop1/jwplayer.js$domain=javsex.net`

**Comment by jspenguin2017** [comment]
That "folder" is black listed by EasyList because the other two files it serves: 
![image](https://cloud.githubusercontent.com/assets/7283682/26590868/12f0d8c8-4519-11e7-8e3e-6cc57e5c098d.png)
We should be good just white listing the player bootstraper.

**Comment by uBlock-user** [comment]
Yeah white-listing the player does the job just fine.

**Comment by LaxusiC** [comment]
I'm new to uBlock how do i use the fix?

**Comment by jspenguin2017** [comment]
Looks like it's still working. Closing.
