### ISSUE TITLE
Adblock Protector list on Github it's offline... please fix.

### ISSUE THREAD

**Issue by DjDiabolik** [jspenguin2017/uBlockProtector#247]
https://github.com/jspenguin2017/AdBlockProtector/raw/master/AdBlockProtectorList.txt

This filters it's a part of Ublock-origin......... now the github it's no more reachable......

**Comment by DjDiabolik** [comment]
mmmmm.. great to know it.
How it's located the newest filter ?

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/1634a5e079491cea15e68b6d1f509155.png)

**Comment by DjDiabolik** [comment]
mmmmmmmmmmm.... i thinks i can only to wait the next version of ublock-origin ?
I continue to see an errors say "Obsolete" and another say "A network erros etc etc"....

**Comment by jspenguin2017** [comment]
Purge all cache, and update, it will update the list. I also have manual installation instructions. Also, you are not allowed to open issues for help with installation.

**Comment by DjDiabolik** [comment]
@jspenguin2017 oh yeah... it's be ok now... all it's resolved.. Sorry me for bad warning :)

**Comment by jspenguin2017** [comment]
Next time, please go to https://jspenguin2017.github.io/uBlockProtector/ and follow instructions there, do not open issue unless you think that that guide is broken.
