### ISSUE TITLE
Two confidential issues are opened in the GitLab issues tracker

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#248]
- [x] https://gitlab.com/xuhaiyang1234/uBlockProtectorSecretIssues/issues/1
- [x] https://gitlab.com/xuhaiyang1234/uBlockProtectorSecretIssues/issues/2

**Comment by uBlock-user** [comment]
It shows 404 page, is that supposed to happen ?

**Comment by jspenguin2017** [comment]
Yes, only me and the reporter has access.

**Comment by uBlock-user** [comment]
Ah, okay I understand.
