### ISSUE TITLE
[Discussion] For A Faster Future

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#249]
- jQuery: **Changed** to lazy load. 
- Let and loop: **Keeping** as-is, no performance difference in my tests. 
- a.domCmp: **Changed** to a more efficient algorithm, it's now faster by about a third. 
- a.domInc: **Changed** to a more efficient algorithm, it's now over two times faster. 
- DOM watcher: **Keeping**, this is very complex, as I can't guarantee a faster logic that I can come up with would do the same, I have to leave this as-is, however, I pulled all RegExp out and pre-compiled them, it should make things slightly faster. 
- Minifying: **Keeping** as-is, minifying gives too little gain, and I would need to have a development version that is not minified. 
- Hash function: **Changed** to MD5, solutions that rely on previous hash function (SHA256) are updated. Even though MD5 is not cryptographically secure, it is good enough for our purpose, I can add a length restriction if someone tries to carry out a collision attack. 
- `a.cookie()` get mode: **Changed** to a more efficient algorithm. 
- Property looping: **Changed** to a more efficient algorithm.

**Comment by jspenguin2017** [comment]
Eh... What? 
http://jsben.ch/#/FKapz
![image](https://cloud.githubusercontent.com/assets/7283682/26647553/f7326bda-45fc-11e7-8f1e-0f4156448b5e.png)

**Comment by jspenguin2017** [comment]
Looks like V8 is not perfect, but as that can change, I will not make optimization that I think should be done by V8. It is faster now doesn't mean it will be faster later. 
However, jQuery and the DOM watcher are actual overhead and it's not V8's task to optimize them. 

I might also fix `let` with loop, as the variable is “copied" every iteration and we don't want that. 
![image](https://cloud.githubusercontent.com/assets/7283682/26654079/a5b5720a-4612-11e7-881c-2891bb9b5e5f.png)

**Comment by jspenguin2017** [comment]
`let` is substantially slower for loops... I think this is a problem on my end, I will fix it. 
![image](https://cloud.githubusercontent.com/assets/7283682/26654167/f9618c18-4612-11e7-848c-afb14a79a866.png)

**Comment by jspenguin2017** [comment]
Normal usage: 
![image](https://cloud.githubusercontent.com/assets/7283682/26654320/afe9561e-4613-11e7-9579-15a9ead7aba4.png)
After explicit garbage collection: 
![image](https://cloud.githubusercontent.com/assets/7283682/26654357/d0587aa6-4613-11e7-83d6-6f1e22047714.png)

**Comment by DjDiabolik** [comment]
I look this discussion... because it's suggested to use Violentmonkey and in the pass it's suggested Tampermonkeys ? What's the differences about this two script manager ?

**Comment by jspenguin2017** [comment]
@DjDiabolik Violentmonkey is open source. And it is significantly lighter than Tampermonkey. 

I will do profile guided optimization for V8 JavaScript engine, but FireFox is using SpiderMonkey. The main reason I only support one browser is that I don't have that much time.

**Comment by DjDiabolik** [comment]
mmmmmm.... very interesting.... at this point you suggest to use Chrome because you don't have time to test if all it's working also in other browser ?

If yes i can say i currently use all setup on firefox and tampermonkeys and apparently all it's working whitout any issue or critical issue....

If you sugget violentmonkeys... violentmonkeys it's also released for firefox and i thinks i can tryed to disabled tampermonkeys and try to use this for about some days......

**Comment by jspenguin2017** [comment]
@DjDiabolik What if it doesn't always work? I don't want to fix it.

**Comment by jspenguin2017** [comment]
Also, I will be chasing the latest ECMAScript standard that Chrome supports, which means it can throw syntax error in FireFox.

**Comment by DjDiabolik** [comment]
Oh... the current version it's work on firefox... this future version i don't know and if not working i thinks i try to found an alternative for firefox.....

**Comment by jspenguin2017** [comment]
@DjDiabolik We have one: https://xuhaiyang1234.gitlab.io/AAK-Cont/

**Comment by DjDiabolik** [comment]
Lol i know this configuration....... i have tryed to setup that but for moment i prefer to use ublock protector ways. How i have already says.. apprently i don't find problems and all it's work whitout any problems :)

The next future.... i don't know :)

**Comment by jspenguin2017** [comment]
@DjDiabolik I'm not going to stop you from using unsupported setup, but do not open issue before testing on the standard setup.

**Comment by DjDiabolik** [comment]
But i'm not here for ask support... i'm here only to know because you suggest a single solution and now i know because you can't have time to test all setup whit all different browser and script manager...

I also ever says.... for moment apparently on firefox + violentmonkeys and all currently setup all it's working. and now i know If i have problems whit this setup you can't be helped whit that........

**Comment by jspenguin2017** [comment]
Oh, this is interesting, need to benchmark it out. 
https://github.com/gorhill/uBlock/blob/master/src/js/ublock.js#L51

**Comment by jspenguin2017** [comment]
Extra: A fun challenge for you https://github.com/jspenguin2017/AdBlockChallenge#adblock-challenge

**Comment by okiehsch** [comment]
https://github.com/jspenguin2017/AdBlockChallenge#ublock-origin-bab-defuserjs-bypassing-nightmare-mode


`jspenguin2017.github.io##script:inject(abort-on-property-write.js, Math.floor)`  :wink:

**Comment by jspenguin2017** [comment]
@okiehsch Wow, what?! I cached a reference to the good Math...

**Comment by okiehsch** [comment]
Well, this will obviously never work in real world cases anyway ,because of site breakage, but your rules
didn't mention that.

**Comment by jspenguin2017** [comment]
I explicitly cached the reference to the good Math, somehow BlockAdBlock refuses to use it... Good job on it 👍 
I'm not sure if it will cause breakage as I don't think many pages use Math.floor.

**Comment by okiehsch** [comment]
More than you think, I tried this fix with a few sites to circumvent different anti-adblock scripts, but it always lead to severe site breakage on my end.

**Comment by jspenguin2017** [comment]
@okiehsch Anyway, it's fixed... 
<details>

![image](https://cloud.githubusercontent.com/assets/7283682/26748250/3d95cbb8-47b9-11e7-9866-6c077e23aef6.png)

</details>

**Comment by okiehsch** [comment]
Can I use any `script:inject` that is part of uBO-ressources?

**Comment by jspenguin2017** [comment]
You can use custom ones as well.

**Comment by okiehsch** [comment]
No need. `jspenguin2017.github.io##script:inject(setInterval-defuser.js, (), 1000)`

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/AdBlockChallenge/commit/4c0176b66f3980dfb8fe2d351d7b8fc6dae2b4f0

**Comment by okiehsch** [comment]
Well, `Math.floor` and  `setInterval`. were the two obvious ways to circumvent and you clearly only forgot about `setInterval`, now I don't have a solution.
Good job.

**Comment by jspenguin2017** [comment]
Looks like if we want local `i`, either way is the same. 
![image](https://cloud.githubusercontent.com/assets/7283682/26763884/fdc78bbe-4918-11e7-97b1-0534ebfdcd5a.png)

**Comment by jspenguin2017** [comment]
Switching to algorithm 2 😄 
![image](https://cloud.githubusercontent.com/assets/7283682/26764075/efc5b9a6-491c-11e7-94d5-a18e817fc814.png)

**Comment by jspenguin2017** [comment]
WOW, new `a.domInc` is two times faster
![image](https://cloud.githubusercontent.com/assets/7283682/26764952/b9cac848-492e-11e7-8ba7-d194a3d023f8.png)

**Comment by jspenguin2017** [comment]
Not a big improvement, but it's worth it. 
![image](https://cloud.githubusercontent.com/assets/7283682/26765537/e8955664-493a-11e7-8229-0e845393ca12.png)

**Comment by epicgirl1998** [comment]
these "couple milliseconds faster" microbenchmarks are making me sick

i think you are doing your codebase a big misfavor by making non-obvious (confusing and less readable) and engine-specific (what if they're slower in other browsers?) micro-optimizations instead of going after what's actually slowing it down

inefficient code will be inefficient regardless of the language features used, and different loop styles and caching regexps are exactly the kind of pointless optimizations i hate

javascript should come with an instruction manual that has useful tips like "microbenchmarks aren't representative of real performance" and "simplifying and removing code and just doing less is the best optimization technique"

and something like "think about what the code does, not what the compiler does"

> Also, I will be chasing the latest ECMAScript standard that Chrome stable supports

this makes no sense as new features are usually the least optimized ones, unlike older features that have had years of optimization work put towards them and have established coding patterns and conventions to actually optimize for

**Comment by jspenguin2017** [comment]
@epicgirl1998 If I loop it more, it would be longer, it's not milliseconds, it's percentage. There are many complex code that I cannot remove, and I don't have enough tests to optimize what is actually slowing things down. Also, I don't care if it is slower in other browsers as I don't support them anyway. 
New features are less optimized but that will change, I want to write the latest JavaScript, that's all.

**Comment by jspenguin2017** [comment]
@epicgirl1998 I am thinking what the code does, it now compares integers instead of strings, which speeds it up significantly. I tested the loop structure because `let` would create a new variable for each iteration if the variable's reference is kept. But it looks like V8 is able to optimize it. I only tested things I think I am responsible for, I won't try to optimize things that I think it's V8's job to properly compile.

**Comment by uBlock-user** [comment]
> these "couple milliseconds faster" microbenchmarks are making me sick

Then don't look at it instead of spewing a temper tantrum like this. Such small optimizations are making the codebase better and simplied with each update. Those milliseconds collectively can make a big difference when you measure the page load time, so nothing is insignificant here.

**Comment by jspenguin2017** [comment]
Maybe having compilers written in C# was a mistake...

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/27061945-eea0aafc-4fa4-11e7-8df7-7d58eff329b7.png)
![image](https://user-images.githubusercontent.com/7283682/27061960-00cd3ee8-4fa5-11e7-9118-59c905a31de0.png)
![image](https://user-images.githubusercontent.com/7283682/27061963-06bf6d30-4fa5-11e7-82bb-702dc71321bf.png)
![image](https://user-images.githubusercontent.com/7283682/27061969-125538e6-4fa5-11e7-80c4-e025b1310699.png)

Over half of the script execution time is used to load jQuery... I think I should lazy load jQuery...

**Comment by jspenguin2017** [comment]
Compile time from minified script: change too tiny, and I would need a non-minified version for development, too little gain, keeping as-is. 
![image](https://user-images.githubusercontent.com/7283682/27062232-e4fd7938-4fa6-11e7-82cb-3590e6602bef.png)

**Comment by jspenguin2017** [comment]
Lazy loading jQuery, execution time reduced by over 2.5 times on websites that doesn't need jQuery. 
![image](https://user-images.githubusercontent.com/7283682/27256651-cecec4ec-5379-11e7-8625-67fbe74d9ef6.png)

**Comment by jspenguin2017** [comment]
I feel like an idiot... Just realized that jQuery is used in generic solutions... Need to fix that first...

**Comment by jspenguin2017** [comment]
OK, that's changed... Hopefully I didn't break anything while refactoring the code...

**Comment by jspenguin2017** [comment]
One last test left 😮

**Comment by jspenguin2017** [comment]
Only a few Core functions to go

**Comment by jspenguin2017** [comment]
`split` is significantly slower. Time to optimize the Core. 
![image](https://user-images.githubusercontent.com/7283682/27257932-c3f7d684-53a7-11e7-9853-1b733c2e0799.png)
