### ISSUE TITLE
yalujailbreak.net

### ISSUE THREAD

**Issue by LaxusiC** [jspenguin2017/uBlockProtector#250]
Test link: [Here](https://yalujailbreak.net/ios-10-3-3-beta-2/)

Screenshot: https://prnt.sc/fe6d8r

**Comment by uBlock-user** [comment]
Filter `yalujailbreak.net##script:inject(noeval.js)`

**Comment by jspenguin2017** [comment]
Thanks.

**Comment by LaxusiC** [comment]
I still getting the warning popup, already used latest version

**Comment by uBlock-user** [comment]
Subscribe to uBlockProtectorList and then try again.

**Comment by LaxusiC** [comment]
when i click subscribe uBlockProtectorList it does nothing, have to add as custom list. It does bypass on this site linkneverdie.com but not on yalujailbreak.net

**Comment by jspenguin2017** [comment]
The site works for me, after the fix.

**Comment by LaxusiC** [comment]
Updated so many times, doesn't work for me :(

http://prntscr.com/ffphrg

**Comment by jspenguin2017** [comment]
@LaxusiC Looks like you are using uBlock, which is not supported. Only uBlock Origin is supported.
