### ISSUE TITLE
blogaziendali.com

### ISSUE THREAD

**Issue by ale5000-git** [jspenguin2017/uBlockProtector#251]
Test link: http://blogaziendali.com/2016/05/30/come-fare-il-backup-wordpress/

After a certain amount of time (a bit) I got this screen: ![screen](https://cloud.githubusercontent.com/assets/15793015/26636777/053e3936-461e-11e7-9aab-ffbf1dd43574.png)

I'm not sure if it can be considered an ads but I find it annoying.

**Comment by jspenguin2017** [comment]
What that says? If it's not anti-adblock then you should contact EasyList.

**Comment by Dibbyo456** [comment]
This works : `blogaziendali.com###om-m5xo969omjexvw7b
`

**Comment by jspenguin2017** [comment]
![image](https://cloud.githubusercontent.com/assets/7283682/26637217/1c93fc7a-45dc-11e7-9363-8b3ea283d0c1.png)
It doesn't look like anti-adblock, more of an ad. Closing as invalid.

**Comment by jspenguin2017** [comment]
Yea, it's a new ads serving domain `||optnmnstr.com/app^`. Probably better for EasyList to deal with this kind of stuff.

**Comment by ale5000-git** [comment]
@jspenguin2017: Instead forced FaceBook likes where should go?

**Comment by Dibbyo456** [comment]
@jspenguin2017 it's not an ad serving domain. it's actually a email building list / offers pop-ups.. which sometimes is very useful, I think this is why they did not added on on EasyList.

**Comment by jspenguin2017** [comment]
@Dibbyo456 Huh, in this case we'll include this in our list.

**Comment by uBlock-user** [comment]
It's an ad/tracking server, so Easylist will deal with this. Report it on their forums - https://forums.lanik.us/

**Comment by jspenguin2017** [comment]
@ale5000-git Forced Facebook like? How is that possible?

**Comment by ale5000-git** [comment]
Fixed.

**Comment by ale5000-git** [comment]
@jspenguin2017: Maybe what I said can be misunderstood I didn't mean that it auto-like but just that it doesn't give access to the download until you like it.
I have created a new issue.
