### ISSUE TITLE
karibusana.org

### ISSUE THREAD

**Issue by ale5000-git** [jspenguin2017/uBlockProtector#253]
Test link: http://www.karibusana.org/2014/02/creare-un-backup-di-wordpress-con-backwpup/

Screenshot before: ![screen-before](https://cloud.githubusercontent.com/assets/15793015/26647103/809ba008-463e-11e7-9ac4-95bf2438c94e.png)
Screenshot after: ![screen-after](https://cloud.githubusercontent.com/assets/15793015/26647107/845488ae-463e-11e7-83b9-af7c5cb69f32.png)

It do not give access to the download until you give a like or a tweet or a +1.

**Comment by jspenguin2017** [comment]
Ah, this should be an easy fix. Let me have a look, I remember something like this...

**Comment by jspenguin2017** [comment]
Unfortunately, this is just that much different than the other sample I have so I can't make it generic. It's rather simple, just 2 lines of code.

**Comment by jspenguin2017** [comment]
The plugin is called Social Locker, I don't have enough sample to make it generic yet...

**Comment by uBlock-user** [comment]
It's that BizPanda social locker shit.

**Comment by uBlock-user** [comment]
WE came across such case once.

**Comment by uBlock-user** [comment]
Yep this one - https://github.com/jspenguin2017/uBlockProtector/issues/165

**Comment by jspenguin2017** [comment]
Yea, the other one has different style, basically we just need to force a style on it, if it starts to use mutation observer to enforce the style then it'll be a pain in the rear. 

Hum, I solved it different last time... 
```
    a.ready(() => {
        a.$(".onp-sl-social-buttons-enabled").remove();
        a.$(".onp-sl-content").show();
    });
```

**Comment by uBlock-user** [comment]
Do we need those lines if we `noAccess` to bizpanda ? That should break the script.

**Comment by jspenguin2017** [comment]
@uBlock-user Yes, or it will show the lock box too, the script is inline for this.

**Comment by jspenguin2017** [comment]
@ale5000-git Thanks for these reports, they are awesome 😄

**Comment by ale5000-git** [comment]
I like to help removing annoying things, I hope to don't bother you too much :)
