### ISSUE TITLE
lukkr.com

### ISSUE THREAD

**Issue by ale5000-git** [jspenguin2017/uBlockProtector#254]
Test link: https://lukkr.com/anti-adblock-script/

Probably it is enough to block this script: lukkr.com/website/pf.js
Or maybe replace it with a blank script.

It should work on all sites that use it.

**Comment by uBlock-user** [comment]
It also auto refreshes itself which is another nagging feature along with others.

**Comment by uBlock-user** [comment]
ContextMenu is also blocked.

**Comment by uBlock-user** [comment]
For anti adblock - `@@||lukkr.com^$elemhide`

**Comment by uBlock-user** [comment]
The whole website is shit, why would anyone bother to visit it is beyond me and I doubt anyone would use anything from that. Might as well block the entire website.

**Comment by jspenguin2017** [comment]
OK, I'll have a look. Do you have a few sample websites that uses their detection script?

**Comment by ale5000-git** [comment]
@jspenguin2017: Currently no, just the sample page.

@uBlock-user: Unfortunately internet is full of copied bad code.

**Comment by jspenguin2017** [comment]
I guess `||lukkr.com/website/pf.js` would do the job. That file is a bootstraper that loads `lukkr.com/website/sync.js` and `lukkr.com/tags/side.js`.

**Comment by jspenguin2017** [comment]
Unpacking the code, it gives: 
```JavaScript
var mincodrzdf = "d330dfhdf3";
var lkrdom = "//lukkr.com";
var fsdxvch = "403dfsd.js";
var vrshrsere = "vr/vrshrsere";
var lrhstr = "/sbar/sb/";
var lrhropnx = "/opn/sb/";
var drdfodrzdf = "d353h3dfhdf3";
var xvdhflhd3 = "lzidlhfhdf3dd";
var difrentdd3x = "supzer3y30v.js";
var liyvdlgdtzbd = "quitzietyvd3";
(function mrvrshr() {
    var lrsync1 = document.createElement('script');
    lrsync1.type = 'text/javascript';
    lrsync1.async = true;
    lrsync1.src = lkrdom + lrhropnx + vrshrsere + cnctlr + 'lrss' + fsdxvch;
    var lrsync2 = document.getElementsByTagName('script')[0];
    lrsync2.parentNode.insertBefore(lrsync1, lrsync2)
})();

function mcodrldr() {
    var lrsync3 = document.createElement('script');
    lrsync3.type = 'text/javascript';
    lrsync3.async = true;
    lrsync3.src = lkrdom + lrhropnx + vrshrsere + cnctlr + fsdxvch;
    var lrsync4 = document.getElementsByTagName('script')[0];
    lrsync4.parentNode.insertBefore(lrsync3, lrsync4)
}
```

Which loads even more scripts... Good job on packing your code 50 layers, we'll just block the bootstraper.

**Comment by uBlock-user** [comment]
@ale5000-git Make it "intentionally" bad copied code.

**Comment by ale5000-git** [comment]
@uBlock-user: Well, there are the ones that do it intentionally because they don't care and the ones that do it because they aren't good programmer so internet is full of bad code; fortunately there are also good programmer, just few :)

PS: Fixed.
