### ISSUE TITLE
receive-a-sms.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#257]
Test link: https://receive-a-sms.com/USA

Screenshot: 
<img width="276" alt="przechwytywanie" src="https://cloud.githubusercontent.com/assets/18214146/26707581/2847f0b0-4746-11e7-974e-3413c7b3e9e2.PNG">

**Comment by jspenguin2017** [comment]
Huh, interesting... nooping doesn't seem to work... 
`||receive-a-sms.com/showads.js$xmlhttprequest,redirect=noopjs`
Tried `nooptext` and `noopframe`... I guess we'll have to patch jQuery.

**Comment by jspenguin2017** [comment]
Pretty simple detection script...
```JavaScript
$(document).ready(function() {
    $.ajax('showads.js').fail(function(d) {
        if (d.status === 0 || d.statusText == 'error') {
            $('html').addClass('ab');
            $(".ab").css("display", "inline-block");
            window.location.href = "http://receive-a-sms.com/adblock";
        }
    });
});
```
I guess we can just white list that...

**Comment by uBlock-user** [comment]
Will that [work](https://github.com/reek/anti-adblock-killer/blob/master/anti-adblock-killer.user.js#L4716) ?

**Comment by jspenguin2017** [comment]
@uBlock-user [Nope](https://github.com/jspenguin2017/uBlockProtector/blob/master/uBlockProtector.user.js#L2327)

**Comment by jspenguin2017** [comment]
@uBlock-user I was tinkering around this afternoon and I manage to break `setTimeout-defuser` and `bab-defuser`... I think the resource file needs an update... https://github.com/jspenguin2017/AdBlockChallenge#adblock-challenge

**Comment by uBlock-user** [comment]
@jspenguin2017 Are you saying that those two scriptlets can be bypassed ?

**Comment by jspenguin2017** [comment]
@uBlock-user Yes, I have a theoretical fix, didn't test it out yet, go to my demo pages and try the scriptlets out.

**Comment by uBlock-user** [comment]
@jspenguin2017 I did. You should report this to gorhill.

**Comment by jspenguin2017** [comment]
@uBlock-user I think he knows it, it'll be really heavy to properly fix this, so I guess we should have another scriptlet that blocks the bypass when needed. Last time I tried to implement an anti-bypass it didn't go well, I'll try again later. 
I'll report to him once I have a working prototype.

**Comment by uBlock-user** [comment]
So can you do something about that redirect ?

I almost succeeded with `(abort-on-property-read.js, $.ajax)` but the messages won't load.

**Comment by uBlock-user** [comment]
This should help - https://gist.github.com/zacharytamas/082e538784ebe07e40f9

**Comment by ghajini** [comment]
If I click "click here to return", it works

**Comment by uBlock-user** [comment]
No it takes you to the homepage.

**Comment by szymon1118** [comment]
What about: `@@||receive-a-sms.com/showads.js` ?

**Comment by jspenguin2017** [comment]
@uBlock-user Ohhhh, that'w worth a try.

**Comment by jspenguin2017** [comment]
@uBlock-user I think that rule would break jQuery... It's really hard to patch jQuery, but it can be done with `a.make$`, but it is really heavy...

**Comment by uBlock-user** [comment]
@jspenguin2017 Did you try https://github.com/jspenguin2017/uBlockProtector/issues/257#issuecomment-305696488 ?

**Comment by jspenguin2017** [comment]
@uBlock-user I don't think that would work because it is not altering the real window. I'll try it out though. 

BTW, I think I can bypass WebRTC blocking of uBO Extra, I'll test it out.

**Comment by uBlock-user** [comment]
@jspenguin2017 `nowebrtc.js` has already been bypassed and no longer in use, so save yourself the trouble. Gorhill recently implemented a CSP scriptlet which he will use for WebRTC or any other such stuff wherever necessary.

This might help - http://userscripts-mirror.org/topics/121108

**Comment by jspenguin2017** [comment]
@uBlock-user Are you sure CSP can restrict WebRTC? https://content-security-policy.com/

**Comment by uBlock-user** [comment]
It already is doing via connect-src policy.

**Comment by uBlock-user** [comment]
For a demo - 

add  this filter - ||$websocket
Visit http://www.xnxx.com/
Open console and you will see this - https://i.gyazo.com/dfabf27dc0a880e7c1bcbad9d905ce3d.png

**Comment by jspenguin2017** [comment]
Ah, OK. 👍

**Comment by uBlock-user** [comment]
Unfortunately it's doing via a wrapper so it won't be as effective as the real thing.

**Comment by uBlock-user** [comment]
List of websites running WebRTC connections behind-the-scenes - https://publicwww.com/websites/RTCPeerConnection/

**Comment by jspenguin2017** [comment]
I don't think the Gist you posted will work, since the window is in a closure... 
https://gist.github.com/zacharytamas/082e538784ebe07e40f9

**Comment by jspenguin2017** [comment]
I'm afraid there is just no way to override it... 
![image](https://cloud.githubusercontent.com/assets/7283682/26733128/177aa09e-4777-11e7-9119-02192f66d047.png)

**Comment by uBlock-user** [comment]
So how will you foil the redirect ?

**Comment by jspenguin2017** [comment]
White list?

**Comment by jspenguin2017** [comment]
Sorry I'm out of solution... have to white list I think.

**Comment by uBlock-user** [comment]
It's first-party whitelist so it's fine.

**Comment by uBlock-user** [comment]
`receive-a-sms.com##script:inject(abort-on-property-write.js, $.ready)` seems to work.

**Comment by jspenguin2017** [comment]
Looks like it's still working. Closing.

**Comment by uBlock-user** [comment]
`receive-a-sms.com##script:inject(abort-current-inline-script.js, $, adblock)`

Works perfectly!

**Comment by jspenguin2017** [comment]
I see, the scriptlet takes in a global hook and a current script niddle. Brilliant.

**Comment by adreporter** [comment]
@jspenguin2017 
https://receive-a-sms.com/USA
It doesn't work anymore.

**Comment by jspenguin2017** [comment]
Well, `abort-current-inline-script` is as unstable as `a.beforeScript`... That's disappointing...

**Comment by uBlock-user** [comment]
`receive-a-sms.com##script:inject(abort-current-inline-script.js, $, adblock)` still works for me.

@okiehsch
