### ISSUE TITLE
eateseseirimastoconharry.com

### ISSUE THREAD

**Issue by marcomg** [jspenguin2017/uBlockProtector#259]
Before opening an issue, you MUST read the contribution guideline. Failure to do so may result in a ban. 

Test link: http://www.eateseseirimastoconharry.com/

Screenshot: https://s26.postimg.org/jm9pylzrd/Senza_titolo-1.jpg

Add everything else that you believe to be useful below:

**Comment by jspenguin2017** [comment]
It's caught in Script, are you sure you installed it right?

**Comment by marcomg** [comment]
Sorry, oops I had to clear uBlock cache and restart browser...
Now it works 👍 
Sorry and good evening ;)

**Comment by uBlock-user** [comment]
Yep, patched by the Script.
