### ISSUE TITLE
newyorker.com

### ISSUE THREAD

**Issue by ale5000-git** [jspenguin2017/uBlockProtector#260]
Test link: http://www.newyorker.com/

Screenshot with uBlock disabled: ![ublock-disabled](https://cloud.githubusercontent.com/assets/15793015/26741955/cf1c8f32-47db-11e7-9326-06998431519c.png)

Screenshot with uBlock enabled: ![ublock-enabled](https://cloud.githubusercontent.com/assets/15793015/26741954/cf193044-47db-11e7-800e-12980a0d829d.png)

The normal ads get replaced by other ads when ublock is enabled.

**Comment by jspenguin2017** [comment]
I can't reproduce it. 
![image](https://cloud.githubusercontent.com/assets/7283682/26742304/775010bc-479a-11e7-87ea-4f82a18aedcd.png)

**Comment by ale5000-git** [comment]
@ jspenguin2017: It is intermittent, if you refresh the page sometimes they appears and sometimes not.

**Comment by ale5000-git** [comment]
@jspenguin2017: It fix the problem.

**Comment by uBlock-user** [comment]
Can't reproduce.

Ads are inserted as inline-scripts - `||newyorker.com/wp-content/assets^$inline-script`

**Comment by ale5000-git** [comment]
@uBlock-user: I just open the site and press Ctrl+r 2 or 3 times and I almost always see  the problem.

PS: Fixed in the latest version.

**Comment by uBlock-user** [comment]
I dont see it, but it does try to load ad banners and other crap through that `/wp-content/assets` folder.
