### ISSUE TITLE
themelot.net Block Pop-up

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#263]
Ad Pop-ups.

Test link: https://themelot.net/adlinkfly-v3-7-2-monetized-url-shortener.html

Screenshot: 

Add everything else that you believe to be useful below: Does not always shows, there might be a timer delay.

**Comment by ghajini** [comment]
Report this to easylist or use no poup feature on ublock origin..... Pls read contribution guidelines of this repository.....

**Comment by Dibbyo456** [comment]
@ghajini YES there is. Like I said, it's sometimes.

**Comment by ghajini** [comment]
@jspenguin2017 please update `purpose of this repository `  in `simple language ` not like antiadblock defused for ublock...users might open issues regarding ads/popups......

**Comment by uBlock-user** [comment]
Popups are third-party and based on popads third-party script.

Instead of blocking random domains every now and then I suggest you subscribe to - https://github.com/Yhonay/antipopads

It aut-updates every 2 hours or so.

**Comment by uBlock-user** [comment]
@ghajini We do patch popups which are used to circumvent uBO and open connections to ad-servers, so it's fine.

**Comment by Dibbyo456** [comment]
@uBlock-user Thank you.. adding it. :)

**Comment by ghajini** [comment]
Yes....herein this case no circumvention or antiadblock message is displayed.......
one can't make another easylist for that purpose.....

**Comment by jspenguin2017** [comment]
@ghajini What's wrong with you? Can you chill if you don't have anything constructive to say?

**Comment by Dibbyo456** [comment]
@jspenguin2017 I was gonna reply him the same, but didn't know how you might have reacted.

**Comment by ghajini** [comment]
Sorry I will not react more then.......my purpose is only to said ad blocking filters to be reported to easylist and maintain issues solely to antiadblock workarounds in this repo.....also I know already filters needed for this site as of uBlock-user reported......
