### ISSUE TITLE
[Off-Topic] Google exchange rates graph breaks

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#264]
Test link: [Here](https://www.google.co.in/search?q=%24+2%2C615&rlz=1C1CHBD_enIN747IN747&oq=%24+2%2C615&aqs=chrome..69i57&sourceid=chrome&ie=UTF-8)

Screenshot: [Here](http://prntscr.com/fg1wtv)

I'm not sure, but I think it's causing by EasyPrivacy. I am not familiar with EasyList forums, I did reported this, but I'm not sure I posted in the correct category. is there any temporary patch, without compromising privacy?

**Comment by uBlock-user** [comment]
Can't reproduce. The issue is on your end and nothing to do with uBlockProtector either.

Some filter is blocking the image from `*.google.co.in/finance` URL. Run the logger and find out, that's the first thing you're supposed to do when something breaks.

**Comment by jspenguin2017** [comment]
Works for me.

**Comment by Dibbyo456** [comment]
@uBlock-user @jspenguin2017 I'm asking this here, because it's not a Topic issue neither AdBlock Detection issue.

Go [Here](https://null-24.com/product-options-woocommerce-v4-133/?nocache) click any links bellow the "Other Free Download Links" it will take you to a 10 sec timer page.

1) Patch the timer and redirect to the destination?
or
2) Disable this [JavaScript](http://prntscr.com/fi49oz) for the entire site, which causing the redirection ?

There is a couple of other sites, who uses the same technique so any change making it globally ?

**Comment by jspenguin2017** [comment]
@Dibbyo456 That's an easy fix, I just need to replace the URLs with real ones.

**Comment by jspenguin2017** [comment]
@Dibbyo456 It's patched, don't hijack issues again.

**Comment by uBlock-user** [comment]
Avoid such baiting websites if you can. Their appearance itself signals how shady and nasty they are.

**Comment by Dibbyo456** [comment]
@jspenguin2017 "Direct Download Link" also causing the same redirection. [Test Link](https://null-24.com/events-schedule-v2-0-4-2-wordpress-plugin/)
