### ISSUE TITLE
onhax.me - pop up ads

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#265]
[Test link](https://onhax.me/teamviewer)

Anti Pop-Ads Filter also used which was suggested by @uBlock-user but does not seem to work.

`||$third-party,script,domain=onhax.me`

does not work.

**Comment by uBlock-user** [comment]
Can't reproduce.

> Anti Pop-Ads Filter also used which was suggested by @uBlock-user but does not seem to work.

There's no one size shoe that will fit all. I suggest solution on case by case basis. Also Pop-Ads popups are third-party in nature. The repo is for blocking popups induced by third-party domains only, not first-party popups inlined by the website itself.

**Comment by Dibbyo456** [comment]
@uBlock-user **Click on Mirror**

**Comment by uBlock-user** [comment]
I did and it takes me to https://uplod.ws/8kvgwfp1gmwy

**Comment by uBlock-user** [comment]
If `Download Our Offers` is ticked - > popups appear.

**Comment by uBlock-user** [comment]
Script that induces popups

```javascript
 $(document).ready(function() 

{
              $('#downloadBtnClickOrignal').hide()

              $('#downloadBtnClick').on

('click', function (v) {

                  v.preventDefault();
                  if 

($('#chkIsAdd').prop("checked")) {
                      //  window.location.replace

($('#addLinkBtn').val());
                      window.open($('#addLinkBtn').val(), 

'_blank');
                  }
                  else {
                      

$('#myDownloadForm').submit();
                  }
              })
              

$('#chkIsAdd').change(function(){
                  if ($('#chkIsAdd').prop("checked")) {
    

                  $('#downloadBtnClickOrignal').hide();
                      

$('#downloadBtnClick').show();
                  }else{
                      

$('#downloadBtnClick').hide();
                      $('#downloadBtnClickOrignal').show();
   

               }
              })
          });
```

**Comment by uBlock-user** [comment]
Try - `uplod.ws##script:inject(abort-on-property-read.js, $.ready)`

**Comment by Dibbyo456** [comment]
@uBlock-user Worked!

**Comment by Dibbyo456** [comment]
Nah.. Still shows.

**Comment by Dibbyo456** [comment]
@uBlock-user [Screenshot 1](http://prntscr.com/fghrm4) - [Screenshot 2](http://prntscr.com/fghsev)

**Comment by uBlock-user** [comment]
I cannot reproduce any popups at onhax.me. My filter is for `uplod.ws` only and that works.

**Comment by ghajini** [comment]
@Dibbyo456 If you are interested in https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-popups

**Comment by Dibbyo456** [comment]
@ghajini No-Popups are enabled by default, but still the sites bypassing it.

**Comment by uBlock-user** [comment]
Try -` onhax.me##script:inject(abort-on-property-read.js, open)` That should kill any popups/unders.

**Comment by Dibbyo456** [comment]
Worked.

**Comment by jspenguin2017** [comment]
@uBlock-user I don't think you can modify jQuery easily, both page would have their popup blocked by nooping open.

**Comment by Dibbyo456** [comment]
But it did worked!

**Comment by jspenguin2017** [comment]
@Dibbyo456 Oh, wait, `abort-on-property-read` does work, `write` doesn't: https://github.com/uBlockOrigin/uAssets/blob/5e429e22b959a4c516f12364a905650c405c7043/filters/resources.txt#L1619

**Comment by jspenguin2017** [comment]
Blowing up `open` will break share buttons, I'll apply a filter instead.

**Comment by jspenguin2017** [comment]
The script on `uplod.ws` formats to this: 

```JavaScript
$(document).ready(function() {
  $("#downloadBtnClickOrignal").hide();
  $("#downloadBtnClick").on("click", function(types) {
    types.preventDefault();
    if ($("#chkIsAdd").prop("checked")) {
      $("#addLinkBtn").val();
      window.open($("#addLinkBtn").val(), "_blank");
    } else {
      $("#myDownloadForm").submit();
    }
  });
  $("#chkIsAdd").change(function() {
    if ($("#chkIsAdd").prop("checked")) {
      $("#downloadBtnClickOrignal").hide();
      $("#downloadBtnClick").show();
    } else {
      $("#downloadBtnClick").hide();
      $("#downloadBtnClickOrignal").show();
    }
  });
});
```

**Comment by jspenguin2017** [comment]
The other time `$.ready` is called is also not going good stuff, so yea, looks like blowing up `$.ready` is OK in this case.

**Comment by uBlock-user** [comment]
@jspenguin2017 The filter I posted works in this case but not in the case of `receive-a-sms.com` which is similar and it's not breaking anything visibly, but I will leave that upto you if you want to inspect.
