### ISSUE TITLE
ihax.fr

### ISSUE THREAD

**Issue by xitero** [jspenguin2017/uBlockProtector#266]
Test link: https://ihax.fr/

Screenshot: https://image.prntscr.com/image/9546f05ab691499bafab296efe5895b5.png

Add everything else that you believe to be useful below: 
To open any page of this site you need to disable uBlock Origin.

**Comment by jspenguin2017** [comment]
You have not properly installed uBlock Protector. 
![image](https://user-images.githubusercontent.com/7283682/26853487-71e81844-4acf-11e7-88f7-0128f6faa7df.png)

**Comment by uBlock-user** [comment]
Patched via Script. The issue lies within your setup.

**Comment by xitero** [comment]
I use your filter in uBlock Origin on Google Chrome, I even tried to reinstall the extension and activate its filter again. In fact, I cleared the cache and updated all the filters, but it did not help. What else can I do?

**Comment by jspenguin2017** [comment]
https://jspenguin2017.github.io/uBlockProtector/

**Comment by xitero** [comment]
Ok, after installing Violentmonkey and the script, the lock does not appear anymore. I did not know it was necessary to have the script either, thank you anyway.
