### ISSUE TITLE
ilgazzettino.it

### ISSUE THREAD

**Issue by MrcRel** [jspenguin2017/uBlockProtector#268]
When i open an article appears the blue banner, that ask me to disable adblock, and if i not disable adblock, i can read at maximum 5 articles.

I'm using:
- uBlock Protector Script v8.22
- Violent Monkey
- Chromium

Test link: 
[http://www.ilgazzettino.it/nordest/udine/carro_armato_italia_sequestro_polizia_austria_autostrada-2488271.html](http://www.ilgazzettino.it/nordest/udine/carro_armato_italia_sequestro_polizia_austria_autostrada-2488271.html)

Screenshot: 
https://s23.postimg.org/7hzppeeej/image.png
https://s23.postimg.org/y4c6ediln/image.png

**Comment by jspenguin2017** [comment]
What about `ilgazzettino.it###overlay_bloccante`

**Comment by jspenguin2017** [comment]
NVM, I'll block the detection script instead.

**Comment by uBlock-user** [comment]
Anti adblock script http://utils.cedsdigital.it/checkSubscription/checkSubscription.js

**Comment by uBlock-user** [comment]
I'm not sure that filter would work, it's loaded inline.

**Comment by jspenguin2017** [comment]
Yea, I decided to block the detection script instead.

**Comment by uBlock-user** [comment]
No, I meant the detection script filter, it's not loaded as first party, rather inlined, so it won't appear in the logger as it gets loaded when the inline-script is loaded.

**Comment by uBlock-user** [comment]
Run the logger and put "checkSubscription.js" in the filter see if you can find it there.

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/26890210-023bbed4-4b6e-11e7-9f79-4d0ed6a1a268.png)

**Comment by uBlock-user** [comment]
It only appears the first time, once it's loaded, it won't appear in the logger on subsequent refreshes.

**Comment by jspenguin2017** [comment]
@uBlock-user That's cached, Chrome won't trigger WebRequest event if the file can be loaded from disk or memory.

**Comment by uBlock-user** [comment]
Ah yes, so I will have to clear the cache and so it will appear again and then filter will block it.

**Comment by jspenguin2017** [comment]
Yes. Once it is blocked, it will show up every time.

**Comment by uBlock-user** [comment]
No, I'm refreshing the page, read again I've edited it. Refresh forces a new copy regardless of the cache present or not.

**Comment by uBlock-user** [comment]
This is what led to me to question why it's happening as it's not supposed to load from cache if the page is refreshed.

**Comment by jspenguin2017** [comment]
@uBlock-user If you press `ctrl+F5` then it asks Chrome to load a new copy, refresh or `F5` won't load everything from source again.

**Comment by jspenguin2017** [comment]
You can tick this settings so debugging is easier: 
![image](https://user-images.githubusercontent.com/7283682/26890566-31493cc8-4b6f-11e7-87ae-58f07e7744da.png)

**Comment by uBlock-user** [comment]
@jspenguin2017 Are you sure ? Because so far I have tested I have never seen any docs loaded from cache when I press Refresh or ctrl +F5. Both do the same thing.

**Comment by jspenguin2017** [comment]
@uBlock-user Why don't you clear the cache and test out if the rule reliably works?

**Comment by uBlock-user** [comment]
Well it's working if I open it in the new tab, so you're right cache handling is weird, and I will leave it at that.

**Comment by jspenguin2017** [comment]
Still works. Closing.
