### ISSUE TITLE
windowsreport.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#269]
[Test link](http://windowsreport.com/windows-10-email-client-apps/)

[Screenshot](http://prntscr.com/fh1gbp)

Sometimes times show, sometime does not.

**Comment by jspenguin2017** [comment]
I feel Google's Funding Choices is kicking in, so many websites with similar detection methods... 
![image](https://user-images.githubusercontent.com/7283682/26889353-2e706e94-4b6b-11e7-8c54-67a1937c7d90.png)

**Comment by jspenguin2017** [comment]
Try `windowsreport.com##script:inject(abort-on-property-read.js, XMLHttpRequest)`

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
The detection is running in the background, doesn't seem to do anything to the page.

**Comment by uBlock-user** [comment]
Mine's different, looks like uBO's CSP policy is kicking in

![](https://i.gyazo.com/6c057f6020ad6363747be127edbbe56e.png)

**Comment by jspenguin2017** [comment]
Huh, it doesn't behave the same way here. I'll just nuke `eval`.

**Comment by uBlock-user** [comment]
Question inlined-script - https://gist.githubusercontent.com/uBlock-user/ab401cfcb77a5ed25bd5a9a29353ca6e/raw/41c55e30949f6de6344ae42b5510f03990f253aa/gistfile1.txt

Can you decipher and tell what's it's doing ?

**Comment by uBlock-user** [comment]
FYI, it's not Google's funding choices as that will not begin before 2018.

**Comment by jspenguin2017** [comment]
I'm still getting ready for Funding Choices, that can be pain in the rear to fight, so I have to make something that kills their script from the root. 

The script probably generates some code and evaluate it. 
![image](https://user-images.githubusercontent.com/7283682/26890035-700d3bdc-4b6d-11e7-8e1b-bd567ec6c9b3.png)

**Comment by uBlock-user** [comment]
Does it check for anti adblock ? I can't find the anti adblock script here.

**Comment by jspenguin2017** [comment]
@uBlock-user It definitely does.

**Comment by Dibbyo456** [comment]
How to block [this](http://prntscr.com/fh1win) ? scroll down a little give it time it will show up.

**Comment by uBlock-user** [comment]
@Dibbyo456 I did everything, I simply cannot reproduce it.

Try - `windowsreport.com##script:inject(overlay-buster.js)`

**Comment by uBlock-user** [comment]
@jspenguin2017 No I meant the script that I specifically posted in https://github.com/jspenguin2017/uBlockProtector/issues/269#issuecomment-306852203 ? Does that script check for adblock ?

**Comment by jspenguin2017** [comment]
@uBlock-user Yes, it does.

**Comment by jspenguin2017** [comment]
@Dibbyo456 Can you try `windowsreport.com##script:inject(silent-noeval.js)`?

**Comment by Dibbyo456** [comment]
@uBlock-user it's partially works. show a flicker then disappear.

**Comment by Dibbyo456** [comment]
@jspenguin2017 Fully Worked!

**Comment by uBlock-user** [comment]
@Dibbyo456 Yes, it's by-design. Killing the eval is the proper solution.

**Comment by gotitbro** [comment]
> FYI, it's not Google's funding choices as that will not begin before 2018.
Google "Funding Choices" is live right now: 
http://www.androidpolice.com/2017/06/01/google-launches-funding-choices-way-users-pay-sites-hide-ads/

Chrome ad blocker/filter will [roll out in 2018](https://www.wsj.com/articles/ad-blockers-say-they-wont-be-replaced-by-google-chrome-ad-filter-1496829601).

**Comment by jspenguin2017** [comment]
@gotitbro That's what I thought! Once Google steps in, if you can't control what the browser receives, it can be a bit tough to patch the anti-adblock.

**Comment by uBlock-user** [comment]
@gotitbro Nope, that's not it. Funding Choices messages won't be intrusive as this one and won't block access to the website. Also this is a pretty old script already. I first encountered it back in March on `comicbook.com` They're using `contributor.google.com/scripts` to check whether something is blocked or not and if it is, then they use random domains of google to display the anti adblock notice and block the entire page, that's not how it's going to be with Funding Choices as they will only display the message and won't be block the access to the page itself.

**Comment by uBlock-user** [comment]
@gotitbro Then it's just as intrusive as others, nothing changed. Google never really gave a thought and made it intrusive, that's a fucking shame!

**Comment by Zhangsun321** [comment]
@jspenguin2017 'network level anti adblock defuser?

**Comment by jspenguin2017** [comment]
@Zhangsun321 Yea, but it's kind of not going well, I can plug the socket onto the local server, but I'm not sure what to do with the socket...

**Comment by Zhangsun321** [comment]
@jspenguin2017  wow...    ok..   so why wont the current 'client' based defuser work on those google popups?
you said google wont let the end user control what gets sent?

**Comment by jspenguin2017** [comment]
@Zhangsun321 Because their code is barely patchable, if they wrap accessing `stop` in a try-catch block, our solution will fail.

**Comment by Zhangsun321** [comment]
ohh... i don't know a thing bout all this...   just know you and @uBlock-user  work is so much appreciated..  you two work on all 3 of the ad block wall defusers..   and I know it is time consuming..
I just spread the word of uboprotect and aak-cont

**Comment by Dibbyo456** [comment]
Thank you!
Spark by Readdle

**Comment by uBlock-user** [comment]
@Zhangsun321 I simply like patching such anti adblock scripts as it's more of a challenge given the possibilities with complexity of javascript and I learn something new in the course.
