### ISSUE TITLE
webcheats.com.br

### ISSUE THREAD

**Issue by xitero** [jspenguin2017/uBlockProtector#270]
When I open any topic, this message appears, which forces me to disable adblock, otherwise I can not access the topics.

I'm using:

- uBlock Origin (Filter uBlock Protector active)
- uBlock Protector Script v8.23
- Violent Monkey
- Chrome

[Test Link](http://www.webcheats.com.br/threads/o-que-existia-antes-do-big-bang-vamos-voltar-pra-l%C3%A1-um-dia.2540165/)

[Screenshot](https://image.prntscr.com/image/838f8418f2fd44748123a08c4330a0ae.png)

**Comment by jspenguin2017** [comment]
I can't quite reproduce it... 
![image](https://user-images.githubusercontent.com/7283682/26892510-ca4bf4be-4b75-11e7-940a-cbc172cf5c18.png)

**Comment by xitero** [comment]
After I cleaned the cookie from the site the message did not appear anymore. Sorry, now I cleaned all the cookies so I should not have this problem with other sites that have already been filtered.

**Comment by uBlock-user** [comment]
Can't reproduce it either.

**Comment by xitero** [comment]
Hey man, the problem came back with this site. I've already tried clearing cookies and caching, the problem continues. I use uBlock Origin with the following Ad filters enabled:
Adblock Warning Removal List
EasyList
UBlock Protector List

I'm also using the 'uBlock Protector Extension' extension.

The problem occurs when trying to get into any link related to that site, even the official website.

**Comment by jspenguin2017** [comment]
Fixed.
