### ISSUE TITLE
androidpolice.com

### ISSUE THREAD

**Issue by Sangenkai** [jspenguin2017/uBlockProtector#271]
Before opening an issue, you MUST read the contribution guideline. Failure to do so may result in a ban. 

Test link: http://www.androidpolice.com/

Screenshot: 
![image](https://user-images.githubusercontent.com/3925535/26904060-ebe346e4-4b7b-11e7-8567-56fd9f275cee.png)

Add everything else that you believe to be useful below:

**Comment by jspenguin2017** [comment]
Eh... Google's Funding Choice...
![image](https://user-images.githubusercontent.com/7283682/26904163-d98a7f36-4b9d-11e7-8918-2a67c16b0f9e.png)
That domain is owned by Google.

**Comment by jspenguin2017** [comment]
```HTML
<script src="https://contributor.google.com/scripts/63f02a1010609dd6/loader.js"></script><script>(function(){var g=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null"; else if("function"==b&&"undefined"==typeof a.call)return"object";return b};var h=function(a){"function"==g(a)&&a()},k=function(a,b,c){a.addEventListener?a.addEventListener(b,c):a.attachEvent&&a.attachEvent("on"+b,c)},l=function(a,b){var c=a.indexOf(b);return 0<=c?parseInt(a.substring(c+b.length,a.indexOf(".",c)),10):-1},m=-2;var n=function(a,b,c,f){var d=new Date;k(b,"load",function(){var e;if(-2===m){e=window.navigator.userAgent;var v=l(e,"MSIE ");m=0<=v?v:0<=e.indexOf("Trident/")?11:l(e,"Edge/")}e=m;-1!==e&&11>=e&&a.a[b.src]>=d?h(f):h(c)});k(b,"error",function(){h(f)})},p=function(a,b,c,f){var d=document.createElement("script");n(a,d,function(){h(c);d&&d.parentNode&&d.parentNode.removeChild(d)},function(){h(f);d&&d.parentNode&&d.parentNode.removeChild(d)});d.async=!0;d.src=b;document.getElementsByTagName("head")[0].appendChild(d)}, q=function(a,b,c,f,d,e){0>=d?h(f):p(a,b,c,function(){e?window.setTimeout(function(){q(a,b,c,f,d-1,e)},e):q(a,b,c,f,d-1)})};var r=new function(){this.a={}},u=function(){if(!/Mobi/i.test(navigator.userAgent)&&!window["turnoff63f02a1010609dd6"]){h(window.stop);document.body&&document.body.parentNode.removeChild(document.body);document.getElementsByTagName("HTML")[0].appendChild(document.createElement("BODY"));var a=document.createElement("IFRAME");a.src="https:\/\/p.w.m80fg.com\/s\/err?w\x3d63f02a1010609dd6";a.style.width="100%";a.style.height="100%";a.style.background="white";a.style.border="none";a.style.zIndex=2147483647;document.body.appendChild(a); a=document.createElement("STYLE");a.innerText="body, html { margin: 0; padding: 0; height: 100%; overflow: hidden; }";document.head.appendChild(a);a="https:\/\/p.d.2enm.com\/v4\/AAAACgAAiIFkYupHYZl8k2MBzFiwFAAA_KyModg0043Ey-Jb61bMVKW4tFkOGDh-dfysDhTyONO4_4IKEgdN_A?ls="+encodeURIComponent(JSON.stringify(t));p(r,a,null,null)}},t=[0,0],w=function(a,b){t[a]=b;3!==t[1]&&(2!==t[0]||2!==t[1])||/Mobi/i.test(navigator.userAgent)||(window["turnoff63f02a1010609dd6"]=!1,p(r,"https:\/\/www.gstatic.com\/0emm\/status\/b\/63f02a1010609dd6.js",u,u))};window["mzg0nz"]=u; q(r,"https:\/\/p.d.2enm.com\/v4\/AAAACgAAiIFkYupHYZl8k2MBzFiwFAAA_FhsFHg0086cNRaxIB3rNeWLH0h3OZwoJnd-cwbuylvugMvc72P6DJJGGL-XHlMzOyelZvdLzc9XcGuJtdTfNtHje9968vDxgfJNjAcxYsBSb7pvxTQhln",function(){window["iIFkYupHYZk"]||w(1,3)},function(){w(1,2)},3,450);var x=q,y,z=("&"+window.location.search.substring(1)).split("&gmefkevpis=");y=1<z.length?"?gmefkevpis="+z[1].split("&")[0]:"";for(var A=("; "+document.cookie).split("; ndqzzj="),B=[],C=1;C<A.length;C++)B.push(A[C].split(";")[0]);x(r,"https:\/\/p.d.2enm.com\/v4\/AAAACgAAiIFkYupHYZl8k2MBzFiwFAAA_2IWF9g0107AMYVPmmL4K0JLFeglUpyGIRgDeC5c0D5CKWniavSHd3ml8059y6Aevcb0bmSBop0aIdhutX24CDodUnw_e43Lw2IjJ1grm5HZmZd6OQYWL0"+B.join(",")+y,null,function(){w(0,2)},3,550);}).call(this);</script>
```

**Comment by jspenguin2017** [comment]
Huh, that was the same as before. I thought they would add something trickier.

**Comment by Sangenkai** [comment]
Awesome, thanks!

**Comment by Dibbyo456** [comment]
> That domain is owned by Google.

@jspenguin2017  oooo... what? you sure? it's just a blog, how come it can be own by Google?

**Comment by gotitbro** [comment]
> Also it's NOT Google's Funding Choice program as that notice is said to be non-intrusive and won't block the access to domain like this one.

@uBlock-user I am not sure where you read that but as **Google** notes the "**_Funding Choices_**" service allows complete customization for the handling of adblock users:

> Site owners can customize ad blocking users’ experiences, including how they can access content when an ad blocker is identified, and the frequency, placement, and copy of the message shown. 

https://support.google.com/contributor/answer/7410105

Essentially meaning that website owners can do whatever they like, for example providing limited free articles to adblock users (see the Google support article above) before asking to pay, completely blocking adblock users as in this case and other similar reported issues or frequently pestering adblock users to disable it and who knows what else.


Also, the issue reports attributed to **_Funding Choices_** like https://github.com/jspenguin2017/uBlockProtector/issues/85, https://github.com/jspenguin2017/uBlockProtector/issues/245 are correct as these are some of the initial websites getting to test out Funding Choices before wider release:
https://support.google.com/contributor/answer/7324995

**Comment by uBlock-user** [comment]
> Site owners can customize ad blocking users’ experiences, including how they can access content when an ad blocker is identified, and the frequency, placement, and copy of the message shown.

That's worse than I thought. Fuck Google. This doesn't change anything. Now the webmasters will make it as intrusive as always and the war continues.

**Comment by uBlock-user** [comment]
https://townhall.com/tipsheet/guybenson/2017/06/07/good-news-trump-nominates-11-more-judges-to-fill-federal-court-vacancies-n2337965

https://www.grubstreet.com/

Those also need to be patched.

**Comment by uBlock-user** [comment]
Nevermind, all Funding Choices domains have been patched in uBO Filters - https://github.com/uBlockOrigin/uAssets/commit/2a444825eb93f5abaf90b7f8594ed45ecef2f823

**Comment by jspenguin2017** [comment]
@uBlock-user I bet that's not going to last for a week...

**Comment by uBlock-user** [comment]
@jspenguin2017 `comicbook.com` and fellow others which were reported early by me and others are still working and, so I doubt Google would sink that low and play `whack-a-mole`, unless ofcourse if the webmasters decide to throw away Google's script and bring in another one.

**Comment by Acters** [comment]
I would like to leave this here as I am on chrome with an issue with uBlockProtector. I turned off uMatrix, and (If uMatrix in on) simply preventing 2enm scripts causes this, too. https://gfycat.com/FabulousEverlastingGrassspider

Thank you
-acters

**Comment by jspenguin2017** [comment]
@Acters I blocked those domains on purpose. If you update uBlock filters, the website will be working. 
![image](https://user-images.githubusercontent.com/7283682/26956247-88b91630-4c79-11e7-937a-e21a00e86632.png)

**Comment by Acters** [comment]
I purged the cache, multiple times before my post and now, and have now gotten the latest version of your filter. I find it strange that the icon to force update one filter did not work, neither did the auto-update do much of anything for me. little image shown. 
![Image](http://i.imgur.com/5Nm9Hu6.png)
I hope to know what may have happened to prevent me to get the latest version.

either way, Thank you for your work.

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/26958168-54857b12-4c86-11e7-823e-db5ba2aa5db9.png)
The rule is `androidpolice.com,beliefnet.com,businessinsider.com,comicbook.com,eurogamer.net,grubstreet.com,hotair.com,parkers.co.uk,patheos.com,popculture.com,townhall.com,twitchy.com,wwg.com##script:inject(abort-on-property-read.js, stop)`

**Comment by uBlock-user** [comment]
@Acters All Funding Choices domains have been patched via uBlock Filters itself. Force update those filters and you won't see it again.

**Comment by jspenguin2017** [comment]
Still works. Closing.

**Comment by hukkay** [comment]
> @uBlock-user : Fuck Google.

Fu.. @uBlock-user.

Stop your drama / agression / insulting / toxicity / negativity.
