### ISSUE TITLE
NSFW! swfchan.net

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#272]
Hi, the site has pop-ups. 
Test link: http://swfchan.net/7/31730.shtml?baddog.swf
I already subscribed to "Anti popads.net" and added these filters into uBlock Origin:
```
||$third-party,script,domain=swfchan.com
swfchan.com##script:inject(abort-on-property-read.js, open)
swfchan.com##script:inject(abort-on-property-read.js, $.ready)
```
but unfortunately if I click on "[W]"
<img width="155" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/26917078-1ec00ffa-4c2d-11e7-85ca-b2c9c31dd5d7.PNG">
I'm sometimes getting a pop-up.

Could you please tell me what additional rule I have to add into uBlock Origin?

**Comment by uBlock-user** [comment]
Your filters are incorrect.

`swfchan.net##script:inject(abort-on-property-read.js, open)`

**Comment by adreporter** [comment]
@jspenguin2017 
If you go to http://swfchan.com/ and click anywhere, a popup will come out.
Could you please add also `swfchan.com##script:inject(abort-on-property-read.js, open)` to your list?

**Comment by adreporter** [comment]
@jspenguin2017 Thank you so much. For today I'm done 😄

**Comment by uBlock-user** [comment]
@jspenguin2017 another one - http://swfchan.org/swf.shtml

Just make it `swfchan.*##script:inject(abort-on-property-read.js, open)`
