### ISSUE TITLE
croco.site

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#273]
Hi, the site has pop-ups.
Test link: http://www.croco.site/n22c4w2Mws

**Comment by Dibbyo456** [comment]
I can't even click recaptcha, looks like there is conflict with [adsbypasser](https://github.com/adsbypasser/adsbypasser)

**Comment by adreporter** [comment]
@Dibbyo456 Yeah, I know. You have to add the rule to make it work.

**Comment by uBlock-user** [comment]
`croco.site##script:inject(abort-on-property-read.js, open)
`

**Comment by uBlock-user** [comment]
@jspenguin2017 There's a 5 sec timer that needs to be patched.

**Comment by jspenguin2017** [comment]
@uBlock-user I can't seem to inject the script... Is it a bug in Violentmonkey?

**Comment by uBlock-user** [comment]
could be, I'm not sure. I tried `timewarp` too and didn't work either.

**Comment by jspenguin2017** [comment]
The script isn't running at all on that specific page...

**Comment by uBlock-user** [comment]
Did you check the console for any errors or warnings ?

**Comment by jspenguin2017** [comment]
@uBlock-user Nothing, it just didn't run. I'm reporting it to Violentmonkey repo.

**Comment by jspenguin2017** [comment]
Oh wait... it does work if uBO is off... Eh...

**Comment by jspenguin2017** [comment]
OK, that rule somehow breaks it... Looks like blocking `open` like that would cause the timer to be unskippable.

**Comment by uBlock-user** [comment]
So that filter is causing the conflict ?

**Comment by jspenguin2017** [comment]
@uBlock-user Yea...

**Comment by uBlock-user** [comment]
Get Link now sends you to the homepage, seems they removed it or it expired.

**Comment by jspenguin2017** [comment]
@uBlock-user That's fine, here is another one: http://croco.site/BgaC80b0wQ

**Comment by uBlock-user** [comment]
cooked up a new one - http://croco.site/nTrTHlNiA5

**Comment by uBlock-user** [comment]
Filter - `croco.site##script:inject(abort-on-property-read.js, popup)`

**Comment by uBlock-user** [comment]
Killing any window property such as `open` or `focus` conflicts with the timer.

**Comment by jspenguin2017** [comment]
Yep, the new solution seems to work.

**Comment by uBlock-user** [comment]
Nothing's wrong on our end, it's just the way the popup script is structured which is causing such conflict.
