### ISSUE TITLE
spaste.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#274]
Hi, I have a problem with this site.
Test link: http://www.spaste.com/s/xmh86z 
After solving the captcha you should see:
<img width="438" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/26921866-a749d80a-4c3d-11e7-99ca-7fa27e585a02.PNG">
But I see this:
<img width="225" alt="przechwytywanie1" src="https://user-images.githubusercontent.com/18214146/26921876-b43d23be-4c3d-11e7-9cd9-6709c5b61639.PNG">
Am I the only one?

I had to disable uBlock to see the link, but now I can't see the link anymore, even with uBlock disabled.
I thought the problem was my IP address, so I used some VPN and changed it but unfortunately I still can't see the link.

**Comment by uBlock-user** [comment]
Can't reproduce.

![](https://i.gyazo.com/e07e07c067224e0602fe71f580a95ede.png)

**Comment by Dibbyo456** [comment]
Can't reproduce. Install  [adsbypasser](https://github.com/adsbypasser/adsbypasser)

**Comment by adreporter** [comment]
@Dibbyo456 I already installed it. Doesn't work for me.

**Comment by adreporter** [comment]
This is what I see on Chrome without extensions:
https://s8.postimg.org/urs8g784z/Link_Generating_SPaste.png

**Comment by jspenguin2017** [comment]
You just need to turn off adsbypasser. 
![image](https://user-images.githubusercontent.com/7283682/26937889-ea2d796e-4c2f-11e7-8fc8-de148a06bd3f.png)
![image](https://user-images.githubusercontent.com/7283682/26937897-f0cb03fe-4c2f-11e7-9db5-7a0b5b77f603.png)

**Comment by adreporter** [comment]
Not working, already did that. I think it's something with my IP address, because there is no other explanation.

**Comment by adreporter** [comment]
@jspenguin2017 Are you using 64bit version of Chrome?

**Comment by jspenguin2017** [comment]
@adreporter Yes, that shouldn't be a problem, right?

**Comment by adreporter** [comment]
Hmm, I just installed Firefox 32bit and it works.

**Comment by adreporter** [comment]
@jspenguin2017 I give up. Tried everything. I think they banned my IP or something like that.

**Comment by jspenguin2017** [comment]
If you have base-clock overclock on your CPU, it can happen that timers runs faster than they should.

**Comment by adreporter** [comment]
@jspenguin2017 I don't overclock. I'm sure the problem is my IP: I clicked the test link on a second computer and the result is the same. I'll let you know if it's only my IP or Poland in general, but I think it's mine because in the past I even had problems accessing some forums.

**Comment by Dibbyo456** [comment]
@adreporter Install a VPN then check

**Comment by adreporter** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/2749#issuecomment-307175173

**Comment by jspenguin2017** [comment]
I can't read that.

**Comment by adreporter** [comment]
@jspenguin2017 I thought I am the only one, but as you can see in the second screenshot, I'm not. Yeah.
😆

**Comment by adreporter** [comment]
@jspenguin2017 Ok, last question from me: are you using IPv6?

**Comment by xxcriticxx** [comment]
with us ip i have to turn off adbaypaser and aak-cont to get the link working

**Comment by adreporter** [comment]
@jspenguin2017 Could you please see what happens if you solve the captcha 5 times in a row? If you will see the link on the 5th "attemp", I'm done for real then. I know it's annoying, but please answer me.

**Comment by jspenguin2017** [comment]
@adreporter Huh, it sometimes works sometimes not...

**Comment by jspenguin2017** [comment]
This should fix it.

**Comment by adreporter** [comment]
I just removed Chrome, deleted cookies, Chrome folders, Chrome registry entries, used CCleaner, Wise Registry Cleaner and Privazer and I reinstalled Chrome but unfortunately it doesn't work for me. I think spaste doesn't like Poland because there are some polish users that have the same problem with this site.

**Comment by adreporter** [comment]
Well, at least now I'm 100% sure the problem is my IP address. Screenshot from my mobile phone:
![screenshot_2017-06-09-17-08-33](https://user-images.githubusercontent.com/18214146/26982191-e3386e94-4d37-11e7-9a98-1f7b4150fbb2.png)

**Comment by adreporter** [comment]
@jspenguin2017 I changed ISP but http://www.spaste.com/s/xmh86z doesn't work correctly: it shows me the link only the first time, but after refreshing the link, I see:
<img width="225" alt="przechwytywanie1" src="https://user-images.githubusercontent.com/18214146/26921876-b43d23be-4c3d-11e7-9cd9-6709c5b61639.PNG">
Can you reproduce?

**Comment by gotitbro** [comment]
@jspenguin2017 Please remove these filters they are not needed anymore:
```
@@||spaste.com/ads/$subdocument
@@||spaste.com^$generichide
||taboola.com^$domain=spaste.com
```

**Example URL:** http://www.spaste.com/p/?c=c0VNv29506

**Comment by jspenguin2017** [comment]
Why?
