### ISSUE TITLE
pcgameshardware.de

### ISSUE THREAD

**Issue by uBlock-user** [jspenguin2017/uBlockProtector#275]
Test link: http://www.pcgameshardware.de/CPU-Hardware-154106/Tests/Rangliste-Bestenliste-1143392/

Screenshot: https://i.gyazo.com/9f99089dd831caaa19c603b506d0cdfd.jpg

Summary: The orange coloured CSS background image is actually the ad-banner hyper-link which in the event of a mouse click leads to a third-party server. It loads after a time interval of 4 seconds or more, upon detection by AdDefend script.

AdDefend Script - https://pastebin.com/raw/jhyzvNwq

Filter - `pcgameshardware.de##script:inject(uabinject-defuser.js)`

**Comment by jspenguin2017** [comment]
Can you try to update your filters? 
https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/30#note_31781655

**Comment by uBlock-user** [comment]
Patched via uBO Filters.
