### ISSUE TITLE
haxmaps.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#276]
Test link: http://haxmaps.com/

Screenshot: 
<img width="584" alt="przechwytywanie2" src="https://user-images.githubusercontent.com/18214146/26952091-3465ae74-4ca4-11e7-9bda-07bf0820a6c4.PNG">

The message appears after 10 seconds.

**Comment by jspenguin2017** [comment]
Can you open just one issue for related websites?

**Comment by adreporter** [comment]
Ok, sorry.

**Comment by uBlock-user** [comment]
This work too -` haxmaps.com##script:inject(abort-on-property-read.js, abbwarn)`

**Comment by uBlock-user** [comment]
Same for the rest of the two domains

`haxrec.com,haxcolors.com,haxmaps.com##script:inject(abort-on-property-read.js, abbwarn)`
