### ISSUE TITLE
hl-live.de

### ISSUE THREAD

**Issue by TimK1987** [jspenguin2017/uBlockProtector#279]
Before opening an issue, you MUST read the contribution guideline. Failure to do so may result in a ban. 

Test link: https://www.hl-live.de/aktuell/textstart.php?id=114889

Screenshot: 
![bildschirmfoto vom 2017-06-09 02-01-48](https://user-images.githubusercontent.com/28412759/26955542-a91a104e-4cb7-11e7-881b-8a8839bc47a0.png)

Add everything else that you believe to be useful below: Main Page works, but clicking on article links let this Anti-Ad-Block message appear.

**Comment by jspenguin2017** [comment]
Please, properly follow installation steps. 
![image](https://user-images.githubusercontent.com/7283682/26955613-1d422dbe-4c75-11e7-9297-5dab93f21b94.png)

**Comment by uBlock-user** [comment]
Patched via Script, so the issue is with your setup.
