### ISSUE TITLE
cloudwebcopy.com

### ISSUE THREAD

**Issue by Connor37** [jspenguin2017/uBlockProtector#281]
Test link: http://s01.cloudwebcopy.com/

Screenshot: 
![image](https://user-images.githubusercontent.com/8341213/26979445-140a55ae-4d2f-11e7-9d29-b300c69e03b3.png)

**Comment by uBlock-user** [comment]
`cloudwebcopy.com##script:inject(bab-defuser.js)`

**Comment by jspenguin2017** [comment]
Looks like it's still working, closing.
