### ISSUE TITLE
sopsport.org

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#282]
Test link: http://sopsport.org/

Screenshot:
<img width="433" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/26985568-4f116254-4d44-11e7-8552-138d15014cdc.PNG">

**Comment by uBlock-user** [comment]
Can't reproduce.

Try `sopsport.org##script:inject(abort-on-property-read.js, anOptions)`

**Comment by jspenguin2017** [comment]
I can't reproduce neither.

**Comment by Connor37** [comment]
I can reproduce by turning on the EasyList.

**Comment by jspenguin2017** [comment]
Huh, the block screen doesn't show on first visit...

**Comment by uBlock-user** [comment]
Easylist is on by default, didn't change, neither my numerous subsequent visits. I just can't reproduce it.
