### ISSUE TITLE
NSFW! archived.moe

### ISSUE THREAD

**Issue by MonfGeiger** [jspenguin2017/uBlockProtector#283]
added the nsfw tag because this websites also archives nsfw content in various boards like /b/ /h/ /d/ and so on; this happens on chrome/firefox as well with violentmonkey/greasemonkey and default ublock origin test settings

Test link: https://archived.moe/* (adding wildcard to show that it happens on every subsequent board-archive link)

![before](https://user-images.githubusercontent.com/28603306/26994529-37402922-4d25-11e7-83dc-20d6bbb497e3.JPG)

![after](https://user-images.githubusercontent.com/28603306/26994538-41bb0b06-4d25-11e7-9011-c7b2b2b9a40a.JPG)

was trying to find an old thread that had content I wanted to save myself, but this happened; wat do?

**Comment by jspenguin2017** [comment]
Did you just installed Violentmonkey or installed Violentmonkey then Script? 
![image](https://user-images.githubusercontent.com/7283682/26995465-fccd1444-4d29-11e7-9df0-d91cb0e2930a.png)

**Comment by jspenguin2017** [comment]
I thought my contribution guideline is clear enough, I'll start to ban people who don't read.

**Comment by MonfGeiger** [comment]
Didn't see that firefox was removed on the accepted browser-issue talk list, so I redid this on chrome with latest dev version of ublock origin, china list, ublock filter list, adblock warning removal list, and ublock script with violentmonkey (had it installed a month ago, took a bit to set ccleaner to stop deleting the script from violentmonkey)

apparently, despite the error you posted, it does work on chrome; but again, firefox is no longer an option to discuss concerning issues with ublock protector anymore?

**Comment by jspenguin2017** [comment]
@MonfGeiger The error crashes the detection script, that's good. FireFox users are no longer allowed to open issues, if you insist on using FireFox, please head over to AAK-Cont.

**Comment by uBlock-user** [comment]
Avoid using FF, it will only create far more trouble for you aside from anti adblock issues, as its WebExtensions are heavily filled with bugs.

**Comment by MonfGeiger** [comment]
guess ill stick with chrome, report any issues, and hope the fixes translate to firefox, or switch filters

**Comment by jspenguin2017** [comment]
@uBlock-user Actually, after investigating the problem, it seems that FireFox's problem is not with the support of WebExtension, but with security policies, it follows the standard closely even if there is a good reason to not to, which creates incompatibility with uBlock Origin. There is a workaround in development in AAK-Cont repository, but it will either require another extension to bypass the security policies or a hacky way to patch some window properties.

**Comment by jspenguin2017** [comment]
@uBlock-user You got to toss code quality and performance out of the window if you want to support every browser. 
There are 2 ad server white listing that gone into uBlock filter after the breakage on FireFox... I probably should reverse that...
