### ISSUE TITLE
gentside.com

### ISSUE THREAD

**Issue by Slowerzs** [jspenguin2017/uBlockProtector#285]
I recently opened a issue for gentside because an overlay was covering the page, now it is blocked, but videos can't be played

Test link : http://gaming.gentside.com/league-of-legends/league-of-legends-un-seul-champion-n-039-a-jamais-ete-pick-dans-l-039-histoire-des-lcs-eu_art19468.html

Screenshot of the web page : 
![capture1](https://user-images.githubusercontent.com/28687818/27006639-8177bc48-4e39-11e7-873d-d4b82847c823.png)

Screenshot of the console : 
![capture](https://user-images.githubusercontent.com/28687818/27006631-3b897d2a-4e39-11e7-8f06-d7d040bca514.png)

Thanks

**Comment by jspenguin2017** [comment]
OK, I'll have a look. Hopefully the detection is not built into the player. 

Code dump: https://pastebin.com/W4XreNLw

**Comment by uBlock-user** [comment]
Bad Filter from Easylist

`@@||gtsstatic.com/p/mscripts/prebid_32.js$domain=gentside.net`

**Comment by uBlock-user** [comment]
Easylist's filter breaks the HTML 5 player, nothing more.

**Comment by jspenguin2017** [comment]
Well, looks like I overthought 😆

**Comment by jspenguin2017** [comment]
They changed the name... Updating filter.

**Comment by jspenguin2017** [comment]
Still works, closing.
