### ISSUE TITLE
cyberterminators.co

### ISSUE THREAD

**Issue by ColliderTD** [jspenguin2017/uBlockProtector#287]

**Comment by uBlock-user** [comment]
I was going to suggest killing the setTimeout call, but looks like you already patched the `anOptions` property.

**Comment by ColliderTD** [comment]
Still....

**Comment by adreporter** [comment]
@ColliderTD Can't reproduce, make sure you're using the latest version of the list and of the script.

**Comment by uBlock-user** [comment]
That's because it got patched by jspenguin before you posted.

**Comment by adreporter** [comment]
@uBlock-user ikr

**Comment by ColliderTD** [comment]
:D (y)

**Comment by jspenguin2017** [comment]
It's patched in https://github.com/jspenguin2017/uBlockProtector/commit/8f66e2773b0aa68bfc6c60d7b2cd5aaabed21cd5

**Comment by jspenguin2017** [comment]
Still works. Closing.
