### ISSUE TITLE
firstone.tv

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#289]
Test link: https://www.firstone.tv/Live/Italy/Rai-Sport-+-HD-27

Screenshot of the web page: 
<img width="872" alt="cattura1" src="https://user-images.githubusercontent.com/18214146/27911650-12e236ac-625a-11e7-955c-fd805b6428b2.PNG">

Screenshot of the console:
<img width="960" alt="cattura" src="https://user-images.githubusercontent.com/18214146/27911660-1d3d52e4-625a-11e7-9373-b87795d0e0bc.PNG">

**Comment by adreporter** [comment]
Wow, so fast. Thank you.

**Comment by lain566** [comment]
@jspenguin2017 It's broken again

**Comment by adreporter** [comment]
Screenshot of the web page: 
<img width="872" alt="cattura1" src="https://user-images.githubusercontent.com/18214146/27911650-12e236ac-625a-11e7-955c-fd805b6428b2.PNG">
Screenshot of the console:
<img width="960" alt="cattura" src="https://user-images.githubusercontent.com/18214146/27911660-1d3d52e4-625a-11e7-9373-b87795d0e0bc.PNG">

**Comment by adreporter** [comment]
@jspenguin2017 Can you remove the 10 seconds "SKIP AD" timer?
