### ISSUE TITLE
streamwoop.tv

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#290]
Test link: https://streamwoop.tv/replay/Berisha-sent-off-2nd-Yellow-Card-for-diving-and-1st-yellow-for-complaining-to-the-ref

Screenshot of the web page: 
<img width="702" alt="addb" src="https://user-images.githubusercontent.com/18214146/27014708-3abd820e-4efe-11e7-8553-c93ae034c835.PNG">

Screenshot of the console: 
<img width="960" alt="cons2" src="https://user-images.githubusercontent.com/18214146/27014713-42c3666c-4efe-11e7-99dd-adcba8e6c252.PNG">

**Comment by adreporter** [comment]
Good deal, thanks.

**Comment by adreporter** [comment]
@jspenguin2017 There is one more site I have to report, but the console is full of errors and warnings. Should I screenshot the console?

**Comment by jspenguin2017** [comment]
Yes. Just the top.

**Comment by adreporter** [comment]
@jspenguin2017 Ok.
