### ISSUE TITLE
youtube-videos.tv

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#291]
Test link: https://it.youtube-videos.tv/the-thinning-2016-sub-ita/

Screenshot of the web page:
<img width="960" alt="js" src="https://user-images.githubusercontent.com/18214146/27014784-01b54b84-4f00-11e7-88a9-d71bb15687ca.PNG">

Screenshot of the console:
<img width="960" alt="js2" src="https://user-images.githubusercontent.com/18214146/27014787-0cdfb71a-4f00-11e7-8c06-8be9ec568060.PNG">
What? Yesterday the errors and warnings were like two times more. Anyway, after closing the antiadblock message, you have to wait 2 minutes to watch the movie, could you please remove that?

**Comment by adreporter** [comment]
You Sir, are my hero.

**Comment by jspenguin2017** [comment]
Took a while to tweak the CSS, I'm not familiar with CSS priority... 

![joke](http://2.bp.blogspot.com/-41v6n3Vaf5s/UeRN_XJ0keI/AAAAAAAAN2Y/YxIHhddGiaw/s1600/css.gif)

**Comment by jspenguin2017** [comment]
Social locker is pretty weak, I bet they aren't even trying.
