### ISSUE TITLE
www.ispazio.net

### ISSUE THREAD

**Issue by log4en** [jspenguin2017/uBlockProtector#292]
### Screenshot of the console: ![schermata 2017-06-12 alle 16 06 36](https://user-images.githubusercontent.com/19669305/27037902-ab9ee9d2-4f89-11e7-8a9f-6992cb479b31.png)

**Comment by uBlock-user** [comment]
Filter - `ispazio.net##script:inject(setTimeout-defuser.js, an_message_display)`

**Comment by log4en** [comment]
thank you!
