### ISSUE TITLE
[Off-topic] forums.lanik.us

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#293]
https://forums.lanik.us/viewtopic.php?f=9&t=37127
Am I the only one?

**Comment by uBlock-user** [comment]
You can also report here - https://github.com/easylist/easylist/issues

I don't have an account there, neither I will bother to make one.

**Comment by jspenguin2017** [comment]
Nope, works for me. 
![image](https://user-images.githubusercontent.com/7283682/27085298-1af55834-500c-11e7-8710-ae6de8a3a366.png)

**Comment by adreporter** [comment]
@uBlock-user Thanks for the info, I will report there.
@jspenguin2017 If you have an account there, could you please go here https://forums.lanik.us/posting.php?mode=post&f=62 and see if you can insert code or quote something?

**Comment by jspenguin2017** [comment]
@adreporter I don't have an account there...

**Comment by adreporter** [comment]
@jspenguin2017 Can I use https://jspenguin.com/PrivateMessage/ (reference 293?) and send you credentials? If yes, let me change the password first.

**Comment by adreporter** [comment]
@jspenguin2017 Could you please do me a favor and use my credentials on https://forums.lanik.us/posting.php?mode=post&f=62 to test if the editor works for you?

**Comment by uBlock-user** [comment]
@adreporter Open that link and then open the logger, then hit refresh and look for everything that is blocked or coloured red in the logger.

**Comment by adreporter** [comment]
@uBlock-user The uBlock logger, right?

**Comment by uBlock-user** [comment]
Yes.

**Comment by adreporter** [comment]
<img width="960" alt="sdsdsds" src="https://user-images.githubusercontent.com/18214146/27086863-c7a59ef8-5053-11e7-81a0-1feacc2ef340.PNG">

**Comment by jspenguin2017** [comment]
@adreporter Post it like before, I'll have a look when I have time.

**Comment by adreporter** [comment]
@jspenguin2017 Ok, thanks.

**Comment by uBlock-user** [comment]
Is that it ? or are you filtering anything ?

**Comment by adreporter** [comment]
@uBlock-user I'm not filtering anything.

**Comment by adreporter** [comment]
@jspenguin2017 Sent.

**Comment by uBlock-user** [comment]
Well, try disabling all your extensions with the exception of uBlock Origin and see if you can reproduce it. Then load extensions one by one and check whether it happens again or not.

**Comment by jspenguin2017** [comment]
@adreporter Huh, it actually doesn't, adding the domain to excluded list doesn't help, turning off Violentmonkey doesn't help neither, sounds like an issue on their end. In the uBO logger, nothing is blocked. If you refresh a couple times, sometimes it works. 
![image](https://user-images.githubusercontent.com/7283682/27088717-b9404e6e-5015-11e7-950d-00ebde619e15.png)

**Comment by jspenguin2017** [comment]
Try this? 
```JavaScript
if (a.domCmp(["forums.lanik.us"])) {
    a.win.form_name = "postform";
    a.win.text_name = "message";
}
```

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/27089510-c7128a3c-5017-11e7-91fa-338bc22b9e0b.png)

**Comment by adreporter** [comment]
@jspenguin2017 After running those commands in the console, the smilies are working, but "the icons", above the text box, aren't working. You're right, it's their job to fix their website. If I have some websites to report, I'll do so on their github repository. Closing.
