### ISSUE TITLE
litv.tv

### ISSUE THREAD

**Issue by at01076172** [jspenguin2017/uBlockProtector#294]
### Test link (required): 
https://www.litv.tv/vod/drama/content.do?brc_id=&id=VOD00047752
### Screenshot of the web page (required): 

https://i.imgur.com/vOonmGi.png
### Screenshot of the console (press `F12` to bring up the console) (required): 

https://i.imgur.com/4RyrsUZ.png

**Comment by uBlock-user** [comment]
I'm receiving a Geo-Lock notification rather.

**Comment by at01076172** [comment]
i live in Taiwan, let me see if i can find a stable VPN server.

**Comment by at01076172** [comment]
@uBlock-user 
is there a way i can give you server address, username and password in private?

**Comment by ghajini** [comment]
open a confidential issue in the GitLab repository
https://gitlab.com/xuhaiyang1234/AAK-Cont/issues

**Comment by uBlock-user** [comment]
Give that info to @jspenguin2017 privately via website's contact us page or post in AAK-Cont issue tracker which is also private.

**Comment by at01076172** [comment]
@ghajini @uBlock-user ok! thanks for helping me.

**Comment by uBlock-user** [comment]
If you can read the language, this is what I receive - https://www.litv.tv/promo/playerMask/playerMaskImage/player_outside_region_mask.jpg

**Comment by at01076172** [comment]
@uBlock-user 
the following is the translation: 
> This service is only available to viewers in Taiwan.
> 
> viewers in your area are unauthorized, We are sorry.
> If you are viewer in Taiwan, please call support (02)7707-0708

It is a Geo-Lock notification.

**Comment by uBlock-user** [comment]
Thanks, that confirms my suspicion.

**Comment by jspenguin2017** [comment]
Hi, confidential data can be posted in one of these 3 places: 

* Secret Issues repository: https://gitlab.com/xuhaiyang1234/uBlockProtectorSecretIssues
* AAK-Cont repository: https://gitlab.com/xuhaiyang1234/AAK-Cont
* Directly to me: https://jspenguin.com/PrivateMessage with reference being the issue number

There can be more than just me who can view confidential issues in AAK-Cont repository, keep that in mind. Don't forget to mark the issue as confidential if you are opening an issue. 

I saw that you opened a confidential issue in AAK-Cont repository, I'll have a look. Hopefully it is not integrated in the player...

**Comment by jspenguin2017** [comment]
From your screenshot, it looks like a solution is activated: 
```JavaScript
if (a.domCmp(["litv.tv"])) {
    a.bait("div", ".player_mask");
}
```
But it is probably outdated...

(What? GitHub syntax highlighting style changed AGAIN?)

**Comment by uBlock-user** [comment]
This website also loads lots of first party ad + tracking scripts which can be found via the logger

**Comment by jspenguin2017** [comment]
OK, I found the place where they put player masks: 
https://www.litv.tv/resources/js/vodModule932.js
Available masks: 
```JavaScript
var playerMaskOnServer = {
    "appDownload": "/promo/playerMask/playerMaskImage/player_app_dl_mask.jpg",
    "channelLogin": "/promo/playerMask/playerMaskImage/player_channel_login_mask.jpg",
    "channelPurchase": "/promo/playerMask/playerMaskImage/player_channel_purchase_mask.jpg",
    "channelTrial": "/promo/playerMask/playerMaskImage/player_channel_trial_mask.jpg",
    "eltaPurchase": "/promo/playerMask/playerMaskImage/player_elta_purchase_mask.jpg",
    "outsideRegion": "/promo/playerMask/playerMaskImage/player_outside_region_mask.jpg",
    "adblock": "/promo/playerMask/playerMaskImage/player_adblock_mask.jpg",
    "idleOverHours": "/promo/playerMask/playerMaskImage/player_idle_over_hours_mask.jpg",
    "vodLogin": "/promo/playerMask/playerMaskImage/player_vod_login_mask.jpg",
    "mobileParental": "/promo/playerMask/playerMaskImage/player_mobile_parental_mask.jpg",
    "multipleStream": "/promo/playerMask/playerMaskImage/player_multiple_stream_mask.jpg",
    "notAvailable": "/promo/playerMask/playerMaskImage/player_not_available_mask.jpg",
    "pcParental": "/promo/playerMask/playerMaskImage/player_pc_parental_mask.jpg",
    "shelves": "/promo/playerMask/playerMaskImage/player_shelves_mask.jpg",
    "watchDeviceMobile": "/promo/playerMask/playerMaskImage/player_watch_device_mobile_mask.jpg",
    "watchDeviceTV": "/promo/playerMask/playerMaskImage/player_watch_device_tv_mask.jpg",
    "watchDeviceTVMobile": "/promo/playerMask/playerMaskImage/player_watch_device_tv_mobile_mask.jpg",
    "vodPurchase": "/promo/playerMask/playerMaskImage/player_vod_purchase_mask.jpg",
    "playerError": "/promo/playerMask/playerMaskImage/player_error_mask.jpg"
};
```

**Comment by jspenguin2017** [comment]
@uBlock-user I don't see any first party ads...
![image](https://user-images.githubusercontent.com/7283682/27086377-3c4d3d78-500f-11e7-9f85-0bd36af6e2ae.png)

**Comment by uBlock-user** [comment]
I meant first party ad scripts

**Comment by jspenguin2017** [comment]
@uBlock-user Ah, a few tracking scripts, we'll leave those to EasyList.

**Comment by uBlock-user** [comment]
and ad scripts too coming from `/promo` folder

**Comment by jspenguin2017** [comment]
@uBlock-user Are you sure that's ads and not recommended related videos? 

Looks like anti-adblock is here: https://www.litv.tv/resources/js/callPlayer932.js

**Comment by jspenguin2017** [comment]
Eh... It looks like it's integrated to the player... Ouch... https://www.litv.tv/resources/js/litvplayer.min932.js

**Comment by uBlock-user** [comment]
It's in the promo folder so it's promoting, that make it classify as ads first party or not, but anyways..

**Comment by uBlock-user** [comment]
Ads are also integrated inside from the looks

**Comment by jspenguin2017** [comment]
@uBlock-user Showing related videos should not be considered ads because you want to know what else the site has. 
But we still have a bigger problem to fix.

**Comment by uBlock-user** [comment]
I can't confirm that's if it's recommendations or not as I get stuck with Geo-Lock.

Can you find video URL from that player js you posted, then you can swap the player with ours and won't have to deal with pre-roll ads and anti adblock as well.

**Comment by at01076172** [comment]
![image](https://user-images.githubusercontent.com/5987870/27087583-f4813ca0-5087-11e7-9d06-ed6bcefeb600.png)
if you are talking about this, it is recommended videos.

**Comment by jspenguin2017** [comment]
@uBlock-user I'm Geo Locked, swapping the player is no easy task, as it is highly integrated with the page...

**Comment by jspenguin2017** [comment]
I'll use the VPN to see if I can find anything interesting.

**Comment by jspenguin2017** [comment]
I'm seeing `.swf` in the source... Reek used to host a Flash based player, but it's gone since his website is down...

**Comment by at01076172** [comment]
@jspenguin2017  I thought it is htm5 player playing `.ts` file.
Do i misunderstand what you mean?

**Comment by jspenguin2017** [comment]
I can't connect to the VPN you provided...

**Comment by at01076172** [comment]
@jspenguin2017 
I'm so sorry, it's possible that its maximum user limit reached and you won't be able to connect successfully.

If you don't mind waiting, 
I'll get back to my place in a couple of days.
Then, I'll set up a my own temporary VPN server for you.

I also want to provide a temporary VPN account for @uBlock-user, if there is a way in private.

**Comment by uBlock-user** [comment]
Hey it's alright, no need to take such trouble setting another for me. One should be enough.

**Comment by at01076172** [comment]
@jspenguin2017 @uBlock-user 
i just found how to bypass this website's geo-lock by modifying HTTP request headers with [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj).
Importing the profile and pasting the profile i provide below.
![image](https://user-images.githubusercontent.com/5987870/27171778-4835fd96-51e5-11e7-84a9-c72008fcd86b.png)
```
{"title":"LiTV","hideComment":true,"headers":[{"enabled":true,"name":"X-Forwarded-For","value":"203.188.200.67","comment":""},{"enabled":true,"name":"Client-IP","value":"203.188.200.67","comment":""}],"respHeaders":[],"filters":[{"enabled":true,"type":"urls","urlPattern":"https://www.litv.tv/*"}],"appendMode":""}
```
this method works after i connect to a US VPN server.
If this doesn't work, i'll start to set up a VPN server.

**Comment by uBlock-user** [comment]
Thanks, great find. Now I can reproduce it without Geo-Lock getting in my way.

**Comment by uBlock-user** [comment]
Add

```
||litv.tv/promo/
litv.tv##.fp-pausebn
```

That works for me - https://i.gyazo.com/1dda015d718b8a1276ca50b734787079.png

**Comment by uBlock-user** [comment]
Tested other video links too, works fine. Consider this patched.

**Comment by at01076172** [comment]
It works fine,too. Thank you so much.

two line @uBlock-user provided above have defused anti-adblock.
I know that's what uBlockProtector do.

However, ad still remains before video is played.
![image](https://user-images.githubusercontent.com/5987870/27178140-a76b5c50-51fb-11e7-91dc-f3d722a9cdb8.png)
At the upper-right, the text in red rectangular box is "Skip in 12 sec, VIP won't have ads"
May i ask a little bit more? can this be block as well?
If you guys don't want to do it, i'll understand and still be grateful for what you have done.

**Comment by uBlock-user** [comment]
I don't see any such ads. Link ?

**Comment by uBlock-user** [comment]
Add this filter too 

`||$third-party,script,domain=litv.tv`

That should kill any unblocked third-party ads.

**Comment by at01076172** [comment]
It shows up when the first time your click the video.

Perhaps clicking a video that you haven't played before will let you see ads.
maybe [this one](https://www.litv.tv/vod/drama/content.do?brc_id=53&id=VOD00074711)?
If you still any ads, switching to another episode.

![image](https://user-images.githubusercontent.com/5987870/27179026-620a1c4c-51ff-11e7-8433-49356597693d.png)
This is the place where you switch episodes.

**Comment by at01076172** [comment]
@uBlock-user 
`||$third-party,script,domain=litv.tv`
uh...this is not working.

**Comment by uBlock-user** [comment]
Nope, tried all 7 episodes. NO ADS! It's probably third-party leakage on your end.

**Comment by uBlock-user** [comment]
Clear all cache and site data and then try again.

**Comment by at01076172** [comment]
@uBlock-user 
These three lines works actually. 
I sincerely apologize.

**Comment by jspenguin2017** [comment]
Thanks, I'll test it out.

**Comment by jspenguin2017** [comment]
Seems to work, added to List.
