### ISSUE TITLE
solereview.com

### ISSUE THREAD

**Issue by Zhangsun321** [jspenguin2017/uBlockProtector#295]
https://www.solereview.com/
chrome violent and ubo
http://prntscr.com/fjccj9  screenshot of block wall

console pic 1  http://prntscr.com/fjce26
console pic 2 http://prntscr.com/fjce9q

https://github.com/reek/anti-adblock-killer/issues/3280

you supplied a fix to LiveNewsOn
||pelcro.com^$third-party
pelcro.com being the script provider....

NOW   i ran into www.solereview.com which uses pelcro too
and that fix doesnt work..
what would the fix be? and why would it be different?
thanks for taking time to explain stuff

**Comment by adreporter** [comment]
Hmm, I can't reproduce it.

**Comment by adreporter** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
Can't reproduce.

Also it's using its own and not making a connection to `pelcro.com`. Always run the logger if you come across an anti-adblock barrier and wish to investigate.

Try adding this filter - `magnific-popup`

**Comment by jspenguin2017** [comment]
The solution is different for every domain. I can't reproduce it. Turn off your extensions one by one and see which one is causing the problem.

**Comment by Zhangsun321** [comment]
ok
i disabled EVERYTHING cept for ubo and violent monkey...
even disabled all the scirpts inside violentmonkey cept for the ublock protector one
removed all the filters on filters
added /*magnific-popup.min.js^$script to filters
http://prntscr.com/fjfz8s the only blocklists im using

even d/cd the vpn to see if that'll do it
the ONLY possible thing i can think of... is this..
the main page
solereview.com   the adblock notice doesnt pop up all the time
unless i go unto a sub url
eg
https://www.solereview.com/best-running-shoes-for-men-2017/

http://prntscr.com/fjg4mr
ok....  those first 4 'above branding css comes from pelcor.com
everything else comes from amazonads and google ads..

**Comment by Zhangsun321** [comment]
correction... the first thing blocked.. is by pelcor

http://prntscr.com/fjggkz
iframe.html at 12 ms

**Comment by jspenguin2017** [comment]
@Zhangsun321 I went to 3 articles, scrolled up and down and waited a few minutes, no block screen. 
First, try this filter: `||afairweb.com^$third-party` (This filter is part of EasyPrivacy and will not be added to uBlock Protector)

If it doesn't work, try to configure your system *exactly* like this: 
https://github.com/jspenguin2017/uBlockProtector/blob/master/Notes/Standard%20Configuration.MD
Then change it towards your usual configuration a little bit at a time and see where is the problem.

**Comment by Zhangsun321** [comment]
ok...   will do that today...
and report back tommorow.. cuz i know your busy...
thank you SOO much for your time and help..  I am learning A LOT :)

**Comment by Zhangsun321** [comment]
nope... reset everything to defaults... used the lists specificed in  addtion to the defaults..
only ubo and violentmonkey running   still not working
oh well... thanks for the help...

**Comment by uBlock-user** [comment]
Add `||$third-party,script,domain=solereview.com` and see if it happens. Clear all cache and site data before adding that filter.

**Comment by Zhangsun321** [comment]
that worked!!!!
interesting...
thanks for taking the time..

**Comment by uBlock-user** [comment]
Well that confirms that it's a third-party script so another domain like `pelcro.com` is making the connection and sending the payload. My guess is `afairweb.com`

**Comment by uBlock-user** [comment]
Okay I can reproduce it if I whitelist `afairweb.com` which makes connection to `pelcro.com`, so adding `afairweb.com` should do it. You can remove the above filter and add `||afairweb.com^$third-party`

**Comment by Zhangsun321** [comment]
i posted the log where i seen the site connecting to pelcro.com! :) :) :)
i tried the ||afairweb.com^$third-party yesterday.. and didnt work...
it works now though..

**Comment by jspenguin2017** [comment]
@Zhangsun321 It could be cached. You need to use DevTools to force a re-fetch.

**Comment by Zhangsun321** [comment]
i see ctl f5?
i need to write that down..

**Comment by jspenguin2017** [comment]
Ctrl+F5 doesn't work reliably.

**Comment by Zhangsun321** [comment]
https://superuser.com/questions/220179/how-can-i-do-a-cache-refresh-in-google-chrome
?
this?

**Comment by jspenguin2017** [comment]
Yea, that would work. Doesn't work with console closed though.

**Comment by Zhangsun321** [comment]
ive notced... is there an add one so when i click refresh with the console closed, itll do it? :)

**Comment by jspenguin2017** [comment]
@Zhangsun321 I don't think you can force reload without using the developer console.

**Comment by Zhangsun321** [comment]
welp ive learnt tons.. ty so much.. all 3 of you... ima close this now...

**Comment by uBlock-user** [comment]
Just press F12 to open developer console, how hard could that be ?
