### ISSUE TITLE
Errors in Chrome Console - Failed to define read-only properties & Error running script

### ISSUE THREAD

**Issue by jjohns71** [jspenguin2017/uBlockProtector#296]
### Screenshot of the web page (required): 

![ublockprotectorerror](https://user-images.githubusercontent.com/6795795/27142954-acd69328-50fa-11e7-961e-1bd3cf24025f.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
Included in screenshot above

### Add everything else that you believe to be useful below (optional): 

I'm honestly not sure if all of these errors in the Console mean the script is not working or if these errors are to be expected but didn't find anything in the issues tracker regarding this.

- Tested on Windows 7 & Windows 10 systems with the following browser/extensions:
Chrome Version 59.0.3071.86 (Official Build) (64-bit)
      - uBlock Origin 1.12.4 subscribed to the uBlock Protector Filter list
      - Violent Monkey 2.6.4
      - uBlock Origin Extra 2.24
      - HTTPS Everywhere 2017.6.5
      - Decentraleyes 1.3.7.5

**Comment by jspenguin2017** [comment]
Can't reproduce, which scripts do you have installed? 
![image](https://user-images.githubusercontent.com/7283682/27143441-9766dc46-50eb-11e7-8881-45ca18dfe0dd.png)

**Comment by jspenguin2017** [comment]
I should wrap that in a try-catch, but that's not the root of your problem.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by jjohns71** [comment]
Hi @jspenguin2017, maybe one of these scripts is interfering that I have installed.

1. [AAK-Cont](https://xuhaiyang1234.gitlab.io/AAK-Cont/) v1.045
2. [AdsBypasser](https://adsbypasser.github.io/) v5.71.0
3. [Amazon CamelCamelCamel Graph](https://github.com/jjohns71/Monkey-Scripts/blob/master/Amazon_Camel_Graph_Revived_With_https_Fix.js) v1.1.6
4. [Anti-Disabler](https://greasyfork.org/en/scripts/9002-anti-disabler/code) v1.0.1
5. [Auto Check-in to Southwest Flights](https://github.com/jjohns71/Monkey-Scripts/blob/master/Auto_Check-In_to_Southwest_Flights.user.js) v1.3.6
6. [CLPics](https://github.com/eternicode/clpics/blob/master/clpics.user.js) v0.8.8
7. [GitHub Editor](https://greasyfork.org/en/scripts/21964-github-editor-change-default-settings) v1.0.10
8. [Quora Unblocker](https://github.com/jjohns71/Monkey-Scripts/blob/master/Quora_Unblocker.js) v1.0.2
9. [Reddit Overwrite](https://greasyfork.org/en/scripts/10380-reddit-overwrite) v1.4.8
10. [uBlock Protector](https://jspenguin2017.github.io/uBlockProtector/) v8.41


I will test by disabling one-by-one until I find the culprit and report back.

**Comment by jspenguin2017** [comment]
@jjohns71 Don't use AAK-Cont if you are using this project.

**Comment by jjohns71** [comment]
@jspenguin2017 Thanks for that! I didn't see that suggested anywhere but I have uninstalled AAK-Cont script - disabling that script fixes the Console errors. 

Is there anyway the readme/wiki/Install page can be updated to tell users not to install both scripts as there will be a script conflict if you are running AAK-Cont side-by-side? I just saw the notice about AAK-Cont on the project homepage and figured installing both would be better than just one of them.

I appreciate your time with this project, not trying to be an idiot user!

**Comment by jspenguin2017** [comment]
I'll add that to AAK-Cont installation instructions.

**Comment by uBlock-user** [comment]
Remove AdsByPasser too

**Comment by jspenguin2017** [comment]
AdsBypasser is not known to cause major issues, but if it does I won't fix it.

**Comment by jjohns71** [comment]
I've removed AdsBypasser as well for now, the project doesn't seem to be updated very often anyway.
