### ISSUE TITLE
dato.porn

### ISSUE THREAD

**Issue by Fezreal** [jspenguin2017/uBlockProtector#298]
http://dato.porn/embed-wtvq9adyr9g6.html#iframeload

img: http://imgur.com/a/eQR1w

**Comment by jspenguin2017** [comment]
Where is the template?

**Comment by Fezreal** [comment]
模板在哪里 是什么意思..

**Comment by jspenguin2017** [comment]
这个填了
https://github.com/jspenguin2017/uBlockProtector/blob/master/ISSUE_TEMPLATE.TXT

**Comment by Fezreal** [comment]
### Test link (required): 
http://dato.porn/embed-wtvq9adyr9g6.html#iframeload

### Screenshot of the web page (required): 
![unnamed](https://user-images.githubusercontent.com/6703674/27164101-239a0b70-51be-11e7-9ad7-da670ebd868b.png)


### Screenshot of the console (press `F12` to bring up the console) (required): 
<img width="1050" alt="2" src="https://user-images.githubusercontent.com/6703674/27164135-6577ff34-51be-11e7-9e88-de2f0187b861.png">


### Add everything else that you believe to be useful below (optional):

**Comment by jspenguin2017** [comment]
你反广告插件是啥啊？暴力猴呢？

**Comment by Fezreal** [comment]
就装了一个ublock origin

**Comment by jspenguin2017** [comment]
你去装了暴力猴然后装了脚本，链接在主页上。

**Comment by jspenguin2017** [comment]
之前的方案有点慢，缓存了就不行了，没办法只能白名单。
我看主页和版规得有个中文版的，哪天有时间我给加上。

**Comment by Fezreal** [comment]
..不是很喜欢用脚本来解决... 
能单单用ublock搞定就最好了.

**Comment by jspenguin2017** [comment]
这个网站能行，但是好多不行，如果你只想用规则列表，下次去[这里](https://gitlab.com/xuhaiyang1234/AAK-Cont/issues)求助。
也有其他插件是反广告和猴子脚本二合一的。

**Comment by Fezreal** [comment]
<img width="421" alt="2017-06-15 11 57 39" src="https://user-images.githubusercontent.com/6703674/27164735-e366a91a-51c1-11e7-9789-110978defef3.png">
已使用 6 / 2,390
这是不是意味着, 这里面只有6条规则是适合ublock使用的? 其余全都无效吗.



<img width="261" alt="2017-06-15 11 58 38" src="https://user-images.githubusercontent.com/6703674/27164750-ff49d1b6-51c1-11e7-9fe5-1bfedf5fa3c6.png">
连easyPrivacy都这样???

**Comment by uBlock-user** [comment]
Can't reproduce.

I rather get 3 to 4 popups.

**Comment by uBlock-user** [comment]
Add

```
dato.porn##script:inject(abort-on-property-read.js, open)
dato.porn##a[href^="//"]
```

That takes care of all the popups and hyperlink windows being triggered.

**Comment by Fezreal** [comment]
@uBlock-user  只加这两条, 还是会提示禁用adblock的.

**Comment by uBlock-user** [comment]
@Fezreal English please, I don't speak that language, neither I understand it.

**Comment by Fezreal** [comment]
`dato.porn##script:inject(abort-on-property-read.js, open)
dato.porn##a[href^="//"]`

Just add both,still a prohibition of prompting

**Comment by uBlock-user** [comment]
Those two are for popups only. I cannot reproduce anti adblock as it's already patched.

**Comment by Fezreal** [comment]
`@@||dato.porn/js/pop.js$script,~third-party`

this can fix anti adblock

**Comment by uBlock-user** [comment]
For anti adblock, this should do the job

`29443kmq.video,dato.porn###a`

**Comment by Fezreal** [comment]
I subscribed to too many ublock-scripts
If I do not add a white list, it will always be prompted to prohibit

**Comment by uBlock-user** [comment]
Remove AAK-Cont script and deactivate AAK-Cont filter list from uBO. Remove all uBlock-sripts and only keep this uBlockProtector. The issue is on your end.

**Comment by jspenguin2017** [comment]
This should fix popup for good.

**Comment by jspenguin2017** [comment]
@uBlock-user The old solution kind of worked, but has race condition sometimes, so I moved the solution over to List. Breaking `open` has the side effect of breaking Violentmonkey anyway. 
The white list is needed, as some initialization is done by the anti-adblock script. 

@Fezreal 你要是不想用脚本的话你必须去用AAK-Cont，以后有问题也去那边问。
另外，显示的已使用条数是不重复的条数，不是只有6条有效，是只有6条使用了。

**Comment by uBlock-user** [comment]
@jspenguin2017 I can't reproduce it though. Works as expected on my end.

**Comment by jspenguin2017** [comment]
@uBlock-user You are not using standard setup, right?

**Comment by uBlock-user** [comment]
Yes I'm not, the difference being not installing the List as I run my own list so I add the filters there and I have Chromium instead of Chrome.

**Comment by jspenguin2017** [comment]
Anyway doesn't matter, extension no longer have race condition.
