### ISSUE TITLE
kitguru.net

### ISSUE THREAD

**Issue by Connor37** [jspenguin2017/uBlockProtector#299]
### Test link (required): 
https://www.kitguru.net/gaming/matthew-wilson/gta-v-flooded-with-negative-reviews-on-steam-following-openiv-shutdown/

### Screenshot of the web page (required): 
![image](https://user-images.githubusercontent.com/8341213/27197386-514bbe74-520e-11e7-8a30-4ca6cf2407f1.png)
https://user-images.githubusercontent.com/8341213/27197386-514bbe74-520e-11e7-8a30-4ca6cf2407f1.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
![image](https://user-images.githubusercontent.com/8341213/27197433-754f65dc-520e-11e7-9d2f-e2e26cba2743.png)
https://user-images.githubusercontent.com/8341213/27197433-754f65dc-520e-11e7-9d2f-e2e26cba2743.png

**Comment by uBlock-user** [comment]
Filter - `kitguru.net##script:inject(setTimeout-defuser.js, an_message_display)`

**Comment by jspenguin2017** [comment]
Wait, some content images are caught in some filters and some ads are not blocked... Need to have another look.
