### ISSUE TITLE
uploadboy.com, dailyuploads.net

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#300]
[Link](https://uploadboy.com/oy8qhxpe1k91/1660) - [ScreenShot](http://prntscr.com/fk8f0l)

freaking pop-ups in [dailyuploads](https://dailyuploads.net/qab9emiqtb2y)

**Comment by jspenguin2017** [comment]
Use the template next time.

**Comment by uBlock-user** [comment]
Can't reproduce for `uploadboy.com`

**Comment by uBlock-user** [comment]
Download Offers tick popups - `dailyuploads.net##script:inject(abort-on-property-read.js, $.ready)`

**Comment by Dibbyo456** [comment]
It seems you whitlisted the the ads.js, isn't their any other way? I'm no JS coder, just curious, you only whitlist something which you can't patch.

Yes. Add the download offers tick popups too

**Comment by jspenguin2017** [comment]
@Dibbyo456 There isn't another way because the file is randomized on the server side. Well, there is always a way with Violentproxy but no one is using that.

**Comment by jspenguin2017** [comment]
@uBlock-user That rule doesn't work for me, I fixed it in another way.

**Comment by uBlock-user** [comment]
@jspenguin2017 It works fine, I don't see any popups coming from it and I directly get the download page.

**Comment by jspenguin2017** [comment]
@uBlock-user Didn't work for me, so I fixed it another way.

**Comment by uBlock-user** [comment]
Yeah I know and saw that, I'm just wondering why.

**Comment by jspenguin2017** [comment]
@Dibbyo456 Also, when you see "jspenguin2017 added a commit that referenced this issue", it means I pushed out a fix, you can click the hash on the right to see what I changed.
