### ISSUE TITLE
sznpaste.net

### ISSUE THREAD

**Issue by khrwani** [jspenguin2017/uBlockProtector#301]
Test link: http://sznpaste.net/WW7beNQr

Screenshot of the web page:  http://imgur.com/wthxdXu

Screenshot of the console: http://imgur.com/MY6iXnp

**Comment by uBlock-user** [comment]
FYI linkdrop links found on this page also contain BAB script. I have opened another issue.

**Comment by jspenguin2017** [comment]
linkdrop.net is fixed in #302

**Comment by jspenguin2017** [comment]
Still works. Closing.
