### ISSUE TITLE
linkdrop.net

### ISSUE THREAD

**Issue by uBlock-user** [jspenguin2017/uBlockProtector#302]
### Test link (required): 

http://linkdrop.net/JmERRi

### Screenshot of the web page (required): 

https://i.gyazo.com/6a60232391f24bd13c3213e47b931883.png

### Screenshot of the console (press `F12` to bring up the console) (required): 

https://i.gyazo.com/14f61dc010d247b2cd1c131d0b4fe33e.png

### Add everything else that you believe to be useful below (optional): 

Filter - `linkdrop.net##script:inject(bab-defuser.js)`

Also contains a 5 sec timer after reCaptcha is successfully completed.

**Comment by uBlock-user** [comment]
Third-Party PopAds popups are also present FYI

**Comment by marmooz** [comment]
i've added [linkdrop.net##script:inject(bab-defuser.js)] to my filters and the anti-adblock message is gone but now the whole anti-BOT captcha under the [Please check the captcha box to...] has disappeared. when i disable the ublock, the [i'm not a robot] comes back but after solving that, the page goes to a  white page with [Please disable your adblock and script blockers to view this page.] message
