### ISSUE TITLE
aetv.com

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#304]
Issue: https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/64
Test link: http://www.aetv.com/shows/born-this-way/season-3/episode-6
Another test link (no account required for this one): http://www.aetv.com/shows/born-this-way/videos/life-lessons-alan-on-the-perfect-family?playlist_slug=born-this-way-life-lessons

Requires Flash. 

![image](https://user-images.githubusercontent.com/7283682/27261190-15390d4e-53fb-11e7-852f-bf15b8a6bf38.png)
![image](https://user-images.githubusercontent.com/7283682/27261764-f9c69048-5406-11e7-8ff4-fc5a8155e5ea.png)

EasyList white lists need to be reversed. 

![image](https://user-images.githubusercontent.com/7283682/27261194-2c496740-53fb-11e7-871b-46690bb0adf8.png)

**Comment by ghajini** [comment]
If this works from easy list

`aetv.com#@#.ad`

**Comment by jspenguin2017** [comment]
@ghajini I still want to fix the whitelists.

**Comment by jspenguin2017** [comment]
OK, this should fix it, it is no longer trying to load whitelisted resources, so I'll leave the whitelists as is. 
```JavaScript
if (a.domCmp(["aetv.com"])) {
    a.inject(() => {
        "use strict";
        let val;
        window.Object.defineProperty(window, "_sp_", {
            configurable: false,
            set(value) {
                val = value;
            },
            get() {
                //Patch detection
                try {
                    val.checkState = (e) => { e(false); };
                    val.isAdBlocking = (e) => { e(false); };
                    delete val._detectionInstance;
                } catch (err) { }
                return val;
            },
        });
    });
}
```

**Comment by jspenguin2017** [comment]
Pushing to the store.

**Comment by uBlock-user** [comment]
Got v9.2! Is that the latest commit you pushed ?

**Comment by jspenguin2017** [comment]
9.2 is the latest solution commit, I have another optimization commit, pretty minor, I'll wait for next issue.

**Comment by jspenguin2017** [comment]
OK, this did fix the problem that was preventing background page from unloading. Anyway, 12MB of RAM isn't much, I'll wait for next solution commit.

**Comment by uBlock-user** [comment]
Is there a way we can know what version is the latest commit from the repo ?

**Comment by jspenguin2017** [comment]
`git fetch`

**Comment by uBlock-user** [comment]
any other way without installing the git software ?

**Comment by jspenguin2017** [comment]
I will mark issues that are fixed only in developer preview with `Awaiting Publication` label. I will only bump version before publishing. Developers are expected to use Git.

**Comment by uBlock-user** [comment]
Hmmm, so I will have to lookout for that label or I will have to check WebStore version. Installing Git client will be a waste of space on my machine as I'm not pushing any commits here, so just to install Git for checking updates is redundant for me.

**Comment by jspenguin2017** [comment]
Still works. Closing.
