### ISSUE TITLE
https://www.15min.lt/video

### ISSUE THREAD

**Issue by Vartotojas1234** [jspenguin2017/uBlockProtector#305]
Mozzila Firefox + Ublock Origin + Tampermonkey (uBlock Protector Script)
Doesnt show any videos. Example: https://www.15min.lt/video/tautvydo-sabonio-ir-paulinos-olivios-frukacz-vestuves-115218

**Comment by uBlock-user** [comment]
FF is not supported. Also you didn't follow the format either.

**Comment by Vartotojas1234** [comment]
U r WRONG FF is ok. I found the answer. If someone have the same problem, need to try these rules:
15min.lt###adocean_message
@@||15min.lt/js/ads/banner.js?adzone=$domain=15min.lt
@@||15min.lt^$generichide

**Comment by jspenguin2017** [comment]
@Vartotojas1234 Firefox is not supported, you have not read the contribution guideline, this is a warning.
