### ISSUE TITLE
script not downloading?

### ISSUE THREAD

**Issue by Zhangsun321** [jspenguin2017/uBlockProtector#306]
cant auto download the ublock protector script..
from step #4

**Comment by jspenguin2017** [comment]
Works for me, you need to explain more.

**Comment by Zhangsun321** [comment]
welp.. i tried helping a new user..  and he couldnt get it to work
i couldnt get it to download either
i went over to firefox...  and tried to just to download it onto tampermonkey.. wouldnt even download
had to have him manually copy and paste the script...

**Comment by jspenguin2017** [comment]
Huh, the install link is kind of not working, the Userscript is approaching end of life anyway, I'll just leave it like this until it's replaced.

**Comment by Zhangsun321** [comment]
ok....      i wont send anymore people here till the next thing comes out...
yea.. the install link wasnt workin... :)
ty for your time and work

**Comment by jspenguin2017** [comment]
Also the replacement is actually not going to run on Firefox as I will only publish it in the Chromium WebStore.

**Comment by jspenguin2017** [comment]
The extension is released.
