### ISSUE TITLE
Violent monkey doesn't want to load ublock protector script

### ISSUE THREAD

**Issue by Sheeraudacity** [jspenguin2017/uBlockProtector#307]
I can't even install ublock protector, there's no image available since when I press the install now link nothing happens, well not nothing the tab's icon starts to shutter and the tab becomes unable to go to any other site. I tried both https://openuserjs.org/scripts/jspenguin2017/uBlock_Protector_Script and https://jspenguin2017.github.io/uBlockProtector/ ,hell I downloaded the usercript itself and dragged it to violent monkey settings tab, as you may have already figured out I have no idea how to use violent monkey I only downloaded it for u block protector because I'd rather use it than AAK cont, never had this much trouble with tampermonkey always downloaded easily but violentmonkey is a pain in the ass

**Comment by jspenguin2017** [comment]
I'm aware that either the install link or Violentmonkey is bugged, but since Script is approaching end of life anyway, I won't be spending time fixing it. If you wish to use AAK-Cont, that's your freedom, but keep in mind that I won't be spending as much time maintaining AAK-Cont.

**Comment by Sheeraudacity** [comment]
I am pretty sure it's violent monkey I was able to download the script easily enough with tampermonkey, I'd rather not use AAK-cont can you tell me how to downloads scripts with violent monkey in general or anything that might interfere with that

**Comment by jspenguin2017** [comment]
Try pasting this link to "Install from URL" box: `https://github.com/jspenguin2017/uBlockProtector/raw/master/uBlockProtector.user.js`

I don't really know why it's bugged, I just want to work on the extension instead of debugging Violentmonkey, so I can once for good replace those script hosts that I'm relying on.

**Comment by Sheeraudacity** [comment]
Thanks it worked perfectly, good luck with fixing the extension

**Comment by jspenguin2017** [comment]
Don't close, so other people can see it...

**Comment by Sheeraudacity** [comment]
ooh my bad I thought that issues will remain in the issues tab even if closed and you should close an issue after it's been solved

**Comment by uBlock-user** [comment]
This is a regression bug in VM, nothing to do with the Script. With the release of v2.7.0, this bug was introduced.

**Comment by uBlock-user** [comment]
Okay many functions of VM are not working, looks like v2.7.0 is broken !

**Comment by ghajini** [comment]
@gera2ld fyi

**Comment by uBlock-user** [comment]
New bug report - https://github.com/violentmonkey/violentmonkey/issues/144

**Comment by jspenguin2017** [comment]
Violentmonkey is trying to support Firefox, that ended up to be a bad idea...

**Comment by jspenguin2017** [comment]
Hopefully this fixes it, I expected Violentmonkey to say it's not valid or just ignore the click, not freeze the page. Anyway, I won't rush the extension as I want to do it right.

**Comment by uBlock-user** [comment]
Okay, it appears the issue seems to be stemming with this script only.

**Comment by Piter432** [comment]
> keep in mind that I won't be spending as much time maintaining AAK-Cont.

Does this mean that in the future the AAK-Cont will not be developed or what?

**Comment by jspenguin2017** [comment]
@Piter432 Maybe, whatever happens to it, it will be better than the original AAK.

**Comment by jspenguin2017** [comment]
@uBlock-user Can you check if b6489d4d687a7f4f824969a4018bc51240579e4a fixed it?

**Comment by uBlock-user** [comment]
@jspenguin2017 I removed the script and reinstalled it and the issue is still there.

**Comment by uBlock-user** [comment]
Also I cannot disable the script in VM.

**Comment by jspenguin2017** [comment]
@uBlock-user What issue? Not installing? That's not my problem, I already added `@namespace`. If `null` is not a valid namespace, then he must add doc somewhere, as I won't be digging into the issues. 
I think he screw something up when refactoring for Firefox, another reason to not support Firefox.

**Comment by jspenguin2017** [comment]
> Also I cannot disable the script in VM.

That has nothing to do with my code...

**Comment by uBlock-user** [comment]
https://github.com/violentmonkey/violentmonkey/issues/144#issuecomment-309832836

That's what he said

**Comment by uBlock-user** [comment]
Everything was working fine until today and VM just screwed up out of no-where.

**Comment by uBlock-user** [comment]
Still all of this is happening on this script only so I think VM is somehow conflicting with this script somewhere

**Comment by jspenguin2017** [comment]
@uBlock-user OK, I don't care anymore, just let me finish the extension.

**Comment by uBlock-user** [comment]
@jspenguin2017 Sure, VM issues are not our responsibility anyway.

**Comment by jspenguin2017** [comment]
The extension is released.
