### ISSUE TITLE
save.thoaimedia.com

### ISSUE THREAD

**Issue by EmersonTR** [jspenguin2017/uBlockProtector#308]
Test link (required): https://save.thoaimedia.com/index.php
Screenshot of the web page (required): http://i.imgur.com/hVb6Ty4.png
Screenshot of the console (press `F12` to bring up the console) (required): http://i.imgur.com/dykvS9g.png

**Comment by uBlock-user** [comment]
Can't reproduce. Seems to have already been patched by the Script.
