### ISSUE TITLE
uBlock Protector Extension "Not Compatible"

### ISSUE THREAD

**Issue by FrogFan** [jspenguin2017/uBlockProtector#310]
### Add everything else that you believe to be useful below (optional): 
uBlock Protector script no longer available.  Attempted to install extension, got "Not Compatible" message.  Windows 7, Chrome, uBlock Origin

**Comment by jspenguin2017** [comment]
I marked it as require Chrome 59+ as I'm not sure which feature requires what, update your Chrome and try again.

**Comment by FrogFan** [comment]
That did it.  Thank you.

**Comment by uBlock-user** [comment]
Will not install on Chrome below version 59.

**Comment by jspenguin2017** [comment]
I'll leave this open for until Chrome 60 comes out.

**Comment by Zhangsun321** [comment]
ok jspenguin..    i got a few questions.. updates and sitefixes.  will they occur as frequently as with the old github system?

now it is an extension....... anything differnet in f12/devmode that we can read up on.... to make your life easier?

does this make  us ready for next years changes with ad blocking?

**Comment by jspenguin2017** [comment]
@Zhangsun321 
For fixes, it depends, I will push fixes to the store when I feel appropriate, if you use the developer preview, it will probably be the same frequency. 
The console output is pretty much the same, I changed the wording a bit. You will get many more logs in debug mode, the store version have debug mode turned off, developer preview may have it turned on or off depending on what I'm doing. 
I don't know what you are referring as next year's changes. If you mean Funding Choices, it's already released a while back.

**Comment by jspenguin2017** [comment]
@Zhangsun321 Actually, I'm not sure, I might have Continuous Integration to upload it for me.

**Comment by uBlock-user** [comment]
> does this make us ready for next years changes with ad blocking?

Elaborate on that. With the release of uBO 1.13.x, we now can use CSP policy via `csp` scriptlet FYI or via `$csp` directive which is also supported by ABP and found in Easylist filters, so third-party ads won't be any issue anymore.

**Comment by jspenguin2017** [comment]
@uBlock-user How does CSP help removing third party ads? Unless it goes though WebRTC it can just be blocked via `chrome.webRequest`. 
It could be useful to get rid of unwanted inline script, but it works as a whitelist and not blacklist, so to get rid of one inline script, you need to list everything else.

**Comment by uBlock-user** [comment]
@jspenguin2017 Read https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

Example - `example.com##script:inject(csp.js, script-src 'self')` 

Here only scripts originating from `example.com` domain will be loaded  and inline-script will not be executed, neither will `eval`, since inline-script will not be executed, third-party connections will not be made,as this is very strict, it cannot be used for every website out there but we can patch few like this where using such rules doesn't break the functionality of the website.

**Comment by jspenguin2017** [comment]
Or you can just use `chrome.webRequest`? Obviously it works, but it's not like we don't have a solution before.

**Comment by uBlock-user** [comment]
There's a difference, with `chrome.webRequest` the request is still made and then blocked, but in the case of CSP, it doesn't make connection request in the first place.

**Comment by jspenguin2017** [comment]
I guess it's faster because it's handled by native code. But fully blocking 3rd party connection is not always what we want.

**Comment by uBlock-user** [comment]
yes that and the downside being we have to be very careful when using CSP, otherwise we can break the entire website with one filter as it tends to be very strict.

**Comment by jspenguin2017** [comment]
It's been a while, I think everyone is upgraded to 59 now. Closing.

**Comment by uBlock-user** [comment]
Chrome 60 is out!
