### ISSUE TITLE
totaldebrid.org

### ISSUE THREAD

**Issue by Sheeraudacity** [jspenguin2017/uBlockProtector#311]
Seems to be the cause of some anti-adblock movement called BlockAdBlock seems legit got a website and everything.
![blockadblock](https://user-images.githubusercontent.com/28789170/27461010-536e9124-57c0-11e7-98fc-2366a1a049ec.png)
using the latest chrome version with the extension and the list on u block

**Comment by jspenguin2017** [comment]
Use the template next time.

**Comment by Sheeraudacity** [comment]
ehm ehm, sure but I'm am pretty much a noob when it comes to user scripts sooo how do I use it exactly

**Comment by jspenguin2017** [comment]
The Userscript is legacy now, all you need to do now is install the extension and enable the two filters.

**Comment by jspenguin2017** [comment]
Wait 10 minutes and update the filters, it should work after that.

**Comment by Sheeraudacity** [comment]
ooooh, ya it's working perfectly now thanks

**Comment by uBlock-user** [comment]
Remove the script and install the extension.

**Comment by uBlock-user** [comment]
Weird thing is the BAB script is the `eval` version which is already patched by the generic BAB solution in the extension yet that doesn't work on that domain and we need to use `bab-defuser.js`

**Comment by uBlock-user** [comment]
It used to, before when it was a user-script.

**Comment by jspenguin2017** [comment]
OK I think I know what's wrong.

**Comment by jspenguin2017** [comment]
Should be fixed in 9.6.
