### ISSUE TITLE
Automate store upload with Continuous Integration

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#312]
https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/web-store
https://developer.chrome.com/webstore/webstore_api/items/update
https://github.com/c301/grunt-webstore-upload/blob/master/tasks/webstore_upload.js

Automate store upload with Continuous Integration.

**Comment by uBlock-user** [comment]
So with this it every update will be get automatically uploaded to the webstore without you doing it ?

**Comment by jspenguin2017** [comment]
Yep, that's the goal.

**Comment by jspenguin2017** [comment]
https://docs.travis-ci.com/user/environment-variables/
Well, time to install Ruby...

**Comment by jspenguin2017** [comment]
Hum... 
![image](https://user-images.githubusercontent.com/7283682/27499207-0a0436dc-5820-11e7-8ad3-48d2128ca632.png)

**Comment by jspenguin2017** [comment]
Going to try again on a real Debian device...

**Comment by jspenguin2017** [comment]
Travis plz update your doc... 
https://github.com/abitrolly/travis.rb/commit/a0744f21d0514fd9a9f774e02c9034535076d496#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by jspenguin2017** [comment]
OK, I got the encryption working...

**Comment by jspenguin2017** [comment]
Google's docs on how to create credential are kind of crap... They need to make it noob friendly... Took me 1h to find the correct doc...

**Comment by jspenguin2017** [comment]
The doc on obtaining OAuth token is here: https://developer.chrome.com/webstore/using_webstore_api
But steps 7 and 8 are bad, the good doc for steps 7 and 8 is here: https://developers.google.com/identity/protocols/OAuth2

**Comment by uBlock-user** [comment]
Is it done ? I received another update to v9.9!

**Comment by jspenguin2017** [comment]
Yea I'm testing it... Not quite done yet.

**Comment by jspenguin2017** [comment]
The web store API is absolute crap, I have no way to check the current draft version...

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/27511214-91485ce2-58dc-11e7-8c18-10be235ede37.png)
And I received "OK"... Fix your docs...

**Comment by jspenguin2017** [comment]
Don't tell me I need a custom API to keep track of last build version... I'll just check published version, hopefully it'll go well.

**Comment by jspenguin2017** [comment]
Yea I guess I need to make an API server...... This is a bit more complex than I wanted... Anyway, I will manually upload updates until everything is ready.

**Comment by jspenguin2017** [comment]
It should be good now... Let me test it out...

**Comment by jspenguin2017** [comment]
Oh no, the build failed...

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/27512293-17560e30-58f9-11e7-869d-315bf8b82e84.png)
I finally finished implementing it... That was HARD...

**Comment by jspenguin2017** [comment]
Actually the script didn't run in the last build... But I'm sure it's good now. 

I was planning on making the extension install page to look a bit better, but getting too much attention is not really what I want. I will probably keep the install page as-is and the extension unlisted.

**Comment by jspenguin2017** [comment]
Alright, time to work on a syntax highlighter! 
![image](https://user-images.githubusercontent.com/7283682/27513511-f456eed6-5925-11e7-8dd4-b502bd9d862e.png)
