### ISSUE TITLE
fastserver.me

### ISSUE THREAD

**Issue by EmersonTR** [jspenguin2017/uBlockProtector#313]

**Comment by jspenguin2017** [comment]
A new domain of Rapidleech?

**Comment by EmersonTR** [comment]
Before was http://fastrapidleech.com.

**Comment by jspenguin2017** [comment]
It's just the alerts or there is something else?

**Comment by EmersonTR** [comment]
Just alerts.

**Comment by jspenguin2017** [comment]
Oh, that was easy.

**Comment by uBlock-user** [comment]
A rapidleech clone, just adding the domain will do the job.

**Comment by jspenguin2017** [comment]
@uBlock-user No, I don't think this version uses the same detection methods.

**Comment by jspenguin2017** [comment]
Still works, closing.
