### ISSUE TITLE
Firefox, IExplorer and other users.

### ISSUE THREAD

**Issue by TokcDK** [jspenguin2017/uBlockProtector#314]
Script was universal and was possible use it for any browser where was script extension but now it is GChrome 59+ ONLY extension. 
GChrome is very heavy for resources program and can not be used in many causes and many systems. 
What Firefox, IExplorer and all other browser users must to do now? Go back to original Reek's extension or last ublock protector script version?
It is realy realy bad...

**Comment by TokcDK** [comment]
ps. Sorry. Found AAK-Cont. Close then.

**Comment by uBlock-user** [comment]
> Script was universal

Where did you read that ? Cite your source. It was never anything remotely "Universal". Initially FF was supported **BUT** later on support was removed and it was Chrome only. IE is gone and dead, nobody uses that anymore. Please don't make up stuff out of thin air.

**Comment by ghajini** [comment]
@uBlock-user , are you on aak cont repository.... You can contribute little there....in that only 1 contributor exist `giwayume`.....that repo shouldn't be dead like aak repository....
