### ISSUE TITLE
generatorlinkpremium.com

### ISSUE THREAD

**Issue by Sheeraudacity** [jspenguin2017/uBlockProtector#315]
https://generatorlinkpremium.com/

not nearly as intrusive as the rest, this adblock detector will not let me download at a higher speed without removing it, any thoughts?? 
![generator link premium](https://user-images.githubusercontent.com/28789170/27473585-55b0bdac-5808-11e7-9f75-40d6ff1afb6c.png)

**Comment by uBlock-user** [comment]
Follow the template and edit your post accordingly.

**Comment by Sheeraudacity** [comment]
ooh I didn't read the console screenshot part, and the link is the name of the website itself try downloading a file like this (https://mega.nz/#!1K430Bia!MKdpptHqDMQPuHcL5Ch9z3MNfDeDnlM5sSvgmKieIU0) because it always stays in the same page
![pr 2](https://user-images.githubusercontent.com/28789170/27479544-008d3912-581d-11e7-82a3-2bf2c94c76a1.png)
See what I mean , hope this screenshot is ok

**Comment by uBlock-user** [comment]
CSS bait with reCaptcha

**Comment by uBlock-user** [comment]
Need to whitelist this https://generatorlinkpremium.com/ads/advertisement.php OR create the CSS classes via the Script.

No conditional check found.

**Comment by Sheeraudacity** [comment]
I am not quite sure it worked out (it says daily limit exceeded even though I didn't download anything), you'll have to check on your end, but I'll just assume it did and close this thread

**Comment by uBlock-user** [comment]
Why close the thread ? It hasn't been patched yet, leave it open.

**Comment by jspenguin2017** [comment]
I guess just inject the code ourselves...

**Comment by jspenguin2017** [comment]
Still works. Closing.

**Comment by ghajini** [comment]
is this working?
quick download shows antiadblock

**Comment by jspenguin2017** [comment]
Fixed.
