### ISSUE TITLE
realkana.com

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#318]
https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/75

http://realkana.com/study/

Nothing interesting in console.

**Comment by uBlock-user** [comment]
Anti adblock script - http://realkana.com/js/?abcdefg

**Comment by uBlock-user** [comment]
Filter - `realkana.com##script:inject(abort-on-property-read.js, hooAdBlock)`

**Comment by jspenguin2017** [comment]
That breaks the site, probably should apply `readOnly` on it.

**Comment by uBlock-user** [comment]
Can you test this - `realkana.com##script:inject(csp.js, script-src 'self' *)` See if breaks anything

**Comment by jspenguin2017** [comment]
CSP and just blocking are not different, actually `csp.js` can have some race condition.

**Comment by uBlock-user** [comment]
Works fine on my end, not seeing any race condition here or any domain I'm using it on.
