### ISSUE TITLE
gigaleecher.com

### ISSUE THREAD

**Issue by Sheeraudacity** [jspenguin2017/uBlockProtector#319]
Test link: https://www.gigaleecher.com/

Screenshot of the web page:
![giga](https://user-images.githubusercontent.com/28789170/27488068-661ca530-583e-11e7-9065-6ca764fd4be5.png)

Screenshot of the console:
![console](https://user-images.githubusercontent.com/28789170/27488087-797c0850-583e-11e7-89db-526fd84df066.png)

**Comment by uBlock-user** [comment]
Try this - `gigaleecher.com##script:inject(abort-on-property-read.js, alert)`

**Comment by uBlock-user** [comment]
Unfortunately I cannot test it as Chromium is throwing "NET::ERR_CERT_REVOKED" and is blocking the page in the name of Privacy error.

**Comment by Sheeraudacity** [comment]
I want to check it out but it's saying download limit exceeded don't know what's that about. It didn't let me download anything I'll check in 10 mins when it allows me "another" try

**Comment by uBlock-user** [comment]
Remove cache and site data and see if that limit message appears again

**Comment by jspenguin2017** [comment]
```JavaScript
function Download(){

		//var elem = $("#")
		if(document.getElementById('ad-top').innerHTML.length < 1000 ||
		(document.getElementById('ad-top').innerHTML.indexOf('display: none') >= 0)){
			alert("This service is funded by advertising, please disable your Adblock and retry.");
			top.location = location;
			return false;
		}
		document.forms[0].submit();
	}
```
I'll patch `getElementById`. Easy fix.

**Comment by jspenguin2017** [comment]
NVM just block this script: `www.gigaleecher.com/templates/plugmod/giga.js`

**Comment by jspenguin2017** [comment]
I feel the 10 minutes is not enforced, I think I can remove it.

**Comment by jspenguin2017** [comment]
The 10 minutes timeout seems to be done on server side, it's probably checking for IP...

**Comment by jspenguin2017** [comment]
Anyway, this should fix it.

**Comment by Sheeraudacity** [comment]
ip in some cases but not always because my vpn doesn't work on most, the timeout ended anyway I'll check it out

**Comment by Sheeraudacity** [comment]
yep works perfectly gave me another timeout god knows why but it works
