### ISSUE TITLE
What does uBlockProtector do?

### ISSUE THREAD

**Issue by SylveonBottle** [jspenguin2017/uBlockProtector#320]
I'm trying to find information on what it actually does, but all I can find is installation guides and "This extension covers uBO-Extra's functionalities."

There's no settings page to check in, no FAQ, no documentation or manuals, nothing.

**Comment by uBlock-user** [comment]
Description - **An anti-adblock defuser for uBlock Origin**

**Comment by jspenguin2017** [comment]
If you don't know what it does, you probably don't need it.
