### ISSUE TITLE
photobucket.com

### ISSUE THREAD

**Issue by superctr** [jspenguin2017/uBlockProtector#321]
### Test link (required):
http://i49.photobucket.com/albums/f278/katietiedrich/comic331_zps0e179cf7.png (redirects [here](http://photobucket.com/gallery/http://s49.photobucket.com/user/katietiedrich/media/comic331_zps0e179cf7.png.html))

### Screenshot of the web page (required):
http://i.imgur.com/nXOcn7c.png

### Screenshot of the console (press `F12` to bring up the console) (required):
see above

### Add everything else that you believe to be useful below (optional):
similar script to http://blockadblock.com/ however that one works (the block screen is removed)

**Comment by jspenguin2017** [comment]
Something is blocking jQuery......

**Comment by superctr** [comment]
![2017-06-23_19-58-36](https://user-images.githubusercontent.com/1159409/27494483-5eaf0a4e-584e-11e7-96e3-e2d86efa5051.png)
Apparently this was done by EasyList.

**Comment by uBlock-user** [comment]
This is also the old BAB script which should have been blocked by the generic BAB solution but doesn't.

**Comment by jspenguin2017** [comment]
@uBlock-user From when does the generic solution break all old BAB scripts?

**Comment by uBlock-user** [comment]
This is the second time I have seen `eval` based BAB script not being killed by the generic solution found in the Script. It always used to work when it was a user-script. I guess converting it to an extension might have broke something.

**Comment by uBlock-user** [comment]
Got v9.6! Looks like it's patched and working as expected.

Also Easylist is blocking jQuery via this bad filter - `|https://$third-party,script,domain=photobucket.com`

**Comment by ryanbr** [comment]
https://github.com/easylist/easylist/commit/55b62370a849ec8365673d3f67544bdc2e1b86d6

**Comment by jspenguin2017** [comment]
@ryanbr Why don't you just remove `|https://$third-party,script,domain=photobucket.com`? It doesn't block anything.

**Comment by ryanbr** [comment]
Revolving adservers.

**Comment by jspenguin2017** [comment]
@ryanbr I don't get it, why not just block the ad serving domain every time a new one pops up? If someone register a new ad serving domain, he probably wouldn't only use it for a single website.

**Comment by ryanbr** [comment]
Because we don't have infinite time to constantly check, see the waging war with popads currently on various websites which is being updated every 2-3 hours with new random domains.

**Comment by jspenguin2017** [comment]
@ryanbr It will cost more than infinite time to monitor every website on Earth for which library they are using. I don't buy that, I overridden that filter. I rather use a script to prevent popads from functioning than maintaining filters like that.

**Comment by ryanbr** [comment]
Its your call, but I see no reason to remove the filter. I fixed the false positive, its enough

**Comment by superctr** [comment]
With easylist updated everything appears to be fixed.
