### ISSUE TITLE
www.pg3dhacks.com

### ISSUE THREAD

**Issue by N1kk0kill** [jspenguin2017/uBlockProtector#322]
Test link (required): 
http://www.pg3dhacks.com/pixel-gun-1220-mod.html
Screenshot of the web page (required): 
http://imgur.com/a/mPtMm
Your screenshot must include the address bar, it should look something like this: http://imgur.com/a/mPtMm

### Screenshot of the console (press `F12` to bring up the console) (required): 
http://i.imgur.com/ecISf9W.png

**Comment by uBlock-user** [comment]
Case of Bad Installation. You're not running the standard setup.

**Comment by jspenguin2017** [comment]
Yep. The download button needs to be patched though...

**Comment by jspenguin2017** [comment]
```JavaScript
if (a.domCmp(["pg3dhacks.com"])) {
    a.ready(() => {
        const buttons = document.querySelectorAll("button");
        const matcher = /Unlock.*Download/;
        for (let i = 0; i < buttons.length; i++) {
            if (buttons[i].innerText === "Download") {
                buttons[i].disabled = false;
            } else if (matcher.test(buttons[i].innerText)) {
                buttons[i].remove();
            }
        }
    });
}
```
This fixes the download button. Closing this since it's not a valid issue.

**Comment by jspenguin2017** [comment]
@N1kk0kill Read the guideline next time, or you risk to get banned.
