### ISSUE TITLE
wabetainfo.com

### ISSUE THREAD

**Issue by rockyshaw** [jspenguin2017/uBlockProtector#323]
http://wabetainfo.com/

http://imgur.com/a/nh7Iv

**Comment by uBlock-user** [comment]
Bad Installation. Also you didn't post in accordance to the format specified in https://github.com/jspenguin2017/uBlockProtector/blob/master/CONTRIBUTING.MD

**Comment by uBlock-user** [comment]
Anti adblock script - http://wabetainfo.com/wp-content/uploads/phZpAqypuioT/MMjjlHgaGBfg.js?ver=2.2.1

Can be patched by killing the setTimeout call to `an_message_display`

**Comment by jspenguin2017** [comment]
@rockyshaw Read the guideline next time, or you risk to get banned.
