### ISSUE TITLE
uBlock Origin not enabled message when I have it enabled

### ISSUE THREAD

**Issue by Accelyte** [jspenguin2017/uBlockProtector#324]

**Comment by jspenguin2017** [comment]
Do you have generic hide enabled?

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/27510098-4d1e595a-58c7-11e7-89c7-55323d59591a.png)
Works for me.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
Run the logger, capture it and post it here

**Comment by jspenguin2017** [comment]
@uBlock-user It's not testing network blocking, I have that `div` to have id of `banner-ads`, which should be caught in generic filter.

**Comment by uBlock-user** [comment]
Logger is not only for network blocking but it logs any and all doms if inserted by the uBO.

This is how it should look like - https://i.gyazo.com/9e9dcf6d30ef5b7021441292046c47ff.png

**Comment by jspenguin2017** [comment]
Oh, yea, you are right... But it only show elements that it enforces...

**Comment by uBlock-user** [comment]
Basically it shows everything that is passed through `chrome.webRequest` API. WebRTC isn't sent through that that's why it still remains undetected unless you run `chrome://webrtc-internals`.

**Comment by Accelyte** [comment]
![chrome_2017-06-25_00-42-07](https://user-images.githubusercontent.com/21363469/27510239-20ff92d0-593f-11e7-8549-0b7bbf18928a.png)

**Comment by jspenguin2017** [comment]
You have something white listing that element... Don't worry about it.

**Comment by Accelyte** [comment]
Did an extension block it? I tried disabling Tampermonkey to see if it was a script's fault but the issue persisted.

**Comment by uBlock-user** [comment]
Disable all extensions except for uBO and uBlock Protector and then run the logger and refresh the page to see if the div gets caught.

**Comment by jspenguin2017** [comment]
First check the obvious: 
![image](https://user-images.githubusercontent.com/7283682/27510274-81298d3e-58ca-11e7-8253-10ac14d6dd8e.png)

**Comment by uBlock-user** [comment]
and make sure `Ignore generic cosmetic filters` **is NOT ticked** just like you see in the above picture.

**Comment by Accelyte** [comment]
Ok I unticked 'ignore generic cosmetic filters', and the error message disappeared. Do I have to have this disabled?

**Comment by uBlock-user** [comment]
There you go, that was root cause. Yes you have to, otherwise generic cosmetic filters won't be inserted by uBO which will save resources and result in faster page load BUT you will see some ads in return if they're not blocked by site specific cosmetic filters.

Gorhill's words

> Generic cosmetic filters are those cosmetic filters which are meant to apply on all web sites.
> 
> Though handled efficiently by uBlock₀, generic cosmetic filters may still contribute measurable memory and CPU overhead on some web pages, especially for large and long-lived ones.
> 
> Enabling this option will eliminate the memory and CPU overhead added to web pages as a result of handling generic cosmetic filters, and also lower the memory footprint of uBlock₀ itself.
> 
> It is recommended to enable this option on less powerful devices.

**Comment by Accelyte** [comment]
I see. Thanks for the detailed response and explanation. Maybe you should also leave a note in the installation instructions so others won't be affected by the same issue :)

**Comment by jspenguin2017** [comment]
@Accelyte I expect people to keep settings as-is, if they touch them, I expect them to know what they are doing.

**Comment by uBlock-user** [comment]
Actually this issue of yours has nothing to do with uBlock Protector. It's a uBO issue and it will happen at every website you visit once you tick that setting, so you should only tinker with settings if you know what you're doing.
