### ISSUE TITLE
diariodenavarra.es

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#325]
### Test link (required): 
http://www.diariodenavarra.es/noticias/sucesos/2017/06/24/fallece-una-mujer-apunalada-presuntamente-por-pareja-sevilla-538574-3204.html
### Screenshot of the web page (required): 
https://puu.sh/wtpLZ/f45d391984.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://puu.sh/wtprB/bb0c2ae3fa.png
https://puu.sh/wtpsn/470b6fc265.png

**Comment by jspenguin2017** [comment]
`diariodenavarra.es###abMsgWrap`
Sounds good?

**Comment by lain566** [comment]
It's ok
Thanks

**Comment by uBlock-user** [comment]
If you want to patch it  then use this filter - `diariodenavarra.es##script:inject(setTimeout-defuser.js, abElem)`
