### ISSUE TITLE
windowscentral.com

### ISSUE THREAD

**Issue by Connor37** [jspenguin2017/uBlockProtector#327]
### Test link (required): 
https://www.windowscentral.com/
### Screenshot of the web page (required): 
![image](https://user-images.githubusercontent.com/8341213/27520055-c0b8b500-5a01-11e7-91a1-7eed121e0414.png)
### Screenshot of the console (press `F12` to bring up the console) (required): 
![image](https://user-images.githubusercontent.com/8341213/27520059-e46453d8-5a01-11e7-9697-7576f3cde7a1.png)
![image](https://user-images.githubusercontent.com/8341213/27520061-f3926a48-5a01-11e7-9fa8-c4377e0209fa.png)

**Comment by jspenguin2017** [comment]
Show your address bar
![image](https://user-images.githubusercontent.com/7283682/27520192-8a8dcc70-59c2-11e7-900c-4e54576fc2d9.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
