### ISSUE TITLE
mylifetime.com

### ISSUE THREAD

**Issue by dianey** [jspenguin2017/uBlockProtector#331]
### Test link (required): 
http://www.mylifetime.com/shows/dance-moms/season-7/episode-1

### Screenshot of the web page (required): 

<img width="1054" alt="screen shot 2017-06-27 at 12 14 00 am" src="https://user-images.githubusercontent.com/2693914/27575152-a0c87c18-5acd-11e7-8abe-d4b3602107eb.png">

### Screenshot of the console (press `F12` to bring up the console) (required): 
<img width="559" alt="screen shot 2017-06-27 at 12 25 19 am" src="https://user-images.githubusercontent.com/2693914/27575709-75b6cb2c-5acf-11e7-87c1-23a04f6af29c.png">
<img width="552" alt="screen shot 2017-06-27 at 12 25 31 am" src="https://user-images.githubusercontent.com/2693914/27575717-77b66ab8-5acf-11e7-88de-71827ac55cf9.png">
<img width="549" alt="screen shot 2017-06-27 at 12 27 15 am" src="https://user-images.githubusercontent.com/2693914/27575722-7bacfea2-5acf-11e7-8a11-8addc891ba4c.png">

**Comment by uBlock-user** [comment]
Requires Flash !

same as https://github.com/jspenguin2017/uBlockProtector/issues/304

**Comment by jspenguin2017** [comment]
What's wrong with EasyList, stop whitelisting DoubleClick...

**Comment by jspenguin2017** [comment]
US Geo Lock apparently...

**Comment by uBlock-user** [comment]
They not only whitelist Doubleclick but GoogleSyndication server too and numerous other ad-servers if it helps, they have no quells about it either, whatever hides the ads from loading, they will do it.

**Comment by jspenguin2017** [comment]
I can't stop `_sp_` from making the request or it will stuck in an infinite loop (maybe I did it wrong...), have to block it from uBlock Origin. I guess we just have to override whitelists as they pop up...

**Comment by jspenguin2017** [comment]
Still works, closing.
