### ISSUE TITLE
Generic solution for ads.js v2

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#332]
Some websites request a script that look like: 
```
var e=document.createElement('div');
e.id='qvMym2bCOpKBX';
e.style.display='none';
document.body.appendChild(e);
```

Then use a code that look like this to detect blocked `ads.js`: 
```
if(!document.getElementById('qvMym2bCOpKBX')){
  //Do stuff
}
```

Whitelisting the `ads.js` file works fine, but that is not ideal, a scripted solution needs to be found. 

Test links: 
https://www.videohelp.com/
https://efilmy.online/mcimperium/11259/

**Comment by uBlock-user** [comment]
It's not requesting on my end which is weird. No matter what I do, it doesn't request it.

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/27592152-fa08e8ce-5b10-11e7-9c09-1c5af3b78798.png)
Is it cached?

**Comment by uBlock-user** [comment]
Yes, so I decided to block the ads.js by clearing the site and cache data and created a blocking filter for ads.js, and it requested, but it doesn't produce any anti adblock notice, so is it supposed to ?

**Comment by jspenguin2017** [comment]
Depends on the site. 4 whitelists in uBlock Protector are being replaced by `a.generic.adsjsV2()`: 

```
@@||gamersclub.com.br/js/ads.js$script,first-party,badfilter
@@||uploadboy.com/ads.js$script,first-party,badfilter
@@||vidoza.net/js/ads.js$script,first-party,badfilter
@@||videohelp.com/ads.js$script,first-party,badfilter
```

**Comment by uBlock-user** [comment]
It's supposed to display something like this

```javascript
<div id="zqFhRMLGTfwB">
  Our website is made possible by displaying online advertisements to our visitors.<br/>
  Please consider supporting us by disabling your ad blocker or buy <a href="http://go.videohelp.com/?id=19619X769413&site=videohelp.com&xs=1&isjs=1&url=https%3A%2F%2Fwww.playon.tv%2F&xguid=242ffcbdad7dea6ae1bcc5c4f93c0df9&xuuid=9a1eb197db858c6a940ac51b22943205&xsessid=0d239b0bdda32b67ce434da8d8f96ffe&xcreo=0&xed=0&sref=http%3A%2F%2Fwww.videohelp.com%2Fsoftware%2FPlayOn&pref=http%3A%2F%2Fwww.videohelp.com%2Fsoftware%3Ftoolsearch%3Dplayon%26submit%3DSearch%26portable%3D%26s%3D%26orderby%3DName%26hits%3D50&xtz=-60&abp=1" target="_blank" class="toollink">PlayOn (record Netflix)</a> :)
</div>
```

**Comment by jspenguin2017** [comment]
Just need to finish tweaking that matcher and we're good. 
```JavaScript
a.generic.adsjsV2 = () => {
    a.inject(() => {
        "use strict";
        const matcher = /[a-zA-Z0-9]{11,14}/; //From samples I saw, the length is 12 or 13, checking for 11 to 14 to be sure
        let original; //document.getElementById
        const newFunc = (...args) => {
            if (matcher.test(args[0])) {
                return original.apply(window.document, args) || window.document.createElement("div");
            } else {
                return original.apply(window.document, args)
            }
        };
        try {
            original = window.document.getElementById;
            window.document.getElementById = newFunc;
        } catch (err) {
            window.console.error("uBlock Protector failed to set up ads.js v2 defuser!");
        }
    });
};
```

**Comment by uBlock-user** [comment]
Second produce anti adblock notice via an embedded iframe

**Comment by uBlock-user** [comment]
This is the url that needs patching  - https://vidoza.net/embed-d3qb7fwscu5c.html

**Comment by uBlock-user** [comment]
Popups and anti adblock blockage

**Comment by jspenguin2017** [comment]
If you override the whitelist then yes, I haven't pushed by fix.

**Comment by uBlock-user** [comment]
Yes I overrode it with /`ads.js$script,important`. You still need to patch popunders/ups. Killing `open` seals that for good.

**Comment by uBlock-user** [comment]
They're also requesting https://vidoza.net/js/pop.js

**Comment by jspenguin2017** [comment]
I know, but that is not whitelisted and is taken care by Extension already.

**Comment by uBlock-user** [comment]
```javascript
jwplayer().onPlay(function(x) {
  // if file owner set adblock locking and user have adblock - block player with message
  if(ownerAdblockLock == 1 && (ifAb == 1 || window.cRAds === undefined || window.cRAds == null) ){
    $('#vplayer').prepend($('.vplayer-container').html());
    jwplayer().stop();
    return false;
  } else {
    doPlay(x);
  }
});

/**
* checking click on play button for sending firstclick event
**/
jwplayer().onDisplayClick(function(x){
   // if file owner set adblock locking and user have adblock - block player with message
  if(ownerAdblockLock == 1 && (ifAb == 1 || window.cRAds === undefined || window.cRAds == null) ){
    $('#vplayer').prepend($('.vplayer-container').html());
    jwplayer().stop();
    return false;
  } else {
    doPlay(x);
  }
});
```

**Comment by jspenguin2017** [comment]
Can you pull 9.25 from Store and try again? I think I fixed it.

**Comment by uBlock-user** [comment]
Yes, anti adblock is patched, but popunders/ups are still firing. Also is the solution generic ? I prefer it that way, this `ads.js` crap is being overused by every other domain as of late.

**Comment by jspenguin2017** [comment]
This `ads.js` defuser is not applied generically as it has a risk to cause some sites to malfunction, but we can easily call `a.generic.adsjsV2` on any domain that uses `ads.js`. 
Popup fixed in 9.26, it is being pushed to the Store by Travis.

**Comment by uBlock-user** [comment]
Perfect! Already got 9.26 via the Store, Travis was fast 😄

**Comment by jspenguin2017** [comment]
Alright, closing this, let me know if something is not right.

**Comment by uBlock-user** [comment]
Btw congratulations on gaining 1000+ users on the WebStore ㊗️

**Comment by jspenguin2017** [comment]
Publishing from Travis does not go though review at all, it shows up instantly, it's so weird, when I use the web interface it takes like 20 minutes.

**Comment by ghajini** [comment]
https://www.tubeninja.net/
may be related to ads.js whitelist,,,may be fixed by your approach....
steps to produce:
go to this site
enter any youtube video link in box and click download
this triggers antiadblock

**Comment by jspenguin2017** [comment]
It's checking via XHR. I'll just whitelist it...
