### ISSUE TITLE
portal.abczdrowie.pl

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#333]
Test link: https://portal.abczdrowie.pl/pytania/skutki-picia-octu-spirytusowego

Screenshot of the web page: 
![przechwytywanie1](https://user-images.githubusercontent.com/18214146/27611761-c5bcaa82-5b93-11e7-94cd-66f40484b2d5.PNG)

Screenshot of the console: 
![przechwytywanie](https://user-images.githubusercontent.com/18214146/27611785-da910d72-5b93-11e7-9346-0708ae82e528.PNG)

Can't watch the video because of the antiadblock message. Could you please fix it?

**Comment by jspenguin2017** [comment]
Huh... works for me...
![image](https://user-images.githubusercontent.com/7283682/27613102-eca7d6ea-5b56-11e7-8b5b-a5f0fbddf5b4.png)

**Comment by uBlock-user** [comment]
I can reproduce. Using `wp.tv,abczdrowie.pl##.windowErrCont ` the overlay doesn't appear.

**Comment by jspenguin2017** [comment]
The block screen show for a second or two for me, then goes away... I guess I can use cosmetic filter to remove it completely...

**Comment by jspenguin2017** [comment]
This was totally working this morning...

**Comment by adreporter** [comment]
@jspenguin2017 The message is gone, but I can't use the player to skip part of the video.

**Comment by jspenguin2017** [comment]
I pushed out a fix, it should be in the store in a few minutes.

**Comment by adreporter** [comment]
@jspenguin2017 Thanks.
