### ISSUE TITLE
linksh.top

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#335]
Test link: http://linksh.top/TRrHU

Screenshot of the web page:
![aaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/18214146/27664018-98209552-5c65-11e7-9af3-bdb99adac0bc.PNG)

Screenshot of the console: 
![aaaaaaaa](https://user-images.githubusercontent.com/18214146/27664026-a4d9c692-5c65-11e7-88b8-8cd00371bfe5.PNG)

**Comment by uBlock-user** [comment]
Clone of adshort, same script, same timer!
