### ISSUE TITLE
handelsblatt.com

### ISSUE THREAD

**Issue by jollyrogers88** [jspenguin2017/uBlockProtector#336]
Please add @@||handelsblatt.com^$generichide (I think @@||handelsblatt.com/js/*/iqadcontroller.js is redundant) to the blocklist.

**Comment by uBlock-user** [comment]
Follow the template provided and make a case if something is not working, not like this.

**Comment by uBlock-user** [comment]
Also can't reproduce any anti-adblock notice, works fine.

**Comment by jspenguin2017** [comment]
Cannot reproduce. You must use the template next time. This is a warning.

**Comment by jspenguin2017** [comment]
Also, I can't find `@@||handelsblatt.com/js/*/iqadcontroller.js` Did you copy it right? 
![image](https://user-images.githubusercontent.com/7283682/27690971-eff72e3c-5c9f-11e7-8140-0e93e4a1d9ab.png)

**Comment by uBlock-user** [comment]
Already patched by uBO - https://i.gyazo.com/26c618edd645303a53cfebe6ea3ecf94.png
