### ISSUE TITLE
abc.go.com

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#338]
https://github.com/reek/anti-adblock-killer/issues/3331

http://abc.go.com/shows/blackish/episode-guide/season-03/16-one-angry-man

![screenshot](https://user-images.githubusercontent.com/19941343/27716961-eb3dc110-5d0f-11e7-9bd8-0fbf80c97d11.png)

![image](https://user-images.githubusercontent.com/7283682/27720926-2c7876ca-5d1a-11e7-86b0-2f92719b0b94.png)

**Comment by jspenguin2017** [comment]
Looks like the player is blocked.

**Comment by uBlock-user** [comment]
Looks more broken at the website's end or is the extension breaking it ?

**Comment by uBlock-user** [comment]
Okay, I disabled all my extensions except uBO and it still happens. So either uBO is breaking it or the player is broken.

**Comment by jspenguin2017** [comment]
I guess neither... 
![image](https://user-images.githubusercontent.com/7283682/27737800-bc6125d8-5d66-11e7-9a00-b9b82f562016.png)

**Comment by uBlock-user** [comment]
Ofcourse ABC Network is owned by an American company named Disney. Try it with a US VPN.

**Comment by jspenguin2017** [comment]
It detects VPN. 
![image](https://user-images.githubusercontent.com/7283682/27739203-07328d82-5d6b-11e7-95a5-14b7ef0176da.png)

**Comment by jspenguin2017** [comment]
Does the `_sp_` rule works for this? Looks pretty similar...

**Comment by uBlock-user** [comment]
I can't test it, requires a VPN running on a US ISP and on top of that we have to disable uBO and I can't do that.

**Comment by uBlock-user** [comment]
You can use SoftEther VPN where servers are hosted on US ISP connections so the IP is of an ISP.

**Comment by jspenguin2017** [comment]
TunnelBear also have servers in the US, but this website seems to be able to detect it.

**Comment by jspenguin2017** [comment]
The error message is different, this one probably would require private VPN.

**Comment by uBlock-user** [comment]
You can try this if you don't want t install SoftEther VPN on your device -
 https://github.com/jspenguin2017/uBlockProtector/issues/294#issuecomment-308663278

**Comment by uBlock-user** [comment]
Tunnel Bear's servers are not hosted on ISP connections are they ? Connections hosted by Digital Ocean and such entities will be detected as VPN, you will have to change the IP to a US ISP like AT@T, Verizon and such.

**Comment by uBlock-user** [comment]
Got it working finally!

![](http://i.imgur.com/dUVbcAAg.png)

**Comment by jspenguin2017** [comment]
Which VPN did you use?

**Comment by uBlock-user** [comment]
Use **107.77.200.10** as the IP via ModHeader Extension and clear site data and cookies followed by a refresh and no need to disable uBO, you can keep it on!

**Comment by jspenguin2017** [comment]
And it just works? Then where is the anti-adblock?

**Comment by uBlock-user** [comment]
The above IP address belongs to AT&T  - https://myip.ms/info/whois/107.77.200.10

**Comment by uBlock-user** [comment]
No anti-adblock, it just works on my end.

**Comment by uBlock-user** [comment]
Set URL match to **https://*.go.com/*** and fill all IP address fields with **107.77.200.10**

**Comment by uBlock-user** [comment]
ModHeader for chrome - https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en

**Comment by uBlock-user** [comment]
Tested with only uBO and ModHeader enabled!

**Comment by uBlock-user** [comment]
There's a filter in EasyPrivacy which breaks the Geo-Lock check - > `/visitorapi.js` so to counter that use `@@||edgedatg.com^$script,domain=abc.go.com`

**Comment by jspenguin2017** [comment]
Got it. 
![image](https://user-images.githubusercontent.com/7283682/27741227-9d3226c0-5d71-11e7-95be-6bb1d9bef2f2.png)

**Comment by uBlock-user** [comment]
I take it you didn't face any anti-adblock notice either ?

**Comment by jspenguin2017** [comment]
Looks like that EasyPrivacy rule is the source of the problem...

**Comment by uBlock-user** [comment]
Yeah that one rule was causing the misunderstanding.

Also I will drop this list of AT&T subnets for any VPN use in future - https://gist.githubusercontent.com/uBlock-user/f18c6dfc58b63587344b1d0c85c0d8f6/raw/67c71799b8dea86c8ae1f8bd01de59f8103ee008/AT&T%2520subnets

You can use any IPs from the above list and no need to lock to one IP only.

**Comment by jspenguin2017** [comment]
They can just block `X-Forwarded-For` header... I always ignore that header and use `$_SERVER["REMOTE_ADDR"]`.

**Comment by uBlock-user** [comment]
They're not the only ones others do too. They compare IP addresses against their database to check whether the IP belongs to a VPN/Server hosting company or an ISP, that's the only way they can detect whether it's a VPN or not.

**Comment by jspenguin2017** [comment]
But why do they compare `X-Forwarded-For` header instead of the real IP address?

**Comment by uBlock-user** [comment]
because they wanna know the originating IP address and they don't trust the real IP address as that can be spoofed ? See - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

**Comment by jspenguin2017** [comment]
No, the header can be easily spoofed, the real IP cannot, some ISP have broken firewall and allow IP spoofing, but that is only useful in DDoS since the response will go to the wrong place.

**Comment by uBlock-user** [comment]
By connecting to a VPN server you can spoof the real IP address easily. I used to do that a lot when I used to join a game-server to play some multiplayer game online to mask my real IP.

**Comment by jspenguin2017** [comment]
The IP is the real IP of the VPN server, they will need a blacklist to detect VPN, but you can't just choose any IP you want.

**Comment by uBlock-user** [comment]
Ofcourse I can't just choose any IP if I'm connecting to a VPN, I will have to use the ones provided by the VPN company in question, but yeah real IP would then be the VPN server's IP and my ISP's IP will NOT be revealed and I can bypass their blacklist too by connecting to a VPN server hosted on a ISP connection, and they will have to trust that.

**Comment by uBlock-user** [comment]
Also the IP I used with the Mod-Header extension is a valid IP address of AT&T and not just something I made up.

**Comment by jspenguin2017** [comment]
Still, changing header is way easier, VPNs may not let you stream video for free for a long time.

**Comment by uBlock-user** [comment]
Many of them do if you're paying or if it's free then they will put up a snag like time-limit or data-caps etc.. Thanks to all spying and privacy invasive methods coming up, VPNs today are in huge demand and people are willing to pay.
