### ISSUE TITLE
adshorte.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#339]
Test link: http://adshorte.com/Xau4fP

Screenshot of the web page: 
<img width="526" alt="cattura" src="https://user-images.githubusercontent.com/18214146/27743820-8adf9cae-5dbd-11e7-9480-64b082ae6671.PNG">

Screenshot of the console:
<img width="587" alt="cattura1" src="https://user-images.githubusercontent.com/18214146/27743828-92e28e5c-5dbd-11e7-9290-e28ff9aa38bd.PNG">

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/3325

**Comment by uBlock-user** [comment]
Also has a 7 sec timer

**Comment by jspenguin2017** [comment]
This one is not quite ads.js v2, let's call it v1.5.

**Comment by adreporter** [comment]
@jspenguin2017 I can't solve the captcha anymore. Could you please fix it?

**Comment by jspenguin2017** [comment]
Remove the video first...

**Comment by jspenguin2017** [comment]
This should be good.

**Comment by adreporter** [comment]
Yep, it's fixed now. Thank you very much for what you're doing. You're the best and please don't leave like reek did. Internet is nothing without you!

**Comment by adreporter** [comment]
@jspenguin2017 
https://github.com/jspenguin2017/uBlockProtector/commit/87a27f41aebd8011c6fa790163d5a5526bea582c

Could you please add also the following rule?`||cloudfront.net^$domain=pasteca.sh`
Without this rule you won't solve the captcha at https://pasteca.sh/vV8bLmkr
