### ISSUE TITLE
[Off-topic] timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#340]
Test link (required): http://timesofindia.indiatimes.com/

When I visit `timesofindia.indiatimes.com` directly to the page I get a interstitial page which looks like [This](http://prntscr.com/fq2vvq). Then Few seconds later we get to view the actual page. A patch to bypass the interstitial page?

**Note**: `timesofindia.indiatimes.com` & `indiatimes.com` both are whole different websites.

**Comment by jspenguin2017** [comment]
Can't reproduce...
![image](https://user-images.githubusercontent.com/7283682/27744925-b5af3690-5d7e-11e7-8009-e074344fc0f7.png)

**Comment by Dibbyo456** [comment]
@jspenguin2017 Visit `timesofindia.indiatimes.com`directly. You surely get Interstitial page then 2-3 seconds later it will redirect you to that homepage (Like Forbes) I read the website almost daily, so I'm pretty sure it's exist.

**Comment by Dibbyo456** [comment]
@jspenguin2017 Don't right click that link & open in new tab. Copy that link then paste, then try to open.

**Comment by uBlock-user** [comment]
Does blocking the `inline-script` break anything ?

**Comment by Dibbyo456** [comment]
And the website never actually fully loads, neither the Homepage or article page, always keeps loading, I know they have Lazy-Load inbuilt but it should fully load.

**Comment by uBlock-user** [comment]
I don't see that happening if I block the `inline-script`

**Comment by Dibbyo456** [comment]
@uBlock-user Give me the filter, let me test it.

**Comment by jspenguin2017** [comment]
@Dibbyo456 Still can't reproduce: 
![image](https://user-images.githubusercontent.com/7283682/27746000-c8c93952-5d82-11e7-83f2-64dea3733abf.png)

**Comment by Dibbyo456** [comment]
@jspenguin2017 Then, I think it's GEO basis, only Indian users happen to see that page.
But, how come @uBlock-user producing the issue?

**Comment by jspenguin2017** [comment]
I don't see any redirect code in inline script...

**Comment by uBlock-user** [comment]
I'm not reproducing it either, but the inline-script is filled with nasty amount of ad code from third-party servers and what not and that interstitial is also an re directional ad and since I can't find any JS specific to that I'm suggesting you block the inline-script and see if it breaks anything.

Filter - `||timesofindia.indiatimes.com^$$inline-script`

**Comment by jspenguin2017** [comment]
Still can't reproduce.
