### ISSUE TITLE
uBlock Protector List

### ISSUE THREAD

**Issue by js017** [jspenguin2017/uBlockProtector#341]
https://github.com/jspenguin2017/uBlockProtector

![ublock protector list](https://user-images.githubusercontent.com/26278182/27749026-bacf2e66-5d9f-11e7-82f3-4d3675e93466.jpg)

It seems there's a lot of different anti-adblocker scripts, so which one is the correct one to use, Anti-Adblock Killer, uBlock Protector List, or AdBlock Protector Script? Are uBlock Protector List and AdBlock Protector Script the same scripts, made by the same person, with two different names? Why does uBlock Protector List say "(Discontinued, read message inside) uBlock Protector Script" in the settings? Thanks.

Firefox Developer Edition 55.0b6 (32-bit)
uBlock Origin 1.13.0
Anti-Adblock Killer 10.0
uBlock Protector List 8.61
AdBlock Protector Script 7.33

**Comment by jspenguin2017** [comment]
Don't look in the repository files list if you are not developer, installation instructions are here: https://jspenguin2017.github.io/uBlockProtector/

**Comment by uBlock-user** [comment]
FYI, your browser is not supported either.
