### ISSUE TITLE
uBlock Protector

### ISSUE THREAD

**Issue by js017** [jspenguin2017/uBlockProtector#342]
https://github.com/jspenguin2017/uBlockProtector

![ublock protector](https://user-images.githubusercontent.com/26278182/27752891-3b00b27e-5db1-11e7-882d-fa8293b1be00.jpg)

Why did you create uBlock Protector for uBlock Origin in Firefox and now your website says it can only be used in Chrome, but uBlock Protector List still shows up in uBlock Origin for Firefox's 3rd-party filters setting page under "Ads" and "Custom"? You should let users know if you don't plan to continue development for a specific browser, and make sure that your script uninstalls automatically from a browser when it updates the scripts if it isn't available anymore for that browser. Also, if you close the post then how can someone respond to your comments? Thanks.

Firefox Developer Edition 55.0b6 (32-bit)
uBlock Origin 1.13.0
Anti-Adblock Killer 10.0
uBlock Protector List 8.61
AdBlock Protector Script 7.33

**Comment by jspenguin2017** [comment]
It no longer work for Firefox, I can't make the script to uninstall by itself so I changed its title so users are notified. List is in Ads section for all browsers and that is out of my control. You can still reply to a closed issue. 
Now you have broken many of my rules, this is your last warning, post invalid issue again and you are banned.

**Comment by js017** [comment]
Why did you stop development of uBlock Protector for Firefox and make it only for Chrome? Where is a list of your rules? All the issues I asked you about were valid issues. You can try and be a little bit more polite to different users. The rest of your information was helpful. Have a good day. Thanks.

**Comment by jspenguin2017** [comment]
I have no reason to be polite to someone who ignores my rules. I stopped developing it for Firefox because it takes too much time. 
![image](https://user-images.githubusercontent.com/7283682/27755187-614aacba-5dab-11e7-9153-fe4d585fc35b.png)

**Comment by uBlock-user** [comment]
Why do you keep asking these kind of questions ? Read the homepage for once! It doesn't say Firefox, so end of story! There's nothing to argue to about it!
