### ISSUE TITLE
gamereactor.*

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#343]
Need to update the logic that skips "welcome" page. 

http://www.gamereactor.eu/news/558613/H1Z1+gets+team+scoring+leaderboards/

![image](https://user-images.githubusercontent.com/7283682/27759253-d77e21a4-5de8-11e7-8ffc-153c2490af15.png)

**Comment by uBlock-user** [comment]
It's cookie based. We did place countdowntoAd and it's value to -1 if you can recall.

**Comment by uBlock-user** [comment]
Okay it's not the inline-script. So it's some first party going into action when you delete all cookies and site data or when you keep refreshing and it happens once in a while then.

**Comment by uBlock-user** [comment]
Could that be the one - http://www.gamereactor.eu/lay/shared_functions.js?v39 ?

**Comment by jspenguin2017** [comment]
I'm 99% certain that it is done on server side.

**Comment by jspenguin2017** [comment]
Domains: 
`Gamereactor.dk, Gamereactor.se, Gamereactor.no, Gamereactor.fi, Gamereactor.de, Gamereactor.it, Gamereactor.es, Gamereactor.eu, Gamereactor.pt`
(thanks to Wikipedia)

**Comment by jspenguin2017** [comment]
I think I know how their cookie works, but it needs to be done in the background page...
![image](https://user-images.githubusercontent.com/7283682/27762885-1f99a802-5e37-11e7-8ef3-2963a5014e13.png)

**Comment by jspenguin2017** [comment]
Doesn't seem to work, it is probably validated with session on the server side. Going with an auto-reload approach.

**Comment by uBlock-user** [comment]
Block all first party scripts and it doesn't happen, so it not done server-side.

**Comment by jspenguin2017** [comment]
Hum... The server does serve a different document though... There are way too many first party scripts, it happen once every 10 articles, I'll just go with the current auto-reload solution.

**Comment by uBlock-user** [comment]
NVM, I just tested blocking all scripts and inline-script and it still happened 1 out of 5 times, so it's random and server side apparently.

**Comment by uBlock-user** [comment]
I faced it first when I opened it here -https://github.com/jspenguin2017/uBlockProtector/issues/124

**Comment by jspenguin2017** [comment]
Yea, the old solution doesn't work anymore. The server is now aware of potentially tampered cookies...

**Comment by uBlock-user** [comment]
I don't suppose you can merge two issues into one. Does github provide such functionality ?

**Comment by jspenguin2017** [comment]
No. I think you can do it manually with GitLab. Why would you want to merge them?

**Comment by uBlock-user** [comment]
Duplicate issue that's why. Merging them together will have all the information in one place and could be beneficial when ever someone opens a duplicate issue we could merge them and streamline it in one place.

**Comment by jspenguin2017** [comment]
No, long threads are harder to navigate. When a new solution is needed, old one tend to be irrelevant.

**Comment by uBlock-user** [comment]
Yeah the downside of having it merged too.

**Comment by jspenguin2017** [comment]
Works. Closing.
