### ISSUE TITLE
onet.pl, komputerswiat.pl

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#347]
https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/95

https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/97

**Comment by lain566** [comment]
![duza_aktualizacja_do_pokemon_go_ma_powstrzymac_osz_2017-07-13_01-42-39](https://user-images.githubusercontent.com/27441315/28144576-9784d916-676c-11e7-8ffd-da6a6f2c0fca.png)

The video player is broken, this rule might be the source of the problem https://github.com/jspenguin2017/uBlockProtector/commit/cfc817cb016f01bef05bd179f42c7770c067dc3d

test link
http://www.komputerswiat.pl/nowosci/gry/2017/16/duza-aktualizacja-do-pokemon-go-ma-powstrzymac-oszustow.aspx

more:
http://www.komputerswiat.pl/wideo.aspx

**Comment by jspenguin2017** [comment]
Yea, the rule is too aggressive, I guess I would have to patch it another way.

**Comment by jspenguin2017** [comment]
Looks like it only breaks `komputerswiat.pl`

**Comment by jspenguin2017** [comment]
Looks good. Closing.
