### ISSUE TITLE
sovrnlabs.net

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#348]
This domain, `sovrnlabs.net`, seems to be an ads serving domain related to https://www.sovrn.com/
I'm not sure if it is safe to block the whole domain, it is serving a script that includes adblock detection to http://asoiaf.westeros.org/ which is currently suppressed by Extension with a DOM watcher. 
The domain is registered for over 7 months, and is still not blocked by EasyList. Need investigation.

**Comment by jspenguin2017** [comment]
Maybe we can just ask them? :trollface:

**Comment by uBlock-user** [comment]
page is empty ???

**Comment by uBlock-user** [comment]
Just block it like this `||sovrnlabs.net^$domain=westeros.org`

**Comment by jspenguin2017** [comment]
Well, that domain doesn't have a home page...

**Comment by uBlock-user** [comment]
FYI I can't reproduce any anti adblock at `westeros.org` or at its sub-domain either even when I disable the extension.

**Comment by jspenguin2017** [comment]
I can reproduce it if Extension is off: 
![image](https://user-images.githubusercontent.com/7283682/27962695-ececd646-62ef-11e7-8ace-2ffb0a2d177f.png)

**Comment by jspenguin2017** [comment]
I'm going with the restricted blocking filter, I don't have enough data to know if blocking the whole domain is safe.
