### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#349]

**Comment by uBlock-user** [comment]
Nothing to do with this extension. Did you run the logger ?

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/20e3c758d733a5ea9599b59525cbf6fc.png)

Bad Filter by Easylist. This is why you should always run the logger first and check for bad filters by filter list maintainers before posting here.

**Comment by Dibbyo456** [comment]
So, How to Fix?

**Comment by uBlock-user** [comment]
`_ad6.$domain=~facebook.com`

Does that work on your end ? For some reason uBlock Origin is not applying that filter.

**Comment by Dibbyo456** [comment]
@uBlock-user Nope. uBO ignoring that Filter.

**Comment by uBlock-user** [comment]
@ryanbr

**Comment by uBlock-user** [comment]
@gorhill Why isn't `_ad6.$domain=~facebook.com` being applied by uBO ?

**Comment by gorhill** [comment]
> Why is _ad6.$domain=~facebook.com being ignored by uBO ?

It's not being ignored, as expected it's not applied. The network request however is still filtered by the filter `_ad6.`. You need an exception filter to override `_ad6.`in EasyList:

    @@_ad6.$domain=facebook.com

**Comment by gorhill** [comment]
Fixed in Unbreak filters until fix is in EasyList: <https://github.com/uBlockOrigin/uAssets/commit/d81d6d14d6b119e75269ef0939749b2ce972e9b5>.

**Comment by uBlock-user** [comment]
Yes, thanks but would you explain the logic behind not applying that filter ?

**Comment by gorhill** [comment]
Given two distinct blocking filters:

    _ad6.
    _ad6.$domain=~facebook.com

The first one is a hit, the second one is not.

**Comment by uBlock-user** [comment]
Hmmm, I guess that doesn't get applied to `$badfilter` as `_ad6.$badfilter`, on the contrary.

**Comment by gorhill** [comment]
`badfilter` tells the filtering engine to remove a specific filter from the filterset. `_ad6.$badfilter` removes the filter `_ad6.` and consequently only `_ad6.$domain=~facebook.com` would be left. However, the filter `_ad6.` is not bad, it just is a false positive on facebook.com, and consequently the solution is an exception filter.

**Comment by jspenguin2017** [comment]
Looks like EasyList updated their rule.

**Comment by jspenguin2017** [comment]
Yep, it's fixed after updating filters. Is Facebook intentionally naming their files like that?

**Comment by uBlock-user** [comment]
Probably or probably it came out of a coincidence as all the scripts are named with random letter and numbers.

**Comment by collincusce** [comment]
I'm still having issues with messenger.com but facebook.com is working.

**Comment by jspenguin2017** [comment]
@ryanbr

**Comment by uBlock-user** [comment]
Same filter is being applied there from the `FBCDN` domain.

**Comment by Dibbyo456** [comment]
`messenger.com` still broken.

**Comment by jspenguin2017** [comment]
Flush your filters I guess. 
https://github.com/uBlockOrigin/uAssets/commit/0b83e002fc7576bfe38be1af38fb920b7ec76edf
