### ISSUE TITLE
dingit.tv

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#352]
### Screenshot of the web page: 
![image](https://user-images.githubusercontent.com/7283682/27976972-ef1a625e-6325-11e7-9b23-793c61d3013b.png)

**Comment by uBlock-user** [comment]
traces of Anti adblock 
http://www.dingit.tv/v2-assets/js/vendor.js?1487955086586

http://www.dingit.tv/v2-assets/js/app.js?1499438377258

**Comment by uBlock-user** [comment]
Whitelisting http://www.dingit.tv/js/dingit-player/js/html5/videojs.ads.js works

**Comment by uBlock-user** [comment]
and as a consequence it will try to pull ads via WebSocket connection

![](https://i.gyazo.com/c419b4cc265523bbe4cf9c5c4d748b55.png)

**Comment by jspenguin2017** [comment]
Weird, it's not requesting `videojs.ads.js` anymore...

**Comment by uBlock-user** [comment]
Is `video.js.ads.js` the player itself or load the player after it loads ?

**Comment by jspenguin2017** [comment]
I think it is a VideoJS plugin, it should be requested with an inline tag. But I'm not seeing it in Logger anymore.

**Comment by uBlock-user** [comment]
Yeah it happened to me too, repeated clearing the site data and cookies and then opening in a new tab made it appear again.

**Comment by jspenguin2017** [comment]
That's weird, if they don't check it every time, how can they know if the user turned off his adblocker?

**Comment by ghajini** [comment]
https://www.reddit.com/r/starcraft/comments/32te5g/dingit_rolls_out_antiadblock_measures/

**Comment by jspenguin2017** [comment]
@ghajini We are here to break their code, not to ask them to remove their code or to listen to their excuses.

**Comment by ghajini** [comment]
No they are just trolling adblock users ...madalssc2 comments

**Comment by uBlock-user** [comment]
Trolling or not trolling doesn't matter

**Comment by jspenguin2017** [comment]
Yep, can confirm that whitelist `@@||dingit.tv/js/dingit-player/js/html5/videojs.ads.js$first-party` works. 
Is that the vanilla VideoJS plugin?

**Comment by jspenguin2017** [comment]
I broke my IDE...

**Comment by lain566** [comment]
my whitelist

```
@@|http://www.dingit.tv/v2-assets/css/playerjs/videojs.ads.css
@@|http://www.dingit.tv/js/dingit-player/js/html5/videojs.ads.js
dingit.tv#@#.*
```

**Comment by jspenguin2017** [comment]
That's unacceptable.

**Comment by jspenguin2017** [comment]
```
dingit.tv#@#.adsbox
||dingit.tv/js/dingit-player/js/html5/videojs.ads.js$script,redirect=noopjs
```

**Comment by lain566** [comment]
Ohh you already have the solution... my bad

**Comment by uBlock-user** [comment]
Works perfectly, patched!

**Comment by jspenguin2017** [comment]
Still works. Closing.
