### ISSUE TITLE
short.am

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#356]
Test link: http://short.am/9SCLoi

Screenshot of the web page: 
<img width="960" alt="cattura33" src="https://user-images.githubusercontent.com/18214146/27987871-7e9f7de8-6415-11e7-9b92-b1e450588b22.PNG">

Screenshot of the console: 
<img width="960" alt="cattura4545" src="https://user-images.githubusercontent.com/18214146/27987874-8bb0fc96-6415-11e7-9dba-726cad077a49.PNG">

**Comment by Dibbyo456** [comment]
@adreporter It's actually redirecting me to 2paste, few seconds later. Use [adsbypasser](https://adsbypasser.github.io/)

@jspenguin2017 Why EasyList [allowing ads](http://prntscr.com/ft8e6e) on that domain?

**Comment by adreporter** [comment]
@Dibbyo456 I don't use adsbypasser anymore.

**Comment by Dibbyo456** [comment]
@jspenguin2017 I'm getting ads.

**Comment by jspenguin2017** [comment]
Update List, I overrode that whitelist.

**Comment by Dibbyo456** [comment]
@jspenguin2017 Thank you. But why would they whitelist it? Bribe?

**Comment by uBlock-user** [comment]
Left over ad place holder - `short.am##.adsbygoogle`

**Comment by jspenguin2017** [comment]
Can't seem to bypass the popup. Does AdsBypasser has a solution for this?

**Comment by jspenguin2017** [comment]
https://github.com/adsbypasser/adsbypasser/blob/master/src/sites/link/short.am.js
OK, I'll implement this.

**Comment by Dibbyo456** [comment]
@jspenguin2017 Enabling AdsBypasser, actually redirect to the destination URL without even solving captcha.

**Comment by jspenguin2017** [comment]
@Dibbyo456 I won't test for conflict, it's up to you to decide what to do.

**Comment by jspenguin2017** [comment]
It's now using another checking logic, it should now be 1 second faster.

**Comment by ghajini** [comment]
need update...its causing load-reload cycle...page never load completely...on standard setup

**Comment by jspenguin2017** [comment]
Yep, I see that. Does Adsbypasser still work?

**Comment by jspenguin2017** [comment]
OK, this fixes it...
