### ISSUE TITLE
wdbloog.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#357]
Please can u fix this site

### Screenshot of the web page : 
http://i.imgur.com/qRjnylU.png
-->

### Screenshot of the console  
http://i.imgur.com/gbyekTZ.png

ublock origin installed 
ublock protector installed
tampermoneky installed >> and script anti-adblock killer reek installed

custom 3rd party filters  installed
Custom (2)
AakList (Anti-Adblock Killer)​​
uBlock Protector List​​

**Comment by jspenguin2017** [comment]
Fixed. Also, don't use AAK.

**Comment by titosalah** [comment]
thank you  jspenguin2017   >> Fixed. Also, don't use AAK.
now i remove anti-adblock reek killer script from  custom  filter (ublock origin)
and disable tampermoneky
now only  ublock origin and ublock protector installed
and same message appeared http://i.imgur.com/qRjnylU.png

**Comment by jspenguin2017** [comment]
Did you update your filters?

**Comment by titosalah** [comment]
jspenguin2017  thank you very very much my best friend 
after update uBlock Protector List filter 
every thing working very good  
love u

**Comment by jspenguin2017** [comment]
Alright, closing then.
