### ISSUE TITLE
vz.lt

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#360]
### Test link (required): 
http://www.vz.lt/laisvalaikis/2017/06/10/keliaujame-po-lietuva-moletai-kviecia-gaudyti-rojaus-zuvis
### Screenshot of the web page (required): 
![keliaujame_po_lietuva_moletai_kviecia_gaudyti_roj_2017-07-09_00-21-04](https://user-images.githubusercontent.com/27441315/27989602-accac6e2-643c-11e7-800f-49e3d4f846eb.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww vz ltlaisvalaikis20_2017-07-09_00-21-18](https://user-images.githubusercontent.com/27441315/27989606-b8f9de3a-643c-11e7-860d-84e28971ef9d.png)

**Comment by jspenguin2017** [comment]
```JavaScript
$(function() {
    var e = function() {
        if ("undefined" != typeof vzCountersMaster) {
            var e = "m=" + vzCountersMaster;
            "undefined" != typeof sas && void 0 !== sas.__smartLoaded || (e += "&a=1");
            var t = document.createElement("script");
            t.async = "async", t.type = "text/javascript", t.src = "http://static.vz.lt/files/antsrauto/countsJS.php?" + e + "&t=" + (new Date).valueOf();
            var i = document.getElementsByTagName("script")[0];
            i.parentNode.insertBefore(t, i)
        }
    };
    setTimeout(e, 2e3)
});
```
Filter `setTimeout` should do it.

**Comment by jspenguin2017** [comment]
Actually, let's block `countsJS.php`.

**Comment by lain566** [comment]
Thanks for this promptness
