### ISSUE TITLE
endocrineweb.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#361]
### Test link (required): 
https://www.endocrineweb.com/
### Screenshot of the web page (required): 
![endocrine_diseases_thyroid _parathyroid_adrenal_a_2017-07-09_00-26-19](https://user-images.githubusercontent.com/27441315/27989837-44614fd4-6443-11e7-9a6a-d77e84336184.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww endocrineweb com_2017-07-09_00-26-46](https://user-images.githubusercontent.com/27441315/27989842-52d8d708-6443-11e7-8735-450ade64638f.png)

**Comment by uBlock-user** [comment]
`||dk4ywix.com^$third-party`
