### ISSUE TITLE
nowloading.co

### ISSUE THREAD

**Issue by foobb** [jspenguin2017/uBlockProtector#363]
### Screenshot of the web page (required): 

![blokd](https://user-images.githubusercontent.com/30014774/27991412-00caa4b6-643c-11e7-8c43-b5a05cb1d657.PNG)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![blerkd](https://user-images.githubusercontent.com/30014774/27991423-307b591c-643c-11e7-92b1-def4c65e5563.PNG)

Message pops up about 2 seconds after the page loads. Also the console got cut off a tad at the bottom, but that's all the code.

**Comment by uBlock-user** [comment]
Ah yes, the infamous Google Funding Choices!

`nowloading.co##script:inject(abort-onproperty-read.js, stop)`

**Comment by uBlock-user** [comment]
Another domain  - `https://champions.co/`

**Comment by foobb** [comment]
Thanks that worked.
