### ISSUE TITLE
moviezr.org

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#365]
### Test link (required): 
https://moviezr.org/watch/The_Grand_Budapest_Hotel_2014
### Screenshot of the web page (required): 
![watch_the_grand_budapest_hotel_ 2014 _full_movie_o_2017-07-09_18-59-29](https://user-images.githubusercontent.com/27441315/27996045-a9281c36-64d9-11e7-95be-6af513516a09.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpsmoviezr orgwatchthe_gr_2017-07-09_18-59-56](https://user-images.githubusercontent.com/27441315/27996046-b34f1476-64d9-11e7-9d99-2dbfa891f2cd.png)

**Comment by jspenguin2017** [comment]
`moviezr.org##script:inject(abort-on-property-read.js, $.getScript)`
I'll roll out the fix later.

**Comment by lain566** [comment]
Fine, but there's no rush.

**Comment by uBlock-user** [comment]
same as https://github.com/jspenguin2017/uBlockProtector/issues/90
