### ISSUE TITLE
socketloop.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#366]
### Test link (required): 
https://www.socketloop.com/tutorials/how-to-show-different-content-from-website-server-when-adblock-is-detected

https://www.socketloop.com/blogs/check-out-gal-gadot-s-intense-workout-for-wonder-woman
### Screenshot of the web page (required): 
![check_out_gal_gadot s_intense_workout_for_wonder_w_2017-07-09_20-52-34](https://user-images.githubusercontent.com/27441315/27997034-74d5bdc4-64ef-11e7-91e1-1756f9e9117b.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww socketloop comblogs_2017-07-09_20-54-38](https://user-images.githubusercontent.com/27441315/27997035-7da47206-64ef-11e7-84ce-bf0c95f2b1dc.png)

**Comment by lain566** [comment]
Section not showing
https://www.socketloop.com/tutorials/android-studio-highlight-imagebutton-when-pressed-on-example

more:
https://www.socketloop.com/tutorials

**Comment by jspenguin2017** [comment]
Hum... it shows for a second and it collapses.

**Comment by lain566** [comment]
It's broken again

**Comment by jspenguin2017** [comment]
Fixed. They renamed `content` to `cootent`...

**Comment by lain566** [comment]
@jspenguin2017 It's broken. They changed something again.

https://socketloop.com/tutorials/nginx-web-server-go

**Comment by jspenguin2017** [comment]
Fixed.

**Comment by lain566** [comment]
It's broken.

**Comment by jspenguin2017** [comment]
These two websites are going after us...

**Comment by lain566** [comment]
@jspenguin2017 yep, `lolalytics` still not working for me.

**Comment by jspenguin2017** [comment]
I thought I fixed it...

**Comment by lain566** [comment]
They can see where their visitors come from any more. Maybe that's why they know us.

**Comment by jspenguin2017** [comment]
Yea... The `referrer` header...

**Comment by lain566** [comment]
@jspenguin2017 `lolalytics` has done it again.

**Comment by jspenguin2017** [comment]
They are so annoying...

**Comment by lain566** [comment]
It's broken again :sob:

`https://www.socketloop.com/tutorials/cloudflare-another-way-to-get-visitor-s-real-ip-address`

**Comment by jspenguin2017** [comment]
Eh, this is sticky...

**Comment by lain566** [comment]
broken

**Comment by lain566** [comment]
It's broken again

**Comment by jspenguin2017** [comment]
Do they have a meme in their console before? 
f1fce183f0637084fd1a5170a495aac4ade56aa3

**Comment by lain566** [comment]
That is new, I think.

**Comment by lain566** [comment]
Still not working for me

**Comment by jspenguin2017** [comment]
It's getting complex real fast...

**Comment by lain566** [comment]
Have you thought about using whitelist?

**Comment by jspenguin2017** [comment]
It's testing multiple ads servers.

**Comment by lain566** [comment]
They will never give up. :anguished:
https://github.com/reek/anti-adblock-killer/issues?utf8=%E2%9C%93&q=socketloop
https://adblockplus.org/forum/viewtopic.php?f=1&t=48436
https://www.facebook.com/socketloop/posts/655086711287929

Can user stylesheet help us with this?

**Comment by lain566** [comment]
Have you fixed it?

**Comment by jspenguin2017** [comment]
I think I did, do you have a link that does not work?

**Comment by jspenguin2017** [comment]
I wasn't expecting them to do it, but they are now checking if `fetch` works, and that is going to break some compatibility. Old Apple devices won't be able to properly display the content. 
![image](https://user-images.githubusercontent.com/7283682/30301074-95927b4e-9715-11e7-9003-06e7780c4ec1.png)

**Comment by lain566** [comment]
Does not work for me on the first load, works if I refresh the page
https://www.socketloop.com/tutorials/how-to-show-different-content-from-website-server-when-adblock-is-detected

They are worse than `lolalytics`

**Comment by jspenguin2017** [comment]
Can't reproduce, it works perfectly for me, even in incognito mode.

**Comment by lain566** [comment]
It's broken.

**Comment by jspenguin2017** [comment]
"Just add more obfuscation", their code looks more and more like BetterJsPop's code...

**Comment by uBlock-user** [comment]
This guy reminds me of BAB, the dev kept adding more obfuscation in hopes that it will make it harder and difficult which only made it worse for him.

**Comment by uBlock-user** [comment]
I can reproduce. Use `||socketloop.com^$inline-script` Works fine.

**Comment by jspenguin2017** [comment]
That does not work fine, the content format is not loading.

**Comment by uBlock-user** [comment]
Where ?

**Comment by jspenguin2017** [comment]
With inline script blocking: 
![image](https://user-images.githubusercontent.com/7283682/30485616-39c3ba52-99eb-11e7-8f90-4e359bc0347a.png)

Expected: 
![image](https://user-images.githubusercontent.com/7283682/30485600-298a1e74-99eb-11e7-8886-a0e22a21f998.png)

**Comment by uBlock-user** [comment]
That's the inline CSS, inline script won't block that.

**Comment by jspenguin2017** [comment]
No it's not, it sends an XHR to load the real content and replace the placeholder.

**Comment by uBlock-user** [comment]
Well this works - `socketloop.com##script:inject(setTimeout-defuser.js)` I haven't been able to pinpoint which setTimeout call to be precise.

**Comment by jspenguin2017** [comment]
Doesn't work for me.

**Comment by uBlock-user** [comment]
You might have to refresh and remove cookies. This website is another pain in the ass. It has been patched more than 5 times already that's why they have come so far.

**Comment by jspenguin2017** [comment]
Still doesn't. The last solution is this: 
```js
if (a.debugMode && a.domCmp(["socketloop.com"])) {
    //Issue: https://github.com/jspenguin2017/uBlockProtector/issues/366
    a.readOnly("epmads_block", false);
    a.readOnly("DMAds", true);
    a.inject(() => {
        "use strict";
        const _fetch = window.fetch;
        const re = /^https?:\/\//;
        const newFunc = (url, ...rest) => {
            if (re.test(url)) {
                return new window.Promise(() => { });
            } else {
                return _fetch.call(window, url, ...rest);
            }
        };
        window.Object.defineProperty(window, "fetch", {
            configurable: false,
            set() { },
            get() {
                return newFunc;
            },
        });
    });
    /*
    a.antiCollapse("innerHTML", (ignored, val) => {
        return !realVal.trim();
    });
    a.antiCollapse("innerText", (ignored, val) => {
        return !val.trim();
    });
    */
    a.replace(() => {
        this.addEventListener("readystatechange", () => {
            if (this.readyState === 4 && this.status !== 200) {
                window.Object.defineProperties(this, {
                    "responseText": {
                        configurable: false,
                        set() { },
                        get() {
                            return "Connection Established";
                        },
                    },
                    "status": {
                        configurable: false,
                        set() { },
                        get() {
                            return 200;
                        },
                    },
                    "statusText": {
                        configurable: false,
                        set() { },
                        get() {
                            return "OK";
                        },
                    },
                });
            }
        });
    });
}
```
Do you actually think you can patch it with one line filter?

**Comment by jspenguin2017** [comment]
OK, got it.

**Comment by jspenguin2017** [comment]
OK, got it.

**Comment by uBlock-user** [comment]
Yes and I did it. I checked it on two or three articles and it worked and then it didn't and on a fresh again it worked.

**Comment by jspenguin2017** [comment]
Test link is here: https://www.socketloop.com/tutorials/how-to-show-different-content-from-website-server-when-adblock-is-detected

**Comment by uBlock-user** [comment]
They already patched your solution once, they will do it again, they're desperate.

**Comment by uBlock-user** [comment]
Yes I tested it there myself. It works for me.

**Comment by lain566** [comment]
It's broken again...

**Comment by jspenguin2017** [comment]
I really don't know what to do now, it is now enforcing a freaking hash.

**Comment by uBlock-user** [comment]
Yeah content formatting is broke, they will never stop.

**Comment by jspenguin2017** [comment]
I don't have the resource to fight this, I need to come up with something smart.

**Comment by jspenguin2017** [comment]
The only thing I can think of is pile up obfuscation and anti-debugging just like what they did...

**Comment by ghajini** [comment]
the have this problem in incognito mode too
![chrome_2017-09-17_22-25-55](https://user-images.githubusercontent.com/20338483/30523035-712032e2-9bf7-11e7-9699-24ac2616d368.png)

**Comment by jspenguin2017** [comment]
I know that, that's why I'm not fixing it but planning the long term.

**Comment by uBlock-user** [comment]
`socketloop.com##script:inject(setTimeout-defuser.js)` still work btw

**Comment by jspenguin2017** [comment]
That definitely doesn't, the real content setter is wrapped in a `setTimeout`.

**Comment by uBlock-user** [comment]
What do you mean ? We already established that content formatting is broken even without using any adblocker in post https://github.com/jspenguin2017/uBlockProtector/issues/366#issuecomment-330062294 so that's NOT caused by the filter and my filter stops the content from getting wiped out.

**Comment by uBlock-user** [comment]
Without my filter - https://i.gyazo.com/da4d2ebf18f26b1a5f0c5034bb13c8d0.png

With my filter - https://i.gyazo.com/67df35b22b85d2cbdac42a267ddad1a2.png

As you can see, with my filter, the content stays and doesn't get WIPED out by innerHTML property value being set to "" via a `setTimeout` call.

**Comment by jspenguin2017** [comment]
Setting the real content is wrapped in a `setTimeout`, which never get to execute because something else is broken.

**Comment by ghajini** [comment]
@okiehsch, do you have lookup here?

**Comment by jspenguin2017** [comment]
The problem is not about finding a solution, is we need a way to protect our solution from reverse engineering.

**Comment by ghajini** [comment]
That has nothing to do with finding a solution.....I just encountered problem with adguard and that why reported there?

**Comment by jspenguin2017** [comment]
Yes, that's why the new solution can't be open source. I have obfuscated the new solution :)
Don't worry, it is not in the Web Store version, only in debug mode. 
https://github.com/jspenguin2017/uBlockProtector/commit/23a98afb615f15c8de36b298825329d466599e41

**Comment by jspenguin2017** [comment]
I still need to push the code to my server, still a bit of work to do on that side, the loader is ready, although I recommend you to just leave the site.

**Comment by uBlock-user** [comment]
Can't they obfuscate it like we do ?

**Comment by ghajini** [comment]
That commit should not be visible to anyone except you😊

**Comment by uBlock-user** [comment]
Commit will be visible, but he won't be commiting the solution via commit. Secondly, they can always download the extension, open the obfuscated file, and then deofuscate it.

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/issues/478#issuecomment-331749999
I don't think he succeeded. Well, that was for `lolalytics`, I didn't add `socketloop` yet.

**Comment by jspenguin2017** [comment]
I think I'm attracting more attention than I intended, from my server log, there are at least 3 people who attempted to reverse my code. I won't tell you to not try to reverse my code, as obviously no one is going to listen, but there really isn't anything interesting to see in there, it'll be easier if you just reverse the anti-adblock logic. 

I do ban IPs, I think most of you would have guessed by now, the solution won't work while your IP is banned. I'll update the unban process to make it more forgiving, also to prevent bad guys from rerolling his IP and put the ban on someone else's head. 

I also have plan on adding some more obfuscation and anti-reversing logic, I'll do that before fixing `socketloop`.

**Comment by darkbasic** [comment]
As I said, reversing is fun :)

**Comment by jspenguin2017** [comment]
I just added some next gen anti-reversing technology 😄 This should be impenetrable now!

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/commit/f214ec22f1b65c894b96d3a796ea833d9a129a8f

**Comment by ghajini** [comment]
i think reversed ?
![2017-10-08_17-43-33](https://user-images.githubusercontent.com/20338483/31316719-9e9c929c-ac50-11e7-830e-ba26c8b8b694.png)

**Comment by jspenguin2017** [comment]
Seems to be working for me. 
![image](https://user-images.githubusercontent.com/7283682/31319219-ac185f02-ac1c-11e7-981f-290d0ecb50ce.png)

**Comment by thrwat** [comment]
Does not work for me.

**Comment by jspenguin2017** [comment]
Still works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/31558001-6e604586-b008-11e7-839f-9b11f8f10daf.png)

**Comment by darkbasic** [comment]
Sooner or later he will whitelist your IP to let you think that it works while it doesn't :P

**Comment by jspenguin2017** [comment]
I have more than 1 IP. I tested on a couple of them, all works.

**Comment by thrwat** [comment]
JSPENGUIN2017, try on a different browser.

**Comment by jspenguin2017** [comment]
I only support one browser.

**Comment by jspenguin2017** [comment]
Also `socketloop.com` is part of proprietary solutions, so it only runs when Extension is loaded in debug mode.

**Comment by thrwat** [comment]
How do i run debug mode?

**Comment by jspenguin2017** [comment]
Clone the repo with Git, then load `/Extension Compiler/Extension` into Chrome.

**Comment by AhsanE** [comment]
You do know that you can bypass the antiDebugging with JavaScript disabled?

**Comment by AhsanE** [comment]
I can disable JavaScript without opening the inspector, and without page reload.

**Comment by jspenguin2017** [comment]
If you disable JavaScript, then there is nothing to debug.

**Comment by AhsanE** [comment]
There is. Some websites rely on JavaScript to manipulate HTML, after page
load. If you open inspector the page reloads.

**Comment by AhsanE** [comment]
Reverse engineering can also be done by judging the output.

**Comment by jspenguin2017** [comment]
I won't reveal how I made my anti debugging logic, if you think you can defeat it, then good for you.

**Comment by AhsanE** [comment]
Its darn easy.

**Comment by darkbasic** [comment]
It isn't for the guys at socketloop.com, that's more than enough.
