### ISSUE TITLE
gutefrage.net

### ISSUE THREAD

**Issue by xtrars** [jspenguin2017/uBlockProtector#367]
https://www.gutefrage.net/frage/wie-schalte-ich-adblock-ein

https://i.imgur.com/tdjRuxU.png

https://i.imgur.com/eY49DGM.png

**Comment by jspenguin2017** [comment]
Seems to work for me, which extensions do you have installed?

**Comment by xtrars** [comment]
uBlock Origin 1.13.2
uBlock Protector Extension 10.59
uMatrix 1.0.0
Privacy Badger 2017.6.13.1
Location Guard 1.2.0

**Comment by jspenguin2017** [comment]
What you see in the logger?

**Comment by xtrars** [comment]
To reproduce: go to the page and wait for loading the whole page and then refresh the page (i've pressed F5).

**Comment by jspenguin2017** [comment]
Nope, still works for me.

**Comment by jspenguin2017** [comment]
Configure your setup exactly like this: https://github.com/jspenguin2017/uBlockProtector/blob/master/Notes/Standard%20Configuration.MD
Then turn on your other stuff one by one and see what is causing the problem.

**Comment by lain566** [comment]
I can reproduce, sometimes
https://www.gutefrage.net/frage/welchen-namen-findet-ihr-am-schoensten--was-denkt-ihr-von-ihnen-

**Comment by jspenguin2017** [comment]
Nope, working consistently for me.

**Comment by lain566** [comment]
no idea

**Comment by xtrars** [comment]
The Log: http://imgur.com/a/KcKsN

I have all other extensions turned off. 
I have reset ublock to standard.

**Comment by jspenguin2017** [comment]
Hum... I don't see those DOM logs. 
![image](https://user-images.githubusercontent.com/7283682/27997441-58b3a00a-64b5-11e7-81c4-933d51c35631.png)

**Comment by xtrars** [comment]
a video (with my config) about the problem: http://imgur.com/a/Lxo8k

**Comment by adreporter** [comment]
Same problem here.
Screenshots of the console:
<img width="960" alt="p1" src="https://user-images.githubusercontent.com/18214146/27997500-7f9ed09c-64f9-11e7-9bf7-ed44b446b063.PNG">
<img width="960" alt="p2" src="https://user-images.githubusercontent.com/18214146/27997502-84119a24-64f9-11e7-9496-4e40621103b3.PNG">

**Comment by jspenguin2017** [comment]
You didn't wait for uBO to finish compiling filters.

**Comment by adreporter** [comment]
Maybe I found the reason why it's showing the anti-adblock message:
<img width="178" alt="cattura1" src="https://user-images.githubusercontent.com/18214146/27997595-e959e682-64fb-11e7-8ab6-28552eecedf0.PNG">
Only 5 used of 13.263
Am I the only one?

**Comment by jspenguin2017** [comment]
Yes I guess... 
![image](https://user-images.githubusercontent.com/7283682/27997609-18c78f20-64b9-11e7-9dc1-dda34d4d29bf.png)

**Comment by xtrars** [comment]
i have 13k too http://imgur.com/a/TRmSR

**Comment by adreporter** [comment]
@jspenguin2017 Unfortunately using only 5 filters of 13.263 wasn't the problem: just reset the uBlock Origin settings to default, but I'm still seeing the anti-adblock message.
This is what I see in the logger:
<img width="960" alt="pp1" src="https://user-images.githubusercontent.com/18214146/27997670-e85ada5a-64fd-11e7-8f63-5b0b4e4b7ba9.PNG">
<img width="782" alt="pp2" src="https://user-images.githubusercontent.com/18214146/27997671-edb8a5cc-64fd-11e7-83f3-19807ea9901e.PNG">

**Comment by jspenguin2017** [comment]
I see the DOM logs now, but I still don't see the block screen.

**Comment by xtrars** [comment]
If the blockscreen only appears for few users: i have a netherland ip

**Comment by adreporter** [comment]
@jspenguin2017 Sometimes I don't see it neither, but if I delete the website cookies
<img width="149" alt="aaaa" src="https://user-images.githubusercontent.com/18214146/27997734-1e1ddff6-64ff-11e7-836b-c95e2e15c2f4.PNG">
and press ctrl+r, the block screen will appear. Can you reproduce?

**Comment by okiehsch** [comment]
I can reproduce, the site uses sourcepoint, 
`gutefrage.net##script:inject(abort-on-property-write.js, _sp_)`
fixes the issue but also breaks some site functionality, namely search.
I will have to take a closer look and a fix will also be part of `uBO-filters`

**Comment by okiehsch** [comment]
`||happyunicorns.gutefrage.net^$script,redirect=noopjs,domain=gutefrage.net`
or
`gutefrage.net##script:inject(abort-on-property-read.js, _sp_._networkListenerData)`
work without any obvious site breakage on my end.

**Comment by jspenguin2017** [comment]
I have a generic `_sp_` defuser: 
```JavaScript
if (a.domCmp(["aetv.com", "history.com", "mylifetime.com"])) {
    a.inject(() => {
        "use strict";
        let val;
        window.Object.defineProperty(window, "_sp_", {
            configurable: false,
            set(value) {
                val = value;
            },
            get() {
                //Patch detection
                try {
                    val.checkState = (e) => { e(false); };
                    val.isAdBlocking = (e) => { e(false); };
                    delete val._detectionInstance;
                } catch (err) { }
                return val;
            },
        });
    });
}
```

**Comment by jspenguin2017** [comment]
I still can't reproduce it, even after clearning cookies.

**Comment by okiehsch** [comment]
If I use a US-proxy I can't reproduce either, so it seems to be based on your location.

**Comment by jspenguin2017** [comment]
Which country can reproduce it?

**Comment by okiehsch** [comment]
If I use a dutch or german IP, I can reproduce consistently.

**Comment by adreporter** [comment]
Same in Poland.

**Comment by jspenguin2017** [comment]
Can you reproduce with TunnelBear?

**Comment by xtrars** [comment]
germany: yes
us: yes
hong kong: yes
i have delete cookies after each new tunnelbear ip

**Comment by jspenguin2017** [comment]
@okiehsch rolled out a patch, can you update your filters and see if it's fixed?

**Comment by adreporter** [comment]
@okiehsch It's working now, thank you.

**Comment by uBlock-user** [comment]
I can reproduce.

`gutefrage.net##script:inject(abort-on-property-read.js, _sp_)`

**Comment by jspenguin2017** [comment]
Solved by `uBlock filters`.
