### ISSUE TITLE
startclass.com

### ISSUE THREAD

**Issue by Elkrite** [jspenguin2017/uBlockProtector#369]
### Test link (required): 
http://colleges.startclass.com/l/1929/Harvard-University

### Screenshot of the web page (required): 

![3jlng9i](https://user-images.githubusercontent.com/15133609/27998499-5010b72a-64de-11e7-9eda-6c4c1864bfda.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

Part one: 

![9ey7awf](https://user-images.githubusercontent.com/15133609/27998500-5ecd2e06-64de-11e7-85a6-687a88e6395f.png)

Part two:

![ko5ry2b](https://user-images.githubusercontent.com/15133609/27998504-78c42260-64de-11e7-9d98-cbb9c1454ee2.png)

### Add everything else that you believe to be useful below (optional): 

I have been using this website recently for college searches. Very annoying ad blocker!

Activates when you scroll down the page a bit.

**Comment by jspenguin2017** [comment]
Fixed. Update extension to get the patch.

**Comment by Elkrite** [comment]
Thanks for the awesome work you do!
