### ISSUE TITLE
bild.de

### ISSUE THREAD

**Issue by HanSolo80** [jspenguin2017/uBlockProtector#371]
### Test link (required): 

http://www.bild.de/politik/inland/g20-gipfel/bild-english-g20-52507612.bild.html

### Screenshot of the web page (required): 
![Error](https://i.imgur.com/sWJU55Z.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![Part 1](https://i.imgur.com/M08hMHc.png)
![Part 2](https://i.imgur.com/TuWc1JF.pngg)

### Add everything else that you believe to be useful below (optional): 
Strangely, the adblock detection message is not always shown. It happens that sometimes the page is correctly loaded, but when opening another tab the message is shown. So when reproducing the issue you might have to try some times.
This is a console screenshot when the page is correctly loaded:

![Imgur](https://i.imgur.com/1F1gP6t.png)

**Comment by jspenguin2017** [comment]
The log shows `document.querySelector` is correctly blocked, but I can't seem to reproduce it. 
What is the reproduction rate?

**Comment by HanSolo80** [comment]
I tried again to reproduce it. Apparently, it only happens on first load in a new tab. When reentering the url in the same tab the page is shown correctly.
What about the first error message in the log: 
Uncaught Error: uBlock Origin detectors are not allowed on this device!

**Comment by lain566** [comment]
It's fixed by `uBlock filters` list

**Comment by jspenguin2017** [comment]
It works consistently for me, try clear site cache? 
That log shows whenever a site-specific solution is activated.

**Comment by jspenguin2017** [comment]
@lain566 No, they added a try-catch to bypass uBO's `abort-on-property-*`.

**Comment by jspenguin2017** [comment]
@HanSolo80 When it does not work, can you open the console and type `document.querySelector` follow by Enter and show what you see? It should be something like this if things worked correctly: 
```
(...args) => {
            //Call log
            if (false) {
                warn("window.document.querySelector is called with these arguments:");
                for (let i = 0; i < args.length; …
```

**Comment by lain566** [comment]
@jspenguin2017 You're right, i can reproduce with uBP extension disabled

**Comment by HanSolo80** [comment]
ok the document.querySelector call outputs the code you posted.
Clearing site cache didn't help.
I tried to enable upb and ublock protector in incognito mode and the error occurs there as well.

**Comment by jspenguin2017** [comment]
They might be serving geo based page source, can you dump the source? Press `Ctrl+U` to bring up page source.

**Comment by HanSolo80** [comment]
Source code of working page:
https://pastebin.com/bMWmi50D

Source code of page showing adblocker message:
https://pastebin.com/0BTQExCV

**Comment by jspenguin2017** [comment]
OK, the source is different... They must be testing some new tech...

**Comment by jspenguin2017** [comment]
Can you post the link of the broken page?

**Comment by HanSolo80** [comment]
http://www.bild.de/politik/inland/g20-gipfel/bild-english-g20-52507612.bild.html

**Comment by HanSolo80** [comment]
Ah, you mean the link where you get redirected to:
http://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html

**Comment by jspenguin2017** [comment]
Oh, it's a redirect?

**Comment by HanSolo80** [comment]
A JS redirect, yes.
Output of Redirect Path Extension:
`Status Code	URL	IP	Page Type	Redirect Type	Redirect URL	
200	http://www.bild.de/politik/inland/g20-gipfel/bild-english-g20-52507612.bild.html	23.211.8.64	client_redirect	javascript	http://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html
200	http://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html	23.211.8.64	normal	none	none`

**Comment by jspenguin2017** [comment]
What do you see when you type `de.bild.cmsKonfig.a.a` to the console?

**Comment by HanSolo80** [comment]
Status Code	URL	IP	Page Type	Redirect Type	Redirect URL	
200	http://www.bild.de/politik/inland/g20-gipfel/bild-english-g20-52507612.bild.html	23.211.8.64	client_redirect	javascript	http://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html
200	http://www.bild.de/wa/ll/bild-de/unangemeldet-42925516.bild.html	23.211.8.64	normal	none	none

**Comment by jspenguin2017** [comment]
It could be a race condition in uBO...

**Comment by HanSolo80** [comment]
(unknown) Uncaught ReferenceError: sn3056t
    at Object.abort [as a] (<anonymous>:5:9)
    at <anonymous>:1:20

**Comment by jspenguin2017** [comment]
It only happen when the page is cached, right? Then that's a race condition...

**Comment by HanSolo80** [comment]
Yeah, I disabled cache in dev tools and it didn't occur anymore. I tried several times but couldn't reproduce the error anymore.

**Comment by jspenguin2017** [comment]
The rule is implemented by Extension to eliminate race condition. Update Extension to 10.70 and see if it fixes it.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by HanSolo80** [comment]
@jspenguin2017 your update apparently fixed the issue. I don't get the message anymore. Thank you.
