### ISSUE TITLE
maxisciences.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#372]
### Test link (required): 
http://www.maxisciences.com/ville/la-chine-est-en-train-de-construire-la-premiere-ville-foret-anti-pollution-au-monde_art39667.html
### Screenshot of the web page (required): 
![forest_city__la_chine_est_en_train_de_construire__2017-07-10_23-08-23](https://user-images.githubusercontent.com/27441315/28040076-d2c221fe-65c4-11e7-8c01-333bcb800332.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww maxisciences comvill_2017-07-10_23-08-54](https://user-images.githubusercontent.com/27441315/28040082-dc30d276-65c4-11e7-8f6f-4e59fa2a4a39.png)

**Comment by jspenguin2017** [comment]
Fixed

**Comment by uBlock-user** [comment]
This one is from the gentside group. Same anti adblock script.
