### ISSUE TITLE
ohmymag.com.br

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#373]
### Test link (required): 
http://www.ohmymag.com.br/cubo/cubo-anti-stress-o-novo-aliado-da-dieta_art4140.html
### Screenshot of the web page (required): 
![cubo_anti_stress_o_novo_aliado_da_dieta _-_google_2017-07-10_23-23-05](https://user-images.githubusercontent.com/27441315/28040741-09507be2-65c7-11e7-88dd-330590a4b2ab.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww ohmymag com brcuboc_2017-07-10_23-23-22](https://user-images.githubusercontent.com/27441315/28040747-12929186-65c7-11e7-817d-38f67b6a31b5.png)

**Comment by jspenguin2017** [comment]
How many domains do they have...

**Comment by lain566** [comment]
I only found these

**Comment by uBlock-user** [comment]
You will have to do a crude search if you want to find more.

**Comment by lain566** [comment]
@jspenguin2017 Video player is not working, video doesn't load.

![cubo_anti_stress_o_novo_aliado_da_dieta _-_google_2017-07-15_22-55-28](https://user-images.githubusercontent.com/27441315/28242620-be938c28-69b0-11e7-871f-08d153ac6eda.png)

**Comment by jspenguin2017** [comment]
Fixed.

**Comment by lain566** [comment]
@jspenguin2017 The player is broken again, only `maxisciences.com` works for me https://github.com/jspenguin2017/uBlockProtector/issues/372 Can you fix it?

**Comment by jspenguin2017** [comment]
Fixed.

**Comment by lain566** [comment]
@jspenguin2017 thanks
