### ISSUE TITLE
hayan.tv

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#375]
### Test link (required): 
http://hayan.tv/a/2017/boruto/
### Screenshot of the web page (required): 
![_-_google_chrome_2017-07-10_23-54-07](https://user-images.githubusercontent.com/27441315/28041863-37367c92-65cb-11e7-9a94-757749a9e54e.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httphayan tva2017boruto_2017-07-10_23-54-19](https://user-images.githubusercontent.com/27441315/28041873-3fb6a1a8-65cb-11e7-9c83-6f394077851c.png)

**Comment by jspenguin2017** [comment]
`||clickmon.co.kr^$subdocument,redirect=noopframe,important,domain=hayan.tv`
Has some side effect, the `iframe` can't be hidden...

**Comment by lain566** [comment]
and this 
https://github.com/reek/anti-adblock-killer/issues/3153

**Comment by jspenguin2017** [comment]
Yep, that works...

**Comment by uBlock-user** [comment]
Can't reproduce.
