### ISSUE TITLE
forums.digitalpoint.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#379]
### Add everything else that you believe to be useful below (optional): 
Like the website said, some features does not work, (eg: Post Reply)

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by Dibbyo456** [comment]
@ublock-user Can't reproduce what? The Adblock detection banner? Or the Post reply problem while uBlock enabled?

**Comment by uBlock-user** [comment]
anti adblock banner

**Comment by ghajini** [comment]
`forums.digitalpoint.com##.importantMessage`
