### ISSUE TITLE
nbcsports.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#380]
### Test link (required): 
http://www.nbcsports.com/live
http://www.nbcsports.com/video/paul-millsap-and-jrue-holiday-part-surging-nba-contracts

### Screenshot of the web page (required): 
![live__nbc_sports_-_google_chrome_2017-07-11_13-53-55](https://user-images.githubusercontent.com/27441315/28067203-8824a064-6640-11e7-8c23-e4ec493c3c62.png)
![paul_millsap_and_jrue_holiday_part_of_surging_nba__2017-07-11_14-21-41](https://user-images.githubusercontent.com/27441315/28068101-50427424-6644-11e7-9da5-78688063486d.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww nbcsports comlive_2017-07-11_13-54-13](https://user-images.githubusercontent.com/27441315/28067211-8e960bb8-6640-11e7-82ac-83d1de645ed8.png)
![developer_tools_-_httpwww nbcsports comvideop_2017-07-11_14-27-06](https://user-images.githubusercontent.com/27441315/28068281-1cc05ce6-6645-11e7-8a5e-f3c523f639e2.png)

**Comment by uBlock-user** [comment]
nbcsports.com##script:inject(abort-on-property-write.js, cts_canShowAds)

or

nbcsports.com##script:inject(abort-on-property-read.js, cts_canShowAds)

Does either of them work ?

**Comment by uBlock-user** [comment]
I can hide the overlay with `vplayer.nbcsports.com###sherlock` but can't say if it doesn't play or it requires Flash.

**Comment by uBlock-user** [comment]
anti adblock message appears in the iframe of the player.

true URL - http://vplayer.nbcsports.com/p/BxmELC/nbcsports/select/media/cp__2Xrm9Xp7?autoPlay=true&parentUrl=http://www.nbcsports.com/video/paul-millsap-and-jrue-holiday-part-surging-nba-contracts#playerurl=http%3A//www.nbcsports.com/live

**Comment by uBlock-user** [comment]
Traces of anit adblock message found here - http://hdliveextra-a.akamaihd.net/HD/scripts/V4.17/nbcsports-main-v4-17-0a.min.js

**Comment by uBlock-user** [comment]
Just as I thought the variable is dummy and not checked bu rather the status of the /ads.js script loaded or not.

This works `||hdliveextra-a.akamaihd.net/*/ads.js$script,redirect=noopjs`
