### ISSUE TITLE
macupload.net

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#386]
macupload.net

### Test link (required): 
https://macupload.net/3ws

### Screenshot of the web page (required): 
http://i.imgur.com/geN7fDt.png

-->

### Screenshot of the console  (required): 
http://i.imgur.com/xguj445.png

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
Try `@@||macupload.net^$elemhide`

**Comment by jspenguin2017** [comment]
timeout enforced on server side, can't reproduce anti-adblock.

**Comment by Dibbyo456** [comment]
Can't reproduce either.

**Comment by jspenguin2017** [comment]
Still works. Closing.
