### ISSUE TITLE
blog.giallozafferano.it

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#388]
http://blog.giallozafferano.it/langolodelleprelibatezze/torta-al-limone-dentro-al-calderone/
<img width="364" alt="cattura" src="https://user-images.githubusercontent.com/18214146/28120413-46b84116-6718-11e7-8f84-4b3c595a5e6a.PNG">
<img width="960" alt="cattura1" src="https://user-images.githubusercontent.com/18214146/28120420-4c71db62-6718-11e7-9739-069559fabf82.PNG">
The message appears in the lower right corner after about 10 seconds.

**Comment by uBlock-user** [comment]
Can't reproduce.
