### ISSUE TITLE
vvvvid.it

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#390]
https://www.vvvvid.it/#!show/637/my-hero-academia-seconda-stagione/700/513960/proprio-cosi-ochaco

Click this, it redirect to https://www.vvvvid.it/adblock.html
![image](https://user-images.githubusercontent.com/7283682/28127591-5a59a81e-66ea-11e7-8857-b15cb7e69933.png)

https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/112
https://github.com/Robotex/KAADIVVVV/issues/16

KAADIVVVV was working yesterday, today they seem to have changed the property to `cab4`, but the old solution with the property name changed does not work. 

Also, Italy Geo Lock, TunnelBear works.

**Comment by uBlock-user** [comment]
ModHeader won't work on this it seems.

**Comment by jspenguin2017** [comment]
TunnelBear works though.

**Comment by lain566** [comment]
It's broken.

**Comment by jspenguin2017** [comment]
OK, I'll check tonight.
