### ISSUE TITLE
clik.pw

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#392]
http://clik.pw/emWZD
<img width="295" alt="1" src="https://user-images.githubusercontent.com/18214146/28131561-8c74c838-673a-11e7-80ed-5adc29a5ac53.PNG">
<img width="581" alt="cattura232" src="https://user-images.githubusercontent.com/18214146/28131568-91ec2a9a-673a-11e7-80f2-d8112863859c.PNG">

**Comment by uBlock-user** [comment]
http://clik.pw/js/ads.js

CSS based bait

**Comment by uBlock-user** [comment]
`clik.pw##script:inject(setTimeout-defuser.js, checkAdblockUser)`

**Comment by uBlock-user** [comment]
anti adblock script - http://clik.pw/cloud_theme/build/js/script.min.js?ver=4.1.0

**Comment by uBlock-user** [comment]
Majority of URL shorteners reported by @adreporter here are apparent clones of each other. Similar website layout, same notice, same anti adblock script, so one solution will work for them all.

**Comment by adreporter** [comment]
@jspenguin2017 
http://clik.pw/emWZD
After solving the captcha, you have to click 3 times on "Click here to continue", otherwise it won't work.
The same problem occurs on http://linksh.top/TRrHU
Could you please fix it?

**Comment by jspenguin2017** [comment]
As long as it doesn't popup I don't see why it matters.

**Comment by adreporter** [comment]
Ok

**Comment by adreporter** [comment]
@jspenguin2017 

> As long as it doesn't popup

I know the priority is to report websites with anti-adblock messages, but if I find some sites with popups, do you want me to report them?

**Comment by jspenguin2017** [comment]
You should report to EasyList first.

**Comment by adreporter** [comment]
Ok, thanks

**Comment by adreporter** [comment]
@jspenguin2017 
http://clik.pw/3dT7y
After solving the captcha, the "GET LINK" doesn't show up.

**Comment by jspenguin2017** [comment]
Fixed.
