### ISSUE TITLE
der-postillon.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#393]
### Test link (required): 
http://www.der-postillon.com/

### Screenshot of the web page (required): 
![der_postillon_-_google_chrome_2017-07-12_13-44-57](https://user-images.githubusercontent.com/27441315/28117107-62febd70-670c-11e7-80e2-ad9f4aa30d19.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww der-postillon com_2017-07-12_14-19-00](https://user-images.githubusercontent.com/27441315/28117287-171f409a-670d-11e7-8f9a-c1c20d954ccd.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
