### ISSUE TITLE
rspk.paksociety.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#395]
https://rspk.paksociety.com/kids-corner/kids-stories/rehan-khurshid/hassan-series/
<img width="545" alt="ffff" src="https://user-images.githubusercontent.com/18214146/28181334-89cbfdb2-6808-11e7-8e52-671a58f56f6d.PNG">
<img width="960" alt="ewrwew" src="https://user-images.githubusercontent.com/18214146/28181340-8ccd43cc-6808-11e7-8075-425844192994.PNG">

**Comment by uBlock-user** [comment]
Element based on detection.

`@@||paksociety.com^$elemhide`

**Comment by jspenguin2017** [comment]
Too many placeholders showing with that.

**Comment by lain566** [comment]
@jspenguin2017 Disappearing scroll bar. I can't scroll down.

**Comment by jspenguin2017** [comment]
Works for me: 
![image](https://user-images.githubusercontent.com/7283682/28347382-f4dd5094-6bf3-11e7-8b6f-006941418a52.png)

**Comment by lain566** [comment]
@jspenguin2017 It only works in the first visit, in your screenshot shows two vertical scrollbars.

**Comment by jspenguin2017** [comment]
It shows two scroll bar on a browser that has no extensions too: 
![image](https://user-images.githubusercontent.com/7283682/28370401-714591ba-6c57-11e7-8177-e31bb3bfc125.png)

I see that it only work on first visit, I'll fix it.
