### ISSUE TITLE
wiadomosci.wp.pl

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#397]
@lain566 
https://github.com/jspenguin2017/uBlockProtector/issues/384#issuecomment-315177534

Test link: 
https://wiadomosci.wp.pl/tvp-info-przekracza-kolejne-granice-zobaczcie-jak-nazwali-kontrmanifestantow-6142973419370113a

**Comment by jspenguin2017** [comment]
Possible workaround (by @lain566 ): 
```
||pagead2.googlesyndication.com/pagead/js/adsbygoogle.js$script,redirect=noopjs,domain=wiadomosci.wp.pl
||static.criteo.net/js/ld/publishertag.js$script,redirect=noopjs,domain=wiadomosci.wp.pl

@@||wp.hit.gemius.pl/gplayer.js$script,domain=wiadomosci.wp.pl
@@||wp.hit.gemius.pl/gdejs/xgde.js$script,domain=wiadomosci.wp.pl
```

**Comment by lain566** [comment]
Try this rule only, player does not disappear

`||wiadomosci.wp.pl/*$xmlhttprequest`

**Comment by jspenguin2017** [comment]
Yea but it doesn't play neither...

**Comment by jspenguin2017** [comment]
The whole `wp.pl` thing is exhausting, I'll just wait for someone to find a solution and add it.

**Comment by adreporter** [comment]
Try `wiadomosci.wp.pl#@#script:inject(abort-on-property-write.js, habahaba)` Thanks to @hawkeye116477

**Comment by jspenguin2017** [comment]
Doesn't seem to work on this one though: https://wiadomosci.wp.pl/archiwalna-wypowiedz-blaszczaka-kiedys-skrytykowal-po-a-teraz-pis-robi-to-samo-6142419287754369a

**Comment by adreporter** [comment]
Yes, you are right. Unfortunately I don't have any clue.

**Comment by adreporter** [comment]
@jspenguin2017 I noticed it works if you delete cookies.

**Comment by adreporter** [comment]
Hmmm weird. It works if I delete the site cookies. But after some page refreshing it stops to work.

**Comment by jspenguin2017** [comment]
I pushed out an update, since my XHR goes through the background page, it is not interfered by uBO. Add `||wiadomosci.wp.pl^$xmlhttprequest` and it will work for the first video, but the rest of the page won't load.

**Comment by jspenguin2017** [comment]
We just need to pin down which XHR is responsible for hiding the video.

**Comment by jspenguin2017** [comment]
I am able to grab the removed node, but I can't put it back in... Its parent has randomized class name...

**Comment by jspenguin2017** [comment]
I added an anti-collapsing observer, can someone update Extension and test? 
Also what about other domains?

**Comment by adreporter** [comment]
https://parenting.pl/chlopcy-bardziej-poszkodowani-biernym-paleniem
Could you please fix the video?
It's wp related site, about to test more

**Comment by adreporter** [comment]
OK, seems like all the wp domains are working correctly.

**Comment by adreporter** [comment]
Are you able to play the videos in these domains?
https://parenting.pl/chlopcy-bardziej-poszkodowani-biernym-paleniem
https://portal.abczdrowie.pl/czy-film-az-do-kosci-gloryfikuje-anoreksje

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/28231654-da07c800-68a9-11e7-8d02-2c426744d7e7.png)
I think it's something else...

**Comment by adreporter** [comment]
"Sorry, the video is unavailable in your country"

**Comment by jspenguin2017** [comment]
Well...

**Comment by hawkeye116477** [comment]
@jspenguin2017 Updated extension and confirm, now all movies on wiadomosci.wp.pl works without these 2 rules on Vivaldi.

**Comment by adreporter** [comment]
@jspenguin2017 
Check here: https://portal.abczdrowie.pl/4-sposoby-na-oczyszczenie-tetnic-ze-zlogow-tluszczowych/2
It should work for you as it is working for me.
Unfortunately it doesn't work on https://portal.abczdrowie.pl/czy-film-az-do-kosci-gloryfikuje-anoreksje

**Comment by jspenguin2017** [comment]
Looks like the play button is covered...

**Comment by jspenguin2017** [comment]
This works... https://portal.abczdrowie.pl/pij-go-codziennie-rano-a-schudniesz-kilkanascie-kilogramow-w-miesiac

**Comment by adreporter** [comment]
Oh no, the player disappears again...

**Comment by jspenguin2017** [comment]
where?

**Comment by adreporter** [comment]
On the link above

**Comment by adreporter** [comment]
https://portal.abczdrowie.pl/pij-go-codziennie-rano-a-schudniesz-kilkanascie-kilogramow-w-miesiac

**Comment by jspenguin2017** [comment]
The anti-collapsing only applies to a single domain for now.

**Comment by adreporter** [comment]
Now all videos on `portal.abczdrowie.pl` aren't working anymore even the video that worked for me 10 minutes ago...

**Comment by jspenguin2017** [comment]
This fixes controls being blocked.

**Comment by jspenguin2017** [comment]
I can't reproduce videos disappearing on `portal.abczdrowie.pl` though, maybe they just changed something...

**Comment by adreporter** [comment]
Who knows, maybe it's happening for polish people only.
@hawkeye116477 just wrote to me I'm not the only one.

**Comment by adreporter** [comment]
@jspenguin2017 Sorry, my bad. I added custom filters to uBlock, and now the player shows up.
The problem is:
<img width="481" alt="tertert" src="https://user-images.githubusercontent.com/18214146/28232715-8e120c96-68f2-11e7-8a78-d6bc20c25a04.PNG">

**Comment by adreporter** [comment]
@jspenguin2017 Thank you so much as always. Updating to 10.100 solves the problem.

**Comment by adreporter** [comment]
@jspenguin2017 
https://wiadomosci.wp.pl/tvp-info-przekracza-kolejne-granice-zobaczcie-jak-nazwali-kontrmanifestantow-6142973419370113a
Please delete cookies and cache and refresh the page. Press play, then go to fullscreen. Is everything OK for you?

**Comment by HateAds** [comment]
@jspenguin2017  @adreporter Same problem as above.
https://parenting.pl/chlopcy-bardziej-poszkodowani-biernym-paleniem
![wp](https://user-images.githubusercontent.com/29756590/28233458-53bca7ea-68f7-11e7-9850-63ff28fdbd0f.png)

**Comment by adreporter** [comment]
@jspenguin2017 
https://wiadomosci.wp.pl/tvp-info-przekracza-kolejne-granice-zobaczcie-jak-nazwali-kontrmanifestantow-6142973419370113a
Sometimes after playing and exiting the video from full screen, I see the same videos under "the original one":
<img width="111" alt="ertlol" src="https://user-images.githubusercontent.com/18214146/28233597-1ed8564a-68f8-11e7-9183-a7f3b5f50ecc.PNG">

**Comment by adreporter** [comment]
@HateAds Delete uBlock custom filters regarding wp, portal.abczdrowie.pl and parenting.pl
Update uBlock Protector Extension to 10.100
Delete cookies and cache and refresh your page.

**Comment by HateAds** [comment]
@adreporter zrobiłem wszystko tak jak napisałeś, i nadal nie działa. (później usune wpis bo niechce tu zaśmiecać)

**Comment by adreporter** [comment]
hmm

**Comment by adreporter** [comment]
tez pozniej usune

**Comment by adreporter** [comment]
ale szczerze nie wiem, bo u mnie dziala

**Comment by HateAds** [comment]
Wszystko z wp mi działa poza pareting

**Comment by adreporter** [comment]
@HateAds Try ctrl+r and then ctrl+F5

**Comment by HateAds** [comment]
Nadal nie działa, szkoda że tu prywatnie nie można wiadomości pisać.

**Comment by adreporter** [comment]
Sory ale nie wiem. U mnie też są problemy czasami z https://wiadomosci.wp.pl/tvp-info-przekracza-kolejne-granice-zobaczcie-jak-nazwali-kontrmanifestantow-6142973419370113a

**Comment by HateAds** [comment]
Dziwne, ja nie mam czegoś takiego jak Ty. robiłem kilka full screenów i nigdy nie pojawiło mi się tyle filmów o tym samym co Tobie wyżej.

**Comment by adreporter** [comment]
No, sam nie wiem co jest grane. Na szczęście, że to rzadko się zdarza.

**Comment by adreporter** [comment]
Ale nie powinno tak robić

**Comment by adreporter** [comment]
Sory ale na prawde nie mam pomyslow co do parenting.pl

**Comment by HateAds** [comment]
z wp to same problemy jutro napisze na polskich filtrach bo jest coś dziwnego co zauważyłem z główną stroną jak polskie filtry są włączone.

**Comment by adreporter** [comment]
Tez tak mialem jak ty, ale wystarczylo ze usunalem ciasteczka, cache i odswiezylem strone i wszystko sie naprawilo

**Comment by adreporter** [comment]
o parenting pl pisze

**Comment by HateAds** [comment]
dzięki że odpisujesz przynajmniej nie jestem sam hehe

**Comment by adreporter** [comment]
dobra, to co kasujemy wiadomosci

**Comment by adreporter** [comment]
kasujemy?

**Comment by HateAds** [comment]
tak

**Comment by adreporter** [comment]
@jspenguin2017 Sorry for spamming, we're about to delete our messages

**Comment by adreporter** [comment]
@jspenguin2017 It's OK
<img width="502" alt="dfdeff" src="https://user-images.githubusercontent.com/18214146/28234190-529fce04-68fd-11e7-90d7-5ebc8cd26a36.PNG">

**Comment by HateAds** [comment]
It's working fine now.  thanks @adreporter 
![works](https://user-images.githubusercontent.com/29756590/28234580-937f855a-6901-11e7-8b90-140fede24994.png)

**Comment by jspenguin2017** [comment]
Alright. Closing.

**Comment by HateAds** [comment]
@jspenguin2017 Once again wp has changed something and the player stopped working.
![image](https://user-images.githubusercontent.com/29756590/28937783-4231387a-788c-11e7-898a-190fe8206e95.png)

**Comment by jspenguin2017** [comment]
Fixed.

**Comment by hawkeye116477** [comment]
@jspenguin2017 Not everything fixed. With uBlock Origin and uBlock Protector I can't switch quality and can't see "Others have also seen:".

Without uBlock Origin and uBlock Protector:
![screenshot_20170804_125757](https://user-images.githubusercontent.com/19818572/28966162-f99ddb34-7914-11e7-8e91-4b3f9976a4ca.png)

With uBlock Origin and uBlock Protector:
![screenshot_20170804_125828](https://user-images.githubusercontent.com/19818572/28966186-1aa8749c-7915-11e7-886e-48ba5f9f925b.png)

**Comment by jspenguin2017** [comment]
I don't have a solution that doesn't involve replacing their player, I'll mark it as non-perfect solution.

**Comment by hawkeye116477** [comment]
@jspenguin2017 Ok, I found another problem, WP has two version of site on server.
![screenshot_20170804_154132](https://user-images.githubusercontent.com/19818572/28972098-adb5b150-792e-11e7-9f3e-67ce7890d913.png)
![screenshot_20170804_160629](https://user-images.githubusercontent.com/19818572/28972180-f022e7c4-792e-11e7-861c-38841d9d74a1.png)
When on top is white color, then player don't work with uBlock Protector. Versions changes when I clear cookies.

**Comment by hawkeye116477** [comment]
https://parenting.pl/jest-upal-wiec-pozwalasz-dziecku-pluskac-sie-w-miejskiej-fontannie-to-niebezpieczne#

**Comment by jspenguin2017** [comment]
I don't have a perfect solution. The `figcaption` is patched.

**Comment by hawkeye116477** [comment]
@jspenguin2017 Thanks, now it works perfect.
![screenshot_20170804_162148](https://user-images.githubusercontent.com/19818572/28972740-09ba8f28-7931-11e7-873d-f0f8dc36934b.png)

**Comment by hawkeye116477** [comment]
@jspenguin2017 Probably not so perfect, though. Another problem, from 0:03 to 0:05, the video has lags. Can you do something about it?

**Comment by jspenguin2017** [comment]
That has to do with Chromium's player, it doesn't know how to buffer.

**Comment by HateAds** [comment]
http://autokult.pl/30015,pierwszy-bugatti-chiron-dla-klienta-dostarczony
I spotted a bug, here should be a video from youtube.
![image](https://user-images.githubusercontent.com/29756590/29493956-be524ce8-85a0-11e7-9794-bc1c1a98e557.png)
![image](https://user-images.githubusercontent.com/29756590/29493962-d33b5956-85a0-11e7-85c7-3a0ecef0c713.png)
![image](https://user-images.githubusercontent.com/29756590/29493977-0f4755b2-85a1-11e7-942a-42c02f3a2e94.png)

**Comment by jspenguin2017** [comment]
Can't reproduce: 
![image](https://user-images.githubusercontent.com/7283682/29495469-3deddd38-857d-11e7-9c42-fccb7cea00c9.png)

**Comment by hawkeye116477** [comment]
@jspenguin2017 Refresh page and video will be replaced with wp video instead of youtube video.

**Comment by jspenguin2017** [comment]
Refreshed 5 times, still can't reproduce.

**Comment by hawkeye116477** [comment]
@jspenguin2017 Forgot something to write, video will be replaced when you scroll down page.

**Comment by hawkeye116477** [comment]
![screenshot_20170820_161041](https://user-images.githubusercontent.com/19818572/29495566-2e425a2c-85c2-11e7-927e-64184d46c69d.png)

Should be playable video here, but it jumps to place where should be youtube video.

**Comment by hawkeye116477** [comment]
@jspenguin2017 Thanks, now it works correct :smile:.
