### ISSUE TITLE
angrybirdsnest.com

### ISSUE THREAD

**Issue by ghajini** [jspenguin2017/uBlockProtector#401]
video player i think get replaced by antiadblock message
### Test link (required): 
http://www.angrybirdsnest.com/angry-birds-golden-egg-1-walkthrough/
### Screenshot of the web page (required): 
http://prntscr.com/fw4dcn

### Screenshot of the console (press `F12` to bring up the console) (required): 
http://prntscr.com/fw4dju

**Comment by lain566** [comment]
@jspenguin2017 It's broken or it's just me?

**Comment by jspenguin2017** [comment]
I thought I tested it... Did they rename `adBlock` to `adblock`?

**Comment by jspenguin2017** [comment]
Ops, that was dumb...
