### ISSUE TITLE
youwatch.to

### ISSUE THREAD

**Issue by xlollomanx** [jspenguin2017/uBlockProtector#402]
**Test link (required):** 

http://youwatch.to/8t9mzzuhy77x

**Screenshot of the web page (required)**:

 https://prnt.sc/fwgbb7

**Screenshot of the console (press `F12` to bring up the console) (required):** 

https://prnt.sc/fwg5bc

**Add everything else that you believe to be useful below (optional):**

Youwatch.to is a streaming site. Everytime you try to open a youwatch.to link you'll get redirected. If you take the test link ( http://youwatch.to/8t9mzzuhy77x ) you'll get redirected to http://he2eini7ka.com/8t9mzzuhy77x

**Comment by jspenguin2017** [comment]
Redirects to `http://he2eini7ka.com/8t9mzzuhy77x`. Can reproduce.

**Comment by xlollomanx** [comment]
@jspenguin2017 with NSFW you mean "Not Safe for Work"? I use this websites sometimes but I never seen something dangerous.

**Comment by jspenguin2017** [comment]
Not sure if this works...

**Comment by uBlock-user** [comment]
one big overlay needs to be be removed

```
he2eini7ka.com###OnPlayerClose
he2eini7ka.com###player_imj
```

**Comment by uBlock-user** [comment]
also the test url redirects to http://he2eini7ka.com/8t9mzzuhy77x

**Comment by xlollomanx** [comment]
@jspenguin2017 now anti-adblock it's gone and the player appeared but it loading forever until you get error and it stuck. Otherwise I noticed that I'm still redirected to the other sites (http://he2eini7ka.com/).

**Comment by ghajini** [comment]
website broken...i get `error loading media-file could not be played` even with extensions off

**Comment by xlollomanx** [comment]
@ghajini maybe it's true...I tried even with other browser and without any addon or script but I can't still play any videos. Maybe the site itself have some problems.

**Comment by jspenguin2017** [comment]
@uBlock-user Can't use cosmetic filter, the site checks for it.

**Comment by uBlock-user** [comment]
I don't see any issue with using it, the player is broken whether you use it or not.

**Comment by jspenguin2017** [comment]
It doesn't work for this video, what about others? I see the code that checks for if the button is clicked, I won't use that cosmetic filter.

**Comment by uBlock-user** [comment]
As long as that trolling overlay is removed, that's all it matters.

**Comment by uBlock-user** [comment]
Also it's an iframe of the embedded player so the true test link is http://he2eini7ka.com/embed-8t9mzzuhy77x-_-VmZWeTBYam5aV0Irc2xZandaNTRtZXZpUmFvWXJRVHJFTDhrUUQrckFEQVUvdz09Cg==.html?673398499#

**Comment by jspenguin2017** [comment]
I usually use the full webpage as some frames refuse to run as top frame.

**Comment by jspenguin2017** [comment]
Looks good, closing.
