### ISSUE TITLE
lpg-forum.pl

### ISSUE THREAD

**Issue by hawkeye116477** [jspenguin2017/uBlockProtector#403]
### Test link (required): 
www.lpg-forum.pl

### Screenshot of the web page (required): 
![screenshot_20170717_143135](https://user-images.githubusercontent.com/19818572/28268474-b57c4720-6afe-11e7-8488-4c4963b91af1.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![screenshot_20170717_143310](https://user-images.githubusercontent.com/19818572/28268489-bed80d2c-6afe-11e7-8f7c-dda998166d3d.png)

### Add everything else that you believe to be useful below (optional): 
I added that rule to uBlock Origin: `||lpg-forum.pl/adtaily.js$script` and now message from screenshot appears: "Do you block ads? We block this page".

**Comment by jspenguin2017** [comment]
What is blocking `adtaily.js`?

**Comment by hawkeye116477** [comment]
@jspenguin2017 Should block adverts.

**Comment by jspenguin2017** [comment]
I don't see anything blocking that file, if it is a polish filter then ask its maintainer to add an exception.

**Comment by hawkeye116477** [comment]
@jspenguin2017 I added this by myself to try block ads. So it's not possible to do something with anti adblock on this site?

**Comment by jspenguin2017** [comment]
It looks like a bait file, its content is `document.write('<div id="adt">adtaily</div>');`

**Comment by hawkeye116477** [comment]
Ok, I found a workaround. Just blocked these ads with cosmetic filters and now anti-adblock doesn't appear.

**Comment by hawkeye116477** [comment]
@jspenguin2017 Ok, so then I apologize for the trouble. Just blocked these ads with cosmetic filters, removed this rule and now anti-adblock doesn't appear.

**Comment by uBlock-user** [comment]
I can reproduce. Blocking http://lpg-forum.pl/advert.js will cause that to happen.

**Comment by uBlock-user** [comment]
```javascript
$(document).ready(function() { if ((document.getElementById("abp_tester") != undefined) && (document.getElementById("adt") != undefined))
{
}
else
{
	location.href='/stop.html';
}
});
```

**Comment by uBlock-user** [comment]
`lpg-forum.pl##script:inject(abort-on-property-read.js, $.ready)`
