### ISSUE TITLE
[Off-topic] spaste.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#404]
We all know, spaste.com is a well known short linking website. They use 2 type of captcha - "Solve Media" & Their own captcha.

**I believe there is way to solve their own captcha automatically**. This is how their own [captcha looks](http://prntscr.com/fx0oes) & their answer is on [their sources](http://prntscr.com/fx0omd). Here is source dump if you wants to [take a look](https://pastebin.com/nJr3dirp).
I can solve their own captcha automatically in PHP, but I would like to see the feature in uBP.
What do you think? 

Tip: Use FireFox for debugging.

**Comment by uBlock-user** [comment]
What about Solve Media ? can that be solved like this ?

**Comment by Dibbyo456** [comment]
@uBlock-user No. Solve Media can be solved by different trick. By creating a database with images with MD5 hashes of the images, then we can cross check each query. It can be easily made by PHP. I thought of creating it, but it would be pointless, since I mostly need it for browser, so back end language like PHP isn't gonna cut it.

**Comment by jspenguin2017** [comment]
It's not really answer, it's the word that shows in the middle there, the images are below, although the name of the image kind of gives it out but it's still not that predictable. 
Either way, I'm not going to implement CAPTCHA auto solving here.

**Comment by Dibbyo456** [comment]
@jspenguin2017 Okay. I will try to implement this on PHP.
But problem is spaste send their captcha randomly which makes it pretty hard to test & debug.

**Comment by jspenguin2017** [comment]
That's the point of Captcha...

**Comment by jspenguin2017** [comment]
If you want to make something that actually works, it should be an Userscript or extension. And it needs to work most time, not just that one time.

**Comment by Dibbyo456** [comment]
@jspenguin2017 also, you should take another look. I'm pretty sure it's predictable. The images are in the order. We need match the answers with questions order. My English is poor else I could have give you proper logic. 

Also, triggering the logic only when the specific captcha found wouldn't hurt

**Comment by jspenguin2017** [comment]
Yea but how do I find the image that matches the word? I can look at the image address and it sometimes would work, but I don't want to get into this.

**Comment by Dibbyo456** [comment]
If you don't want to get into this, that's different matter. Least you can do verify the logic. 
Also, is there could be a way to get their own captcha everytime instead of Solve Media captcha?

**Comment by jspenguin2017** [comment]
It's up to you to investigate, that is outside the scope of my project.
