### ISSUE TITLE
slickdeals.net

### ISSUE THREAD

**Issue by kekwowse01** [jspenguin2017/uBlockProtector#405]
### Screenshot of the web page (required): 

![2017-07-18_010231](https://user-images.githubusercontent.com/20890266/28303060-ad3eb14e-6b56-11e7-9b8e-1509965004b8.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![2017-07-18_010749](https://user-images.githubusercontent.com/20890266/28302938-f94e9618-6b55-11e7-96d2-890cfa2fa4f3.png)

### Add everything else that you believe to be useful below (optional): 
System:
- uBlock Origin 1.13.2
- uBlock Protector Extension 10.122
- Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- Windows 10 Home (64-bit) Version 1703 OS Build 15063.483

The following is what the site looks like when the uBlock Protector Extension is disabled. The font is smaller and without the text across the page in the middle. 

![2017-07-18_010438](https://user-images.githubusercontent.com/20890266/28303072-bb5a64e4-6b56-11e7-8b3c-2aeef115e836.png)

**Comment by uBlock-user** [comment]
Can't reproduce.

The page on my end looks different and not like the one you're seeing even after disabling uBP.

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/5fee570711c97326ef101f9fd280c261.png)

**Comment by kekwowse01** [comment]
Maybe what I see is the page after login. What info can I provide to further the investigation? BTW, thank you much for the prompt response.

**Comment by kekwowse01** [comment]
Should I follow the "Reporting something secret" instructions in the "contribution guideline"?

**Comment by uBlock-user** [comment]
Provide a usable account for further checks.

**Comment by uBlock-user** [comment]
This is not an anti adblock issue, so reporting here is fine.

**Comment by kekwowse01** [comment]
Okay. Got the account setup. Is there a way to send in the credential in private?

**Comment by jspenguin2017** [comment]
Open a confidential issue in my restricted issues tracker. https://gitlab.com/xuhaiyang1234/uBlockProtectorSecretIssues/issues

**Comment by jspenguin2017** [comment]
ops, that was a wrong reference...

**Comment by jspenguin2017** [comment]
The webpage looks very different for me... 
![image](https://user-images.githubusercontent.com/7283682/28322347-1d19f71c-6b93-11e7-8f05-d83e3d87798e.png)

**Comment by kekwowse01** [comment]
Got a case opened at gitlab. Thank you again for all the help :)

**Comment by jspenguin2017** [comment]
It is caused by uBO-Extra, @gorhill

**Comment by jspenguin2017** [comment]
I need a way to instruct uBO-Extra to abort, current hack is kind of ugly...

**Comment by jspenguin2017** [comment]
Travis plz...

**Comment by jspenguin2017** [comment]
Instart Logic Buster is causing problem on this site, it doesn't seem to be using Instart Logic anymore.
