### ISSUE TITLE
cellmapper.net

### ISSUE THREAD

**Issue by 3v1n0** [jspenguin2017/uBlockProtector#406]
### Test link (required):

https://www.cellmapper.net/map?MCC=222&MNC=10&type=LTE&latitude=42.71828820177733&longitude=12.110477089881215&zoom=14&showTowers=true&clusterEnabled=true&tilesEnabled=true&heatMapEnabled=false&showOrphans=false&showNoFrequencyOnly=false&showFrequencyOnly=false&showBandwidthOnly=false&DateFilterType=FirstSeen&showHex=false&bands=0,3,20&showVerifiedOnly=false&showUnverifiedOnly=false&showLTECAOnly=false&showBand=0

### Screenshot of the web page (required): 
![immagine](https://user-images.githubusercontent.com/345675/28311514-2f81ebd6-6bb0-11e7-85e0-20ea48371bbb.png)

**Comment by uBlock-user** [comment]
`@@||cellmapper.net^$elemhide`

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/commit/ceefe6ca6ae0cd18d4fe0b8d193d24a75eb7e082

**Comment by jspenguin2017** [comment]
Looks good. Closing.
