### ISSUE TITLE
tlz.de

### ISSUE THREAD

**Issue by tinloaf** [jspenguin2017/uBlockProtector#408]
### Screenshot of the web page (required): 
![site](https://user-images.githubusercontent.com/442687/28327796-c35c11a4-6be4-11e7-98b1-c7dd93a72612.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![console](https://user-images.githubusercontent.com/442687/28327813-cf12cf1a-6be4-11e7-9ede-8950f36c35ad.png)

**Comment by uBlock-user** [comment]
apparently the old solution still works - https://github.com/reek/anti-adblock-killer/issues/2706#issuecomment-273304491

**Comment by jspenguin2017** [comment]
Hum... I fixed it in another way...

**Comment by jspenguin2017** [comment]
Still works. Closing.
