### ISSUE TITLE
holadoctor.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#410]
### Test link (required): 
https://holadoctor.com/es/
### Screenshot of the web page (required): 
![holadoctor_-_google_chrome_2017-07-19_21-33-52](https://user-images.githubusercontent.com/27441315/28385946-40c5705a-6cca-11e7-92de-78a1a205a3b9.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpsholadoctor comes_2017-07-19_21-34-09](https://user-images.githubusercontent.com/27441315/28385959-4ae146b8-6cca-11e7-8fb1-7ac4223eafdb.png)

**Comment by uBlock-user** [comment]
They're not blocking the scroll. So killing the CSS selector will also do it.

**Comment by jspenguin2017** [comment]
Just use network filter, they conveniently named their file to be `adblock-popup.js` 😂
