### ISSUE TITLE
hells-hack.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#411]
### Test link (required): 
http://hells-hack.com/
### Screenshot of the web page (required): 
![_ _ _ _ _2017-07-19_22-54-00](https://user-images.githubusercontent.com/27441315/28389620-3076a72a-6cd7-11e7-9bcc-d994c8c64070.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httphells-hack com_2017-07-19_22-54-14](https://user-images.githubusercontent.com/27441315/28389622-392be2c2-6cd7-11e7-8202-06a58a89dd63.png)
### Add everything else that you believe to be useful below (optional): 
Steps to reproduce:
Click on the [logo](https://user-images.githubusercontent.com/27441315/28390201-5acdf08a-6cd9-11e7-8e8c-5c6beed44fa4.png)

**Comment by uBlock-user** [comment]
fyi it's baiting `###adblock-msg` from Adblock Warning Removal List, so another CSS bait.

**Comment by jspenguin2017** [comment]
Yea, doesn't matter, just `$generichide` it.
