### ISSUE TITLE
memurlar.net

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#412]
### Test link (required): 
http://video.memurlar.net/default.aspx
http://video.memurlar.net/video/44351/havali-tufekle-fare-avladi.html
### Screenshot of the web page (required): 
![havali_tufekle_fare_avladi_-_memurlar net_-_google_2017-07-19_23-40-00](https://user-images.githubusercontent.com/27441315/28390744-a50dbc5a-6cdb-11e7-9c4e-4d200d1463cc.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpvideo memurlar netvideo_2017-07-19_23-39-43](https://user-images.githubusercontent.com/27441315/28390756-ad4d40d4-6cdb-11e7-80ac-7c0f82658f20.png)

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
nvm, Adguard English filter has got a whitelisted filter - `@@||cdn.vidyomani.com/*/*ads*.js`
