### ISSUE TITLE
uptostream.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#413]
### https://uptostream.com/u25xc7a1qn11

<img width="960" alt="sddsd" src="https://user-images.githubusercontent.com/18214146/28411546-576a0f10-6d41-11e7-938b-f511fe7f8cf2.PNG">

<img width="960" alt="sdsds" src="https://user-images.githubusercontent.com/18214146/28411554-5bb04d82-6d41-11e7-8377-9e01f2b3206b.PNG">

### The player doesn't load.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/da24eaa41cf85fd98e2e480027c127f0.png)

**Comment by xxcriticxx** [comment]
@uBlock-user hit play then reload current page i get this 

but if i hit reload again page loads fine and movie plays with no problem  

![capture](https://user-images.githubusercontent.com/15007183/28420853-73bd0c04-6d31-11e7-843e-44c9e4a0e411.PNG)

**Comment by jspenguin2017** [comment]
Bad EasyList filter, like always.

**Comment by uBlock-user** [comment]
@xxcriticxx I did and the video started playing normally. Still can't reproduce it.

**Comment by adreporter** [comment]
@jspenguin2017 
https://uptostream.com/u25xc7a1qn11
Now I see this
<img width="493" alt="przechwytywanie2" src="https://user-images.githubusercontent.com/18214146/29240282-3675273a-7f62-11e7-8677-deb7970527aa.PNG">
Could you please fix it?

**Comment by lain566** [comment]
It's broken
`https://uptostream.com/iframe/u25xc7a1qn11`
