### ISSUE TITLE
appear.in

### ISSUE THREAD

**Issue by HanSolo80** [jspenguin2017/uBlockProtector#414]
### Test link (required): 
https://appear.in/test
Audio and video not working while extension is active

### Screenshot of the web page (required): 
![Imgur](https://i.imgur.com/m0EEFte.jpg)

### Screenshot of the console (press `F12` to bring up the console) (required): 
Screen1: 
![Imgur](http://i.imgur.com/p1nsAeO.jpg)
Screen2:
![Imgur](http://i.imgur.com/MiSE2IL.jpg)

### Add everything else that you believe to be useful below (optional): 
The problem with this page is that the audio and video is not working when the uBlockProtector extension is active. I tried to whitelist the page in uBlock extension but it didn't make any difference. The only way I could get the audio and video to work is by disabling the uBlockProtector extension completely.

**Comment by uBlock-user** [comment]
Can't reproduce.

probably a bad filter from Easylist.

**Comment by uBlock-user** [comment]
Also there's no whitelisting feature in the Extension, so I'm not sure what you tried exactly.

**Comment by HanSolo80** [comment]
As I said, even when I disabled uBlock extension for this page and only have uBlockProtector active the audio and video doesn't work.

**Comment by jspenguin2017** [comment]
I don't see the problem. 
![image](https://user-images.githubusercontent.com/7283682/28465059-ba7a162e-6de4-11e7-90d3-e36c8a8ce906.png)
![image](https://user-images.githubusercontent.com/7283682/28465074-c3f21de6-6de4-11e7-9cb6-3c7321c2bd00.png)

**Comment by HanSolo80** [comment]
Did you try to speak to someone in the same room? The website itself works, but you can't hear and see anyone that joined the room.
I will be in the room https://appear.in/test the next hour, so if you want you can join it and we will see if it works on your side.

**Comment by jspenguin2017** [comment]
WebRTC wrapper in uBO-Extra is causing the problem, I added a white list. 

Also, https://github.com/gorhill/uBO-Extra/issues/52 @gorhill

**Comment by gorhill** [comment]
Yes I was suspecting a whitelisting would be needed, but the person who opened the issue on my side has not provided timely feedback for me to decide for the whitelisting.
