### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#416]
https://github.com/jspenguin2017/uBlockProtector/issues/40#issuecomment-317170526

https://pilot.wp.pl/tv

**Comment by xxcriticxx** [comment]
@jspenguin2017 told you going have some fun with wp.pl 👍

**Comment by lain566** [comment]
@jspenguin2017 It's broken

![ogladaj_darmowa_telewizje_online_na_zywo_-_google__2017-09-16_14-48-16](https://user-images.githubusercontent.com/27441315/30512369-409e60c6-9aee-11e7-917b-e10f53c60115.png)

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by lain566** [comment]
It's broken again.
