### ISSUE TITLE
gamejolt.com

### ISSUE THREAD

**Issue by clst** [jspenguin2017/uBlockProtector#417]
### Add everything else that you believe to be useful below (optional): 
Adblocking and the flash player work if ublock stays enabled and just protector is disabled. Not even a page reload is necessary (just click "close game" and reopen).

**Comment by clst** [comment]
Problem seems to be the Google IMA SDK doesn't like the extension somehow. I haven't looked very far into it but as soon as the base64 embedded JS from imasdk.googleapis.com loads (that also loads a few iframes) it throw the error in the console.

**Comment by jspenguin2017** [comment]
Hum, the fake SDK isn't working properly, I added an exception.

**Comment by clst** [comment]
Wow, that was quick. Cheers!

**Comment by jspenguin2017** [comment]
It's just a work around, not a fix.

**Comment by clst** [comment]
I saw, but as there seems to be no anti-adblock code on gamejolt it shouldn't matter much (other than clutter your code). Would be good to find out why IMA is acting up or what they used it for.  
Thanks for some really useful software :)

**Comment by jspenguin2017** [comment]
Apparently `google.ima.AdError` is not an instance of `Error`...
