### ISSUE TITLE
gamekit.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#418]
### Test link (required): 
https://gamekit.com/quest
### Screenshot of the web page (required): 
![gana_pts_-_gamekit_-_juegos_mmo_ _seccion_de_regal_2017-07-20_11-56-24](https://user-images.githubusercontent.com/27441315/28498432-97ee9598-6f9d-11e7-8789-e5df11a97a9a.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpsgamekit comquest_2017-07-20_11-56-41](https://user-images.githubusercontent.com/27441315/28498434-9d660c5e-6f9d-11e7-8cc9-82241686e546.png)

**Comment by jspenguin2017** [comment]
Seems to require account. Can you provide a test account? 
Open a confidential issue in GitLab.

**Comment by lain566** [comment]
Do you already have the test account?

**Comment by uBlock-user** [comment]
Geo-Lock is present!

**Comment by uBlock-user** [comment]
`||$third-party,script,domain=gamekit.com`

see it that kills it

**Comment by uBlock-user** [comment]
Found anti adblock script - https://gamekit.com/scripts/421aba1-cf29026.js,2888a26-6f5f2e9.js,ac2a3d7-e4b5c93.js,fd9e92b-f958388.js,d56da86-8756ce8.js,3f3ada0-479d194.js,826f20c-6c1e0c1.js,dad90e4-90ce112.js,9cdc37c-018ab8f.js,d93e8c5-efdfdc0.js,f708e31-a4435fd.js,74163d3-00302af.js,e41e509-96cbb54.js,d02922f-1d41854.js,636e639-09ca643.js,aff021a-f981e09.js,48ec5f8-2072eb4.js,8706d0a-97433ba.js,3c00eb7-c7d9084.js,73b26b1-0837340.js,a35e9f8-d267f28.js,f9cf7b0-7283fbd.js,4b96114-389d158.js,d934bde-e452831.js,b4b97fe-ec0f483.js,8a80dfc-dc0f359.js,2e4efd0-4e6347b.js,a705404-9c4c312.js,7d2f6e3-ef54a7f.js,f23e3ea-9b7cff7.js,a53fe4e-7b2798a.js,56f34f4-251a532.js,3688c2b-1373811.js,ebfd9d4-9202935.js,bc252b8-83fe34d.js,482b47c-97e093c.js,3a81576-bb7315a.js,cb703c1-ac5aba5.js,d8380cf-253c798.js,5d55b11-3f83b08.js,e1da01d-5cbe4ab.js,eb8186e-cb6a838.js,2b0de80-2f37b3c.js,1be0e2e-6e8272a.js,daed843-dec1701.js,79ef395-99de01b.js,44a4b01-55265df.js,c818580-5ecff3a.js,203960c-e202c2c.js,32ba6bb-9ccc0ab.js,4d1df7e-735ac7a.js,3352f3e-4631e68.js,d63857e-9154f76.js,c9396e3-c24de1c.js,196b974-5c56735.js,62315f6-27509a1.js,3f37a61-4dba505.js

**Comment by uBlock-user** [comment]
This page doesn't require login - https://gamekit.com/forum/

Can you reproduce it there ?

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/28500337-ca9a9182-6f83-11e7-92e1-82c690acca23.png)
![image](https://user-images.githubusercontent.com/7283682/28500339-d1cbb454-6f83-11e7-8a77-36fd74030643.png)

I think it does require login. That script is too big, can you pin down the section?

**Comment by jspenguin2017** [comment]
@lain566 I don't think I have a test account.

**Comment by lain566** [comment]
@jspenguin2017 here https://gist.github.com/lain566/c03fd525f6d5d8dd1cac3a88d7611c8e

**Comment by jspenguin2017** [comment]
Thanks, I can reproduce now.

**Comment by jspenguin2017** [comment]
Seems to work, can you test?

**Comment by lain566** [comment]
@jspenguin2017 Yes, it works. Thanks 👍

**Comment by uBlock-user** [comment]
```javascript
adBlockDetect: function (timeout) {
        if (typeof timeout === 'undefined') {
            timeout = 5000;
        }

        if (!$('#a-d-block-popup').length) {
            return;
        }
```

```javascript
 window.setInterval(function () {
            var iframe = document.getElementById('ads-text-iframe');
            var adblockPopup = document.getElementById('a-d-block-popup');

            if (iframe.style.display == 'none' || iframe.style.display == 'hidden' ||
                iframe.style.visibility == 'hidden') {
                $.magnificPopup.open({
                    showCloseBtn: false,
                    closeOnBgClick: false,
                    enableEscapeKey: false,
                    items: {
                        src: '#a-d-block-popup',
                        type: 'inline'
                    }
                });
```
