### ISSUE TITLE
filmz.dk

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#419]
### Test link (required): 
http://filmz.dk/
### Screenshot of the web page (required): 
![filmz_-_google_chrome_2017-07-23_17-33-17](https://user-images.githubusercontent.com/27441315/28500706-38e73106-6fcd-11e7-82e8-592d9c05a323.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpfilmz dk_2017-07-23_17-33-41](https://user-images.githubusercontent.com/27441315/28500707-3ee0c586-6fcd-11e7-8526-7fc964dd2502.png)

**Comment by jspenguin2017** [comment]
Renamed FuckAdBlock. Why is this script so popular...

**Comment by uBlock-user** [comment]
Because the name itself represents the hate towards adblock users which is usually the case with most webmasters, they hate adblock users, simple.

**Comment by uBlock-user** [comment]
It's a 3rd party anti adblock script coming from domain 5`3de24a8d5e98766af5d18a0323a72a1.dk`

**Comment by uBlock-user** [comment]
Blocking that also fixes it.

**Comment by jspenguin2017** [comment]
I think there are other stuff served though that domain... Well, whatever works, I'll just apply the generic FAB solution.
