### ISSUE TITLE
ghame.ru

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#420]
### Test link (required): 
https://ghame.ru/
### Screenshot of the web page (required): 
![ghame ru_-_google_chrome_2017-07-23_18-21-11](https://user-images.githubusercontent.com/27441315/28501053-deaa2fde-6fd3-11e7-80d8-7dcdd85b65aa.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpsghame ru_2017-07-23_18-20-55](https://user-images.githubusercontent.com/27441315/28501056-e3ccd264-6fd3-11e7-8fb2-c01156c851bb.png)

### Add everything else that you believe to be useful below (optional): 
Page does not load if uBlock Protector Extension is enabled

**Comment by lain566** [comment]
@jspenguin2017 uBlock Protector Extension is disabled by Chrome 
`This extension may has been corrupted.`
![extensiones_-_google_chrome_2017-07-23_20-17-04](https://user-images.githubusercontent.com/27441315/28501809-1a7a4c32-6fe4-11e7-847c-307b2c5ff9c7.png)

**Comment by jspenguin2017** [comment]
Can't reproduce, reinstall?

**Comment by lain566** [comment]
Yes, that worked

**Comment by jspenguin2017** [comment]
That happens when the signature doesn't match, the signing is done by Google, so when it doesn't match it's either the store is broken or the files are actually damaged.

**Comment by uBlock-user** [comment]
That's a v59 bug in Chromium, was patched few weeks back.
