### ISSUE TITLE
nachrichten.at

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#422]
### Test link (required): 
http://www.nachrichten.at/nachrichten/fotogalerien/cme203651,1782293
### Screenshot of the web page (required): 
![bildergalerie_top_5_des_nationalparks_tiere _pfl_2017-07-23_22-22-23](https://user-images.githubusercontent.com/27441315/28503980-e950722c-700f-11e7-98da-750239ba30b1.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww nachrichten atnachri_2017-07-23_22-22-51](https://user-images.githubusercontent.com/27441315/28503981-effaa66a-700f-11e7-8952-a70389310300.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
