### ISSUE TITLE
wired.it

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#423]
### Test link (required): 
https://www.wired.it/play/cinema/2017/02/23/doctor-strange-ditko-escher-e-matrix/
### Screenshot of the web page (required): 
![doctor_strange_e_gli_effetti_speciali_tra_ditko _e_2017-07-24_10-11-31](https://user-images.githubusercontent.com/27441315/28516971-40c89f86-7063-11e7-871d-a02cac8c41e0.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww wired itplaycinema_2017-07-24_10-12-04](https://user-images.githubusercontent.com/27441315/28516978-465c463c-7063-11e7-9e13-3b0eff395be5.png)

**Comment by lain566** [comment]
If you click on the video, message anti-adblock appears

test link
https://www.wired.it/video/2017/06/27/wired-next-fest-2017/809101

**Comment by uBlock-user** [comment]
Can't reproduce.
