### ISSUE TITLE
playrust.io

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#424]
### Test link (required): 
http://playrust.io/map/?74.91.113.39:28025
### Screenshot of the web page (required): 
![viking_republic_4x_ 0724 _pvpezlootgunsinstat_2017-07-24_21-59-59](https://user-images.githubusercontent.com/27441315/28542205-ad4d5c20-70bb-11e7-91e7-c7fab5396b93.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpplayrust iomap74 91 11_2017-07-24_22-00-12](https://user-images.githubusercontent.com/27441315/28542229-c58e4416-70bb-11e7-9cab-5853e9fd7bf3.png)

**Comment by uBlock-user** [comment]
`playrust.io##script:inject(abort-on-property-read.js, as_slots)`

Hmm, that filter still works

**Comment by jspenguin2017** [comment]
I'm afraid that blowing up that file will have side effects... Are you absolutely sure it doesn't break anything? I don't have an account, can't test all functionalities.

**Comment by uBlock-user** [comment]
No, I'm not absolutely sure but noone has complained about it, so I will need some feedback. I posted that filter a long time ago - https://github.com/reek/anti-adblock-killer/issues/2865#issuecomment-280860251

**Comment by jspenguin2017** [comment]
Looks like about 0 people saw your post... 
It definitely needs to be tested, as the functions are called externally, probably from main code. And uBO swallows the error, kind of annoying actually.

**Comment by uBlock-user** [comment]
Or it could be that some may have seen it, added it and nothing broke for them so didn't bother to come back post the feedback.

Alright, this is the script - http://playrust.io/js/as.js

see any potential breakage ?

**Comment by jspenguin2017** [comment]
If the code is called within the main code and it blow up, then it can cause problems. What we really need is someone with an account to test it.

**Comment by uBlock-user** [comment]
Actually you need a steam account which I don't have as I don't buy or play steam games.

**Comment by uBlock-user** [comment]
Okay, on a closer look, it does look like it can cause breakage, and this is the specific anti adblock code

```javascript
function as_notice() {
    var counter = 20;
    var overlay = $('<div />');
    overlay.css({ 'position': 'fixed', 'left': '0', 'top': '0', 'z-index': '9999', 'width': '100%', 'height': '100%', 'text-align': 'center', 'background-color': 'rgba(0,0,0,0.3)', 'padding-top': '10%' });
    var inner = $('<div />');
    inner.addClass('inner');
    inner.css({ 'display': 'block', 'margin': 'auto', 'width': '550px', 'background': '#eee', 'border-radius': '7px', 'padding': '3px', 'color': '#111', 'line-height': '140%' });
    inner.append($('<p />')
        .text('Advertising enables us to provide Rust:IO for free')
        .css({ 'font-weight': 'bold' }));
    inner.append($('<p />')
        .text('May we kindly ask you to disable your ad blocker? Just for us?'));
    var btn = $('<button />');
    btn.text('Nah, that ain\'t me. (' + counter + ')');
    btn.css({ 'border': '1px solid #999', 'background': '#ddd', 'padding': '3px 5px 5px 5px', 'border-radius': '5px', 'cursor': 'pointer', 'color': '#666' });
    btn.click(function () {
        if (counter > 0)
            return false;
        overlay.remove();
    });
    inner.append($('<p />')
        .append(btn));
    overlay.append(inner);
    for (var i = 0; i < ((Math.random() * 15) | 0); ++i)
        $(document.body)
        .append('<div />');
    $(document.body)
        .append(overlay);
    var timer = setInterval(function () {
        if (--counter === 0) {
            clearInterval(timer);
            btn.text('Nah, that ain\'t me.');
            btn.css({ 'color': '#111' });
        } else { btn.text('Nah, that ain\'t me. (' + counter + ')'); }
    }, 1000);
}
```
