### ISSUE TITLE
ghacks.net

### ISSUE THREAD

**Issue by ariefpizzuti** [jspenguin2017/uBlockProtector#425]
Test link (required): 
https://www.ghacks.net/2017/05/02/create-custom-windows-10-installations-with-msmg-toolkit/

Screenshot of the web page (required): 

![screenshot 1](https://user-images.githubusercontent.com/18688192/28545340-3e36458e-70f9-11e7-99f9-cd4e8192768b.png)

Screenshot of the console (press `F12` to bring up the console) (required): 

![screenshot 2](https://user-images.githubusercontent.com/18688192/28545357-4c39590a-70f9-11e7-9f16-26f08a6d1848.png)

**Comment by uBlock-user** [comment]
Didn't think Martin would stoop down to this level, but oh well!

**Comment by uBlock-user** [comment]
Running 4 nasty `evals`.

**Comment by jspenguin2017** [comment]
I just blocked `atob`. I'll switch to blocking `eval` if `atob` is used elsewhere.

**Comment by uBlock-user** [comment]
Filter - `ghacks.net##script:inject(noeval-if.js, adblock)`

**Comment by okiehsch** [comment]
After more and more users [complained](https://www.ghacks.net/2017/07/24/windows-10-web-search-gets-a-tad-more-useful/#comment-4218237), he saw the errors of his way and [removed](https://www.ghacks.net/2017/07/26/chrome-60-stable-is-out/#comment-4218540) the offending script.

**Comment by jspenguin2017** [comment]
- `atob` is no longer noop on `ghacks.net`. 
- `ghacks.net` is no longer white listed.

**Comment by uBlock-user** [comment]
For a guy promotes uBlock Origin on regular basis, it was so paradoxical to see him going that way. 

Anyways, found another case - http://www.fhm.com

Same anti adblock script 

Filter - `fhm.com##script:inject(noeval-if.js, adblock)`

**Comment by jspenguin2017** [comment]
It's already taken care by another filter: `fhm.com##script:inject(abort-on-property-write.js, adonisHash)`

**Comment by uBlock-user** [comment]
Yeah looks like uBlock Filters already covered it.. I didn't have it. Force update did the job.
