### ISSUE TITLE
dilidili.wang

### ISSUE THREAD

**Issue by chen185102** [jspenguin2017/uBlockProtector#426]
### Test link (required): 
http://www.dilidili.wang/
### Screenshot of the web page (required): 
![default](https://user-images.githubusercontent.com/22681233/28570696-db9e22d8-7171-11e7-9e63-20c5103a47e0.PNG)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![default](https://user-images.githubusercontent.com/22681233/28570725-004a86e4-7172-11e7-9109-b5ce7556ad31.png)

### Add everything else that you believe to be useful below (optional): 
It seems to be updated yesterday...

**Comment by uBlock-user** [comment]
Is that working ?https://github.com/jspenguin2017/uBlockProtector/commit/6f2cd6d93037b03240f81b6a3eb32aab708f58c3

**Comment by jspenguin2017** [comment]
Looks like they changed something... It was working yesterday.

**Comment by jspenguin2017** [comment]
Looks like I need to filter this out. 
```JavaScript
<!-- good game well play -->
<script>
    $(function () {
        document.addEventListener('DOMNodeInserted',function () {
            // var ele1Length=document.querySelectorAll('*[hidden]').length;
            if (document.querySelectorAll('*[hidden]')){
                var ele1=document.querySelectorAll('*[hidden]');
                for (var i=0;i<ele1.length;i++){
                    ele1[i].removeAttribute('hidden');
                }
                var tagStyle=document.getElementsByTagName('style')[0];
                tagStyle.parentNode.removeChild(tagStyle)
            }
        });
    })
</script>
```

**Comment by jspenguin2017** [comment]
They commented it out and now checks for network...

**Comment by uBlock-user** [comment]
```javascript
  $.ajax({
    url: "http://static.jfrft.com/js/main_list.js",
    dataType: "script"
    }).done(function(){   
        $.ajax({
            url: "http://static.jfrft.com/js/main_video.js",
            dataType: "script"
            }).fail(function(){
                document.body.innerHTML='<h2 id="adb-contant">æˆ‘ä»¬æ£€æµ‹åˆ°ä½ å¯èƒ½ä½¿ç”¨äº†å¹¿å‘Šè¿‡æ»¤æ’ä»¶æˆ–è½¯ä»¶ï¼Œå®ƒçš„éƒ¨åˆ†ç­–ç•¥å¯èƒ½ä¼šå½±å“åˆ°æ­£å¸¸åŠŸèƒ½çš„ä½¿ç”¨ã€‚<br>ä½ å¯ä»¥è®¾å®šç‰¹æ®Šè§„åˆ™æˆ–å°†å˜€å“©å˜€å“©åŠ å…¥ç™½åå•ï¼Œä»¥ä¾¿æ›´å¥½çš„åœ¨äºŒæ¬¡å…ƒä¸–ç•Œé©°éª‹ã€‚</h2>';
            });
    }).fail(function(){
        document.body.innerHTML='<h2 id="adb-contant">æˆ‘ä»¬æ£€æµ‹åˆ°ä½ å¯èƒ½ä½¿ç”¨äº†å¹¿å‘Šè¿‡æ»¤æ’ä»¶æˆ–è½¯ä»¶ï¼Œå®ƒçš„éƒ¨åˆ†ç­–ç•¥å¯èƒ½ä¼šå½±å“åˆ°æ­£å¸¸åŠŸèƒ½çš„ä½¿ç”¨ã€‚<br>ä½ å¯ä»¥è®¾å®šç‰¹æ®Šè§„åˆ™æˆ–å°†å˜€å“©å˜€å“©åŠ å…¥ç™½åå•ï¼Œä»¥ä¾¿æ›´å¥½çš„åœ¨äºŒæ¬¡å…ƒä¸–ç•Œé©°éª‹ã€‚</h2>';
    });
```

**Comment by uBlock-user** [comment]
`$.fail `or `$.done` don't work.

**Comment by jspenguin2017** [comment]
Why would it work? It is a method of an object returned from `$.ajax`.

**Comment by jspenguin2017** [comment]
I think I can blow up `innerHTML`, not sure if it is used elsewhere...

**Comment by uBlock-user** [comment]
It's property of jQuery it should work, regardless.

**Comment by uBlock-user** [comment]
Blowing `innnerhtml` breaks thumbnails, already tried that.

**Comment by uBlock-user** [comment]
Blowing `$.ajax` would also kill it but also breaks thumbnails.

**Comment by jspenguin2017** [comment]
I'll just patch `innerHTML`.

**Comment by jspenguin2017** [comment]
Hopefully it'll work, I never done it XD

**Comment by jspenguin2017** [comment]
Oh wow, it actually worked, now I have a way to block `document.body.innerHTML = "..."`.

**Comment by uBlock-user** [comment]
Think they will patch this soon too ?

**Comment by jspenguin2017** [comment]
Everything can be patched. Doesn't matter what we do, if they are determined, they can patch it in hours.

**Comment by leoxxx** [comment]
@jspenguin2017 what's the rule for ABP?

**Comment by jspenguin2017** [comment]
No rule for ABP.

**Comment by jspenguin2017** [comment]
Still works. Closing. Let me know if they changed it again.
