### ISSUE TITLE
maketecheasier.com

### ISSUE THREAD

**Issue by ariefpizzuti** [jspenguin2017/uBlockProtector#427]
Test link (required): https://www.maketecheasier.com/best-context-menu-editors/

Screenshot of the web page (required): 

![screenshot 3](https://user-images.githubusercontent.com/18688192/28579355-0a3c269a-718f-11e7-9170-8b7e6e6345a7.png)

Screenshot of the console (press `F12` to bring up the console) (required): 

![screenshot 4](https://user-images.githubusercontent.com/18688192/28579364-104ec9ac-718f-11e7-988d-0d29898b1d19.png)

**Comment by uBlock-user** [comment]
Filter - `maketecheasier.com##script:inject(noeval-if.js, adblock)`

**Comment by ariefpizzuti** [comment]
Thank you @uBlock-user

**Comment by uBlock-user** [comment]
same as https://github.com/jspenguin2017/uBlockProtector/issues/425

3 nasty evals

**Comment by jspenguin2017** [comment]
Adonis.

**Comment by uBlock-user** [comment]
Yes we call also kill it via blowing the `adonis` variable.
