### ISSUE TITLE
latin.it

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#428]
### Test link (required): 
http://www.latin.it/versione/40264
### Screenshot of the web page (required): 
![otone_temporeggia_e_poi_riesce_a_uccidere_galba_-__2017-07-25_20-32-05](https://user-images.githubusercontent.com/27441315/28588335-849646ec-717a-11e7-9ff5-75c289024d32.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww latin itversione413_2017-07-25_20-32-20](https://user-images.githubusercontent.com/27441315/28588340-882d9152-717a-11e7-90c1-a92d43543de7.png)

**Comment by jspenguin2017** [comment]
I could reproduce once, then it shows the content just fine...

**Comment by lain566** [comment]
@jspenguin2017 If you disable uBO the anti-adblock message disappears, and no longer appears even if you have to enable uBO again.
Try again using VPN.

**Comment by jspenguin2017** [comment]
I see the problem, they are logging on the server side whether `banner.php` is requested, and I have manually requested it (to see what's in it) which disables their detection. 
Looks like I have to use whitelist for this one. `@@||latin.it/banner.php`

**Comment by lain566** [comment]
Yes, that solved my issue 👍

**Comment by uBlock-user** [comment]
Same as https://github.com/jspenguin2017/uBlockProtector/issues/428#issuecomment-317861705

I can't reproduce it again after the first time.
