### ISSUE TITLE
stocks.cafe

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#430]
### Test link (required): 
https://stocks.cafe
### Screenshot of the web page (required): 
![intelligent_portfolio_management_-_stockscafe_-_go_2017-07-26_09-36-41](https://user-images.githubusercontent.com/27441315/28609690-fcd1062c-71e5-11e7-9410-80387288e107.png)

![stockscafe_-_google_chrome_2017-07-26_09-12-52](https://user-images.githubusercontent.com/27441315/28609616-bb748050-71e5-11e7-85f0-8586d731c14e.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpsstocks cafead_block_mes_2017-07-26_09-13-07](https://user-images.githubusercontent.com/27441315/28609620-c0ad43e0-71e5-11e7-840b-ad891aeea911.png)

### Steps to reproduce: 
Reload page 11 times

**Comment by uBlock-user** [comment]
https://stocks.cafe/js/showads.js

ads.js v2

**Comment by uBlock-user** [comment]
Does this filter work ?

`||stocks.cafe/amazon/google728x90Top`
