### ISSUE TITLE
iprima.cz

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#431]
### Test link (required): 
http://prima.iprima.cz/porady/ted-vari-sef/6-epizoda-0
### Screenshot of the web page (required): 
![ted_vari_sef _6 _epizoda__prima_-_google_chrome_2017-07-26_00-19-03](https://user-images.githubusercontent.com/27441315/28596399-a74f4b84-7198-11e7-8413-27ef8708e3c7.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpprima iprima czporadyte_2017-07-26_00-22-05](https://user-images.githubusercontent.com/27441315/28596408-b356cf6a-7198-11e7-8445-d7bbc075ed1d.png)
![developer_tools_-_httpprima iprima czporadyte_2017-07-26_00-22-23](https://user-images.githubusercontent.com/27441315/28596413-b8f013b4-7198-11e7-89ce-6c368aee4f0a.png)

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/3360#issuecomment-314023309 is not working anymore

**Comment by uBlock-user** [comment]
Embedded inline script view-source:http://api.play-backend.iprima.cz/prehravac/embedded?id=p248627

**Comment by jspenguin2017** [comment]
They updated the selector: `iprima.cz##.play-wrapper.player-wrapper + .you-shall-not-pass`

**Comment by uBlock-user** [comment]
Keep the old filter, it still works on http://play.iprima.cz/vinari/vinari-ii-16

**Comment by uBlock-user** [comment]
They didn't update it, but rather added another one.

**Comment by uBlock-user** [comment]
Video player controls don't work, need to add `iprima.cz###AdTrackVideoPlayer`

**Comment by jspenguin2017** [comment]
Controls works fine for me...

**Comment by lain566** [comment]
@jspenguin2017 Controls is not working for me.

**Comment by uBlock-user** [comment]
Controls don't work for me after your patch, but adding `iprima.cz###AdTrackVideoPlayer` and they work again.

**Comment by uBlock-user** [comment]
It's like an invisible overlay which requires to be removed to gain access to the controls.

**Comment by lain566** [comment]
Yep, that works
