### ISSUE TITLE
geo.de

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#432]
### Test link (required): 
http://www.geo.de/natur/tierwelt/16822-rtkl-hummelsterben-warum-liegen-unter-linden-im-sommer-so-viele-tote-hummeln
### Screenshot of the web page (required): 
![hummelsterben_warum_liegen_unter_linden_im_sommer_2017-07-26_10-48-07](https://user-images.githubusercontent.com/27441315/28612577-08986068-71f0-11e7-86cb-a9de5145e1ae.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww geo denaturtierwelt_2017-07-26_10-48-19](https://user-images.githubusercontent.com/27441315/28612586-0d581c7e-71f0-11e7-9d4d-ec3da3609254.png)

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
Blocking that JS will kill it.

**Comment by jspenguin2017** [comment]
Doesn't work for me.

**Comment by jspenguin2017** [comment]
The detection script seems to be here: https://connectormwi.laterpay.net/2.14.0/live/app-de-de.js

**Comment by uBlock-user** [comment]
`@@||geo.de^$elemhide`

Does that work ?

**Comment by jspenguin2017** [comment]
`||laterpay.net^$domain=geo.de`
Doesn't seem to break anything, I think Later Pay is only used for subscription on that domain.
