### ISSUE TITLE
listamais.com.br

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#433]
### Test link (required): 
https://www.listamais.com.br/
### Screenshot of the web page (required): 
![lista_mais__a_plataforma_que_conecta_consumidores_2017-07-26_12-01-51](https://user-images.githubusercontent.com/27441315/28615709-593c220c-71fa-11e7-8d31-c17b86c3e253.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww listamais com br_2017-07-26_12-02-00](https://user-images.githubusercontent.com/27441315/28615717-5f9f75e0-71fa-11e7-8fd7-3298e8a6ed5f.png)

**Comment by uBlock-user** [comment]
https://www.listamais.com.br/Resources/js/ads.js

ads.js v2

**Comment by uBlock-user** [comment]
```javascript
if (!document.getElementById('iufjSNpeSJm')) {
--
  | $.ajax({
  | dataType: 'html',
  | type: 'GET',
  | url: '/Shared/AdBlockerModal',
  | success: function (result) {
  | var $modal = $('#homeModal');
  | $modal.find('.modal-content').html(result);
  | $modal.modal({
  | keyboard: false,
  | backdrop: 'static',
  | show: true
  | });
  | }
  | });
  | }
```
