### ISSUE TITLE
techforever.net

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#434]
### Test link (required): 
http://www.techforever.net/
### Screenshot of the web page (required): 
![techforever_-_google_chrome_2017-07-26_19-58-15](https://user-images.githubusercontent.com/27441315/28636044-2ae99bc6-723d-11e7-8baf-56a25be02b3a.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww techforever net2014_2017-07-26_19-57-28](https://user-images.githubusercontent.com/27441315/28636057-336091ce-723d-11e7-9e40-f814d13605d9.png)

**Comment by uBlock-user** [comment]
https://central.bhaskar.com/adblock/google/adtech/ads.js

**Comment by uBlock-user** [comment]
`setTimeout(function(){try{if(canABP){}}catch(e){var count=0;var el=document.getElementsByTagName('body')[0];elChild=document.createElement('div');elChild.innerHTML=el.innerHTML;el.innerHTML="";elChild.setAttribute('id','blockwrapper');el.insertBefore(elChild,el.firstChild);document.getElementById("blockwrapper").style.transform='matrix(-1, 0, 0, 1, 0, 0)';var imageCount=document.getElementsByTagName("img");for(var i=0;i<imageCount.length;i++){imageCount[i].style.transition="transform 2s";imageCount[i].style.transform="matrix(0.586,0.8,-0.8,0.586,-54,92)";};$('body').css('overflow-x','hidden');setTimeout(openPopUpForBreakPage,'2000');}},'4000');function openPopUpForBreakPage(){var ODiv=document.createElement("div");ODiv.setAttribute("id","Odiv");document.getElementsByTagName("body")[0].appendChild(ODiv);var OCDiv=document.createElement("div");OCDiv.setAttribute("id","OCdiv");document.getElementsByTagName("body")[0].appendChild(OCDiv);document.getElementById("OCdiv").innerHTML="<img src='https://2.bp.blogspot.com/-EppBQwI84kE/V46Qs491yqI/AAAAAAAAC7Y/-8jpQvRwaa8YAP96A0C58n5StTAI6DFcACLcB/s1600/imageedit_3_5938355881.gif'><a href=''></a>";document.getElementById("OCdiv").style.transition='top 1s';setTimeout(function(){$('#OCdiv').css('top','25%');},1000)}`

**Comment by uBlock-user** [comment]
Also running two suspicious `evals`

**Comment by uBlock-user** [comment]
Filter - `techforever.net##script:inject(setTimeout-defuser.js, canABP)`
