### ISSUE TITLE
videacesky.cz

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#435]
### Test link (required): 
https://videacesky.cz/
### Screenshot of the web page (required): 
![videacesky cz__youtube_videa_s_ceskymi_titulky_-__2017-07-26_20-22-56](https://user-images.githubusercontent.com/27441315/28637018-5b7290b0-7240-11e7-87f5-4701340d45d7.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpsvideacesky cz_2017-07-26_20-23-05](https://user-images.githubusercontent.com/27441315/28637028-618f8372-7240-11e7-865c-b16e31dad0e6.png)

**Comment by uBlock-user** [comment]
Filter - |`|videacesky.cz/js/adbdetect.min.js`

**Comment by uBlock-user** [comment]
traces of anti adblock found in https://videacesky.cz/js/app.js

**Comment by uBlock-user** [comment]
inline-script


```javascript
<!-- CHECK IF ADBLOCK IS TURN ON -->
--
  | <script type="text/javascript">
  | var adb = false;
  | </script>
  | <script>
  | $(document).ready(function(){
  |  
  | adblockDetect(function(adblockDetected) {
  | if (adblockDetected)
  | {
  | adb = true;
  |  
  | gaEvent('_trackEvent', 'AdBlock', '103.241.226.50', undefined, undefined, {'nonInteraction': 1});
  |  
  | showAdblockWarning();
  |  
  | }
  | });
  | });
  | </script>
  | <script type="text/javascript">
  | $(document).ready(function(){
  | adblockDetect(function(adblockDetected) {
  | if (adblockDetected) adb = true;
  | });
  | });
  | </script>
  | <!-- END CHECK IF ADBLOCK IS TURN ON -->
```

**Comment by uBlock-user** [comment]
Filter mentioned in https://github.com/jspenguin2017/uBlockProtector/issues/435#issuecomment-318150216 breaks videos apparently 

Use - `videacesky.cz##script:inject(abort-on-property-read.js, showAdblockWarning)`

**Comment by uBlock-user** [comment]
There's also an unnecessary overlay on the video player, add `videacesky.cz##.videoOverBlock`
