### ISSUE TITLE
explosm.net

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#439]
http://explosm.net/

47c0b3bff446ceaac3c6e9a59f10d8f4a0d7ef6d

**Comment by jspenguin2017** [comment]
Looks like the video loading is built into the ads controller... 
![image](https://user-images.githubusercontent.com/7283682/28723381-ce2d136c-7373-11e7-939e-1d855f9332d5.png)

**Comment by jspenguin2017** [comment]
They seems to always use YouTube, but I'm not sure if that's always the case, I guess white list the embed is the way to go...

**Comment by uBlock-user** [comment]
XHRs from http://explosm.net/extra/promo/ needs to be blocked.

**Comment by uBlock-user** [comment]
can't reproduce any anti adblock detection though

**Comment by uBlock-user** [comment]
You can also block those anti adblock notices via `explosm.net##.blocked-panel`

**Comment by jspenguin2017** [comment]
It's up to EasyList to block first party promos.
