### ISSUE TITLE
(Discussion and parameters draft) v11 new APIs

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#440]
### Implemented (final parameters are in the source file)

Prevent or interfere the execution of a specific ~~inline~~ script. 
*I always thought that it's not possible without `beforescriptexecute` event, turns out I'm wrong.*

Parameters (draft 1): 
`a.getMatcher` returns string, which means matching logic needs to be re-implemented. Maybe it should take a callback instead. 
- `method`: The filter method. 
- `filter`: The filter. 

Parameters (draft 4): 
It is also possible to patch the inline script instead of removing it, maybe it should be better to ask a callback what to do. 
But then this is more of a fancy wrapper... And it should be names `a.patchInline`. But then this function can patch more than just inline script, scripts with `src` can be patched too... Maybe I should just name it `a.beforeScriptExecute`... 
- `handler`: The callback function, it is given: 
    - `script`: The script element, patch or remove it as appropriate. 
    - `parent`: The parent of the script element. 
- `inlineOnly`: Whether the callback should only be called when the script is an inline script. 

Usage: 
This is probably a better way to deal with Instart Logic, as aborting the document and use `document.write` to load it doesn't always go well. 

### Implemented (final parameters are in the source file)

Prevent assignment of `innerHTML`, `innerText`, and `textContent` of a specific element. 

Parameters (draft 2): 
- `matcher`: Matcher function, it will lose its scope. It will be given: 
    - `elem`: The target element.
    - `data`: The new `innerHTML`, `innerText`, or `textContent`. 
    - `type`: `innerHTML`, `innerText`, or `textContent`. Probably an enumeration in the runtime. 

Usage: 
To prevent webpage from nuking `body` when it detects ad blocker.

**Comment by uBlock-user** [comment]
This is brilliant. By v11, do you mean v11 of JS script engine used by Chromium ?

**Comment by jspenguin2017** [comment]
Yes v11 if Extension. 
I'm still planning it, think twice code once, I want to get it right the first time.

**Comment by uBlock-user** [comment]
Is there any official documentation online about these APIs ?

**Comment by jspenguin2017** [comment]
It's my API, so the post above is draft of official documentation.

**Comment by jspenguin2017** [comment]
> Documentation of my custom API is in `content/content-core.js`, `content/content-domlib.js`, and `background/background-core.js`. 

I have documented my APIs, but since I'm the only one using them, I just left them in the source file.

**Comment by jspenguin2017** [comment]
Tested on a few IL sites, seems to somewhat works, but not perfect. Don't fix what is not broken I guess... I'll leave it as-is for now.

**Comment by jspenguin2017** [comment]
Testing my new black magic on BlockAdBlock 😄 
Execution of BlockAdBlock scripts with the legal notice will be canceled.

**Comment by jspenguin2017** [comment]
It is working beautifully and consistently with DevTools open... As soon as I close DevTools, it stops working...

**Comment by jspenguin2017** [comment]
Looks like Chrome doesn't always supply `textContent` for large scripts... 
![image](https://user-images.githubusercontent.com/7283682/28749731-ad4988d0-748e-11e7-9d19-e8a2ecfd59ec.png)

**Comment by jspenguin2017** [comment]
For some reasons, `textContent` doesn't always work... But `id` does work consistently, well, having a half-working way to block specific inline script is better than having no way to do that.

**Comment by jspenguin2017** [comment]
It randomly drop the `textContent`, `innerText`, and `innerHTML`... Is this a bug in Chromium? 
![image](https://user-images.githubusercontent.com/7283682/28750433-cfed1bc2-74a7-11e7-9d33-e6d411733e5f.png)

**Comment by uBlock-user** [comment]
Is it done ? So now we have our own `BeforeScriptExecute` event ?

**Comment by jspenguin2017** [comment]
@uBlock-user Eh... Kind of... Sometimes works, usually don't...

**Comment by ghajini** [comment]
is instart logic destroyable with this?

**Comment by jspenguin2017** [comment]
Yes and no, I can prevent a script from executing, but I can't know which script to block. The only thing I can rely on is counting, which requires too many assumptions to be safe to use.

**Comment by uBlock-user** [comment]
> I can't know which script to block

Can't you do something about that ?

**Comment by jspenguin2017** [comment]
Maybe... I'm not sure. I did try a few things, but nothing worked so far.

**Comment by uBlock-user** [comment]
I will give you an example script


```javascript
(function (doc, adBlockHandlerName, adBlockLocation) {
--
  | window[adBlockHandlerName] = function() {
  | var load = function load() {
  | var xhr = new XMLHttpRequest();
  | xhr.withCredentials = true;
  | xhr.open('GET', adBlockLocation, true);
  | xhr.onreadystatechange = function () {
  | if (xhr.readyState == 4 && xhr.status == 200 && xhr.responseText) {
  | eval(xhr.responseText);
  | }
  | };
  | try {
  | xhr.send();
  | } catch (e) {
  | try { console.error('Unable to load antiadblock code'); } catch(e) {}
  | }
  | };
  | load();
  | };
  | })(window.document, 'hahaadblock', '/804548.hahaadblock');
```

How will BeforeScriptExecute block it ?

**Comment by jspenguin2017** [comment]
Either this script has an *attribute* that I can grab on, or it is *preceded* by a script that has an attribute that I can grab on. For example, an `id` is perfect: 1f6be1c40c36df8549d7f37ef2cda386ca9132c9. 

For some unknown reasons, I can't reliably read its `textContent`. Actually, I don't even know if `MutationObserver` is suppose to be able to cancel script execution.

**Comment by jspenguin2017** [comment]
Also I have a more fancy implementation here: https://gist.github.com/jspenguin2017/cd568a50128c71e515738413cd09a890

**Comment by uBlock-user** [comment]
> Either this script has an attribute that I can grab on, or it is preceded by a script that has an attribute that I can grab on.

So does it have any ?

**Comment by uBlock-user** [comment]
That example script comes from here - view-source:https://fmovies.is/

Can you check it out ?

**Comment by uBlock-user** [comment]
Also will `src` as an attribute work ?

**Comment by jspenguin2017** [comment]
Yes, that should work, that script is removable, but I don't see it doing anything.

**Comment by uBlock-user** [comment]
It `evals` and then launches an XHR called "/hahaadblock" upon detection, no visible anti adblock blockage though, but it's only a matter of time before they do something about it.

**Comment by jspenguin2017** [comment]
Well, that's after `window.hahaadblock` being called, and that never happen. The XHR that is `eval`ed is quite long, but even if I manually triggering that, it doesn't do anything. 
We'll see what to do, filtering `eval` should be a better way to handle this.

**Comment by ghajini** [comment]
hi @jspenguin2017 ,can you try on instart logic stuff....

tv.com

**Comment by jspenguin2017** [comment]
It doesn't quite work for large inline script blocks, for some reason Chromium doesn't supply `textContent`.

**Comment by jspenguin2017** [comment]
Report to uBO-Extra, there are quite a few solutions for IL there.
