### ISSUE TITLE
Please mention that its a Chrome project on the main page

### ISSUE THREAD

**Issue by davidhedlund** [jspenguin2017/uBlockProtector#441]
https://jspenguin2017.github.io/uBlockProtector/ says "You must be using Chrome and uBlock Origin to use this project.".

Can you please mention this on the main [page](https://github.com/jspenguin2017/uBlockProtector)?

**Comment by davidhedlund** [comment]
https://github.com/jspenguin2017/uBlockProtector doesn't say this is for Chrome only but if it is then please update the page and say so.

**Comment by davidhedlund** [comment]
https://jspenguin2017.github.io/uBlockProtector/ says "You must be using Chrome and uBlock Origin to use this project.".

Can you please mention this on the main [page](https://github.com/jspenguin2017/uBlockProtector)?

**Comment by lain566** [comment]
You can use uBlock Protector Extension on Firefox but not officially.

**Comment by jspenguin2017** [comment]
Hum... The repository page points to my home page, which says it is Chrome only.

**Comment by jspenguin2017** [comment]
@lain566 It's going to misbehave from time to time, I really don't recommend doing that.

**Comment by davidhedlund** [comment]
@lain566 I wonder why "uBlock Protector List​​​​​​​​​" is in uBlock Origin (under "3rd-party filters") for Firefox.

**Comment by jspenguin2017** [comment]
I think there is only one filters manifest for now, I guess it should have one for each browser. But that's not decided by me.

**Comment by lain566** [comment]
@jspenguin2017 I mean download this project as zip, and load `manifest.json` on Firefox

**Comment by jspenguin2017** [comment]
If you are a developer, the notes for extension clearly suggests it is a Chrome extension: https://github.com/jspenguin2017/uBlockProtector/blob/master/Extension%20Compiler/Extension%20Notes.MD
If you are an user, the installation instructions on my home page clearly states that it is Chrome only. 

I don't see the problem here...

**Comment by jspenguin2017** [comment]
@lain566 Firefox will inject content scripts on extension enable (but not Chrome). I assumes my content scripts will run on document-start, and I cache pointers to critical functions. If I'm not able to cache the real pointers, there can be unwanted code execution. 
Also, Firefox has broken CSP handling, so `a.inject` and `a.injectWithRuntime` will not always work. 

You can load an extension doesn't mean it will work as intended.

**Comment by davidhedlund** [comment]
@jspenguin2017 It would just be nice to read it in https://github.com/jspenguin2017/uBlockProtector too.

**Comment by jspenguin2017** [comment]
Do you have a suggested change?

**Comment by davidhedlund** [comment]
@jspenguin2017 Add "You must be using Chrome and uBlock Origin to use this project." to https://github.com/jspenguin2017/uBlockProtector

**Comment by jspenguin2017** [comment]
That's already on my home page, I think it's redundant.

**Comment by davidhedlund** [comment]
@jspenguin2017 Ok.

**Comment by ghajini** [comment]
little offtopic
how ubo extra within ublock protector updates ? do i need to use ubo extra seperately?

**Comment by jspenguin2017** [comment]
The update is somewhat manual. I have a script that pulls update from uBO-Extra. 

If it still shows then chances are the solution in uBO-Extra isn't functioning properly. I just put the uBO-Extra script at the end of my content scripts.

**Comment by uBlock-user** [comment]
what @davidhedlund is suggesting, is that you put the notice on README.md too so he and others know what they need before they click on the home page for installation instructions, which I guess will save them a click or so.

**Comment by uBlock-user** [comment]
I can't reproduce any g00 on `chowhound.com`. Loads fine for me.

**Comment by jspenguin2017** [comment]
I know what he meant, I still don't feel that's necessary.

**Comment by davidhedlund** [comment]
@jspenguin2017 Final suggestion, replace

> An anti-adblock defuser for uBlock Origin

with

> An anti-adblock defuser for uBlock Origin in Chrome.

**Comment by jspenguin2017** [comment]
I'll consider it. There are quite a few reference to that phrase it's kind of hard to change.

**Comment by davidhedlund** [comment]
@jspenguin2017 

> I'll consider it.

Thank you.

**Comment by kode54** [comment]
It seems that 20 people have voted that "Yes" the extension works with Chrome Store Foxified, while 1 person has voted "No".

The main page status check seems to detect the extension, but fails to detect the list. Apparently, that sort of injection only works in Chrome. I'm currently avoiding Chrome because of outstanding issues with my preferred web IRC client, which somehow causes the entire Chrome UI to freeze for 1-2 seconds every 5-10 seconds.

Have you investigated Firefox Quantum? Is it any better at handling WebExtensions than whatever you previously tested against? It may be worth lodging bugs against the project to see things fixed.

**Comment by jspenguin2017** [comment]
I clamped down my pages with CSP for security, I won't do that for ABR2. https://adblockprotector2.github.io/AdBlockProtector2/
OK, I'm doing it right now, but if I'm going to add installation detection then I'll lift the restriction.

**Comment by davidhedlund** [comment]
@jspenguin2017 https://xuhaiyang1234.gitlab.io/AAK-Cont/ says:

"AAK-Cont is reaching End-Of-Life. Please migrate to one of the following projects
[uBlock Protector](https://jspenguin2017.github.io/uBlockProtector/)
[AdBlock Protector 2](https://adblockprotector2.github.io/AdBlockProtector2/)"

Is uBlockProtector Firefox (Firefox 47 aka Quantum was released a while ago, it only uses WebExtension) compatible now or are you going to make it compatible?

**Comment by jspenguin2017** [comment]
It should work on Quantum 58+ for 99% of the time I'd say, although I won't officially support it. 
ABR2 will support the "big 5"... Except Safari because I don't have a mac.
