### ISSUE TITLE
gp.se

### ISSUE THREAD

**Issue by eiktyrner** [jspenguin2017/uBlockProtector#442]
### Test link (required): 
http://www.gp.se/livsstil/bostad/dramatisk-budgivning-n%C3%A4r-%C3%B6vergivna-bj%C3%B6rks%C3%A4ttra-herrg%C3%A5rd-s%C3%A5ldes-1.4477023
### Screenshot of the web page (required): 
![untitled](https://user-images.githubusercontent.com/4710252/28747673-10012b20-74a5-11e7-83f1-5251f12d0c16.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![untitled2](https://user-images.githubusercontent.com/4710252/28747674-1146896c-74a5-11e7-919f-d73e4b6ee0be.png)

### Add everything else that you believe to be useful below (optional): 
Blocks all images after the second in the image carousels if it detects adblock.

Judging by their debug output, they might be using this script http://www.speakingtree.in/detector.cms

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
Need a minimal noop tracking API to prevent the page from crashing.

**Comment by lassekongo83** [comment]
The same fix can also be applied to these sites: bohuslaningen.se, ,hallandsposten.se, hn.se, stromstadstidning.se, ttela.se

**Comment by jspenguin2017** [comment]
http://www.bohuslaningen.se/nyheter/soten%C3%A4s/full-fart-och-laser-f%C3%B6r-sommarlediga-1.4477096
http://www.hallandsposten.se/nyheter/halmstad/marknad-med-hantverk-i-l%C3%A5nga-rader-1.4490891
http://www.hn.se/nyheter/varberg/stenkul-sev%C3%A4rdhet-i-torstorps-skogar-1.4485135
http://www.stromstadstidning.se/nyheter/avliden-man-hittad-i-vattnet-vid-sydkoster-1.4490133
http://www.ttela.se/nyheter/hemmet-jag/det-st%C3%B6r-grannarna-mest-1.4479865
