### ISSUE TITLE
klartext-ne.de

### ISSUE THREAD

**Issue by fallobst22** [jspenguin2017/uBlockProtector#443]
### Test link (required): 
https://www.klartext-ne.de/

### Screenshot of the web page (required): 
http://i.imgur.com/R8Xp01T.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
http://i.imgur.com/8ykcMx4.png

**Comment by uBlock-user** [comment]
Filter - `klartext-ne.de##script:inject(bab-defuser.js)`
