### ISSUE TITLE
short.am issue

### ISSUE THREAD

**Issue by LaxusiC** [jspenguin2017/uBlockProtector#444]

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
I rather get redirected to https://linksvip.net/?link=http%3A%2F%2F4share.vn%2Ff%2F3501070c000d0606%2FDead.Island.Riptide.V1.4.1.1.13.Steamworks.And.LAN.Fix_Linkneverdie.com.rar&ref=share

**Comment by jspenguin2017** [comment]
Assuming you didn't install Extension.
