### ISSUE TITLE
linx.cloud

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#446]
### Test link (required): https://linx.cloud/suits-s07e04-divide-conquer-1080p-web-dl-6ch-x265-hevc-psa-329441/

Pop-up ads keep appearing. Tried to block some .js script but still appearing.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
Third-party popup ads from popads domains. `$csp=script-src` will be perfect for this kind of case.

**Comment by uBlock-user** [comment]
I will leave the filter for you to try - `||linx.cloud^$csp=script-src 'self' 'unsafe-inline'`

**Comment by Dibbyo456** [comment]
@jspenguin2017 still appearing.
