### ISSUE TITLE
docer.pl

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#447]
http://docer.pl/doc/vc8eee
<img width="367" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/28976691-30c8b51e-793f-11e7-8bba-40c3e1fa1c34.PNG">
<img width="722" alt="asas" src="https://user-images.githubusercontent.com/18214146/28976773-7f67c340-793f-11e7-859a-4c0a43c476aa.PNG">
I can't download the pdf file. 
The anti-adblock message appears if I click on "Pobierz plik *.pdf". 
Could you please fix it?

**Comment by uBlock-user** [comment]
http://docer.pl/static/js/utils/docer_scripts.js

**Comment by jspenguin2017** [comment]
Wow, so many debug logs and weird logic, looks like it is coded by a kid.
