### ISSUE TITLE
mitele.es

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#448]
### Test link (required): 
http://www.mitele.es
### Screenshot of the web page (required): 
![tv_online_y_series_a_la_carta_-_mitele es_-_mitele_2017-08-04_23-40-13](https://user-images.githubusercontent.com/27441315/28988549-998eec36-7970-11e7-9d95-b24062710ee5.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww mitele esestaticosa_2017-08-04_23-40-31](https://user-images.githubusercontent.com/27441315/28988556-a04ad9a4-7970-11e7-8975-0db2ce781224.png)

**Comment by jspenguin2017** [comment]
This works...

```
@@||mitele.es^$xmlhttprequest,first-party
@@||mitele.es$generichide
```

**Comment by uBlock-user** [comment]
http://www.mitele.es/scripts/scripts-2e2d0559c7.js

**Comment by uBlock-user** [comment]
It's cookie based. Blocking cookies from being created works.

**Comment by jspenguin2017** [comment]
Then you can't login, that's not good enough.

**Comment by uBlock-user** [comment]
There's the script, isn't there a way to patch it ?

**Comment by jspenguin2017** [comment]
I already patched it.

**Comment by uBlock-user** [comment]
No I meant the script, not by using `$redirect` filters.

**Comment by jspenguin2017** [comment]
It's going to be quite hard, it uses Angular framework, I guess I can filter out modules but why do that when you can just redirect the bait requests?

**Comment by uBlock-user** [comment]
They can just change file name and pick another one from Easylist in a heartbeat, we should rather make their job harder and use $redirect as the last resort.

**Comment by jspenguin2017** [comment]
And they can just recompile Angular and bypass the patch.

**Comment by uBlock-user** [comment]
not if we can break their script, which will force them to use another. I wonder if we can killing setTimeout calls would help.

**Comment by jspenguin2017** [comment]
I think the function that is passed in will be an Angular framework's function, and it'll be impossible to filter. We can try that next time if it turns out they do change their detection target.

**Comment by uBlock-user** [comment]
Somehow angular framework js is failing to load for me right now. It was working fine hours ago, yeah we will see if they change anything.

**Comment by jspenguin2017** [comment]
It still loads for me.

**Comment by lain566** [comment]
It's not working for me. Anti-adblock appears again.
Try watching this.
http://www.mitele.es/directo/telecinco

**Comment by jspenguin2017** [comment]
Fixed.

**Comment by uBlock-user** [comment]
Won't load for me for some reason. 

Offtopic - Congratulations, the extension now has 10K users!

**Comment by jspenguin2017** [comment]
Thanks...

**Comment by jspenguin2017** [comment]
I see the problem... 

```
||player.ooyala.com/*/ad-plugin/$important,script
```

**Comment by jspenguin2017** [comment]
```
||player.ooyala.com/*/ad-plugin/$important,script,badfilter
||player.ooyala.com/*/ad-plugin/$important,script,domain=~mitele.es
||player.ooyala.com/*/ad-plugin/$important,script,domain=mitele.es,redirect=noopjs
```

**Comment by lain566** [comment]
More sites with anti adblock
These pages and mitele.es belong to www.mediaset.es

http://www.telecinco.es
http://www.cuatro.com
http://www.divinity.es
http://www.factoriadeficcion.com
http://www.energytv.es
http://www.bemad.es
http://www.eltiempohoy.es
http://www.mtmad.es

**Comment by jspenguin2017** [comment]
Fixed, can you test? 

Although they might be related in some way, the solution of these domains are different from the solution for `mitele.es`.

**Comment by lain566** [comment]
I did a quick test and all seems to work fine

**Comment by jspenguin2017** [comment]
Fixed here: https://github.com/uBlockOrigin/uAssets/issues/1012

**Comment by lain566** [comment]
Isn't fixed for me
http://www.mitele.es/directo/telecinco

**Comment by jspenguin2017** [comment]
A fix landed in uAssets: https://github.com/uBlockOrigin/uAssets/commit/79bfd57ec74f22a0dfa1b1b66aea58d331790697

**Comment by ghajini** [comment]
Too much exception filters applied there

**Comment by jspenguin2017** [comment]
> @ghajini  Too much exception filters applied there

Forward your complains to gorhill.

**Comment by FPRSergio** [comment]
Mediaset has updated the anti-adblock again, it no longer works :S
