### ISSUE TITLE
diariodemallorca.es

### ISSUE THREAD

**Issue by martilucena** [jspenguin2017/uBlockProtector#449]
### Test link (required): 

http://www.diariodemallorca.es/

### Screenshot of the web page (required): 

![screenshot1](https://user-images.githubusercontent.com/30754371/28997017-ae258be6-7a0b-11e7-884e-fe9ca916a996.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![screenshot2](https://user-images.githubusercontent.com/30754371/28997067-b85fe880-7a0c-11e7-9599-41e8dad25375.png)

### Add everything else that you believe to be useful below (optional): 

When you enter http://www.diariodemallorca.es/ with an adblocker it redirects you to http://micuenta.diariodemallorca.es/prok/info2/

**Comment by jspenguin2017** [comment]
Fixed.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
http://www.diariodemallorca.es/servicios/ads/dfp.js
