### ISSUE TITLE
livenewsus.com

### ISSUE THREAD

**Issue by djc920** [jspenguin2017/uBlockProtector#451]
### Test link (required): 
http://www.livenewsus.com/tv-tokyo-live-stream/

### Screenshot of the web page (required): 
![webpage](https://user-images.githubusercontent.com/14368113/29002218-2f7b017e-7a63-11e7-9c2c-50bbe683034b.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![console](https://user-images.githubusercontent.com/14368113/29002221-35e64618-7a63-11e7-96eb-91b6f52d344f.png)

### Add everything else that you believe to be useful below (optional): 
Requires Flash player

**Comment by uBlock-user** [comment]
Embedded URL

true url - https://vaughnlive.tv/embed/video/sherming66?viewers=false&watermark=left&autoplay=false

**Comment by uBlock-user** [comment]
https://vaughnlive.tv/js/fadb.js


https://vaughnlive.tv/1502021420/js/ima3.js

**Comment by djc920** [comment]
Works now, thanks.
