### ISSUE TITLE
alein.org

### ISSUE THREAD

**Issue by Rusenche** [jspenguin2017/uBlockProtector#452]
Test link (required):
http://alein.org

Screenshot of the web page (required):
https://s2.postimg.org/owiu8n221/alein.org.png
https://s1.postimg.org/6l6anlwtr/alein.org_1.png

Screenshot of the console (press F12 to bring up the console) (required):
https://s1.postimg.org/aajagcizz/alein.org_1.png

**Comment by uBlock-user** [comment]
http://alein.org/jscript/advert.js

**Comment by jspenguin2017** [comment]
This is caught in generic anti-bait filter...
