### ISSUE TITLE
jbzdy.pl

### ISSUE THREAD

**Issue by ghajini** [jspenguin2017/uBlockProtector#456]
### Test link (required): 
https://jbzdy.pl/
### Screenshot of the web page (required): 
https://prnt.sc/g5xl5c

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://prnt.sc/g5xl9j
https://prnt.sc/g5xlem

**Comment by jspenguin2017** [comment]
Hum, the old solution broke...

**Comment by uBlock-user** [comment]
Can't reproduce.
