### ISSUE TITLE
webnovel.com

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#457]
~~https://www.webnovel.com/book/6831839002000405/21635291458627841~~
~~https://www.webnovel.com/book/6831839002000405/21635384605731094~~
They only ads-wall last two chapters, so the links gets out of date pretty quick. 

![image](https://user-images.githubusercontent.com/7283682/29141865-350490a4-7d0d-11e7-9c1f-9aad87ef8989.png)
![image](https://user-images.githubusercontent.com/7283682/29141886-45a245c8-7d0d-11e7-86a5-614286c5761b.png)

**Comment by jspenguin2017** [comment]
Uses IMA, maybe it is possible to trick the page into thinking ads just finish playing.

**Comment by jspenguin2017** [comment]
Wait that's not good, the content is cut off...

**Comment by jspenguin2017** [comment]
Make the non-working solution to be debug mode only

**Comment by jspenguin2017** [comment]
Eh... Looks like I have to do TWO XHR to get though it, if it is timed on the server side it's going to be a pain... 

```
https://www.webnovel.com/apiajax/chapter/GetChapterContentToken?_csrfToken=r6z7tgSdgp0xxPjwlfG754aHBCEfyiip8noFSdbD&bookId=6831839002000405&chapterId=21635318033737991

Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate, br
Accept-Language: en-CA
Connection: Keep-Alive
Cookie: _csrfToken=r6z7tgSdgp0xxPjwlfG754aHBCEfyiip8noFSdbD; webnovel_uuid=1502328232_1104867312; _ga=GA1.2.1093111694.1502328235; _gid=GA1.2.1848404716.1502328235; _gat=1; __gads=ID=59278c70a542df71:T=1502328234:S=ALNI_MYSfTTQaDUOUUALEqO3ZYiBGEjj6w; GED_PLAYLIST_ACTIVITY=W3sidSI6IkpzSmMiLCJ0c2wiOjE1MDIzMjgyNTcsIm52IjoxLCJ1cHQiOjE1MDIzMjgyMzMsImx0IjoxNTAyMzI4MjU3fV0.
DNT: 1
Host: www.webnovel.com
Referer: https://www.webnovel.com/book/6831839002000405/21635291458627841
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
X-Requested-With: XMLHttpRequest

Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html
Date: Thu, 10 Aug 2017 01:24:17 GMT
Request-Type: ajax
Server: nginx
Transfer-Encoding: chunked


https://www.webnovel.com/apiajax/chapter/GetChapterContentByToken?_csrfToken=r6z7tgSdgp0xxPjwlfG754aHBCEfyiip8noFSdbD&token=N((g6rUA0GxxkM_h46ux3MLwmZQCTdZSEH_yXUcoE6Y_AkoUIcSXsKFrWuK1Z2FqLs1c9T9ZJyWqdylTCXER5NLpU_oeQEzur9j5ZCrVnjbcmQGt1RWvlvQa1vj_Z_5nlMoXGBOsrEz6ClWTRPQ15IoqQ2

Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate, br
Accept-Language: en-CA
Connection: Keep-Alive
Cookie: _csrfToken=r6z7tgSdgp0xxPjwlfG754aHBCEfyiip8noFSdbD; webnovel_uuid=1502328232_1104867312; _ga=GA1.2.1093111694.1502328235; _gid=GA1.2.1848404716.1502328235; _gat=1; __gads=ID=59278c70a542df71:T=1502328234:S=ALNI_MYSfTTQaDUOUUALEqO3ZYiBGEjj6w; GED_PLAYLIST_ACTIVITY=W3sidSI6IkpzSmMiLCJ0c2wiOjE1MDIzMjgyOTIsIm52IjoxLCJ1cHQiOjE1MDIzMjgyMzMsImx0IjoxNTAyMzI4MjkxfV0.
DNT: 1
Host: www.webnovel.com
Referer: https://www.webnovel.com/book/6831839002000405/21635291458627841
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
X-Requested-With: XMLHttpRequest

Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html
Date: Thu, 10 Aug 2017 01:24:52 GMT
Request-Type: ajax
Server: nginx
Transfer-Encoding: chunked
```

**Comment by uBlock-user** [comment]
traces of anti adblock - https://www.yueimg.com/c/=/lbf/2.0.0/lib/jQuery.js,/en/js/chapter/index.bd017.js

**Comment by uBlock-user** [comment]
Also the that ad player box is mixed inside somewhere here - https://www.yueimg.com/c/=/en/js/lulu/common/Node.1afa9.js,/lbf/2.0.0/util/Cookie.js,/en/js/chapter/chapter.554c7.js,/en/js/review/index.c2b4a.js,/en/js/common/index.4c14d.js,/en/js/del/index.fa6da.js,/en/js/abuse/index.59b1f.js,/en/js/common/page/ajaxSetting.e14ce.js,/en/js/review/postChapLikeReview.8dbad.js,/en/js/common/utils/form.73694.js,/lbf/2.0.0/util/ejs2.js,/en/js/lulu/common/ui/LightTip.13225.js,/en/js/common/utils/tplExtends.cd70b.js,/en/js/common/utils/smartReply.498c7.js,/en/js/common/utils/valiReply.29fd3.js,/en/js/common/plugin/doubleScroll.8197e.js,/en/js/library/addToLibrary.c19cc.js,/en/js/library/removeFromLibrary.339d5.js,/en/js/chapter/chapterScroller.7c3f8.js,/en/js/common/utils/AdCreater.07dd7.js

**Comment by jspenguin2017** [comment]
It is using LBF (Lazy Bullet Framework?), it's something like RequireJS, which makes it really hard to tamper.

**Comment by jspenguin2017** [comment]
Seems like no way to bypass the timer, hum...

**Comment by uBlock-user** [comment]
Seems like you will have to dig deep and surgically patch it or just use those `$redirect` filters on one of those whitelists if that works.

**Comment by jspenguin2017** [comment]
It's going to be really complicate, and the timer can't be skipped anyway.

**Comment by jspenguin2017** [comment]
The potential solution is too hard to implement for what it unlocks: newest 2 chapter but still have to wait 30 seconds. Need to come up with something better...

**Comment by ghajini** [comment]
@jspenguin2017 
script=
pastebin.com/DSMJN8m3

source=
http://forum.novelupdates.com/threads/qidian-adblock.43828/

**Comment by jspenguin2017** [comment]
Oh, someone already implemented it!

**Comment by ghajini** [comment]
I tried this in violent monkey, its working correctly

**Comment by uBlock-user** [comment]
@ghajini Good find!

**Comment by uBlock-user** [comment]
@jspenguin2017 No change yet, still happens at the last two chapters!

**Comment by jspenguin2017** [comment]
I didn't push to web store

**Comment by uBlock-user** [comment]
I just got updated to 11.150. Didn't that cover in that ?

**Comment by jspenguin2017** [comment]
It's not working anyway so... I still need to debug it.
