### ISSUE TITLE
flooxer.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#460]
### Test link (required): 
http://www.flooxer.com/video/mister-jagger-fuera-homeopatia/598879c0986b2826d1ea6aa8
### Screenshot of the web page (required): 
![flooxer__jagger_y_la_homeopatia_-_google_chrome_2017-08-09_14-11-56](https://user-images.githubusercontent.com/27441315/29120970-dd54d8fa-7d0c-11e7-9fa6-22c65d7f72ff.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww flooxer comvideomis_2017-08-09_14-12-19](https://user-images.githubusercontent.com/27441315/29120975-e7975c34-7d0c-11e7-8662-3d8cd8dc5428.png)

**Comment by uBlock-user** [comment]
Anti adblock script - http://www.flooxer.com/public/js/app.footer.min.js

**Comment by uBlock-user** [comment]
They're inserting like 6 random classes from Easylist to catch the browser into the bait.
