### ISSUE TITLE
spectator.co.uk

### ISSUE THREAD

**Issue by CarlosHBC** [jspenguin2017/uBlockProtector#461]
### Test link (required): 
https://www.spectator.co.uk/2017/08/dont-forget-the-yazidis-to-avoid-the-next-genocide-remember-the-last/

### Screenshot of the web page (required):
![Image](http://i.imgur.com/pkc9RwX.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![Image](http://i.imgur.com/fyQHFfI.png)

**Comment by jspenguin2017** [comment]
Is that an anti-adblock? I get the same block screen with uBO off.

**Comment by jspenguin2017** [comment]
Tried on Edge without extension, got the same screen. This is paywall, not anti-adblock.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
You can try this - `||$third-party,script,domain=spectator.co.uk`
