### ISSUE TITLE
cwseed.com

### ISSUE THREAD

**Issue by Stariya** [jspenguin2017/uBlockProtector#462]
### Test link (required): 
http://www.cwseed.com/shows/la-rangers/once-upon-a-time-in-the-park/?play=c91e3a2f-f6fe-44cd-a937-021bd4a4ed60

### Screenshot of the web page (required): 

![screenshot 24](https://user-images.githubusercontent.com/10893571/29201610-566213f2-7e25-11e7-967a-835551b48c1f.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![screenshot 23](https://user-images.githubusercontent.com/10893571/29201614-61ce0ade-7e25-11e7-99d5-4b5e5701bdcb.png)
![screenshot 22](https://user-images.githubusercontent.com/10893571/29201616-64a319b6-7e25-11e7-93bd-5163b16ed68c.png)
![screenshot 21](https://user-images.githubusercontent.com/10893571/29201619-66958ec0-7e25-11e7-92ba-d371487039a7.png)

### Add everything else that you believe to be useful below (optional): 
The video's sound plays but there is no visual except for the ad block detected screen.

**Comment by uBlock-user** [comment]
Website is trolling me with this error in the console - Failed to load resource: the server responded with a status of 401

**Comment by jspenguin2017** [comment]
Yes, same, getting 401 from server.

**Comment by jspenguin2017** [comment]
Is there a Geo Lock? Which country are you in?

**Comment by ghajini** [comment]
united states?

**Comment by uBlock-user** [comment]
More like some kind of authentication requirement from the server, which is not met and server decides to 401 in return.

**Comment by jspenguin2017** [comment]
Tried US proxy, didn't work.

**Comment by ghajini** [comment]
just tried justproxy vpn ... new york,usa

**Comment by uBlock-user** [comment]
Thanks that extension works.

Only found this in regards to ablocking


```
function onAdBlockStart() {
--
  | if (typeof console != 'undefined') {
  | console.log("onAdBlockStart");
  | }
  | toggleAdRefresh( false );
  | }
```

**Comment by uBlock-user** [comment]
`cwseed.com##script:inject(abort-on-property-read.js, onAdCreativeStart)` that breaks it

Something to do with onAdCreativeStart

**Comment by uBlock-user** [comment]
It's inside the video player, you might have to replace the damn player.

**Comment by jspenguin2017** [comment]
Eh... I can't quite reproduce it... 
![image](https://user-images.githubusercontent.com/7283682/29251299-96628360-800f-11e7-9633-ad07fffd2871.png)

**Comment by ghajini** [comment]
ywah something changed on their side
