### ISSUE TITLE
adblocking being dmca'd

### ISSUE THREAD

**Issue by Zhangsun321** [jspenguin2017/uBlockProtector#463]
not sure if you 2 have seen this... but.. its worth noting...
https://github.com/easylist/easylist/commit/1ba8d4afeec6d562a5871fc7504c756e4b2bd5bc#diff-4903e7590de76df1abe1703921a2c88b
https://github.com/dmcahelper
https://blog.adguard.com/en/ad-blocking-is-under-attack/

**Comment by jspenguin2017** [comment]
That account is a random account registered 24 days ago, also I am not in the United States.

**Comment by uBlock-user** [comment]
That DMCA bullshit is not valid for filters and filterlists, period.

**Comment by jspenguin2017** [comment]
GitHub, like YouTube, will take down content really easily. If you wrote a two pages letter, they will take things down without thinking. And Admiral knows that, and they abuses that to get their domain unblocked. 

EasyList have many more Admiral domains blacklisted, they should have let EFF fight this...

**Comment by uBlock-user** [comment]
Github can only takedown on valid grounds of DMCA, blocking something has nothing to do with DMCA neither does any filterlists.

**Comment by uBlock-user** [comment]
If Github will does it like you said, then we will have to move to another repo which is not a sellout.

**Comment by jspenguin2017** [comment]
GitHub ToS says: 

> We do not pre-screen User-Generated Content, but we have the right (though not the obligation) to refuse or remove any User-Generated Content that, in our sole discretion, violates any GitHub terms or policies.

Which translates to they can take down anything at anytime for any reason.

**Comment by uBlock-user** [comment]
They should just start using CSP, so no $third-party domain specific filter will be needed.

**Comment by uBlock-user** [comment]
Also I love how adguard folks just stir things up and create a clickbaity blog post to help exaggerate it to the moon!

**Comment by jspenguin2017** [comment]
I'm not sure if that's a super good idea... As more advertisers will know this and start abusing DMCA. 
Maybe I should mirror important repositories just in case...

**Comment by uBlock-user** [comment]
Better make a backup on somewhere DMCA is not considered, probably a service outside housed outside of USA.

**Comment by jspenguin2017** [comment]
I'm wondering if NoAdBlock will try the same thing... I guess sooner or later I will have to move.

**Comment by ghajini** [comment]
Generic admiral defuser? Either by heuristics(what privacy badger do) or any other means........ That once you thought of making.....just spoil their business

**Comment by jspenguin2017** [comment]
That's not something to make a business out of in the first place.

**Comment by uBlock-user** [comment]
These attempts reek of desperation, which is pathetic on their part.

**Comment by jspenguin2017** [comment]
Looks good. 
![image](https://user-images.githubusercontent.com/7283682/29243503-b31eb364-7f5d-11e7-82e0-6e09d5af8592.png)

To be used as a public / internal instance I would need: 
- Another Pi
- Get email system working
- A better password
- Get another HTTPS certificate

Yea... I might not be as ready as I'd like...
