### ISSUE TITLE
tvnow.de

### ISSUE THREAD

**Issue by ghajini** [jspenguin2017/uBlockProtector#465]
### Test link (required):
https://www.tvnow.de/ntv/n-tv-dokumentation/durchblick-am-himmel-lotsen-in-aktion-2017-08-12-00-10-00/player 

### Screenshot of the web page (required): 
http://prntscr.com/g7js7y

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://streamable.com/3tbkp
### Add everything else that you believe to be useful below (optional): 
geolock= ***germany***

requires ***flash***

With default settings/(+easylist germany) you have to see preroll ads & then antiadblock doesn't appear.....

but if i block those preroll ads with following rules( ***or whatever custom rules to block preroll ads***) antiadblock displays( so it seems antiadblock is inside player)
`||ais.tvnow.de/crossdomain.xml$object,domain=www.tvnow.de,important`
`||ssl.*.damoh.tvnow.de/*/*$object,domain=www.tvnow.de,important`

easylist germany doesn't seem to have solution for that neither ublock origin(thread is opened in uassets for long time)

**Comment by ghajini** [comment]
these 2 scripts check for adblock
https://cdn.static-fra.de/tvnow/app/aaea358e.main.js
https://cdn.static-fra.de/tvnow/app/7803d699.angular.js

**Comment by jspenguin2017** [comment]
`damoh`? Huh, that sounds familiar...

**Comment by jspenguin2017** [comment]
Can't reproduce preroll: 
![image](https://user-images.githubusercontent.com/7283682/29244905-f037ec18-7f83-11e7-991c-4422d72501fc.png)

**Comment by ghajini** [comment]
I can reproduce preroll ads.....with default settings and NO custom rules at all......

https://streamable.com/rdnxa

**Comment by jspenguin2017** [comment]
Try the standard settings? https://github.com/jspenguin2017/uBlockProtector/blob/master/Notes/Standard%20Configuration.MD

**Comment by ghajini** [comment]
Yes iam on default settings, I shown in video that iam on that.......no custom rules at all

**Comment by ghajini** [comment]
Why iam only suffering......Can I get your help @uBlock-user....

**Comment by jspenguin2017** [comment]
Still can't reproduce...

**Comment by uBlock-user** [comment]
I can't help here, I'm on Chromium so NO FLASH!

**Comment by ghajini** [comment]
Can you try another VPN other than tunnel bear.....i tried tunnelbear but it has some problems (like this site still shows iam out of Germany)

**Comment by ghajini** [comment]
@jspenguin2017 , after clicking on preroll ads,these are doubleclick ads??
iam using justproxy vpn...

**Comment by jspenguin2017** [comment]
Don't know. I don't see any ads.

**Comment by ghajini** [comment]
this extension actually working.....
https://chrome.google.com/webstore/detail/tv-now-adblock-werbefreie/kpmcfodpngaecgfkmpjfiicfppkojcjf

**Comment by jspenguin2017** [comment]
Is it open source?

**Comment by ghajini** [comment]
don't know bro....

**Comment by jspenguin2017** [comment]
But uBlock Origin works too.

**Comment by ghajini** [comment]
nope bro...there's already thread opened long ago....
https://github.com/uBlockOrigin/uAssets/issues/1

also adguard...
https://github.com/AdguardTeam/AdguardFilters/issues/1834

replace rule for preroll ads in adguard....
guess you try justproxy vpn, you will reproduce
sorry iam too much...

**Comment by jspenguin2017** [comment]
Can't reproduce. I can play the video just fine, without any preroll. 
![image](https://user-images.githubusercontent.com/7283682/29281356-f8aeee42-80db-11e7-8d1b-9c46c00ea413.png)

**Comment by jspenguin2017** [comment]
If you see ads with that VPN app, are you sure it is not inserted by the VPN?

**Comment by ghajini** [comment]
How can I try tunnelbear.....I don't have credentials

**Comment by jspenguin2017** [comment]
You can register an account if you want...

**Comment by ghajini** [comment]
tunnelbear act weirdly
https://streamable.com/2qgqz

i will use that app i mentioned,tht still works

**Comment by jspenguin2017** [comment]
Something is wrong with your configuration, works perfectly for me.

**Comment by ghajini** [comment]
now i reset my settings to default as per your criteria....
iam using vyprvpn for windows>(germany)
https://streamable.com/j7lwc
iam not lying bro,trust me

**Comment by jspenguin2017** [comment]
I'm not saying you are lying, I'm saying that your config is off, or maybe something else is off. Either way, I can't fix it unless I can reproduce it.

**Comment by ghajini** [comment]
fixed as per https://github.com/jspenguin2017/uBlockProtector/issues/476
so you can now remove ''Cannot Reproduce'' label
