### ISSUE TITLE
sportspyder.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#467]
### Test link (required): 
http://sportspyder.com/
### Screenshot of the web page (required): 
![sports_news _tweets _rumors_and_articles__sportsp_2017-08-12_21-23-38](https://user-images.githubusercontent.com/27441315/29243670-e46e66ac-7fa4-11e7-8b3b-fab370bde499.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpsportspyder com_2017-08-12_21-23-52](https://user-images.githubusercontent.com/27441315/29243674-ee44fec0-7fa4-11e7-90d3-dfe661d2d4f1.png)

**Comment by uBlock-user** [comment]
Script is inline. Blowing the function itself breaks it - `sportspyder.com##script:inject(abort-on-property-read.js, BlockerChecker)`

**Comment by lain566** [comment]
Search box does not work

**Comment by uBlock-user** [comment]
`$badfilter` that rule then
