### ISSUE TITLE
diffnow.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#469]
### Test link (required): 
https://diffnow.com/
### Screenshot of the web page (required): 
![diffnow_-_compare_files_online _powered_by_examdif_2017-08-13_13-01-51](https://user-images.githubusercontent.com/27441315/29249045-aac76b8c-8027-11e7-8580-9a31f4a32067.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww diffnow com_2017-08-13_13-02-08](https://user-images.githubusercontent.com/27441315/29249047-af1e99b2-8027-11e7-893d-66e70c865604.png)

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
`diffnow.com###adblockBanner`
