### ISSUE TITLE
halamadrid.pl

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#470]
### Test link (required): 
http://www.halamadrid.pl/
### Screenshot of the web page (required): 
![halamadrid pl_-_serwis_o_realu_madryt_-_google_chr_2017-08-13_13-04-02](https://user-images.githubusercontent.com/27441315/29249058-fef12234-8027-11e7-9956-c4a869b3d32e.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww halamadrid pl_2017-08-13_13-04-12](https://user-images.githubusercontent.com/27441315/29249059-070b2154-8028-11e7-8095-4ad0bc9493d7.png)

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
`halamadrid.pl##script:inject(setTimeout-defuser.js, an_state)`
