### ISSUE TITLE
nbcsports.com

### ISSUE THREAD

**Issue by MTWomg** [jspenguin2017/uBlockProtector#471]
### Add everything else that you believe to be useful below (optional): 

NBC Sports has some nasty anti-adblock BS on their live stream pages. Go to any live NBC Sports stream page and you will get prompted with it. I am not sure if you need a US TV subscription to view these pages or not, if you do I can provide one.

There was a previous issue with this that was closed as solved a while ago. NBC must have changed something, because the anti-adblock is working again.

**Comment by jspenguin2017** [comment]
I need a test account... Open an issue in the GitLab issue tracker. 
![image](https://user-images.githubusercontent.com/7283682/29252422-4a9326e6-8024-11e7-8e55-ec360ff1f443.png)

**Comment by MTWomg** [comment]
Done!

**Comment by uBlock-user** [comment]
Already posted https://github.com/jspenguin2017/uBlockProtector/issues/380

**Comment by jspenguin2017** [comment]
Does v11.65 works?

**Comment by MTWomg** [comment]
Checking now.

**Comment by MTWomg** [comment]
Appears to be working. Would like to wait for someone else to test to be sure, but it appears to be working on my end.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
Old solution still working!

**Comment by MTWomg** [comment]
Are you trying to view live video? The old solution worked for me for the replays, but the live video pages did not.

**Comment by uBlock-user** [comment]
@MTWomg link for live videos ?

**Comment by MTWomg** [comment]
http://stream.nbcsports.com/nbc/?pid=34757

**Comment by uBlock-user** [comment]
Requires flash player

```
You currently do not have the latest version of Adobe Flash Player installed.
You will need Flash Player 19.0.0.245 or higher in order to view this site.

Get the latest version of Flash Player
```

**Comment by MTWomg** [comment]
Yep. You will have to enable flash to view that page.

**Comment by uBlock-user** [comment]
Can't do that. I'm on Chromium, which doesn't come with Flash installed. I will leave @jspenguin2017 to further on his own.

**Comment by jspenguin2017** [comment]
What needs to be investigated?

**Comment by jspenguin2017** [comment]
@lain566 Can you show a screenshot?

**Comment by lain566** [comment]
@jspenguin2017 It may just be me.

![nbc_sports_-_google_chrome_2017-09-24_15-37-25](https://user-images.githubusercontent.com/27441315/30783129-5125bdf8-a13e-11e7-87a3-663fce5acd03.png)

![developer_tools_-_httpstream nbcsports comnbc_2017-09-24_15-36-25](https://user-images.githubusercontent.com/27441315/30783132-56c87458-a13e-11e7-8807-aa3525119931.png)

**Comment by jspenguin2017** [comment]
OK, I see. Fixed.

**Comment by spinxxy** [comment]
May be broken again...

Test Link (or any live event): http://stream.nbcsports.com/nbcsn/generic?pid=37518

![image](https://user-images.githubusercontent.com/32970984/31845612-766f4fb0-b5b7-11e7-9332-3f7064446e4f.png)

![image](https://user-images.githubusercontent.com/32970984/31845729-f32ef1b2-b5b8-11e7-8b51-254802f2aa7b.png)

**Comment by jspenguin2017** [comment]
I can't seem to reproduce... Might need a test account, open a confidential issue on GitLab if you are still experiencing the problem.

**Comment by spinxxy** [comment]
Confidential issue opened.
