### ISSUE TITLE
scambieuropei.info

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#473]
http://www.scambieuropei.info/
<img width="477" alt="przechwytywanie2" src="https://user-images.githubusercontent.com/18214146/29315237-6710ba50-81c2-11e7-8f7a-7e104088f7d4.PNG">
<img width="599" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/29315248-6b9b1566-81c2-11e7-9780-86516ab57ba3.PNG">

**Comment by uBlock-user** [comment]
http://www.scambieuropei.info/wp-content/uploads/ElcGdJQunzQQ/FFFnKsayXhAb.js?ver=2.2.1

**Comment by uBlock-user** [comment]
`scambieuropei.info##script:inject(abort-on-property-read.js, anOptions)`
