### ISSUE TITLE
acquavivalive.it

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#474]
http://www.acquavivalive.it/news/attualita/515428/marco-piconio-trasferito-presso-lufficio-tecnico
<img width="263" alt="przechwytywaniefedfef" src="https://user-images.githubusercontent.com/18214146/29315477-bbade816-81c3-11e7-99da-e63473eb4afc.PNG">
<img width="557" alt="wwqwqw" src="https://user-images.githubusercontent.com/18214146/29315482-c14bbfe6-81c3-11e7-8721-9e61becb5259.PNG">
Related websites:
http://www.palolive.it/news/cronaca/515447/auto-in-fiamme-nella-notte-in-via-focarazzo
http://www.molfettalive.it/news/attualita/515621/uninstallazione-video-per-raccontare-molfetta

**Comment by uBlock-user** [comment]
http://www.acquavivalive.it/TemplateLive/app/assets/js/ads.js

Patch it via ads.js v2

**Comment by uBlock-user** [comment]
anti adblock script http://www.acquavivalive.it/TemplateLive/app/assets/js/app.min-55.js

**Comment by uBlock-user** [comment]
Same anti adblock script for other two domains as well.

**Comment by adreporter** [comment]
@jspenguin2017 On the related websites
http://www.palolive.it/news/cronaca/515447/auto-in-fiamme-nella-notte-in-via-focarazzo
http://www.molfettalive.it/news/attualita/515621/uninstallazione-video-per-raccontare-molfetta
there are still the anti-adblock messages. Can you confirm it?

**Comment by jspenguin2017** [comment]
Yep, I'll do that. Getting my Linode instance up is top priority now.
