### ISSUE TITLE
knowyourmeme.com

### ISSUE THREAD

**Issue by SomeGuyNamedDavid** [jspenguin2017/uBlockProtector#475]
### Test link: http://knowyourmeme.com/photos/trending

Site has implemented an anti-adblock warning that is not currently handled by any of the anti-adblock filters. Removing the overlay is not enough, as the webpage will not scroll. Disabling inline scripts is too much, as this causes significant errors on some pages, such as in the test link. When these errors occur, scrolling further down the page will not load thumbnails for any additional images, and causes problems for the overlay which appears when images are clicked on. (The anti-adblock warning appears on all pages in the domain, but the test link is a page where removing inline scripts will break the page in addition to removing the warning.)

### Screenshot of the console: http://i.imgur.com/h8tDkgd.png

**Comment by jspenguin2017** [comment]
API server is down... The build may be stuck for a while.

**Comment by uBlock-user** [comment]
aa script - http://a.kym-cdn.com/assets/application-3e625eb1217ff7d986acd46782b5e6fa.js
