### ISSUE TITLE
aftonbladet.se

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#479]
https://www.aftonbladet.se/sportbladet/a/WVn72/spar-av-cannabis-i-woods-system

![image](https://user-images.githubusercontent.com/7283682/29424345-95bbd7c4-833c-11e7-8c6f-272b07b45789.png)
![image](https://user-images.githubusercontent.com/7283682/29424352-9f1aa052-833c-11e7-945f-253f96dbd832.png)

**Comment by ghajini** [comment]
that notice is geolock-sweden and not antiadblock
![chrome_2017-08-17_22-51-48](https://user-images.githubusercontent.com/20338483/29424859-de9b76f4-839e-11e7-8226-9647de94d682.png)

**Comment by jspenguin2017** [comment]
Yep, you are right. 

![image](https://user-images.githubusercontent.com/7283682/29439375-68d67118-837a-11e7-8128-c44eebbf8cc4.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
