### ISSUE TITLE
not an issue- enhancement

### ISSUE THREAD

**Issue by ghajini** [jspenguin2017/uBlockProtector#481]
regarding opening ublock protector page on ***reddit***....so that more users can know about ublock protector and report issues there.....this can result in more reach of ublock protector

also on wildersecurity forum...

**Comment by jspenguin2017** [comment]
The problem with open forum with little to no rule is that many users will ask for expanding supported setup, I used to have an open message board, but it is filled with spam about Adblock Plus being not supported.

**Comment by ghajini** [comment]
You can attach instructions on reddit page that its only for ublock origin and chrome....

**Comment by jspenguin2017** [comment]
Yea... I guess that would help a bit. 
But then people will be reporting issues to the Reddit page, and not following the template.

**Comment by jspenguin2017** [comment]
I don't want to deal with that, I want to keep things in the same place and I want people to follow my rules.

**Comment by uBlock-user** [comment]
From what I have seen, the more you expand and offer, the more in the ass it becomes.

**Comment by ghajini** [comment]
May be open page on reddit and avoid those issues which aren't reproducible on standard setup...

**Comment by jspenguin2017** [comment]
But I would still need to test every link that pops up, and if I open a page on Reddit, chances are it is going to turn into a crappy issues tracker pretty quick. 
I don't think opening a Reddit page is a good idea, not for this project at least.

**Comment by ghajini** [comment]
is this possible?
https://www.reddit.com/r/uBlockOrigin/comments/6xbspz/can_we_make_getcomputedstyle_not_reveal_our/

**Comment by jspenguin2017** [comment]
It should be possible.

**Comment by ghajini** [comment]
can you add that to ublock protector?

gorhill has no comment on that ,so might not be interested in that?

**Comment by jspenguin2017** [comment]
But how do I know if an element is hidden by uBO? And currently uBO injects style right onto the element which reveals everything anyway. Need to wait until user stylesheet is implemented.

**Comment by ghajini** [comment]
uBO injects `display:none` style right onto the element which reveals everything anyway
> @gorhill, do we have your opinion on this?
https://www.reddit.com/r/uBlockOrigin/comments/6xbspz/can_we_make_getcomputedstyle_not_reveal_our/
