### ISSUE TITLE
qoshe.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#482]
http://qoshe.com/hurriyet-daily-news/murat-yetkin/turkey-iran-rapprochement-and-possible-consequence/1461793
<img width="226" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/29469210-911a4fe6-8447-11e7-878e-bb8a009c3164.PNG">
<img width="960" alt="dsds" src="https://user-images.githubusercontent.com/18214146/29469215-945aeb02-8447-11e7-806b-2f89ee71bc8d.PNG">
If the anti-adblock message doesn't show up, you have to delete the site cookies and cache. It disappears if I add these rules into uBlock Origin: `qoshe.com###alertContainer` and `qoshe.com###alertOverlay`

**Comment by uBlock-user** [comment]
Anti adblock script

http://qoshe.com/js/MjAxNi9qcXVlcnktMi4yLjMubWluLDIwMTYvanFhZGQsMjAxNi9tYXNvbnJ5LjMuMy4yLm1pbiwyMDE2L21haW4uY29tcHJlc3NlZA==,q201703091812.pagespeed.jm.WTX78jX_8W.js

**Comment by uBlock-user** [comment]
`qoshe.com##script:inject(abort-on-property-read.js, adBlockFunction)`

**Comment by jspenguin2017** [comment]
Won't that noop the whole script?

**Comment by uBlock-user** [comment]
No, not the whole script, adblockFunction comes pretty late into the script, so partially yeah. Actually the entire script is for anti adblock only and I don't see anything being broke.

**Comment by jspenguin2017** [comment]
Not quite, it is function declaration, and declarations run first, which will stop the script in declaration phase.

**Comment by uBlock-user** [comment]
So does it break anything ?

**Comment by jspenguin2017** [comment]
Don't know, I fixed it in another way.
