### ISSUE TITLE
aargauerzeitung.ch 

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#484]
https://www.aargauerzeitung.ch/aargau/kanton-aargau/nach-den-anschlaegen-in-spanien-so-schaetzt-der-badener-polizeichef-die-sicherheitslage-ein-131623681

![1](https://user-images.githubusercontent.com/31142317/29475861-debda3c8-8461-11e7-998e-71c8789564b3.png)
![2](https://user-images.githubusercontent.com/31142317/29475909-01a2cb3e-8462-11e7-8c69-9ff4a53938e3.png)

**Comment by uBlock-user** [comment]
https://www.aargauerzeitung.ch/__node__/0.39.1/__static__/client/nwch.bundled.js

**Comment by uBlock-user** [comment]
`aargauerzeitung.ch##script:inject(setTimeout-defuser.js, [native code])`
