### ISSUE TITLE
androidemulator.in

### ISSUE THREAD

**Issue by easterneas** [jspenguin2017/uBlockProtector#485]
### Test link:
https://androidemulator.in/updates/nox-app-player-v5-0-0-0-released/

### Screenshot of the web page:
![image](https://user-images.githubusercontent.com/31128200/29486132-53bed6b8-8509-11e7-8711-dd72c2470fd4.png)

### Screenshot of the console: 
![image](https://user-images.githubusercontent.com/31128200/29486150-b8ba8896-8509-11e7-9ca9-fb10bb65a769.png)

### Some useful info: 
It seems like the blocked page is using BlockAdBlock script (which is disguised as a bitly text link --> http://bit.ly/2uKG2NU; <-- on the lower-left corner when I clicked that text), but it's weird, considering UBP blocks script from BAB as I followed in the example, but on this site, the script runs well.

**Comment by uBlock-user** [comment]
add - `androidemulator.in##script:inject(bab-defuser.js)`
