### ISSUE TITLE
games.nydailynews.com and similar domains

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#487]
http://games.nydailynews.com/games/premier-crossword/
<img width="450" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/29489582-a8b24414-8524-11e7-9477-fab3b5355598.PNG">
<img width="960" alt="przechwytywanie2" src="https://user-images.githubusercontent.com/18214146/29489584-abdbd36c-8524-11e7-8090-48b66756fee2.PNG">
Related websites:
http://games.express.co.uk/games/jigsaw/
http://puzzles.independent.co.uk/games/concise-crossword-independent?puzzleDate=20170819#!201701
http://games.orlandosentinel.com/games/daily-jumble/
http://puzzles.standard.co.uk/games/easy-crossword-eveningstandard/?puzzleDate=20170819#!201701
http://games.parade.com/games/mahjongg-solitaire/
http://games.baltimoresun.com/games/crosswords-jumble/
http://games.mcall.com/games/daily-jumble/
http://games.somersetlive.co.uk/games/premier-crossword/

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by adreporter** [comment]
@jspenguin2017 Another similar domain
http://puzzles.bestforpuzzles.com/games/daily-american-crossword/#!201708

**Comment by adreporter** [comment]
@jspenguin2017 Other similar domains
http://games.sun-sentinel.com/games/daily-jumble/
http://games.reviewjournal.com/games/mine-sweeper/
http://games.dailypress.com/games/daily-jumble/
http://puzzles.bestforpuzzles.com/games/daily-american-crossword/#!201708
http://games.sandiegouniontribune.com/games/jumble-kids/
http://games.charlotteobserver.com/games/premier-crossword/
http://games.chicagotribune.com/games/daily-jumble/
