### ISSUE TITLE
ohmymag.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#488]
http://www.ohmymag.de/neuigkeiten/das-bild-dieser-frau-im-bikini-geht-aufgrund-eines-kleinen-details-um-die-welt-findest-du-es_art6880.html

![1](https://user-images.githubusercontent.com/31142317/29494981-ce17d19c-85b5-11e7-94b4-4f908317306e.png)
![2](https://user-images.githubusercontent.com/31142317/29494982-d0884ede-85b5-11e7-8753-5cc9a11ebd70.png)

**Comment by ghajini** [comment]
`@@||www.ohmymag.de/jsad/advertisement.js$xmlhttprequest,domain=www.ohmymag.de`

**Comment by jspenguin2017** [comment]
Removed misleading filter.

**Comment by uBlock-user** [comment]
Was there domain there before or did they bought another one ?

**Comment by jspenguin2017** [comment]
It's another one.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by ghajini** [comment]
sorry iam very sorry.......................
