### ISSUE TITLE
przegladsportowy.pl

### ISSUE THREAD

**Issue by HateAds** [jspenguin2017/uBlockProtector#489]
http://www.przegladsportowy.pl/
![image](https://user-images.githubusercontent.com/29756590/29496855-805143dc-85db-11e7-8e16-c5cf80416bb7.png)

![image](https://user-images.githubusercontent.com/29756590/29496858-bfb37428-85db-11e7-935d-3fbd5f90b802.png)

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
Can't reproduce.

**Comment by StreamXL** [comment]
**The same goes for me**

![w](https://user-images.githubusercontent.com/31142317/29497502-fe327c82-85e8-11e7-8838-362dd1accfb9.png)

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/29497596-047d6c0a-85a8-11e7-8d8f-aa8dbf5868b1.png)
