### ISSUE TITLE
badenertagblatt.ch and similar domains

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#490]
1
https://www.badenertagblatt.ch/sport/aargau/weiterhin-ohne-sieg-der-fc-aarau-verliert-nach-einer-schwachen-leistung-gegen-vaduz-mit-02-131629524
2
https://www.basellandschaftlichezeitung.ch/sport/basel/nach-spaetem-gegentor-der-fc-basel-spielt-zu-hause-gegen-lugano-nur-11-unentschieden-131629557
3
https://www.bzbasel.ch/sport/basel/nach-spaetem-gegentor-der-fc-basel-spielt-zu-hause-gegen-lugano-nur-11-unentschieden-131629557
4
https://www.limmattalerzeitung.ch/limmattal/zuerich/unbekannte-beschaedigen-in-zuerich-altstetten-rund-40-gartenhaeuschen-131630481
5
https://www.solothurnerzeitung.ch/solothurn/thal-gaeu/anno-1375-soeldner-unter-franzoesischer-fahne-auf-verwuestungstour-im-gaeu-131624739
6
https://www.grenchnertagblatt.ch/solothurn/thal-gaeu/anno-1375-soeldner-unter-franzoesischer-fahne-auf-verwuestungstour-im-gaeu-131624739
7
https://www.oltnertagblatt.ch/solothurn/thal-gaeu/anno-1375-soeldner-unter-franzoesischer-fahne-auf-verwuestungstour-im-gaeu-131624739

![1](https://user-images.githubusercontent.com/31142317/29497049-e75c6458-85e0-11e7-9830-7393f219d155.png)
![2](https://user-images.githubusercontent.com/31142317/29497050-ea136520-85e0-11e7-9a04-424c5db8b292.png)

**Comment by uBlock-user** [comment]
https://www.badenertagblatt.ch/__node__/0.39.1/__static__/client/nwch.bundled.js

**Comment by uBlock-user** [comment]
same as https://github.com/jspenguin2017/uBlockProtector/issues/484

**Comment by uBlock-user** [comment]
`badenertagblatt.ch##script:inject(setTimeout-defuser.js, [native code])`

**Comment by StreamXL** [comment]
Yes is the same recognition the company use the on all sides
