### ISSUE TITLE
televisa.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#491]
### Test link (required): 
http://www.televisa.com/
### Screenshot of the web page (required): 
![televisa com__sitio_oficial_de_televisa_-_google__2017-08-20_20-29-59](https://user-images.githubusercontent.com/27441315/29497361-cfcdee3c-85e6-11e7-8e07-0085572dc3c0.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww televisa com_2017-08-20_20-30-16](https://user-images.githubusercontent.com/27441315/29497363-db7b8776-85e6-11e7-974d-f7f7c3d2d243.png)

**Comment by uBlock-user** [comment]
http://i2.esmas.com/wp/assets/js/adblock/kw-pqr.js
http://i2.esmas.com/wp/assets/js/adblock/kw-pqr_.js

Just block the entire `adblock` folder.

**Comment by lain566** [comment]
Same filter for this site
http://www.lasestrellas.tv/telenovelas/la-piloto/
