### ISSUE TITLE
windowstechinfo.com

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#493]
http://www.windowstechinfo.com/

![1](https://user-images.githubusercontent.com/31142317/29497696-f59d7bc2-85ec-11e7-98ff-b0e3f40ed7e7.png)
![2](https://user-images.githubusercontent.com/31142317/29497697-f5bc6de8-85ec-11e7-9dba-6ee815ef77b8.png)

**Comment by uBlock-user** [comment]
seen this `Alobaidi` shit before, can't find the case here!
