### ISSUE TITLE
vod.pl

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#494]
https://vod.pl/seriale/wmiksowani-online-za-darmo/dtc5g1b

![1](https://user-images.githubusercontent.com/31142317/29497969-d92ce83c-85f2-11e7-8251-4fc9b8a88ad4.png)
![2](https://user-images.githubusercontent.com/31142317/29497970-d93289ea-85f2-11e7-8d5f-c453fe363800.png)

**Comment by jspenguin2017** [comment]
Can't reproduce: 
![image](https://user-images.githubusercontent.com/7283682/29497979-f11397ea-85af-11e7-9180-834b5306404f.png)

**Comment by StreamXL** [comment]
This is very funny, that is already the 2 side. something is not correct

**Comment by StreamXL** [comment]
**UBlock Protector** _turned off_
The page works

**Comment by jspenguin2017** [comment]
How does your setup differ from the [standard setup](https://github.com/jspenguin2017/uBlockProtector/blob/master/Notes/Standard%20Configuration.MD) ?

**Comment by lain566** [comment]
I can reproduce only if I delete cookies and refresh the page

**Comment by jspenguin2017** [comment]
Hum, was able to reproduce once...

**Comment by uBlock-user** [comment]
wasn't this patched already with other .pl group domains ?

**Comment by HateAds** [comment]
@jspenguin2017
The video doesn't load when uBlock Protector Extension is enabled.

**Comment by jspenguin2017** [comment]
@uBlock-user What was the patch? 

@HateAds It should be fixed now.

**Comment by jspenguin2017** [comment]
Something isn't working correctly with GitHub, `git remote prune origin` was hanging, and now pipeline is stuck.

**Comment by uBlock-user** [comment]
I can't find the case, must have been another .pl domain I suppose.
