### ISSUE TITLE
bildungsspender.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#495]
https://www.bildungsspender.de/bildungsspender/shopping?shop=4f055b00f537dad976c5c4c34c3745ad&org_id=999999999&from_topshops=1

![1](https://user-images.githubusercontent.com/31142317/29529045-787c1ca4-869e-11e7-81f8-c4156b3a3341.png)
![2](https://user-images.githubusercontent.com/31142317/29529044-7875db64-869e-11e7-83fc-b0f4ffbea1cd.png)

**Comment by uBlock-user** [comment]
bait https://www.bildungsspender.de/banner/ads/adserver/click/ad.js

**Comment by uBlock-user** [comment]
`bildungsspender.de##script:inject(abort-on-property-read.js, zeigemeldung)`
