### ISSUE TITLE
tvnow.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#496]
https://www.tvnow.de

full blocked

![1](https://user-images.githubusercontent.com/31142317/29529616-af71cbf8-86a0-11e7-9802-91dd307ea025.png)
![2](https://user-images.githubusercontent.com/31142317/29529617-af8c695e-86a0-11e7-8f31-04b254e3c14d.png)

**Comment by uBlock-user** [comment]
https://github.com/jspenguin2017/uBlockProtector/issues/476

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/29529728-11ffb020-865e-11e7-861d-eb93fa33cd75.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
