### ISSUE TITLE
watson.ch

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#497]
http://www.watson.ch/

![1](https://user-images.githubusercontent.com/31142317/29529811-6e295034-86a1-11e7-9d47-b437fe064797.png)
![2](https://user-images.githubusercontent.com/31142317/29529812-6e455040-86a1-11e7-858d-86aa1e9d7fa2.png)

**Comment by uBlock-user** [comment]
`watson.ch##.adget`
