### ISSUE TITLE
sledujserialy.sk

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#499]
http://sledujserialy.sk/episode/hello-goodbye-1503332238

![1](https://user-images.githubusercontent.com/31142317/29535742-590916fc-86bb-11e7-94a6-36c7d82af918.png)
![2](https://user-images.githubusercontent.com/31142317/29535744-5926294a-86bb-11e7-948c-aa16ba19b38c.png)

**Comment by StreamXL** [comment]
Error: Movies can not be played.
SCRIPT BLOCKED

**Comment by StreamXL** [comment]
![w](https://user-images.githubusercontent.com/31142317/29537593-9430ef1e-86c2-11e7-8bd6-052f0a2af0f8.png)

**Comment by jspenguin2017** [comment]
Can you explain the problem better? I don't understand what you are trying to say.

**Comment by StreamXL** [comment]
The FILMS DO NOT PLAY, they are blocked Through a script.
It is not geoblocking

**Comment by jspenguin2017** [comment]
Looks like Geo Lock to me, I see the same thing with uBO off: 
![image](https://user-images.githubusercontent.com/7283682/29538659-0288f784-8684-11e7-8aaa-b9ca28665284.png)

**Comment by jspenguin2017** [comment]
What you shown on that screenshot is Flash being blocked by Chromium, nothing to do with ads blocking.

**Comment by StreamXL** [comment]
alright thanks

**Comment by uBlock-user** [comment]
Flash is turned off by default in Chrome. You will have to turn it on.

**Comment by lain566** [comment]
@jspenguin2017 Openload player is blocked, can you take a look?
You can only see it using a vpn from Slovakia.

Test link
`http://sledujserialy.sk/episode/curious-george-beats-the-band-hats-and-a-hole`

**Comment by jspenguin2017** [comment]
I'll have a look tonight.

**Comment by jspenguin2017** [comment]
Fixed.

**Comment by djlimix** [comment]
The script is blocking Openload source, because you can't use Adblock while not having premium account :)

**Comment by jspenguin2017** [comment]
Yea, it broke. 
https://github.com/NanoMeow/QuickReports/issues/344#issuecomment-456637557

**Comment by jspenguin2017** [comment]
OK. Track it here: https://github.com/NanoMeow/QuickReports/issues/344#issuecomment-456637557
