### ISSUE TITLE
sledujufilmy.cz

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#500]
https://sledujufilmy.cz/kategorie/dobroudruzny/6/

![1](https://user-images.githubusercontent.com/31142317/29536369-d595e9dc-86bd-11e7-8a05-4f5b49eaf079.png)
![2](https://user-images.githubusercontent.com/31142317/29536370-d5b4d8d8-86bd-11e7-8286-ae39059eef4b.png)

**Comment by uBlock-user** [comment]
bait - https://sledujufilmy.cz/js/ads.js

**Comment by uBlock-user** [comment]
```
sledujufilmy.cz##script:inject(abort-on-property-read.js, ads_ok)
sledujufilmy.cz##.ads-position
sledujufilmy.cz##.bottom-advert
```
