### ISSUE TITLE
9anime.to

### ISSUE THREAD

**Issue by weeb312** [jspenguin2017/uBlockProtector#501]
[https://9anime.to/watch/isekai-shokudou.r6mp/l12606](https://9anime.to/watch/isekai-shokudou.r6mp/l12606)

<img width="960" alt="issue" src="https://user-images.githubusercontent.com/31227404/29543772-81df3822-86b1-11e7-88da-678abfac6254.PNG">

<img width="959" alt="issue3" src="https://user-images.githubusercontent.com/31227404/29544189-6305495c-86b4-11e7-933e-1f5940caaef4.PNG">

<img width="960" alt="issue2" src="https://user-images.githubusercontent.com/31227404/29544191-68fffec4-86b4-11e7-9801-aae87407f304.PNG">

The episode does not play when clicking another episode button and reverts to a message box stating the user must disable his/her adblock. (i.e. press the link, then press [002] in the Server F4 line can create this event.) At first, the video appears to be playable until trying to go on to another one.

**Comment by jspenguin2017** [comment]
Works for me. Are everything up to date on your side?

**Comment by weeb312** [comment]
The video appears to be working at first, but as stated before when clicking another episode button the message dialog pops up.

**Comment by weeb312** [comment]
I updated the screenshots with more of the console chain.

**Comment by weeb312** [comment]
Are you able to reproduce the event?

**Comment by jspenguin2017** [comment]
I clicked another button, still works.

**Comment by weeb312** [comment]
I apologize. I just realized I accidentally still had another anti-adblock list on and it appears shutting that down fixed the issue.

Thanks for your help!

**Comment by uBlock-user** [comment]
I could reproduce too!

`@@||9anime.*^$elemhide` works for me.

**Comment by jspenguin2017** [comment]
I can't reproduce after my fix earlier.

**Comment by uBlock-user** [comment]
That's because you don't have additional filter lists apart from the std setup. The detection is done through checking insertion of generic elements and in my and others case here, they got caught in the bait, that's why the anti adblock script was triggering. By turning off the generic elements, it didn't trigger anymore.
