### ISSUE TITLE
insurancenewsnet.com, advisornews.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#503]
https://insurancenewsnet.com/innarticle/d2c-lead-gen-pose-digital-challenges-insurers
<img width="297" alt="przechwytywanie2" src="https://user-images.githubusercontent.com/18214146/29560977-16306b9a-8734-11e7-8e41-74251ec6bbc6.PNG">
<img width="960" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/29560979-186f56d2-8734-11e7-82e8-e10b6e1ef2ad.PNG">
Related website:
https://advisornews.com/oarticle/100-year-study-stock-market-crash-risk-high

**Comment by uBlock-user** [comment]
script https://insurancenewsnet.com/wp-content/plugins/inn-anti-adblock/index.js?ver=1.0.0

**Comment by uBlock-user** [comment]
`insurancenewsnet.com##script:inject(abort-on-property-read.js, adblock_detect)`

**Comment by uBlock-user** [comment]
same solution for `advisornews.com`
