### ISSUE TITLE
mmorpgitalia.it

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#504]
https://www.mmorpgitalia.it/

![1](https://user-images.githubusercontent.com/31142317/29575657-7a4acf5e-8765-11e7-904e-95ba0fcdb917.png)
![2](https://user-images.githubusercontent.com/31142317/29575658-7a6854c0-8765-11e7-8074-60472e5d91b6.png)

**Comment by uBlock-user** [comment]
`mmorpgitalia.it##.noticeContainer`
