### ISSUE TITLE
mmovie.it

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#505]
https://www.mmovie.it/cinema/news/kingsman-cerchio-doro-primo-trailer-del-film/4436

![1](https://user-images.githubusercontent.com/31142317/29575962-7b1a60ce-8766-11e7-9b38-88c47f7420c7.png)
![2](https://user-images.githubusercontent.com/31142317/29575963-7b385980-8766-11e7-936c-05313f8ebd6d.png)

**Comment by uBlock-user** [comment]
`mmovie.it###advleft`
