### ISSUE TITLE
gpro.net

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#506]
https://www.gpro.net/it/forum/index.asp

![1](https://user-images.githubusercontent.com/31142317/29576189-3e54beae-8767-11e7-954c-3da7e6a4ce1d.png)
![2](https://user-images.githubusercontent.com/31142317/29576190-3e734df6-8767-11e7-8be3-113203d2918f.png)

**Comment by uBlock-user** [comment]
`gpro.net##.boxy`
