### ISSUE TITLE
gamestar.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#507]
http://www.gamestar.de/

![1](https://user-images.githubusercontent.com/31142317/29577399-88462a76-876b-11e7-9a89-e86f4a694af6.png)
![2](https://user-images.githubusercontent.com/31142317/29577400-889f8fe4-876b-11e7-85f6-83322c3b9f02.png)

**Comment by uBlock-user** [comment]
They also have a paywall

http://www.gamestar.de/artikel/anno-1800-zurueck-in-die-vergangenheit,3318239.html

**Comment by StreamXL** [comment]
Yes, I also see them,
How can you make that out?

![d](https://user-images.githubusercontent.com/31142317/29579861-670217ae-8774-11e7-984b-fb927e64cb46.png)

**Comment by jspenguin2017** [comment]
Mock as a bot or pay up.

**Comment by uBlock-user** [comment]
Is it patchable ?

**Comment by uBlock-user** [comment]
Nvm, it appears even after blocking all the JS and CSS, it's server sided.

**Comment by jspenguin2017** [comment]
If you pretend to be Google Bot then it may let you in. Either way, I'm not going to patch that, you'll have to patch it yourself.

**Comment by uBlock-user** [comment]
Yeah changing user agent will do the job, I know.
