### ISSUE TITLE
shutterdowner.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#509]
### Test link (required): 
https://www.shutterdowner.com/image-photo/blonde-young-woman-elegant-blue-dress-575084896?src=dcSeWjlmVobmIjRyAzDWfQ-1-0

### Screenshot of the web page (required): 
http://i.imgur.com/5nj5Jn3.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
http://i.imgur.com/GlY6vxX.png
-->

**Comment by Farhan1385852** [comment]
https://image.shutterstock.com/image-illustration/watercolor-flower-pattern-450w-751589089.jpg
