### ISSUE TITLE
washingtonpost.com

### ISSUE THREAD

**Issue by hvthinh** [jspenguin2017/uBlockProtector#511]
### Test link (required): 
https://www.washingtonpost.com/news/arts-and-entertainment/wp/2017/08/22/louise-linton-just-spelled-out-her-value-system-for-you-common-folk/

### Screenshot of the web page (required): 
http://i.imgur.com/QYpWtSK.jpg

### Screenshot of the console (press `F12` to bring up the console) (required): 
http://i.imgur.com/Gdw5iLM.jpg
http://i.imgur.com/UfxYlUI.jpg

Thank you.

**Comment by StreamXL** [comment]
Install uBlock Protector Extension

**You do not use uBlock Protector**

https://chrome.google.com/webstore/detail/ublock-protector-extensio/ggolfgbegefeeoocgjbmkembbncoadlb

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by StreamXL** [comment]
Can't reproduce.

**Comment by hvthinh** [comment]
@StreamXL : I did install it. Just that I hid it in the Chrome menu.

**Comment by jspenguin2017** [comment]
Well, yes, you are suppose to use that filter.
