### ISSUE TITLE
pcgames-download.com

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#512]
https://pcgames-download.com/

![1](https://user-images.githubusercontent.com/31142317/29635710-20838864-884e-11e7-8e1d-0139d50bf0ba.png)
![3](https://user-images.githubusercontent.com/31142317/29635711-20a6f59c-884e-11e7-8fe5-8f642b155d85.png)

**Comment by uBlock-user** [comment]
They have a dedicated folder for this

`||pcgames-download.com/wp-content/plugins/noadb-leftthenicemessage/`
