### ISSUE TITLE
gala.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#513]
http://www.gala.de/lifestyle/film-tv-musik/knight-rider-wird-dieser-star-der-neue-michael-knight--21428272.html

![1](https://user-images.githubusercontent.com/31142317/29637004-fb087b4e-8852-11e7-977e-39f55029dbf7.png)
![2](https://user-images.githubusercontent.com/31142317/29637005-fb312fa8-8852-11e7-8ac4-dd8d2b90cec1.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
