### ISSUE TITLE
urbia.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#514]
https://www.urbia.de/

![1](https://user-images.githubusercontent.com/31142317/29637109-680ef718-8853-11e7-9fbd-c5386c38425c.png)
![2](https://user-images.githubusercontent.com/31142317/29637110-6833e550-8853-11e7-9266-dd2ec4ea2377.png)

**Comment by jspenguin2017** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by StreamXL** [comment]
Press F5 to wait a bit

**Comment by jspenguin2017** [comment]
Nope, waited like 5 minutes.
