### ISSUE TITLE
grazia-magazin.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#515]
http://www.grazia-magazin.de/

![1](https://user-images.githubusercontent.com/31142317/29637484-86802f40-8854-11e7-9664-9697d5b00271.png)
![2](https://user-images.githubusercontent.com/31142317/29637485-869bd3bc-8854-11e7-9b07-c01f67478542.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
