### ISSUE TITLE
jan-magazine.nl

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#516]
https://www.jan-magazine.nl/

![1](https://user-images.githubusercontent.com/31142317/29637749-65414ef8-8855-11e7-9b7c-e3bdda70fc67.png)
![2](https://user-images.githubusercontent.com/31142317/29637751-656b8664-8855-11e7-96d0-f5ed37228fa8.png)

**Comment by uBlock-user** [comment]
generic elements being inserted is used as detection and in other two also
