### ISSUE TITLE
glamour.nl

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#517]
https://www.glamour.nl/

![1](https://user-images.githubusercontent.com/31142317/29637875-d06b21b8-8855-11e7-9aac-6cdf89624db7.png)
![2](https://user-images.githubusercontent.com/31142317/29637882-d685f37a-8855-11e7-8a84-545f18b44e46.png)

**Comment by uBlock-user** [comment]
same as #516
