### ISSUE TITLE
quest.nl

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#518]
https://www.quest.nl/

![1](https://user-images.githubusercontent.com/31142317/29638207-c615737a-8856-11e7-802a-7793d3e1a039.png)
![2](https://user-images.githubusercontent.com/31142317/29638209-c636c3f4-8856-11e7-949f-6ac14aa840cf.png)

**Comment by uBlock-user** [comment]
same as #516
