### ISSUE TITLE
afdah.to

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#519]
http://afdah.to/

![1](https://user-images.githubusercontent.com/31142317/29676675-fa4e84cc-88f8-11e7-8e3b-2dc682ffe8e2.png)
![2](https://user-images.githubusercontent.com/31142317/29676676-fa6d7fda-88f8-11e7-8f13-951117409b22.png)

**Comment by uBlock-user** [comment]
http://afdah.to/show-ad.js

It's also hiding various 3rd party video players

**Comment by jspenguin2017** [comment]
Looks like the player logic is in that file.

**Comment by uBlock-user** [comment]
So whitelist will be required ? or can you defuse it without whitelisting ?

**Comment by StreamXL** [comment]
Videos will not be played

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/29678174-d16f60b4-88ba-11e7-93bd-33794c8aa569.png)

**Comment by jspenguin2017** [comment]
@uBlock-user They can name their script however they want, they can name their ads serving script `index.js`, a file named `show-ad.js` doesn't have to do what its name says. I guess the element bait is just to tell the user why the website isn't working.

**Comment by uBlock-user** [comment]
@jspenguin2017 So I suppose we will have to whitelist because since the players lie in there.

I tried to blow up `$.hide` via `abort-on-property-read.js` didn't have any effect.

**Comment by uBlock-user** [comment]
If you're seeing black screen still then whitelist - http://afdah.to/show-ads.js

**Comment by StreamXL** [comment]
Now that

![d](https://user-images.githubusercontent.com/31142317/29678603-76b0a0a8-88ff-11e7-838e-15c25087f9bb.png)

**Comment by jspenguin2017** [comment]
This should fix it.

**Comment by StreamXL** [comment]
If not, the message still appears

When will that be fixed?

**Comment by jspenguin2017** [comment]
Test link?

**Comment by StreamXL** [comment]
http://afdah.to/watch-movies/65446-alien-covenant-2017/

![fffff](https://user-images.githubusercontent.com/31142317/29681017-bd3489ac-8906-11e7-98c2-548af00f1f32.png)

**Comment by uBlock-user** [comment]
Have you activated uBlock Protector List from 3rd party Filters tab in uBO ?

If you do that, you won't see this notice.

**Comment by StreamXL** [comment]
Yes
![ee](https://user-images.githubusercontent.com/31142317/29681547-481554e2-8908-11e7-850a-9cf8d2902199.png)

**Comment by uBlock-user** [comment]
Force update that list by clearing the cache and click Update button.

**Comment by StreamXL** [comment]
Thanks,

now it's working

Very funny

**Comment by uBlock-user** [comment]
A commit was already added an hour ago - https://github.com/jspenguin2017/uBlockProtector/commit/b6e49212550f0a56e04e2530b9910ebe982c817a

All you had to do is force update it, simple.

**Comment by jspenguin2017** [comment]
Yea, I changed the filter, so it is good now?
