### ISSUE TITLE
wp.tv

### ISSUE THREAD

**Issue by MajkiIT** [jspenguin2017/uBlockProtector#52]
Hi, on this video http://wp.tv/i,orphan-black,mid,1997328,cid,2303723,klip.html?_ticrsn=3&ticaid=618a37/ when I click on play I hear double sound. Can you check it?

FYI @xxcriticxx @F4z

**Comment by X01X012013** [comment]
I could not check it because it has Geo Lock. Can you fine a video that have same issue but not Geo Locked?

**Comment by X01X012013** [comment]
I tested on http://wp.tv/i,prognoza-pogody-na-17-lutego,mid,1997971,cid,2303759,klip.html , everything seems to be fine...

**Comment by MajkiIT** [comment]
One moment please.

**Comment by MajkiIT** [comment]
Sorry, my mistake. I have added 2 scripts.

**Comment by adreporter** [comment]
@jspenguin2017 
http://wp.tv/i,prognoza-pogody-na-17-lutego,mid,1997971,cid,2303759,klip.html
![3](https://user-images.githubusercontent.com/18214146/27758476-fd3d4a2e-5e14-11e7-8329-6c475cf3ac7e.PNG)
I can't play the video, could you please have a look?

**Comment by jspenguin2017** [comment]
@adreporter 
![image](https://user-images.githubusercontent.com/7283682/27758508-85387e14-5dd2-11e7-9b28-daf08b80d941.png)

**Comment by adreporter** [comment]
@jspenguin2017 
http://wp.tv/i,prognoza-pogody-na-17-lutego,mid,1997971,cid,2303759,klip.html
I have some issues with the player if I skip to a different part of the video. Am I the only one?

**Comment by jspenguin2017** [comment]
Eh...

**Comment by hawkeye116477** [comment]
@adreporter All is fine, but I checked this on Vivaldi/Chromium 59.0.3071.112. I do not have Google Chrome.

**Comment by jspenguin2017** [comment]
Hum, it is working now... I didn't change anything...

**Comment by adreporter** [comment]
@jspenguin2017 @hawkeye116477 I noticed that sometimes it works and sometimes not.

**Comment by jspenguin2017** [comment]
Are you sure it's not because their servers are broken?

**Comment by adreporter** [comment]
It could be, but I'm not sure. I was thinking about some bad EasyList rule.

**Comment by adreporter** [comment]
Can you check what happens to the player after 7 seconds of playback?

**Comment by adreporter** [comment]
I don't understand, a moment ago after playing the first 7 seconds, the player stopped working. Now it works fine.

**Comment by jspenguin2017** [comment]
Hum... It blinks once and continues...

**Comment by adreporter** [comment]
Could you please disable EasyList for a while and tell me if the video stops after 7 seconds?

**Comment by adreporter** [comment]
For me it does.

**Comment by jspenguin2017** [comment]
Then don't disable EasyList, I don't see the problem here.

**Comment by hawkeye116477** [comment]
@adreporter EasyList is required for Polish filters to work properly. Don't disable it.

**Comment by adreporter** [comment]
> I don't see the problem here
You mean now the video player works fine for you?

**Comment by jspenguin2017** [comment]
Well, not 100% to what one would expect, but it is working OK.

**Comment by adreporter** [comment]
@jspenguin2017 I'm using standard setup. I updated uBlock Origin and your extension, cleared all filter lists cache and updated them, cleared cookies, cleared site cache, refreshed the page 10 times but the problem isn't solved yet: the video stops playing after 7 seconds.
I noticed that in the 5th second of the video in the top left corner, this is appearing <img width="134" alt="cattura" src="https://user-images.githubusercontent.com/18214146/28458966-e3c94eba-6e0b-11e7-814f-9ad03bea194c.PNG">that means "advertisement in a moment", 2 seconds after, the video blinks and it stops playing.

**Comment by jspenguin2017** [comment]
Yea it is not really working. I'll just apply the other solution, but I need to properly size the video player...

**Comment by ghajini** [comment]
http://wp.tv/i,policyjna-wpadka,mid,2005479,cid,4051,klip.html?ticaid=5198bb
ad popunder is present over player which hides player controls...
![chrome_2017-07-21_22-47-14](https://user-images.githubusercontent.com/20338483/28474637-0820c21a-6e67-11e7-836e-6a9379dae58f.png)

**Comment by ghajini** [comment]
purge all caches>update now...worked

**Comment by jspenguin2017** [comment]
Fixed... For now...
