### ISSUE TITLE
urlaubspartner.net

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#520]
https://www.urlaubspartner.net/

![1](https://user-images.githubusercontent.com/31142317/29682345-fcff58b0-890a-11e7-833f-a07a787026f7.png)
![2](https://user-images.githubusercontent.com/31142317/29682346-fd03d50c-890a-11e7-8cb8-2cce168c3380.png)

**Comment by uBlock-user** [comment]
bait - https://www.urlaubspartner.net/js/adview.js

**Comment by uBlock-user** [comment]
`urlaubspartner.net###abmsg`
