### ISSUE TITLE
vertamedia.com

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#521]
https://ssp.vertamedia.com

![1](https://user-images.githubusercontent.com/31142317/29684678-2ac2277a-8913-11e7-874e-f55ea2b54787.png)
![2](https://user-images.githubusercontent.com/31142317/29684677-2abfac52-8913-11e7-9ee0-996e58a7c6c2.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
