### ISSUE TITLE
bizled.co.in

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#522]
http://bizled.co.in/led-lighting-module-market-to-grow-at-cagr-20-by-2021/

![1](https://user-images.githubusercontent.com/31142317/29685192-ff8a544a-8914-11e7-8b01-3645e2c9d3a4.png)
![2](https://user-images.githubusercontent.com/31142317/29685193-007148f0-8915-11e7-91fd-3572e8c0ca33.png)

**Comment by uBlock-user** [comment]
alternative filter - `bizled.co.in##script:inject(setTimeout-defuser.js, ad blocker)`
