### ISSUE TITLE
dexternights.com

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#523]
https://www.dexternights.com/

![1](https://user-images.githubusercontent.com/31142317/29685977-7765d8ca-8917-11e7-9b51-61778ca8390f.png)
![2](https://user-images.githubusercontent.com/31142317/29685978-77874960-8917-11e7-9ac1-4808fe223b1a.png)

**Comment by uBlock-user** [comment]
https://www.dexternights.com/wp-content/cache/autoptimize/js/autoptimize_267a5e762ea358bcaa219e4d85c079e4.js

`dexternights.com##script:inject(abort-on-property-read.js, anOptions)`
