### ISSUE TITLE
sectorsatoshi-amarillo.website

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#524]
http://sectorsatoshi-amarillo.website/

![1](https://user-images.githubusercontent.com/31142317/29686050-beabadae-8917-11e7-9012-586f01635727.png)
![2](https://user-images.githubusercontent.com/31142317/29686049-bea4ba76-8917-11e7-9577-db212234a446.png)

**Comment by uBlock-user** [comment]
https://github.com/jspenguin2017/uBlockProtector/issues/232
