### ISSUE TITLE
cryptovertise.tk

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#525]
http://cryptovertise.tk

![1](https://user-images.githubusercontent.com/31142317/29686066-e29137ca-8917-11e7-8432-6f6b786465de.png)
![2](https://user-images.githubusercontent.com/31142317/29686067-e2bb0e24-8917-11e7-9014-24da92d1b903.png)

**Comment by uBlock-user** [comment]
same as #232
