### ISSUE TITLE
freeridermagazine.net

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#526]
http://www.freeridermagazine.net

![1](https://user-images.githubusercontent.com/31142317/29686108-0bc637c6-8918-11e7-8f47-cca7fcbca6c8.png)
![2](https://user-images.githubusercontent.com/31142317/29686105-060c89b6-8918-11e7-907d-eb858c1d4325.png)

**Comment by uBlock-user** [comment]
`freeridermagazine.net##script:inject(abort-on-property-read.js, anOptions)`
