### ISSUE TITLE
catcatyfaucet.xyz

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#527]
http://ltc.catcatyfaucet.xyz
http://catcatyfaucet.xyz

![1](https://user-images.githubusercontent.com/31142317/29686187-5b8fa5b2-8918-11e7-8155-b1f9c573b590.png)
![2](https://user-images.githubusercontent.com/31142317/29686188-5bb830c2-8918-11e7-8ecc-59c594f9a5bf.png)

**Comment by uBlock-user** [comment]
http://catcatyfaucet.xyz/ads/ads.js

http://catcatyfaucet.xyz/libs/advertisement.js

`catcatyfaucet.xyz##script:inject(abort-on-property-read.js, isAdsDisplayed)`
