### ISSUE TITLE
receivesmsonline.net

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#528]
https://www.receivesmsonline.net/

![1](https://user-images.githubusercontent.com/31142317/29686689-4226c8c4-891a-11e7-8fa3-b907e873d36c.png)
![2](https://user-images.githubusercontent.com/31142317/29686691-424247c0-891a-11e7-9a83-b06d61da2d5d.png)

**Comment by uBlock-user** [comment]
https://www.receivesmsonline.net/ads.js

ads.js v2

**Comment by jspenguin2017** [comment]
Eh... that's like v2.1...

**Comment by uBlock-user** [comment]
what's the difference ?

**Comment by jspenguin2017** [comment]
The ID is longer... Going with white list for now. `a.onBeforeScriptExecute` would work for this but it's kind of slow.

**Comment by uBlock-user** [comment]
Can't `onBeforeScriptExecute` be implemented like gorhill did in uBO with `##script:contain` scriptlets ?

**Comment by jspenguin2017** [comment]
`a.onBeforeScriptExecute` can do more, it can also modify the script that is about to execute. But it (should be) way slower than `##script:contain`, but on the other side, `##script:contain` is about to dysfunc.

**Comment by uBlock-user** [comment]
What I'm saying is, we have our own onBeforeScriptExecute event, so we should be able to do something similar to `##script:contain`

**Comment by jspenguin2017** [comment]
Well, obviously I can use it to remove that detection block, but it is kind of heavy and it would be specific to this website.

**Comment by uBlock-user** [comment]
https://github.com/jspenguin2017/uBlockProtector/issues/257#issuecomment-305668401

How about that ? Can that redirect be patched with the current implementation of `onBeforeScriptExecute` ?

**Comment by uBlock-user** [comment]
This is the current detection script

```javascript
$(document).ready(function() {
  |  
  | $.ajax('showads.js').fail(function(d){if(d.status===0 \|\| d.statusText == 'error'){ $('html').addClass('ab'); $(".ab").css("display", "inline-block");
  |  
  |  
  | var chick = window.location.href.indexOf('USA2') > -1;
  | var chick2 = window.location.href.indexOf('UK2') > -1;
  | var chick3 = window.location.href.indexOf('Sweden') > -1;
  | var chick4 = window.location.href.indexOf('Canada2') > -1;
  | var chick5 = window.location.href.indexOf('usa2') > -1;
  |  
  |  
  | if ((!chick)&&(!chick2)&&(!chick3)&&(!chick4)&&(!chick5)) {
  | window.location.href = "http://receive-a-sms.com/adblock";
  |  
  | }
```

**Comment by jspenguin2017** [comment]
Possibly, don't forget that `a.onBeforeScriptExecute` is not very stable, if a first party white list can fix it, going with white list would be better.

**Comment by uBlock-user** [comment]
I just hate to surrender by whitelisting, so I was looking into this and this domain also reminded me of #257

**Comment by jspenguin2017** [comment]
Yea, well, I'm not confident enough to use it over a bait script white list, it's definitely using an undocumented behavior. I did use it a few times when the next solution is to block all inline scripts and monkey patch after.

**Comment by okiehsch** [comment]
How about 
`receivesmsonline.net##script:inject(abort-current-inline-script.js, elms)`

**Comment by jspenguin2017** [comment]
Oh, a global variable. `receivesmsonline.net##script:inject(abort-on-property-read.js, elms)`

**Comment by uBlock-user** [comment]
@okiehsch can we use that scriptlet to do the same on #257 ?

Here's the script


```javascript
$(document).ready(function() {
--
  |  
  | $.ajax('showads.js').fail(function(d){if(d.status===0 \|\| d.statusText == 'error'){ $('html').addClass('ab'); $(".ab").css("display", "inline-block");
  |  
  |  
  | var chick = window.location.href.indexOf('USA2') > -1;
  | var chick2 = window.location.href.indexOf('UK2') > -1;
  | var chick3 = window.location.href.indexOf('Sweden') > -1;
  | var chick4 = window.location.href.indexOf('Canada2') > -1;
  | var chick5 = window.location.href.indexOf('usa2') > -1;
  |  
  |  
  | if ((!chick)&&(!chick2)&&(!chick3)&&(!chick4)&&(!chick5)) {
  | window.location.href = "http://receive-a-sms.com/adblock";
  |  
  | }
```
