### ISSUE TITLE
ur.ly, zippyshare.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#529]
### Add everything else that you believe to be useful below (optional): 
Zippyshare pop ups coming from last week, I think they built a new mechanism, the pop comes each 3-4 times cycle, reload your page couple of times then click download now.

ur.ly is new, clicking Skip Ad, opens pop up.

**Comment by uBlock-user** [comment]
try `zippyshare.com##script:inject(abort-on-property-read.js, open)`

**Comment by uBlock-user** [comment]
||ur.ly^$inline-script

Works for me!

**Comment by Dibbyo456** [comment]
Both worked, but the timer needs to be patched. 👍

**Comment by uBlock-user** [comment]
I'm leaving the timer for @jspenguin2017 to bypass, I didn't say it won't be bypassed.

**Comment by Dibbyo456** [comment]
@uBlock-user Yes I know, I was talking about auto redirect to the destination page.

**Comment by uBlock-user** [comment]
Ofcourse If gets bypassed completely, then you don't need add any filters for that domain.

**Comment by jspenguin2017** [comment]
`ur.ly` is bypassable.

**Comment by Dibbyo456** [comment]
@jspenguin2017 ur.ly new domain : `urly.mobi` - [Test Link](http://urly.mobi/xD7dQZY)
