### ISSUE TITLE
animeflv.co

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#530]
### Test link (required): 
http://animeflv.co/Ver/3812/dragon-ball-super/episodio-1/
### Screenshot of the web page (required): 
![ver_dragon_ball_super_episodio_1_hd_-_animeflv_-_g_2017-08-25_09-46-32](https://user-images.githubusercontent.com/27441315/29718584-8a538d82-89b3-11e7-94c4-97ea10b269c1.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpanimeflv cover3812drag_2017-08-25_09-46-50](https://user-images.githubusercontent.com/27441315/29718592-8f473dde-89b3-11e7-8ae1-7a6c453c839c.png)

**Comment by uBlock-user** [comment]
same as https://github.com/reek/anti-adblock-killer/issues/3214
