### ISSUE TITLE
tagesspiegel.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#532]
http://www.tagesspiegel.de/berlin/bezirke/steglitz-zehlendorf/gastbeitrag-vom-evangelischen-kirchenkreis-teltow-zehlendorf-bitte-gehen-sie-waehlen/14517690.html

![1](https://user-images.githubusercontent.com/31142317/29721185-79acc8dc-89bc-11e7-8215-00a0b69e6260.png)
![2](https://user-images.githubusercontent.com/31142317/29721186-79c9abbe-89bc-11e7-8336-f529efb18d45.png)

**Comment by uBlock-user** [comment]
`tagesspiegel.de##.hcf-ressort`

**Comment by jspenguin2017** [comment]
That is not working as intended. It should look like this: 
![image](https://user-images.githubusercontent.com/7283682/29735108-b576f04e-89b3-11e7-82fe-a64c54fc4642.png)
![image](https://user-images.githubusercontent.com/7283682/29735105-afe81996-89b3-11e7-843e-bf05eddf1ac3.png)

**Comment by uBlock-user** [comment]
Is that a video ?

**Comment by jspenguin2017** [comment]
Yes, the box is suppose to have videos... I think. It doesn't look like ads, kind of news-like. I don't speak that language so I'm not 100% sure, but I believe those are not ads.

**Comment by uBlock-user** [comment]
http://www.tagesspiegel.de/js/11666790/35/tgs.teaser-ad.js

http://www.tagesspiegel.de/js/11666790/35/tgs.teaser-ad.js

http://www.tagesspiegel.de/js/11666790/tgs.teaser-ad.js

**Comment by jspenguin2017** [comment]
Huh, I don't see anything checking for anything... The line `node.find('.ta-content-right').prepend(' <strong id="ta-adblock-info">Bitte schalten Sie den Adblocker aus, wenn Sie die Videos sehen wollen.</strong> ');` is unconditional...

**Comment by uBlock-user** [comment]
so why not block the entire file ?

**Comment by jspenguin2017** [comment]
Does videos work with entire file blocked?

**Comment by uBlock-user** [comment]
No, but are the videos actual website content or just random bait videos not related to the website just placed to test if adblocker is used or not?

**Comment by jspenguin2017** [comment]
I don't speak that language so I'm not sure.

**Comment by StreamXL** [comment]
The videos belong to the site, they contain reports about the city

**Comment by okiehsch** [comment]
I would not say that the videos contain reports about the city , they talk about and promote the businesses they work for.

**Comment by jspenguin2017** [comment]
Well, we need someone who speak that language to confirm this.

**Comment by okiehsch** [comment]
I do.

**Comment by jspenguin2017** [comment]
Oh, then I guess block the whole screen is the way to go. Thanks for the info.
