### ISSUE TITLE
wer-weiss-was.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#533]
http://www.wer-weiss-was.de/

![1](https://user-images.githubusercontent.com/31142317/29721554-f8f80cf4-89bd-11e7-8dfb-61913f4d8790.png)
![2](https://user-images.githubusercontent.com/31142317/29721555-f91af2be-89bd-11e7-9d7f-f42f9d9485af.png)

**Comment by uBlock-user** [comment]
`wer-weiss-was.de###hint`
