### ISSUE TITLE
so-abnehmen.info

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#535]
https://so-abnehmen.info/uber-uns/bitte-adblocker-abschalten/
https://so-abnehmen.info/

![1](https://user-images.githubusercontent.com/31142317/29725984-5033a644-89ce-11e7-8e9d-1123c42ea679.png)
![2](https://user-images.githubusercontent.com/31142317/29725985-50597a22-89ce-11e7-8b3b-cabff92fe597.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
