### ISSUE TITLE
rallye-magazin.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#536]
https://www.rallye-magazin.de

![1](https://user-images.githubusercontent.com/31142317/29726082-c1790a74-89ce-11e7-9c27-b3e22216768b.png)
![2](https://user-images.githubusercontent.com/31142317/29726083-c19a5648-89ce-11e7-9120-9cb53de607c0.png)

**Comment by jspenguin2017** [comment]
https://www.rallye-magazin.de/typo3temp/compressor/merged-1349caa871dc2ff5df5664fd6d7d4cd2.js?1498032006
