### ISSUE TITLE
schwarzwaelder-bote.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#538]
http://www.schwarzwaelder-bote.de/

![1](https://user-images.githubusercontent.com/31142317/29726660-e2a93d8e-89d0-11e7-8643-e5e7354885c1.png)
![2](https://user-images.githubusercontent.com/31142317/29726661-e2c83ba8-89d0-11e7-904b-d7baefde5693.png)

**Comment by uBlock-user** [comment]
`schwarzwaelder-bote.de###blocker-note`
