### ISSUE TITLE
forum.peugeot-metropolis.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#539]
https://forum.peugeot-metropolis.de/

![1](https://user-images.githubusercontent.com/31142317/29726717-262f4bb6-89d1-11e7-8ec3-cb63dda49fb2.png)
![2](https://user-images.githubusercontent.com/31142317/29726718-264b9550-89d1-11e7-8de6-c3db954eb67e.png)

**Comment by uBlock-user** [comment]
`peugeot-metropolis.de##script:inject(abort-current-inline-script.js, $, #gandalfads)`
