### ISSUE TITLE
linkneverdie.com

### ISSUE THREAD

**Issue by LaxusiC** [jspenguin2017/uBlockProtector#541]

**Comment by uBlock-user** [comment]
Your console screenshot doesn't have domain listed, which means you haven't installed the extension as per the instructions prescribed.

**Comment by uBlock-user** [comment]
`linkneverdie.com##script:inject(abort-current-inline-script.js, $, #wrapper)`

**Comment by uBlock-user** [comment]
```javascript
function banphaohoa() {
--
  | $('#wrapper').fireworks();
  | setTimeout(tatbanphaohoa, 20000)
  | }
  | function tatbanphaohoa() {
  | $('#wrapper').fireworks('destroy');
  | }
  | $(function () {
  | //$("img.lazy").lazyload({
  | //effect: "fadeIn"
  | //});
  | var notify = $.connection.viewsCount;
  | notify.client.displayNotification = function (msg) {
  | $("#soluotview").html(msg);
  | };
  | var usr = $.connection.OnlineHub;
  | usr.client.showUsersOnLine = function (data) {
  | $('#pagehits').text(data);
  | };
  | // Enter Search
  | $("#txtSearch").keyup(function (event) {
  | if (event.keyCode == 13) {
  | var replaced = $("#txtSearch").val().split(' ').join('-');
  | window.open('/tag/?k=' + replaced, '_blank');
  | }
  | });
  | setTimeout(function () {
  | if ($('#adquangcao').height() == 0 \|\| $('#adquangcao').css('display') == 'none' \|\| $('#adquangcao').attr('src') == null) {
  | $('#wrapper').hide()
  | }
  | // Cập nhật Facebook
  | $.post("https://graph.facebook.com", {
  | id: 'https://linkneverdie.com/',
  | scrape: true
  | }, function () {
  | });
  | }, 3000)
  | })
```

**Comment by Dibbyo456** [comment]
@uBlock-user isn't it BAB? noeval will also work?

**Comment by uBlock-user** [comment]
No it's NOT BAB. It only uses CSS of BAB notice.

**Comment by LaxusiC** [comment]
huh, i already installed the extension, like i said it was working but today i got this error, weird

**Comment by uBlock-user** [comment]
If you had the extension installed then the console screenshot would look like this - 

![](https://i.gyazo.com/fef798bd76d94b3c501089f91b30c491.png)

See the text "Domain: linkneverdie.com" that comes from the extension and here's yours

![](https://image.prntscr.com/image/WUGY6cqtQOuZOQtGF9AQsg.png)

^^ No such "Domain: linkneverdie.com" there

**Comment by lain566** [comment]
@jspenguin2017 It's broken again, go to `linkneverdie.com` and wait

![opera instant nea_2017-09-30_220905_linkneverdie com](https://user-images.githubusercontent.com/27441315/31049099-5a2cddb2-a62c-11e7-9b59-aba3f751c0d3.png)


![developer_tools_-_httpslinkneverdie com_2017-09-30_22-11-08](https://user-images.githubusercontent.com/27441315/31049103-6889df22-a62c-11e7-9ec1-e24a77beceaa.png)

**Comment by jspenguin2017** [comment]
After some tracing, I think it's in `en6.js`. They do wrap `setTimeout` making filtering a bit difficult... 
![image](https://user-images.githubusercontent.com/7283682/31049248-85bbbab0-a5ec-11e7-9941-fbdc04336f80.png)

**Comment by LaxusiC** [comment]
Getting this today, i already re-installed everything and still getting the issue. I'm using Chrome

http://prntscr.com/gw1sub

Tested with Firefox using uBlock and AAK Cont and doesn't has this problem

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/31444341-3b1e06d2-ae59-11e7-8eac-99852b143ef5.png)
