### ISSUE TITLE
null-24.com, nulledvar.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#542]
### Test link (required): 
1) https://null-24.com/wplms-learning-management-system-v3-0-nulled/
2) https://nulledvar.com/frizi-arcade-v1-0-10-wordpress-arcade-theme-nulled-free/

### Add everything else that you believe to be useful below (optional): 
@jspenguin2017 patched the redirection before, but it's not working since the day, uBO turns into a extension.

1) null-24.com - Clicking download links, opens another 10 sec redirect page, the redirection can be completely skip, it's a by a simple java script on the main page.

nulledvar follows the same method, I couldnot post screenshots because the site has view source + right click protection. :/

**Comment by uBlock-user** [comment]
1) I don't see what the issue is, the domain itself hosts the download and has internal redirection, right click is blocked and a has a timer after clicking download.

2) nulledvar  doesn't have any redirection internal or external, and no timers either and right is NOT blocked either. In all it's fine and there's nothing to patch.

**Comment by Dibbyo456** [comment]
@uBlock-user I think you did not understood what I meant, so here the details.

If I click the [download link](http://prntscr.com/gd958i) it actually sends me to [another page](http://prntscr.com/gd95eo), In the [source code](http://prntscr.com/gd95qw) there is a redirect javascript, which causes the 10 sec redirect. The javascript basically redirect any download link to 10 sec page, So, ignoring the javascript we don't have to wait for 10 secs.

I reported this to @jspenguin2017  a month ago, he actually did it, but it's broken, since the extension update. Same goes for nulledvar.com

**Comment by uBlock-user** [comment]
> If I click the download link it actually sends me to another page, In the source code there is a redirect javascript, which causes the 10 sec redirect. The javascript basically redirect any download link to 10 sec page, So, ignoring the javascript we don't have to wait for 10 secs.

Yes, and it's called internal redirection. If you try to patch it, the whole website can break, other than right click issue and the 10 sec I don't see any other issue with it. Did he actually patch the internal redirection ? If so, link me the issue here.

I don't get any internal redirection or timer or the right click issue at nulledvar.

**Comment by Dibbyo456** [comment]
> Yes, and it's called internal redirection. If you try to patch it, the whole website can break, other than right click issue

Nope. It wont. Because it's not internal link, the javascript triggering the redirect. 
`https://null-24.com/download/?link=` it's actually a page. If you look into the [source code](http://prntscr.com/gd9dr8), you can find the actual download link. So, ignoring the javascript won't break anything. I'm positive.

> Did he actually patch the internal redirection ? If so, link me the issue here.

YES. He did, like a said before, it's not a internal redirect. I can't find the thread, where I reported it, I probably hijacked some else's thread, that's why ended up opening a new issue.

> I don't get any internal redirection or timer or the right click issue at nulledvar.

Nulledvar does not have right click protection, but they have the same javascript redirect, if you click [this links](http://prntscr.com/gd9ev4).

P.S - I used, [Allow Copy](https://chrome.google.com/webstore/detail/allow-copy/abidndjnodakeaicodfpgcnlkpppapah) extension to enable right click, but it's not seem to bypass the copy protection.

**Comment by uBlock-user** [comment]
Hmmm, I see, so it's a deliberately added page like a stitched popup. I do remember seeing null24 on this repo before, but I can't find it either.

Also those links on nulled var don't have redirect if you right click and do "Open in a new tab" however if you left click those links then a third-party redirect is invoked, another stitched popup I suppose.

**Comment by Dibbyo456** [comment]
Yeah, That was me. 
Actually null24 changed their domain null24.net to null-24.com maybe that broke the patch.

**Comment by uBlock-user** [comment]
https://github.com/jspenguin2017/uBlockProtector/blob/master/Extension%20Compiler/Extension/content/content-rules.js#L2740

It is `null-24.com` So the patch should work. They changed the script.

**Comment by jspenguin2017** [comment]
`null-24.com` fixed, I don't see what's wrong with `nulledvar.com`.

**Comment by Dibbyo456** [comment]
@jspenguin2017 in `nulledvar.com` [clicking this links](http://prntscr.com/gda00h) redirecting [to here](http://prntscr.com/gda0c8) same as null24.

**Comment by StreamXL** [comment]
**It's a script**

![g](https://user-images.githubusercontent.com/31142317/29741955-e4ff7c50-8a76-11e7-9467-314434793963.png)

**Comment by StreamXL** [comment]
It's a script

![g](https://user-images.githubusercontent.com/31142317/29741986-458b5756-8a77-11e7-9af0-8ac36933e0e7.png)

**Comment by Dibbyo456** [comment]
@jspenguin2017 Clicking [this links](http://prntscr.com/gdk6xw) also triggering the popup - [Test Link](https://null-24.com/betheme-v20-4-3-1-responsive-multi-purpose-wordpress-theme/).
