### ISSUE TITLE
topagrar.com

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#545]
https://www.topagrar.com/

![1](https://user-images.githubusercontent.com/31142317/29743323-f47786aa-8a8f-11e7-938b-07e2832f6cda.png)
![2](https://user-images.githubusercontent.com/31142317/29743324-f4e66386-8a8f-11e7-9ec6-6bc10f33364c.png)

**Comment by uBlock-user** [comment]
script https://www.topagrar.com/_themes/topagrar-responsive/_js/header.js?v=131214

**Comment by uBlock-user** [comment]
```
topagrar.com##.adblocker.open.fade.modal
topagrar.com##.fade.modal-backdrop
```

**Comment by jspenguin2017** [comment]
Wouldn't that affect other backdrops too?

**Comment by uBlock-user** [comment]
Are there any other backdrops ? I can't find any. 

There's yet another option you can use by setting a cookie named `closed-adblocker` to value `1`.
