### ISSUE TITLE
fm.tuba.pl

### ISSUE THREAD

**Issue by hawkeye116477** [jspenguin2017/uBlockProtector#547]
### Test link (required): 
http://fm.tuba.pl/play/10/2/radio-tok-fm?appId=03
### Screenshot of the web page (required): 
![screenshot_20170828_133325](https://user-images.githubusercontent.com/19818572/29771967-a62b1a3a-8bf6-11e7-9e1b-c9a8de63a1f6.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![screenshot_20170828_133616](https://user-images.githubusercontent.com/19818572/29771974-ac57ce62-8bf6-11e7-91ca-1de757339b41.png)
![screenshot_20170828_133631](https://user-images.githubusercontent.com/19818572/29771975-ae1e964a-8bf6-11e7-9c38-b91b6ddb75fc.png)

### Add everything else that you believe to be useful below (optional): 
Browser: Chromium 60.0.3112.90 (64-bit)
"Your browser blocks ads. You can buy ad-free access...."
On Waterfox with AAK Cont this helps: `@@||imasdk.googleapis.com/js/sdkloader/ima3.js$script,domain=fm.tuba.pl`, but on Chromium with uBlock Protector, this doesn't work. I must turn off uBlock Protector Extension to hide this message and make player properly working.

**Comment by uBlock-user** [comment]
script - http://images.fm.tuba.pl/tuba3/_js/player_html_2016/dist2/main.055a7ec17748acd95db6.bundle.js?a=2

**Comment by hawkeye116477** [comment]
@jspenguin2017 Thanks, works correct.
