### ISSUE TITLE
mallorcazeitung.es

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#548]
http://www.mallorcazeitung.es/

![1](https://user-images.githubusercontent.com/31142317/29833427-b576363c-8ceb-11e7-8113-65fe6667c9a1.png)
![2](https://user-images.githubusercontent.com/31142317/29833426-b5751446-8ceb-11e7-99ee-10e0607d3063.png)

**Comment by uBlock-user** [comment]
Can't reproduce.

bait - http://www.mallorcazeitung.es/elementosWeb/js/ads.js

**Comment by StreamXL** [comment]
Update your system :-)

**Comment by uBlock-user** [comment]
What has my system got anything to do with me not able to reproduce it ? It's rather I got more filterlists than the default added which breaks the aa script itself.
