### ISSUE TITLE
haaretz.com

### ISSUE THREAD

**Issue by MTWomg** [jspenguin2017/uBlockProtector#550]

**Comment by jspenguin2017** [comment]
Can't reproduce. 

Try `@@||haaretz.com^$generichide`

**Comment by MTWomg** [comment]
That doesn't work, not sure why you can't reproduce.

**Comment by jspenguin2017** [comment]
I'm not sure. Try update your filters. 
![image](https://user-images.githubusercontent.com/7283682/29840506-822bd59c-8cbf-11e7-885a-c200260ffbd1.png)

**Comment by MTWomg** [comment]
Just tried that, no go. Will wait to see if anyone else can reproduce it.

**Comment by uBlock-user** [comment]
Can't reproduce.

Try `haaretz.com##script:inject(abort-current-inline-script.js, AdBlockUtil)`

**Comment by MTWomg** [comment]
Looks like that fixed it.

**Comment by uBlock-user** [comment]
Browse few pages and let me know how it goes.

**Comment by MTWomg** [comment]
Working great. Opened a bunch of pages, all is still working. Think it's good now, thanks!

**Comment by jspenguin2017** [comment]
Ah, I see... 
![image](https://user-images.githubusercontent.com/7283682/29841573-1e5cfb8c-8cc3-11e7-8aea-10396ea3e85c.png)

**Comment by MTWomg** [comment]
That's hilarious. What the hell.

**Comment by uBlock-user** [comment]
So was it cookie based ?

**Comment by jspenguin2017** [comment]
It uses cookie to track its state, not exactly cookie "based".

**Comment by uBlock-user** [comment]
similar to https://github.com/jspenguin2017/uBlockProtector/issues/492

**Comment by jspenguin2017** [comment]
It's set to 20% trigger rate, if it doesn't trigger, it won't trigger for 3 days.

**Comment by uBlock-user** [comment]
That's funny, I would like to see it get triggered 😆
