### ISSUE TITLE
wp.pl and related domains

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#552]
Hi guys, I have updated the solution for `wp.pl` and related domains. Let me know if something is not right. 

Keep in mind that I will not be fixing programming mistakes (player being replaced by ads) of the website, so if the issue occurs on a browser without any extension (I usually test with Edge), then I will not fix it.

**Comment by HateAds** [comment]
Here should be video player.
https://parenting.pl/odcien-ust-moze-powiedziec-wiele-o-stanie-twojego-zdrowia-to-moga-byc-problemy-z-sercem-czy-watroba
![image](https://user-images.githubusercontent.com/29756590/29951675-644981a8-8ec4-11e7-91c6-71074e70eca6.png)

**Comment by jspenguin2017** [comment]
Can't reproduce. Don't forget to update the filter list as well. 
![image](https://user-images.githubusercontent.com/7283682/29951775-40477d38-8e82-11e7-82eb-f46865f40ebb.png)

**Comment by HateAds** [comment]
@jspenguin2017 works fine now. Thanks.
![image](https://user-images.githubusercontent.com/29756590/29951876-fa31765c-8ec5-11e7-8d00-278152e000e1.png)
