### ISSUE TITLE
kmspico.esy.es

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#553]
### Test link (required): 
http://kmspico.esy.es/
### Screenshot of the web page (required): 
![kmspico esy es_-_google_chrome_2017-09-01_11-43-50](https://user-images.githubusercontent.com/27441315/29964629-fbc222e2-8f0a-11e7-8092-e210e188501f.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpkmspico esy es_2017-09-01_11-43-58](https://user-images.githubusercontent.com/27441315/29964644-05c31fb2-8f0b-11e7-83fc-27eac9785eec.png)

**Comment by uBlock-user** [comment]
`esy.es##script:inject(abort-on-property-read.js, adBlockDetected)`

**Comment by lain566** [comment]
That's weird. It works, but if I delete cookies and refresh the page, anti-adblock message appears again.
http://kmspico.esy.es/keygen/ratiborus-kms-tools-07-08-2017-portable/

**Comment by jspenguin2017** [comment]
I can't reproduce, maybe race condition?

**Comment by ghajini** [comment]
reproduce with if frequent refresh 
![chrome_2017-09-01_20-12-57](https://user-images.githubusercontent.com/20338483/29974957-422229fc-8f52-11e7-9c0e-fe0aa90cd42c.png)
![chrome_2017-09-01_20-13-15](https://user-images.githubusercontent.com/20338483/29974958-4228d0b8-8f52-11e7-9980-4feb7d37189b.png)

**Comment by lain566** [comment]
I have no idea, but in doing so, I could not enter the page. It was hard.

**Comment by jspenguin2017** [comment]
OK, I moved the solution to Extension.

**Comment by lain566** [comment]
Yes, that solved it.

**Comment by ghajini** [comment]
so thats bug in `script:inject(abort-on-property-read.js`,
these findings to be reported to gorhill

**Comment by jspenguin2017** [comment]
No, it's not a bug, that's as good as it gets.

**Comment by uBlock-user** [comment]
Scriptlets in uBO have no guarantee that they will be injected before the page's script loads so if it's not working for you, then race condition on your end is prevalent.
