### ISSUE TITLE
worldoftruckstr.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#554]
### Test link (required): 
https://www.worldoftruckstr.com/ets-2-agir-nakliye-paketine-yeni-dorse-ve-yukler-ile-eskortlar-geliyor/
### Screenshot of the web page (required): 
![ets_2_agir_nakliye_paketine_yeni_dorse_ve_yukler_i_2017-09-01_13-24-26](https://user-images.githubusercontent.com/27441315/29967866-14726fe6-8f19-11e7-8473-d137d805a4c3.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww worldoftruckstr com_2017-09-01_13-24-33](https://user-images.githubusercontent.com/27441315/29967870-1be90438-8f19-11e7-823d-6e445f026a34.png)

**Comment by uBlock-user** [comment]
`worldoftruckstr.com##script:iject(abort-on-property-read.js, anOptions)`
