### ISSUE TITLE
tinano.com.br

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#555]
### Test link (required): 
https://tinano.com.br/2017/05/30/serial-kaspersky-total-security-2017/
### Screenshot of the web page (required): 
![serial_kaspersky_total_security_2017_-_tinano_anti_2017-09-01_13-39-16](https://user-images.githubusercontent.com/27441315/29968253-1160e52e-8f1b-11e7-9825-0547eb99eb1a.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpstinano com br20170530_2017-09-01_13-39-26](https://user-images.githubusercontent.com/27441315/29968250-0c0b9146-8f1b-11e7-91c7-042048afb03f.png)

**Comment by uBlock-user** [comment]
same as #554
