### ISSUE TITLE
gulmeklazim.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#556]
### Test link (required): 
https://www.gulmeklazim.com/Galeri/turkiye-sharp039-nin-en-guzel-25-kadini-karsinizda/6596/1/
### Screenshot of the web page (required): 
![turkiye nin_en_guzel_25_kadini_karsinizda__gulmek_2017-09-01_14-14-01](https://user-images.githubusercontent.com/27441315/29969347-f64bbbec-8f1f-11e7-85cf-9c17ed2bae1d.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww gulmeklazim comgale_2017-09-01_14-14-08](https://user-images.githubusercontent.com/27441315/29969339-f183f9bc-8f1f-11e7-8839-8d4f3f2c8d77.png)

**Comment by uBlock-user** [comment]
`gulmeklazim.com##script:inject(setTimeout-defuser.js, adblock)`
