### ISSUE TITLE
arenabg.com

### ISSUE THREAD

**Issue by Rusenche** [jspenguin2017/uBlockProtector#557]
Test link (required):
https://arenabg.com/torrents/

Screenshot of the web page (required):
http://store.picbg.net/pubpic/8A/FC/10f3ce358c018afc.png

Screenshot of the console (press F12 to bring up the console) (required):
http://store.picbg.net/pubpic/D7/B3/9a7969665b5bd7b3.png

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
You have too many extensions and scripts. Can't reproduce.
