### ISSUE TITLE
gntai.xyz

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#559]
### Test link (required): 
http://www.gntai.xyz/
### Screenshot of the web page (required): 
![gntai__manga_hentai_online__lector_hentai__desc_2017-09-02_22-36-12](https://user-images.githubusercontent.com/27441315/29998587-5aadb274-902f-11e7-8c31-c1cf19ed2ad2.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww gntai xyz_2017-09-02_22-36-20](https://user-images.githubusercontent.com/27441315/29998588-60dda51e-902f-11e7-80e2-7e571ffe863e.png)

**Comment by uBlock-user** [comment]
Setting `showAds` to `true` should do it.
