### ISSUE TITLE
wifihack.me

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#560]
### Test link (required): 
http://wifihack.me/
### Screenshot of the web page (required): 
![wifi_sifre_kirici_programi_indir__wifihack me_-_g_2017-09-02_23-13-13](https://user-images.githubusercontent.com/27441315/29998803-676252a4-9034-11e7-8b3e-467140173b5b.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwifihack me_2017-09-02_23-13-21](https://user-images.githubusercontent.com/27441315/29998804-6e43ca80-9034-11e7-9046-acd9d3e5ed27.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
