### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#561]
https://github.com/jspenguin2017/uBlockProtector/issues/60

https://player.pl/seriale-online/miasto-zla-odcinki,4104/odcinek-2,S00E02,56663.html
![image](https://user-images.githubusercontent.com/29756590/29999314-cb9f7ba2-9043-11e7-9334-d567854f5bed.png)
![image](https://user-images.githubusercontent.com/29756590/29999402-3c05d136-9047-11e7-88b4-0eccd1aa118a.png)

**Comment by jspenguin2017** [comment]
@HateAds I think I got it, can you test?

**Comment by adreporter** [comment]
Sorry but unfortunately it doesn't work.

**Comment by jspenguin2017** [comment]
So `11.219` didn't work? 
Hum... I need a proxy or something...

**Comment by jspenguin2017** [comment]
How do you bring up the player? 
![image](https://user-images.githubusercontent.com/7283682/29999738-0a455cb0-9011-11e7-8f4b-6b5aca474e6d.png)

**Comment by adreporter** [comment]
Yes, the latest version didn't work. I also cleared site cookies and cache, but it didn't work. Sorry but I can't help you with proxy.
Anyway I also seeing that and I'm clicking on "OGLĄDAJ" on the left, then this anti-adblock message is showing up:
https://user-images.githubusercontent.com/29756590/29999314-cb9f7ba2-9043-11e7-9334-d567854f5bed.png

**Comment by jspenguin2017** [comment]
Well, looks like I'm Geo Locked... 
![image](https://user-images.githubusercontent.com/7283682/29999826-df065b28-9013-11e7-9623-2af075f08838.png)

**Comment by HateAds** [comment]
@jspenguin2017 I can give you access to my NordVPN account if you want. (It has polish servers)

**Comment by jspenguin2017** [comment]
What this says? 
![image](https://user-images.githubusercontent.com/7283682/30003500-2259864a-907b-11e7-84ae-65bae7682b7b.png)

**Comment by jspenguin2017** [comment]
Does `11.221` works?

**Comment by HateAds** [comment]
The video doesn't play?
You have lost your internet connection or the display is suspended by the software blocking your ads. Switch them off or uninstall them to see what we have prepared for you.
Thanks to advertisements all materials are available free of charge.
Check how to disable ad blocking.

**Comment by HateAds** [comment]
@jspenguin2017 Yes it's working now.

**Comment by adreporter** [comment]
It's working now, thanks.
