### ISSUE TITLE
schieb.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#562]
http://www.schieb.de/topic/tipps

![1](https://user-images.githubusercontent.com/31142317/30005523-a9467b68-90e4-11e7-8db7-c05b13c16ec8.png)
![2](https://user-images.githubusercontent.com/31142317/30005524-a9658896-90e4-11e7-9b94-76af08e2f495.png)

**Comment by uBlock-user** [comment]
http://img.schieb.de/wp-content/uploads/PGtZFyhZdcZQ/gErgAUNTHtrw.js?ver=2.2.3

AdBlock Notify

**Comment by jspenguin2017** [comment]
I added a generic solution for AdBlock Notify, this should end this once for all.
