### ISSUE TITLE
cbs.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#567]
### Test link (required): 
http://www.cbs.com/shows/the_bold_and_the_beautiful/video/

### Screenshot of the web page (required): 
![the_bold_and_the_beautiful_video_-_912017_-_cbs _2017-09-04_20-05-48](https://user-images.githubusercontent.com/27441315/30035656-bf724c0a-91ac-11e7-8b3e-77dfeab61569.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww cbs comshowsthe_bol_2017-09-04_20-06-53](https://user-images.githubusercontent.com/27441315/30035746-a3b180f2-91ad-11e7-853e-3468bc33bc82.png)
![developer_tools_-_httpwww cbs comshowsthe_bol_2017-09-04_20-07-33](https://user-images.githubusercontent.com/27441315/30035747-a72c5162-91ad-11e7-82a6-f9a1acde8f78.png)

**Comment by uBlock-user** [comment]
Can't reproduce.

Has GeoLock.

**Comment by lain566** [comment]
Yes, Geo Lock from USA
