### ISSUE TITLE
einthusan.tv

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#568]
### Test link (required): 
https://einthusan.tv/launcher/?lang=telugu
https://einthusan.tv/intro/
### Screenshot of the web page (required): 
![disable_ad_blocker_-_einthusan_-_google_chrome_2017-09-04_21-11-18](https://user-images.githubusercontent.com/27441315/30036719-1670edaa-91b6-11e7-959b-9367461370ad.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpseinthusan tvadblocker_2017-09-04_21-14-04](https://user-images.githubusercontent.com/27441315/30036724-1bf18cee-91b6-11e7-840a-5431936d8bd6.png)

**Comment by uBlock-user** [comment]
GeoLocked, requires a VPN from US or UK.

**Comment by lain566** [comment]
Not for me.

**Comment by uBlock-user** [comment]
I get redirected to this page - https://einthusan.tv/blocked/?lang=

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/30037383-8ddc41bc-9177-11e7-9237-4d9a13b95a21.png)
![image](https://user-images.githubusercontent.com/7283682/30037386-92dd8b3a-9177-11e7-8909-20996e19eb26.png)

**Comment by lain566** [comment]
I keep getting redirected to https://einthusan.tv/adblocker/

**Comment by lain566** [comment]
`@@||einthusan.tv^$generichide` Works for me
