### ISSUE TITLE
warforum.cz

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#569]
### Test link (required): 
http://www.warforum.cz/
### Screenshot of the web page (required): 
![forum_-_w a r _forum_-_google_chrome_2017-09-04_21-17-20](https://user-images.githubusercontent.com/27441315/30036796-89a7652e-91b6-11e7-8e50-418ab1d23eb8.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww warforum cz_2017-09-04_21-17-28](https://user-images.githubusercontent.com/27441315/30036803-8f4cdc20-91b6-11e7-9e31-48a54ec28817.png)

**Comment by uBlock-user** [comment]
bait - http://www.warforum.cz/ads.js?

ads.js v2

Also add - `warforum.cz###popwrapper`
