### ISSUE TITLE
infoua.biz

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#570]
### Test link (required): 
http://infoua.biz/live/431
### Screenshot of the web page (required): 
![brazzers_tv_europe_ 18 _russia _belarus_-_infoua_2017-09-03_10-46-48](https://user-images.githubusercontent.com/27441315/30036869-1be53c7c-91b7-11e7-90cf-e22047edfd0c.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpinfoua bizlive431_2017-09-03_10-46-57](https://user-images.githubusercontent.com/27441315/30036883-2b580ad6-91b7-11e7-9727-840511312470.png)

**Comment by uBlock-user** [comment]
bait - http://infoua.biz/advertising.js

requires VLC plugin/ Flash ???

**Comment by lain566** [comment]
Yes that seems

**Comment by uBlock-user** [comment]
http://infoua.biz/js/code/_at.js
