### ISSUE TITLE
kisscartoon.io

### ISSUE THREAD

**Issue by sed-** [jspenguin2017/uBlockProtector#572]
### Test link (required): 
https://kisscartoon.io/Cartoon/Rick-and-Morty-Season-3/Episode-006-Rest-and-Ricklaxation?id=76077
### Screenshot of the web page (required): 
 https://i.imgur.com/pwmh044.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
 https://i.imgur.com/vHkysod.png

**Comment by uBlock-user** [comment]
```javascript
if (window.check_adblock === undefined) {
--
  | $("#player_container").html('<div class="error_movie alert alert-warning notice" role="alert"><h4>Please Disable Your AdBlock</h4><p style="color:red;   font-weight: normal;">Video will be visible once you whitelist kisscartoon.io on your adblocker.</p></div>');
  | } else {
  | request_link();
  | }

```
https://kisscartoon.io/js/ads.js?v=1.1

`a.bait("div", "#player_container")`; should do it.

**Comment by sed-** [comment]
ty that seems to of worked :).

**Comment by jspenguin2017** [comment]
I see `@@||kisscartoon.io^$first-party,script` in uBlock filters.

**Comment by uBlock-user** [comment]
For hyperlink popups - `kisscartoon.*##script:inject(abort-current-inline-script.js, eval, catch(l))`

**Comment by jspenguin2017** [comment]
Can't reproduce popup.
