### ISSUE TITLE
shortzero.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#573]
### Test link (required): 
http://shortzero.com/eUSvEZ

### Screenshot of the web page (required): 
https://i.imgur.com/sumo55e.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/8XDkodh.png

**Comment by uBlock-user** [comment]
bait - http://shortzero.com/js/ads.js

`shortzero.com##script:inject(setTimeout-defuser.js, checkAdblockUser)`

**Comment by titosalah** [comment]
[jspenguin2017 ](https://github.com/jspenguin2017)  thank u very much my bro
