### ISSUE TITLE
randaris-anime.net

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#574]
### Test link (required): 
http://randaris-anime.net/serie/episode/sengoku-basara-episode/12/986/de-sub
### Screenshot of the web page (required): 
![anime_sengoku_basara_-_episode_12_-_randaris-anim_2017-09-06_11-31-57](https://user-images.githubusercontent.com/27441315/30104915-44505368-92f7-11e7-8488-9249890f5fb2.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httprandaris-anime netserie_2017-09-06_11-33-01](https://user-images.githubusercontent.com/27441315/30104922-49551e66-92f7-11e7-9cec-2f9bbcceba39.png)

**Comment by uBlock-user** [comment]
I can only reproduce the adblock notice, not the adblock overlay on the video.

for notice - `randaris-anime.net##.adblock-box`
