### ISSUE TITLE
lolskinlistgenerator.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#575]
### Test link (required): 
http://www.lolskinlistgenerator.com/
### Screenshot of the web page (required): 
![lol_skin_list_generator_-_new_ 2018 _-_google_chro_2017-09-06_11-35-42](https://user-images.githubusercontent.com/27441315/30105026-aeaa33e6-92f7-11e7-8c57-98917231f4ad.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww lolskinlistgenerator _2017-09-06_11-35-51](https://user-images.githubusercontent.com/27441315/30105039-b480f08e-92f7-11e7-923a-0cc52f02f5b2.png)

**Comment by uBlock-user** [comment]
`lolskinlistgenerator.com##script:inject(abort-current-inline-script.js, $, adblock)`
