### ISSUE TITLE
reviewmeta.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#576]
### Test link (required): 
https://reviewmeta.com/amazon-uk/B019IYUZ1W
### Screenshot of the web page (required): 
![warn_bearded_ben_premium_quality_teak_beard_brush_2017-09-06_12-30-18](https://user-images.githubusercontent.com/27441315/30107527-52595268-92ff-11e7-9845-672b21424772.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpsreviewmeta comamazon-uk_2017-09-06_12-30-26](https://user-images.githubusercontent.com/27441315/30107534-56d510d4-92ff-11e7-861f-d722c8a973bd.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
