### ISSUE TITLE
urltocloud.nsspot.net

### ISSUE THREAD

**Issue by gavbn** [jspenguin2017/uBlockProtector#577]
### Screenshot of the web page (required): 

https://user-images.githubusercontent.com/23123477/30119552-b94798b0-9343-11e7-9e77-2ec4a9c366d1.PNG

### Screenshot of the console (press `F12` to bring up the console) (required): 

https://user-images.githubusercontent.com/23123477/30119772-6e60b88a-9344-11e7-8d11-bcd5c17979ae.PNG

### Add everything else that you believe to be useful below (optional): 
it prevents me from uploading any file to google drive

**Comment by uBlock-user** [comment]
same as https://github.com/jspenguin2017/uBlockProtector/issues/445
