### ISSUE TITLE
cbs.com

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#578]
https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/229

http://www.cbs.com/shows/big_brother/video/ClDvh7FriAH8tpA67A4iRBqJXLtW9kjF/big-brother-episode-32/

Geo lock: US (TunnelBear works)
Seems to only occur on the first page load, goes away if refreshed. 

![image](https://user-images.githubusercontent.com/7283682/30144223-14baf2e8-9347-11e7-85c3-3fe7473c6d85.png)

Nothing interesting in console.

**Comment by uBlock-user** [comment]
I don't see that adblock warning if I add `@@||cbscom^$elemhide`

**Comment by jspenguin2017** [comment]
`elemhide` is mapped to `generichide` I think, didn't quite work for me.

**Comment by uBlock-user** [comment]
Ofcourse, `elemhide` is only for comfort, in reality it's `generichide`.

**Comment by jspenguin2017** [comment]
Either way, it's not working for me. The video does play once I refresh though.

**Comment by jspenguin2017** [comment]
Add an auto reload. Good enough for now.
