### ISSUE TITLE
platinmods.com

### ISSUE THREAD

**Issue by xchannels** [jspenguin2017/uBlockProtector#579]
### Screenshot of the web page (required): 
![image](https://user-images.githubusercontent.com/20967118/30175053-7f4378b8-93fd-11e7-9cde-90833377b800.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![image](https://user-images.githubusercontent.com/20967118/30175073-8fabe3ac-93fd-11e7-9ea6-487365e1cf08.png)

### Add everything else that you believe to be useful below (optional): 
An anti-adblock appear on home page. Only happen for guest visitors. I tried to bypass it but no luck
Note: I had to open private mode because i'm already logged in

**Comment by uBlock-user** [comment]
Can't reproduce.

You don't seem to have the Extension installed/activated as per your console picture.
