### ISSUE TITLE
androidsage.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#580]
### Test link (required): 
https://www.androidsage.com/
### Screenshot of the web page (required): 
![httpswww androidsage com_-_google_chrome_2017-09-07_21-39-43](https://user-images.githubusercontent.com/27441315/30181924-45d05fca-9415-11e7-8001-0e44e8cc5115.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww androidsage com_2017-09-07_21-39-53](https://user-images.githubusercontent.com/27441315/30181928-49448f64-9415-11e7-8e9f-2cc3a40b2291.png)

**Comment by uBlock-user** [comment]
script

`<script type='text/javascript'>function blckad(){function htmlUnescape(a){return a.replace(/"/g,'"').replace(/'/g,"'").replace(/</g,"<").replace(/>/g,">").replace(/&amp;/g,"&")}var blcode=htmlUnescape("<div id=\"n1234Upuomdvk1uLkPy7bdg7DB5BQx\" style=\"position: fixed; left: 0px; top: 0px; width: 100%; height: 100%; background-color: #444444; z-index: 9999;\">&nbsp;</div>\n<div id=\"MPFVxIsDxKR6dRCm3iyyBqWeHcU6HQ\" style=\"position: relative; top: 71.2857px; background-color: #ffffff; z-index: 10000; font-family: 'Arial Black', Helvetica, geneva, sans-serif !important; line-height: normal !important; font-size: 16pt !important; text-align: center !important; padding: 12px !important; display: block; margin-left: 20px; margin-right: 20px; border-radius: 15px; box-shadow: rgba(0, 0, 0, 0.3) 0px 14px 24px -8px; visibility: visible;\">\n<h3 style=\"color: #000000; font-size: 30pt; font-family: Helvetica, geneva, sans-serif; font-weight: 200; margin-top: 10px; margin-bottom: 10px;\">Welcome, my precious visitor!</h3>\n<h1 style=\"font-size: 22pt; font-weight: 500; color: #000000; margin-top: 10px; margin-bottom: 10px;\">It looks like you're using an ad blocker. Whitelist to view full content.</h1>\n<hr style=\"display: block; border: 1px solid #CCC; width: 25%; margin: 0.5em auto 0.5em auto;\" />\n<p style=\"font-family: Helvetica, geneva, sans-serif; font-weight: 300; font-size: 18pt; color: #000000;\">All content may not be visible while Ad-blockers are on. Some of the important files or content may get hidden. Be assured, that you'll not get annoyed by the ads.</p>\n<p style=\"margin-top: 35px;\">&nbsp;</p>\n<div onclick=\"window.location.reload();\"id=\"UKhSyMEsVA011xZDJS432ITL2Lu41s\" style=\"cursor: pointer; font-size: 18pt; font-family: Helvetica, geneva, sans-serif; font-weight: 300; border-radius: 15px; padding: 10px; background-color: #5ab878; color: #ffffff; padding-left: 60px; padding-right: 60px; width: 60%; max-width: fit-content; margin: auto; margin-top: 10px; margin-bottom: 10px;\">Please click here after you have disabled your adblocker on this site.</div>\n<p>&nbsp;</p>\n</div>");window.stop();document.open();document.write(htmlUnescape(blcode));}</script><script async='true' onerror='setTimeout(blckad,5000);' src='//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js'></script>`

`androidsage.com##script:inject(abort-on-property-read.js, stop)`
