### ISSUE TITLE
link-cash.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#582]
### Test link (required): 
http://link-cash.com/Etisalat

### Screenshot of the web page (required): 
https://i.imgur.com/ueOMUHd.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/nzIJMKn.png

**Comment by uBlock-user** [comment]
`link-cash.com##script:inject(setTimeout-defuser.js, checkAdblockUser)`
