### ISSUE TITLE
peliculasmega.info

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#583]
### Test link (required): 
http://peliculasmega.info/desacrgar-pelicula-descendants-2-mega-gratis/
### Screenshot of the web page (required): 
![autocombinacion_-_webmaster_workers_-_google_chrom_2017-09-09_13-17-15](https://user-images.githubusercontent.com/27441315/30239637-80a86514-9561-11e7-85ad-cf6b922b548c.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww webmasterworkers info_2017-09-09_13-17-25](https://user-images.githubusercontent.com/27441315/30239641-879fa102-9561-11e7-9eb8-bd1a2eea49fa.png)

### Add everything else that you believe to be useful below (optional): 
Scroll down and click on button  `VER ENLACES DE DESCARGA POR 48 HS` [Screenshot](https://user-images.githubusercontent.com/27441315/30239749-62fa7bd6-9563-11e7-993e-e38e6091052c.png)

 will open a popup and this warning appears
`Click on the advertising and wait 30 seconds will see links of downloads during 48 hours`

**Comment by uBlock-user** [comment]
----> #472
