### ISSUE TITLE
mega-estrenos.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#584]
### Test link (required): 
http://www.mega-estrenos.com/descargar-carrie-pilby-2017-mega-castellano-1-link-1080p/
### Screenshot of the web page (required): 
![descargar_carrie_pilby_ 2017 mega castellano 1__2017-09-09_13-40-22](https://user-images.githubusercontent.com/27441315/30239869-458cdec0-9565-11e7-9bdb-1a3252049fd3.png)
![_protector_de_enlaces__-_google_chrome_2017-09-09_13-40-51](https://user-images.githubusercontent.com/27441315/30239870-4c4e0360-9565-11e7-901b-ebccf9423931.png)
![los_mejores_hosting_del_2015_ _global_best_hosting_2017-09-09_13-41-05](https://user-images.githubusercontent.com/27441315/30239835-bec3e7ee-9564-11e7-8090-b885ea73442a.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpglobalbesthosting comlos_2017-09-09_13-41-22](https://user-images.githubusercontent.com/27441315/30239839-cd704666-9564-11e7-9a96-6919136e7c8c.png)

### Add everything else that you believe to be useful below (optional): 
Similar to https://github.com/jspenguin2017/uBlockProtector/issues/583

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by lain566** [comment]
@jspenguin2017 It's broken.

**Comment by jspenguin2017** [comment]
It still works for me.

**Comment by lain566** [comment]
@jspenguin2017 Ok.

**Comment by lain566** [comment]
It's broken 
Test link:
`https://www.mega-estrenos.org/descargar-1517-tren-a-paris-2018-mega-latino-1-link-hd/`

<details>Click on VER ENLACES DE DESCARGA POR 48 HS

Then a message appears: Click on the advertising and wait 30 seconds will see links of downloads during 48 hours.

![descargar_1517_tren_a_paris_ 2018 mega latino _2018-05-05_15-09-25](https://user-images.githubusercontent.com/27441315/39663680-f60cec2c-5077-11e8-8072-76be2518e660.png)

-----------------------
It should look like this
![espere_1_segundos_-_iron_2018-05-05_15-23-35](https://user-images.githubusercontent.com/27441315/39664039-6bfb2a84-507d-11e8-974c-86357cc3f8a3.png)

</details>

**Comment by jspenguin2017** [comment]
@okiehsch
