### ISSUE TITLE
stern.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#585]
http://www.stern.de/tv/verkaeufer-aufgepasst--mit-diesem-trick-zocken-betrueger-ueber-paypal-ab-7607550.html

![1](https://user-images.githubusercontent.com/31142317/30240619-131c6ef6-9574-11e7-9966-2f043a8467ed.png)
![2](https://user-images.githubusercontent.com/31142317/30240620-13392be0-9574-11e7-9703-5582eb7c997a.png)

**Comment by jspenguin2017** [comment]
It goes away when refreshed. Not sure what controls it though...

**Comment by uBlock-user** [comment]
https://static.stern.de/resources/7496776/2/mms-client.js
https://static.stern.de/resources/7496770/2/msg.js

**Comment by uBlock-user** [comment]
stern.de##script:inject(abort-on-property-read.js, _sp_)
