### ISSUE TITLE
solidfiles.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#587]
### Test link (required): 
http://www.solidfiles.com/d/8d8f5eaac7/
https://www.solidfiles.com/d/f6745c0e00/
### Add everything else that you believe to be useful below (optional): 
Could you remove popups,? Can not download if popup doesn't open.

**Comment by uBlock-user** [comment]
`solidfiles.com##script:inject(abort-on-property-read.js, open)`

Works for me

**Comment by lain566** [comment]
Yes, that works for me.  I don't really know what was fixed.

**Comment by jspenguin2017** [comment]
Ops wrong domain

**Comment by lain566** [comment]
@jspenguin2017 Your filter not working for me. I still have popups, and if I use a Popup Blocker, it cannot be downloaded.

**Comment by jspenguin2017** [comment]
You're right, that doesn't work. I did tested it though, not sure how.

**Comment by lain566** [comment]
@jspenguin2017 It's working fine now, thanks.

**Comment by lain566** [comment]
@jspenguin2017 It seems that this has been solved in `uBlock filters` list
```
https://github.com/uBlockOrigin/uAssets/commit/80295a14629b199cfd34c5c5441972fe17e7da06

https://github.com/uBlockOrigin/uAssets/commit/743dde0392c543b108e14ab8cdcaec6402e20c95

```
There are many repeat solutions...

```
https://github.com/uBlockOrigin/uAssets/commit/65af9b89ad5268da062ed0b379aa16082121dbc5

https://github.com/jspenguin2017/uBlockProtector/commit/d7368568ce2d8ce2e6757905d7acc98deae59e25
```
