### ISSUE TITLE
behindwoods.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#588]
### Test link (required): 
http://www.behindwoods.com/english-movies/doctor-strange/doctor-strange-review.html
### Screenshot of the web page (required): 
![doctor_strange_ aka _dr strange_review_-_google_ch_2017-09-10_13-07-59](https://user-images.githubusercontent.com/27441315/30248555-2d23e4d0-962a-11e7-8c89-cd712c82ba1f.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww behindwoods comengli_2017-09-10_13-08-44](https://user-images.githubusercontent.com/27441315/30248557-347962fa-962a-11e7-83b5-d52452e5e366.png)

**Comment by uBlock-user** [comment]
https://github.com/reek/anti-adblock-killer/issues/2598
