### ISSUE TITLE
prevention.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#589]
### Test link (required): 
https://www.prevention.com/health/health-concerns/heart-attack-7-signs-youre-having-heart-attack
### Screenshot of the web page (required): 
![7_signs_you re_having_a_heart_attack__prevention__2017-09-10_12-54-22](https://user-images.githubusercontent.com/27441315/30248397-5c73efc6-9627-11e7-87bf-5ff10df51760.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww prevention comhealt_2017-09-10_12-54-30](https://user-images.githubusercontent.com/27441315/30248398-60433dc8-9627-11e7-9f9c-430d8bb4aba9.png)

**Comment by jspenguin2017** [comment]
`dataLayer[0].AdBlockerDetected=dataLayer_gtm[0].AdBlockerDetected=false;`
It's kind of long and it has a good chance to change on server side. Maybe I should white list. I need to think about that.

**Comment by uBlock-user** [comment]
`prevention.com##script:inject(setTimeout-defuser.js, adblock)`

**Comment by uBlock-user** [comment]
old one - https://github.com/uBlockOrigin/uAssets/issues/260
