### ISSUE TITLE
youku.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#590]
### Test link (required): 
http://v.youku.com/v_show/id_XMzAxNjQwMzg3Ng==.html

### Screenshot of the web page (required): 
![_ _ __ fight_of_gods_2017-09-10_19-48-36](https://user-images.githubusercontent.com/27441315/30251530-6514a230-9661-11e7-85be-4f197837996a.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpv youku comv_showid_xmz_2017-09-10_19-49-30](https://user-images.githubusercontent.com/27441315/30251533-71648d98-9661-11e7-88c0-ab92eca7bad5.png)
![developer_tools_-_httpv youku comv_showid_xmz_2017-09-10_19-50-11](https://user-images.githubusercontent.com/27441315/30251535-75530c22-9661-11e7-9b0c-3ff4766b1f10.png)

### Add everything else that you believe to be useful below (optional): 
I'm not sure if it's an anti-adblock warning, I can play the video if I add it to white list.
If it's not an anti-adblock warning, please close issue

**Comment by jspenguin2017** [comment]
It says you must enable Cookies. 
![image](https://user-images.githubusercontent.com/7283682/30251688-38e76bd2-9622-11e7-889f-35ac17d0c960.png)

**Comment by uBlock-user** [comment]
Can't reproduce any anti adblock or cookie overlay either.
