### ISSUE TITLE
artesacro.org

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#591]
### Test link (required): 
http://www.artesacro.org/
### Screenshot of the web page (required): 
![portada_artesacro_10092017_-_google_chrome_2017-09-10_21-07-38](https://user-images.githubusercontent.com/27441315/30252076-69119270-966c-11e7-9b20-d8867c40a782.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww artesacro org_2017-09-10_21-07-47](https://user-images.githubusercontent.com/27441315/30252079-6d78dcc4-966c-11e7-8e97-77c1a161e4b8.png)

**Comment by uBlock-user** [comment]
`artesacro.org##script:inject(setTimeout-defuser.js, adsbygoogle)`
