### ISSUE TITLE
solowrestling.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#592]
### Test link (required): 
https://www.solowrestling.com/new/64091-karen-jarrett-agradece-el-apoyo-recibido-a-jeff-jarrett
### Screenshot of the web page (required): 
![karen_jarrett_agradece_el_apoyo_recibido_a_jeff_ja_2017-09-10_21-16-13](https://user-images.githubusercontent.com/27441315/30252165-7a03cb7e-966d-11e7-9307-09bd8ed0005e.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww solowrestling comne_2017-09-10_21-16-22](https://user-images.githubusercontent.com/27441315/30252166-7dfc625e-966d-11e7-9afb-fedb567ab84e.png)

**Comment by uBlock-user** [comment]
solowrestling.com##script:inject(abort-current-inline-script.js, document.getElementById, ad_banner)
