### ISSUE TITLE
kshowes.net

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#593]
### Test link (required): 
http://www.kshowes.net/2017/09/fantastic-duo-season-2-ep-23-sub-esp.html
### Screenshot of the web page (required): 
![fantastic_duo_season_2_ep_23_sub_esp__kshowes net_2017-09-10_21-34-15](https://user-images.githubusercontent.com/27441315/30252289-f9dcf760-966f-11e7-9ed7-d195f0f72cb8.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww kshowes net201709f_2017-09-10_21-33-32](https://user-images.githubusercontent.com/27441315/30252290-ff9cfc22-966f-11e7-806d-4014331de2c4.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
