### ISSUE TITLE
turkdown.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#595]
http://turkdown.com/
http://cbox.turkdown.com/checkdigger/
<img width="304" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/30294156-708a8f68-973c-11e7-935d-161facb2a13b.PNG">
<img width="516" alt="przechwytywanie3" src="https://user-images.githubusercontent.com/18214146/30294332-01eb0eb0-973d-11e7-9d9c-8f5423f413aa.PNG">
<img width="391" alt="przechwytywanie1" src="https://user-images.githubusercontent.com/18214146/30294162-73d6085a-973c-11e7-9d98-b0d596c7d5e8.PNG">

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
test

**Comment by adreporter** [comment]
@jspenguin2017 
http://cbox.turkdown.com/checkNetworks/
<img width="304" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/30294156-708a8f68-973c-11e7-935d-161facb2a13b.PNG">
Can you reproduce?

**Comment by jspenguin2017** [comment]
Nope.

**Comment by HateAds** [comment]
Weird. I can reproduce.

**Comment by jspenguin2017** [comment]
OK, I'll test it tomorrow. I put it on my backlog.

**Comment by jspenguin2017** [comment]
Reloaded all the filters, updated everything, still can't reproduce.
