### ISSUE TITLE
tmearn.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#596]
http://tmearn.com/915y
<img width="288" alt="1" src="https://user-images.githubusercontent.com/18214146/30333549-78f37d80-97dd-11e7-85ab-c75f2eac9705.PNG">
<img width="408" alt="2" src="https://user-images.githubusercontent.com/18214146/30333555-7bb61226-97dd-11e7-8a87-6ad97df53c80.PNG">

**Comment by jspenguin2017** [comment]
It says 404.

**Comment by adreporter** [comment]
Try http://tmearn.com/FeO3g

**Comment by adreporter** [comment]
@jspenguin2017 Now it should be online.

**Comment by adreporter** [comment]
@jspenguin2017 It's online now.

**Comment by adreporter** [comment]
Yea, the website had some problems, but it should be online now.

**Comment by uBlock-user** [comment]
Works for me.

`tmearn.com##script:inject(setTimeout-defuser.js, checkAdblockUser)`

**Comment by titosalah** [comment]
works for me
