### ISSUE TITLE
cuturlink.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#598]
### Test link (required): 
http://cuturlink.com/TyinUPF
### Screenshot of the web page (required): 
https://i.imgur.com/VQbGt71.png
### Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/xCn5rEi.png

**Comment by uBlock-user** [comment]
same as #183

**Comment by okiehsch** [comment]
I would remove the clickable link, it actually automatically opens a download-dialog, trying to download some malicious file using Chrome.
`cuturlink.com##script:inject(abort-on-property-write.js, Fingerprint2)` disables that crap.
