### ISSUE TITLE
shorteurl.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#599]
http://shorteurl.com/FakirDebridToplamLimit
<img width="288" alt="1" src="https://user-images.githubusercontent.com/18214146/30333549-78f37d80-97dd-11e7-85ab-c75f2eac9705.PNG">
<img width="399" alt="1" src="https://user-images.githubusercontent.com/18214146/30353167-a6dc3ee8-9824-11e7-9e99-de03ff483542.PNG">

**Comment by jspenguin2017** [comment]
How many domains do they have...

**Comment by uBlock-user** [comment]
another #183 clone

These clones keep popping using the exact same script and the CSS, won't even bother to change anything
