### ISSUE TITLE
forbes.com

### ISSUE THREAD

**Issue by gotitbro** [jspenguin2017/uBlockProtector#600]
The **uBlock Protector** extension's current solution to bypass the Forbes anti adb measure includes redirecting the user to the [Forbes homepage](https://www.forbes.com/) ([Solution](https://github.com/jspenguin2017/uBlockProtector/blob/11516073a487fc5a21f4829cf1f526cbd614d066/Extension%20Compiler/Extension/content/content-rules-specific.js#L229)).  

This is really inconvenient as the user will have to find his way back to the original URL they visited from the homepage. It also happens that Forbes shows the Welcome screen once in a while so a frequent visitor to Forbes will be redirected to the homepage multiple times making the solution not completely viable.

I recommend removing the fix for Forbes as uBO handles it very well on its own, redirecting to the original page visited by the user making navigation much more smoother ([uBO's Solution](https://github.com/uBlockOrigin/uAssets/blob/871014de24445992c370b124f4fad68dc4b816a7/filters/resources.txt#L599)).

**Error URL:**  
https://www.forbes.com/sites/ywang/2017/09/12/why-iphone-x-isnt-the-answer-to-apples-china-problem/ (Visit the page with no previous cookies of Forbes.com)

_**Note:** Using uBO 1.14.8 on Chrome 61 with the default filters and settings along with uBlock Protector._

**Comment by jspenguin2017** [comment]
The rule is inherited from AAK and I didn't properly test it. It is now removed.

**Comment by gotitbro** [comment]
@jspenguin2017 Oh that's fine, thanks for removing it. I wonder if there are any other deprecated AAK rules in uBlock Protector.

**Comment by jspenguin2017** [comment]
There are over 2000 rules that I have not checked, and there are rules that are outdated. 

Most of the rules that are not checked are here: 
https://github.com/jspenguin2017/uBlockProtector/blob/master/List%20Compiler/List/6-other.txt

Work smart, not hard, this needs to be automated somehow...

**Comment by uBlock-user** [comment]
> There are over 2000 rules that I have not checked, and there are rules that are outdated.

In the List or in the Extension or in both ?

**Comment by jspenguin2017** [comment]
Mostly in List.

**Comment by gotitbro** [comment]
@jspenguin2017 Here is a harsh but effective suggestion. These old rules can be harmful in many ways this issue is an example of that. 

So, I suggest removing all unchecked/untested filters and as issues come in we can check if the old filter still works and can add that no further investigation required. And if it doesn't or breaks something the usual testing can be done.

We have to realize that uBlock Protector is now much more than AAK. 

Or we can all just test the all those filters.

**Comment by uBlock-user** [comment]
Removing Reek's rules in List and Extensions should be enough, they're deprecated in most cases and will only cause issues moving further.

**Comment by gotitbro** [comment]
@uBlock-user That is what I meant :)

**Comment by jspenguin2017** [comment]
It is like 70% of my rules, I can't just dump all that out...

**Comment by gotitbro** [comment]
@jspenguin2017 You're right, maybe we can check the filters one by one which is time consuming or test which website filters get a hit when the websites are visited that should preen out most of the useless ones.

**Comment by jspenguin2017** [comment]
Checking them one by one is likely to not work as we don't know which path to check. And checking 2000 rules is no easy task. I have to leave them as-is for now, let me know if you have further concerns.

**Comment by gotitbro** [comment]
@jspenguin2017 Alright but we can still report ones that cause issues right?

**Comment by jspenguin2017** [comment]
Yes, I'll fix them, you can report redundant filters too, but make sure to properly test them as they are not always reproducible on the home page.
