### ISSUE TITLE
lavozdealmeria.es

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#602]
### Test link (required): 
http://www.lavozdealmeria.es
### Screenshot of the web page (required): 
![default la_voz_de_almeria _-_google_chrome_2017-09-14_10-34-51](https://user-images.githubusercontent.com/27441315/30419973-7cc424f8-9938-11e7-8c90-2d9b8f000235.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww lavozdealmeria esavi_2017-09-14_10-35-04](https://user-images.githubusercontent.com/27441315/30419980-824d2bea-9938-11e7-827d-9456151f1f18.png)

**Comment by uBlock-user** [comment]
http://www.lavozdealmeria.es/js/addblock.js
