### ISSUE TITLE
linkkawy.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#603]
http://linkkawy.com/GCtI
<img width="213" alt="2" src="https://user-images.githubusercontent.com/18214146/30487745-a4974936-9a34-11e7-91c2-8fac3d5fed0c.PNG">
<img width="960" alt="1" src="https://user-images.githubusercontent.com/18214146/30487747-a6f0211c-9a34-11e7-9d8a-6d6675d2c30d.PNG">

**Comment by uBlock-user** [comment]
another #183 clone
