### ISSUE TITLE
NSFW! getrelax.club

### ISSUE THREAD

**Issue by kekwowse01** [jspenguin2017/uBlockProtector#604]
### Test link (required): 
http://en.getrelax.club/javpreview/24500_GetRelax_JAV_T-28513_%E4%B8%AD%E5%87%BA_%E5%96%AE%E9%AB%94%E4%BD%9C%E5%93%81_%E8%98%BF%E8%8E%89%E5%A1%94_%E4%BA%82%E5%80%AB_%E5%A6%B9%E5%A6%B9_%E4%BD%90%E3%80%85%E6%B3%A2%E7%B6%BE_T-28513.html

### Screenshot of the web page (required): 
![2017-09-16_010134](https://user-images.githubusercontent.com/20890266/30509617-f36727f2-9a7a-11e7-9ef1-77b54195dced.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2017-09-16_010235](https://user-images.githubusercontent.com/20890266/30509618-fb387ec2-9a7a-11e7-86ae-fdb84ac693c3.png)

**Comment by uBlock-user** [comment]
script


```javascript
var ad_height;
--
  | if ($('.google-ad').height() <= 0){
  | $('#adisblock').show();
  | }
```

**Comment by uBlock-user** [comment]
```
@@||getrelax.club^$elemhide
getrelax.club##.loaded-popup-wrapper
```
