### ISSUE TITLE
mycinema.pro

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#605]
### Test link (required): 
https://www.mycinema.pro/options.html
### Screenshot of the web page (required): 
![0002017-09-16_232823](https://user-images.githubusercontent.com/2828165/30516157-e03dcd2c-9b36-11e7-9a31-f83a546e1456.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![0002017-09-16_232857](https://user-images.githubusercontent.com/2828165/30516159-e7bdeb7c-9b36-11e7-9288-02d83227dd66.png)

**Comment by jspenguin2017** [comment]
It looks like it is an YouTube related extension that request permission for all websites, sounds like it inserts ads from extension. Unfortunately, uBlock Protector cannot protect yourself from adware you install.

**Comment by jspenguin2017** [comment]
I'm not sure why the extension isn't using an extension page for options, I assume it will inject its options to the empty `adv_config` div, if that doesn't work I don't really have a solution since I have no way to patch another extension.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
`content_security_policy": "default-src 'self';img-src 'self';connect-src 'self' https://www.mycinema.pro https://www.google-analytics.com https://clients2.google.com;frame-ancestors 'self' https://www.mycinema.pro https://*.youtube.com;report-uri https://appn.center/apiv1/csp;",`

Though looking at its CSP policy in the `manifest.json` It will be sending your browser data to Google Analytics and will be sending spurious CSP reports to `appn.center` If you're the user, you should remove this extension asap.

**Comment by jspenguin2017** [comment]
That is a reasonable CSP for an average extension. The thing that is suspicious is that the extension requests permission for all web sites.

**Comment by uBlock-user** [comment]
Not reasonable if you care about spyware and privacy of your browsing session.

**Comment by jspenguin2017** [comment]
You care about privacy, I do too, but it's not the norm to care about privacy of users. 
Also, uBlock Origin is not able to block privileged requests from another extension.

**Comment by uBlock-user** [comment]
Ofcourse it's not the norm. It's the user's job to care about his/hers privacy. 

>  uBlock Origin is not able to block privileged requests from another extension

It used to on Firefox, Chromium specifically disallows that feature and now since WebExtensions are the norm, FF won't be able to either. Also, I simply don't install extensions which make suspicious `behind-the-scene` requests. Only trustwoethy extensions like uBO, uMatrix and yours are allowed to run on my device.

**Comment by jspenguin2017** [comment]
There is no feedback, so I assume this is fixed?

**Comment by uBlock-user** [comment]
I don't know about the OP, but my feedback is present in https://github.com/jspenguin2017/uBlockProtector/issues/605#issuecomment-330019716
