### ISSUE TITLE
digitalinformationworld.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#606]
### Test link (required): 
http://www.digitalinformationworld.com/2017/09/what-is-internet-video.html
### Screenshot of the web page (required): 
![what_is_the_internet_ video __digital_informatio_2017-09-18_19-08-15](https://user-images.githubusercontent.com/27441315/30554442-cfb6e8f2-9ca4-11e7-9591-e97d102ab05e.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww digitalinformationwor_2017-09-18_19-08-29](https://user-images.githubusercontent.com/27441315/30554445-d4c98142-9ca4-11e7-83ee-09d65d33ba6d.png)

**Comment by uBlock-user** [comment]
`digitalinformationworld.com##script:inject(abort-on-property-read.js, adsbygoogle)`

**Comment by xxxdepy** [comment]
What's going on in here? Some kind of scam?

**Comment by jspenguin2017** [comment]
@xxxdepy If you have more concrete proofs, I'm happy to discuss that, otherwise, this is a warning.

**Comment by uBlock-user** [comment]
The issue tracker is attracting weirdos lately, I wonder why.

**Comment by xxxdepy** [comment]
The console errors are due to the fact that you have AdBlocker on your browser and the extension is blocking the ad service's resources, this isn't an issue. What concrete proof do you need other than the exact written text in the console errors.

**Comment by xxxdepy** [comment]
@uBlock-user weirdos are you people who sends out email to random site owners telling them they have errors on your site, this is not why GitHub's issue tracker is made for. 

The real weirdos and parasites are you people. And the site in question is a site that I maintain.

**Comment by jspenguin2017** [comment]
@xxxdepy uBlock Protectors shows debug logs to console.

**Comment by uBlock-user** [comment]
@jspenguin2017 Kick him out, he's the owner of the aformentioned website and he's pissed off because the anti adblock script got patched, so now he comes here to vent his hate and stupidity.
