### ISSUE TITLE
okkazeo.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#607]
### Test link (required): 
https://www.okkazeo.com/jeux/view/20020/193096/Clout-Fantasy---starter-Elfes-et-Morts-vivants
### Screenshot of the web page (required): 
![acheter_clout_fantasy_-_starter_elfes_et_morts-viv_2017-09-18_20-37-17](https://user-images.githubusercontent.com/27441315/30558327-511f0d50-9cb1-11e7-8924-72b8df10b6d8.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww okkazeo comjeuxvie_2017-09-18_20-37-26](https://user-images.githubusercontent.com/27441315/30558314-49f28d0e-9cb1-11e7-8808-e2368e73d54f.png)

**Comment by uBlock-user** [comment]
`okkazeo.com###ads`
