### ISSUE TITLE
cut-egy.ml

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#609]
### Test link (required): 
http://cut-egy.ml/xlyT
### Screenshot of the web page (required): 
![2017-09-19_121859](https://user-images.githubusercontent.com/2828165/30587852-e7c02c98-9d34-11e7-9cd6-46f3534b2bde.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2017-09-19_121921](https://user-images.githubusercontent.com/2828165/30587869-f3b332d4-9d34-11e7-965e-6c9df67e9b14.png)

**Comment by uBlock-user** [comment]
same as #183
