### ISSUE TITLE
babbel.com

### ISSUE THREAD

**Issue by spec1re** [jspenguin2017/uBlockProtector#610]
### Test link (required): 

https://my.babbel.com/de/learning/#learn_languages/ITA/review?return_url=https%3A%2F%2Fhome.babbel.com%2Fdashboard

### Screenshot of the web page (required): 
![image](https://user-images.githubusercontent.com/11883076/30595869-c6c637da-9d52-11e7-8583-0b68c9e39266.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![image](https://user-images.githubusercontent.com/11883076/30596191-b60cd2a4-9d53-11e7-9286-77d42fc5c9d2.png)

### Add everything else that you believe to be useful below (optional): 

Hello, for some odd reason uBlockProtector is breaking this site, even with uBlock Origin and uBlock Origin Extra is DISABLED and only uBlockProtector is enabled.

Disabling uBlockProtector and the site is working again.

**Comment by jspenguin2017** [comment]
Hi, this is now fixed.

**Comment by spec1re** [comment]
Thanks!
