### ISSUE TITLE
investing.com

### ISSUE THREAD

**Issue by spec1re** [jspenguin2017/uBlockProtector#611]
### Test link (required): 
https://www.investing.com/
### Screenshot of the web page (required): 

![1](https://user-images.githubusercontent.com/11883076/30661708-1f8e170a-9e45-11e7-922a-abf078d2945e.PNG)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2](https://user-images.githubusercontent.com/11883076/30661715-246824b4-9e45-11e7-8d89-87fe9ec1b966.PNG)

**Comment by jspenguin2017** [comment]
I can't reproduce it: 
![image](https://user-images.githubusercontent.com/7283682/30669515-dc3b69cc-9e1b-11e7-9971-80a34045a050.png)

**Comment by spec1re** [comment]
After deleting all cookies for this domain, it's gone,

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by spec1re** [comment]
It looks like they have a cookie based counter, so you need to visit this page few times a day/week till the pop-up appears.

**Comment by uBlock-user** [comment]
I deleted all cookies and site data and I still can't reproduce it. 

You may test `@@/js/ads.js$domain=investing.com` and see if that changes anything.

**Comment by spec1re** [comment]
Deleting the cookie will reset the counter = no pop-up, you need to allow cookies for the page and visit the page frequently till it pops-up again.

**Comment by uBlock-user** [comment]
Did you test the filter I posted in https://github.com/jspenguin2017/uBlockProtector/issues/611#issuecomment-331053579 ?

**Comment by spec1re** [comment]
![image](https://user-images.githubusercontent.com/11883076/30682724-ef70bd28-9eaa-11e7-95b1-251996aa87ec.png)

![image](https://user-images.githubusercontent.com/11883076/30682744-013edce2-9eab-11e7-9c9a-567561d14644.png)

It's still there, but deleting the cookie for this site, makes it disappear...

**Comment by jspenguin2017** [comment]
I think it tests `google_ad_status`, which is handled by a generic rule.
