### ISSUE TITLE
pilot.wp.pl

### ISSUE THREAD

**Issue by MajkiIT** [jspenguin2017/uBlockProtector#612]
This rule will display adblock "||adv.wp.pl/*/inline-videostar.js$xmlhttprequest,redirect=noopjs,important,domain=pilot.wp.pl"

https://user-images.githubusercontent.com/15007183/30665155-2071526c-9e1e-11e7-865f-b778309f1c95.PNG

**Comment by lain566** [comment]
> This rule will display adblock

Not for me.
This rule does not work on Firefox: `xmlhttprequest` `redirect`

![ogladaj_darmowa_telewizje_online_na_zywo_-_google__2017-09-20_22-47-27](https://user-images.githubusercontent.com/27441315/30666778-bbbb0d30-9e55-11e7-9761-b7a1d24c0e7b.png)

**Comment by jspenguin2017** [comment]
That's right, the rule does not work on Firefox.

**Comment by MajkiIT** [comment]
@jspenguin2017 But not do it. So if it not universal please delete it.

**Comment by jspenguin2017** [comment]
uBlock Protector is only for Chrome, and I don't care if it works on Firefox. 
For AAK-Cont, Merge Request welcomed.
