### ISSUE TITLE
adlinkme.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#613]
### Test link (required): 
http://adlinkme.com/6Mc0
### Screenshot of the web page (required): 
![2017-09-22_221935](https://user-images.githubusercontent.com/2828165/30762989-87102bc0-9fe4-11e7-9a03-044ed67a1983.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2017-09-22_222038](https://user-images.githubusercontent.com/2828165/30762963-745e4fac-9fe4-11e7-99d1-1531a5cca4f0.png)

**Comment by uBlock-user** [comment]
another #183 clone
