### ISSUE TITLE
ur.ly, linx.cloud, jzrputtbut.net, urly.mobi

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#615]
Test link :  http://ur.ly/xNwnJzx

Screenshot of the web page : 
Phase 1) - http://prntscr.com/gq7apa
Phase 2) - http://prntscr.com/gq7b0s

Problems:
1) Site Opening tons of annoying pop-ups.
2) The site use different algorithm different times. meaning sometimes they show captcha (which I belive can be bypassed), I believe they have 3-4 templates, they all runs randomly, try reload the page 2-3 times, it will show up.

=======================

Test link :  http://linx.cloud/mick-s02e01-720p-hdtv-2ch-x265-hevc-psa-87456/

Linx.cloud has been patched before, but I believe they changed something, for that, I have to click "show links" 5-6 times, before the actual content shows up.

=======================

Test link :  http://www.jzrputtbut.net/AsrQH

Patch the 5 sec timer? then redirect to destination automatically?

=======================

Test Link : http://urly.mobi/xNwnJzx - http://prntscr.com/gq7ptf

Sometimes captcha appears, which I believe can be patched.

**Comment by uBlock-user** [comment]
http://ur.ly/xNwnJzx redirects me to http://linx.cloud/mick-s02e01-720p-hdtv-2ch-x265-hevc-psa-87456/ and then the entire page is broke because of a blocked XHR to `http://piguiqproxy.com/api`

**Comment by uBlock-user** [comment]
`ur.ly `can be bypassed though and doesn't have any reCaptcha from Google.

**Comment by Dibbyo456** [comment]
@uBlock-user ur.ly uses 2-3 algorithms? Sometimes direct redirect, sometimes captcha, sometimes skip page.

**Comment by uBlock-user** [comment]
Which algorithms ? I only see a fake ad CSS selector named `##.captcha-container`

**Comment by Dibbyo456** [comment]
@uBlock-user Take a look - http://prntscr.com/gq7mdj

**Comment by uBlock-user** [comment]
That doesn't appear on my end and on clicking Skip AD twice I get redirected to linx.cloud.

For linx.cloud - `linx.cloud##script:inject(abort-on-property-read.js, performance)`

**Comment by uBlock-user** [comment]
This is what I see

![](https://i.gyazo.com/a22141835a8037fb743a1b08e8c18e77.png)

**Comment by Dibbyo456** [comment]
that filter worked.
btw, i'm sorry, the captcha was appearing on `urly.mobi`
I guess they sometimes redirect urls to their alias domain.

**Comment by uBlock-user** [comment]
Okay, clicking twice doesn't redirect me but opens another page with a 5 sec timer

![](https://i.gyazo.com/a3528684f107a2a91b3a524c9d405c70.png)

and when I click skip ad the third time I get to` linx.cloud`

**Comment by uBlock-user** [comment]
@jspenguin2017 can bypass `ur.ly` as there's no Captcha. 

I can reproduce anit adblock notice on `jzrputtbut.net/AsrQH`

**Comment by Dibbyo456** [comment]
@uBlock-user Check my updated comment.

**Comment by uBlock-user** [comment]
Also has a 5 sec timer

AA script - http://www.linkbucks.com/scripts/intermissionLink.v13.js

**Comment by uBlock-user** [comment]
http://urly.mobi/xNwnJzx is the same, I get redirected to linx.cloud, no reCapcha is shown although connect request appears via logger.

**Comment by adreporter** [comment]
@jspenguin2017 
http://www.jzrputtbut.net/nnc1
After clicking on "SKIP THIS AD":
<img width="306" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/32900947-eb1e7060-caee-11e7-8991-a469cb53bcbc.PNG">
<img width="960" alt="przechwytywanie1" src="https://user-images.githubusercontent.com/18214146/32900953-eea7f95e-caee-11e7-8fb4-5be16dc0d0cd.PNG">

**Comment by jspenguin2017** [comment]
Hum, the timer seems to be validated on server side now.

**Comment by Infinitay** [comment]
Is there a bypass for Linx.Cloud? Sorry if it's the wrong place to ask

**Comment by jspenguin2017** [comment]
I think no...
