### ISSUE TITLE
xilften.tk

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#617]
### Test link (required): 
http://xilften.tk/filme/376-Baywatch-HD

### Screenshot of the web page (required): 
![2017-09-27_184550](https://user-images.githubusercontent.com/2828165/30926086-54e461c4-a3b4-11e7-8599-2111226aef67.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2017-09-27_184535](https://user-images.githubusercontent.com/2828165/30926106-649ab622-a3b4-11e7-82a4-78ef3551b97f.png)

**Comment by uBlock-user** [comment]
That's not anti adblock but rather a notice that tells you that the media is not supported or the video server link is 404 something like that

**Comment by jspenguin2017** [comment]
Reproducible on a browser that has no extension, so it is not anti-adblock, maybe the media server is down.
