### ISSUE TITLE
zdnet.de

### ISSUE THREAD

**Issue by StreamXL** [jspenguin2017/uBlockProtector#618]
http://www.zdnet.de/

![1](https://user-images.githubusercontent.com/31142317/30930680-ae735412-a3c2-11e7-9d2b-7b5c339a6a10.png)
![2](https://user-images.githubusercontent.com/31142317/30930679-ae7275ce-a3c2-11e7-8994-ba88da07ba74.png)

**Comment by uBlock-user** [comment]
`zdnet.de##script:inject(abort-on-property-read.js, can_i_run_ads)`

or

`zdnet.de###abl-overlay`
