### ISSUE TITLE
avoiderrors.net

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#619]
### Test link (required): 
https://www.avoiderrors.net/set-up-a-vpn-server-on-windows-server-2012/

### Screenshot of the web page (required): 
![2017-09-28_100258](https://user-images.githubusercontent.com/2828165/30955581-5de3389c-a434-11e7-9d8e-82cf75147ab3.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2017-09-28_100338](https://user-images.githubusercontent.com/2828165/30955593-66c6d16c-a434-11e7-9fad-5539f1715cba.png)

**Comment by uBlock-user** [comment]
```javascript
jQuery(document).ready(function($) {
--
  |  
  | setTimeout(function() {
  | if ( typeof(window.google_jobrunner) === "undefined" ) {
  |  
  | //ad blocker installed - hide content
  |  
  | jQuery("body").html('<div class="san_wrapper"> \
  | <div class="san_inner"> \
  | <h2>Adblocker Detected</h2><br> \
  | This website has become a multi author site. Please disable adblock on AvoidErrors.net so they can get paid. Thank you.<br>\<br>\<img class="alignnone size-full wp-image-33468" src="https://www.avoiderrors.net/wp-content/uploads/2017/05/Disable-popupblocker.png" alt="" width="266" height="288" />                                </div> \
  | </div>');
  |  
  | }
  |  
  | }, 10000);
  |  
  | });
```

**Comment by uBlock-user** [comment]
`avoiderrors.net##script:inject(setTimeout-defuser.js, adblock)`
