### ISSUE TITLE
theage.com.au

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#621]
### Test link (required): 
`http://www.theage.com.au/`
### Screenshot of the web page (required): 
![otto_warmbier _american_student_held_in_north_kore_2017-09-29_22-32-07](https://user-images.githubusercontent.com/27441315/31035297-c047f7a0-a567-11e7-95fd-b134998e44ef.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2017-09-29_22-47-11](https://user-images.githubusercontent.com/27441315/31035415-2e525a60-a568-11e7-9772-8c71d7efb58c.png)

### Add everything else that you believe to be useful below (optional): 
It's broken by ublock protector list

**Comment by jspenguin2017** [comment]
It's not, those Google's domains are blocked on purpose.

**Comment by ghajini** [comment]
@lain566
Its Google funding choices ....Google it

https://github.com/jspenguin2017/uBlockProtector/issues/271

**Comment by uBlock-user** [comment]
Can't reproduce.
