### ISSUE TITLE
maisgasolina.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#625]
### Test link (required): 
`https://www.maisgasolina.com/`
### Screenshot of the web page (required): 
![preco_dos_combustiveis_-_mais_gasolina_-_google_ch_2017-09-30_20-49-57](https://user-images.githubusercontent.com/27441315/31048614-372ec0f6-a621-11e7-8ae4-72971fb53c85.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww maisgasolina com_2017-09-30_20-50-18](https://user-images.githubusercontent.com/27441315/31048616-3cc78ab6-a621-11e7-9524-f66e6584f3bf.png)

**Comment by uBlock-user** [comment]
```
This site can’t be reached
www.maisgasolina.com took too long to respond.
```

For some reason the website won't open.

**Comment by ghajini** [comment]
Because it requires `netherlands`  Ip ....
Use opera browser built in VPN ,it has Netherland location.....

https://prnt.sc/grz3kf

**Comment by uBlock-user** [comment]
@ghajini Can you reproduce the issue I face ?

**Comment by ghajini** [comment]
Yep I can reproduce your issue if I use regular Ip other than Netherlands..... So a geolock of 'Netherlands' ,I can reproduce op page is antiadblock

**Comment by jspenguin2017** [comment]
Pretty hard to hook on with debugger, but I got it... 
![image](https://user-images.githubusercontent.com/7283682/31061486-2e944b14-a6df-11e7-9b2e-dc418dec1545.png)

**Comment by jspenguin2017** [comment]
Not sure about Geo Lock though, as I can access it just fine.
