### ISSUE TITLE
literaturcafe.de

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#626]
### Test link (required): 
`http://www.literaturcafe.de/`
### Screenshot of the web page (required): 
![literaturcafe de_ _der_literarische_treffpunkt_im__2017-09-30_20-15-21](https://user-images.githubusercontent.com/27441315/31048386-4b5b82a8-a61c-11e7-85e3-3c1cddb417da.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww literaturcafe de_2017-09-30_20-12-23](https://user-images.githubusercontent.com/27441315/31048361-bbfe7a2a-a61b-11e7-927d-dcf83e7be869.png)

**Comment by uBlock-user** [comment]
Can't reproduce.
