### ISSUE TITLE
deckshop.pro

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#627]
### Test link (required): 
`https://www.deckshop.pro/`
### Screenshot of the web page (required): 
![deck_shop_for_clash_royale__best_clash_royale_dec_2017-09-30_21-02-20](https://user-images.githubusercontent.com/27441315/31048695-fb5fc0aa-a622-11e7-9d2c-50e821237f1c.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww deckshop pro_2017-09-30_21-02-35](https://user-images.githubusercontent.com/27441315/31048698-01470b04-a623-11e7-8dcf-0e0d0d663a96.png)

**Comment by uBlock-user** [comment]
https://www.deckshop.pro/js/ads.js 

looks like ads.js v2.5 or something.

**Comment by jspenguin2017** [comment]
Yea... `a.adsjsV2` still can't handle it... I'll aim it for v12 core.

**Comment by uBlock-user** [comment]
whoa! From v2 to directly v12 ? Why such a big jump ?

**Comment by jspenguin2017** [comment]
The Core is at v11 now.
