### ISSUE TITLE
V12 roadmap

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#628]
The maintenance to Core is long overdue, with new browser API coming to light, Core APIs often fall short of what is needed. 
I'm a bit busy these days, so this can take a while to implement. 

The testing in the build pipeline is pretty useless, I'll remove them. Maybe I'll add some tests once I can get Selenium Chrome Driver to work. 

Done: 
- `a.request` is re-introduced due to `$.request` has a much lower privilege. 
- Cleaned up code style. 
- Removed dead code. 
- Added `//@pragma-if-debug` compiler directives. 
- Updated `a.adsjsV2` to accept custom ID length. 
- `a.replace` is renamed to `a.replaceXHR`, same for `a.loopback` (of content-core). 
- Added blank MP4 as redirect resource ( https://github.com/AdguardTeam/AdguardFilters/issues/6718#issuecomment-335027980 )
- `a.nativePlayer` is removed. 
- Rewrote CI scripts to: 
  1. Strip out debug code from final package
  2. Always build and check syntax
  3. Only publish if needed

**Comment by jspenguin2017** [comment]
Most stuff are implemented, but I'm not very confident...

**Comment by jspenguin2017** [comment]
Although we still have 2 functions to implement, let's celebrate V12 in advance 😄

**Comment by jspenguin2017** [comment]
`fetch` is not easy to fully patch, but is not that hard to patch on a case by case basis. 
![image](https://user-images.githubusercontent.com/7283682/31367159-8d149a14-ad32-11e7-94e9-b95e1e150857.png)

**Comment by Zhangsun321** [comment]
this is kinda sexy....
are you kinda sexy??

**Comment by ghajini** [comment]
How much this is handy?
Js rules to be wrapped into anonymous function...

**Comment by jspenguin2017** [comment]
Why is that needed? The rules run in a privileged scope, the page cannot interfere with it.

**Comment by ghajini** [comment]
I just came across this one
`https://github.com/AdguardTeam/AdguardBrowserExtension/issues/838`

**Comment by jspenguin2017** [comment]
Yes, when I need to inject code to page scope, I always wrap it in a self executing function. It's like that since the first version of Extension.

**Comment by ghajini** [comment]
Also is it needed to give warnings in console (like ublock origin detectors are not allowed on this device).... half of sites know what you are doing.....its suggestion only,   I mean limit/display these warnings in debug mode extension only(developers only)

**Comment by jspenguin2017** [comment]
The "blocked by client" is printed internally by Chrome, it is out of the control of uBO. 
I need the console output so I can know which rule ran, there **should** be no programatic way to intercept the log, let me know if you found a way. 
I kind of need the console output even when the extension is running in production mode, but I'll consider the suggestion.

**Comment by jspenguin2017** [comment]
After some testing, it seems that `Element Hide Enforcer` and `fetch Loopback Engine` are better implemented on a case by case basis, as there will be countless ways to bypass a generic implementation.
