### ISSUE TITLE
megawrzuta.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#629]
### Test link (required): 

https://megawrzuta.pl/download/5d40e6af888e34ff21c8e8121c060dea.html

### Screenshot of the web page (required): 

![capture](https://user-images.githubusercontent.com/15007183/31058134-a435fe26-a6bc-11e7-88f6-d69f64303ba3.PNG)

**Comment by jspenguin2017** [comment]
It's an unconditional popup...

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
A new scriptlet titled window.open-defuser.js, has landed in ![resources.txt](https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt#L1904) FYI

**Comment by jspenguin2017** [comment]
Doesn't matter, I can filter any function I want since last year.

**Comment by jspenguin2017** [comment]
I mean `a.filter`, which can be used to filter any built in function.
