### ISSUE TITLE
ecut.io

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#630]
### Test link (required): 
http://ecut.io/sJ7m

### Screenshot of the web page (required): 
![2017-10-01_221212](https://user-images.githubusercontent.com/2828165/31058541-cacdc242-a6f5-11e7-8f5c-eb6df0cbbce3.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2017-10-01_221254](https://user-images.githubusercontent.com/2828165/31058547-d4cc01fa-a6f5-11e7-8f4a-413ffdb3b52f.png)

**Comment by uBlock-user** [comment]
#183 clone
