### ISSUE TITLE
4downfiles.org

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#632]
Test Link - https://4downfiles.org/ztztbaclv18e

Problems Details:

1) PopMyAds Pop-up ads. - The annoying pop-up ads showing up even I have antipop-ads filter, they're getting bypassed somehow.

2) When clicking [Download](http://prntscr.com/gslqfg), it's redirecting to `ouo.io` which I think can be skipped, because the actual download url exist on the [source code](http://prntscr.com/gslr9e). So, I think we can completely skip the `ouo.io` redirection part

**Comment by uBlock-user** [comment]
1) Can't reproduce any popups.

2) Yes the redirect can be skipped if the download link is retrieved before landing on `ouo.io`

3) a 10 sec timer needs to be patched

**Comment by Dibbyo456** [comment]
> Can't reproduce any popups.

@uBlock-user Yes. Me neither, very strange. The pop-ups was showing 3 hours ago, but no pop-ups now.. o.O

**Comment by uBlock-user** [comment]
Try in incognito mode and see if you can still reproduce them.

**Comment by jspenguin2017** [comment]
1. Can't reproduce. 
2. Can't reproduce. 

@uBlock-user Server side timer.
