### ISSUE TITLE
insuranceage.co.uk

### ISSUE THREAD

**Issue by jackyaz** [jspenguin2017/uBlockProtector#633]
### Test link (required): 
https://www.insuranceage.co.uk/broker/3151961/county-group-buys-nmj-insurance-brokers
### Screenshot of the web page (required): 
https://gyazo.com/38d5e3942b103005d57fcbb86cfe8b40
### Screenshot of the console (press `F12` to bring up the console) (required): 
https://gyazo.com/ba940d07f7cf01d9400ead00a7f405ae

**Comment by uBlock-user** [comment]
`||adpass.co.uk^$third-party`
