### ISSUE TITLE
strefadb.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#636]
site
https://strefadb.pl/filmy-kinowe/dragon-ball-z-tv-special_01_bardock---ojciec-goku.html

ubpe & ub ( on - not work )
![2017-10-05 00_07_30-dragon ball z tv special - 01 bardock - ojciec goku - napisy filmy online](https://user-images.githubusercontent.com/5884000/31202066-6532d77e-a961-11e7-9a8a-7987706cd518.png)
![2017-10-05 00_12_45-dragon ball z tv special - 01 bardock - ojciec goku - napisy filmy online](https://user-images.githubusercontent.com/5884000/31202197-f8ab8b9a-a961-11e7-912e-fa2b3217ace7.png)

ubpe & up ( off - normaly work )
![2017-10-05 00_08_06-dragon ball z tv special - 01 bardock - ojciec goku - napisy filmy online](https://user-images.githubusercontent.com/5884000/31202073-6987abf6-a961-11e7-84f7-578cf000d9a1.png)
![2017-10-05 00_14_09-dragon ball z tv special - 01 bardock - ojciec goku - napisy filmy online](https://user-images.githubusercontent.com/5884000/31202255-27bd5b98-a962-11e7-93ca-ef729c696173.png)

ub 1.14.8
ubpe 11.352
chrome 61.0.3163.100 x64

**Comment by jspenguin2017** [comment]
That's some weird anti-adblock logic. Fixed.

**Comment by mat41997** [comment]
i still have a this
![2017-10-05 00_49_52-dragon ball z tv special - 03 historia trunks a - napisy filmy online](https://user-images.githubusercontent.com/5884000/31203445-61e95ae2-a967-11e7-9453-371370369df0.png)

**Comment by uBlock-user** [comment]
```
strefadb.pl###videodiv
strefadb.pl###tooltip
```

**Comment by uBlock-user** [comment]
Anti adblock notice video is put as an overlay.

**Comment by uBlock-user** [comment]
They're not removing the video but only superimposing anti adblock notice video on the Openload video, so hiding via CSS selectors will also work.

**Comment by jspenguin2017** [comment]
The tooltip is unrelated, you can block it with the zapper if you wish. 
![image](https://user-images.githubusercontent.com/7283682/31203553-dfd76a0e-a924-11e7-887b-80bcccb471bc.png)
The thing on the bottom is blocked, it can take some time for filter list to sync.

**Comment by jspenguin2017** [comment]
@uBlock-user Yea, but it won't dispose the player in that case.

**Comment by uBlock-user** [comment]
You mean via picker ? Zapper doesn't block elements, it only removes them until a page refresh.

**Comment by uBlock-user** [comment]
Still tooltip is an annoyance, should be removed.

**Comment by mat41997** [comment]
@uBlock-user i still have
![2017-10-05 00_57_15-dragon ball z tv special - 03 historia trunks a - napisy filmy online](https://user-images.githubusercontent.com/5884000/31203697-8d969f14-a968-11e7-9b79-1446d135b004.png)

**Comment by jspenguin2017** [comment]
True, I thought it's permanent... 
I wouldn't say it's purely annoyance, as it could be helpful in some cases. I won't add it to List.

**Comment by uBlock-user** [comment]
I don't speak polish, you will have to describe it.

**Comment by uBlock-user** [comment]
By annoyance, I meant its position. They should have placed it somewhere else and not in the centre of the video player, that makes it an annoyance as it always appears.

**Comment by jspenguin2017** [comment]
Missed ads goes to EasyList. Or right click -> block element.

**Comment by jspenguin2017** [comment]
Still, I won't add it to List, just in case someone needs it. You can block it with with your custom filter if you don't like it.

**Comment by mat41997** [comment]
@jspenguin2017 i know, thx. for you help : )

**Comment by uBlock-user** [comment]
Another thing, sometimes Openload loads videos via Oload.info which is his clone site and popups appear via `about:blank`

https://oload.info/embed/MDWXdU0koJ0/DBZ_TV_Special_01_-_Bardock_Ojciec_Goku_1990_NapisyPL.mp4

```
oload.*/*license
oload.*/*script
```

**Comment by jspenguin2017** [comment]
Ehm, they have a crypto miner as well... 
![image](https://user-images.githubusercontent.com/7283682/31204349-b91fb5d4-a928-11e7-9967-154219e01b69.png)

**Comment by jspenguin2017** [comment]
cc/ @okiehsch CoinHive is registering new domains...

**Comment by jspenguin2017** [comment]
Linode hypervisor is experiencing hardware issues. 
![image](https://user-images.githubusercontent.com/7283682/31204767-a1f23538-a92a-11e7-9610-66e35d2d855d.png)

**Comment by okiehsch** [comment]
Hm, they are using random domains.
![unbenannt](https://user-images.githubusercontent.com/16838044/31205005-e6e60fb8-a96e-11e7-854c-b068734acbd5.PNG)


So blocking by domain seems pointless.

**Comment by jspenguin2017** [comment]
Blocking the WebAssembly file only fix half the problem, the bootstraper will try to start 3 times per second. I have put `/cryptoneight.wasm` in List until we can figure something out. Probably fingerprint the `wasm` file by patching `WebAssembly` property.

**Comment by jspenguin2017** [comment]
Can we write a bot and list all their domains? It costs money to register domain, let's see how much funding they got. 
I knew CoinHive is going to be a hard and long battle...

**Comment by okiehsch** [comment]
Well, I can see two solutions for uBO:
`oload.info##script:inject(abort-on-property-read.js, WebAssembly)` or
````
oload.info##script:inject(abort-current-inline-script.js, document.createElement, (/[A-Z0-9]{8}-[A-Z0-9]{4}-[A-Z0-9]{4}/.test(key)`
````
the second one seems preferable.

**Comment by jspenguin2017** [comment]
So basically we'll be chasing behind them and patch on a per domain basis? 
It's kind of hard tell since it throttles itself pretty hard (to 13% of CPU on my PC), they can stay under the radar for a while.

**Comment by okiehsch** [comment]
I don't see a better solution right now.

@uBlock-user regarding the popups, I added `oload.info` to [uBO-filters](https://github.com/uBlockOrigin/uAssets/commit/a7cd8fd83aee2728075d9a590f9e1882abd32791)

**Comment by gorhill** [comment]
> So basically we'll be chasing behind them and patch on a per domain basis?

That's how it has been always working with ads and trackers, there is no magic bullet. 

In <https://github.com/uBlockOrigin/uAssets/issues/690#issuecomment-330401913>, I entertain the idea of informing users about the use of webworkers, and ability to block them (like the no-popup-switch). One problem is Firefox is not CSP3 yet, it does not know about `worker-src`. At least this would give users some control without having to completely wait for filter list maintainers to provide filters.

**Comment by okiehsch** [comment]
`.info^$script,third-party,domain=oload.info` will also work and could be added to `NoCoin`

**Comment by gorhill** [comment]
@okiehsch Yes, that seems to be the safest solution for now. Though why not:

    ||info^$script,third-party,domain=oload.info

**Comment by okiehsch** [comment]
OK, I will add it to `uBlock Origin -- Resource-abuse`

**Comment by jspenguin2017** [comment]
Alright, my server is up, build is published. 
It's gone far enough off topic, so I'll lock the thread. Open an new issue for further problems.

**Comment by uBlock-user** [comment]
Why not CSP the entire domain ? Let them run as many random domains as they want.

`||oload.info^$csp=script-src 'self' 'unsafe-inline' 'unsafe-eval'`

**Comment by uBlock-user** [comment]
@okiehsch I already have that filter in my personal list, that doesn't stop the popups on my end. They only stop after I block `license` and `script` jses mentioned in https://github.com/jspenguin2017/uBlockProtector/issues/636#issuecomment-334316392
