### ISSUE TITLE
sms7.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#638]
site
http://sms7.pl/darmowa-bramka-sms

img
![2017-10-05 06_50_06-sms7 pl - darmowa bramka sms do wszystkich sieci orange plus play t-mobile i](https://user-images.githubusercontent.com/5884000/31211489-b3a184d6-a999-11e7-845b-b7acec66e7e5.png)

ub 1.14.8
ubpe 11.354
chrome 61.0.3163.100

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
Can't reproduce.

**Comment by mat41997** [comment]
ok : /
