### ISSUE TITLE
ultimate-catch.eu

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#640]
### Test link (required): 
`http://ultimate-catch.eu/`
### Screenshot of the web page (required): 
![www ultimate-catch eu_ _le_catch_en_version_franca_2017-10-05_20-52-22](https://user-images.githubusercontent.com/27441315/31254973-0982ebf6-aa2b-11e7-961e-ff962f2f7b27.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpultimate-catch eu_2017-10-05_20-52-37](https://user-images.githubusercontent.com/27441315/31254969-051dfa56-aa2b-11e7-997e-1c869e9b5dde.png)

**Comment by uBlock-user** [comment]
```javascript
jQuery(window).load(function(){if(jQuery(".footer_ad").height()==0){var aba_cookie=readCookie("Ad_Blocking_Advisor_WP_Plugin")
--
  | if(!aba_cookie){jQuery(".special-message-wrapper").show().prependTo(jQuery("body"));}}});jQuery(".special-message-right").click(function(){jQuery(".special-message-wrapper").hide();createCookie("Ad_Blocking_Advisor_WP_Plugin","closed",2);});
```
