### ISSUE TITLE
cut-earn.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#642]
http://cut-earn.com/cokKp
http://adbilty.me/nZSV
<img width="306" alt="asas" src="https://user-images.githubusercontent.com/18214146/28378340-1f7756d0-6cb0-11e7-8b52-66324f42a7d7.PNG">
<img width="368" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/31310417-1842fafa-ab98-11e7-8d25-27114148f417.PNG">

**Comment by adreporter** [comment]
@jspenguin2017 Could you please fix also http://adbilty.me/nZSV ?

**Comment by uBlock-user** [comment]
same as #183
