### ISSUE TITLE
adbilty.me

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#643]
http://adbilty.me/nZSV
<img width="306" alt="asas" src="https://user-images.githubusercontent.com/18214146/28378340-1f7756d0-6cb0-11e7-8b52-66324f42a7d7.PNG">
![image](https://user-images.githubusercontent.com/18214146/31310707-5bf94b82-ab9d-11e7-9596-a0d63e94cc30.png)

**Comment by uBlock-user** [comment]
same as #183
