### ISSUE TITLE
ondemandkorea.com

### ISSUE THREAD

**Issue by Connor37** [jspenguin2017/uBlockProtector#644]
### Test link (required): 
http://www.ondemandkorea.com/ask-us-anything-e94.html

### Screenshot of the web page (required): 
![image](https://user-images.githubusercontent.com/8341213/31316855-f6175fb8-ac35-11e7-88a2-34b90b8991fe.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![image](https://user-images.githubusercontent.com/8341213/31316846-e3bb8dda-ac35-11e7-9b5d-ea2298dcb1c6.png)

**Comment by jspenguin2017** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
Can't reproduce.
