### ISSUE TITLE
leech.ninja

### ISSUE THREAD

**Issue by ghajini** [jspenguin2017/uBlockProtector#645]
### Test link (required): 
need to remove timer which is put by website for downloading....
go to 
1. leech.ninja
2.enter any link e.g 
http://nitroflare.com/view/34F0041DC4159CC/9351528065.pdf
3.click on hyperlink of download
4.site will present with 10 mins timer
### Screenshot of the web page (required): 
![2017-10-08_18-31-04](https://user-images.githubusercontent.com/20338483/31317063-afa44588-ac57-11e7-821c-b5147d12654a.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2017-10-08_18-32-04](https://user-images.githubusercontent.com/20338483/31317070-d3adfd2a-ac57-11e7-9f7b-870b87e89ab5.png)

### Add everything else that you believe to be useful below (optional): 
is `a.timewarp` can be applied

**Comment by jspenguin2017** [comment]
Can't reproduce the first time, `a.timewarp` cannot bypass server side locking. 
![image](https://user-images.githubusercontent.com/7283682/31318181-36e5ae62-ac0b-11e7-96ab-4adba8074621.png)

**Comment by ghajini** [comment]
But I have visited that site first time only....how can I check myself if a.timewarp works for that site in debug mode

**Comment by jspenguin2017** [comment]
Write a script rule: 
```js
if (a.domCmp([ INSERT_DOMAIN_LIST ])) {
    a.timewarp("setTimeout");
    a.timewarp("setInterval");
}
```
Keep in mind that these rules without a filter can slow down a website for up to 50 times.

**Comment by ghajini** [comment]
A WiFi having pppoe connection....

**Comment by uBlock-user** [comment]
If I visit NitroFlare link, I get a popup and a 2 minute timer - https://i.gyazo.com/6b685d60f108cb3e6b9716f5595555ad.png

Not sure if server-sided.

**Comment by jspenguin2017** [comment]
Just test the script rule, it works then let me know, it doesn't then I can't help neither.

**Comment by ghajini** [comment]
Yes its usual to get 2mins timer on nitroflare (becoz of free download) but getting timer of ***10mins***  at leech.ninja just sucks

**Comment by jspenguin2017** [comment]
Guys, for the 100000th time, I CANNOT remove server side timer!!!

**Comment by ghajini** [comment]
Yes I already understood.........

**Comment by uBlock-user** [comment]
My post was about nitroflare only, not about the `leech.ninja`
