### ISSUE TITLE
crash-aerien.news

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#646]
### Test link (required): 
`http://www.crash-aerien.news/forum/`
### Screenshot of the web page (required): 
![www crash-aerien newsforum_-_google_chrome_2017-10-08_15-46-04](https://user-images.githubusercontent.com/27441315/31317361-d5537aa0-ac3f-11e7-8aca-9c435822ac4b.png)
### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww crash-aerien newsfor_2017-10-08_15-45-20](https://user-images.githubusercontent.com/27441315/31317359-befb30cc-ac3f-11e7-8925-2a977b037d67.png)

**Comment by uBlock-user** [comment]
from here - https://github.com/reek/anti-adblock-killer/issues/3629
