### ISSUE TITLE
pornhub.com

### ISSUE THREAD

**Issue by gotitbro** [jspenguin2017/uBlockProtector#647]
An anti adblock notice is currently hidden on Pornhub by `pornhub.com,tube8.fr,tube8.es,tube8.com###abAlert`. But since the notice is not completely hidden a big space remains below the header making it a nuisance for users.

**SS:** https://i.imgur.com/XXMDak9.png
**Error URL:** `https://www.pornhub.com/`

Since the notice is dismissable I recommend either removing the above filter so that the user can dismiss the message on his own and see no space below the header or using a filter that hides the space along with the message comprehensively.

_**Note:** Using uBO 1.14.8 on Chrome 61 with the default filters and settings along with uBlock Protector._

**Comment by uBlock-user** [comment]
`pornhub.com##script:inject(abort-on-property-read.js, userABMessage)`

Does it work for you ?
