### ISSUE TITLE
NSFW! ultrahorny.com

### ISSUE THREAD

**Issue by thrwat** [jspenguin2017/uBlockProtector#648]
### Test link (required): 

`ultrahorny.com`
`https://ultrahorny.com/brazzers-would-taking-off-my-alge-bra-help/`

### Screenshot of the web page (required): 

https://i.imgur.com/A5l4Ykd.png

### Add everything else that you believe to be useful below (optional): 

They seem to be using custom solution...

**Comment by uBlock-user** [comment]
Put "NSFW!" in the title if the link is porn related.

text-link - `https://ultrahorny.com/brazzers-olivias-wet-little-secret/`

`ultrahorny.com##script:inject(abort-current-inline-script.js, decodeURIComponent, atob)` works as long as race condition doesn't come into play.

**Comment by uBlock-user** [comment]
aa script - https://gist.githubusercontent.com/uBlock-user/637137cc6d44f019d2e9fa10beb6cc9e/raw/3143944c6838bc74c21e43cd304aed4eb94dcb36/gistfile1.txt

**Comment by uBlock-user** [comment]
There's nothing for you to do except you can add the filter I proposed if you want or wait for jspenguin to patch it in the Extension.

**Comment by thrwat** [comment]
I added the filter, it still does not work :(

**Comment by uBlock-user** [comment]
Which one ? Add the second one for consistency.

**Comment by thrwat** [comment]
Works for few seconds, than message pops up again :(

**Comment by uBlock-user** [comment]
Works perfectly as expected for me. Disable all other extensions and then enable them one by one and see which one is causing the issue.

**Comment by jspenguin2017** [comment]
Race condition affects every scriptlet pretty much equally.

**Comment by jspenguin2017** [comment]
Although the second rule works, it breaks thumbnails.

**Comment by jspenguin2017** [comment]
All we want is to take out that big chunk of obfuscated code right? Let's just count which script to remove.

**Comment by uBlock-user** [comment]
`abort-on-property-read.js`, generally works best with race conditions from my experience.

**Comment by uBlock-user** [comment]
Also which thumbnails break ?

**Comment by jspenguin2017** [comment]
I go with fact instead of feelings. uBO's source code indicates that it treats all scriptlets the same. 

> Which thumbnails break

All of them break.

**Comment by uBlock-user** [comment]
I go with what I see. Regardless of race conditions or how uBO treats the scriptlets, that scriptlet has worked for 99% of the times, that's why I stick to that.

**Comment by jspenguin2017** [comment]
`https://ultrahorny.com/mofos/`
![image](https://user-images.githubusercontent.com/7283682/31520861-9c5fdf22-af64-11e7-9caf-f15ea8500f6a.png)

**Comment by uBlock-user** [comment]
It loads on my end if I start scrolling, nothing to do with my filter.

![](https://i.gyazo.com/10e64b6ecc36990e96fa05818321f2f3.png)

**Comment by jspenguin2017** [comment]
Yea you're right, something was wrong with their server.

**Comment by uBlock-user** [comment]
I think this thumbnail issue lies with the website itself and how it loads thumbnails upon page load, because if the filter breaks something completely, it wouldn't load after scrolling based on my observations of using scriptlets for more than a year.

**Comment by ghajini** [comment]
Patching ubo scriptlets for race conditions are at the hands of @gorhill......

**Comment by jspenguin2017** [comment]
How many times have I repeated, it is not patchable, that's as good as it gets with current Chrome API.

**Comment by uBlock-user** [comment]
Please don't abuse the use of mentions like this, ghajini. It's not to be used over a casual chat.

**Comment by ghajini** [comment]
Sorry  😨.....I got it
