### ISSUE TITLE
hackernoon.com

### ISSUE THREAD

**Issue by thrwat** [jspenguin2017/uBlockProtector#649]
### Test link (required): 

https://hackernoon.com/challenge-program-without-variables-javascript-bee89a41455e

### Screenshot of the web page (required): 

https://i.imgur.com/6WBP4rS.png

### Screenshot of the console (press `F12` to bring up the console) (required): 

https://i.imgur.com/zhAZkCq.png

### Add everything else that you believe to be useful below (optional): 

As soon as console opens, the page gets fixed.

**Comment by uBlock-user** [comment]
Can't reproduce.

What's the issue here ?

**Comment by HateAds** [comment]
Can't reproduce.

**Comment by thrwat** [comment]
The GitHub code is embedded there but is not visible with UBlock protector on. As soon as I open the console, it is visible. I disabled Ublock Protector and it works fine after that.

**Comment by lain566** [comment]
imgur.com has anti-adblock :confused:

**Comment by uBlock-user** [comment]
Where ? If you found the link, post a new issue then.

**Comment by lain566** [comment]
I forgot it, sorry.
Go here https://imgur.com/DTyeLvo for example
Click on `report ad`

![imgur_the_most_awesome_images_on_the_internet_-_g_2017-10-14_20-34-10](https://user-images.githubusercontent.com/27441315/31578373-608d91f2-b120-11e7-8421-83f8e24e6db2.png)

**Comment by uBlock-user** [comment]
Try `||imgur.com/min/px.js`

**Comment by lain566** [comment]
It does not work for me

**Comment by uBlock-user** [comment]
`imgur.com##script:inject(abort-on-property-read.js, ADBLOCKED)`

what about that ?

**Comment by lain566** [comment]
that does not work either

**Comment by jspenguin2017** [comment]
Well, how do you report ads when you block them?

**Comment by uBlock-user** [comment]
Will have to set value for ADBLOCKED variable then the form appears. Wait for jspenguin to fix that.

**Comment by uBlock-user** [comment]
Personally, there's no reason to use report ad if you're using uBlock Origin. If you want to patch the detection that's fine, otherwise there's no real reason to fix this.

**Comment by jspenguin2017** [comment]
I noticed it a long time ago, but last time I tried, Imgur works better without detection patched.

**Comment by jspenguin2017** [comment]
That link is not for reporting people hosting ads on Imgur, so won't fix. 
![image](https://user-images.githubusercontent.com/7283682/31578578-3e9eeaa8-b0e1-11e7-83b0-8435b0699419.png)

**Comment by uBlock-user** [comment]
I can never be that honest as I block more than just ads, I block all their scripts too and what not 🤣

**Comment by lain566** [comment]
I saw it by chance, not only happens with that option, I thought that this project blocked any adblock warning regardless of the reason.

**Comment by jspenguin2017** [comment]
What do you mean by not only happen to that option? What else does it affect? 

Hum, OK, but in this case, I believe hiding the report ads button would be a better fix.

**Comment by uBlock-user** [comment]
That's the bait -` https://imgur.com/min/advertising.js` Whitelist it or set its value and it will work for you.
