### ISSUE TITLE
cda-hd.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#650]
http://cda-hd.pl/21111/dragon-nest-tron-elfow-dragon-nest-movie-2-throne-of-elves-2017-online/

before
![2017-10-15 06_31_12-dragon nest_ tron elfow _ dragon nest movie 2_ throne of elves 2017 _ darmowe](https://user-images.githubusercontent.com/5884000/31581767-d0f4cf1c-b172-11e7-8517-f2f75aeb6377.png)

after
![2017-10-15 06_31_40-dragon nest_ tron elfow _ dragon nest movie 2_ throne of elves 2017 _ darmowe](https://user-images.githubusercontent.com/5884000/31581769-d9ef1906-b172-11e7-907e-e6bf176b6699.png)

uBlock Protector Extension 12.14
chrome 61.0.3163.100

**Comment by uBlock-user** [comment]
Can't reproduce.

![](https://i.gyazo.com/6503601817c08bef2b8bda1602527d48.png)

**Comment by HateAds** [comment]
Can't reproduce.

**Comment by mat41997** [comment]
Ok. : -/

**Comment by mat41997** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/3942#issuecomment-336705950

**Comment by uBlock-user** [comment]
As per https://github.com/MajkiIT/polish-ads-filter/issues/3942#issuecomment-336707185, you're using AAK-Cont list instead of uBlockProtector List. That's not the std. setup. Deactivate AAK-Cont list and add uBlockProtector List.

**Comment by mat41997** [comment]
@uBlock-user still not work
![2017-10-15 14_23_33-dom wygranych _ the house 2017 _ darmowe filmy i seriale w hd online - cda-hd](https://user-images.githubusercontent.com/5884000/31584756-845c3e46-b1b4-11e7-8354-98270008970f.png)
![2017-10-15 14_24_40-ublock panel sterowania](https://user-images.githubusercontent.com/5884000/31584762-af256d82-b1b4-11e7-9fa3-3b68eb728545.png)
![2017-10-15 14_25_00-ublock panel sterowania](https://user-images.githubusercontent.com/5884000/31584761-af02b814-b1b4-11e7-9625-143420b190a3.png)

**Comment by uBlock-user** [comment]
Tht wasn't for this issue, but a suggestion in general. It doesn't work for you because something on your end is being blocked.

**Comment by jspenguin2017** [comment]
Can't reproduce.
