### ISSUE TITLE
simply-debrid.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#652]
### Screenshot of the web page (required): http://prntscr.com/gzbni6

Add this link `http://uptobox.com/zrznpynoije2` in the text box

**Comment by uBlock-user** [comment]
Wrap the test link, don't make it clickable.

**Comment by uBlock-user** [comment]
As a work-around you can use - `@@||simply-debrid.com^$elemhide` but placeholders will appear.

**Comment by Dibbyo456** [comment]
Very strange, first time it worked, second time not works.

**Comment by uBlock-user** [comment]
![](https://i.gyazo.com/6dfa8e339e1490b68a5a698993c02ca9.png)

Works fine for me, everytime.

**Comment by uBlock-user** [comment]
`a.bait` can take care of this I suppose.

**Comment by jspenguin2017** [comment]
The element is already present, no need to `a.bait` again.

**Comment by uBlock-user** [comment]
Yeah but the problem is the empty placeholder appears because the size is now `1px` as you can see below.

![](https://i.gyazo.com/7a034c4c01f78517bffaaf20e2fe6379.png)

Can you hide that ?

**Comment by uBlock-user** [comment]
Okay, `simply-debrid.com###google_ads:style(visibility: hidden !important;)` does the job.
