### ISSUE TITLE
webnovel.com

### ISSUE THREAD

**Issue by inedarr** [jspenguin2017/uBlockProtector#653]
### Test link (required): 
`https://www.webnovel.com/book/6838665602002005/23659659332212318/Throne-of-Magical-Arcana/The-Hand-of-Paleness`
`https://www.webnovel.com/book/6838665602002705/23700065042356299/The-Avalon-Of-Five-Elements/Karakorum`
`https://www.webnovel.com/book/6838665602002705/23700078195693644/The-Avalon-Of-Five-Elements/Meridian-Sand`
`https://www.webnovel.com/book/7834185605001405/23714632229247356/True-Martial-World/A-Sword-Strike-that-Looks-Familiar`

### Screenshot of the web page (required): 

https://imgur.com/aoQqOXF

### Add everything else that you believe to be useful below (optional): 
While ad-skipping still works fine, the site started adding some stuff that breaks the formatting of the chapters (see the screenshot) after the ad-blocked part is retrieved. Originally it was only a couple of novels but recently they added it to several more making it quite annoying.

**Comment by uBlock-user** [comment]
Has something changed ?

It was patched here before - https://github.com/jspenguin2017/uBlockProtector/issues/457

**Comment by jspenguin2017** [comment]
Fixed.

**Comment by uBlock-user** [comment]
It's adding <p></p> tags after few seconds, seems like an annoyance now.

**Comment by jspenguin2017** [comment]
No, it's a bug in Extension.

**Comment by inedarr** [comment]
Hm... it's fixed for the affected novels but now all the "old" style novels lack any paragraph breaks... example: `https://www.webnovel.com/book/7141974606000205/23270505750523730/MMORPG:-Rebirth-of-the-Legendary-Guardian/The-Four-Horsemen`

**Comment by jspenguin2017** [comment]
Seems to work fine for me, maybe clear the cache? 
![image](https://user-images.githubusercontent.com/7283682/31779472-6c1bc0fa-b4b0-11e7-9781-98167346ddd6.png)

**Comment by inedarr** [comment]
Nope, tried it right now (also did a forced extension update check, still 12.18) and here it's still broken. Tried a new, just released chapter:
`https://www.webnovel.com/book/6831850602000905/22864360758105338/Library-of-Heaven's-Path/The-Promised-Duel`
and it's showing me a big block of text without a single line break. Screenshot:
https://imgur.com/a/PIWAz

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/31782408-1011a6dc-b4b8-11e7-8280-731ceb28b63d.png)

**Comment by jspenguin2017** [comment]
Yea, you are right, there are some cache issues, I'll add a check for now.

**Comment by inedarr** [comment]
Indeed, it seems to work just fine now for both types of novels. Thank you very much for fixing the issue.
