### ISSUE TITLE
odcinki-seriali.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#654]
https://github.com/MajkiIT/polish-ads-filter/issues/4029

site
https://odcinki-seriali.pl/

![2017-10-20 09_12_30-odcinki seriali - seriale filmy wiadomosci i muzyka online](https://user-images.githubusercontent.com/5884000/31809200-d7f81582-b576-11e7-9a5c-79e84853fc80.png)

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.21
chrome 62.0.3202.62
win10 x64

**Comment by uBlock-user** [comment]
Wrap the links, don't make them clickable.

**Comment by jspenguin2017** [comment]
The page gives 403. I'll test later.

**Comment by mat41997** [comment]
try with polish vpn

**Comment by mat41997** [comment]
site has back
try with polish vpn

**Comment by uBlock-user** [comment]
Site is working now. I can reproduce. 

Filter - `odcinki-seriali.pl##script:inject(abort-on-property-read.js, adBlockDetected)`
