### ISSUE TITLE
filmowoonline.cba.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#656]
https://github.com/MajkiIT/polish-ads-filter/issues/4046
![2017-10-21 14_00_56-filmy i seriale online bez limitu zapraszamy do ogladania filmow online _ z](https://user-images.githubusercontent.com/5884000/31851562-906f22ee-b668-11e7-98b0-105c01b1d543.png)

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.24
chrome 62.0.3202.62
win10 x64

**Comment by uBlock-user** [comment]
cba.pl##script:inject(abort-on-property-read.js, adBlockDetected)

same as #654
