### ISSUE TITLE
firstonetv.net

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#657]
``https://www.firstonetv.net/Live/Poland/Discovery-Channel-23``
![2017-10-21 17_30_52-discovery channel poland - live stream _ firstone tv - watch tv when and where](https://user-images.githubusercontent.com/5884000/31853443-8ab1aec4-b688-11e7-9077-709a274fbd16.png)
![2017-10-21 17_32_21-discovery channel poland - live stream _ firstone tv - watch tv when and where](https://user-images.githubusercontent.com/5884000/31853445-945c4aa6-b688-11e7-83a1-9360fb856ba0.png)

https://github.com/MajkiIT/polish-ads-filter/issues/4050

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.24
chrome 62.0.3202.62
win10 x64

**Comment by uBlock-user** [comment]
Domain swapped from .eu to .net

Script - `https://www.firstonetv.net/js/jquery.kyco.easyshare`

`firstonetv.*##script:inject(noeval-if.js, Adblocker)`
