### ISSUE TITLE
niezalezna.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#658]
![2017-10-21 22_08_12-niezalezna - wiadomosci _ informacje _ wydarzenia - polska i swiat](https://user-images.githubusercontent.com/5884000/31855499-9d8a6d32-b6ac-11e7-85d4-503402a881a0.png)

https://github.com/MajkiIT/polish-ads-filter/issues/4058

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.25
chrome 62.0.3202.62
win10 x64

**Comment by uBlock-user** [comment]
`niezalezna.pl##script:inject(noeval-if.js, adblock)`
