### ISSUE TITLE
lkcash.net

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#659]
### Test link (required): 
http://lkcash.net/oM7B

### Screenshot of the web page (required): 
![2017-10-22_001642](https://user-images.githubusercontent.com/2828165/31856334-7956202a-b6be-11e7-97e5-3ee018a667fb.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![2017-10-22_001725](https://user-images.githubusercontent.com/2828165/31856336-8a27019e-b6be-11e7-8310-c34d0a87063c.png)

**Comment by uBlock-user** [comment]
clone of #183
