### ISSUE TITLE
NSFW! gej-porno.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#662]
![2017-10-23 22_58_56-polskie chlopaki jada sie na kanapie](https://user-images.githubusercontent.com/5884000/31912972-0b1d3b6e-b846-11e7-89a9-b6260e893793.png)

https://github.com/MajkiIT/polish-ads-filter/issues/4091

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.31
chrome 62.0.3202.62
win10 x64

**Comment by uBlock-user** [comment]
Link - `https://gej-porno.pl/dwaj-mlodzi-chlopcy-sa-fanami-jebania,5617`

script - `https://gej-porno.pl/javascript/javascript.js?t=2`

`gej-porno.pl#@#.myTestAd`

**Comment by jspenguin2017** [comment]
@mat41997 Can you use the template next time?
