### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#664]
![2017-10-24 16_52_46-pasazer 2018 - filmweb](https://user-images.githubusercontent.com/5884000/31950394-cf4338be-b8db-11e7-92e4-f49ab9982804.png)
``http://www.filmweb.pl/film/Pasa%C5%BCer-2018-560109``

https://github.com/MajkiIT/polish-ads-filter/issues/4098

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.34
chrome 62.0.3202.62
win10 x64

**Comment by uBlock-user** [comment]
`filmweb.pl##script:inject(setTimeout-defuser.js, notDetected)`
