### ISSUE TITLE
[Discussion] Automation and AAK-Cont

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#665]
Important Update: 

AdBlock Protector 2 is ready for beta, it currently only work with uBlock Origin (any browser), because even though I have libmicro code in there I'm 150% sure it's bugged beyond belief. 
Be warned that on Quantum, libquantumizer will inject `'unsafe-inline'` to every page. This may change in the future when the CSP bug is fixed in Quantum. 

Because ABR2 is now ready for beta, AAK-Cont will now stop accepting new issues, it will still be available for download, and the daily build task will run until ABR2 hits stable for 1 month. 

https://adblockprotector2.github.io/AdBlockProtector2/

-----

Things are getting boring and repetitive here, and no one wish to help on AAK-Cont side. Let's solve these two problems at once. 

When we talk about AAK-Cont, we think about cross browser support. Unfortunately, that project have not attracted enough attention and support, so I will end-of-life it if my following plan went as planned. 
[Update: I meant not enough attention from developers]

I want to create a new project, name undecided [Update: decided below], which will support Chrome, Chromium, Opera, and Quantum browsers; uBlock Origin, Adblock Plus, and AdBlock adblockers. Just like this project, it will be composed of a filter list and an extension (not Userscript). Support for Safari will be dropped and support for Edge is undecided. 
You are probably thinking, wouldn't that be even more boring and repetitive? Well, yes, unless... unless I have a bot to maintain all those repositories for me, it will scan for changes every day, and generate compatibility shim for each setup. 

Not sure how well this will go, I already have a graveyard of failed projects, one more wouldn't hurt. The important part is having fun.

**Comment by jspenguin2017** [comment]
**Extension Design**

One major problem we are having is that people don't know what to install. Although I like the idea of letting the user to decide what to do, an average person cannot make a good decision. Therefore, for the new project and the new project only, the companion extension will perform some testing: 
* When background script is starting up: 
    * If the adblocker it is designed to work with is found, that adblocker will be enabled and all other adblockers will be disabled; if at least one management action is performed, the user is notified and will be given the option to revert changes and uninstall the companion extension in one click
    * If the adblocker it is designed to work with is not found: 
        * If another adblocker is found, the companion extension will notify the user, bring the user to the install page of the correct extension, and uninstall itself
        * If another adblocker is not found, the companion extension will notify the user and disable itself
    * If extensions that are known to cause problems are found, they will be disabled and the user is notified; the user will be given the option to revert changes and uninstall the companion extension in one click
* When content script is executed: 
    * If the correct filter list is not installed, the companion extension will notify the user and bring the user to the correct install page; this can be opt-out in settings page
    * If the filter list for another companion extension is installed, the companion extension will notify the user and bring the user to instructions on how to fix his configuration; this can be opt-out in settings page

**Comment by jspenguin2017** [comment]
**Bot Design**

The bot will be equipped with a few parser and a few compatibility shim generators. It will download uBlock Protector and uAssets repositories, and generate code that would work for each platform once a day. It will also respond to explicit commands from me. 
This is the hard part, but also the fun part, I will be thinking and planning this in the coming weeks and hopefully I can get a working prototype by the end of the year.

**Comment by jspenguin2017** [comment]
**Reserved**

**Comment by jspenguin2017** [comment]
**Reserved**

**Comment by thrwat** [comment]
Thanks, but how do you find so much free time?

**Comment by uBlock-user** [comment]
Merge this into uBlock Protector and run it when it's ran for the first time and detect the setup, so give shim to those who're on other blockers and kep Protector for uBO users. Doable ?

**Comment by jspenguin2017** [comment]
@thrwat I don't, that's why I'm getting a bot to help me out. 

@uBlock-user Manifest configuration cannot be changed programmatically on Chromium, although I will investigate that idea for the companion extension for Quantum.

**Comment by jspenguin2017** [comment]
The new project will be called AdBlock Protector 2 (ABR2 for short). https://github.com/AdBlockProtector2
The bot will be called Alpha Bot, bot account name undecided, please refrain from rushing out register every good name that starts with Alpha.

**Comment by mat41997** [comment]
seriusly? this is not good marketing
![2017-10-29 14_05_48-ublock protector extension - chrome web store](https://user-images.githubusercontent.com/5884000/32144003-7a02bbe2-bcb2-11e7-93ab-825be9fad243.png)

**Comment by jspenguin2017** [comment]
Not this project, AAK-Cont: https://xuhaiyang1234.gitlab.io/AAK-Cont/
I think it looks OK, if you can get a better design, let me know.

**Comment by jspenguin2017** [comment]
I think it's a good opportunity to clean up some inefficient server code, I also moved `/API/uBlockProtector` to just `/uBlockProtector`, if there are any path that I forgot to change, let me know. 
Hopefully I didn't introduce any vulnerability while moving stuff around... 

I still need to clean up the client, although it's not as much of a priority since modern devices can handle the inefficiency. I'll start making the bot next week or the week after, anyone know a good GraphQL client library for Node?

**Comment by uBlock-user** [comment]
>  anyone know a good GraphQL client library for Node?

https://github.com/f/graphql.js ??

**Comment by Piter432** [comment]
Why no userscript? :(

**Comment by jspenguin2017** [comment]
Userscript depends on script hosts, which are made by independent author without consensus. There are no international standard for Userscript, making development impossible.

**Comment by uBlock-user** [comment]
UserScripts can't use browser API directly, which is a limitation.

**Comment by lfmnovaes** [comment]
I prefer this way, a complementary extension for uBlock. Looking forward to see the FF57 version of this.

**Comment by jspenguin2017** [comment]
It will probably only run on Quantum 58+

I haven't started coding the bot yet, don't expect it before next year.

**Comment by jspenguin2017** [comment]
I need to learn GraphQL, write a filter parser and transpiler, then make a customer service bot. I have only 1 line of code at the moment, at current pace, I won't be done before 2020. If someone wants to speed things up, PRs are welcomed over at AlphaBot repo.

**Comment by jspenguin2017** [comment]
I have 3 lines of code now. Good. Progress. 
Maybe I should make it a standalone application instead of integrating into my existing server.

**Comment by jspenguin2017** [comment]
Quantum 57 hit stable! Time to code!

**Comment by jspenguin2017** [comment]
I'm not sure how to use Quantum debugger, it definitely works on Chrome, I still have some debugging to do for Quantum, if someone wants to test it out, it's available for developers now. (See update in the opening)

What to report: 
- Crashes
- Does not for for a group of domains (example: fail on every page that has CSP)

What to not report:
- One website where it doesn't work

**Comment by siric1** [comment]
> Bot Design
> 
> The bot will be equipped with a few parser and a few compatibility shim generators. It will download uBlock Protector and uAssets repositories, and generate code that would work for each platform once a day. It will also respond to explicit commands from me.
> This is the hard part, but also the fun part, I will be thinking and planning this in the coming weeks and hopefully I can get a working prototype by the end of the year.

Have you considered using Webpack for this? After setting up it's configs it could do all of the automation for you, include the defined shims per browser, and generate builds for the supported browsers with one single command. Example boilerplate: https://github.com/samuelsimoes/chrome-extension-webpack-boilerplate

**Comment by jspenguin2017** [comment]
Currently the extension is universal, the single extension runs in every supported browser. 
Most of the work is making libmicro and splitting filter lists.

**Comment by jspenguin2017** [comment]
It's almost ready, I need to make a costume service bot then it's ready for public beta. 
Anyone know how do you inspect options page in Quantum? I can't inspect inside that element... 
![image](https://user-images.githubusercontent.com/7283682/32958862-f5cebe1e-cb7c-11e7-9446-993b771c3a3d.png)

**Comment by siric1** [comment]
Tried to inspect the same thing but looks like that's not possible. Why would you need that though? I don't believe you can give that any styling if that's what you wanted to do because FF enforces it's design guidelines on it - unless you do a custom settings page.

**Comment by jspenguin2017** [comment]
Styling does work, except the right border is missing, and I was trying to understand why. That page is fully inspectable on Chrome though.

**Comment by jspenguin2017** [comment]
Alright, the developer beta is fully ready now, it should work in Quantum and Edge (and Chrome ofc). Let's continue the discussion over in that repository.

**Comment by uBlock-user** [comment]
Are you going to discontinue uBlock Protector once AdBlockProtector2 is stable ?

**Comment by jspenguin2017** [comment]
No, uBR is a dependency of ABR2.

**Comment by jingyu9575** [comment]
> how do you inspect options page in Quantum

The inspector works here on 58.0b4 (Developer Edition). When it didn't work, I could debug the extension in about:debugging and switch the frame ![default](https://user-images.githubusercontent.com/8923139/33019336-d45eba94-ce34-11e7-9668-084aaf6df40d.png) to the option page, and then the page would be inspectable there.

**Comment by jspenguin2017** [comment]
OK, I'll try that when 58 hits stable.
