### ISSUE TITLE
livesport.ws

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#666]
http://livesport.ws/
<img width="960" alt="przechwytywanie2" src="https://user-images.githubusercontent.com/18214146/32015632-f5161250-b9c1-11e7-8a0f-24efdea88b3c.PNG">
<img width="960" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/32015638-f81fede0-b9c1-11e7-9fac-81221a039e89.PNG">

**Comment by uBlock-user** [comment]
`livesport.ws##script:inject(abort-on-property-read.js, document.avp_ready)`
