### ISSUE TITLE
curs.io

### ISSUE THREAD

**Issue by marmooz** [jspenguin2017/uBlockProtector#667]
not working on "curs.io"

example :        http://curs.io/3cGJSb

screenshot:     https://imgur.com/jbYua83

Screenshot of the console:     https://imgur.com/a9DEJbV

Scrips that i use in tampermonkey extension:     https://imgur.com/jKVksR0

Thanks for your attension 🎃

**Comment by uBlock-user** [comment]
clone of #183

**Comment by marmooz** [comment]
actually i made a simple change to the "AdsBypasser" script and added the "curs.io" because the console seemed similar to "urle.co".
Thanks for the reference 👍

**Comment by uBlock-user** [comment]
You don't need AdsByPasser or any such script. Just use this extension.
