### ISSUE TITLE
cnhv.co

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#669]
### Test link (required): 
https://cnhv.co/92vq

### Screenshot of the web page (required): 

![aaaa10-27_233547](https://user-images.githubusercontent.com/2828165/32126265-055b69c6-bb70-11e7-8a99-b4dcbd4f9798.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![aaaa2017-10-27_233624](https://user-images.githubusercontent.com/2828165/32126249-e8a75d6c-bb6f-11e7-89fd-25f7663056b5.png)

**Comment by uBlock-user** [comment]
See ->>>> https://github.com/jspenguin2017/uBlockProtector/issues/624
