### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#670]
### Test link (required): 
http://www.filmweb.pl/film/Thor%3A+Ragnarok-2017-707970
### Screenshot of the web page (required): 

![capture](https://user-images.githubusercontent.com/15007183/32136743-2f1486dc-bbe1-11e7-98de-fc120306b96f.PNG)

**Comment by xxcriticxx** [comment]
sorry false call had list off

**Comment by uBlock-user** [comment]
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/664
