### ISSUE TITLE
psl.io

### ISSUE THREAD

**Issue by c0achq** [jspenguin2017/uBlockProtector#671]
### Test link (required): 
http://psl.io/UoVP9d
### Screenshot of the web page (required): 
http://prntscr.com/h39j9z

### Screenshot of the console (press `F12` to bring up the console) (required): 
http://prntscr.com/h39jio

### Add everything else that you believe to be useful below (optional): 
Adblock detected,  also 10 second timer and captcha.  Please fix this @jspenguin2017 .  Thanks!

**Comment by uBlock-user** [comment]
clone of #183
