### ISSUE TITLE
NSFW! rule34hentai.net

### ISSUE THREAD

**Issue by catshitz** [jspenguin2017/uBlockProtector#672]
win10 1709 Pro
Chromium 61.0.3163.100
uBlock Origin 1.14.12
uBlockProtector 12.42

uBlock basic rules
EasyList
Adguard Base Filters
Adblock Warning Removal List
EasyPrivacy
and a few basic local rules

Random click open-up ads pages like this:
http://k26fe9xhuzm.com/921851.html?q
This happens whenever your first few opens of different sub-domain pages of rule34hentai.net,
and once after a sub open-up ads page appeared, it stops showing in the same page for long,
but the other continues before the first click, quite annoying.

Custom block rules showing like this,
##div:nth-of-type(17)
number changes, it won't help.

**Comment by jspenguin2017** [comment]
Can you fill the template?

**Comment by uBlock-user** [comment]
Test url - http://rule34hentai.net/post/view/275484

**Comment by uBlock-user** [comment]
https://github.com/uBlockOrigin/uAssets/commit/0cf71fb5e1ae0397e549e75fb2f05db8a3d8bac3

Nevermind, it's already patched.

**Comment by jspenguin2017** [comment]
I have `||rule34hentai.net^$inline-script` in List, that is a superset of the filter added to uAssets. And I can't reproduce popup.
