### ISSUE TITLE
wp.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#673]
https://github.com/MajkiIT/polish-ads-filter/issues/4037#issuecomment-340272304

i not can scroll this site
![2017-10-29 17_00_54-wirtualna polska - wszystko co wazne - www wp pl](https://user-images.githubusercontent.com/5884000/32145539-caed4cc6-bcca-11e7-99d8-218d82113d93.png)

``https://www.wp.pl/``
![2017-10-29 17_54_52-wirtualna polska - wszystko co wazne - www wp pl](https://user-images.githubusercontent.com/5884000/32146071-7c5411be-bcd2-11e7-99bc-c93ed48667a4.png)

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.44
chrome 62.0.3202.75
win10 x64

**Comment by jspenguin2017** [comment]
Fill the template.

**Comment by mat41997** [comment]
@jspenguin2017 ok, right now

**Comment by uBlock-user** [comment]
What's the issue here ?

**Comment by jspenguin2017** [comment]
Seems to be performance issue, I'll optimize the solution.

**Comment by jspenguin2017** [comment]
The performance of the website is really horrible to begin with, uBlock Protector is obviously going to make it worse, there is no way around that. It spins the main thread at 100% CPU on Edge too. 
I added some optimization so hopefully it will be faster.

**Comment by uBlock-user** [comment]
The whole domain should be added to Resource-abuse list then.

**Comment by jspenguin2017** [comment]
Also, @mat41997 fill the template next time, and keep the headings, it's hard to understand your issue.

**Comment by jspenguin2017** [comment]
@uBlock-user I don't think anyone will mine coins the the main thread, that's just stupid, it's probably some broken script stuck in a loop.

**Comment by jspenguin2017** [comment]
It should be way faster now, the slowdown was caused by uBO's observer.

**Comment by mat41997** [comment]
still not work ^^
i don't can scroll

**Comment by jspenguin2017** [comment]
uBO's content script can lock up on high node manipulations, update List to latest version and see if it helps.

**Comment by uBlock-user** [comment]
@jspenguin2017 I never said anything about coins and mining coins are not the only way to abuse resources. It's a generalized term. Any domain that abuses visitor's resources should be blocked in general.

**Comment by uBlock-user** [comment]
@mat41997 Install uMatrix and then try again. Should help.

**Comment by jspenguin2017** [comment]
I don't think that's abuse, more like bugged. They seem to have fixed the issue, it's not spinning CPU at 100% anymore.

**Comment by uBlock-user** [comment]
I don't think so, my RAM usage spikes to 45 % on the homepage, that's still horrible.
