### ISSUE TITLE
Remove anti-AdBlock DRM circumvention measures 

### ISSUE THREAD

**Issue by AdBlockDRM** [jspenguin2017/uBlockProtector#675]
### Describe the issue

uBlockProtector provides a functionality that is illegally bypassing anti-AdBlock DRM measures. anti-AdBlock is a DRM measure used to restrict access to a software blocking advertisements.
### Solution

Remove all the circumvention measures, that bypass anti-AdBlock DRM measures.
Remove the file: https://github.com/jspenguin2017/uBlockProtector/blob/master/uBlockProtectorList.txt

Note: **In case of non-compliance, legal action may be pursued.**

**Comment by lfmnovaes** [comment]
DRM protects copyrighted material, I don't get it when I choose to don't see an Ad I violate the copyright. Can you please explain?

**Comment by uBlock-user** [comment]
@jspenguin2017 Looks like we got ourselves another troll lurking around.

**Comment by AdBlockDRM** [comment]
Digital rights management (DRM) is a set of access control technologies for restricting the use of proprietary hardware and copyrighted works. DRM technologies try to control the use, modification, and distribution of copyrighted works (such as software and multimedia content), as well as systems within devices that enforce these policies. 

uBlockProtecter will be referred as "The software" from now on.

Anti-AdBlock DRM controls the distribution and visibility under certain conditions. The software circumvents the Anti-AdBlock DRM measures are used by publishers with copyrighted content meant not to be visible under conditions. 

Any public software circumventing the DRM measures is illegal under 
1. 17 U.S.C. §§ 512, 1201–1205 
2. 1301–1332; 28 U.S.C. § 4001
3. Directive 2001/29/EC

**Comment by thrwat** [comment]
:O @jspenguin2017 @uBlock-user 
What should be done about it?

**Comment by uBlock-user** [comment]
Nothing, we will let penguin deal with him.

**Comment by lfmnovaes** [comment]
Well, I've never seen a single webpage enforcing user to agree rules like 'you must agree to watch our ads to use our site'. While I never agreed to watch any kind of ads to begin with, I have the right to block every single ads they throwing at my face.

**Comment by jspenguin2017** [comment]
It's my right to decide which script gets to execute on my device.

**Comment by thrwat** [comment]
Javascript can be disabled, this is not how our system works. We block the user if Javascript is disabled. If Assembly language can be used as a DRM measure so can Javascript. Easier to bypass does not mean you can do it freely. 

This the final warning.  If action is not taken within next 3 working days, the repository will be taken down under DMCA laws. We have determined after legal consultation what you are doing is illegal.
