### ISSUE TITLE
Remove Anti-AdBlock DRM circumvention measures

### ISSUE THREAD

**Issue by ghost** [jspenguin2017/uBlockProtector#676]
Dear author,

On the behalf of the organization, this is a final warning.

Your work
https://github.com/jspenguin2017/uBlockProtector/blob/master/uBlockProtectorList.txt is a violation of our copyright enforcement measures.

Intentionally circumventing or promoting the circumvention of Anti-AdBlock DRM is a violation of: 
1. 17 U.S.C. §§ 512
2. 17 U.S.C. §§ 1201-1204 
3.  92/100/EEC

In case of non-compliance of the DMCA notice within three working days, this may escalate to the court.

I have a good faith belief that use of the material in the manner complained of here is not authorized by me, the copyright holder, or the law. The information provided here is accurate to the best of my knowledge. I swear under penalty of perjury that I am the copyright holder.

Sincerely,
Anti-AdBlock DRM Legal Team

**Comment by jspenguin2017** [comment]
Hi, DMCA does not apply to me.

**Comment by jspenguin2017** [comment]
> I swear under penalty of perjury that I am the copyright holder. 

You are the copyright holder of what? You cannot copyright domain names.

**Comment by AdBlockDRM** [comment]
A comprehensive list will be provided after an NDA is signed, make this private or contact us.

**Comment by jspenguin2017** [comment]
It's not a valid DMCA notice unless you provide more information.

**Comment by uBlock-user** [comment]
Would you just block the troll and be done with him ? Why allow him to post here for the second time ?

**Comment by AdBlockDRM** [comment]
@jspenguin2017 
The work 
https://github.com/jspenguin2017/uBlockProtector/blob/master/uBlockProtectorList.txt
circumvents our Anti-AdBlock DRM which is specifically a violation of 17 U.S.C. §§ 1201.

Anti-AdBlock DRM is our copyright.

Additionally, our client's legal action is taken by our side, as they have granted us the legal authority for their copyrights, which is a violation of multiple laws including but not limited to:

1. 17 U.S.C. §§ 512
2. 17 U.S.C. §§ 1201-1204
3. 92/100/EEC

The solution would be to add multiple websites to the exception.

Here is the list of the website(s) and domain(s) that enforce the DRM, add them to the exclusion list. Some of these websites may not completely restrict access but fall under the same category.

1. bild.de
2. hulu.com
3. softpedia.com
4. lolalytics.com
5. flightradar24.com
6. nbcsports.com
7. nbc.com 
8. bloomberg.com
9. theguardian.com
10. indiatimes.com

A further list of the domain(s) may be provided to you to add to the exclusion list.

**Comment by thrwat** [comment]
@jspenguin2017  
WTH? 
man I think you should remove them from list... This may become a huge trouble. fk corporations but these are big sites

Anyone who wants can add manually

**Comment by KingThunder** [comment]
Prove that you are the copyright owner of these sites.

**Comment by KingThunder** [comment]
i think this is more related to lolalytics...

**Comment by jspenguin2017** [comment]
Hi, thank you for being more forthcoming, I will be reaching out to these sited to validate the copyright claim that you swore under penalty of perjury. A snapshot of this issue page at time of this post is here: https://web.archive.org/web/20171030185921/https://github.com/jspenguin2017/uBlockProtector/issues/676

**Comment by jspenguin2017** [comment]
Did he just deleted his account?

**Comment by thrwat** [comment]
He trolled...

**Comment by uBlock-user** [comment]
hahahahahah, there you go.

**Comment by thrwat** [comment]
Close this issue, troll is gone 😆

**Comment by jspenguin2017** [comment]
Well, eh, let's call this fixed.

**Comment by AdBlockDRM** [comment]
Dear author,
The work
https://github.com/jspenguin2017/uBlockProtector/blob/master/uBlockProtectorList.txt
circumvents our Anti-AdBlock DRM which is specifically a violation of 17 U.S.C. §§ 1201. 

Your software is not in compliance and this may result in negative consequences. This is a reminder that you have 2 days remaining before escalating this issue further. 

This account is created specifically for legal purposes and is deleted after the conversation. 

Sincerely,
AdBlock DRM Legal Team

**Comment by uBlock-user** [comment]
Dear ghost, nobody cares!

**Comment by jspenguin2017** [comment]
That's just ridiculous, you can't file a copyright claim while staying anonymous.
