### ISSUE TITLE
globo.com

### ISSUE THREAD

**Issue by lfmnovaes** [jspenguin2017/uBlockProtector#677]
### Add everything else that you believe to be useful below (optional): 
It's possible to remove this current window with uBlock's Element Picker, but the scrollbar goes away.

**Comment by jspenguin2017** [comment]
You can use this: 
```
blogs.oglobo.globo.com##html,body:style(overflow: scroll !important;)
blogs.oglobo.globo.com###login-barreira
```
It's not anti-adblock so I won't add it to List.

**Comment by lfmnovaes** [comment]
Yeah, after posting it I thought about it again and It's more suitable for the Fanboy's Annoyance List than here, that's why I closed.
I tried your code and worked fine. Although I was getting 2 scrollbars, I removed the `!important` tag and now its perfect.

Anyway, thank you very much for your help.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by lfmnovaes** [comment]
To reproduce, you need to navigate the website for a while and then shows up the payment window.
Btw `||static.infoglobo.com.br/paywall/*$domain=oglobo.globo.com` is a better fix for this problem.

**Comment by uBlock-user** [comment]
I did that, nothing happens on my end. I don't see the login dialog at all.
