### ISSUE TITLE
drugs.com

### ISSUE THREAD

**Issue by onmyouji** [jspenguin2017/uBlockProtector#678]
### Test link (required): 
`https://www.drugs.com/mtm/chlorhexidine-gluconate-oral-rinse.html`

### Screenshot of the web page (required): 
https://vgy.me/l1wWTM.png

### Screenshot of the console (press `F12` to bring up the console) (required):
https://vgy.me/fVoqW8.png

### Add everything else that you believe to be useful below (optional): 
The page loads just fine, but after few seconds it shows empty white page.

Thanks

**Comment by uBlock-user** [comment]
`drugs.com##script:inject(abort-on-property-read.js, stop)`

**Comment by uBlock-user** [comment]
It's Google funding choices, if you're wondering.
