### ISSUE TITLE
meulink.tk

### ISSUE THREAD

**Issue by lfmnovaes** [jspenguin2017/uBlockProtector#679]
### Add everything else that you believe to be useful below (optional): 
I believe the block is from `http://meulink.tk/modern_theme/build/js/script.min.js?ver=4.1.0`, but disabling it breaks the page

**Comment by uBlock-user** [comment]
clone of #183 

filter -  `meulink.tk##script:inject(setTimeout-defuser.js, checkAdblockUser)`
