### ISSUE TITLE
tui.click

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#680]
http://tui.click/ZZ7Zo
<img width="306" alt="asas" src="https://user-images.githubusercontent.com/18214146/28378340-1f7756d0-6cb0-11e7-8b52-66324f42a7d7.PNG">
<img width="372" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/32254077-da195d72-be9e-11e7-9600-f26088edced0.PNG">

**Comment by uBlock-user** [comment]
clone of #183
