### ISSUE TITLE
vizer.tv

### ISSUE THREAD

**Issue by xitero** [jspenguin2017/uBlockProtector#681]
http://vizer.tv/assistir/serie/travelers/online/gratis

ADBLOCK detected
No ads can not stay online!
If you care about our service, turn off the adblock on the vizer.

![adblock](https://user-images.githubusercontent.com/28655175/32269941-1ed9f962-bedb-11e7-88c6-52f990ff251a.png)

**Comment by uBlock-user** [comment]
`@@||vizer.tv^$elemhide`

**Comment by jspenguin2017** [comment]
Can't reproduce. Fill the template.
