### ISSUE TITLE
mitele.es

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#682]
`http://www.mitele.es`
https://github.com/reek/anti-adblock-killer/issues/3628

**Comment by uBlock-user** [comment]
Can't reproduce. 

Does it happen on any specific link also ?

**Comment by jspenguin2017** [comment]
The home page is the test link. Nooping doesn't quite work for me, I'll investigate later.

**Comment by uBlock-user** [comment]
Nothing's changed in the script and nooping does it for me. Another potential solution would be to neuter `XMLHttpRequest.properties`.

**Comment by jspenguin2017** [comment]
That doesn't work neither.

**Comment by uBlock-user** [comment]
Are you serious ? Whitelisting always works. 

Alright do this `@@||akamaihd.net^$xmlhttprequest,domain=mitele.es`

**Comment by jspenguin2017** [comment]
That doesn't work neither, however, `@@||akamaihd.net^$xmlhttprequest,script,domain=mitele.es` works. 
I'll find an ideal solution later.

**Comment by uBlock-user** [comment]
Is the filter getting applied on your end ?

**Comment by jspenguin2017** [comment]
It is applied. Maybe you got another filter that white listed the script type.

**Comment by uBlock-user** [comment]
None, it's the ones I posted here. All of them work on my end.

**Comment by Dibbyo456** [comment]
@uBlock-user I can reproduce it - http://prntscr.com/h5ev0e

**Comment by lain566** [comment]
I can't view or play videos either.

**Comment by jspenguin2017** [comment]
Ops, that was the wrong reference...

**Comment by uBlock-user** [comment]
@Dibbyo456 I can also, if I remove [these filters](https://github.com/jspenguin2017/uBlockProtector/issues/682#issuecomment-341300789)

**Comment by Dibbyo456** [comment]
@uBlock-user. Yup. 
One more thing, can I have you email? I need a help to decrypt a JavaScript & change some CSS.
But I have no idea, how to decrypt it properly. It's BAB. 😁

**Comment by uBlock-user** [comment]
Copy the script, try it over jsnice.org or jsbeautifier.org and if that doesn't work ask penguin.

**Comment by jspenguin2017** [comment]
Doesn't quite work, videos don't play...

**Comment by uBlock-user** [comment]
Website's buggy.

**Comment by lain566** [comment]
Add this
`@@||analytics.edgesuite.net/js/csma.js$script,domain=mitele.es`

**Comment by jspenguin2017** [comment]
Yea, that's what I guessed, I'll fill it in with a surrogate.

**Comment by jspenguin2017** [comment]
Well, that was easier than I expected...

**Comment by lain566** [comment]
Can't play this video
`http://www.mitele.es/directo/cuatro`

**Comment by jspenguin2017** [comment]
Yep, it's broken.
