### ISSUE TITLE
filmweb.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#683]
anty-adblock has back
![2017-11-02 21_16_28-blade runner 2049 2017 - filmweb](https://user-images.githubusercontent.com/5884000/32348145-2d28053e-c013-11e7-8539-2bfb0d1b69af.png)
http://www.filmweb.pl/film/Blade+Runner+2049-2017-630798

https://github.com/MajkiIT/polish-ads-filter/issues/4210
https://gitlab.com/xuhaiyang1234/AAK-Cont/issues/335

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.53
chrome 62.0.3202.75

**Comment by mat41997** [comment]
still don't working

**Comment by jspenguin2017** [comment]
Can't reproduce, works fine after the fix.

**Comment by lain566** [comment]
It works only once, appears again when refreshing the page.

**Comment by jspenguin2017** [comment]
Should be good now.

**Comment by jspenguin2017** [comment]
Where did my build go?

**Comment by uBlock-user** [comment]
Cannot reproduce. The solution I posted before still works for me and even on numerous amount of refreshes too.
