### ISSUE TITLE
rapidvideo.com

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#684]
ublock off - works fine
![2017-11-03 16_11_47-macross delta - 25 mp4](https://user-images.githubusercontent.com/5884000/32380963-c65aef8e-c0b1-11e7-8465-07c109cee8c7.png)

ublock on - not works
![2017-11-03 16_15_23- 1 game](https://user-images.githubusercontent.com/5884000/32381129-3f2b7154-c0b2-11e7-880b-70e236ff5b1d.png)

test link
https://www.rapidvideo.com/?v=FK7XVGQ94C

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.12 & ubo-pe 12.54
chrome 62.0.3202.75

**Comment by uBlock-user** [comment]
Already patched by uBlock Filters. Force update your filters.

**Comment by uBlock-user** [comment]
`rapidvideo.com##a[href^="//"]`

For the nasty tabunder.

**Comment by mat41997** [comment]
@uBlock-user still don't work

**Comment by jspenguin2017** [comment]
Still can't reproduce.

**Comment by uBlock-user** [comment]
I'm able to reproduce the tabunder.
