### ISSUE TITLE
animezone.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#686]
- clear cookie/cache
- install popup blocker ``https://add0n.com/popup-blocker.html``
- join to ``http://www.animezone.pl/``
![2017-11-07 13_54_47-animezone pl - twoja strefa anime online pl](https://user-images.githubusercontent.com/5884000/32494959-f9f287de-c3c3-11e7-9b14-7b923db5dd8c.png)
- click 2 ( next site )
![2017-11-07 13_55_04-chrome-extension___cjpalhdlnbpafiamejdnhcphjbkeiagm_document-blocked html_detail](https://user-images.githubusercontent.com/5884000/32494967-00bac5e0-c3c4-11e7-8be9-282628b28a42.png)

https://github.com/MajkiIT/polish-ads-filter/issues/4311#issuecomment-342469981

my filters
https://gist.github.com/mat41997/51ae1f1fb7f2a32d795c0a17b855feef

ubo 1.14.16 & ubo-pe 12.59
chrome 62.0.3202.89

**Comment by uBlock-user** [comment]
Nothing to do with uBlock Protector, report to Filter list maintainer of Polska Filtry Adblocka  | uBlocka
