### ISSUE TITLE
adshort.im

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#687]
http://adshort.im/ZNp29B6
<img width="306" alt="asas" src="https://user-images.githubusercontent.com/18214146/28378340-1f7756d0-6cb0-11e7-8b52-66324f42a7d7.PNG">
Can't do a screenshot of the console because I'm getting the message "Console was cleared" all the time.

**Comment by uBlock-user** [comment]
clone of #183
