### ISSUE TITLE
i don't can install ublock protector on yandex browser (android)

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#688]
![2017-11-08 16_10_10-releases jspenguin2017_ublockprotector](https://user-images.githubusercontent.com/5884000/32556359-7bec18b4-c49f-11e7-9b2a-02035af32802.png)

``https://www.youtube.com/watch?v=DgSkfzSb5BI``

android 5.1
yandex browser
ublock 1.14.19b0

**Comment by lain566** [comment]
This project has no release file, you have to download this project as a zip file, and unzip the folder called `Extension`

**Comment by uBlock-user** [comment]
Try via Chrome Store if it supports or do it manually.

**Comment by mat41997** [comment]
@uBlock-user i don't can
![screenshotcapture_2017_11_08_17_55_13](https://user-images.githubusercontent.com/5884000/32562207-56ed13b0-c4ae-11e7-9e92-016ea154ddd2.png)

**Comment by mat41997** [comment]
@lain566 ok works. thx : )

**Comment by jspenguin2017** [comment]
Only Chromium and Chrome are supported, as stated in contribution guideline. 
Make sure to read over the contribution guideline before opening another issue or you risk to be banned.

**Comment by mat41997** [comment]
@jspenguin2017 
>  "based on the Chromium open source project."
``https://en.wikipedia.org/wiki/Yandex_Browser``

**Comment by mat41997** [comment]
@jspenguin2017 
>  "based on the Chromium open source project."
``https://en.wikipedia.org/wiki/Yandex_Browser``

**Comment by jspenguin2017** [comment]
So what?

**Comment by mat41997** [comment]
@jspenguin2017 sorry, i did not know.

**Comment by uBlock-user** [comment]
"based on the Chromium project" also includes Yandex as it's a Chromium clone so it should be supported too, that's what he meant in https://github.com/jspenguin2017/uBlockProtector/issues/688#issuecomment-342910387

**Comment by jspenguin2017** [comment]
If you want to support other Chromium forks, feel free to fork.
