### ISSUE TITLE
coin.mg

### ISSUE THREAD

**Issue by notahaxor** [jspenguin2017/uBlockProtector#689]
### Test link (required): 
http://coin.mg/WAYrc
### Screenshot of the web page (required): 

http://prntscr.com/h81g7g
### Screenshot of the console (press `F12` to bring up the console) (required): 

http://prntscr.com/h81gb9
### Add everything else that you believe to be useful below (optional): 
I did my best to add it myself,  but I'm no professional,  so I may have done it wrong.  Please take a look at my edit and either approve it or modify it to make it work.  Thanks!  :D

**Comment by uBlock-user** [comment]
clone of #183
