### ISSUE TITLE
cutearn.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#691]
### Test link (required): 
http://cutearn.com/rEq

### Screenshot of the web page (required): 
![n2017-11-10_103207](https://user-images.githubusercontent.com/2828165/32649413-96429904-c602-11e7-8013-d3a05c45da8f.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![n12017-11-10_103257](https://user-images.githubusercontent.com/2828165/32649421-9cd9ccf6-c602-11e7-96d9-375957ef21d3.png)

**Comment by uBlock-user** [comment]
clone of #183
