### ISSUE TITLE
egy.best

### ISSUE THREAD

**Issue by nightknight13** [jspenguin2017/uBlockProtector#692]
https://egy.best/

This website is still detecting uBlock Origin.
player is blocked

screenshot
<img src="https://image.ibb.co/jEdLnb/Capture.png" alt="Capture" border="0">

screenshot of consol
<img src="https://image.ibb.co/jYkfLw/Capture2.png" alt="Capture2" border="0">

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
Can't reproduce.

**Comment by ghajini** [comment]
producible on link
https://egy.best/movie/totem-2017/
scroll little downward, you will see warning

**Comment by uBlock-user** [comment]
```
egy.best##script:inject(abort-on-property-read.js, check_adblock)
egy.best##a[href^="//"]
```
