### ISSUE TITLE
NSFW! xmovies8.es

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#693]
### Test link (required): 
`https://xmovies8.es/movie/finding-dory-2016-161103.98296/watching.html`
### Screenshot of the web page (required): 
![watch_finding_dory__watch_finding_dory__xmovies8_2017-11-11_18-50-35](https://user-images.githubusercontent.com/27441315/32692035-5bc83774-c711-11e7-9e47-62b7097174e1.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpsxmovies8 esmoviefindin_2017-11-11_18-50-46](https://user-images.githubusercontent.com/27441315/32692038-61452658-c711-11e7-8f82-86b2ce00d07e.png)

**Comment by uBlock-user** [comment]
same as https://github.com/jspenguin2017/uBlockProtector/issues/572
