### ISSUE TITLE
okdiario.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#694]
### Test link (required): 
`https://okdiario.com/`
### Screenshot of the web page (required): 
![okdiario_-_el_sitio_de_los_inconformistas_-_google_2017-11-11_19-28-09](https://user-images.githubusercontent.com/27441315/32692378-6a2fc3da-c717-11e7-94fd-79e47a0a4b78.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpsokdiario com_2017-11-11_19-28-18](https://user-images.githubusercontent.com/27441315/32692379-7000e776-c717-11e7-939d-5c55e734aa76.png)

**Comment by uBlock-user** [comment]
`||okdiario.com/*/check-blocker.js$script`
