### ISSUE TITLE
fotbollskanalen.se, tv4.se

### ISSUE THREAD

**Issue by crdil** [jspenguin2017/uBlockProtector#695]
Can't play videos from the domains in the subject.

![](https://i.imgur.com/OvUufmP.png)

**Comment by jspenguin2017** [comment]
Fill the template.

**Comment by lassekongo83** [comment]
Most likely a bad filter in the list: `||damoh.*^$media`

Using `||damoh.tv4play.se^$xmlhttprequest,redirect=nooptext` works.

**Comment by jspenguin2017** [comment]
It's not a bad filter, that filter is intentional.

**Comment by uBlock-user** [comment]
Nothing to do with this Extension. It's geo-locked.

**Comment by uBlock-user** [comment]
@lassekongo83 Not a bad filter, that stops video ads.

**Comment by lassekongo83** [comment]
Yep, I see that now. Forgot about the $media part. The fix for OP however is to figure out which filter or other extension that is blocking the xhr request to `damoh.tv4play.se` and apply my fix above.

**Comment by jspenguin2017** [comment]
Yea, the place of that generic filter is misleading, I moved it to the top.

**Comment by crdil** [comment]
The video starts to play, but just with sound. So I can hear the sound playing but there's no picture, just white.

**Comment by jspenguin2017** [comment]
Fill the template.

**Comment by uBlock-user** [comment]
This is what I get on my end in the console

`Uncaught (in promise) ecode: "asset_playback_invalid_geo_location"details: {error: {…}}fatal: truemessage: "Ip address '*.*.*.*' does not have access to category '3060317'"type: "vimond"__proto__: Object`

The only thing I'm blocking is `googletagmanager` and `googletagservices`.

**Comment by uBlock-user** [comment]
`fotbollskanalen.se` also has embedded videos from `tv4.se` which don't play, nothing else.

**Comment by crdil** [comment]
Like this?
![image](https://user-images.githubusercontent.com/11871071/32698090-ec959714-c79e-11e7-96fe-faf80df23cbd.png)

**Comment by jspenguin2017** [comment]
Go read the contribution guideline, and open another issue when you properly understood it.
