### ISSUE TITLE
NSFW! netdna-storage.com

### ISSUE THREAD

**Issue by hatplay** [jspenguin2017/uBlockProtector#696]
### Test link (required): 
http://netdna-storage.com/f/HNLCtfYs/EV-Rikksnatchesahotguyinthesubway.mp4.html

### When I click the download button, 
![image](https://user-images.githubusercontent.com/27808164/32699331-bd971d5c-c7ee-11e7-9e82-59981f49b8b9.png)

### it now goes to the file-not-found page with any of the two plugins on.
![image](https://user-images.githubusercontent.com/27808164/32699336-d3b356f0-c7ee-11e7-854d-b3af1a18f824.png)

### BUT it should go to the continue page as it did before with the plugins on.
![image](https://user-images.githubusercontent.com/27808164/32699349-1ae5678e-c7ef-11e7-8fea-63fc072578e7.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![image](https://user-images.githubusercontent.com/27808164/32699468-4f09303e-c7f1-11e7-925c-5b16dd3e8ff9.png)

**Comment by uBlock-user** [comment]
If I disable the Extension, I get sent to http://viwright.com/BIj8 which is `adf.ly` clone.

**Comment by hatplay** [comment]
Yes, then you wait and it will eventually turn to the continue page if you disable both Extension uBO and uBP.

**Comment by uBlock-user** [comment]
No, by extension, I meant uBlock Protector only.

**Comment by hatplay** [comment]
Got it. But the problem is that disabling any one of the two extensions, the page will not turn into the continue page.

With only the uBlock Origin on:
![image](https://user-images.githubusercontent.com/27808164/32700410-b549a01e-c7ff-11e7-928f-5548e22f8099.png)

**Comment by hatplay** [comment]
Previously, the two extensions together work perfectly well.

**Comment by lain566** [comment]
There is a popup when clicked anywhere on the page.

**Comment by jspenguin2017** [comment]
Can't reproduce that. Maybe update your filters?

**Comment by lain566** [comment]
Ahm ok, I see, I have enabled `Dan Pollock's list` and `MVPS HOSTS list`, if I disable it, disappears.
It's weird.

**Comment by hatplay** [comment]
Same here. There have been popups for days. But there wasn't when the file-not-found bug was fixed.

**Comment by jspenguin2017** [comment]
Should be fixed now.

**Comment by hatplay** [comment]
Thank you, penguin!
