### ISSUE TITLE
hgtv.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#698]
![capture](https://user-images.githubusercontent.com/15007183/32708604-ecb4d872-c7f8-11e7-9ae7-125a76376f14.PNG)

**Comment by jspenguin2017** [comment]
Can you not open 5 issues for the same problem?

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by uBlock-user** [comment]
Open one issue and group them all, that saves time and gets patched quickly.
