### ISSUE TITLE
ostrzeszowinfo.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#703]
![2017-11-14 18_25_33-ostrzeszowinfo pl - najwiekszy portal informacyjno - rozrywkowy w regionie](https://user-images.githubusercontent.com/5884000/32794468-41259b3c-c969-11e7-9f9d-42cf71ad1b46.png)
`ostrzeszowinfo.pl`

https://github.com/MajkiIT/polish-ads-filter/issues/4470#issuecomment-344319984

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.74
chrome 62.0.3202.94

**Comment by uBlock-user** [comment]
Site appears broken in the middle ? Otherwise, I don't see anything else.

**Comment by hawkeye116477** [comment]
@jspenguin2017 On infostrow.pl is same problem.
