### ISSUE TITLE
infostrow.pl

### ISSUE THREAD

**Issue by hawkeye116477** [jspenguin2017/uBlockProtector#704]
### Test link (required): 
http://infostrow.pl/
### Screenshot of the web page (required): 
![screenshot_20171114_195839](https://user-images.githubusercontent.com/19818572/32798887-58512d46-c976-11e7-915c-a3c9064960d3.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![screenshot_20171114_195817](https://user-images.githubusercontent.com/19818572/32799011-aba7982c-c976-11e7-9698-2ff6b516a5be.png)

### Add everything else that you believe to be useful below (optional): 
uBlock Protector Extension 12.75
Chromium 62.0.3202.75

**Comment by uBlock-user** [comment]
same issue as #703
