### ISSUE TITLE
Console Messages

### ISSUE THREAD

**Issue by gotitbro** [jspenguin2017/uBlockProtector#706]
_**uBO Protector**_ shows some messages in the console log which I don't think are needed and these also inundate the Console making other info harder to assess.

For example the `Domain:` message. I don't believe it is needed as that's just extraneous information that is upfront for the user and can also be accessed very easily through **_uBO's Logger_** which is much extensive.

The same goes for `This domain is excluded from all generically applied solutions` which can also be very easily assessed from the Logger. There also seems to be some issue with this message as it appears for websites where generic filters aren't even excluded.

**SS:** https://i.imgur.com/Saioogi.png

**Error URL:** 
https://www.google.com/amp/s/www.cnbc.com/amp/2017/11/17/wall-street-is-freaking-out-as-ea-caves-again-to-social-media-outrage-over-its-star-wars-game.html (Use Chrome's Device emulator to see the AMP page)

It would be better if these messages aren't shown in the Console as it would help assess other messages by the website better.

**Comment by jspenguin2017** [comment]
How do you easily access them from the Logger? If it's possible then I wouldn't have added those logs.

**Comment by gotitbro** [comment]
@jspenguin2017 Maybe I am not understanding correctly. Can you explain what these mean exactly?
```
Domain:
This domain is excluded from all generically applied solutions
```

**Comment by jspenguin2017** [comment]
It means a frame in the webpage has that domain, and generic solutions are excluded (`a.generic()`, `a.generic.Adfly()`, and `a.generic.NoAdBlock()`). 
Although frames are logged in the Logger, it's hard to associate them with further output from uBlock Protector, so that's why I print the domain.

**Comment by uBlock-user** [comment]
> Can you explain what these mean exactly?

It says what exactly it means, Generic rules are not applied on that domain at all. 

On the contrary, console messages make things easy when assesing whether the anti adblock script is patched on a specific domain or not and whether the specific domain has been added to the list of Extension rules or not, so I say keep them.

**Comment by gotitbro** [comment]
@jspenguin2017 Thanks. So lets say I visit https://github.com even then the `Domain: github.com` message is shown. What is the point of showing it here?

If the `Domain:` message is to be shown for iframes only show it when further messages such as generic solution not applied are to be shown. What is the point of the `Domain:` messages otherwise?

Another thing which domains are excluded from generic solution and why?

**Comment by jspenguin2017** [comment]
Yea, it does it for the main frame too, it's just one more message, it's not always easy to know if the frame is main frame or not, I don't see the point of checking for that. 

I don't want to have complex logic for spitting out one console message. 

White lists are here, reasons in comments: 
https://github.com/jspenguin2017/uBlockProtector/blob/master/Extension%20Compiler/Extension/content/3-content-rules-1-common.js

**Comment by gotitbro** [comment]
@jspenguin2017 Say I am on a website which uses social media embeds for likes, tweets, plus ones (Google+) etc. then the `Domain:` messages get excessive. And a lot of websites use these social media plugins these days.

Also a website where there are a lot of embeds like Reddit in such as well cases these messages get excessive.

It is also easy to see what iframes are on a page through the "Application" tab on the Console.

And since Facebook, Google etc. are used on a lot of websites the "generically solutions not applied" also get excessive.

I am not sure what should be done but yes the Console messages output by uBlock Protector get excessive that much can be said.

**Comment by jspenguin2017** [comment]
> I am not sure what should be done

Well, I can't do anything unless there is something reasonable I can do.

**Comment by uBlock-user** [comment]
Just use console filters, if you need to weed out.

**Comment by jspenguin2017** [comment]
That's kind of hard actually, as those filters are based on type, and uBlock Protector pretty much use every type. 
I'm open for suggestions, but the current implementation is the most reasonable that I can come up with.

**Comment by gotitbro** [comment]
@jspenguin2017 I have to say one thing man, initially when you just started uBlock Protector and with your tussles with the community you didn't come out as very good. But you have turned around to be one of the nicest devs.

An internet hug from a stranger ;D

**Comment by uBlock-user** [comment]
I meant using **console sidebar**, it offers numerous categories for as required by the user.
