### ISSUE TITLE
wurstclient.net

### ISSUE THREAD

**Issue by 1145141919** [jspenguin2017/uBlockProtector#707]
#

### Test link (required): 
https://www.wurstclient.net/download/
or
https://www.wurstclient.net/tutorials/

### Screenshot of the web page (including address bar and extension icons) (required): 

![default](https://user-images.githubusercontent.com/25715415/32980489-9802f9ba-ccaa-11e7-847a-977e1e5d2797.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![59fd25663f330991a5485a8f5aeb679a](https://user-images.githubusercontent.com/25715415/32980429-9336b486-cca9-11e7-8c4e-89f39d5ede44.png)

### Add everything else that you believe to be useful below (optional): 
chrome ver:62.0.3202.94 (Official Build) (64-bit) 
the mysterious dialog
![default](https://user-images.githubusercontent.com/25715415/32980421-82763a68-cca9-11e7-9aa6-0c31fa7965d7.png)

--

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
It's checking the height of an element, maybe you have a CSS filter.

**Comment by uBlock-user** [comment]
Nope, no specific filter. It just doesn't happen on my end and yes I know what its checking.

**Comment by uBlock-user** [comment]
I do have network filters blocking `/cdn-cgi/pe/bag2` XHR requests, that must be it.
