### ISSUE TITLE
cutwi.in

### ISSUE THREAD

**Issue by KiraYamatoSD** [jspenguin2017/uBlockProtector#708]
### Test link (required): 
https://cutwi.in/SBXD

### Screenshot of the web page (including address bar and extension icons) (required): 

<a href="https://imgur.com/bs0m4ux"><img src="https://i.imgur.com/bs0m4ux.png" title="source: imgur.com" /></a>

### Screenshot of the console (press `F12` to bring up the console) (required): 

<a href="https://imgur.com/EPOS8YZ"><img src="https://i.imgur.com/EPOS8YZ.png" title="source: imgur.com" /></a>

### Add everything else that you believe to be useful below (optional): 
<a href="https://imgur.com/RSY4lvK"><img src="https://i.imgur.com/RSY4lvK.png" title="source: imgur.com" /></a>

**Comment by uBlock-user** [comment]
These people never change, swaping domains is not last long to evade.

clone of #183
