### ISSUE TITLE
ourl.io

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#709]
https://ourl.io/qydtc
<img width="306" alt="asas" src="https://user-images.githubusercontent.com/18214146/28378340-1f7756d0-6cb0-11e7-8b52-66324f42a7d7.PNG">
<img width="482" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/32989894-4e8143c6-cd1f-11e7-94af-edea4688f531.PNG">

**Comment by uBlock-user** [comment]
clone of #183
