### ISSUE TITLE
programinadresi.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#713]
### Test link (required): 
`http://www.programinadresi.com/`

### Screenshot of the web page (including address bar and extension icons) (required): 
![programinadresi__full_programlar_-_google_chrome_2017-11-20_09-10-44](https://user-images.githubusercontent.com/27441315/33009892-93f9e75a-cdd8-11e7-87ec-c12d845ec413.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2017-11-20_09-13-04](https://user-images.githubusercontent.com/27441315/33009894-9732ed36-cdd8-11e7-91af-d0b36963464a.png)

**Comment by uBlock-user** [comment]
`programinadresi.com##script:inject(setTimeout-defuser.js, adBlock)`
