### ISSUE TITLE
arenavision.us

### ISSUE THREAD

**Issue by Juananchrome** [jspenguin2017/uBlockProtector#714]
First of all, many thanks for your contributions and making avalable uBlock Protector.

I have installed it along with uBlock origin as well as the list and this website arenavision.us still detects it as it can be seen in the screenshot (I'm using Chrome 62.0.3202.94 (Build oficial) (64 bits) with Ubuntu 16.04.3 LTS) 

![arenavision](https://user-images.githubusercontent.com/33831839/33017423-93b5a530-cdf2-11e7-957c-a99118ec4722.png)

Mny thanks for your time
Juanan

**Comment by uBlock-user** [comment]
Can't reproduce.

Generic BAB defuser took care of it.

**Comment by jspenguin2017** [comment]
I have a template for a reason.

**Comment by Juananchrome** [comment]
Sorry I'm pretty new here and didn't read properly the two screenshots needed (only one). Here's the other one if it helps
![captura de pantalla de 2017-11-21 12-07-39](https://user-images.githubusercontent.com/33831839/33069882-437c903c-ceb6-11e7-925a-87a0e9eca2a5.png)

**Comment by Juananchrome** [comment]
And the text link
http://www.arenavision.us/eventsguide_hf8folyujbik6
