### ISSUE TITLE
nba.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#715]
### Test link (required): 
`http://www.nba.com/scores#/`

### Screenshot of the web page (including address bar and extension icons) (required): 
![scores__nba com_-_google_chrome_2017-11-20_13-26-30](https://user-images.githubusercontent.com/27441315/33018484-e2672556-cdf6-11e7-8370-43d1cef3d4af.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpwww nba comscores_2017-11-20_13-26-43](https://user-images.githubusercontent.com/27441315/33018497-eb741884-cdf6-11e7-9912-8562b43ebaad.png)

**Comment by uBlock-user** [comment]
`/sourcepoint/`
