### ISSUE TITLE
viasatsport.se

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#716]
### Test link (required): 
`https://www.viasatsport.se/sport/motor/nyheter/alonso-kaxiga-svar-nar-han-rankar-de-basta`

### Screenshot of the web page (including address bar and extension icons) (required): 
![alonso_kaxiga_svar_-_nar_han_rankar_de_basta_ _via_2017-11-20_21-06-49](https://user-images.githubusercontent.com/27441315/33039043-f10141e2-ce36-11e7-8848-f4d37e6af064.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpswww viasatsport sesport_2017-11-20_21-07-02](https://user-images.githubusercontent.com/27441315/33039047-f50d73aa-ce36-11e7-9a72-838fea0cbe0a.png)

**Comment by jspenguin2017** [comment]
This feels like a tough one.

**Comment by uBlock-user** [comment]
Happening again ? I remember this one getting patched once.

**Comment by jspenguin2017** [comment]
Yea, it broke.

**Comment by lassekongo83** [comment]
[These filters](https://github.com/jspenguin2017/uBlockProtector/issues/359#issuecomment-314391926) still works for me.

**Comment by jspenguin2017** [comment]
Hum, OK, I'll test them out.
