### ISSUE TITLE
rufootballtv.org

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#719]
https://www.rufootballtv.org/
<img width="900" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/33072114-719883e2-cebe-11e7-8c14-468ca3bd2d67.PNG">
<img width="325" alt="przechwytywanie1" src="https://user-images.githubusercontent.com/18214146/33072117-746bb67a-cebe-11e7-837e-34b687151997.PNG">

**Comment by uBlock-user** [comment]
`rufootballtv.org##script:inject(abort-on-property-read.js, adblock)`
