### ISSUE TITLE
play.nova.bg

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#721]
### Test link: 
https://play.nova.bg/programi/purvichna-sila/893252?autostart=true

### Screenshot of the web page (including address bar and extension icons) (required): 

![image](https://user-images.githubusercontent.com/7283682/33102332-83d4bac4-ced9-11e7-830a-0234a459a729.png)

https://github.com/jspenguin2017/uBlockProtector/commit/72768a717cc3ed47cfa1ddff288a835a0a068a5f
The request is sent from Flash object, I have no way to replace it. 
`@@||playapi.play.mtgx.tv/v3/adinfo?$object-subrequest` doesn't work since `replaceXHR` cannot alter object subrequests.

**Comment by uBlock-user** [comment]
What happened to replacing the player like you used to do ? Did you remove it ?

**Comment by jspenguin2017** [comment]
I don't replace players anymore, more and more players are protected so replacing players isn't always an option. This is fixed btw: https://github.com/jspenguin2017/uBlockProtector/commit/ad73134d4cd013d339fd8cb6481be29d77c1944f

**Comment by uBlock-user** [comment]
You mean DRM-protected right ? Yeah that could be another issue if you were to replace with a custom player.
