### ISSUE TITLE
sadistic.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#722]
### Test link (required): 
https://www.sadistic.pl/

### Screenshot of the web page (including address bar and extension icons) (required): 
![capture](https://user-images.githubusercontent.com/15007183/33103671-ac479f9a-cef1-11e7-92a1-8444aecc568e.PNG)

**Comment by jspenguin2017** [comment]
Fixed although I think the website is broken.

**Comment by uBlock-user** [comment]
`sadistic.pl##script:inject(abort-current-inline-script.js, document.getElementById, is-media-valid)`

**Comment by uBlock-user** [comment]
They removed the script.
