### ISSUE TITLE
cut-win.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#725]
### Test link (required): 
https://cut-win.com/1ocrGwUc

### Screenshot of the web page (including address bar and extension icons) (required): 
![cutt-23_110004](https://user-images.githubusercontent.com/2828165/33164945-a4995732-d03d-11e7-8d37-8acbda62bbe0.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![cuttt1-23_110050](https://user-images.githubusercontent.com/2828165/33164961-af8a3756-d03d-11e7-9e26-3e25f11fa7ff.png)

**Comment by uBlock-user** [comment]
```
Resource Limit Is Reached
The website is temporarily unable to service your request as it exceeded resource limit. Please try again later.
```
