### ISSUE TITLE
adyou.me

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#726]
### Test link (required): 
http://www.adyou.me/pmhO

### Screenshot of the web page (including address bar and extension icons) (required): 
![adyoume11-23_113759](https://user-images.githubusercontent.com/2828165/33166450-f95e8422-d042-11e7-89f4-512b17c9649d.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![adyoumm11-23_113847](https://user-images.githubusercontent.com/2828165/33166458-002ba50a-d043-11e7-8c75-e4489de1670a.png)

**Comment by uBlock-user** [comment]
Can't reproduce.

`Uncaught Error: BlockAdBlock uBlock Origin detector is not allowed on this device!`

**Comment by jspenguin2017** [comment]
The generic solution doesn't always work actually.

**Comment by uBlock-user** [comment]
It's working here, can you reproduce ?

**Comment by jspenguin2017** [comment]
Yea, it doesn't work for me.
