### ISSUE TITLE
kryminalnapolska.pl

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#730]
![2017-11-30 22_27_44-kryminalna polska](https://user-images.githubusercontent.com/5884000/33455888-bceee690-d61d-11e7-8625-0f9ad2b54c01.png)
`https://www.kryminalnapolska.pl/`

https://github.com/MajkiIT/polish-ads-filter/issues/4670#issuecomment-348259478

my filters
https://gist.github.com/mat41997/809ef17633ba86197db6df03d6790f16

ubo 1.14.18 & ubo-pe 12.115
chrome 62.0.3202.94

**Comment by uBlock-user** [comment]
They're also screwing up the element picker if used to block the overlay.

**Comment by jspenguin2017** [comment]
Can't reproduce that.

**Comment by uBlock-user** [comment]
Not happening anymore but it happened when I reported, either they removed the script that did that or it got patched by your solution.
