### ISSUE TITLE
doublemesh.com

### ISSUE THREAD

**Issue by Connor37** [jspenguin2017/uBlockProtector#732]
### Test link (required): 
https://www.doublemesh.com/best-free-file-hosting-websites/

### Screenshot of the web page (including address bar and extension icons) (required): 
![image](https://user-images.githubusercontent.com/8341213/33516218-6b77211c-d76f-11e7-865c-83319d24802d.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![image](https://user-images.githubusercontent.com/8341213/33516220-79c1bbe2-d76f-11e7-9020-e5a4449cfcf3.png)

**Comment by uBlock-user** [comment]
`doublemesh.com##script:inject(setTimeout-defuser.js, ads)`
