### ISSUE TITLE
Browser crashes when clicking at Options on chrome://extensions/ page

### ISSUE THREAD

**Issue by uBlock-user** [jspenguin2017/uBlockProtector#733]
### Test link (required): 

chrome://extensions/

### Reproduction steps (optional if trivial): 

1) Open chrome://extensions/
2) Locate the extension and click on Options and the browser shuts itself down

### Add everything else that you believe to be useful below (optional): 

v12.118
Win 10 x64 Pro
Chromium 64.0.3275.0 x64

This doesn't happen with other extensions with `Options` page and neither when opening `Options` via right click and clicking on `Options` or when directly clicking on the Extension icon.

**Comment by jspenguin2017** [comment]
Can't reproduce. I only support latest stable version of Chrome and Chromium.

**Comment by uBlock-user** [comment]
Did you try it like 2-3 times in succession ?

**Comment by jspenguin2017** [comment]
Nope, doesn't crash. 
It's not my problem either way. Report to Chromium bug tracker.

**Comment by uBlock-user** [comment]
Yeah probably a buggy build on Chromium side.
