### ISSUE TITLE
shortify.pw

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#734]
### Test link (required): 
http://www.shortify.pw/brazzers

### Screenshot of the web page (including address bar and extension icons) (required): 
![brazz3_000728](https://user-images.githubusercontent.com/2828165/33520186-934f71d6-d7be-11e7-9834-ee39354d1895.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![brazer22212-03_000915](https://user-images.githubusercontent.com/2828165/33520187-9a721054-d7be-11e7-82fb-6c15e24fa4b0.png)

**Comment by uBlock-user** [comment]
`shortify.pw##script:inject(abort-current-inline-script.js, document.getElementById, AdBlock)`
