### ISSUE TITLE
Setting for Logging mode

### ISSUE THREAD

**Issue by wsoyka** [jspenguin2017/uBlockProtector#735]
### Test link (required): 
any site (google.com)

### Screenshot of the web page (including address bar) (required): 
<img width="1601" alt="screen" src="https://user-images.githubusercontent.com/2890574/33520592-611c85be-d7be-11e7-9eb1-32982e65a83a.png">

### Explain what was not right (optional if obvious): 
uBlock Protector prints "Domain: {domain}" for every page visited to the console. Almost always another line "{excluded from generic ...}". Working on Websites/Userscripts this is very annoying, esp as its printed for every iFrame (?) again, resulting in 2-5 copies of those messages in the console.

Would be very nice if there was a option to disable console.log's 
(or better yet disable logs per default and making a switch to enable them, as extensions printing info level logs is non standard afaik)

**Comment by jspenguin2017** [comment]
There is no way to configure content script.

**Comment by wsoyka** [comment]
Well then what about disabling info level logging for normal users? It seems kind of irresponsible to clutter every users console with messages that don't provide information for them. If those messages are meant for debugging or development purposes they should only be shown in debug mode, don't you think?

**Comment by jspenguin2017** [comment]
I want to see the console output on the user's end to quickly find problems.

**Comment by uBlock-user** [comment]
Hardly annoying, just one or two lines don't turn the console into a drastic annoyance. Also you can also setup to activate which categories you want to see into console if you're using it.
