### ISSUE TITLE
crockolinks.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#736]
### Test link (required): 
http://crockolinks.com/YrMT6r

### Screenshot of the web page (including address bar and extension icons) (required): 

![crocko-03_013015](https://user-images.githubusercontent.com/2828165/33520747-ac03b2ae-d7c9-11e7-82ba-eb20284793d9.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![crocko 2203_013049](https://user-images.githubusercontent.com/2828165/33520749-b0f3c5c4-d7c9-11e7-8751-5978830633df.png)

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
uBO doesn't hide the element fast enough, but if it win the race once it will win every subsequent time. It's about how the element hider is optimized.

**Comment by uBlock-user** [comment]
I'm not sure what you mean. I can't reproduce at will for most of the time, only if I do it for like 4-5 times then it happens, and my filter works.

**Comment by jspenguin2017** [comment]
If you use `a.timewarp` to slow down the `setTimeout`, then you'll reproduce every time. 
Don't worry about it, I have a fix in place already.
