### ISSUE TITLE
srt.am

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#737]
### Test link (required): 
http://srt.am/m6QBvC

### Screenshot of the web page (including address bar and extension icons) (required): 
![earn_money_with_short_links _make_short_links _sha_2017-12-03_15-41-34](https://user-images.githubusercontent.com/27441315/33526385-b24cc3ae-d840-11e7-859e-f41ccca6a900.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![developer_tools_-_httpsrt amm6qbvc_2017-12-03_15-41-49](https://user-images.githubusercontent.com/27441315/33526383-aa37e680-d840-11e7-935c-f3cc2bd564ec.png)

**Comment by jspenguin2017** [comment]
Still need to test popup and timer skipping.

**Comment by uBlock-user** [comment]
`srt.am##script:inject(abort-on-property-read.js, RunAds)`
