### ISSUE TITLE
You are using an outdated Chromium / Chrome!

### ISSUE THREAD

**Issue by the1wolf** [jspenguin2017/uBlockProtector#739]
### Screenshot of the web page (including address bar and extension icons) (required): 

![ubp](https://user-images.githubusercontent.com/25043074/33565770-068235f2-d8ec-11e7-9ee0-5d9c8e598ab1.gif)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![ubp1](https://user-images.githubusercontent.com/25043074/33565952-9278da02-d8ec-11e7-97e5-7b393d244aaf.png)

### Add everything else that you believe to be useful below (optional): 

![ubp2](https://user-images.githubusercontent.com/25043074/33566469-13beef9c-d8ee-11e7-86fe-f9759c72ab01.png)

**Comment by jspenguin2017** [comment]
Yea, your Chrome is outdated, go update it.

**Comment by jspenguin2017** [comment]
I haven't made an official announcement, but Chrome 61 and below will be dropped due to some browser bugs.

**Comment by the1wolf** [comment]
Yea, your Chrome is outdated, go update it.

That's SOOOO funny!

**Comment by the1wolf** [comment]
Awesome, time to look for another product to use.  I was just trying to figure out why this stopped working, could have done without the sarcasm.

**Comment by uBlock-user** [comment]
If you're using clones of Chromium, this will happen, the maintainers don't update the core source with every update, use Chrome/Chromium instead and avoid clones.
