### ISSUE TITLE
tucson.com

### ISSUE THREAD

**Issue by jjohns71** [jspenguin2017/uBlockProtector#740]
http://tucson.com/news/state-and-regional/thousands-unfollow-sen-john-mccain-after-he-asks-for-more/article_c6548042-d94b-11e7-aef2-7fa7e36b0339.html

![capture](https://user-images.githubusercontent.com/6795795/33613090-aaf52684-d9a1-11e7-9b3e-ad86645946f7.PNG)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![capture2](https://user-images.githubusercontent.com/6795795/33613159-de8cb73c-d9a1-11e7-8d65-c2e3c555c8c4.PNG)

### Explain what was not right (optional if obvious): 

When viewing site on tucson.com, a filter in uBlock Protector List is causing the page to be loaded and then "eaten" with all DOM elements being overwritten by the site and nothing being displayed. Tested my filter lists and narrowed it down to a filter in uBlock Protector List because the site loads fine when the uBlock Protector List is not enabled.

### Reproduction steps (optional if trivial): 

1. Go to http://tucson.com/news/state-and-regional/thousands-unfollow-sen-john-mccain-after-he-asks-for-more/article_c6548042-d94b-11e7-aef2-7fa7e36b0339.html
2. Observe the site load and then within 1 second of page loading, observe the content being overwritten.

**Comment by jspenguin2017** [comment]
Just open an issue when stuff like this happen again, it's a trivial fix.

**Comment by uBlock-user** [comment]
It's Google funding choices.
