### ISSUE TITLE
[Announcement] v13 plan

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#741]
Here are the major changes for v13: 

 - [x] /Extension Compiler
 - [x] /docs
 - [x] Web Store (description, screenshots)

gorhill stated multiple time that uBO can protect itself, and I don't want to be in his way. But don't worry, this project will still work with uBO. Everything will stay the same, except that I'm starting a fork of uBO and this project now has another name.

**Comment by uBlock-user** [comment]
so it won't be uBlock Protector anymore ? Why, what changed ?

**Comment by jspenguin2017** [comment]
Actually, I'll **add** a new name, that's pretty much it.

**Comment by jspenguin2017** [comment]
Like always, it's just a plan, and plan can change significantly when it is being carried out.

**Comment by uBlock-user** [comment]
Yes but why add a new name ?

**Comment by jspenguin2017** [comment]
Because I'm starting a fork and I want my extension to look and feel like designed for my fork. Although it will work just fine with original uBO.

**Comment by uBlock-user** [comment]
so what will become of this extension ? Another uBO ?

**Comment by jspenguin2017** [comment]
No, still a companion extension. 

The fork is called Nano: https://github.com/NanoAdblocker/NanoCore
It's on Web Store but I'll keep it private for now, until I have added enough features to make the fork meaningful.

**Comment by uBlock-user** [comment]
uBlock Protector will become NanoCore and will be be like uBO is ?

**Comment by jspenguin2017** [comment]
No, Nano Stealth Engine, will stay the same.

**Comment by uBlock-user** [comment]
But will this extension still have content-script wrapped inside a extension ?

**Comment by jspenguin2017** [comment]
I don't get what you mean, all I will do here is a name change.

**Comment by uBlock-user** [comment]
Okay, got it. I thought you were changing the extension fundamentally.

**Comment by jspenguin2017** [comment]
I might move some optional rules onto (the upcoming) `Nano filters`, like the timewarp scriptlet, so Nano users can enjoy it without my approval.

**Comment by jspenguin2017** [comment]
I still haven't made up my mind, do I want Nano to be resistant to anti-adblock out of the box or do I want it just to be uBO with some tweaks and new scriptlets and features...

**Comment by jspenguin2017** [comment]
Not yet, I plan to make `setTimeout-booster.js`, `setInterval-booster.js`, and `define-readonly-property.js`.

**Comment by uBlock-user** [comment]
I would love to add them my uBO-Scriptlets repository. They are some nifty tools. Can't bypass the webstore check like you do with this extension ?

**Comment by jspenguin2017** [comment]
I think they still scan it, they just scan it right away instead of scanning it when they feel like it. Because they need to give back a reply to the API call quick. I think publishing from API call only skip the queue.

**Comment by jspenguin2017** [comment]
New console messages (more to update): 
![image](https://user-images.githubusercontent.com/7283682/33790714-c8d85ab8-dc3f-11e7-899e-32f3eef3f443.png)

**Comment by jspenguin2017** [comment]
Alright, I **think** I know how to have 2 assets files, I'll aim it for 1.0.2.0 release of Nano. It's kind of complicated I want to test it out properly.

**Comment by jspenguin2017** [comment]
@uBlock-user Want to be a beta tester? I have timer booster prototypes ready: 
https://github.com/NanoAdblocker/NanoFilters/blob/master/NanoFilters/NanoResources.txt

**Comment by uBlock-user** [comment]
yeah sure but how ?

**Comment by jspenguin2017** [comment]
Yes, but it's a bit complicated. Load this into advanced settings, then update everything: 
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt

Call it like usual: 
`example.com##script:inject(nano-setTimeout-booster.js-debugonly, ...)`
Same arguments as `setTimeout-defuser.js`

**Comment by uBlock-user** [comment]
Yeah I know all that stuff but where can we test it ? We need a domain where we can apply it and see it in action.

**Comment by jspenguin2017** [comment]
There was a bug in the resource file, should be fixed now. The tip-of-tree of Nano will load Nano's extra resources automatically, in addition to whatever is set in advanced settings. 

I have a new scriptlet to define read-only property, which is much easier to test: 
`example.com##script:inject(nano-define-readonly-property.js-debugonly, test, true)`

**Comment by uBlock-user** [comment]
Test-case - http://www.shortify.pw/brazzers

Disable the Extension and then add

```
shortify.pw##script:inject(nano-define-readonly-property.js, alert, true)
shortify.pw##script:inject(nano-setTimeout-booster.js)
```

Both are working, would you mind if I add these to my repo ?

**Comment by uBlock-user** [comment]
@jspenguin2017 Another thing, the console log messages appear twice for some reason, need to look into that

![](https://i.gyazo.com/a91e19651a65ffae53368373be6a205c.png)

Lastly, I need to know about parameters regarding these scriptlets so I know what to pass as the values when applying them.

**Comment by jspenguin2017** [comment]
Maybe there is an iframe?

**Comment by jspenguin2017** [comment]
No, only one log in `example.com`. 
The log is just temporary, they will eventually be logged in Nano Logger.

**Comment by uBlock-user** [comment]
I meant on `shortify.pw`, try there and see for yourself.

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/33808271-bd9ab3b4-dda0-11e7-9d74-7fe250b327f9.png)

**Comment by jspenguin2017** [comment]
The link you supplied definitely has iframes. 
![image](https://user-images.githubusercontent.com/7283682/33808284-e6bf3e54-dda0-11e7-8769-df2d3c33756c.png)

**Comment by uBlock-user** [comment]
Were you able to determine from which URLs the iframes were coming ?

**Comment by jspenguin2017** [comment]
It'll be logged in Nano Logger, I plan on implementing it soon. For now, you can use `nano-debug-hook.js`.

**Comment by uBlock-user** [comment]
Can you also add a scriptlet for getting and setting cookies ? That will also be another weapon for uBO users.

**Comment by jspenguin2017** [comment]
I need to think about that, because it can potentially be abusable. 
You can just make one yourself, it's trivial: `document.cookie = '{{1}}';`

**Comment by uBlock-user** [comment]
That's it ? What are the params ?

**Comment by jspenguin2017** [comment]
I'm worried that some website might save trusted data in cookies, allow inserting arbitrary value into them can potentially open security holes. That's also why `nano-define-readonly-property.js` only allow a few preset values that are considered safe.

**Comment by jspenguin2017** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

**Comment by jspenguin2017** [comment]
For further feature request, open issue in Nano's repo: https://github.com/NanoAdblocker/NanoCore/issues
