### ISSUE TITLE
egarwolin.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#742]
### Test link (required): 
egarwolin.pl

### Screenshot of the console (press `F12` to bring up the console) (required): 
![capture](https://user-images.githubusercontent.com/15007183/33687791-414bf422-daa7-11e7-9fdf-0e1ceb818425.PNG)

**Comment by jspenguin2017** [comment]
Not worth it. It's just a bait file, pseudo selectors are extremely heavy.
