### ISSUE TITLE
freecoursesonline.us

### ISSUE THREAD

**Issue by dmaglio** [jspenguin2017/uBlockProtector#743]
### Test link (required): 
https://www.freecoursesonline.us/linkedin-kotlin-java-developers/

### Screenshot of the web page (including address bar and extension icons) (required): 
![2017-12-07-153838_3360x1080_scrot](https://user-images.githubusercontent.com/446573/33720640-d2f66ef8-db64-11e7-826d-e028a08768fb.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
[www.freecoursesonline.us-1512657642057.log](https://github.com/jspenguin2017/uBlockProtector/files/1539470/www.freecoursesonline.us-1512657642057.log)

**Comment by uBlock-user** [comment]
Can't reproduce.
