### ISSUE TITLE
blockergame.com

### ISSUE THREAD

**Issue by ExtendLord** [jspenguin2017/uBlockProtector#744]
### Test link (required): 

The link: https://blockergame.com/

### Screenshot of the web page (including address bar and extension icons) (required): 

Screenshot of the web page: https://i.imgur.com/CDimVoh.png

### Screenshot of the console (press `F12` to bring up the console) (required): 

Screenshot of the console: https://i.imgur.com/4EGoy4T.png

Fix this please

**Comment by uBlock-user** [comment]
Massive CPU hogger, crashes Chromium too after prolonger use.

PS - It's blocking context menu fyi

**Comment by jspenguin2017** [comment]
A lot of games do that, it's proper use of context menu event.

**Comment by uBlock-user** [comment]
No they don't, no game takes away 70% of your CPU resource. GTA 5 itself doesn't do that. This is a browser game, so obviously not!
