### ISSUE TITLE
blockersurvive.com

### ISSUE THREAD

**Issue by ExtendLord** [jspenguin2017/uBlockProtector#745]
### Test link (required): 
https://blockersurvive.com/

### Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/jmx4p2L.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/jmx4p2L.png

### Add everything else that you believe to be useful below (optional): 
The game blockergame.com was added to the list but they have another game blockersurvive.com which can bypass ublock protector.

**Comment by uBlock-user** [comment]
Can't reproduce.

Same as #744 

Another CPU hogger, avoid if you can.

**Comment by jspenguin2017** [comment]
Well, it's a 3D game, so it's going to use some resources.

**Comment by uBlock-user** [comment]
Badly configured game, It takes away 70% of my CPU, what game does that ? This is going straight to resource-abuse list!

**Comment by jspenguin2017** [comment]
I don't know man, all the games I played use 100% of CPU when active.

**Comment by uBlock-user** [comment]
I used to play Flash games, even they never took 70% of my CPU and this is also before I begin playing. This one literally latches as soon as the page loads.

**Comment by jspenguin2017** [comment]
I don't know what kind of CPU you got but it doesn't do that on my end. 
![image](https://user-images.githubusercontent.com/7283682/33797309-df6e0bf0-dcc2-11e7-9834-96429e43f7a5.png)

**Comment by ExtendLord** [comment]
@jspenguin2017  The game is still blocked, updated the list in ublock origin, checked inside the filter to make sure it is updated, came back to the game, still blocked.
@uBlock-user Well the game works pretty well on my PC, the problem is that browsers has a bad optimization.

**Comment by ExtendLord** [comment]
@jspenguin2017 Nevermind, it does work.

**Comment by uBlock-user** [comment]
@ExtendLord Nothing to do with the browsers, I'm on Chromium, it's already light weight than it's companion fork Chrome and already configured to block most of the things. Good for you if it doesn't happen to you.
