### ISSUE TITLE
squadd.io

### ISSUE THREAD

**Issue by ExtendLord** [jspenguin2017/uBlockProtector#746]
### Test link (required): 
http://squadd.io/

### Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/hiH0uVc.jpg
https://i.imgur.com/G2zAsaf.jpg
https://i.imgur.com/tFrXlhc.jpg
https://i.imgur.com/sxcfUAy.jpg
https://i.imgur.com/tkpF3IK.jpg
Just check one link and F12 by yourself(Huge amount of lines).

### Explain what was not right (optional if obvious): 
It requires me to disable adblock to unlock characters lol.

### Reproduction steps (optional if trivial): 
1. Go to the game and wait till it will load.
2. Click on Heroes(There is a character underneath it and its name is "Brambo").

**Comment by uBlock-user** [comment]
Takes wayy too much time to load!!

**Comment by ExtendLord** [comment]
@uBlock-user Upgrade your PC

**Comment by jspenguin2017** [comment]
It loads in like 5 sec for me.

**Comment by uBlock-user** [comment]
@ExtendLord No thanks, I'm on core i5 laptop with the 5th Gen processor, The Unity3D takes shitload of time to load on Chromium.

**Comment by jspenguin2017** [comment]
OK, you two got to stop fighting.
