### ISSUE TITLE
spanishdict.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#748]
### Test link (required): 
http://www.spanishdict.com/translate/hay%20alguien%20que%20hable%20ingl%C3%A9s%3F

### Screenshot of the web page (including address bar and extension icons) (required): 
![capture](https://user-images.githubusercontent.com/15007183/33804972-a9143c0c-dd7e-11e7-9271-c2a721df3964.PNG)

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by SkeletalDemise** [comment]
I also cannot reproduce that.

**Comment by jspenguin2017** [comment]
Can't reproduce neither.

**Comment by xxcriticxx** [comment]
no problem boys
