### ISSUE TITLE
majorgeeks.com 

### ISSUE THREAD

**Issue by karserasl** [jspenguin2017/uBlockProtector#749]
### Test link (required): 
http://www.majorgeeks.com

### Screenshot of the web page (including address bar and extension icons) (required):

![image](https://user-images.githubusercontent.com/14327196/33805378-d0175f1a-ddaf-11e7-8aae-e8acd4675468.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![image](https://user-images.githubusercontent.com/14327196/33805391-ffe96fa8-ddaf-11e7-9407-44fc438a205f.png)

### Explain what was not right (optional if obvious): 
Seems like it doesnt stop majorgeeks from detecting the adblock. Shows only when you click to download something.

**Comment by ExtendLord** [comment]
Can't reproduce it, shows nothing under tips

**Comment by karserasl** [comment]
well i have disable all extensions except, Nano defender and adblocker. 

I have activated all the correct filters. 

Still getting that.

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by karserasl** [comment]
Ok.. I found the problem.. Seems like a list that i subscribed was the problem. 

I put some extra filter lists.
