### ISSUE TITLE
linkatk.net

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#751]
### Test link (required): 
http://linkatk.net/i5n3Dn7

### Screenshot of the web page (including address bar and extension icons) (required): 
![linktk4](https://user-images.githubusercontent.com/2828165/33819926-94b7521c-de55-11e7-902c-6340146bccad.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![linktk42](https://user-images.githubusercontent.com/2828165/33819939-a2793fdc-de55-11e7-8ef0-c39f12fe0769.png)

**Comment by uBlock-user** [comment]
clone of #183
