### ISSUE TITLE
wolframclient.net

### ISSUE THREAD

**Issue by JourneyOver** [jspenguin2017/uBlockProtector#752]
### Test link (required): 
https://www.wolframclient.net/updates/wolfram-9-5/

### Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/ZASWEaz.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/HTIxPcC.png

**Comment by jspenguin2017** [comment]
Well, just as I thought `nano-remove-element-onready.js` is useless...

**Comment by uBlock-user** [comment]
Why ? Does uBO already have an equivalent for it ?

**Comment by uBlock-user** [comment]
For some reason I wasn't able to reproduce previously when reported, now I can. They must have changed something.

**Comment by jspenguin2017** [comment]
No, but uBO can hide elements, which is enough in most case, I wasn't able to think of any case where removing element can be handy, but now I do.

**Comment by uBlock-user** [comment]
Could it be handy at https://playview.io/ ?

**Comment by jspenguin2017** [comment]
Not sure, what's the problem with that website?

**Comment by uBlock-user** [comment]
Unless you whitelist `showads.js`you get anti adblock wall.

This is the script

```javascript
$(document).ready(function(){function adBlockDetected(){$('#allcontent').remove();$("#showaviso").show();}
function adBlockNotDetected(){$("#showaviso").remove();}
if($('#showaviso').length==1){$.ajax('themes/pv/js/showads.js').fail(function(d){if(d.status===0||d.statusText=='error'){adBlockDetected();$("body").html('<div id="showaviso" class="container"><div class="row" style="padding:50px;"><div class="jumbotron text-center"><img src="media/adblock.png" class="imb-responsive center-block"/><br>Hemos detectado que tienes AdBlock y estÃ¡ habilitado para nuestro sitio lamentablemente nos mantenemos de la publicidad que hay aquÃ­ y si evitas la publicidad no generamos ganancias para poder seguir online, por favor desactiva AdBlock para nuestro sitio y actualiza nuevamente para visualizar el contenido</div></div></div>');}});if(typeof fuckAdBlock==='undefined'){adBlockDetected();}else{fuckAdBlock.setOption({debug:false});fuckAdBlock.onDetected(adBlockDetected).onNotDetected(adBlockNotDetected);}}
function checkAgain(){$('#fuck-adb-enabled').hide();$('#fuck-adb-not-enabled').hide();setTimeout(function(){if(typeof fuckAdBlock==='undefined'){adBlockDetected();}else{fuckAdBlock.onDetected(adBlockDetected).onNotDetected(adBlockNotDetected);fuckAdBlock.check();}},300);}
```

Nooping the XHR doesn't even work.

**Comment by uBlock-user** [comment]
Can you suggest a filter for it ? Whitelisting is the last thing I want to do.

**Comment by jspenguin2017** [comment]
Nah, you are on your own then. They can very well name their ads serving script `index.js`.

**Comment by uBlock-user** [comment]
It's not about naming, it's about fixing it when we have a variety of tools here. I couldn't care less about their names for the bait.

**Comment by jspenguin2017** [comment]
Yea, you can try to nuke that element, yes. 
Don't be restricted by tools that Nano has, you can make your own.

**Comment by uBlock-user** [comment]
nuke how, I tried `nano-remove-element-onready.js`, didn't work

**Comment by jspenguin2017** [comment]
Be creative, if removing doesn't work why not try to add another one? 
Either way, I have well documented Nano's snippets, it's up to you to read and understand the documentation.
