### ISSUE TITLE
Yandex browser is't be supported?

### ISSUE THREAD

**Issue by mat41997** [jspenguin2017/uBlockProtector#753]
![screenshot_2017-12-11-23-07-39](https://user-images.githubusercontent.com/5884000/33856605-ef087f02-dec8-11e7-97ad-09dfe115ac1a.png)
https://github.com/NanoAdblocker/NanoCore/issues/16

**Comment by jspenguin2017** [comment]
What the heck? Does uBlock Origin works?

**Comment by jspenguin2017** [comment]
Paste your UA string?

**Comment by jspenguin2017** [comment]
Nano Defender is written in a newer language than Nano Adblocker, so unfortunately I can't easily make it compatible. 
In the long run, the majority of Nano Defender will be dissolved into Nano Filters, so it'll get better.

**Comment by mat41997** [comment]
My ua from
`http://www.whatsmyua.info/`

```
Mozilla/5.0 (Linux; Android 5.0.2; A0001 Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 YaBrowser/17.10.2.145.00 Mobile Safari/537.36
```

**Comment by jspenguin2017** [comment]
Huh, should work. Can you install uBO from Google's store?

**Comment by mat41997** [comment]
@jspenguin2017 no, don't workt
only i can install from the github repo

**Comment by jspenguin2017** [comment]
Well, that's out of my control, use a CRX downloader to grab the binary off Web Store.
