### ISSUE TITLE
onlinemschool.com

### ISSUE THREAD

**Issue by 3dsboy08** [jspenguin2017/uBlockProtector#755]
### Test link (required): 
http://onlinemschool.com/math/assistance/fraction/transform/

### Screenshot of the web page (including address bar and extension icons) (required): 

![image](https://user-images.githubusercontent.com/14914815/33914180-02f8e6bc-df6b-11e7-8ca2-02c2d509aa42.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![image](https://user-images.githubusercontent.com/14914815/33914191-11e2f758-df6b-11e7-81d1-fba3892fb273.png)

### Explain what was not right (optional if obvious): 
Anti-Adblock Script, hides equation steps.

### Reproduction steps (optional if trivial): 
1) Go to link specified.
2) Put in any random problem (26/13 for example)
3) Press the '=' button
4) See 30 second timer below and anti-adblock warning.

**Comment by uBlock-user** [comment]
`onlinemschool.com###oms_res_block`

**Comment by jspenguin2017** [comment]
@uBlock-user That doesn't show the steps.

**Comment by uBlock-user** [comment]
which steps ?

**Comment by uBlock-user** [comment]
There's an ad leftout which needs to be blocked - `onlinemschool.com###oms_left_block`

**Comment by jspenguin2017** [comment]
Good catch
