### ISSUE TITLE
data-raid-recovery-link.com

### ISSUE THREAD

**Issue by Od1sseas** [jspenguin2017/uBlockProtector#756]
Disable AdBlock Warning

Chrome+Nano AdBlocker+Nano Defender

https://i.imgur.com/dDkGmgT.png

Link:
https://data-raid-recovery-link.com/2017/10/data-raid-2460.html

**Comment by uBlock-user** [comment]
`end-of-adblock-cycle$script,domain=data-raid-recovery-link.com`
