### ISSUE TITLE
investing.com

### ISSUE THREAD

**Issue by stwg34** [jspenguin2017/uBlockProtector#757]
### Screenshot of the web page (including address bar and extension icons) (required): 
![2017-12-13_15 06 57](https://user-images.githubusercontent.com/34512882/33944120-75fa99b6-e01b-11e7-8b32-c957545fc9ed.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2017-12-13_15 33 07](https://user-images.githubusercontent.com/34512882/33944099-5e521d16-e01b-11e7-9ade-bc81c98a9f96.png)

**Comment by jspenguin2017** [comment]
Can't reproduce, can you try to restart your browser and clear cache for that site?

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by stwg34** [comment]
Indeed, after clearing my browser cache and restarting it, the issue is solved. 
I should have thought of that, sorry .
