### ISSUE TITLE
bikeradar.com

### ISSUE THREAD

**Issue by kwaaak** [jspenguin2017/uBlockProtector#759]
### Test link (required): 
http://www.bikeradar.com/

### Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/T4Q378s.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/NKyRwQA.png

**Comment by uBlock-user** [comment]
Can't reproduce.
