### ISSUE TITLE
zdnet.fr

### ISSUE THREAD

**Issue by Tirage** [jspenguin2017/uBlockProtector#760]
### Test link (required): 
http://www.zdnet.fr/actualites/neutralite-du-net-aux-us-la-contestation-se-poursuit-malgre-le-vote-de-la-fcc-39861650.htm

### Screenshot of the web page (including address bar and extension icons) (required): 

https://imgur.com/a/F8zqh

### Screenshot of the console (press `F12` to bring up the console) (required): 

https://imgur.com/a/F8zqh

### Reproduction steps (optional if trivial): 
after looking 4 articles

### Add everything else that you believe to be useful below (optional): 
Version 62.0.3202.94 (Build officiel) Built on Ubuntu , running on Ubuntu 16.04 (64 bits)

**Comment by Tirage** [comment]
https://forums.lanik.us/viewtopic.php?f=91&t=39341

**Comment by jspenguin2017** [comment]
@mapx-

**Comment by uBlock-user** [comment]
Can't reproduce.

**Comment by Tirage** [comment]
it's broken

**Comment by jspenguin2017** [comment]
Still works for me.

**Comment by Tirage** [comment]
After reading more 4 articles ?

**Comment by jspenguin2017** [comment]
Fixed.

**Comment by Tirage** [comment]
Broken again after 4 articles

**Comment by jspenguin2017** [comment]
@mapx- Might need to block all third party connections except those that are required, it's pretty clear they are changing domain every other day.
