### ISSUE TITLE
developpez.com

### ISSUE THREAD

**Issue by Tirage** [jspenguin2017/uBlockProtector#761]
### Test link (required): 
https://www.developpez.com/

### Screenshot of the web page (including address bar and extension icons) (required): 

https://imgur.com/a/lgt4o

### Screenshot of the console (press `F12` to bring up the console) (required): 

https://imgur.com/a/lgt4o

### Add everything else that you believe to be useful below (optional): 

Version 62.0.3202.94 (Build officiel) Built on Ubuntu , running on Ubuntu 16.04 (64 bits)

**Comment by uBlock-user** [comment]
Can't reproduce.
