### ISSUE TITLE
map.poketrack.xyz

### ISSUE THREAD

**Issue by SamuBox** [jspenguin2017/uBlockProtector#762]
### Test link (required): 

https://map.poketrack.xyz/

### Screenshot of the web page (including address bar and extension icons) (required): 

![1](https://user-images.githubusercontent.com/30962122/34071998-e8cecd84-e27f-11e7-8349-01de29ffb667.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![2](https://user-images.githubusercontent.com/30962122/34072001-f49679e6-e27f-11e7-9a87-34b6efc60ca3.png)

**Comment by jspenguin2017** [comment]
@mapx-

**Comment by ghajini** [comment]
Off topic, I don't need to use ublock protector if every solution goes into ublock origin filters....Is it end of ublock protector?

**Comment by jspenguin2017** [comment]
No, it will never go away as some solution are not implementable in filter. 
And there are thoughsands of solutions here and it's hard to move.

**Comment by jspenguin2017** [comment]
Apparently they named their `index.js` to be `ads-min.js`. Closing...

**Comment by uBlock-user** [comment]
`abd.js$script,domain=poketrack.xyz`

That kills the anti adblock check

**Comment by jspenguin2017** [comment]
Unless you actually have something functional, can you not post them?

**Comment by jspenguin2017** [comment]
If we have already reached a solution, you don't have to comment.

**Comment by uBlock-user** [comment]
Your solution doesn't include blocking that script in particular, does it ?

**Comment by jspenguin2017** [comment]
You missed the line above: `@@||map.poketrack.xyz/js/ads-min.js$script`

**Comment by uBlock-user** [comment]
I didn't miss it at all. I chose not to address it as that is required either way. They're sabotaging their website.

**Comment by jspenguin2017** [comment]
There is no point in doing that, as all it does is to test whether the main script is loaded. 
We have not missed it, it is just not necessary to block that. Unless you can actually unbreak the website, don't post unrelated filters. 
You and your no whitelist mindset is getting annoying.

**Comment by uBlock-user** [comment]
This has nothing to do with no whitelist mindset at all. I actually did whitelist on my end. Please don't post irrelevant excuses here, the cosmetic filters are not helping and if there's a script here that needs to be blocked, then it should be blocked instead of adding cosmetic filters.

**Comment by jspenguin2017** [comment]
What tells you the cosmetic filter is for hiding the block screen? It is there to deal with left-over ads placeholders.

**Comment by jspenguin2017** [comment]
You need to do your research before posting, for the last time, I am not here to educate you how the web works.

**Comment by SamuBox** [comment]
works great, thanks!
