### ISSUE TITLE
linkkawy.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#763]
### Test link (required): 

http://linkkawy.com/kG8p

### Screenshot of the web page (including address bar and extension icons) (required): 
![2017-12-17_232828](https://user-images.githubusercontent.com/2828165/34084001-1e011ee6-e382-11e7-801f-3fd08c86b957.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2017-12-17_232902](https://user-images.githubusercontent.com/2828165/34084007-26725978-e382-11e7-91c2-97c1970120ce.png)

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
`linkkawy.com` was part of my ["quest"](https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt#L2646) and the fix still works on my end.

**Comment by jspenguin2017** [comment]
I thought I updated my filters, apparently not... Sry false alert...
