### ISSUE TITLE
money.pl

### ISSUE THREAD

**Issue by HateAds** [jspenguin2017/uBlockProtector#764]
https://www.money.pl/gospodarka/wiadomosci/artykul/kodeks-pracy-for-analiza,163,0,2394019.html
On this website getting double player or ghost player effect ( the same problem is on sportowefakty.wp.pl #571 )
Screenshot of the web page
![image](https://user-images.githubusercontent.com/29756590/34107814-e6ed15e6-e3fd-11e7-9147-8f1e2057db72.png)
Screenshot of the console
![image](https://user-images.githubusercontent.com/29756590/34107945-6544e1b2-e3fe-11e7-9b35-8b7dd926118a.png)
![image](https://user-images.githubusercontent.com/29756590/34107970-7b17f2d6-e3fe-11e7-820a-7d04e1d73335.png)

**Comment by jspenguin2017** [comment]
Not my problem, their website is bugged. 
![image](https://user-images.githubusercontent.com/7283682/34116875-154656ea-e3d7-11e7-808d-857dbaf64fed.png)
