### ISSUE TITLE
filecrypt.cc

### ISSUE THREAD

**Issue by EmersonTR** [jspenguin2017/uBlockProtector#766]
### Browser: Vivaldi Snapshot 1.14.1042.3 (64 bits)

**Comment by jspenguin2017** [comment]
It's a mining wall.

**Comment by jspenguin2017** [comment]
Actually, I'll mark this as duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/624

**Comment by jspenguin2017** [comment]
Duplicate of #624

**Comment by jspenguin2017** [comment]
Actually, the mining doesn't start automatically, so I'll put an exception.
