### ISSUE TITLE
There is a 'Nano Defender' on AMO. Is it official?

### ISSUE THREAD

**Issue by FatOrangutan** [jspenguin2017/uBlockProtector#767]
https://addons.mozilla.org/en-US/firefox/addon/nano-defender/

It isn't linked on https://jspenguin2017.github.io/uBlockProtector/ and doesn't use your Github name so wondering if it's you who uploaded this. Might want to 'Report Abuse' otherwise.

**Comment by Salin1810** [comment]
I tried install this addon, so it's working, but i think it's not offcial

**Comment by jspenguin2017** [comment]
It is not official, do you know how to extract the package? If he didn't add malware in it we can wait until I'm ready to publish the official version to ask Mozilla to pull that down.

**Comment by jspenguin2017** [comment]
OK, I checked the extension, doesn't seem to be malware. Looks like he grab the binary off Chrome web store and uploaded to Firefox extension store unchanged.

**Comment by Francois-dag** [comment]
I'm a bit confused with Nano Defender and aak-cont. Well, I guess you are the developper of aak-cont that reach the idea that aak-cont is not the best way to do the job, sorry if not.
If so, could you please be just a bit more clear about your goals (i.e. tell for what reasons aak-cont is dead, availability for firefox, ...)

Cheers.

**Comment by LukePoke** [comment]
ah and me that I had installed ...

**Comment by jspenguin2017** [comment]
I don't want to maintain AAK-Cont because Userscript managers are changing every other day and they are extremely unreliable. Also no one wants to help me, hundreds of issues are stacking up, it's dead a long time ago. 

I don't use Firefox for now so making it available on Firefox is on the bottom of my todo list, I will probably eventually do that, but that's for the future.

**Comment by Francois-dag** [comment]
I've also installed the fake extension, was working well !
Waiting for your official for firefox (back to aak-cont by now).
Sounds so strange to me to try to get rid of ads with  the google browser !
Cheers.

**Comment by jspenguin2017** [comment]
I made a official build, make sure to not download the fake version. 
https://addons.mozilla.org/en-US/firefox/addon/real-nano-defender/
