### ISSUE TITLE
seriehd.me

### ISSUE THREAD

**Issue by LukePoke** [jspenguin2017/uBlockProtector#768]
http://www.seriehd.me/agents-of-shield-streaming/ (for each video this is just an example)

Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/inVPq8N.png

Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/fCvbqWd.png

Add everything else that you believe to be useful below (optional):
Using Firefox Version 57.0.2 (Official Build) (64-bit)
Ublock Origin Version 1.14.22
The player flashes, only if you disable Nano Defender the player works.

**Comment by LukePoke** [comment]
It does not work I click on the x and the black screen remains.

**Comment by jspenguin2017** [comment]
It definitely works on Chrome.

**Comment by LukePoke** [comment]
It's true! on chrome it works. Too bad that I use Firefox, step to Chrome.

**Comment by jspenguin2017** [comment]
The Firefox version isn't under my control, so you should ask whoever uploaded that to fix it.

**Comment by LukePoke** [comment]
No problem I switched to Chrome.

**Comment by LukePoke** [comment]
I have a similar problem with another site. Can I write it here?

**Comment by jspenguin2017** [comment]
If it's related then yes, otherwise you should open a new issue.

**Comment by LukePoke** [comment]
Ok i opened a new issue.

**Comment by LukePoke** [comment]
It does not work anymore.

**Comment by jspenguin2017** [comment]
Still works for me.

**Comment by LukePoke** [comment]
Look here: https://i.imgur.com/VQ0wuFW.png

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/35250555-6281553a-ff94-11e7-826a-7978b1f540da.png)

**Comment by LukePoke** [comment]
Strange ... what can you depend on?

**Comment by LukePoke** [comment]
I solved! I put Nano Adblocker on and it works.

**Comment by jspenguin2017** [comment]
That's weird, you probably didn't install the integration filters properly in uBO.

**Comment by LukePoke** [comment]
Before he went. However I keep your extension.

**Comment by LukePoke** [comment]
I'm sorry again, but I do not understand why sometimes it does not work. Both with Ublock and with Nano Adbocker. The console gives this writing: [Nano] Specific Solution Triggered.

**Comment by jspenguin2017** [comment]
Tried 5 times, worked every single time.

**Comment by LukePoke** [comment]
Could you please tell me what filters did you activate?

**Comment by jspenguin2017** [comment]
Nano's default plus the integration: 
![image](https://user-images.githubusercontent.com/7283682/35539273-1fe558f0-050e-11e8-8421-fbf5605d274d.png)

**Comment by LukePoke** [comment]
Nothing to do is wrong. I give up...

**Comment by LukePoke** [comment]
Permanently solved! it was the english filter...
