### ISSUE TITLE
ilgeniodellostreaming.org, blastingnews.com

### ISSUE THREAD

**Issue by LukePoke** [jspenguin2017/uBlockProtector#769]
Test link (required): 
http://ilgeniodellostreaming.org/episodi/homeland-caccia-alla-spia-1x4-r7/

Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/tL4B8Mv.png

Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/oWOgayc.png

Add everything else that you believe to be useful below (optional): 
Using Chrome Version 63.0.3239.108 (Official Build) (64-bit)
Ublock Origin Version 1.14.22

I can not open the player is covered by a transparent black screen, if disabled Ublock the problem is solved.

**Comment by LukePoke** [comment]
Thanks so much!! and sorry for disturbing.

**Comment by LukePoke** [comment]
Ah, black security remains the same.

**Comment by jspenguin2017** [comment]
Make sure to update Nano filters.

**Comment by LukePoke** [comment]
Yes and I can not click on the play button.
https://i.imgur.com/48eJuU4.png

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/34222068-84776d78-e577-11e7-8934-ac354aa66ee1.png)
![image](https://user-images.githubusercontent.com/7283682/34222088-97fd632a-e577-11e7-9aee-735943ba09d0.png)

**Comment by LukePoke** [comment]
Ok now it works, thanks a lot !!

**Comment by LukePoke** [comment]
same thing on this site: http://it.blastingnews.com/tv-gossip/2017/12/gossip-due-ex-del-grande-fratello-vip-in-coppia-allisola-dei-famosi-002245053. html

the player is locked with ublock active.

**Comment by jspenguin2017** [comment]
I opened an issue in uAssets for the first link, image viewer works on my end for the second link.

**Comment by LukePoke** [comment]
Thanks so much! I like to contribute.

**Comment by jspenguin2017** [comment]
That's weird, I see it on Chrome: 
![image](https://user-images.githubusercontent.com/7283682/34302615-eb3e8af0-e6ee-11e7-9461-ded0c6986a4a.png)

**Comment by LukePoke** [comment]
Now I see it too.
