### ISSUE TITLE
debridnet.com

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#77]
https://github.com/reek/anti-adblock-killer/issues/2906

Test link: http://debridnet.com/

**Comment by uBlock-user** [comment]
It checks whether a random element height is less than 1 and if that turns out true, it does a redirect.

````
$(window).load(function(){
//   if ($('.np93RYwqM7rv').height() < 1) {
//   window.location.replace('http://debridnet.com/ad-blocker');
//   document.getElementById('7pAoKOn69MQa').id = '';
//  } else {document.getElementById('7pAoKOn69MQa').disabled = false;}
//   if ($('.ShgWNud7cqO0').height() < 1) {
//   window.location.replace('http://debridnet.com/ad-blocker');
//   document.getElementById('7pAoKOn69MQa').id = '';
//  } else {document.getElementById('7pAoKOn69MQa').disabled = false;}
  if ($('.gi9kmHenFGt1').height() < 1) {
  window.location.replace('http://debridnet.com/ad-blocker');
  document.getElementById('7pAoKOn69MQa').id = '';
 } else {document.getElementById('7pAoKOn69MQa').disabled = false;}
//   if ($('.0r27CtZvQlqY').height() < 1) {
//   window.location.replace('http://debridnet.com/ad-blocker');
//   document.getElementById('7pAoKOn69MQa').id = '';
//   } else {document.getElementById('7pAoKOn69MQa').disabled = false;}
})
if ($('#zenvpn-spooks-js').length > 0) window.location.replace('http://debridnet.com/ad-blocker1');
if ($('#javascript-popup-blocker-notify').length > 0) window.location.replace('http://debridnet.com/ad-blocker1');
if (typeof inject == 'function') window.location.replace('http://debridnet.com/ad-blocker1');
if(parent.frames.length > 0) top.location.href = self.location;
$(window).load(function(){
$('#BotBootInput').on('change keyup', function() {
  var sanitized = $(this).val().replace(/[^0-9]/g, '');
  $(this).val(sanitized);
});
});
````

**Comment by uBlock-user** [comment]
add
````
||debridnet.com/stat*^$subdocument,domain=debridnet.com
||amazon-adsystem.com^$subdocument,redirect=noopframe,domain=debridnet.com
````

**Comment by X01X012013** [comment]
Thanks, I added it to the List.

**Comment by X01X012013** [comment]
I also added `a.noAccess("_pop");` to block popunder.

**Comment by lain566** [comment]
@jspenguin2017 It's broken, I can't download, START button not working

<details><summary>Test links</summary>

http://uploaded.net/file/9aww4dzv/AQ46U769Q3.part01.rar http://uploaded.net/file/mfppxq7x/AQ46U769Q3.part02.rar http://uploaded.net/file/ifb1mrjl/AQ46U769Q3.part03.rar http://uploaded.net/file/nepl2bku/AQ46U769Q3.part04.rar http://uploaded.net/file/vybxeon4/AQ46U769Q3.part06.rar http://uploaded.net/file/om1vz5ri/AQ46U769Q3.part07.rar http://uploaded.net/file/4jaa1zw2/AQ46U769Q3.part08.rar http://uploaded.net/file/6x63jqi3/AQ46U769Q3.part09.rar http://uploaded.net/file/j5sz9uhg/AQ46U769Q3.part10.rar
</details>

**Comment by jspenguin2017** [comment]
Works for me... 
![image](https://user-images.githubusercontent.com/7283682/28502561-42013d7e-6fb2-11e7-9822-64c28eeb57ef.png)

**Comment by lain566** [comment]
@jspenguin2017 You have to use the page to generate a link and download as a premium user

http://debridnet.com/
![debridnet com_-_premium_link_generator_-_google_ch_2017-07-23_22-29-40](https://user-images.githubusercontent.com/27441315/28502789-6600f3e8-6ffa-11e7-997c-9bd55f61501e.png)

**Comment by jspenguin2017** [comment]
OK, I see.

**Comment by jspenguin2017** [comment]
It randomizes pretty much everything each page load...

**Comment by jspenguin2017** [comment]
This does fix it. But I think there is something wrong about the domlib, somehow doesn't work through domlib.

**Comment by jspenguin2017** [comment]
Hum... Looks like querySelectorAll gives read-only array...

**Comment by jspenguin2017** [comment]
I'm surprised that the broken domlib didn't create problems earlier. Anyway, it's now fixed...

**Comment by lain566** [comment]
@jspenguin2017 Every time I get this log on the console, Start button not working for me
It just happens sometimes.

![developer_tools_-_httpdebridnet com_2017-07-24_00-38-01](https://user-images.githubusercontent.com/27441315/28503515-f1c9f3ee-7008-11e7-88b9-4993e1870a27.png)

**Comment by jspenguin2017** [comment]
They randomize their function name, but forgot that a function name can't start with a number, so it sometimes crashes.

**Comment by lain566** [comment]
@jspenguin2017 Ahh ... Ok, then issue solved

**Comment by ghajini** [comment]
if `linkshrink` was to be bypassed,then it may have relief for those 6 steps

**Comment by jspenguin2017** [comment]
Test link: http://linkshrink.net/9dxqz

**Comment by jspenguin2017** [comment]
Huh, it is somehow bypassable.

**Comment by jspenguin2017** [comment]
But the link generation is still not quite working, it's due to bugs in the website, it won't be working with uBO off.

**Comment by lain566** [comment]
It's broken, wait bar is looping

**Comment by jspenguin2017** [comment]
Fixed.
