### ISSUE TITLE
calciomercato.it

### ISSUE THREAD

**Issue by BadExcuse** [jspenguin2017/uBlockProtector#770]
Link https://www.calciomercato.it/news/289342/calciomercato_inter_concorrenza_spagnola_per_musonda
Screenshot of the web page (required):
https://i.imgur.com/HJc85J6.png
Screenshot of the console (press F12 to bring up the console) (required):
https://i.imgur.com/voCzZMQ.png

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/ac6f0b674f2c1118ccad20cb51cbfed4ce1360fa

**Comment by BadExcuse** [comment]
Thanks guys

**Comment by BadExcuse** [comment]
Tried again with the fix but doesn't works
