### ISSUE TITLE
rue89lyon.fr

### ISSUE THREAD

**Issue by Tirage** [jspenguin2017/uBlockProtector#771]
### Test link (required): 
http://www.rue89lyon.fr/2017/12/20/transformation-de-la6-a7-la-metropole-de-lyon-est-sur-la-bonne-voie/

### Screenshot of the web page (including address bar and extension icons) (required): 

https://imgur.com/a/lZGs8

### Screenshot of the console (press `F12` to bring up the console) (required): 

https://imgur.com/a/lZGs8

### Add everything else that you believe to be useful below (optional): 
Chromium Version 63.0.3239.84 (Build officiel) Built on Ubuntu , running on Ubuntu 14.04 (64 bits)

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
