### ISSUE TITLE
receive-sms-online.info

### ISSUE THREAD

**Issue by Salin1810** [jspenguin2017/uBlockProtector#773]
### Test link (required): 
https://www.receive-sms-online.info/read-sms.php?phone=447397081339

### Screenshot of the web page (including address bar and extension icons) (required): 

https://i.imgur.com/4cS3A4O.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/CQYBR7z.png

### Environment (Required)

- Operating System and Version: Windows 7 Ultimate x64 build 7601 SP1
- Browser and Version:  Firefox 57.0.2
- Nano Adblocker Version: 1.0.0.20
- Nano Defender Version: 13.15

**Comment by jspenguin2017** [comment]
Eh... this is back again?

**Comment by jspenguin2017** [comment]
It seems to work for me, can you test if another extension is interfering? 
![image](https://user-images.githubusercontent.com/7283682/34328760-e81210ce-e8a4-11e7-8503-f71ef9fb2cf4.png)

**Comment by Salin1810** [comment]
If I reset my profile firefox to default, it seem to work. So I will fix that problem by myself, thanks for your help
https://i.imgur.com/5WQAuv0l.png
