### ISSUE TITLE
bombuj.eu

### ISSUE THREAD

**Issue by MajkiIT** [jspenguin2017/uBlockProtector#775]
### Test link (required): 
http://www.bombuj.eu/online-film-lego-r-ninjago-r-film

### Screenshot of the web page (including address bar and extension icons) (required): 
https://screenshots.firefox.com/HIrMStGVm3JNadEu/www.bombuj.eu

### Environment (Required): 

- Operating System and Version: Win 10 x64
- Browser and Version: FF
- Adblocker and Version: uBlock

### Add everything else that you believe to be useful below (optional): 

Solution `||www.bombuj.eu/adblock/fuckadblock2.js$script,domain=www.bombuj.eu`

**Comment by jspenguin2017** [comment]
Can't reproduce on Chrome, is it Firefox-only?

**Comment by MajkiIT** [comment]
@jspenguin2017 I will check it

**Comment by MajkiIT** [comment]
@jspenguin2017 on chrome, the same situation. 
@xxcriticxx @KonoromiHimaries @hawkeye116477 Can you check it ?

**Comment by hawkeye116477** [comment]
I don't have antiadblock, but I have Nano Defender installed on Vivaldi (Chromium/62.0.3202.97). Probably @MajkiIT don't have Nano Defender extension installed.

**Comment by KonoromiHimaries** [comment]
works fine
![2017-12-28 17_39_47-the lego ninjago movie online film 2017 _ bombuj](https://user-images.githubusercontent.com/5884000/34416929-24736b5e-ebf6-11e7-9c22-00be14dd33d0.png)

**Comment by MajkiIT** [comment]
@jspenguin2017 I find my mistake. Thanks.
