### ISSUE TITLE
liquipedia.net

### ISSUE THREAD

**Issue by fireattack** [jspenguin2017/uBlockProtector#776]
### Test link (required): 

http://liquipedia.net/dota2/Main_Page

### Screenshot of the web page (including address bar and extension icons) (required): 

![image](https://user-images.githubusercontent.com/4130991/34425470-d69ee2c2-ebf1-11e7-88e4-428ea713f9e4.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![image](https://user-images.githubusercontent.com/4130991/34425482-edaff258-ebf1-11e7-9910-0848a8b16122.png)

### Environment (Required): 

- Operating System and Version: 
- Browser and Version: 64.0.3282.39 (Official Build) beta (64-bit) (cohort: Beta)
- Adblocker and Version: Nano Adblocker 1.0.0.21

### Explain what was not right (optional if obvious): 

Open the site, wait until it fully loads. It will then redirect to the page showed above

### Reproduction steps (optional if trivial): 

Use all default filters came with Nano Adblocker **BUT UNcheck `uBlock filters – Privacy​​​​​​​​​`**

### Add everything else that you believe to be useful below (optional): 

The MINIMUM filter set to break it from my observation is either:
* `Nano Defender Integration` + `EasyList`
* `Nano Defender Integration` + `Peter Lowe’s Ad and tracking server list`

And `uBlock filters – Privacy​​​​​​​​​` will always _UNbreak_ it.

**Comment by jspenguin2017** [comment]
Looks like Google changed their code...

**Comment by jspenguin2017** [comment]
Actually, this fix is: `liquipedia.net##script:inject(abort-on-property-read.js, adonis)`
