### ISSUE TITLE
reyada.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#778]
### Test link (required): 

http://www.reyada.com/

### Screenshot of the web page (including address bar and extension icons) (required): 
![2017-12-30_223437](https://user-images.githubusercontent.com/2828165/34457171-c8210114-edb1-11e7-9050-d25a55d3c759.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![2017-12-30_223516](https://user-images.githubusercontent.com/2828165/34457175-d63d2a84-edb1-11e7-9dc0-4b25f61a83e4.png)

### Environment (Required): 
- Operating System and Version: 
Win7 64Bit SP1
- Browser and Version: 
Chrome Version 63.0.3239.108 (Official Build) (64-bit)
- Adblocker and Version: 
ublock origin Version: 1.14.22 + nano defender Version: 13.16

### Explain what was not right (optional if obvious): 
all news disappear when ublock active

**Comment by jspenguin2017** [comment]
`@@||reyada.com^$ghide`

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Looks more like a broken page, than antiadblock to me.

`reyada.com#@#.ads_area`

**Comment by jspenguin2017** [comment]
If they add `.ads_area` to their main content, it's anti-adblock as it is baiting the adblocker to block the wrong thing.

**Comment by okiehsch** [comment]
Or they just don't know what they are doing, I will add `reyada.com#@#.ads_area`, I am just not sure if I should add it to `uBlock-filters` or `uBlock-unbreak`.

**Comment by titosalah** [comment]
@jspenguin2017  please can you fix this site again >> now same problem no news appeared when ublock active
thank you

**Comment by jspenguin2017** [comment]
Can't reproduce, do you have a specific test link?

**Comment by titosalah** [comment]
try this http://www.reyada.com/sections/Premier-League

**Comment by jspenguin2017** [comment]
Works for me, update your filters? 

![image](https://user-images.githubusercontent.com/7283682/34580267-997228d4-f149-11e7-9f95-5727ec234f12.png)

**Comment by titosalah** [comment]
@jspenguin2017  thank you very much 
I disabled ublock origin and enabled Nano Adblocker now every thing perfect 
 very good my friend
