### ISSUE TITLE
ally.sh

### ISSUE THREAD

**Issue by xitero** [jspenguin2017/uBlockProtector#779]
### Test link (required): 
http://ally.sh/SZYR1

### Screenshot of the web page (including address bar and extension icons) (required): 
https://image.prntscr.com/image/KnB69j6sQcqtzUcAFCH3xg.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://image.prntscr.com/image/vOvx3kqrRIuiLWgGzJg43A.png

### Environment (Required): 

- Operating System and Version: Windows 10 Pro Version 1709 
- Browser and Version: Google Chrome 63.0.3239.108
- Adblocker and Version: Nano Adblocker 1.0.0.22 and Nano Defender 13.16

**Comment by jspenguin2017** [comment]
It was fixed a few days ago, try to update your filters.

**Comment by xitero** [comment]
Worked, thank you.
