### ISSUE TITLE
lkky.co

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#780]
### Test link (required): 
http://lkky.co/vVp1

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-01-02_105616](https://user-images.githubusercontent.com/2828165/34478886-146ea584-efac-11e7-9631-11723c0d0897.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-01-02_105649](https://user-images.githubusercontent.com/2828165/34478893-1e44aaa4-efac-11e7-93de-8652783d1f18.png)

### Environment (Required): 
- Operating System and Version: WIN7 SP1 64BIT
- Browser and Version:  63.0.3239.108 (Official Build) (64-bit)
- Adblocker and Version:  uBlock Origin  1.14.22 + Nano Defender 13.16

**Comment by jspenguin2017** [comment]
@mapx-
