### ISSUE TITLE
9anime.is

### ISSUE THREAD

**Issue by HeraKumi** [jspenguin2017/uBlockProtector#781]
### Test link:
`https://9anime.is`

### Screenshots:
[Screenshot 1: with it off](https://i.imgur.com/iUiEA11.jpg)
[Screenshot 2: with it on](https://i.imgur.com/KRblpa4.jpg)

### Screenshot of the console: 
[Screenshot 1](https://i.imgur.com/EceznWx.png)
[Screenshot 2](https://i.imgur.com/nx5bW1T.png)
[Screenshot 3](https://i.imgur.com/A9D5qFG.png)
[Screenshot 4: with it off](https://i.imgur.com/nKVlNMg.png)

### Environment: 

- Operating System and Version: Windows 10 Fall creators update | MacOS: El Capitan | Linux: Debian Deepin 15.5, Arch Linux: Manjaro Xfce, gnome, Arch Base Install with Gnome  
- Browser and Version:  Firefox Quantum
- Adblocker and Version:  Nano Defender/Adblocker

### What isn't right about this: 
Whenever I have the addons enable (nano defender with nano adblocker) mostly everything stops to work on this site, Videos, tabs, theme. But the weird this is that when I first installed this on Windows, Linux, And Marcos. it works fine but after about 10 - 40 mins the site loses functionality due to these being enabled, once turned off everything works as it should.
### Reproduction steps (optional if trivial): 
A fresh copy of cleaned browser(in my case Firefox quantum) and installed nano defender/adblocker an wait about 10 - 30 mins on the site then boom the site loses function.

**Comment by jspenguin2017** [comment]
Can you try: 
```
@@||rapidvideo.com/js/jquery.min.js$script
rapidvideo.com#@#script:inject(abort-on-property-read.js, popns)
```

**Comment by jspenguin2017** [comment]
cc @okiehsch 
Ping Fanboy? `@ryanbr`

**Comment by jspenguin2017** [comment]
Added a temporary fix to NanoFilters while waiting for response from uAssets / EasyList.

**Comment by HeraKumi** [comment]
Thank you, You have saved me from a long night filled with ads.  ❤

**Comment by okiehsch** [comment]
If I add
`@@||ajax.googleapis.com/ajax/libs/jquery/*$script,domain=9anime.is`
I can stream the video without any miner kicking in on my end.
Example link: `https://9anime.is/watch/overlord-dub.6j94`

**Comment by jspenguin2017** [comment]
I see that `@@||rapidvideo.com/js/jquery.min.js$script` is not required for the embed, but does unbreak some functionality of `rapidvideo.com` home page. 

I edited the second post, as I noticed that the jQuery file is cached and `@@||ajax.googleapis.com/ajax/libs/jquery/$domain=9anime.is` unbreak it when Chrome loads it again (which is the source of the real problem).

**Comment by jspenguin2017** [comment]
The third line is to disable an outdated rule form the Nano Defender Integration filter, uBO doesn't need it. I've removed the rule from the filter list.

**Comment by jspenguin2017** [comment]
I'll keep `@@||rapidvideo.com/js/jquery.min.js$script` in NanoFilters as it is legit jQuery for now, and I hope people at `rapidvideo.com` won't be watching me... 

@okiehsch thanks for dropping by. I'll call this fixed. Closing.

**Comment by okiehsch** [comment]
> Use CSP to disable WebWorker? Does video parsing depend on that?

I checked `rapidvideo.com` and 
````
||rapidvideo.com^$csp=child-src 'none';frame-src *;worker-src 'none';
````
does not break streaming.

**Comment by jspenguin2017** [comment]
OK, cool, let's keep that in our back pocket in case they start pulling off other nasty tricks 👍
