### ISSUE TITLE
download.inventivetalent.org

### ISSUE THREAD

**Issue by PaziHD** [jspenguin2017/uBlockProtector#782]
### Test link (required): 
https://download.inventivetalent.org/gh/AnimatedFrames/4.5.0-SNAPSHOT

### Screenshot of the web page (including address bar and extension icons) (required): 

![image](https://user-images.githubusercontent.com/7887281/34527799-072cb400-f0a7-11e7-99cf-e8cb6363e298.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

 
![image](https://user-images.githubusercontent.com/7887281/34527836-3047594e-f0a7-11e7-9d6f-8b16a1a88853.png)

### Environment (Required): 

- Operating System and Version: Windows 10 Pro, Insider Preview 1709
- Browser and Version: Firefox 57.0.3
- Adblocker and Version: Nano Adblocker 1.0.0.23 + Nano Defender 13.16

### Explain what was not right (optional if obvious): 
Detected boi

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
What exactly is the issue? The complete screenshot of `https://download.inventivetalent.org/gh/AnimatedFrames/4.5.0-SNAPSHOT`
![fghgfhfgh](https://user-images.githubusercontent.com/16838044/34532378-4154e42c-f0b6-11e7-92e1-a97cc19f0f18.PNG)


As you can see you can download the file without issue if you click the third option.

If someone feels uncomfortable to be reminded that he or she uses an adblocker, just add
`@@||download.inventivetalent.org/external/adfly/*$xmlhttprequest,first-party`
which results in
![bhfgh](https://user-images.githubusercontent.com/16838044/34532330-10157566-f0b6-11e7-8935-c3030c8b2e9a.PNG)

As you can see the difference is marginal and I will not add that filter to uBlock.

**Comment by jspenguin2017** [comment]
@okiehsch Ops, I just woke up and didn't read it correctly.

**Comment by jspenguin2017** [comment]
No anti-adblock notice is tolerated in Nano (with the only exception being auto-starting mining wall), I'll fix it in NanoFilters.
