### ISSUE TITLE
cutwin.pro

### ISSUE THREAD

**Issue by version365** [jspenguin2017/uBlockProtector#783]
### Test link (required): 
https://cutwin.pro/xCLcAgK

### Environment (Required): 

- Operating System and Version: Windows 7 Ultimate
- Browser and Version: Google Chrome 63
- Adblocker and Version: UBO

### Explain what was not right (optional if obvious): 

Cutwin.com changed/added a new domain cutwin.pro
So, the timer skipping doesn't work.
Please add support for cutwin.pro

**Comment by jspenguin2017** [comment]
That's `cutwin.pro` though. I think `.com` one is fixed.
