### ISSUE TITLE
nbc.com

### ISSUE THREAD

**Issue by nexus077** [jspenguin2017/uBlockProtector#784]
Ads are still playing on nbc.com player, but it does not seem to affect playback otherwise.

### Environment (Required): 

- Operating System and Version: Windows 10
- Browser and Version: Google Chrome 62.0.3202.89
- Adblocker and Version: Nano Adblocker v1.0.0.23

**Comment by nexus077** [comment]
Seems screenshot links don't show:

### Screenshot of the web page (including address bar and extension icons) (required): 

https://i.imgur.com/qIek2oV.png



### Screenshot of the console (press `F12` to bring up the console) (required): 

https://i.imgur.com/S4vaC57.png
https://i.imgur.com/csITFjl.png
https://i.imgur.com/BTdMKsb.png

**Comment by jspenguin2017** [comment]
I'm aware of this, as stated in extension options page.
