### ISSUE TITLE
gyao.yahoo.co.jp

### ISSUE THREAD

**Issue by 1145141919** [jspenguin2017/uBlockProtector#787]
### Test link (required): 
https://gyao.yahoo.co.jp/player/01047/v00061/v0000000000000002156/

### Screenshot of the web page (including address bar and extension icons) (required): 

![0be776f28a85ef78113fea0dfa20689d](https://user-images.githubusercontent.com/25715415/34638562-6299011a-f311-11e7-9926-83f260a07820.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
 https://gyazo.com/ce94632376c8148400e81779481bc53e

### Environment (Required): 

- Operating System and Version: Windows 10 Home
- Browser and Version: Google Chrome 63.0.3239.132 (Official Build) (64-bit)
- Adblocker and Version: Nano Adblocker v1.0.0.25 Based on uBlock Origin v1.14.23.13 (with HTML filtering disabled) 
Nano Defender 13.17

### Explain what was not right (optional if obvious):
normally, video player appear.
with adblock, video player disappear.
(maybe wrong place?)

### Add everything else that you believe to be useful below (optional): 
The video player will not work except for Japan IP address.(Region Locking)

sry for bad english.

**Comment by jspenguin2017** [comment]
Which filter lists are you using?

**Comment by 1145141919** [comment]
seems like false positive on filter. please close.
