### ISSUE TITLE
megaurl.in

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#788]
### Test link (required): 
http://megaurl.in/AG2EDZM

### Screenshot of the web page (including address bar and extension icons) (required): 

![2018-01-06_195139](https://user-images.githubusercontent.com/2828165/34642403-17042590-f31b-11e7-9a11-9dcbf595d4b3.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-01-06_195153](https://user-images.githubusercontent.com/2828165/34642405-1c75d730-f31b-11e7-83f0-54bb8fb17a46.png)

### Environment (Required): 
- Operating System and Version: WIN 7 SP1 64BIT
- Browser and Version:  Chrome 63.0.3239.132 (Official Build) (64-bit)
- Adblocker and Version: Nano Adblocker 1.0.0.25+Nano Defender 13.17

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by titosalah** [comment]
@jspenguin2017  thank you very much .. can you help me and give me this script name used in this site .. or download link to use it in my site

**Comment by jspenguin2017** [comment]
Which script? The timer bypassing? It's included in Nano Adblocker, the script name is: `nano-setInterval-booster.js` and `nano-setTimeout-booster.js`.

**Comment by jspenguin2017** [comment]
There are more here: https://github.com/NanoAdblocker/NanoFilters/blob/master/NanoFiltersSource/NanoResources.txt

**Comment by titosalah** [comment]
@jspenguin2017  NO my friend I mean the name  of  PHP Script used in shortlinks websites  .. sorry iam not speak english iam from egypt try to understand me

**Comment by jspenguin2017** [comment]
Oh, I'm not really sure... I think I read about it somewhere...

**Comment by titosalah** [comment]
@jspenguin2017  ok why this message appear after 5 sec timer 
{"status":"error","message":"Bad Request.","url":""}

![2018-01-06_215224](https://user-images.githubusercontent.com/2828165/34643367-ee351db6-f32b-11e7-9b9b-b9b07d38410a.png)

**Comment by jspenguin2017** [comment]
Can't reproduce...

**Comment by titosalah** [comment]
@jspenguin2017  all shortlinks web sites  give me this error even already fixed like this site
{"status":"error","message":"Bad Request.","url":""}
![2018-01-06_215614](https://user-images.githubusercontent.com/2828165/34643415-9baa699c-f32c-11e7-8b18-635a69dbd11a.png)

**Comment by jspenguin2017** [comment]
@okiehsch Can you reproduce?
