### ISSUE TITLE
freewebscript.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#789]
### Test link (required): 

https://www.freewebscript.com/scripts/adlinkfly-v410-monetized-url-shortener.html

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-01-06_194333](https://user-images.githubusercontent.com/2828165/34642379-c9824e6e-f31a-11e7-9872-a4aa93a10940.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-01-06_194424](https://user-images.githubusercontent.com/2828165/34642386-d42cf044-f31a-11e7-822e-5eef5beb6996.png)

### Environment (Required): 

- Operating System and Version: WIN 7 SP1 64BIT
- Browser and Version:  Chrome 63.0.3239.132 (Official Build) (64-bit)
- Adblocker and Version: Nano Adblocker 1.0.0.25+Nano Defender 13.17

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
The site disables right-click functionality, I will restore the functionality with
`freewebscript.com##script:inject(abort-current-inline-script.js, $, contextmenu)`
This filter will be added to `uBlock-annoyances`, so it will **not** be part of the default setup, just a heads up.
