### ISSUE TITLE
linkurl.org

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#790]
### Test link (required): 
https://linkurl.org/D7a4wh9el3Fwww

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-01-06_213101](https://user-images.githubusercontent.com/2828165/34643216-22edef7c-f329-11e7-88d9-311df456dffc.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-01-06_213130](https://user-images.githubusercontent.com/2828165/34643217-2cbb36f4-f329-11e7-914a-0eb873a369e9.png)

### Environment (Required): 
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome 63.0.3239.132 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.25+Nano Defender 13.17

**Comment by jspenguin2017** [comment]
Seems to work for me, try update your filters?

**Comment by jspenguin2017** [comment]
@okiehsch 
Might need a refresh.

**Comment by okiehsch** [comment]
Another site that disables right-click functionality, this is really spreading, even some high traffic non-warez related websites are starting to do that, anyway
````
linkurl.org##script:inject(abort-current-inline-script.js, $, contextmenu)
linkurl.org##script:inject(abort-on-property-write.js, document.oncontextmenu)
linkurl.org##script:inject(abort-on-property-read.js, app_vars.force_disable_adblock)
@@||linkurl.org^$generichide
````
should work.
I will add it later today, I have some technical issues, damn kernel updates ;).

**Comment by jspenguin2017** [comment]
There are a couple more related: https://github.com/jspenguin2017/uBlockProtector/issues/791 https://github.com/jspenguin2017/uBlockProtector/issues/792

**Comment by okiehsch** [comment]
This includes a fix for https://github.com/jspenguin2017/uBlockProtector/issues/791 and https://github.com/jspenguin2017/uBlockProtector/issues/792.
I am short of time for the next few days, so pinging me will not result in a quick fix.
