### ISSUE TITLE
uploadedpremiumlink.xyz

### ISSUE THREAD

**Issue by version365** [jspenguin2017/uBlockProtector#793]
### Test link (required): 
`https://www.uploadedpremiumlink.xyz/`

### Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/jTUX6N4.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/yLmHCNY.png

### Environment (Required): 

- Operating System and Version: Windows 7 Ultimate
- Browser and Version: Google Chrome 63.0.3239.108 (64-bit)
- Adblocker and Version: UBO 1.14.22

### Reproduction steps (optional if trivial): 
The warning is not immediate. It takes 10 to 20 seconds after loading..

**Comment by jspenguin2017** [comment]
okiehsch

**Comment by okiehsch** [comment]
That ping failed 😆 .
