### ISSUE TITLE
arabcut.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#794]
### Test link (required): 
https://arabcut.com/0qMnj

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-01-07_084402](https://user-images.githubusercontent.com/2828165/34647272-1879b6a8-f387-11e7-8804-7edd2c980832.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-01-07_084423](https://user-images.githubusercontent.com/2828165/34647273-208f8160-f387-11e7-8a2a-205265c536d7.png)

### Environment (Required): 
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome 63.0.3239.132 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.25+Nano Defender 13.17

**Comment by 1145141919** [comment]
try whitelist 'http://arabcut.com/js/ads.js'

**Comment by jspenguin2017** [comment]
@mapx-
