### ISSUE TITLE
publicdomainq.net

### ISSUE THREAD

**Issue by 1145141919** [jspenguin2017/uBlockProtector#797]
### Screenshot of the web page (including address bar and extension icons) (required): 

![b4ddad60be76af2d9648b344b6c89c56](https://user-images.githubusercontent.com/25715415/34649729-f6e01f34-f3f7-11e7-83d0-84d7f91c9b1c.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![a](https://user-images.githubusercontent.com/25715415/34649643-a55a1e22-f3f6-11e7-80d9-636788f8ba78.png)

### Environment (Required): 

- Operating System and Version: Windows 10 Home
- Browser and Version: 63.0.3239.132 (Official Build) （64 bit)
- Adblocker and Version: Nano Adblocker v1.0.0.25 + Nano defender 13.17

### Explain what was not right (optional if obvious): 
download button is disappear if use adblock.

### Reproduction steps (optional if trivial): 
select this button.
![gtsrfdx](https://user-images.githubusercontent.com/25715415/34649679-2c06a92c-f3f7-11e7-8b75-4d5744a481ea.png)
if select this button, normally(without adblock) download button is appear like this.
![3de0ce87351a2221bb000e62493f51e6](https://user-images.githubusercontent.com/25715415/34649721-d3fd9a50-f3f7-11e7-801c-1e4ff92270cc.png)

**Comment by jspenguin2017** [comment]
@mapx- 
```
publicdomainq.net#@#.adsbygoogle
publicdomainq.net##ins.adsbygoogle
```

**Comment by mapx-** [comment]
it should be reported here:
http://www.abpchina.org/forum/forum.php?mod=forumdisplay&fid=49

**Comment by jspenguin2017** [comment]
That is Japanese not Chinese.
