### ISSUE TITLE
[Firefox] Add-on causes tabs to be un-lazified at startup affecting startup performance

### ISSUE THREAD

**Issue by FatOrangutan** [jspenguin2017/uBlockProtector#798]
### Screenshot of the console (press `F12` to bring up the console) (required): 
![capture](https://user-images.githubusercontent.com/8336638/34700415-088d9f88-f509-11e7-8415-bbdfde95032c.PNG)

### Environment (Required): 

- Operating System and Version: Windows 10 1709
- Browser and Version: 59.0a1 (2018-01-08) (64-bit)
- Adblocker and Version: Nano Defender 13.17

### Explain what was not right (optional if obvious): 
Lazy tabs tremendously improve session restore performance. Nano Defender undoes that.

### Reproduction steps (optional if trivial): 
1) On a fresh browser profile, install Nano Defender. Either all by itself, or along with Nano Adblocker or any other add-ons, it doesn't matter.
2) Open some tabs and let them load.
3) Open Browser Console
4) Restart the browser (shift+F2 > restart)
5) Notice poor startup performance and see that Browser Console displays the above message.

### Add everything else that you believe to be useful below (optional): 
Meta bug: [Virtual tabs - lazily create linkedBrowser and other dependent elements for tabbrowser tabs to improve startup performance](https://bugzilla.mozilla.org/show_bug.cgi?id=906076)
[Bug 1345098: Lazy-browser-tabs: Deal with code which would unnecessarily/prematurely bind lazy-browsers](https://bugzilla.mozilla.org/show_bug.cgi?id=1345098)

**Comment by jspenguin2017** [comment]
I can't think of what is causing it...

**Comment by jspenguin2017** [comment]
Is there documentation on how that work, like what an extension does will cause the problem? If not, I guess it's more of a browser bug.

**Comment by FatOrangutan** [comment]
I will try and ask around if there is any documentation.

>If not, I guess it's more of a browser bug.  
  
I can file it on Bugzilla if you want, but looking at [Bug 1368193](https://bugzilla.mozilla.org/show_bug.cgi?id=1368193), I don't think it will be a browser bug.

**Comment by jspenguin2017** [comment]
Well, the bug you linked didn't reach a conclusion, it just listed extensions that are fine and ones that cause the problem. It's still unclear what exactly in those extensions cause the problem, it can very well be a browser bug.

**Comment by FatOrangutan** [comment]
Filed [Bug 1428956](https://bugzilla.mozilla.org/show_bug.cgi?id=1428956).

**Comment by jspenguin2017** [comment]
Can you link it back here? Because I don't get notification of that bug.

**Comment by FatOrangutan** [comment]
Unsure what you mean. Do you want me to leave a comment on the Bugzilla issue containing a link to this issue on your repo?

**Comment by jspenguin2017** [comment]
Yea. 
I'm guessing it's because the tab manager queries frames of tabs, but unloaded tabs shouldn't have any frame, the `discarded` property will be set to true, as per standard, in case extensions need to know the difference.

**Comment by jspenguin2017** [comment]
I'll investigate what other designs are available for tab manager. The current one isn't very good either way.

**Comment by FatOrangutan** [comment]
Ok, linked back here.

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/34747474-ab0919e4-f555-11e7-9f2f-ab2c33c392bc.png)
![image](https://user-images.githubusercontent.com/7283682/34747478-b0a05278-f555-11e7-92ca-cf6e660185fe.png)
I tested it in Chrome, and discarded tabs don't have any frame. This is the logical behavior IMO.

**Comment by jspenguin2017** [comment]
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webNavigation/getAllFrames
In their doc, they said the API is based on Chrome's API, so I'd say it's a browser bug. 
![image](https://user-images.githubusercontent.com/7283682/34747631-54609dbe-f556-11e7-8156-60291284538f.png)

**Comment by FatOrangutan** [comment]
Have you seen [1428956#c3](https://bugzilla.mozilla.org/show_bug.cgi?id=1428956#c3)? If you disagree, can you reply on the bug itself?

**Comment by jspenguin2017** [comment]
I don't have an account there, tell them to either update the docs or to patch the browser API. 
He said it "should probably", I need them to make a final decision.

**Comment by jspenguin2017** [comment]
I'll wait for them to reach a conclusion. 

The memory leak is half fixed, the other half is kind of tricky, it affects many other extensions too, looks like we need another API for that, there seems to be no reasonable way to fix it for now. 
TBH the tab manager is such a problem for so many extensions, the browser should manage it for us. I'm aware that it is not needed for Firefox, but I need to refactor too much code to get that properly implemented.

**Comment by jspenguin2017** [comment]
This is up to the maintainer of Firefox port to fix.

**Comment by LiCybora** [comment]
I cannot reproduce on the current build with Firefox 60.0.2 on Debian 9.4. Not sure whether the new build or Firefox 60 fixed the problem, or just I missed some steps (or not enough tags loading) during reproduction. I also experience no poor start up performance.

**Comment by jspenguin2017** [comment]
I wouldn't worry about this. Unless you have more than 100 tabs it's not going to be a problem. Beside, it is a browser bug. 
Although pull requests welcomed.
