### ISSUE TITLE
How to block ads in Gmail entirely?

### ISSUE THREAD

**Issue by orschiro** [jspenguin2017/uBlockProtector#801]
Dear @jspenguin2017,

Please let me know if this is the wrong way to report this. I am not very experienced with the internals of ad blocking.

I am using both Nano Adblocker and Defender with the default settings.

I noticed that not all ads are blocked in Gmail. I am attaching a screenshot.

Do you have any idea why this is the case?

Thank you for your work!

![image](https://user-images.githubusercontent.com/170947/34711060-22fa19b8-f51e-11e7-9818-6bcd25735f1e.png)

**Comment by version365** [comment]
What browser are you using?
What other extensions are you using?

**Comment by orschiro** [comment]
@version365 I am using Chrome 63.0.3239.132 (Official Build) (64-bit) and I have a bunch of extensions enabled. Anything specific I should look out for that may conflict?

**Comment by version365** [comment]
It would be best if you could give the list of extensions..
>Anything specific I should look out for that may conflict?
Check for any redirector extension or userscript manager or referrer control extension.

Moreover, check if there is any extension/software installed that injects ads in the webpage.

**Comment by orschiro** [comment]
Of course, no problem. Below is the list of the enabled ones.

Maybe these ads cannot be removed because they are added by the service I am using which sends me these emails? It's https://blogtrottr.com.

![image](https://user-images.githubusercontent.com/170947/34721618-adb09c38-f543-11e7-8407-05efc75aa551.png)
![image](https://user-images.githubusercontent.com/170947/34721629-b645460a-f543-11e7-92a5-d0c60053a3e4.png)

**Comment by version365** [comment]
First of all, whoa!! that's lot of extentions..
Why use two password manager??
Also, you can remove 'I don't care about cookies', & subscribe to two adblock filterlists which does the same job..
1. [Prebake](abp:subscribe?location=https%3A%2F%2Fraw.github.com%2Fliamja%2FPrebake%2Fmaster%2Fobtrusive.txt&title=Prebake%20-%20Block%20obtrusive%20EU%20cookie%20notices)
2. [I don't care about cookies](abp:subscribe?location=https%3A//www.i-dont-care-about-cookies.eu/abp/&title=I%20don%27t%20care%20about%20cookies)

----------------------------------
I can't certainly say what's causing the error.
Here's two things you could do..

1. Subscribe to more filterlists. Here is mine >> https://i.imgur.com/8pLMr93.png ; https://i.imgur.com/8oTZZRu.png ; https://i.imgur.com/ux72yqv.png
2. Disable all extentions except NanoADB & NanoDef; then enable them one by one and see which is causing problems.

I am certain it's an issue with other extensions cause I have the same config (Chrome, UBO & NanoDef); I just subscribed to https://blogtrottr.com and I don't see any ads!!

**Comment by jspenguin2017** [comment]
You mean ads inside an email sent to you?

**Comment by orschiro** [comment]
@version365 thanks for your suggestion which I will try but before that...

> You mean ads inside an email sent to you?

Correct!

**Comment by jspenguin2017** [comment]
Oh wow that's going to be a bit hard, maybe try the element picker?

**Comment by orschiro** [comment]
I tried the element picker already but the problem is that the elements are variable, depending on the email I am looking at. Let me show you some screenshots...

**Comment by orschiro** [comment]
Hmm, currently I am only finding one email in my archives that shows an ad actually. 

![image](https://user-images.githubusercontent.com/170947/34727281-c705ac1a-f556-11e7-9353-a7c55602828d.png)

**Comment by jspenguin2017** [comment]
Yea, there isn't much we can do in that case...

**Comment by orschiro** [comment]
OK, no worries. Thanks for your help anyway. :-)

**Comment by version365** [comment]
@orschiro Have you subscribed to more filterlists as I suggested?

**Comment by orschiro** [comment]
@version365 I have just done so. I am going to report back if that helps. Thanks!

**Comment by orschiro** [comment]
@version365 ok, still seeing ads. 

![image](https://user-images.githubusercontent.com/170947/34759270-ee35fd7e-f5da-11e7-881d-0d0f63608b50.png)

![image](https://user-images.githubusercontent.com/170947/34759282-f9f88316-f5da-11e7-8702-97265495fbb1.png)

![image](https://user-images.githubusercontent.com/170947/34759288-029ec2be-f5db-11e7-9601-f5389bb7b259.png)

![image](https://user-images.githubusercontent.com/170947/34759297-1291a42a-f5db-11e7-99e6-604d5a9d6f27.png)

**Comment by version365** [comment]
Hmm.. well, I guess I can't do anything in this case then..

**Comment by orschiro** [comment]
No problem. You were of great help already!
