### ISSUE TITLE
watch.hgtv.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#802]
### Test link (required): 
http://watch.hgtv.com/show/HFXUP/Fixer-Upper/3895534/Ranch-House-Reimagined/

### Screenshot of the console (press `F12` to bring up the console) (required): 
![capture](https://user-images.githubusercontent.com/15007183/34746024-93c36496-f560-11e7-9c06-6b5c4c737255.PNG)

### Environment (Required): 

- Operating System and Version: Win 7 Pro
- Browser and Version: Firefox 57.0.4(64-bit)
- Adblocker and Version: 1.0.0.25

### Reproduction steps (optional if trivial): 
**ACCOUNT NEEDED**
**MAYBE GEO BLOCKED FOR NON US USERS**

login and select episode to watch

### Add everything else that you believe to be useful below (optional): 

i get same result on chrome 63.0.3239.132(64-bit)

**Comment by jspenguin2017** [comment]
Issue moved to https://github.com/NanoAdblocker/NanoFilters/issues/147
Please continue the conversation there.
