### ISSUE TITLE
adcoin.me

### ISSUE THREAD

**Issue by ExtendLord** [jspenguin2017/uBlockProtector#803]
### Test link (required): 
[Adcoin link](https://adcoin.me/rHpNN5SK)

### Screenshot of the web page (including address bar and extension icons) (required): 
![image](https://user-images.githubusercontent.com/26222159/34746608-4c565d24-f59d-11e7-8088-39002f435505.png)

### Environment (Required): 

- Operating System and Version:  Windows 10 Pro Fall Creators Update
- Browser and Version: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- Adblocker and Version: uBlock Origin 1.14.22

**Comment by jspenguin2017** [comment]
@mapx-

**Comment by KiLL4FuNK** [comment]
the page died you can remove the filters

**Comment by jspenguin2017** [comment]
@mapx-

**Comment by mapx-** [comment]
removed
