### ISSUE TITLE
minecraftpolska.net

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#804]
### Test link (required): 
http://minecraftpolska.net/

### Screenshot of the console (press `F12` to bring up the console) (required): 
![capture](https://user-images.githubusercontent.com/15007183/34746938-119e3af0-f564-11e7-9150-f7e799098fbb.PNG)

### Environment (Required): 

- Operating System and Version: Win 7 Pro
- Browser and Version: Firefox 57.0.4(64-bit)
- Adblocker and Version: 1.0.0.25

**Comment by jspenguin2017** [comment]
@mapx-

**Comment by mapx-** [comment]
`minecraftpolska.net#@##reklama`
or
`||minecraftpolska.net/templates/Oneland/dist/sweetalert.min.js$script,first-party`

?

**Comment by jspenguin2017** [comment]
Up to you.
