### ISSUE TITLE
thewindowsclub.com

### ISSUE THREAD

**Issue by Salin1810** [jspenguin2017/uBlockProtector#805]
### Test link (required): 
http://www.thewindowsclub.com/best-chrome-flags-tweaks

### Screenshot of the web page (including address bar and extension icons) (required): 

https://i.imgur.com/yPpWcZD.png

### Screenshot of the console (press `F12` to bring up the console) (required): 

https://i.imgur.com/PaIqOMQ.png

### Environment (Required): 
- Operating System and Version: Windows 7 Ultimate x64 Build 7601 SP1
- Browser and Version: Chromium 62.0.3202.94
- Adblocker and Version: Nano Adblocker v1.0.0.26

### Add everything else that you believe to be useful below (optional): 
The banner will not show immediately, about 10 seconds after it's displayed

**Comment by jspenguin2017** [comment]
Can't reproduce, did you change the default filters selection?

**Comment by Salin1810** [comment]
I did remove uBlock filters filters selection, I rechecked so that banner removed, thank for your help
