### ISSUE TITLE
theweek.co.uk

### ISSUE THREAD

**Issue by spodermenpls** [jspenguin2017/uBlockProtector#806]
### Test link (required): 

    http://www.theweek.co.uk/

### Screenshot of the web page (including address bar and extension icons) (required): 

http://www.bilder-upload.eu/upload/8f7be7-1515589286.png

### Screenshot of the console (press `F12` to bring up the console) (required): 

http://www.bilder-upload.eu/upload/f03eee-1515589821.jpg

### Environment (Required): 

- Operating System and Version: Windows 10 Pro 64-bit
- Browser and Version: Firefox 57.0.4 64-bit
- Adblocker and Version: uBlock Origin 1.14.22 + uMatrix 1.2.0 (+ Nano Defender 13.17 on AMO)

### Add everything else that you believe to be useful below (optional): 

The site doesn't seem to detect the adblocking at all times.

**Comment by jspenguin2017** [comment]
@mapx-

**Comment by jspenguin2017** [comment]
There seems to be a fix in uAssets, try update your filters?

**Comment by spodermenpls** [comment]
@jspenguin2017 I updated all uBlock filters (and everything else), but the "adblock lock" still popped up after a longer time of surfing their sites. According to the inspector (http://www.bilder-upload.eu/upload/3349e6-1515673233.jpg), the adblock banner is related to the "http://cdn1.theweek.co.uk/misc/advagg_js/ab20853.js" script, is there a way to circumvent that thing?

**Comment by jspenguin2017** [comment]
Can you report to uAssets? I can't seem to be able to reproduce.

**Comment by spodermenpls** [comment]
I was able to remove the lock screen using the element zapper, I might open a new issue there later.

**Comment by okiehsch** [comment]
I can reproduce with Chrome, works fine with Firefox on my end.

I will change the `theweek.co.uk` filter to 
`theweek.co.uk##script:inject(abort-on-property-read.js, _sp_._networkListenerData)`

Should fix the issue.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/cbba3ead3ab0195f44c1598a35a47a6a85954462

**Comment by spodermenpls** [comment]
@okiehsch This new rule does the trick, thanks for your work!
