### ISSUE TITLE
urlex.org

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#809]
### Test link (required): 
http://urlex.org/

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-01-11_232251](https://user-images.githubusercontent.com/2828165/34848308-f6c190a0-f726-11e7-8e4d-96465560f5be.png)
### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-01-11_232309](https://user-images.githubusercontent.com/2828165/34848317-fe93e85a-f726-11e7-8dcb-3cf8acd93a92.png)

### Explain what was not right (optional if obvious): 
when try to expand short URL this message appeared 

### Environment (Required): 
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome 63.0.3239.132 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.25+Nano Defender 13.17

**Comment by jspenguin2017** [comment]
Can't reproduce.

**Comment by jspenguin2017** [comment]
Can't reproduce.
