### ISSUE TITLE
tejikarao.kodaisi.net

### ISSUE THREAD

**Issue by 1145141919** [jspenguin2017/uBlockProtector#812]
### Test link (required): 
https://tejikarao.kodaisi.net/tag/httpstejikarao-kodaisi-netmiwayama-layline

### Screenshot of the web page (including address bar and extension icons) (required): 

![2c773ea95f914355ab12394362e1deb5](https://user-images.githubusercontent.com/25715415/34904205-48c7e544-f884-11e7-8268-b80ebc9aba40.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![10e1a6e4f45324a16e5562d4f4bc2035](https://user-images.githubusercontent.com/25715415/34904209-5fe604d6-f884-11e7-8253-fe06820006bd.png)

### Environment (Required): 

- Operating System and Version: Windows10 Home
- Browser and Version: 63.0.3239.132 (Official Build) （64 bit)
- Adblocker and Version: Chrome Nano Adblocker v1.0.0.26

#### Your filter lists (Required): 
NoCoin (https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt)
JPN:Adguard japan filter
JPN:ABP japenese version

**Comment by jspenguin2017** [comment]
I'm getting 403, do you have another test link?

**Comment by version365** [comment]
@1145141919
I too am getting 403 error.
But I think you are getting your adblock detected because you are using 'adf.ly skipper' extension. Try disabling it and see again.
Moreover, you don't need adf.ly skipper because "Nano Defender" already does the job.

**Comment by 1145141919** [comment]
@version365 i disable adfly skipper, but i get 'adblock detected again'
@jspenguin2017 https://tejikarao.kodaisi.net/tag/%E5%A4%A9%E5%B2%A9%E6%88%B8%E5%88%86%E7%A5%9E%E7%A4%BE
new test link

**Comment by 1145141919** [comment]
@version365 i disable adfly skipper, but i get same message. 
@jspenguin2017  new link https://tejikarao.kodaisi.net/tag/httpstejikarao-kodaisi-netmiwayama-layline

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/34912708-1853e860-f8a5-11e7-8d3c-f76f1c766da7.png)
Can you dump the logger?

**Comment by 1145141919** [comment]
what is logger?

**Comment by 1145141919** [comment]
test https://tejikarao.kodaisi.net/aaaefdws

**Comment by jspenguin2017** [comment]
I'm still getting 403. 

Open `chrome-extension://gabbbocakeomblphkmmnoamkioajlkfo/logger-ui.html` and go to the website, then screenshot the Logger.

**Comment by 1145141919** [comment]
https://tejikarao.kodaisi.net/%E3%80%80a

**Comment by 1145141919** [comment]
ok
PS. i get 403 too(sometime)

**Comment by 1145141919** [comment]
https://tejikarao.kodaisi.net/ametejikarao

**Comment by 1145141919** [comment]
https://gyazo.com/e48f630f0f12f490354b5126a4b88284

**Comment by jspenguin2017** [comment]
I'm getting 403 for all of them...

**Comment by 1145141919** [comment]
@jspenguin2017 if dont watch gyazo(screen shot) here is it.
https://gyazo.com/e48f630f0f12f490354b5126a4b88284

**Comment by 1145141919** [comment]
https://gyazo.com/e48f630f0f12f490354b5126a4b88284
https://gyazo.com/e48f630f0f12f490354b5126a4b88284
https://gyazo.com/e48f630f0f12f490354b5126a4b88284
https://gyazo.com/e48f630f0f12f490354b5126a4b88284
https://gyazo.com/e48f630f0f12f490354b5126a4b88284
https://gyazo.com/e48f630f0f12f490354b5126a4b88284
https://gyazo.com/e48f630f0f12f490354b5126a4b88284
https://gyazo.com/e48f630f0f12f490354b5126a4b88284
https://gyazo.com/e48f630f0f12f490354b5126a4b88284
https://gyazo.com/e48f630f0f12f490354b5126a4b88284
https://gyazo.com/e48f630f0f12f490354b5126a4b88284
https://gyazo.com/e48f630f0f12f490354b5126a4b88284

**Comment by jspenguin2017** [comment]
I definitely saw that, although I don't see much interesting there.

**Comment by jspenguin2017** [comment]
Can you dump `view-source:https://tejikarao.kodaisi.net/tag/httpstejikarao-kodaisi-netmiwayama-layline` onto paste bin (if it's not 403)

**Comment by 1145141919** [comment]
@jspenguin2017 https://hastebin.com/avonaramev.xml

**Comment by jspenguin2017** [comment]
Try `tejikarao.kodaisi.net##script:inject(set-constant.js, AlobaidiDetectAdBlock, true)`

**Comment by 1145141919** [comment]
another message are appeared. (yes, about adblock)
https://gyazo.com/07c53db8d6695659e6e7c85488139fb7

**Comment by 1145141919** [comment]
and something in source(kill-adblock)
https://gyazo.com/804d99cf26a049d5f987b8bfe5733766

**Comment by jspenguin2017** [comment]
Add `tejikarao.kodaisi.net##script:inject(abort-on-property-write.js, KillAdBlock)`

**Comment by 1145141919** [comment]
seems like fixed. thx

**Comment by 1145141919** [comment]
@jspenguin2017  seems like fixed. thx
