### ISSUE TITLE
sg-siken.com

### ISSUE THREAD

**Issue by 1145141919** [jspenguin2017/uBlockProtector#813]
### Screenshot of the web page (including address bar and extension icons) (required): 

![1](https://user-images.githubusercontent.com/25715415/34913092-0bd8cfa0-f937-11e7-8388-1bf3f73b2193.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![default](https://user-images.githubusercontent.com/25715415/34913099-3fb51f40-f937-11e7-924e-7e91ef029900.png)

### Explain what was not right (optional if obvious): 
some text is blurred.

### Reproduction steps (optional if trivial): 
1.click orange button  
2. click this button
             ↓
![3](https://user-images.githubusercontent.com/25715415/34913118-a3b61378-f937-11e7-9486-b6e9ebce993a.png)

### Environment (Required): 

- Operating System and Version: Windows10 Home
- Browser and Version: Chrome 63.0.3239.132 (Official Build) （64 bit)
- Adblocker and Version: Nano Adblocker v1.0.0.26

#### Your filter lists (Required): 
NoCoin (https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt)
JPN:Adguard japan filter
JPN:ABP japenese version
Fanboy’s Social Blocking List

#### Your custom filters (Required if you have any): 
tejikarao.kodaisi.net##script:inject(set-constant.js, AlobaidiDetectAdBlock, true)
tejikarao.kodaisi.net##script:inject(abort-on-property-write.js, KillAdBlock)

**Comment by jspenguin2017** [comment]
```js
if ($('.ansbg').length == 2 && Math.random() > 0.2){
	setTimeout(function(){
		var ad = $('ins.adsbygoogle')[0];
		if (ad && ad.innerHTML.replace(/\s/g , "").length === 0) {
			$('.ansbg').last().attr('style', 'opacity:.05 !important').before("<p>※解説へのアクセスはアプリやプラグインなどの拡張機能によって制限されています。</p>");
		}
	}, 2000);
}
```

`sg-siken.com##script:inject(setTimeout-defuser.js, adsbygoogle)` @mapx-

**Comment by jspenguin2017** [comment]
@mapx- I consider this one hard anti-adblock, are you adding this to uAsset?

**Comment by mapx-** [comment]
`some text is blurred.`  I cannot reproduce - if I understood correctly the issue - it. What helps ? only your filter or even the other 2 of OP ?

**Comment by jspenguin2017** [comment]
Just my filter. 
1. Go into the link
2. Click the orange button
3. Click `正解を表示する`
![image](https://user-images.githubusercontent.com/7283682/34994896-26be24d0-fa92-11e7-916f-99e571751128.png)
