### ISSUE TITLE
twitter.com

### ISSUE THREAD

**Issue by 1145141919** [jspenguin2017/uBlockProtector#814]
### Test link (required): 
any tweets on twitter.com 
(like https://twitter.com/realDonaldTrump/status/952301373479104512)

### Screenshot of the web page (including address bar and extension icons) (required): 

![ger](https://user-images.githubusercontent.com/25715415/34913200-011b6d04-f93a-11e7-9043-f600c22f4d3e.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
 https://gyazo.com/3699a13a967e538b5562902ea036532b

### Explain what was not right (optional if obvious): 
Can't click 'Next'
(Can't report tweet.)

### Reproduction steps (optional if trivial): 
Report any tweets in twitter.com

### Environment (Required): 

- Operating System and Version: Windows10 Home
- Browser and Version: Chrome 63.0.3239.132 (Official Build) （64 bit)
- Adblocker and Version: Nano Adblocker v1.0.0.26

#### Your filter lists (Required): 
NoCoin (https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt)
JPN:Adguard japan filter
JPN:ABP japenese version
Fanboy’s Social Blocking List

#### Your custom filters (Required if you have any): 

tejikarao.kodaisi.net##script:inject(set-constant.js, AlobaidiDetectAdBlock, true)
tejikarao.kodaisi.net##script:inject(abort-on-property-write.js, KillAdBlock)

**Comment by jspenguin2017** [comment]
It works for me. If you are using `Social Blocking List` you can expect things doesn't work as expected on social media. 
![image](https://user-images.githubusercontent.com/7283682/34918264-3d33a1e4-f90d-11e7-8bd8-89236f40f024.png)
