### ISSUE TITLE
alts4free.com

### ISSUE THREAD

**Issue by 1145141919** [jspenguin2017/uBlockProtector#815]
### Test link (required): 
http://alts4free.com/decode.php

### Screenshot of the web page (including address bar and extension icons) (required): 

![asdf](https://user-images.githubusercontent.com/25715415/34913893-74f1ceba-f94b-11e7-8c80-1a8d134b84e2.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![asdf2](https://user-images.githubusercontent.com/25715415/34913898-a5546c3e-f94b-11e7-8e2a-9ea81b373b70.png)

#### Your filter lists (Required): 
NoCoin (https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt)
JPN:Adguard japan filter
JPN:ABP japenese version
Fanboy’s Social Blocking List

#### Your custom filters (Required if you have any): 
tejikarao.kodaisi.net##script:inject(set-constant.js, AlobaidiDetectAdBlock, true)
tejikarao.kodaisi.net##script:inject(abort-on-property-write.js, KillAdBlock)

### Add everything else that you believe to be useful below (optional): 
BlockAdBlock

**Comment by jspenguin2017** [comment]
@mapx-

**Comment by jspenguin2017** [comment]
There's also overlay ads and popup...

**Comment by mapx-** [comment]
could you test
`alts4free.com##script:inject(noeval.js)`

**Comment by jspenguin2017** [comment]
Although it does work, it blocks all the scripts, because of the rocket launcher thing. 
I'm not sure how to test it, @1145141919  does it work?

**Comment by 1145141919** [comment]
@jspenguin2017 yes, work fine.
