### ISSUE TITLE
myegy.tv

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#816]
### Test link (required): 
https://myegy.tv/link/601081

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-01-15_085617](https://user-images.githubusercontent.com/2828165/34930492-497d9fe8-f9d2-11e7-92f2-44613bd42a7a.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-01-15_084731](https://user-images.githubusercontent.com/2828165/34930511-6314e560-f9d2-11e7-8e46-0c7dab444eff.png)

### Explain what was not right (optional if obvious): 
![2018-01-15_084902](https://user-images.githubusercontent.com/2828165/34930517-6e8e7f78-f9d2-11e7-8ea6-6c68147e689e.png)

### Environment (Required): 
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome 63.0.3239.132 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.25+Nano Defender 13.17

#### Your filter lists (Required): 
My filter
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Ads (2)
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
Regions, languages (4)
ARA: Liste AR​​​​​2,112 used out of 2,122​​​​
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

#### Your custom filters (Required if you have any): 
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment]
@okiehsch 
Also there's a popup.

**Comment by okiehsch** [comment]
````
myegy.tv##script:inject(abort-current-inline-script.js, parseInt, tabunder)
myegy.tv#@#script:inject(abort-current-inline-script.js, A, popunders)
````
works on my end.
