### ISSUE TITLE
NSFW! avgle.com

### ISSUE THREAD

**Issue by user375s** [jspenguin2017/uBlockProtector#817]
### Test link (required): 
https://avgle.com/video/128459/

### Screenshot of the web page (including address bar and extension icons) (required): 
![clipboard 1](https://user-images.githubusercontent.com/35452463/34939605-f5f19f6c-fa1e-11e7-97a2-8f555dc889d2.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![clipboard 3](https://user-images.githubusercontent.com/35452463/34939834-d4f3c636-fa1f-11e7-8e46-9b6723c93ce8.png)

### Explain what was not right (optional if obvious): 
Anti-adblock when trying to play video.

### Environment (Required): 

- Operating System and Version: Windows 10 Home Version 1709
- Browser and Version: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- Adblocker and Version: uBlock Origin v1.14.24

#### Your filter lists (Required): 
![filter](https://user-images.githubusercontent.com/35452463/34939993-78d391c8-fa20-11e7-9f1e-9b835f159d44.png)

#### Your custom filters (Required if you have any): 
![custom](https://user-images.githubusercontent.com/35452463/34940089-d896cf8a-fa20-11e7-8f80-97c0d708c354.png)

**Comment by jspenguin2017** [comment]
@mapx- (it's hard anti-adblock)

**Comment by mapx-** [comment]
already fixed in uBo

**Comment by jspenguin2017** [comment]
Broke again.

**Comment by mapx-** [comment]
`||avgle.com/templates/frontend/videojs-$script`

**Comment by mirrorplease123** [comment]
It's not working again.

**Comment by hoonkai** [comment]
Is it fair to say they've managed to defeat anti-adblock killers?

**Comment by jspenguin2017** [comment]
If they are watching us, there isn't much we can do...

**Comment by Fezreal** [comment]
https://github.com/reek/anti-adblock-killer/issues/3854
please help

**Comment by mun35** [comment]
Try this on TamperMonkey: https://greasyfork.org/en/scripts/37810-f-ck-avgle-s-anti-adblock

**Comment by jspenguin2017** [comment]
There are ways around everything, if they are determined, they will break that in 2 days as well.

**Comment by jspenguin2017** [comment]
Let's see how long can that Userscript hold. If it fails I'll put up a proprietary solution like for lolalytics

**Comment by hoonkai** [comment]
Not long, I'm afraid. They've already patched it.

**Comment by jspenguin2017** [comment]
It's not possible to beat obfuscated code with clear ones. When a battle goes to this stage, it's pretty much about who has the most time to defeat the other side's obfuscation. The only reasonable way to win is to put in so much obfuscation that the other side gives up. There will never be a "once for all" solution, there are hundreds of solutions burnt at this stage and there are thousands more to come, that is, if the fight continues. 

The only other possibility is to have a browser that loads unfiltered page but render a filtered one, but that only works for non-intrusive sites, as prerolls, popups, and crypto mining can't be blocked this way.

**Comment by mun35** [comment]
> The only other possibility is to have a browser that loads unfiltered page but render a filtered one

Their script seems to constantly check for their ad elements though, so if the elements are stripped out with a delay, you'll get redirected.

**Comment by jspenguin2017** [comment]
The idea is to have the script interact with unfiltered version of the page, where ads elements will exist; but show the user the filtered version. There is no implementation, just theory at this point.

**Comment by jspenguin2017** [comment]
OK, the fight just escalated. The Userscript is now obfuscated and the website started IP banning on detection.

**Comment by ghajini** [comment]
@jspenguin2017 
why not make patches day to day/ less frequently until avgle gives up!!! just like done for noadblock.....

why adblocker to be on backfoot???

**Comment by jspenguin2017** [comment]
@ghajini NoAdblock didn't give up because I keep patching them, they give up because my final solution cannot be bypassed.

**Comment by jspenguin2017** [comment]
Also they have IP ban *plus* heavy obfuscation. I'm making a deobfuscation engine but it didn't go very far since fingerprinting framework functions manually is a huge pain.

**Comment by jspenguin2017** [comment]
Might be able to roll out a fix in ND Extra.

**Comment by jspenguin2017** [comment]
This issue is referenced in https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/18

**Comment by jspenguin2017** [comment]
OK, NVM, this isn't happening before https://github.com/jspenguin2017/JavaScriptDeobfuscator

**Comment by jspenguin2017** [comment]
An update on the deobfuscator, I have a decent self-defending buster going, which is pretty useless TBH. Debug protection buster and rotated RC4 string array buster are way more important. 

Domain lock is obfuscated with regular code, which is a pain to undo, but undoing it is near useless anyway. I honestly have no idea about how to undo control flow flattening, too many things depend on the runtime. Dead code injection should be undoable when string array is taken care of.

**Comment by jspenguin2017** [comment]
Alright, I got roasted RC4 string array buster working, here's the result: https://pastebin.com/LNF4kWjh
It now fits in Pastebin but still need quite a few cleanups. String array is unfortunately not the only trick that was used.
