### ISSUE TITLE
f.tabtter.jp

### ISSUE THREAD

**Issue by 1145141919** [jspenguin2017/uBlockProtector#818]
### Test link (required): 
https://f.tabtter.jp/

### Screenshot of the web page (including address bar and extension icons) (required): 

![tab](https://user-images.githubusercontent.com/25715415/34940415-cada1908-fa32-11e7-8ffc-f53b5c6d8e78.jpg)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![tab2](https://user-images.githubusercontent.com/25715415/34940444-e753cd72-fa32-11e7-8c04-6718a12d6df3.jpg)

### Explain what was not right (optional if obvious): 
I can not login on Twitter (OAuth cannot be used)

### Reproduction steps (optional if trivial): 
click Blue button
Without Adblock, it will go to the OAuth screen.
With Adblock, it does not move to the Oauth screen.

### Environment (Required): 

- Operating System and Version: Windows10 Home
- Browser and Version: Chrome 63.0.3239.132 (Official Build) （64 bit)
- Adblocker and Version: Nano Adblocker v1.0.0.26

#### Your filter lists (Required): 
NoCoin (https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt)
JPN:Adguard japan filter
JPN:ABP japenese version

### Add everything else that you believe to be useful below (optional):

**Comment by jspenguin2017** [comment]
```js
function _adck(fromsubmit) {
    var GAD_O = _$('googlead');
    if (
        GNG ||
        !GAD_O ||
        !GAD_O.innerHTML ||
        (getElementStyle(GAD_O, 'display') || '').search(/none/i) != -1 ||
        GAD_O.hidden
    ) {
        if (!GNG) {
            _$('lgnote').className = (_$('lgnote').className || '') + ' a-show';
            ESH('lgnote');
            //			setTimeout(function(){_$('lgnote').className = (_$('lgnote').className || '').replace(/ \a-show/,'')},1200);
        } else if (fromsubmit) {
            alert('恐れ入りますが、アドブロックを使用している場合は、当サービスをご利用いただけません。ご利用になる場合は、当サイトでのブロックを解除（f.tabtter.jpをホワイトリストに追加）してください。（無料版では、広告が表示されますが、利用を妨げるようなものではありません。）');
        }
        GNG = 1;
        return false;
    }
    return true;
}
```
Eh... Can be a bit tricky...
@mapx-

**Comment by mapx-** [comment]
`@@||tabtter.jp^$generichide`

**Comment by jspenguin2017** [comment]
I thought the div is empty and populated later, apparently not. Awesome.
