### ISSUE TITLE
html-online.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#819]
### Test link (required): 
https://html-online.com/editor/

### Screenshot of the web page (including address bar and extension icons) (required): 
![capture](https://user-images.githubusercontent.com/15007183/34949514-490fd9e8-f9de-11e7-983c-40bb376bc6b0.PNG)

### Environment (Required): 

- Operating System and Version: WIN 7 PRO
- Browser and Version: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.14.24

#### Your filter lists (Required): 
ubo standard + ubo pl list

**Comment by xxcriticxx** [comment]
@jspenguin2017 adblock is back again can you open this again

**Comment by jspenguin2017** [comment]
I can't reproduce: 
![image](https://user-images.githubusercontent.com/7283682/42665502-20a742ec-85fd-11e8-9460-7f8cae247f61.png)

**Comment by jspenguin2017** [comment]
Scrolled up and down 5 times, still can't reproduce.
