### ISSUE TITLE
darkcomet.net

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#820]
### Test link (required): 
https://darkcomet.net/

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-01-16_002603](https://user-images.githubusercontent.com/2828165/34963997-f799ddcc-fa53-11e7-8fe3-0b48f47ab549.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-01-16_002632](https://user-images.githubusercontent.com/2828165/34964005-008de856-fa54-11e7-828d-85975fc88371.png)

### Environment (Required): 
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome 63.0.3239.132 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.25+Nano Defender 13.17

#### Your filter lists (Required): 
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Ads (2)
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
Regions, languages (4)
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

#### Your custom filters (Required if you have any): 
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment]
@okiehsch
