### ISSUE TITLE
cutbit.io

### ISSUE THREAD

**Issue by SkeletalDemise** [jspenguin2017/uBlockProtector#822]
### Test link (required):
http://cutbit.io/OvU9

### Screenshot of the web page (including address bar and extension icons) (required): 
![anti-adblock](https://user-images.githubusercontent.com/29117662/35036526-799da4b8-fb29-11e7-8fca-e0053eb75ddb.PNG)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![console](https://user-images.githubusercontent.com/29117662/35036815-6072dd7c-fb2a-11e7-8910-52ef277c33a4.PNG)

### Explain what was not right (optional if obvious): 
Anti-adblock message.

### Environment (Required): 

- Operating System and Version: Windows 10 1709 (64-bit)
- Browser and Version: Chrome 63.0.3239.132 (Official Build) (64-bit)
- Adblocker and Version: Nano Adblocker 1.0.0.27

#### Your filter lists (Required):
Default.

### Add everything else that you believe to be useful below (optional): 
Another URL shortener.

**Comment by jspenguin2017** [comment]
@mapx-

**Comment by mapx-** [comment]
https://github.com/uBlockOrigin/uAssets/issues/1310
