### ISSUE TITLE
store.playstation.com

### ISSUE THREAD

**Issue by MonfGeiger** [jspenguin2017/uBlockProtector#825]
### Screenshot of the web page (including address bar, extension icons, and console log)
![nano defender console log](https://user-images.githubusercontent.com/28603306/35187124-31c25ee4-fddc-11e7-914b-4ae167b3bf92.JPG) (Forgot to BlankOut one nsfw link, my bad)

### Explain what was not right (optional if obvious): The PSN Store should've been showing this below
![what should be happening ie screenshot](https://user-images.githubusercontent.com/28603306/35186984-68c1492a-fdda-11e7-9981-8be2b062c591.JPG)
Instead, nano defender seems to have derped with PSN (main store page on chrome alright, but if navigating to sub-sections for ps3/ps4/ps-whatever, this (1st screenshot) happens). Blacked out bookmarks are NSFW bookmarks, nuff said

### Reproduction steps (optional if trivial): 
Install uBlock Origin (latest dev build), install nano defender and follow steps for chrome/ublock integration (all nano filter lists included), then navigate to the psn store and try to explore either the psn flash sale (US version at the time of this post) or any sub-section of the store

### Environment (Required): 

- Operating System and Version: Windows 10 Pro 64 Bit (at latest version, updates and all)
- Browser and Version: Google Chrome (Stable, Version 63.0.3239.132)
- Adblocker and Version: Latest Dev Build of uBlock Origin (v1.14.25.101), used hiew32 to modify chrome.dl file to turn off developer mode extensions warning (its annoying, plain and simple)

#### Your filter lists (Required): 
![chosen filters](https://user-images.githubusercontent.com/28603306/35187088-76c14d76-fddb-11e7-86c8-1649ae25e8bd.JPG)

#### Your custom filters (Required if you have any): 
![custom filters](https://user-images.githubusercontent.com/28603306/35187089-790ff4d8-fddb-11e7-87eb-4e556a4da94f.JPG)

### Add everything else that you believe to be useful below (optional): I have whitelisted the psn store in every blocking related extension/function in chrome, and everything (mainly the console log screenshot) points towards nano defender causing a breakage; help whenever prompt is appreciated

**Comment by xxcriticxx** [comment]
i got similar issue with ps vue live tv i will open new topic about it

**Comment by jspenguin2017** [comment]
Can't reproduce. 
![image](https://user-images.githubusercontent.com/7283682/35189739-a3ba9908-fe0e-11e7-9f1e-5034e2ddd8c2.png)

**Comment by MonfGeiger** [comment]
correct me if im wrong, but there's a debug mode for nano defender, right? going into some console and editing lines for advanced users? if so, how would I go about using it, or should I just turn off nano defender and see then?

**Comment by Crardogg** [comment]
Hey I am getting the same issue as @MonfGeiger 
![psn issue](https://user-images.githubusercontent.com/7562927/35193921-053caf2a-fe70-11e7-91e7-9e5ec8c38be9.PNG)
Windows 10 64 Bit
Firefox 57.0.4
Nano Adblocker with Nano Defender
![nano filters](https://user-images.githubusercontent.com/7562927/35193988-e663bdc2-fe70-11e7-9c17-28eee59263ea.PNG)

**Comment by jspenguin2017** [comment]
The debug mode won't help in this case. I think it's a false positive in generic solutions, I'll add a whitelist.

**Comment by jspenguin2017** [comment]
Assuming this is fixed due to lack of response. Closing.
