### ISSUE TITLE
Automate Firefox version building

### ISSUE THREAD

**Issue by jspenguin2017** [jspenguin2017/uBlockProtector#827]
http://addons-server.readthedocs.io/en/latest/topics/api/signing.html
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_sign

**Comment by spodermenpls** [comment]
@jspenguin2017 I just noticed that Nano Defender is no longer available on mozilla.org, what happened?

**Comment by jspenguin2017** [comment]
@spodermenpls https://github.com/NanoAdblocker/NanoCore/issues/41#issuecomment-364117216
