### ISSUE TITLE
https://trakt.tv/shows/anticipated?page=1

### ISSUE THREAD

**Issue by Zhangsun321** [jspenguin2017/uBlockProtector#828]
latest chrome.. ubo 1.14.24
https://trakt.tv/shows/anticipated?page=1
not sure if its anti ad block... or a problem with easylist 

https://i.imgur.com/bc5vwvw.png

console screenshot :  https://i.imgur.com/VibIQbI.png

filter lists used:
https://i.imgur.com/qYP8xm5.png part 1
https://i.imgur.com/8JLahFK.png part 2

**Comment by jspenguin2017** [comment]
@okiehsch I'm not sure why but it's harder to reproduce with uBO default, but I did get it to reproduce once, do you want to try?

**Comment by okiehsch** [comment]
Hm, the only way to reproduce "something interfered with this website" nonsense is to block `adiode.com`, which is not the case with a uBO-default setup as far as I know.

The inline-script pushes ads on my end, so I will add
`trakt.tv##script:inject(abort-on-property-write.js, adonisHash)`
to uBO-filters.

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/56ef26de3d39cf49d98ffa2ce2f5a26de86fceac
