### ISSUE TITLE
earn-guide.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#829]
### Test link (required): 
http://earn-guide.com/CKWATCHESPNWITHEXTRA

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-01-27_101407](https://user-images.githubusercontent.com/2828165/35470071-f3ad01bc-034a-11e8-8449-6c240e1c5a03.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-01-27_101435](https://user-images.githubusercontent.com/2828165/35470074-ff3210fe-034a-11e8-9b46-9f8ac62df600.png)

### Environment (Required): 
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome 63.0.3239.132 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.28+Nano Defender 13.27

#### Your filter lists (Required): 
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
**Ads (2)**
Adblock Warning Removal List​
EasyList
**Privacy (1)**
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
**Regions, languages (4)**
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

#### Your custom filters (Required if you have any): 
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment]
This just keeps coming... @mapx-

**Comment by ghajini** [comment]
@jspenguin2017 
more and more sites bypassing timer ....
`https://github.com/uBlockOrigin/uAssets/issues/2218`
many issues in uassets recently reported

**Comment by jspenguin2017** [comment]
@ghajini If the timer is validated on server side then it is not bypassable.
