### ISSUE TITLE
NSFW! hentaihaven.org

### ISSUE THREAD

**Issue by uravebear** [jspenguin2017/uBlockProtector#831]
### Test link (required): 
`http://hentaihaven.org/katainaka-ni-totsui-de-kita-russia-musume-to-h-shimakuru-ohanashi-episode-2/`

### Screenshot of the web page (including address bar and extension icons) (required): 

[Here](https://imgur.com/a/oGx9C) and [here](https://imgur.com/a/sc3CW)

### Screenshot of the console (press `F12` to bring up the console) (required): 

[Here](https://imgur.com/a/oTWr4) and [here](https://imgur.com/a/2lAN1)

### Explain what was not right (optional if obvious): 
It was working some time before and though the video can still be watched/downloaded, the layout is crap now and the Disqus comments is blocked. You can check out the original look of the page just by disabling the adblocker.

### Reproduction steps (optional if trivial): 
Simply visit the page

### Environment (Required): 

- Operating System and Version: macOS 10.13.3
- Browser and Version: Vivaldi 1.13.1008.44 Stable (Chromium)
- Adblocker and Version: uBlock Origin 1.14.24

#### Your filter lists (Required): 

[Here](https://imgur.com/a/UVRrt) and [here](https://imgur.com/a/5EN55)

#### Your custom filters (Required if you have any): 
Only the Nano Defender filters

### Add everything else that you believe to be useful below (optional): 
None.

**Comment by jspenguin2017** [comment]
I don't see the problem. Disqus works for me, I don't see anything wrong with the layout. It looks the same with and without adblocker.

**Comment by okiehsch** [comment]
EasyList blocks all third-party script requests to hentaihaven on my end, so disqus should be broken for you too.
I think allowing
````
@@||hentaihaven.disqus.com/embed.js$script,domain=hentaihaven.org
@@||disqus.com/next/config.js$script,domain=hentaihaven.org
````
should be sufficient, but I would need some feedback.

**Comment by uravebear** [comment]
Weird. Maybe because I use Vivaldi. I'll try to test on Chrome later when I get home.

**Comment by jspenguin2017** [comment]
I'll check tomorrow, maybe filters are not synced.

**Comment by uravebear** [comment]
Just tried it with Google Chrome with both uBlock and Nano Adblocker (default filters) and yes the layout didn't change but the download button and Disqus section are both blocked.

https://imgur.com/a/UpRMW

**Comment by jspenguin2017** [comment]
Yea, I can reproduce now.
