### ISSUE TITLE
fakt.pl

### ISSUE THREAD

**Issue by Tasiorsa** [jspenguin2017/uBlockProtector#832]
Nano Adblocker 1.0.0.28

### Test link (required): 
http://www.fakt.pl/

### Screenshot of the web page (including address bar and extension icons) (required): 

http://i64.tinypic.com/dyrms9.png

### Screenshot of the console (press `F12` to bring up the console) (required): 

http://i66.tinypic.com/124iic2.png

### Explain what was not right (optional if obvious): 
Adblock Detected

### Environment (Required): 

- Operating System and Version: Win 7 Pro x64
- Browser and Version:  Firefox 58.0
- Adblocker and Version: Nano Adblocker 1.0.0.28 + Nano Defender 13.28

#### Your filter lists (Required): 
 Default + Polish Filters

**Comment by Tasiorsa** [comment]
f12 better screenshot
http://i66.tinypic.com/124iic2.png

**Comment by jspenguin2017** [comment]
Try `fakt.pl##^#adsinit`

**Comment by Tasiorsa** [comment]
Works fine with fakt.pl##^#adsinit
Please add to filters!
Thanks!

**Comment by jspenguin2017** [comment]
@okiehsch Can you reproduce for Chrome?

**Comment by okiehsch** [comment]
No, I can't reproduce the anti-adblock message with Chrome or Firefox, though I can see the inline-script that you disable with `fakt.pl##^#adsinit`.
