### ISSUE TITLE
updato.com

### ISSUE THREAD

**Issue by Zelda189** [jspenguin2017/uBlockProtector#833]
### Test link (required): 

`https://updato.com/how-to/fix-android-phone-thats-freezing`

### Screenshot of the web page (including address bar and extension icons) (required): 
![screenshot 356](https://user-images.githubusercontent.com/31845382/35577137-bcc59df2-061b-11e8-8157-4452e3a3dcd3.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![screenshot 360](https://user-images.githubusercontent.com/31845382/35577335-420a22b2-061c-11e8-919e-f571175a3b8d.png)

### Environment (Required): 

- Operating System and Version: Windows 10 Pro Version 1709 64-bit
- Browser and Version: Google Chrome Version 64.0.3282.119 (Official Build) (64-bit)
- Adblocker and Version: uBlock Origin Version 1.14.24 + Nano Defender Version 13.28

#### Your filter lists (Required): 
![screenshot 362](https://user-images.githubusercontent.com/31845382/35577694-18e4ee2a-061d-11e8-8c92-53d1dbcf6e13.png)

![screenshot 365](https://user-images.githubusercontent.com/31845382/35577783-46ee171a-061d-11e8-94fa-74b8d7168daf.png)

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Done.

**Comment by Zelda189** [comment]
It works! Sould be fixed now.
