### ISSUE TITLE
webnovel.com

### ISSUE THREAD

**Issue by KiraYamatoSD** [jspenguin2017/uBlockProtector#836]
webnovel.com had changed their method to show locked chapters.

**Comment by jspenguin2017** [comment]
Test link?

**Comment by KiraYamatoSD** [comment]
Test link: https://www.webnovel.com/book/7141974606000205/25249393678547883/MMORPG%3A-Rebirth-of-the-Legendary-Guardian/A-Decisive-Battle-with-the-Ghost-Dragon

**Comment by jspenguin2017** [comment]
Old solution moved to debug mode. 

https://forum.novelupdates.com/threads/qidian-adblock.43828/page-7
The new system isn't ad wall, even if there is a solution I won't fix it here.
