### ISSUE TITLE
funnygames.*

### ISSUE THREAD

**Issue by SkeletalDemise** [jspenguin2017/uBlockProtector#837]
### Test link (required): 
`http://www.funnygames.biz/game/stick_figure_badminton_2.html`
`http://www.funnygames.org/game/stick_figure_badminton_2.html`

### Screenshot of the web page (including address bar and extension icons) (required): 
![funnygames anti-adblock](https://user-images.githubusercontent.com/29117662/35763414-b0f1e4a8-0860-11e8-893a-3ddfe9542850.PNG)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![funnygames console](https://user-images.githubusercontent.com/29117662/35763439-361710cc-0861-11e8-9918-0aca6926fbb3.PNG)

### Explain what was not right (optional if obvious): 
Anti-adblock messages.

### Environment (Required): 

- Operating System and Version: Windows 10 1709 (64-bit) 
- Browser and Version: Chrome 64.0.3282.140
- Adblocker and Version: Nano Adblocker 1.0.0.28

#### Your filter lists (Required): 
Default.

### Add everything else that you believe to be useful below (optional): 
There's a dozen of these FunnyGames domains, and they are identical. For example, there's funnygames.org, funnygames.us, funnygames.dk, etc.

**Comment by jspenguin2017** [comment]
I think the domains needs to be all listed...

**Comment by SkeletalDemise** [comment]
Couldn't you do `/placeholders/adblocker$image,domain=funnygames.*`?

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/35763566-5820d58a-086c-11e8-82cb-23348b14ac06.png)

**Comment by SkeletalDemise** [comment]
Huh, so you can't use wildcards in `domain=`?

**Comment by jspenguin2017** [comment]
Nope.

**Comment by SkeletalDemise** [comment]
Is there a better way to do this, then getting all the domains and doing `domain=`?

**Comment by jspenguin2017** [comment]
I'll look for it.

**Comment by jspenguin2017** [comment]
Hum, not ideal but since we need the wildcard...
