### ISSUE TITLE
chase.com

### ISSUE THREAD

**Issue by sabbsol** [jspenguin2017/uBlockProtector#838]
### Test link (required): 
https://www.chase.com/personal/credit-cards/ultimate-rewards#

### Screenshot of the web page (including address bar and extension icons) (required): 

![image](https://user-images.githubusercontent.com/36110198/35769564-d1a7ed86-0915-11e8-9f6a-474a873745e6.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![image](https://user-images.githubusercontent.com/36110198/35769587-f1e9445a-0915-11e8-8a00-55c05cd064ed.png)

### Explain what was not right (optional if obvious): 

Can't sign in
### Environment (Required): 

- Operating System and Version:  Win10 1709
- Browser and Version: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- Adblocker and Version: uBlock Origin v1.14.24

#### Your filter lists (Required): 

Ublock Filters
Ublock Badware Risks
Adblock Warning Removal List​​​​​394 used out of 399​​​​
EasyList​​​​​77,748 used out of 77,995​​​​
EasyPrivacy​​​​​14,031 used out of 14,190​​​​
Malware Domain List​​​​​1,130 used out of 1,146​​​​
Malware domains​​​​​16,044 used out of 16,045​​​​
Peter Lowe’s Ad and tracking server list​​​​​2,577 used out of 2,581​​​​
EasyList Hebrew
#### Your custom filters (Required if you have any): 
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​​​​37 used out of 37​​​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt​​​​​199 used out of 296​​​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt​​​​​140 used out of 140​​​​
https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​​​​0 used out of 0​​​​
uBlock Protector List​​​​​​​​​ (disabled)

### Add everything else that you believe to be useful below (optional): 
Site works in incognito window

**Comment by jspenguin2017** [comment]
I'm not sure what do you mean by can't sign in, the sign in button works for me, but I don't have an account so I can't test more.

**Comment by sabbsol** [comment]
Hi,

Thanks for the quick response.  The sign in button doesn't do anything -
see the console messages below:

[image: Inline image 2]


--
Edwin Shalom Slonim, eslonim@minols.com
 Ltd
44 Moriah Blvd, PO Box 7360, Haifa 3107202 Israel
ph: +972-4-826-6583 fax:+972-4-834-7071
cell: +972-52-282-1906
USA: +1(718)715-0581

**Comment by jspenguin2017** [comment]
The button works for me, although obviously I don't have an account. Do not reply through email, come to GitHub site and reply, I can't see attachments. 
![image](https://user-images.githubusercontent.com/7283682/35770185-c4368726-08d3-11e8-8f62-4280f43ba3ec.png)

**Comment by sabbsol** [comment]
Here are the console messages indicating the problem - 
![image](https://user-images.githubusercontent.com/36110198/35770246-64e62662-0920-11e8-9311-554f8febd7a9.png)

**Comment by sabbsol** [comment]
Sign in button doesn't do anything obvious except generate the above console messages

**Comment by jspenguin2017** [comment]
Can't reproduce.
