### ISSUE TITLE
videolab.io

### ISSUE THREAD

**Issue by coachq127** [jspenguin2017/uBlockProtector#839]
### Test link (required): 
http://videolab.io/ws/2/videolab/index/84t284z2p294t3v23394u2d254v2u2u2k2z2w254r2f4r23313/i5r2f59484/http%3A%2F%2Fvideolab.io%2Fws%2F2%2Fvideolab%2Fclick%2F526517%252F4952%252Fi5r2f59484%252F3543%252Fweb%252F5%252Fy%252F%253Frq%253DVWF%253D4/1%20MINUTE?isAutoRedirect=1#

### Screenshot of the web page (including address bar and extension icons) (required): 

http://prntscr.com/i9n4e6

### Screenshot of the console (press `F12` to bring up the console) (required): 

http://prntscr.com/i9n4mc

### Explain what was not right (optional if obvious): 
When you click play it detects adblock.  Also detects popup blocker.

### Reproduction steps (optional if trivial): 
When you click play it detects adblock.  Also detects popup blocker.

### Environment (Required): 

- Operating System and Version: Windows 10
- Browser and Version: Chrome
- Adblocker and Version: Latest Nano Adblocker

#### Your filter lists (Required): 

all of the default ones enabled

#### Your custom filters (Required if you have any): 
none

### Add everything else that you believe to be useful below (optional): 
I'm hoping to have the timer skipped as well if possible,  thanks!

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/35770083-6110054c-08d2-11e8-81c4-f9385b6cd891.png)
![image](https://user-images.githubusercontent.com/7283682/35770126-cdc0c0b4-08d2-11e8-9fa0-adfb3825ee6f.png)

**Comment by coachq127** [comment]
It's most likely due to the ip difference or you're on a vpn.  This site only allows real ips.

**Comment by jspenguin2017** [comment]
OK, it works with US VPN.
