### ISSUE TITLE
engageme.tv

### ISSUE THREAD

**Issue by coachq127** [jspenguin2017/uBlockProtector#840]
### Test link (required): 
http://engageme.tv/watchscience.php?click=109689_1380575734&prof=8571&pub=109689&sub1=EARNGG-5de25a0c-b960-46c7-b8f8-af50a849c2f7&sub3=

### Screenshot of the web page (including address bar and extension icons) (required): 

http://prntscr.com/i9pxex

### Screenshot of the console (press `F12` to bring up the console) (required): 

http://prntscr.com/i9pxmx

### Explain what was not right (optional if obvious): 
It detects adblock,  also it needs to think that 3 ads were watched when they weren't.

### Reproduction steps (optional if trivial): 
Simply opening the page on a USA semi-legit looking ip works to bring up the no adblocker error.

### Environment (Required): 

- Operating System and Version: Windows 10
- Browser and Version: Latest Chrome
- Adblocker and Version: Latest Nano Adblocker,  disabled temp to show what the page is supposed to look like.

#### Your filter lists (Required): 

all default ones

#### Your custom filters (Required if you have any): 
none

### Add everything else that you believe to be useful below (optional): 

I'd like this site to think that ads were watched when they weren't if possible.  Thanks!

**Comment by jspenguin2017** [comment]
@okiehsch 
Suspecious code: 
```js
if(!document.getElementById('gmZYoNEjyqnb')){
  //document.getElementById('hoifbvQmwCyS').style.display='block';
  window.stop();
  document.execCommand('Stop');
  window.top.location.href = "adblock.php?link=/watchscience.php";
}
var ints = setInterval(function() {
 var adb = $.get("js/ads.js");
  adb.fail(failure);
}, 40000);
var adb = $.get("js/ads.js");
function failure (){
    //document.getElementById('hoifbvQmwCyS').style.display='block';
    $("body *").not("#hoifbvQmwCyS").remove();
    window.stop();
    document.execCommand('Stop');
	window.top.location.href = "adblock.php?link=/watchscience.php";
}
```

**Comment by coachq127** [comment]
Thanks for finding that!  Good luck!  Really hoping this can be done!

**Comment by okiehsch** [comment]
`engageme.tv##script:inject(abort-current-inline-script.js, stop, adblock)`
works on my end.

**Comment by coachq127** [comment]
the above works to bypass the anti-adblock,  but still hoping to make it think I watched videos when I didn't.  Thanks!

**Comment by okiehsch** [comment]
What do you mean by 

> hoping to make it think I watched videos when I didn't. 

If I go to `http://engageme.tv/watchscience.php` this is what I get.

![unbenant](https://user-images.githubusercontent.com/16838044/35772359-effe7710-093c-11e8-8ccd-99426692b520.JPG)

**Comment by coachq127** [comment]
Essentially it's a site that pays you whenever an ad plays,  hoping to bypass it.

**Comment by jspenguin2017** [comment]
I'll mark these sites as won't fix, because they will most likely check on server side if the advertiser registered the view.

**Comment by okiehsch** [comment]
I will add the anti-adblock fix.

**Comment by jspenguin2017** [comment]
Yea, I'd say remove aggressive anti-adblock notice, but I won't try to fix more as I'm 99% sure they'll validate on server side.
