### ISSUE TITLE
explore10.com

### ISSUE THREAD

**Issue by coachq127** [jspenguin2017/uBlockProtector#841]
### Test link (required): 
https://explore10.com/slideshow/offer?id=27d0f9f0-4ff4-42a6-ba97-73c7921c063e&pid=RadiumOne&sid=16348773852674

### Screenshot of the web page (including address bar and extension icons) (required): 

http://prntscr.com/i9qglj

### Screenshot of the console (press `F12` to bring up the console) (required): 

http://prntscr.com/i9qhem

### Explain what was not right (optional if obvious): 

Timer not skipped.
### Reproduction steps (optional if trivial): 
Just clicking start while on a USA ip starts it,  but there's a timer which needs to be skipped.

### Environment (Required): 

- Operating System and Version: Windows 10
- Browser and Version: Latest Chrome
- Adblocker and Version: Latest Nano Adblocker+Nano Defender

#### Your filter lists (Required): 

all default

#### Your custom filters (Required if you have any): 

N/A
### Add everything else that you believe to be useful below (optional): 
N/A

**Comment by jspenguin2017** [comment]
I suspect that they validates it on serve side. Does this work? 
```
explore10.com##script:inject(nano-setInterval-booster.js, /.?/, 100)
```

**Comment by coachq127** [comment]
it ruturns "Uncaught SyntaxError: Invalid or unexpected token" when I put that into console,  thanks regardless!

**Comment by jspenguin2017** [comment]
It's a filter, add to your filter list.

**Comment by coachq127** [comment]
appears to work!  Thanks!
