### ISSUE TITLE
video.younghollywoodtv.com

### ISSUE THREAD

**Issue by coachq127** [jspenguin2017/uBlockProtector#842]
### Test link (required): 
http://video.younghollywoodtv.com/promo/qynKdM5OVOeui3W0/?tid=5a7638a6809c25c358416fdf$110068390$vkxYWcVaKlncIMTX8kUjrQ&euid=5a70fa3c809c25c358af919c$110068376$gMIXYOTo8YA4hDZIB8Kvrw&hasRedesign=null&urrMet=null&rock=%7B%22fid%22%3A%22540f52347591fdc43a8b4567%22%2C%22puid%22%3A%22gavinshreds3%22%7D&paper=r08F113w_gESIbHbCX93smuJXcP8jxzrPUlS9xwtlWubSsckBo-CpjOGpQuV7KbXKZ_vVQeTzHPzHYnIFxDe447Ydrv8pM6jqcotBo9ElmeaBBAc44cPmC3MB9cAcZia97dBYCNAfsTlutEm41zmvj8GVdmlW-UJ7yxfDyqa0DWJe2W5SZ6MgTgr97Tiqx6yKtji9cStFQZ_-L64ffVmxW9-q3Iz9Bmsn8Yq95Osndk3GrZvYqTb4213NBfGpBnPv20JOI-eXjeOkO92JMgLTuo2a9dCkQFVbOzLmU5ogZ9mC9lVCxI6Dw&encl=1133431162&utm_source=instagc&utm_medium=iframe#

### Screenshot of the web page (including address bar and extension icons) (required): 

http://prntscr.com/i9r2wk

### Screenshot of the console (press `F12` to bring up the console) (required): 

http://prntscr.com/i9r32j

### Explain what was not right (optional if obvious): 

Timer needs bypassed please.
### Reproduction steps (optional if trivial): 
Simply click "start earning" and there's a timer I'd like bypassed if possible,  thanks!

### Environment (Required): 

- Operating System and Version: Windows 10
- Browser and Version: Latest Chrome
- Adblocker and Version: Latest Nano Defender+Nano Adblocker

#### Your filter lists (Required): 

default

#### Your custom filters (Required if you have any): 
http://video.younghollywoodtv.com##script:inject(nano-setInterval-booster.js, /.?/, 100)
(Doesn't work)

**Comment by jspenguin2017** [comment]
Seems to be a private link.

**Comment by coachq127** [comment]
Oh,  weird,  I can let you teamviewer into my pc if you want.
