### ISSUE TITLE
gmenhq.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#846]
### Test link (required): 
https://gmenhq.com/

### Screenshot of the console (press `F12` to bring up the console) (required): 
![capture](https://user-images.githubusercontent.com/15007183/35941265-b17d5d40-0c1f-11e8-97c3-67184dbfd961.PNG)

### Environment (Required): 

- Operating System and Version: win7pro
- Browser and Version: Version 64.0.3282.140 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.14.24

#### Your filter lists (Required): 
reg ubo + pl filters

**Comment by jspenguin2017** [comment]
@okiehsch
