### ISSUE TITLE
nmn900.com

### ISSUE THREAD

**Issue by autoestopista** [jspenguin2017/uBlockProtector#847]
### Test link (required): 

http://www.nmn900.com/

### Screenshot of the web page (including address bar and extension icons) (required): 

![image](https://user-images.githubusercontent.com/35890175/35984121-0617d806-0cf4-11e8-9ec8-9e707b3cc6b5.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

[Nano] Nano Defender Activated :: www.nmn900.com
adsbygoogle.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2pagead2.googlesyndication.com/pagead/js/adsbygoogle.js Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
32-content-core.js:60 [Nano] Nano Defender Activated :: www.nmn900.com
www.facebook.com/impression.php/f376d69d6b6947c/?api_key=244617828848&lid=115&payload=%7B%22source%22%3A%22jssdk%22%7D Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
2-content-core.js:60 [Nano] Nano Defender Activated :: www.nmn900.com
browser.js:60 Opera has modified script or content on staticxx.facebook.com (PATCH-1195, Facebook - block first character in the comment field from triggering a single key keyboard shortcut). See browser.js for details
2-content-core.js:60 [Nano] Nano Defender Activated :: staticxx.facebook.com
chrome-extension://ggolfgbegefeeoocgjbmkembbncoadlb/content/3-content-rules-1-common.js:53 [Nano] Excluded :: All Generically Applied Solutions
browser.js:60 Opera has modified script or content on staticxx.facebook.com (PATCH-1195, Facebook - block first character in the comment field from triggering a single key keyboard shortcut). See browser.js for details
2-content-core.js:60 [Nano] Nano Defender Activated :: staticxx.facebook.com
chrome-extension://ggolfgbegefeeoocgjbmkembbncoadlb/content/3-content-rules-1-common.js:53 [Nano] Excluded :: All Generically Applied Solutions
browser.js:60 Opera has modified script or content on www.facebook.com (PATCH-1195, Facebook - block first character in the comment field from triggering a single key keyboard shortcut). See browser.js for details
2-content-core.js:60 [Nano] Nano Defender Activated :: www.facebook.com
chrome-extension://ggolfgbegefeeoocgjbmkembbncoadlb/content/3-content-rules-1-common.js:53 [Nano] Excluded :: All Generically Applied Solutions
ping:1 No se puede cargar la URL: El dominio de esta URL no está incluido en los dominios de la aplicación. Para poder cargar esta URL, añade todos los dominios y subdominios de tu aplicación al campo de dominios de la aplicación en la configuración de tu aplicación.
browser.js:60 Opera has modified script or content on www.facebook.com (PATCH-1195, Facebook - block first character in the comment field from triggering a single key keyboard shortcut). See browser.js for details
2-content-core.js:60 [Nano] Nano Defender Activated :: www.facebook.com
chrome-extension://ggolfgbegefeeoocgjbmkembbncoadlb/content/3-content-rules-1-common.js:53 [Nano] Excluded :: All Generically Applied Solutions

### Environment (Required): 

Operating System and Version: Windows 10 Pro Version 1709
Browser and Version: Opera 51.0.2830.26 (PGO) (64-bit)
Adblocker and Version: Nano Adblocker Versión 1.0.0.29 + Nano Defender Versión 13.31

#### Your filter lists (Required): 

Default filters

**Comment by jspenguin2017** [comment]
@okiehsch Although it's not hard anti-adblock it's really aggressive, do you guys fix those ones as well or strictly only hard anti-adblock?

**Comment by okiehsch** [comment]
My rule of thumb is, do I think it is more than an annoyance, for example if I can click the message away
and it does not bother me after that, while I use the site, I categorize it as an annoyance.
This is clearly more than an annoyance in my opinion.
Fixed.
