### ISSUE TITLE
ally.sh

### ISSUE THREAD

**Issue by daxter19** [jspenguin2017/uBlockProtector#849]
### Test link (required): 
http://ally.sh/9KVt6

### Screenshot of the web page (including address bar and extension icons) (required): 
https://imgur.com/a/yjBJ8

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://imgur.com/a/vS0lb

### Explain what was not right (optional if obvious): 
I both installed Nano adblocker and nano defender, but i still got this message on ally.sh
i updated also the filters in nano adblocker

### Environment (Required): 

- Operating System and Version: windows 10 home 15063
- Browser and Version: Chrome Version 63.0.3239.132
- Adblocker and Version: Nano adblocker 1.0.0.29 and nano defender  13.31

#### Your filter lists (Required): 
all default filters

**Comment by jspenguin2017** [comment]
Can you update your filters? The fix might not be packaged. If that doesn't work, then chances are it's caused by your other extensions. 
It works for me.

**Comment by daxter19** [comment]
hmm i already updated the filters in the nano adblocker settings...

the only extension i have which is associated with ads is a popup blocker, i will try to uninstall it

**Comment by jspenguin2017** [comment]
You can troubleshoot the problem by disabling all other extensions and turn on one extension at a time to see which one is causing the issue.

**Comment by daxter19** [comment]
asd

**Comment by jspenguin2017** [comment]
Try a new browser profile? Maybe some flags are corrupted.

**Comment by daxter19** [comment]
already tried all browsers but was the same for all. 

but now i found the problem - it seems to be my hosts list.
if i delete my custom entries then it works.

but it will be a pain to find out which specific entry causes the problems with ally.sh ... :/
