### ISSUE TITLE
eurosport.*

### ISSUE THREAD

**Issue by DandelionSprout** [jspenguin2017/uBlockProtector#850]
### Test link (required): 
https://www.eurosport.com/curling/pyeongchang/2018/whoops-matt-hamilton-takes-a-tumble-on-the-ice_vid1045454/video.shtml

### Screenshot of the web page (including address bar and extension icons) (required): 
https://imgbox.com/d1913teQ

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://imgbox.com/zlHYax4D

### Environment (Required): 

- Operating System and Version: Windows 10 Pro 64-bit, 10.0.16299
- Browser and Version: Google Chrome 64-bit, 64.0.3282.140
- Adblocker and Version: uBlock Origin v1.15.2

#### Your filter lists (Required): 

• uBlock Filters
• uBlock Filters - Badware risks
• uBlock Filters - Resource abuse
• uBlock Filters - Unbreak
• Adblock Warning Removal List
• Adguard Mobile Filters
• Easylist
• Malvertising filter list by Disconnect
• Malware Domain List
• Malware domains
• Malware filter list by Disconnect
• Spam404
• Fanboy's Social Blocking List

#### Your custom filters (Required if you have any): 
• Nano Base
• Nano Whitelist
• GelboLube
• Gelbooru filters
• Dandelion Sprouts norske filtre for ryddigere nettsider (A Norwegian filter list)
• Ransomwaretracker RW DOMBL
• I don't care about cookies
• Malware domains (long-lived)
• Nano Defender Integration
• [My personalised cloud-shared filters
](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/a.txt)

### Add everything else that you believe to be useful below (optional): 
The problem also applies to all other Eurosport versions as well, such as Eurosport.no ( [Example URL](https://www.eurosport.no/fristil/pyeongchang/2018/falt-i-kvalifiseringen-en-nybegynnerfeil_sto6587517/story.shtml) ).

**Comment by lassekongo83** [comment]
A simple `@@||eurosport.com^$generichide` worked just fine for me.

**Comment by DandelionSprout** [comment]
I have every reason to assume that the $generichide solution(s) work as they should; so if I understand this repo's unspoken rules correctly, I can just as well close the issue now. 😃

**Comment by jspenguin2017** [comment]
@okiehsch There are regional domains, like `https://www.eurosport.no/fristil/pyeongchang/2018/falt-i-kvalifiseringen-en-nybegynnerfeil_sto6587517/story.shtml`

**Comment by okiehsch** [comment]
````
@@*$generichide,domain=eurosport.bg|eurosport.co.uk|eurosport.com|eurosport.cz|eurosport.de|eurosport.dk|eurosport.fi|eurosport.fr|eurosport.hu|eurosport.nl|eurosport.no|eurosport.pl|eurosport.pt|eurosport.ro|eurosport.rs|eurosport.ru|eurosport.se
````
If I missed one, let me know.

**Comment by SkeletalDemise** [comment]
Missed a few regional domains. Switzerland's domain: `eurosport.ch`. Spain's domain: `eurosport.es`. And Turkey's domain: `eurosport.com.tr`.
