### ISSUE TITLE
anghami.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#853]
### Test link (required): 
https://play.anghami.com/song/27844127

### Screenshot of the web page (including address bar and extension icons) (required): 
![bbbbb](https://user-images.githubusercontent.com/2828165/36045711-4acefad8-0ddf-11e8-8497-4ddbda3d3173.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![bbbbbbb22](https://user-images.githubusercontent.com/2828165/36045721-55b72984-0ddf-11e8-93dc-1be0c2bad826.png)

### Environment (Required): 

Environment (Required):
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome  64.0.3282.140 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.29+Nano Defender 13.31

**#### Your filter lists (Required):** 
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
**Ads (2)**
Adblock Warning Removal List​
EasyList
**Privacy (1)**
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
**Regions, languages (4)**
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

**Your custom filters (Required if you have any):**
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment]
Maybe requires account. 
@okiehsch

**Comment by okiehsch** [comment]
Does
````
@@||anghamiwebcdn.akamaized.net/ads.$script,domain=play.anghami.com
@@||d24n15hnbwhuhn.cloudfront.net/libs/amplitude-$script,domain=play.anghami.com
````
work?

**Comment by Ravizz** [comment]
It does for me.

**Comment by jspenguin2017** [comment]
The question is does that unblock real ads...

**Comment by titosalah** [comment]
@jspenguin2017  account 
username:hamasha@gmail.com
Password:yamaan177

**Comment by jspenguin2017** [comment]
@titosalah Recorded. Can you send test account to https://jspenguin.com/PrivateMessage/ next time?

**Comment by jspenguin2017** [comment]
@okiehsch This works, tested: 
```
play.anghami.com##.sideBox:has(.adsbox)
@@||anghamiwebcdn.akamaized.net/ads.$script,domain=play.anghami.com
@@||d24n15hnbwhuhn.cloudfront.net/libs/amplitude-$script,domain=play.anghami.com
```
