### ISSUE TITLE
sport.tvp.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#855]
### Test link (required): 

http://sport.tvp.pl/igrzyska/35828253/pjongczang-2018-curling-mix-kanada-szwajcaria

### Screenshot of the console (press `F12` to bring up the console) (required): 
![capture](https://user-images.githubusercontent.com/15007183/36056326-96e972ee-0dd1-11e8-8fef-157bd3b0b30c.PNG)

### Explain what was not right (optional if obvious): 
It looks like you're using an add-on for your browser that blocks our ads.
To be able to watch live broadcasts from the Pjongchang 2018 Olympics, please turn it off.
Thank you!
Editors of Sport TVP

### Reproduction steps (optional if trivial): 
go to http://sport.tvp.pl/igrzyska/transmisje
press on red button **Ogladaj Online** 
### Environment (Required): 

- Operating System and Version: win7pro
- Browser and Version: Chrome Version 64.0.3282.140 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.15.2

#### Your filter lists (Required): 
reg ubo + pl filters

### Add everything else that you believe to be useful below (optional): 
maybe geo block for some

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
I am geo-blocked, so no fix from me.

**Comment by Ravizz** [comment]
Can't reproduce on F 58.0.2 & O 51.0
