### ISSUE TITLE
hiapphere.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#856]
### Test link (required): 
http://m.hiapphere.com/down/rom-manager-premium

### Screenshot of the web page (including address bar and extension icons) (required): 
![6666666](https://user-images.githubusercontent.com/2828165/36059972-107821b6-0e48-11e8-91e2-e35634ee1909.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![88888888453](https://user-images.githubusercontent.com/2828165/36059975-1b6a5d5a-0e48-11e8-87cb-816920085e24.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome 64.0.3282.140 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.29+Nano Defender 13.31

**#### Your filter lists (Required):**
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Ads (2)
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
Regions, languages (4)
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

**Your custom filters (Required if you have any):**
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
