### ISSUE TITLE
dl.go4up.com

### ISSUE THREAD

**Issue by dragonwarlord1902** [jspenguin2017/uBlockProtector#857]
### Test link (required): 

http://dl.go4up.com//dl/1840e6114a1390

### Screenshot of the web page (including address bar and extension icons) (required): 

https://imgur.com/a/OtO8i

### Screenshot of the console (press `F12` to bring up the console) (required): 

https://imgur.com/a/uGiqe

### Explain what was not right (optional if obvious): 
adblock detection and not loading the links

### Reproduction steps (optional if trivial): 
 just go to http://dl.go4up.com//dl/1840e6114a1390 with an enabled nano adblocker

### Environment (Required): 

- Operating System and Version: windows 10 - 1709 in an vm
- Browser and Version: chrome canary 66.0.3342.0
- Adblocker and Version: Nano Adblocker 1.0.0.29

#### Your filter lists (Required): 

Everthing by the filters except by the Region/language section -nothing selected

Nano Defender Integration​​​​​2.716 used 2.754​​​​
Nano filters​​​​​42 used 43​​​​
Nano filters – Annoyance​​​​​10 used 10​​​​
Nano filters – Timer bypassing (sometimes works)​​​​​2 used 142​​​​
Nano filters – Whitelist​​​​​1 used 1​​​​
uBlock filters​​​​​3.951 used 3.954​​​​
uBlock filters – Annoyances​​​​​42 used 42​​​​
uBlock filters – Badware risks​​​​​7 used 7​​​​
uBlock filters – Experimental​​​​​6 used 6​​​​
uBlock filters – Privacy​​​​​65 used 65​​​​
uBlock filters – Resource abuse​​​​​193 used 195​​​​
uBlock filters – Unbreak​​​​​286 used 286​​​​

Adblock Warning Removal List​​​​​378 used 399​​​​
Adguard Base Filters​​​​​13.305 used 14.046​​​​
Adguard Mobile Filters​​​​​1.481 used 1.982​​​​
EasyList​​​​​79.284 used 79.950​​​​

Adguard Spyware Filters​​​​​2.328 used 6.140​​​​
EasyPrivacy​​​​​12.830 used 14.216​​​​
Fanboy’s Enhanced Tracking List​​​​​2.314 used 2.375​​​​
Domains mit Schadsoftware (5)
Malvertising filter list by Disconnect​​​​​251 used 4.596​​​​
Malware Domain List​​​​​1.129 used 1.146​​​​
Malware domains​​​​​15.028 used 15.040​​​​
Malware filter list by Disconnect​​​​​170 used 1.860​​​​
Spam404​​​​​6.277 used 6.277​​​​

Adguard’s Annoyance List​​​​​8.528 used 10.372​​​​
Fanboy’s Annoyance List​​​​​8.828 used 35.053​​​​
Fanboy’s Anti-Thirdparty Social (see warning inside list)​​​​​68 used 68​​​​
Fanboy’s Cookiemonster List​​​​​8.446 used 8.454​​​​
Fanboy’s Social Blocking List​​​​​17.744 used 17.771​​​​

Dan Pollock’s hosts file​​​​​9.534 used 13.273​​​​
hpHosts’ Ad and tracking servers​​​​​43.434 used 47.563​​​​
MVPS HOSTS​​​​​12.329 used 12.835​​​​
NoCoin Filter List​​​​​163 used 251​​​​
Peter Lowe’s Ad and tracking server list

#### Your custom filters (Required if you have any): 
 
Nothing

### Add everything else that you believe to be useful below (optional): 

The blocking script:
``
```
$(document).ready(function() {
        function loadlinks(){
            $.ajax(
                {
                   url: "/download/gethosts/1840e6114a1390/TEST.txt"
                    type: "GET",
                    success: function(response)
                    {
                        var jsonParsed = $.parseJSON(response);
                        var statusInformer;
                        var refresh = false;

                        if($("#loading").length)
                            $("#linklist").empty();

                        $.each(jsonParsed, function(i, host) {
                            statusInformer = '';
                            if(host.refresh == true)
                                refresh = true;
                            if(i == 'error'){
                                $("#linklist").append('<div class="row-fluid" style="margin-left: 0">'+host+'</div>');
                            } else {
                                if (host.status == 'checking') {
                                    statusInformer = '<span class="span2 label label-block label-waiting" style="min-    height:20px;" id="host_' + host.hostId + '">Checking</span>';
                                    checklink(host.hostId, 'e5d74aeb5e335a');
                                }
                                else {

                                    if (host.status == 'dead')
                                        statusInformer = '<span class="span2 label label-block label-warning" style="min-height:20px;" data-toggle="tooltip" data-placement="top" data-original-title="Updated at : ' + host.updated_at + '" id="host_' + host.hostId + '">Dead</span>';

                                    else if (host.status == 'ok')
                                        statusInformer = '<span class="span2 label label-block label-Fixed" style="min-height:20px;" data-toggle="tooltip" data-placement="top" data-original-title="Updated at : ' + host.updated_at + '" id="host_' + host.hostId + '">Alive</span>';
                                }

                                if ($("#download_line_" + host.hostId).length)
                                    $("#download_line_" + host.hostId).empty().append('<div class="span2"><img src="/assets/img/host/' + host.hostId + '.png" style="max-width: 100%;"></div><div class="span8" style="text-align:center;margin-top:8px;">' + statusInformer + host.link + '</div><div class="span2" style="text-align:center;">' + host.button + '</div>');
                                else {
                                    $("#linklist").append('<div class="row-fluid" style="margin-left: 0" id="download_line_' + host.hostId + '"><div class="span2"><img src="/assets/img/host/' + host.hostId + '.png" style="max-width: 100%;"></div><div class="span8" style="text-align:center;margin-top:8px;">' + statusInformer + host.link + '</div><div class="span2" style="text-align:center;">' + host.button + '</div></div>');
                                }
                            }
                            $("#host_"+host.hostId).tooltip();
                        });

                        if (refresh == true)
                            setTimeout(function () {loadlinks();},5000);
                    },
                });
        }
        if(document.getElementById('MjGBfOxwpNTH')){
            setTimeout(function () {loadlinks();},4000);
        } else {
            $("#linklist").empty();
            $("#linklist").append('<div style="color:red;font-weight:bold;">\n' +
                '  Our website is made possible by displaying online advertisements to our visitors.<br>\n' +
                '  Please consider supporting us by disabling your ad blocker.\n' +
                '</div>');
            if(typeof ga !=='undefined'){
                ga('send','event','Blocking Ads','true',{'nonInteraction':1});
            } else if(typeof _gaq !=='undefined'){
                _gaq.push(['_trackEvent','Blocking Ads','true',undefined,undefined,true]);
            }
        }

    });
    function checklink(hostId, fileId ){
        $.ajax(
            {
                url: "http://lc.go4up.com/linkCheck/process/"+hostId+"/"+fileId,
                type: "GET",
                crossDomain:true,
                success: function(response)
                {
                    var check = $.parseJSON(response);

                    if(check.status == true)
                        $('#host_'+hostId).removeClass('label-waiting').addClass('label-Fixed').empty().append('Alive');
                    else
                        $('#host_'+hostId).removeClass('label-waiting').addClass('label-warning').empty().append('Dead');
                }
            });
    }
```

It`s a adaptation from -  https://github.com/InteractiveAdvertisingBureau/AdBlockDetection
It uses the same function -  document.getElementById (xxxxx)

best regards 
dragonwarlord

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.

**Comment by dragonwarlord1902** [comment]
@okiehsch
the webside owner want t play - he altered his script from ads to gads
Her is the fix - +@@||dl.go4up.com/gads.js$script,first-party
