### ISSUE TITLE
salon.com

### ISSUE THREAD

**Issue by Hikari-chin** [jspenguin2017/uBlockProtector#858]
### Test link (required): 
https://www.salon.com

### Screenshot of the web page (including address bar and extension icons) (required): 
https://i.lolis.stream/uploads/big/adc86ca58b8f8dd0a6aac0c928e63ca2.png

### Screenshot of the console (press `F12` to bring up the console) (required): 

https://i.lolis.stream/uploads/big/e66847d9e4dcbfbbe8e725d7d03279a9.png

### Explain what was not right (optional if obvious): 
Adblock Warning Popup, asks to either disable your blocker or allow cryptocurrency mining, also puts a white filter over everything and disables scrolling (so simply blocking the pop up and filter element is not sufficient to restore functionality)

### Reproduction steps (optional if trivial): 
Simply load the URL.

### Environment (Required): 

1 **Operating System and Version:** Windows 10 FCU build 16299
2. **Browser and Version:** Chrome v66.0.3346.0 (Official Build) canary (64-bit)
3. **Adblocker and Version:** uBlock Origin v1.15.2 w/ NanoDefender lists/[resources](https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoResources.txt)/etc. 

#### Your filter lists (Required): 
1. uBlock filters
2. uBlock filters – Badware risks​​​​​
3. uBlock filters - Privacy
3. uBlock filters - Resource abuse
4. uBlock filters - Unbreak
5. Adblock Warning Removal List
6. EasyList
7. EasyPrivacy
8. Malware Domain List
9. Malware domains
10. Peter Lowe's Ad and tracking server list
11. JPN: ABP Japanese filters (日本用フィルタ)
12. JPN: Adguard Japan Filter

#### Your custom filters (Required if you have any): 
1. https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoBase.txt
2. https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoDefender.txt
3. https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoWhitelist.txt

**Comment by jspenguin2017** [comment]
`@@||salon.com/js/ad-server.js$script,first-party`
@okiehsch

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/blob/322eee9a8a6189569c335ef1c8081dabbfca9afa/filters/filters.txt#L5041

**Comment by nanorocks1** [comment]
Hi,

I am still seeing the issue this morning. Is there something I have to do like adding a filter etc? This is on chrome.

**Comment by jspenguin2017** [comment]
Try updating your filters.
