### ISSUE TITLE
change information

### ISSUE THREAD

**Issue by KonoromiHimaries** [jspenguin2017/uBlockProtector#860]
https://gitlab.com/xuhaiyang1234/AAK-Cont#aak-cont-is-a-semi-automated-compatibility-shim-for-ublock-protector

i think you can actualize information about `uBlock Protector` and `AdBlock Protector 2` to `Nano Defender`

**Comment by jspenguin2017** [comment]
The repository is archived, which indicate that it is abandoned and information there can be outdated.

**Comment by jspenguin2017** [comment]
Actually I did put up an update.
