### ISSUE TITLE
xumo.tv

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#864]
### Test link (required): 
https://www.xumo.tv/channel/9999207/popular-science

### Screenshot of the console (press `F12` to bring up the console) (required): 
![capture](https://user-images.githubusercontent.com/15007183/36649909-6b4b2a8e-1a6e-11e8-8751-6592d24383e1.PNG)

### Explain what was not right (optional if obvious): 
channel doesn't play

### Reproduction steps (optional if trivial): 
goto www.xumo.tv pick a channel to play

### Environment (Required): 

- Operating System and Version:  win7pro
- Browser and Version: Chrome Version 64.0.3282.167 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.15.2

#### Your filter lists (Required): 
standard ubo filters

#### Your custom filters (Required if you have any): 
2 pl filters

**Comment by jspenguin2017** [comment]
Does it normally play?

**Comment by xxcriticxx** [comment]
I just found website today plays on my phone fine with out any blockers

**Comment by zaphodbeebblebrox** [comment]
If it means anything, the video plays just fine for me with Nano Adblocker 1.0.0.38 + nanoDefender with default lists + nano defender integration on Chrome 65.0.3325.181 (Official Build) (64-bit) with a U.S. IP.

**Comment by xxcriticxx** [comment]
i confirm this is working right now
