### ISSUE TITLE
clix4btc.com

### ISSUE THREAD

**Issue by thienha1** [jspenguin2017/uBlockProtector#865]
### Test link (required): 
http://www.clix4btc.com

### Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/BpLFwXA.jpg

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/BpLFwXA.jpg

### Environment (Required): 

- Operating System and Version: Window 10 Pro
- Browser and Version: Chrome 64.0.3282.167
- Adblocker and Version: Ublock Origin 1.15.2

#### Your filter lists (Required): 
https://i.imgur.com/sB62FYx.png

**Comment by jspenguin2017** [comment]
@okiehsch
`@@||clix4btc.com/ads.js$script,first-party`
