### ISSUE TITLE
mtv.fi

### ISSUE THREAD

**Issue by Ollifi** [jspenguin2017/uBlockProtector#866]
### Test link (required): 
https://www.mtv.fi/lifestyle/autot/artikkeli/suomeen-vyoryvat-siperian-pakkaset-vaikuttavat-myos-autoihin-kannattaa-miettia-onko-kaynnistaminen-jarkevaa/6786448

### Explain what was not right (optional if obvious): 
Video does not play

### Add everything else that you believe to be useful below (optional): 

Please change filter
@@||damoh.$media
to
@@||damoh.$media,domain=mtv.fi
This fixes the issue.

**Comment by Ollifi** [comment]
Hi, unfortunately your fix didn't fix this issue. Could you try the fix I suggested in the first post? I tried, and it works.

**Comment by jspenguin2017** [comment]
> Could you try the fix I suggested in the first post?

No, that whitelists ads.

**Comment by jspenguin2017** [comment]
Video plays fine for me: 
![image](https://user-images.githubusercontent.com/7283682/38442804-bf5cf8e4-39a6-11e8-9dfe-d4428495482a.png)
