### ISSUE TITLE
ethereum.cpucap.com

### ISSUE THREAD

**Issue by thienha1** [jspenguin2017/uBlockProtector#867]
### Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/5sdpgkt.png

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/5sdpgkt.png

### Environment (Required): 

- Operating System and Version: Windows 10 Pro
- Browser and Version: 64.0.3282.186
- Adblocker and Version: uBlock Origin 1.15.2

#### Your filter lists (Required): 
https://i.imgur.com/82apsNV.png

**Comment by jspenguin2017** [comment]
Looks like this is addressed in uAssets.
