### ISSUE TITLE
freeopenvpn.org

### ISSUE THREAD

**Issue by ExtendLord** [jspenguin2017/uBlockProtector#868]
### Test link (required): 
https://www.freeopenvpn.org/en/logpass/russia.php

### Screenshot of the web page (including address bar and extension icons) (required): 
![image](https://user-images.githubusercontent.com/26222159/36728659-3169b72e-1bca-11e8-9a1d-742dce6f5e15.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![image](https://user-images.githubusercontent.com/26222159/36728669-3cd74c52-1bca-11e8-9203-73b3add144a7.png)

### Environment (Required): 
- Operating System and Version: Windows 10 Pro x64 Fall Creators
- Browser and Version: Google Chrome 64.0.3282.186 (Official Build) (64-bit)
- Adblocker and Version: 

#### Your filter lists (Required): 
- https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoBase.txt​​​​​
- https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoTimer.txt
- https://raw.githubusercontent.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoWhitelist.txt​​​​​
- Nano Defender Integration
- Peter Lowe’s Ad and tracking server list
- Malware Domain List​​​​​
- Malware domains​​​​​
- EasyPrivacy
- EasyList
- Adblock Warning Removal List
- uBlock filters
- uBlock filters – Annoyances​​​​​
- uBlock filters – Badware risks
- uBlock filters – Experimental​​​​​
- uBlock filters – Privacy
- uBlock filters – Resource abuse​​​​​
- uBlock filters – Unbreak

**Comment by jspenguin2017** [comment]
Looks like this is addressed in uAssets.
