### ISSUE TITLE
openload.co

### ISSUE THREAD

**Issue by LukePoke** [jspenguin2017/uBlockProtector#870]
https://oload.site/f/IFBHiufeaXk/YowamushiPedal2_Ep_09_SUB_ITA.mp4

Screenshot of the web page (including address bar and extension icons) (required): 
https://i.imgur.com/jJgtiQJ.png

Screenshot of the console (press `F12` to bring up the console) (required): 
https://i.imgur.com/2dtkVYa.png

Environment (Required): 

- Operating System and Version: Windows 10 Pro
- Browser and Version: Firefox 58.0.2 (64 bit)
- Adblocker and Version: Ublock Origin 1.15.10

Add everything else that you believe to be useful below (optional):
The site detects adblock and does not allow viewing of the video.

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
