### ISSUE TITLE
fmovies.*

### ISSUE THREAD

**Issue by sixipikova** [jspenguin2017/uBlockProtector#871]
### Test link (required): 
[https://www1.fmovies.se/film/homeland-7.kk0r4](https://www1.fmovies.se/film/homeland-7.kk0r4)

### Screenshot of the web page (including address bar and extension icons) (required): 

[https://imgur.com/d0W3D6P](https://imgur.com/d0W3D6P)

### Screenshot of the console (press `F12` to bring up the console) (required): 

[https://imgur.com/4nFvi1Q](https://imgur.com/4nFvi1Q)

### Explain what was not right (optional if obvious): 
It will not play any videos at all unless I disable both ublock and nano defender.

### Reproduction steps (optional if trivial): 
Click the link, try to play any video. It will not play at all.

### Environment (Required): 

- Operating System and Version:  Windows 10 
- Browser and Version:  Google Chrome is up to date
Version 64.0.3282.186 (Official Build) (64-bit)
- Adblocker and Version: uBlock Origin v1.15.2 / Nano Defender Nano 13.39 - Configured as Required.

#### Your filter lists (Required): 

Enabled
Ublock Default Filter List Enabled including Antiadblock.
Custom (3)
https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoBase.txt​​​​​52 used out of 52​​​​
https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoDefender.txt​​​​​2,651 used out of 2,757​​​​
https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoWhitelist.txt​​​​​0 used out of 0​​​​

**Comment by jspenguin2017** [comment]
@okiehsch Leftover placeholder: `mcloud.to###jwa`

**Comment by okiehsch** [comment]
Thx, added.

**Comment by xredskull** [comment]
Still not working. Videos still not loading.

**Comment by jspenguin2017** [comment]
Yea, there's a popup redirection.

**Comment by okiehsch** [comment]
Are there still any problems if you add
````
fmovies.*##script:inject(abort-current-inline-script.js, atob, tabunder)
````

**Comment by jspenguin2017** [comment]
Yea, seems to work.

**Comment by okiehsch** [comment]
Fixed.
