### ISSUE TITLE
bittube.me

### ISSUE THREAD

**Issue by coachq127** [jspenguin2017/uBlockProtector#873]
### Test link (required): 
https://bittube.me/w/zyun7

### Screenshot of the web page (including address bar and extension icons) (required): 

http://prntscr.com/imqv5n

### Screenshot of the console (press `F12` to bring up the console) (required): 

http://prntscr.com/imqvb9

### Explain what was not right (optional if obvious): 
Detects adblock after a bit,  also timer won't speed up.

### Reproduction steps (optional if trivial): 
Pressing play on the video starts the timer,  but it goes too slow.  Also after a bit it usually goes into anti adblock mode.

### Environment (Required): 

- Operating System and Version: Windows 10
- Browser and Version: Latest Chrome
- Adblocker and Version: Latest Nano Adblocker with Nano Defender

#### Your filter lists (Required): 

default

#### Your custom filters (Required if you have any): 
bittube.me##script:inject(nano-setInterval-booster.js, /.?/, 100)
(doesn't work)

**Comment by jspenguin2017** [comment]
The timer is pumped through WebSocket, so there isn't anything you can do.

**Comment by jspenguin2017** [comment]
@okiehsch
```
bittube.me##script:inject(addEventListener-defuser.js, visibilitychange)
@@||bittube.me/*/js/ads2.js$xmlhttprequest,first-party
```

**Comment by okiehsch** [comment]
Hm, seems fixed with `@@||bittube.me/*/js/ads2.js$xmlhttprequest,first-party`.

Is `bittube.me##script:inject(addEventListener-defuser.js, visibilitychange)` necessary on your end?

**Comment by jspenguin2017** [comment]
It's more of an annoyance, if you unfocus the page the video pauses.

**Comment by okiehsch** [comment]
Thx, added.
