### ISSUE TITLE
userscloud.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#875]
### Test link (required): 
Any Upload
https://userscloud.com/#tab3

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-03-05_091201](https://user-images.githubusercontent.com/2828165/36961766-72fc5bd0-2055-11e8-92b8-b631d30d0ee0.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-03-05_091242](https://user-images.githubusercontent.com/2828165/36961778-7d6ec602-2055-11e8-9d7c-4d702681ce3f.png)

### Explain what was not right (optional if obvious): 
can you fix this problem please
when i disabled adblock upload working good 

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome 64.0.3282.186 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.33 +Nano Defender 13.39

Your filter lists (Required):
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Ads (2)
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
Regions, languages (4)
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

Your custom filters (Required if you have any):
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by titosalah** [comment]
@jspenguin2017  u want account 
username:toi222
password:toi222

**Comment by jspenguin2017** [comment]
Thanks, recorded. I'll test tonight.

**Comment by jspenguin2017** [comment]
Does `@@||usercdn.com^$subdocument,domain=userscloud.com` work? 

cc @okiehsch

**Comment by okiehsch** [comment]
Fixed.
