### ISSUE TITLE
webinsider.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#877]
### Test link (required): 
https://webinsider.pl/raspberry-pi-raspbian-stretch/

### Screenshot of the console (press `F12` to bring up the console) (required): 

![capture](https://user-images.githubusercontent.com/15007183/37029330-0bc1613a-2105-11e8-9688-fb0293fbfc7c.PNG)

### Reproduction steps (optional if trivial): 
1 open test link 
2 scroll all the to the bottom of the page to activate msg

### Environment (Required): 

- Operating System and Version: win7pro
- Browser and Version: chrome Version 64.0.3282.186 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.15.2

#### Your filter lists (Required): 

regular ubo + pl filters

### Add everything else that you believe to be useful below (optional): 
translation of the popup:

I see that you are blocking ads. Can you consider adding WebInsider.pl to exceptions? Thank you in advance!

**Comment by jspenguin2017** [comment]
Hum, I can't seem to reproduce.

**Comment by jspenguin2017** [comment]
It takes 60 seconds for it to pop up...
```js
jQuery(document).ready(function($) {
    if (!$('article').is(":visible")) {
        setTimeout(function() {
            alert('Prawdopodobnie korzystasz z jakiejś wtyczki typu AdBlock/uBlock, która w swojej nadgorliwości zablokowała całą treść artykułu na stronie. By przeczytać artykuł wyłącz blokadę reklam lub dodaj stronę WebInsider.pl do wyjątków.');
            ga('send', 'event', JSAlert, Show, AdBlockArticle01)
        }, 5000)
    }
});
jQuery(document).ready(function($) {
    if (!$('article').is(":visible")) {
        setTimeout(function() {
            alert('Widzę, że nadal masz aktywną blokadę. Naprawdę - nie chodzi o reklamy. Po prostu przy obecnych ustawieniach wtyczki AdBlock/uBlock nie zobaczysz treści artykułu, bo zawiera on słowo "reklama" w swoich tagach, przez co jego treść jest blokowana. Tak, wiem - absurd, ale to nie ja wymyśliłem...');
            ga('send', 'event', JSAlert, Show, AdBlockArticle02)
        }, 60000)
    }
});
jQuery(document).ready(function($) {
    if ((!$('.etad').is(":visible")) && ($('article').is(":visible"))) {
        setTimeout(function() {
            alert('Widzę, że blokujesz reklamy. Czy możesz rozważyć dodanie strony WebInsider.pl do wyjątków? Z góry dziękuje!');
            ga('send', 'event', JSAlert, Show, AdBlock01)
        }, 60000)
    }
});
```

**Comment by jspenguin2017** [comment]
I guess `setTimeout-defuser.js, AdBlock` should work.

**Comment by xxcriticxx** [comment]
@jspenguin2017 can you provide example?

**Comment by jspenguin2017** [comment]
I'll fix this when I get time.
