### ISSUE TITLE
updato.com

### ISSUE THREAD

**Issue by Od1sseas** [jspenguin2017/uBlockProtector#878]
https://updato.com/firmware-archive-select-model?q=SM-A510F&exact=1&r=EUR&v=Nougat%28Android+7.0%29&rpp=15

Adblock Warning after some seconds
Chrome+Nano Defender+Nano Adblocker

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
https://github.com/uBlockOrigin/uAssets/commit/bc617f08bb648c1be4132d8ad5c964c8f0b80b9c
