### ISSUE TITLE
viasatsport.fi (iframe of is.fi)

### ISSUE THREAD

**Issue by arttuberg** [jspenguin2017/uBlockProtector#88]
The site shows blurry version of videos if adblock is detected.  
I added my own whitelisting filters on uBlock origin so I can see the videos, but only with forced commercials before the video. 
When I added AdBlockProtector, it started again complaining about adblock and showed blurred videos only, unless I disable ABProtector.

I'm not at all skilled with writing filters or analyzing what could help, is there a solution someone could help me with?
I'm using Firefox 52.0 atm.

Example: 
http://www.is.fi/mestarienliiga/art-2000005119802.html

**Comment by X01X012013** [comment]
I'll have a look.

**Comment by uBlock-user** [comment]
```` javascript

    (function() {
        // Load detector on a sample of page loads
        // Ratio should be a number between 0 and 1
        //     - 0 means 'never load'
        //     - 0.333 means 'load on every three page loads'
        //     - 1 means 'always load'
        var sabdetect_sample_ratio = 10/100;

        window.Sabdetect_load = Math.random() < sabdetect_sample_ratio;

        if (window.Sabdetect_load) {
            var sabd = document.createElement('script');
            sabd.type = 'text/javascript';
            sabd.async = true;
            sabd.src = '//sn.sanoma.fi/js/sabdetect/Sabdetect-is-async.min.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(sabd, s);
        }
    })();
</script>
<script type="text/javascript">
    if (window.Sabdetect_load) {
        window.setTimeout(function() {
            if (typeof window.Sabdetect == 'undefined' && dataLayer) {
                dataLayer.push({'event':'eventinfo',
                    'eventCategory':'Adblock',
                    'eventAction':'Blocked',
                    'eventLabel': dataLayer[0].page.category.categoryid});
            }
        }, 5000);
    }

````

**Comment by uBlock-user** [comment]
Killing the `setTimeout` call should do the job I suppose.

**Comment by X01X012013** [comment]
Hum... yea. Or redefine `Sabdetect`.

**Comment by uBlock-user** [comment]
Try - `@@||is.fi^$elemhide` and see if it works.

**Comment by X01X012013** [comment]
Actually, let's just lock `Sabdetect_load` to `false`.

**Comment by X01X012013** [comment]
`vjs.getPlayers()` returns an interesting object, but doesn't seem to contain URL to the media file... 
Examining `vjs` namespace, it looks like AdBlock detection is integrated into VideoJS.

**Comment by X01X012013** [comment]
@szymon1118 Can you have a look please?

**Comment by X01X012013** [comment]
The player seems to have detected a generic protector...

**Comment by szymon1118** [comment]
@X01X012013 You are right and it's hard for me to grab the url without being able to play a video. I found a method to grab url but it doesn't work because there is an error in API response (I'm posting a link to Python script I had found connected with this site: http://programtalk.com/vs2/python/12272/svtplay-dl/lib/svtplay_dl/service/viasatsport.py/). I tried looking into this script: https://viasport-assets.mtg-api.com/2017030808/prod/3-f2a6e6b66f51f7838b39.js and seems that it contains a method to form an API url: `getStreamLinks` but as I said before API doesn't work for me.

**Comment by X01X012013** [comment]
I disabled generic protectors on this iframe for now, your rules should now work properly. 
```JavaScript
if (a.domCmp(["is.fi", "viasatsport.fi"])) {
    //Issue: https://github.com/X01X012013/AdBlockProtector/issues/88
    a.readOnly("Sabdetect_load", false);
    if (a.domCmp(["viasatsport.fi"], true)) {
        a.config.allowGeneric = false;
    }
}
```

**Comment by X01X012013** [comment]
@szymon1118 Thanks a lot. Do you know which country is not Geo Locked? Maybe we can Tunnel Bear over...

**Comment by arttuberg** [comment]
Thank you for quick response! 
Looks like we got rid of the blurring for now. Will definitely keep using this protector and recommend to friends.

**Comment by X01X012013** [comment]
Thank you for your support. 
We'll keep trying to find a better solution so the video will play without the need to watch ads.

**Comment by szymon1118** [comment]
@X01X012013 Website has a domain `.fi` so probably Finland isn't Geo Locked. You can try to patch their player but I don't know what do you mean by patching because their player has almost 40000 lines of code: https://viasport-assets.mtg-api.com/2017030808/prod/avod-player-f2a6e6b66f51f7838b39.js but I'm not sure if it's the main player's script. I also found yesterday but I forgot about it that maybe we can disable adblock detection using this: `videoPlayers["video-ceef42dc-bd89-478c-a9ee-95dd1c46039c"]._player.adBlockerBlocker._isShowing`. Let me know if it's worth something :smile: or maybe you will be able to find something more interesting in `videoPlayers`.

**Comment by X01X012013** [comment]
@szymon1118 Thanks for the info. I'll have a look.

**Comment by X01X012013** [comment]
I am a bit busy lately and their code is quite complex. I'll work on this when I have time, if someone can help me pin down the offending function, that'll help a lot.

**Comment by ghajini** [comment]
@jspenguin2017 can you check wirh finland vpn
(Tunnelbear)
If these works

@@||fwmrm.net/p/MTG_Brightcove_HTML5/AdManager.js$domain=viasport.fi
@@||viasport.fi^$xmlhttprequest
@@_Play_Html5_Live$script,domain=viasport.fi

**Comment by jspenguin2017** [comment]
Added to https://github.com/jspenguin2017/uBlockProtector/edit/master/Notes/No%20Solution.MD
Discussion can continue here.

**Comment by jspenguin2017** [comment]
@ghajini TunnelBear doesn't have Finland... I will have another look at that Python algorithm, and see if I can find something.

**Comment by adreporter** [comment]
@jspenguin2017 Let me know if you want ZenMate, I'll post credentials at pastebin.

**Comment by jspenguin2017** [comment]
@ghajini Those rules doesn't work, with them, you will have to watch both preroll ads and blurred video. 
The blurring is done in CSS, but it has solid mutation observer so the blurring can't be overridden...

**Comment by ghajini** [comment]
Ok that was working months ago....Disregard what I suggested.....

**Comment by jspenguin2017** [comment]
Oh, that Python script seems to be still valid, got the JSON URL: https://viasport.mtg-api.com/stream-links/viasport/web/se/clear-media-guids/f1YVbVOh9KCZ05UykzbCdMnGVypKvRCG/streams

And media file URL: https://viasatsport-jic-vod-hls.secure.footprint.net/hls/Viasat_Sport_-_Production/995/808/index.m3u8?nvb=1497290588&nva=1497297818&token=095f412fc170922f9abed

**Comment by jspenguin2017** [comment]
OK, I was able to get this to work... Kind of... Some React code is preventing the document from being mutated... I had to nuke the whole webpage. 
![image](https://user-images.githubusercontent.com/7283682/27049149-a33ea1a6-4f6b-11e7-9c53-d9fc7bd62503.png)

**Comment by jspenguin2017** [comment]
I think that's pretty horrible user experience... But I'll still mark it as workaround... 

@adreporter Thanks for the VPN.

**Comment by jspenguin2017** [comment]
It's been a while and I still couldn't find a solution, closing as no solution.

**Comment by jspenguin2017** [comment]
The debug switch is now hard coded into the extension, you will have to load the unpacked extension to enable it...

**Comment by jspenguin2017** [comment]
Fixed in https://github.com/jspenguin2017/uBlockProtector/commit/8020c2610b21a7269a943bb45467b1db0f7c2a78
