### ISSUE TITLE
Can't believe.

### ISSUE THREAD

**Issue by Raavizz** [jspenguin2017/uBlockProtector#880]
Continuation of https://github.com/jspenguin2017/uBlockProtector/issues/879

@jspenguin2017 : If you don't care about @gorhill's drama (ugly censorship, removing comments, locking thread) and don't walk to talk about it, that's your choice, but saying that it is my drama is an ulgy slander and turning upside down, because:
- I'm completely calmed down
- I'm not insulting
- I'm not calling names
- I'm talking substantively
- I'm not doing ugly censorship
- I'm not removing comments, 
- I'm not locking threads

How can it be my drama then? 
Where do you see my drama here? 
Just because I'm talking about @gorhill' s ugly behaviour doesn't mean that it is my drama.
Also some more people (@thomasklash @mikhoul @tomasz1986 ) were talking about @gorhill ' s bad behaviour, so it seems that's not only "my drama" , also you were talking in the discussion, why didn't you say about their drama? 
And instead of saying about their drama, you were talking to them? 
What is the difference betweeen my objections against @gorhill and their objections against  @gorhill?
Why only my objections are drama?
Why @thomasklash @mikhoul @tomasz1986 's objections are not drama?
Wasn't it their drama when they were talking about @gorhill 's bad behaviour, but suddenly it is drama when I'm doing the same. 
Why don't you talk normally to me too just like to them? 
Such a hypocrisy.
Talking about @gorhill's censorship drama is not drama. 
The only drama is @gorhill ' s (and now your too) censorship and your slanders. 
That's the only drama, because you and him are simply unable to defend your right on a civilized level - by reasonable counter-argument.
Your only arguments are censorhip/hypocrisy (you both) and slanders (you).
I expected a higher level of discussion from intelligent programmers, some kind of argumentation.
I got only ugly censorship and slanders.
That is yours drama, got it?
Stop trolling me by saying that it is my drama.

I want you to remove "drama" word/slander from your comment https://github.com/jspenguin2017/uBlockProtector/issues/879#issuecomment-372124365 or I'll simply report you and @gorhill for abusing/harassing, and you also for trolling, to GitHub administration, after you remove this word you can remove this thread as well.

I was helping solving issues on both repos, and what I got as a gift? Such an ugly treatment, being treated like an enemy. These are the facts, not my drama, that the facts hurts you both.

Censorship, slanders, hypocrisy... I get off this haunted train.

**Comment by jspenguin2017** [comment]
I guess you are the one who was repeatedly banned.
