### ISSUE TITLE
seekingalpha.com

### ISSUE THREAD

**Issue by Oahoahoah** [jspenguin2017/uBlockProtector#882]
### Test link (required): 
https://seekingalpha.com/

### Screenshot of the web page (including address bar and extension icons) (required): 
![image](https://user-images.githubusercontent.com/37158536/37290801-81a944d2-260d-11e8-916d-cf950b555e02.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![image](https://user-images.githubusercontent.com/37158536/37291027-1895a5f2-260e-11e8-9119-0b4d58292ab1.png)

### Environment (Required): 

- Operating System and Version: Windows 10 - 1709 - 16299.125
- Browser and Version: Chrome - 64.0.3282.186  (64-bit)
- Adblocker and Version: Ublock Origin 1.15.2

#### Your filter lists (Required): 
uBlock filters4 380 brukt av 4 380
uBlock filters – Annoyances62 brukt av 62
uBlock filters – Badware risks8 brukt av 8
uBlock filters – Experimental6 brukt av 6
uBlock filters – Privacy65 brukt av 65
uBlock filters – Resource abuse211 brukt av 213
uBlock filters – Unbreak320 brukt av 320
Adblock Warning Removal List401 brukt av 408
Adguard Base Filters14 206 brukt av 14 906
Adguard Mobile Filters1 822 brukt av 2 014
EasyList80 464 brukt av 80 765
EasyPrivacy14 336 brukt av 14 508
Malvertising filter list by Disconnect540 brukt av 4 399
Malware Domain List1 128 brukt av 1 143
Malware domains17 644 brukt av 17 644
Malware filter list by Disconnect160 brukt av 1 663
Adguard’s Annoyance List8 997 brukt av 10 834
Fanboy’s Annoyance List9 110 brukt av 35 971
Fanboy’s Anti-Thirdparty Social (see warning inside list)68 brukt av 68
Fanboy’s Cookiemonster List8 608 brukt av 8 610
Fanboy’s Social Blocking List18 227 brukt av 18 253
Peter Lowe’s Ad and tracking server list2 596 brukt av 2 600

#### Your custom filters (Required if you have any): 
https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoBase.txt55 brukt av 59
https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoDefender.txt2 569 brukt av 2 757
https://jspenguin.com/NanoAdblocker/AssetsMirror/NanoWhitelist.txt0 brukt av 0

**Comment by jspenguin2017** [comment]
Can't reproduce.
