### ISSUE TITLE
dl.ccbluex.net

### ISSUE THREAD

**Issue by grji** [jspenguin2017/uBlockProtector#883]
### Test link (required): 
http://dl.ccbluex.net/download/skip/index.php?target=TGlxdWlkQm91bmNlLzEuOC80NWduaGYvTGlxdWlkQm91bmNlMS44LjktYjQxLnppcA==

### Screenshot of the web page (including address bar and extension icons) (required): 
https://gyazo.com/4dde1e758e2d3b6e47def94c2f22716f

### Screenshot of the console (press `F12` to bring up the console) (required): 
https://gyazo.com/4ad77c05ccf777df8e6ac0c723f94287

### Environment (Required): 

- Operating System and Version: Windows10 Home
- Browser and Version: Chrome 65.0.3325.146
- Adblocker and Version: Nano Adblocker 1.0.0.34 and Nano Defender 13.43

#### Your filter lists (Required): 
JPN: Adguard Japan Filter, http://tofukko.r.ribbon.to/Adblock_Plus_list.txt

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
