### ISSUE TITLE
play.tv3.lt

### ISSUE THREAD

**Issue by sangas** [jspenguin2017/uBlockProtector#884]
### Test link (required): 

https://play.tv3.lt/programos/pasmerkti-4-n-7/924046?autostart=true

### Screenshot of the web page (including address bar and extension icons) (required): 

http://prntscr.com/iqo73j

### Screenshot of the console (press `F12` to bring up the console) (required): 

http://prntscr.com/iqo8wc

### Environment (Required): 

- Operating System and Version: Windows 10 Pro 
- Browser and Version: Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)
- Adblocker and Version: uBlock Origin v1.15.2 and Nano Defender 13.43

#### Your filter lists (Required): 

Enabled: LTU: Adblock Plus Lithuania

**Comment by jspenguin2017** [comment]
Does this website has geo lock?

**Comment by sangas** [comment]
Probably not. Just checked with several IPs from other countries and it works.

**Comment by jspenguin2017** [comment]
Which country are you in?

**Comment by sangas** [comment]
Lithuania

**Comment by okiehsch** [comment]
If I use `LTU: Adblock Plus Lithuania` only 
`@@||gemius.pl/gplayer.js$script,domain=play.tv3.lt`
is needed to fix the issue on my end.

**Comment by jspenguin2017** [comment]
Did the fix land in uAssets?

**Comment by okiehsch** [comment]
I never got any feedback and honestly lost track of this issue, I will add the filter later today.
