### ISSUE TITLE
stream.golfchannel.com

### ISSUE THREAD

**Issue by straightflushin** [jspenguin2017/uBlockProtector#885]
### Environment (Required): 

- Operating System and Version: Windows 10 x64 1703
- Browser and Version: Chrome v65
- Adblocker and Version: Nano 1.0.0.34

**Comment by straightflushin** [comment]
What's your preferred way to be sent a test account?

**Comment by jspenguin2017** [comment]
Submit it here: https://jspenguin.com/PrivateMessage/

**Comment by straightflushin** [comment]
PM sent, thanks for the help

**Comment by jspenguin2017** [comment]
@okiehsch `@@||stream.golfchannel.com/*/ads.js$script`

**Comment by okiehsch** [comment]
````
@@||stream.golfchannel.com/*/ads.js$script,first-party
@@||akamaihd.net/*/ads.js$script,domain=golfchannel.com
````
The video player at `golfchannel.com` has it's own anti-adblock script.
Example link: `https://www.golfchannel.com/video/can-you-swim-feng-i-will-survive-water`

**Comment by straightflushin** [comment]
The warning message is gone for me, but now it's been replaced with an infinite loading screen. The stream plays fine when I disable adblock. Anything I should tweak?

**Comment by jspenguin2017** [comment]
If you update all the filters, does the problem persist?

**Comment by jspenguin2017** [comment]
Issue moved to https://github.com/NanoAdblocker/NanoFilters/issues/148
Please continue the conversation there.
