### ISSUE TITLE
ouo.io

### ISSUE THREAD

**Issue by gabri25ele** [jspenguin2017/uBlockProtector#886]
Today, with ouo.io we have a loop-not-bypass.

**Comment by tebas91** [comment]
Same happened to me.

Chrome ver: 64.0.3282.140
uBlock Origin ver: 1.15.2
Nano Defender ver: 13.44

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/NanoAdblocker/NanoDefender/issues/30
