### ISSUE TITLE
eskago.pl

### ISSUE THREAD

**Issue by krystian3w** [jspenguin2017/uBlockProtector#887]
### What bappend

Nano defender 13.46 detect when is active:

> ![Img](https://user-images.githubusercontent.com/36385327/37578051-7d99aff2-2b36-11e8-8798-73c403babc00.png) |
> --- |

### Link

**http://www.eskago.pl/radio/eska-warszawa** <sup>_([polish-ads-filter issues #6583](/MajkiIT/polish-ads-filter/issues/6583))_</sup> 

---

`@@||eskago.pl^$generichide` may works if nano defender is disabled.

### Environment
Tested in Opera 51 (on Windows 7)  with chrome version addons: Nano Adblocker 1.0.37 & Nano Defender 13.46

#### filters
Default list in nano adblocker + nano defender integration + Polish + Cookiemonster

**Comment by jspenguin2017** [comment]
Is this being handled in regional filter?

**Comment by krystian3w** [comment]
Possible in regional if find better rule as `@@||eskago.pl^$generichide` (maybe exist) and find script loaded front cover and title song (when unlock all script on `eskago.pl` I saw this elements).

I do not know who block nano defender (not adblocker) and activate adblock alert on `eskago.pl`, sorry.

**Comment by jspenguin2017** [comment]
Ahhh, it's the new and improved FuckAdBlock, let me roll out my new and improved foiling engine.
