### ISSUE TITLE
moonbit.co.in

### ISSUE THREAD

**Issue by Linden10** [jspenguin2017/uBlockProtector#888]
### Test link (required): 

https://moonbit.co.in/

### Screenshot of the web page (including address bar and extension icons) (required): 

![Moonbitcoin blockery](https://i.imgur.com/yimGQLz.png)
https://i.imgur.com/yimGQLz.png

**Note: Nano Defender icon is hidden but enabled.**

----------------

### Screenshot of the console (press `F12` to bring up the console) (required): 

![Moonbitcoin web console](https://i.imgur.com/ZIMEmEN.png)
https://i.imgur.com/ZIMEmEN.png

### Explain what was not right (optional if obvious): 

When trying to claim coins after 5 minutes or more, you receive an red
message box claiming that the adblocker needs to be disabled in order
to claim coins.

### Reproduction steps (optional if trivial): 

Login into moonbit.co.in with coinpot account.  
Try to claim coins after 5 minutes or more...  
Receive red message due to blocking ads, not recieving coins.

### Environment (Required): 

- Operating System and Version: Windows 7 SP1 (Home Premium)
- Browser and Version: Opera 51 (latest version)
- Adblocker and Version: Nano Adblocker v1.0.0.37 with Nano Defender Version 13.47

#### Your filter lists (Required): 

Using filters that were enabled by default with Nano Adblocker.

#### Your custom filters (Required if you have any): 

None.

### Add everything else that you believe to be useful below (optional): 

An Account is required to login.  
Here's a fake account, just enter this email in the coinpot text field to login:
aakbonusbtc0@cuvox.de

Also if you need references to bypass this anti-adblock, these sites can help as their anti-adblock
is successfully blocked by nano defender. (and works on the same type of coding as moonbit.co.in)  
https://moonliteco.in/ and https://moondoge.co.in/

(The same fake account will work on those sites too.)

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
I can't reproduce with Chrome or Firefox.
![unbenannt](https://user-images.githubusercontent.com/16838044/37741422-9e7bf4b4-2d61-11e8-9808-c6ce18636421.JPG)

**Comment by jspenguin2017** [comment]
Did you click "claim now"?

**Comment by okiehsch** [comment]
Oh, sorry, it is early and I obviously need more coffee.

**Comment by okiehsch** [comment]
OK, maybe I am missing something, but the best I can come up with is
````
@@||coinad.com/ads/show/show.php$subdocument,domain=moonbit.co.in
moonbit.co.in###advert-space > iframe:style(visibility: collapse !important)
moonbit.co.in##.hide-xs:style(visibility: collapse !important)
````

**Comment by jspenguin2017** [comment]
Did you pin down the offending script?

**Comment by okiehsch** [comment]
In the source code of `view-source:https://moonbit.co.in/`
![unbenannt](https://user-images.githubusercontent.com/16838044/37745441-1f329d16-2d75-11e8-881c-2d66c82ab175.PNG)

I tried `moonbit.co.in###advert-space > iframe:style(height: 31px! important;)` but that does not work.

**Comment by jspenguin2017** [comment]
Hum, how about just patch the code? Sounds like the easiest way to go.

**Comment by jspenguin2017** [comment]
Your solution still works OK, what is the problem that's bothering you? 
Without patching the code, the best you can do is make the ads 0 width.

**Comment by okiehsch** [comment]
I am always trying to find a fix without allowing third-party stuff, probably a bad habit.

Alright I will add my soulution.

**Comment by jspenguin2017** [comment]
I mean I still have my giant hammer `a.beforeScript()`, but I rather not use it unless it's not possible to hide the ads otherwise.

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
Also https://moonliteco.in/ and https://moondoge.co.in/
Basically the same logic.

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
@okiehsch 
The CSS that collapses the ads are no longer matching. 
![image](https://user-images.githubusercontent.com/7283682/40522226-0c3c5d42-5f8d-11e8-9b01-91c56ac28cb6.png)

**Comment by okiehsch** [comment]
The captchas are ridiculous, I have no idea what they are actually checking, I clicked every freaking car and I still can't proceed.
End rant.

`moondoge.co.in##[src^="//coinad.com/ads/"]:style(visibility: collapse !important)` works after trying round about twenty captchas.
I will just assume this works for the other domains as well.

**Comment by jspenguin2017** [comment]
![image](https://user-images.githubusercontent.com/7283682/40523368-75a2742e-5f92-11e8-8f0b-ec1334660d1b.png)
