### ISSUE TITLE
mail.yahoo.com

### ISSUE THREAD

**Issue by jctam** [jspenguin2017/uBlockProtector#889]
### Screenshot of the web page (including address bar and extension icons) (required): 
![image](https://user-images.githubusercontent.com/37606044/37694039-0ea9e3d6-2c81-11e8-8c70-6df4d4d45ff8.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![image](https://user-images.githubusercontent.com/37606044/37694342-aa499fc8-2c83-11e8-98e7-b2c10bb57d2f.png)

### Environment (Required): 
Windows 10 v. 1709 

- Browser and Version: 
Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- Adblocker and Version: 
uBlock Origin v1.15.2

#### Your filter lists (Required): 
default + Nano Defender

**Comment by jspenguin2017** [comment]
Fill the template.

**Comment by jctam** [comment]
I'm sorry, I'm not a github user -- I uploaded what I could without revealing private information, and I don't know what more you. I'm just trying to notify you that I'm having a persistent problem with an anti-adblock popup on yahoomail, and this was the only place I found to leave a bug report.

**Comment by jspenguin2017** [comment]
If you are unable to provide sufficient information to let me reproduce the problem then I can't fix it. 
You can send information in private from here: https://jspenguin.com/PrivateMessage/

I need the test link, and a test account if it's required.

**Comment by jspenguin2017** [comment]
I got your message. 
I can't fix this until I have a test account.

**Comment by ghajini** [comment]
you can create yahoomail account just like gmail

**Comment by jspenguin2017** [comment]
I will never create test accounts myself. It just becomes a huge burden down the road.

**Comment by okiehsch** [comment]
Added, thx.
