### ISSUE TITLE
bizjournals.com

### ISSUE THREAD

**Issue by jjohns71** [jspenguin2017/uBlockProtector#890]
### Test link (required): 
https://www.bizjournals.com/bizjournals/news/2018/03/21/portland-developers-could-collect-tax-breaks.html

### Screenshot of the web page (including address bar and extension icons) (required): 

![paywall](https://user-images.githubusercontent.com/6795795/37720210-310ed266-2cfd-11e8-97d4-1f974ef75e4a.PNG)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![console](https://user-images.githubusercontent.com/6795795/37719993-b31d7844-2cfc-11e8-9ff9-b39526f4ac98.PNG)

### Explain what was not right (optional if obvious): 

For some bizjournal articles that are identified as `isPremium : true` in the page source, the content will initially load but there is some javascript being read that will reload the DOM and a paywall message is then displayed with no article contents anymore. Some articles on bizjournal do not have the paywall message (Second link below). I think there is some `##script:inject()` filter that could stop it from reloading the DOM element but I couldn't figure out a working solution.

Example of paywalled article (with source content `isPremium : true`): https://www.bizjournals.com/bizjournals/news/2018/03/21/portland-developers-could-collect-tax-breaks.html

Example of non paywalled article (with source content `isPremium : false`): https://www.bizjournals.com/austin/news/2018/03/21/austin-crypto-hedge-fund-pulls-in-big-chunk-of.html 

### Environment (Required): 

- Operating System and Version: Windows 10
- Browser and Version: Latest Stable Chrome/Firefox 
- Adblocker and Version: uBlock Origin dev build 1.15.17.0, nano defender 13.47

#### Your filter lists (Required): 

Default

#### Your custom filters (Required if you have any): 

None

**Comment by jspenguin2017** [comment]
I don't think it's a paywall as paywall, by definition, must be implemented on server side. 
I'm not sure if it should be classified as ads, so put in annoyance filter for now.

**Comment by jspenguin2017** [comment]
I updated the filter policy to draw a clear and reasonable line. In short, paywalls that doesn't work when JavaScript and/or cookies are disabled in browser settings are considered to be annoyance.

**Comment by jspenguin2017** [comment]
I don't host filters that are not enabled by default, just add the GitHub link.
