### ISSUE TITLE
makeuseof.com

### ISSUE THREAD

**Issue by adreporter** [jspenguin2017/uBlockProtector#891]
https://www.makeuseof.com/tag/pros-cons-using-microsoft-account-windows/
<img width="451" alt="przechwytywanie" src="https://user-images.githubusercontent.com/18214146/37772840-28811660-2ddc-11e8-8546-c0bb62e448ca.PNG">
<img width="572" alt="przechwytywanie2" src="https://user-images.githubusercontent.com/18214146/37772844-2b87ec44-2ddc-11e8-90b7-cb0691257211.PNG">
Please scroll down the page a little bit to see the anti-adblock message.
The text under that message is almost invisible. Could you please fix it?

**Comment by jspenguin2017** [comment]
Hum, I can't quite reproduce it.

**Comment by okiehsch** [comment]
Fixed.

**Comment by adreporter** [comment]
@okiehsch Thank you.
