### ISSUE TITLE
Deactivate logs

### ISSUE THREAD

**Issue by paveltrufi** [jspenguin2017/uBlockProtector#892]
```
[Nano] Nano Defender Activated :: 127.0.0.1
3-content-rules-1-common.js:56 [Nano] Excluded :: All Generically Applied Solutions
```
It's pretty annoying to have your console.logs flying around mine. Could you, either suppress them or provide an option in the extensions so we can deactivate them?

Thank you in advance.

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/735
