### ISSUE TITLE
pluto.tv

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#897]
### Test link (required): 
http://pluto.tv/watch

### Screenshot of the console (press `F12` to bring up the console) (required): 
![capture](https://user-images.githubusercontent.com/15007183/38149723-b9d2c84a-3429-11e8-9387-2d6b2e414f03.PNG)

### Explain what was not right (optional if obvious): 
video player won't load

### Environment (Required): 

- Operating System and Version: win7 pro
- Browser and Version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.15.18

#### Your filter lists (Required): 
reg ubo + pl list

**Comment by jspenguin2017** [comment]
@okiehsch `@@||pluto.tv/*/js/analytics/core.js$script,first-party`

**Comment by okiehsch** [comment]
Thx, fixed.
