### ISSUE TITLE
Why is an internet connection necessary?

### ISSUE THREAD

**Issue by ylluminarious** [jspenguin2017/uBlockProtector#898]
On the home page for this extension, there is a note which reads:

> Note: If you are using uBlock Origin, then you **must** have a functional Internet connection when you start your browser or touch anything in the dashboard.

Why is that? What are the consequences of not doing so? Does it render one's browser unusable? I would appreciate some more information on the nature of this requirement since it is presently rather ominous and leaves a lot of room for (mis)interpretation.

I apologize if this is the wrong place to ask, but I don't see any other kind of forum or documentation for this extension.

**Comment by jspenguin2017** [comment]
It needs internet connection to load the resource file, which is required for Nano filters to work.

**Comment by ylluminarious** [comment]
@jspenguin2017 So everything else in the browser would work fine? No crashing or errors or whatnot?

**Comment by jspenguin2017** [comment]
No crash, error will be generated in background console. Not everything will work as expected as the resource file is required for Nano filters to work.

**Comment by ylluminarious** [comment]
@jspenguin2017 So it is not *absolutely* necessary to have an internet connection, just strongly recommended, is that a correct assertion?

**Comment by jspenguin2017** [comment]
It's up to you to decide how you use this open source project. It is necessary if you want to report websites that do not work. 
The caching logic was updated recently though, I still have to test out how things works now.

**Comment by ylluminarious** [comment]
@jspenguin2017 Ok, thanks for that clarification. I'll go ahead and close this issue then.
