### ISSUE TITLE
vvvvid.it

### ISSUE THREAD

**Issue by Dr4w** [jspenguin2017/uBlockProtector#899]
### Test link (required): 
https://www.vvvvid.it

### Screenshot of the web page (including address bar and extension icons) (required): 
![immagine](https://user-images.githubusercontent.com/38052711/38274448-172061a2-378f-11e8-9848-d6ebff0a4806.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![console](https://user-images.githubusercontent.com/38052711/38274646-aa835b2a-378f-11e8-835d-21e5e87dc6fb.png)

### Reproduction steps (optional if trivial): 
Open a random film/video on the site. The blocking message won't always shows off at the first page load. Reload the page (that contains the video) few times if the message doesn't immediately pops up.

### Environment (Required): 

- Operating System and Version: Windows 10 LTSB 
- Browser and Version: Firefox Quantum 59.0.2 64Bit
- Adblocker and Version: uBlock Origin v1.15.24 

#### Your filter lists (Required): 
Default uBlock ones + Nano Defender

**Comment by jspenguin2017** [comment]
I need a proper test link.

**Comment by Dr4w** [comment]
@jspenguin2017 https://www.vvvvid.it
