### ISSUE TITLE
xmovies8.org

### ISSUE THREAD

**Issue by uBlock-user** [jspenguin2017/uBlockProtector#90]
URL - https://xmovies8.org/watch?v=Captain_America_Civil_War_2016

````javascript
function checkAdblock(){
    $.ajaxSetup({cache: true});
    $.getScript( "/ads_1489185675.js" ).done(function( script, textStatus ) {
    }).fail(function( jqxhr, settings, exception ) {
         $('#player_container').html('<div id="debridnok" class="debridnok" style="color:#fff;padding:200px 80px 0 80px;"><span style="font-size:20px;"><b>You need to disable your adblocking software to continue watching movie on this site.<br/>Thank you so much!</b></span></div>');
        $.post('/adblock', null, null,'html');
    });
}
````

**Comment by X01X012013** [comment]
`||xmovies8.org/ads_*.js$xmlhttprequest,first-party,redirect=noopjs`

**Comment by uBlock-user** [comment]
Nope, not fixed, nooping doesn't fix it - `https://i.gyazo.com/f3df0699c26f29168dd8db289d19f847.png`

**Comment by uBlock-user** [comment]
You have two options for a fix, either kill that `.fail` condition via userscript or create `function loadedAd(){}` via the script/whitelisting the XHR. That's the only way it would work.

**Comment by X01X012013** [comment]
@uBlock-user 
`noopjs` is the way to go against `$.getScript()`, feeding `nooptext` will cause it to `.fail()`. 
![image](https://cloud.githubusercontent.com/assets/7283682/23824225/9e477144-062f-11e7-9336-de3b7631abed.png)
![image](https://cloud.githubusercontent.com/assets/7283682/23824228/a5d0a408-062f-11e7-943a-f467d8faabe3.png)

**Comment by X01X012013** [comment]
FYI, uBO accepts `nooptext`, `noopcss`, `noopjs`, `noopframe` as well as some transparent images as argument for `redirect`. You can see them here: https://github.com/uBlockOrigin/uAssets/blob/master/filters/resources.txt

**Comment by X01X012013** [comment]
It is pretty hard to patch `jQuery`, if the rule doesn't work, you can just let the XHR through, it doesn't actually load anything useful, just an empty function.

**Comment by uBlock-user** [comment]
@X01X012013 It's not working on Chromium. I see you're on Opera.

I have tested on Chromium 56 and Chromium 59, both produce the same result as below - 

![](https://i.gyazo.com/fb4fec161677a20c22a58ecf54003a8b.png)


![](https://i.gyazo.com/86bc01b8eb773d84b4b2a462cc92ffc1.png)

**Comment by X01X012013** [comment]
That rule works in both Chrome and Opera. Chromium isn't officially supported. 
![image](https://cloud.githubusercontent.com/assets/7283682/23824739/391d4d20-0639-11e7-8d38-f0ef90cc8225.png)

They are using function declaration, which will throw Syntax Error when the identifier is already declared. So `a.readOnly()` does not work in this case since it will crash their script causing the player to not be initialized. Patching `jQuery` is way too heavy for what we are trying to do. White-listing that script is the way to go if redirect doesn't work.

**Comment by uBlock-user** [comment]
> Chromium isn't officially supported.

Chrome is a clone of Chromium, so what do you mean ?

**Comment by X01X012013** [comment]
Opera is also based on Chromium, but Chrome is not Chromium.

**Comment by uBlock-user** [comment]
> but Chrome is not Chromium.

It is but with few differences, the core is completely Chromium. I will let you read this, as I don;t wanna argue about something that is so obvious - https://www.howtogeek.com/202825/what%E2%80%99s-the-difference-between-chromium-and-chrome/

**Comment by X01X012013** [comment]
Tested on Chrome 57, Opera 43, both newest on stable channel. 
I know Chromium and Chrome are very similar, but they are not identical, I tested on Chrome, it works, it's up to you to figure out why it doesn't work on Chromium since Chromium is not in our supported browser list.

**Comment by uBlock-user** [comment]
Chrome is Chromium, the core is same that means if it works on Chrome, it is bound to work on Chromium. That goes without saying. As I said, with each release, something in Chrome/Chromium changes so fixes are not future-proof.. You said you tested on Chrome 57. Try testing on Chrome 58/59 and see if it works or not.

I'm on dev channel and currently on Chromium 59. Anyways, I'm closing this as the whitelisting filter has lready been placed in Adguard's English Filterlist.

**Comment by X01X012013** [comment]
The core is the same doesn't mean they are the same. Look at all the devices powered by Linux kernel, are they the same? 
Dev channel contains bugs that will be fixed before stable release. The stable release of 58 or 59 will be different than the dev 58 or 59. If that filter actually stops working on 58 or 59, we'll fix it by then, not now.

**Comment by uBlock-user** [comment]
But the filter you posted should work, it shouldn't act like this. Don't compare it with Linux based devices, they all are their own flavours man They add and remove a lot of things in each OS! That is not the case here. In Case of Chromium/Chrome, nothing is changed with the core operation, so the redirect filter you posted should work, but it doesn't, that's mind boggling.

> Dev channel contains bugs that will be fixed before stable release. The stable release of 58 or 59 will be different than the dev 58 or 59. If that filter actually stops working on 58 or 59, we'll fix it by then, not now.

If it is a bug, otherwise you will have whitelist too or come up with something new. Stable release don't always mean that everything is patched up. I also tested on stable Chromium 56 release and the filter didn't work there either, which is surprising if you ask me.

**Comment by uBlock-user** [comment]
@jspenguin2017 Finally found a solution

`a.bait("div", "#player_container");`

AND

```
||xmovies8.org/ads_$xmlhttprequest,important
xmovies8.org###debridnok
```

The first filter is to block the whitelisting filter and to trigger the anti adblock script. The second filter is needed when you use `a.bait` a huge white space is created on the top of the page.

**Comment by uBlock-user** [comment]
Test link - https://xmovies8.org/watch?v=X-Men_Apocalypse_2016#video=F1Ejo2pUmtX6EmtX1qCRfsBfh314duPy1FreIDAE

Screenshot - https://i.gyazo.com/e82576e6ba230501c985d166295f6d76.png

**Comment by jspenguin2017** [comment]
@uBlock-user The current solution still works for me.

**Comment by jspenguin2017** [comment]
I think `abort-on-property-read.js` works for jQuery, as it is a bit more complex than `a.noAccess` and is able to create non-existent path.

**Comment by uBlock-user** [comment]
@jspenguin2017 You're testing on Chromium or Opera ? Nothing's wrong with my system. It just doesn't work on my end and it never did when I was on 58 and now on 61, nothing's changed.

> I think abort-on-property-read.js works for jQuery

Do you have a filter with that ?

> The script that it loads does nothing, and it's first party, it's not a big deal to white list it

I hate white-listing, pure and simple. I'm not asking you to add this as the solution, but just FYI, we know have a solution. Adding it or not is upto you. Whitelisting is the last thing I will ever do.

**Comment by uBlock-user** [comment]
Killing `$.getScript` works. Should have used that before!

Filter - `xmovies8.org##script:inject(abort-on-property-read.js, $.getScript)`

**Comment by jspenguin2017** [comment]
I'm on Chrome 59, still works. Try `xmovies8.org##script:inject(abort-on-property-read.js, $.getScript)`. 

We won't need to white list anymore soon, as I finish implementing the extension, I can win every single race condition and patch `XMLHttpRequest()` and we can do a fake redirect internally.

**Comment by jspenguin2017** [comment]
Yea, I guess `abort-on-property-read` is cleaner, I'll update the solution...

**Comment by jspenguin2017** [comment]
I'll test this out tonight to make sure it works.

**Comment by jspenguin2017** [comment]
Tested, works.
