### ISSUE TITLE
nulledpk.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#900]
### Test link (required): 
https://www.nulledpk.com/giveaway-trafficzing-pro-create-your-own-account/

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-04-05_000757](https://user-images.githubusercontent.com/2828165/38337591-34dd81e8-3866-11e8-9a5b-aa21ff45d419.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-04-05_001206](https://user-images.githubusercontent.com/2828165/38337600-3e8c8eaa-3866-11e8-8f28-156e0d0d724f.png)

### Environment (Required): 
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.40+Nano Defender 13.50

**Your filter lists (Required):**
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Ads (2)
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
Regions, languages (4)
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

**Your custom filters (Required if you have any):**
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment]
@okiehsch Do you consider this annoyance or ads?

**Comment by okiehsch** [comment]
A "social" wall, I will add it to `uBO-filters`, there are users without a twitter, facebook or google+ account.

**Comment by okiehsch** [comment]
Thx, fixed.
