### ISSUE TITLE
niagotch.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#902]
### Test link (required): 
https://niagotch.com/2x-rdp-4gb-ram-gcloud-5

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-04-10_000802](https://user-images.githubusercontent.com/2828165/38525637-5ad8e5f4-3c53-11e8-9ae7-ecc1042d2899.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-04-10_000826](https://user-images.githubusercontent.com/2828165/38525648-634f088a-3c53-11e8-949b-d260e3ba06f3.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.40+Nano Defender 13.50

**Your filter lists (Required):**
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Ads (2)
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
Regions, languages (4)
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

**Your custom filters (Required if you have any):**
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by titosalah** [comment]
@jspenguin2017  why bro ??

**Comment by jspenguin2017** [comment]
I don't know man, it works fine for me.

**Comment by titosalah** [comment]
@jspenguin2017 thank you .. now working  . i don't know why this pop up appears?

**Comment by jspenguin2017** [comment]
@okiehsch Can you have a look?

**Comment by okiehsch** [comment]
The link of the OP is not working on my end, however I can reproduce at `niagotch.com`.

**Comment by okiehsch** [comment]
Fixed.

**Comment by titosalah** [comment]
@jspenguin2017 please can you fix this problem? >>> https://niagotch.com/  when website load all links changed to another ads site like this site https://byvngx98ssphwzkrrtsjhnbyz5zss81dxygxvlqd05.com/1583385.html
any way to block that 
thank you

**Comment by jspenguin2017** [comment]
I guess `niagotch.com##script:inject(abort-on-property-read.js, f1V2u)` would work. @okiehsch do you have a better solution?

**Comment by okiehsch** [comment]
`niagotch.com##script:inject(abort-current-inline-script.js, atob, tabunder)`
should work.

**Comment by okiehsch** [comment]
Fixed.

**Comment by titosalah** [comment]
@jspenguin2017 hi bro  .. same problem again all links changed to this website when page loaded 
https://niagotch.com/3000-account-facebook
to
https://z6naousb.com/1583385.html
sorry my bro

thank you very much

**Comment by jspenguin2017** [comment]
I can't seem to reproduce.
