### ISSUE TITLE
Just a trivial issue, but please add a name to the list

### ISSUE THREAD

**Issue by psyblade12** [jspenguin2017/uBlockProtector#906]
Hello, 

This is just a trivial thing, but can you add a name to your list? This link is somewhat long and hard to see.

![untitled](https://user-images.githubusercontent.com/28593221/38656191-0b9d0938-3e43-11e8-8553-30ae82c849b6.png)

Also, thank you for your hard work. I really appreciate it.

**Comment by jspenguin2017** [comment]
If you subscribe from GitHub then it won't have a name. I might add the name to the assets mirror server.
