### ISSUE TITLE
boost.ink

### ISSUE THREAD

**Issue by 3dsboy08** [jspenguin2017/uBlockProtector#908]
### Screenshot of the web page (including address bar and extension icons) (required): 
![image](https://user-images.githubusercontent.com/14914815/38765058-a242bb12-3f88-11e8-919b-1a56b69827a6.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![image](https://user-images.githubusercontent.com/14914815/38765063-bb0bd55c-3f88-11e8-9139-a5077562e499.png)

### Explain what was not right (optional if obvious): 
Pretty obvious, another one of these "subscribe to unlock link" websites. Doesn't seem to actually check if you subscribed or not, but only if you clicked the link.

### Reproduction steps (optional if trivial): 
N/A

### Environment (Required): 

- Operating System and Version: Windows 10 - x64
- Browser and Version: Google Chrome 65
- Adblocker and Version: Nano Adblocker & Nano Defender

#### Your filter lists (Required): 

Default filter list from Nano Adblocker.

#### Your custom filters (Required if you have any): 
N/A

### Add everything else that you believe to be useful below (optional): 
I already took a look at reverse engineering this, and it seems to be very simple. The link itself is encrypted with AES in CBC mode, and the key just seems to be the URL itself. (for example, the key used in the test URL sent is just "boost.ink/ulqgeq" - note though that as longer URLs start to be created it will be substr'd back to 16 characters)

![image](https://user-images.githubusercontent.com/14914815/38765116-8cca049c-3f89-11e8-9323-fa11ebe5dc55.png)

![image](https://user-images.githubusercontent.com/14914815/38765146-69cdca5e-3f8a-11e8-903f-05e6f6f817dd.png)

After decryption, it just sets location.href to the actual URL. Not incredibly special.

**Comment by 3dsboy08** [comment]
Reopening due to site changing algorithm. https://boost.ink/ulqgeq is test link.

**Comment by jspenguin2017** [comment]
Fixed.

**Comment by 3dsboy08** [comment]
Seems they want to start a cat and mouse game.

![image](https://user-images.githubusercontent.com/14914815/40020134-48e22bec-578f-11e8-9d5b-953c53df03ad.png)

![image](https://user-images.githubusercontent.com/14914815/40020146-4d2b283e-578f-11e8-960a-c66b38d98657.png)

We might need a more generalized solution, don't really know how we are going to get around this.

**Comment by jspenguin2017** [comment]
Yea, I don't think there's a easy way around it in this case. 
Solution like this can't be generalized.

**Comment by jspenguin2017** [comment]
This confidential issue refers to this issue: https://gitlab.com/xuhaiyang1234/NanoAdblockerSecretIssues/issues/17

**Comment by jspenguin2017** [comment]
The timer is on server side now, I guess no getting around the delay.

**Comment by timmyrs** [comment]
Your bypass doesn't work, but at least it's undetected. :+1:

**Comment by jspenguin2017** [comment]
I can't believe it, they managed to get around that as well... 
Let's hope it'll last longer this time.

**Comment by jspenguin2017** [comment]
I'm moving this rule to proprietary solutions.
