### ISSUE TITLE
spotify.com

### ISSUE THREAD

**Issue by Francois-dag** [jspenguin2017/uBlockProtector#910]
Not sure wether or not ads detection is involved, but a week ago I was able to listen to spotify using
the simple web client. By now only 1 or 2 songs are played and then the stream is stopped. Occurs
on both firefox and chrome using ub 1.15.24 and nano defender 13.58.

Sorry if out of boundaries.

Cheers !

**Comment by krystian3w** [comment]
This is maybe bug after run new player / ui for free users.

>  https://www.theverge.com/2018/4/17/17248140/spotify-free-tier-new-user-interface-redesign

I see that it can be reproduced on a clean browser profile.

**Comment by Francois-dag** [comment]
argh ...

**Comment by jspenguin2017** [comment]
I don't see what's wrong on that website, so closing.
