### ISSUE TITLE
a-o.ninja

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#912]
### Test link (required): 
https://a-o.ninja/anime/initial-d-first-stage/18

### Screenshot of the console (press `F12` to bring up the console) (required): 
![capture](https://user-images.githubusercontent.com/15007183/39155521-54a42fea-4720-11e8-8c85-2b67933a871c.PNG)

### Environment (Required): 

- Operating System and Version: win7 pro
- Browser and Version: Chrome 66.0.3359.117 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.15.24

#### Your filter lists (Required): 
ubo reg + pl filter

**Comment by jspenguin2017** [comment]
Did you report to regional filter? 
@okiehsch

**Comment by okiehsch** [comment]
It is fixed if I enable the regional filter on my end.

**Comment by xxcriticxx** [comment]
the name of the script changes daily we have cat and mouse game

**Comment by xxcriticxx** [comment]
let me check with @MajkiIT and i be in touch

**Comment by MajkiIT** [comment]
@jspenguin2017 @xxcriticxx I see that they disabled Ablock alert, but I will check it tomorrow.
