### ISSUE TITLE
poki.pl

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#913]
### Test link (required): 
http://poki.pl/g/age-of-war-2

### Screenshot of the console (press `F12` to bring up the console) (required): 
![capture](https://user-images.githubusercontent.com/15007183/39159860-0759edae-4736-11e8-9470-b3a2e88273a4.PNG)

### Explain what was not right (optional if obvious): 
page wont load 

### Environment (Required): 

- Operating System and Version: win7 pro
- Browser and Version: Chrome 66.0.3359.117 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.15.24

#### Your filter lists (Required): 
ubo reg + pl filter

**Comment by jspenguin2017** [comment]
It loads fine for me. 
![image](https://user-images.githubusercontent.com/7283682/39160061-72960c16-4726-11e8-889c-52435921e791.png)

**Comment by xxcriticxx** [comment]
sorry for wasting your time
