### ISSUE TITLE
crackllc.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#915]
### Test link (required): 
https://crackllc.com/z3x-samsung-tool-pro-crack-setup-2018-final/

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-04-27_232316](https://user-images.githubusercontent.com/2828165/39385832-3e6a3350-4a72-11e8-8127-43111e0fb86c.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-04-27_232258](https://user-images.githubusercontent.com/2828165/39385843-48cf3c14-4a72-11e8-9c80-2f65829cb488.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.44+Nano Defender 13.61

**Your filter lists (Required):**
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Ads (2)
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
Regions, languages (4)
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

**Your custom filters (Required if you have any):**
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment]
@okiehsch Social lock + anti-select / right click annoyance

**Comment by okiehsch** [comment]
Fixed.
