### ISSUE TITLE
jcbtechno.com

### ISSUE THREAD

**Issue by JoseHidalgo** [jspenguin2017/uBlockProtector#916]
Website : 
https://www.jcbtechno.com/coollector-movie-database-100-000-films-dans-une-app/

Screenshot : 
![29_04_2018 18_18_38](https://user-images.githubusercontent.com/10851603/39408676-209d2148-4bda-11e8-90b3-0e80dbe55825.jpg)

Steps to reproduce : 
Trivial, just go to the website

Additional info : 
- Nano Defender works on other sites, like http://antiblock.org . So it's just a problem with this particular site.
- Yes, I have Firefox (latest version)
- Yes, I have followed all the steps ( https://jspenguin2017.github.io/uBlockProtector/ )
- Yes, I have installed Nano Defender Firefox 13.61 ( https://github.com/krystian3w/NanoDefenderFirefox/releases )
- Yes, it works on other sites, like said previously. So in my opinion it's not Firefox-related but Nano Defender-related
- OS : Windows 7 x64 SP1

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
Yea just update the filters from dashboard.

**Comment by JoseHidalgo** [comment]
I can confirm that it works indeed. Thank you all.
