### ISSUE TITLE
hollaforums.com

### ISSUE THREAD

**Issue by kreh** [jspenguin2017/uBlockProtector#921]
### Screenshot of the web page): 
![Image](https://i.imgur.com/P2MabRH.png)

### Screenshot of the console:
Included a gif because the console messages disappear, so I had to reload the page to show it.

Gif: ![Gif](https://i.imgur.com/UETseeW.gif)

Image: ![Image](https://i.imgur.com/X14RBiV.png)

### Explain what was not right:
Just went on the webpage and got the anti-adblock message; also upon clicking on the page managed to show ad pop-ups.

### Environment: 

- Operating System and Version: Most recently updated Windows 10 Pro (as of May 1st 2018)
- Browser and Version: Chrome version 66.0.3359.139 
- Adblocker and Version: Nano Adblocker 1.0.0.45

#### Your filter lists (Required): 
![img](https://i.imgur.com/BnmnClJ.png)

Thanks for taking a look at it!

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by jspenguin2017** [comment]
Can't reproduce.

**Comment by kreh** [comment]
Thanks for giving it a look at though; appreciated.

**Comment by jspenguin2017** [comment]
They only trigger the anti-adblock if you come from Google search...
https://github.com/uBlockOrigin/uAssets/issues/2628
