### ISSUE TITLE
cinedoblego.com

### ISSUE THREAD

**Issue by lain566** [jspenguin2017/uBlockProtector#924]
### Test link (required): 
`https://www.cinedoblego.com/the-dragon-spell-2016/`

### Screenshot of the web page (including address bar and extension icons) (required): 
![ver_the_dragon_spell_ 2016 _online_dvdrip_720p_108_2018-05-05_21-04-37](https://user-images.githubusercontent.com/27441315/39666822-26784d7a-50aa-11e8-9bf5-9fa0777da80d.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-05-05_21-13-37](https://user-images.githubusercontent.com/27441315/39666769-6ba3bea8-50a9-11e8-864a-4b81b1b26b1f.png)

### Environment (Required): 

- Operating System and Version: Win 8.1 Pro
- Browser and Version: Chrome 66.0.3359.139 64 bits
- Adblocker and Version: uBO 1.16.4

#### Your filter lists (Required): 
Default + Adblock Warning Removal List + Easylist spanish + nano filters + nano defender integration

### Add everything else that you believe to be useful below (optional): 
Same as https://github.com/jspenguin2017/uBlockProtector/issues/584#issuecomment-386810441
Click on `Desbloquear enlaces de descarga  (1080p)`
then a message appears that says: Just one click on the advertising
<details><summary>It should look like this</summary>

![2018-05-05_21-28-41](https://user-images.githubusercontent.com/27441315/39666974-dd7b6f14-50ac-11e8-8b79-7c9de67b8dfe.jpg)

</details>

No solution in uAssets https://github.com/uBlockOrigin/uAssets/issues/2172

**Comment by jspenguin2017** [comment]
`cinedoblego.com##.accordion .sub-menu:style(display: block !important)`

@mapx- @okiehsch

**Comment by okiehsch** [comment]
Fixed, thx.
