### ISSUE TITLE
anime-update.com

### ISSUE THREAD

**Issue by gavbn** [jspenguin2017/uBlockProtector#926]
### Screenshot of the web page (including address bar and extension icons) (required): 

![Capture](https://user-images.githubusercontent.com/23123477/39675667-0039d0de-517c-11e8-904d-9900dcaab219.PNG)

### Screenshot of the console (press `F12` to bring up the console) (required): 

![vjhjk](https://user-images.githubusercontent.com/23123477/39675687-6066dd08-517c-11e8-8287-7eaa52eacc19.PNG)

### Explain what was not right (optional if obvious): 
I am not able to stream any episode on the mentioned site,due to the anti-adblock

### Environment (Required): 

- Operating System and Version: Windows 7 ultimate
- Browser and Version: chrome 66.0.3359.117 
- Adblocker and Version: Nano adblock 1.0.0.47

#### Your filter lists (Required): 

![janmn](https://user-images.githubusercontent.com/23123477/39675721-e9924d10-517c-11e8-8fd5-106611a4cbc4.PNG)
![astac](https://user-images.githubusercontent.com/23123477/39675729-08a3268e-517d-11e8-87a7-43c34bf2c6a1.PNG)

**Comment by jspenguin2017** [comment]
@okiehsch It's pretty easy to fix with a script snippet, but they register a new domain every other day... 
Current RegExp rule in Nano Defender: `/^anime(?:dao|take|-update)\d*?\.[^.]+$/`
![image](https://user-images.githubusercontent.com/7283682/39676099-c3dad674-5121-11e8-9c97-db5d7fda94ad.png)

**Comment by jspenguin2017** [comment]
That's the problem, 2 days later it'll be `anime-update2.stream`, `3`, `4`, etc. Last time they reached 20+. 
And they also switch TLD, so `.com`, `.xyz`, `.stream`, etc. 

I had quite a few reports here and in the confidential issues tracker and ended up using a RegExp.

**Comment by jspenguin2017** [comment]
One cheap way is to add the first hundred domains according to the pattern and see what they do.

**Comment by okiehsch** [comment]
Let's give it a try.

**Comment by okiehsch** [comment]
Actually I am an idiot why not just use generichide.
`@@||anime-update*.*^$generichide` fixes the issue, so there is no need for a cosmetic filter.

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
There's also `https://animedao19.pro/watch-online/binan-koukou-chikyuu-boueibu-happy-kiss-episode-5/`

**Comment by jspenguin2017** [comment]
And `https://animetake17.pro/watch/binan-koukou-chikyuu-boueibu-happy-kiss-episode-5/`

**Comment by okiehsch** [comment]
Fixed.
