### ISSUE TITLE
new.torrnado.win

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#927]
### Test link (required): 
http://new.torrnado.win/

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-05-07_221231](https://user-images.githubusercontent.com/2828165/39722702-edb938fa-5243-11e8-9f29-91d67de640bd.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-05-07_221250](https://user-images.githubusercontent.com/2828165/39722753-f6da4168-5243-11e8-8ce6-c81534ae0b97.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.47+Nano Defender 14.10

**Your filter lists (Required):**
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Ads (2)
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
**Regions, languages (4)**
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

**Your custom filters (Required if you have any):**
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment]
FYI @okiehsch Annoyance
