### ISSUE TITLE
savetodrive.net

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#928]
### Test link (required): 
https://savetodrive.net/

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-05-08_091828](https://user-images.githubusercontent.com/2828165/39743509-5faad416-52a1-11e8-88f2-821bea94af53.png)
![2018-05-08_091644](https://user-images.githubusercontent.com/2828165/39743516-67b0e006-52a1-11e8-9234-c0b5c50c96ab.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-05-08_091854](https://user-images.githubusercontent.com/2828165/39743529-704b2028-52a1-11e8-877f-bbf7807b7dee.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.47+Nano Defender 14.10

**Your filter lists (Required):**
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Ads (2)
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
**Regions, languages (4)**
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

**Your custom filters (Required if you have any):**
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment]
@okiehsch Also reproduced with uBO (alone).

**Comment by okiehsch** [comment]
Fixed.
