### ISSUE TITLE
gsul.me

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#929]
### Test link (required): 
http://gsul.me/aPt0

### Screenshot of the web page (including address bar and extension icons) (required): 
![2018-05-08_101646](https://user-images.githubusercontent.com/2828165/39745944-28601acc-52a9-11e8-9067-fdbece81c77b.png)

### Screenshot of the console (press `F12` to bring up the console) (required): 
![2018-05-08_101806](https://user-images.githubusercontent.com/2828165/39745959-309a3420-52a9-11e8-8ca0-d0030c488192.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.47+Nano Defender 14.10

**Your filter lists (Required):**
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Ads (2)
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
Regions, languages (4)
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

**Your custom filters (Required if you have any):**
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by ghajini** [comment]
how to defuse `inclk.com` {present in dozens of movie sites & file sharing sites} script globally....easylist has filter for that, but this opens popup,closes then.....

**Comment by jspenguin2017** [comment]
@okiehsch Seems `gsul.me##script:inject(nano-setInterval-booster.js)` works.

**Comment by okiehsch** [comment]
@ghajini there is no way to globally defuse it, the standard fix is
`example.com##script:inject(abort-current-inline-script.js, decodeURI, decodeURIComponent)`
this will not work with `gsul.me` using Chrome, because of a race conditon.
If you use Firefox 
`example.com##^script:has-text(decodeURIComponent)`
will always work.

**Comment by okiehsch** [comment]
Fixed.
