### ISSUE TITLE
damasgate.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#930]
### Test link (required):
http://www.damasgate.com/vb/t432809/

### Screenshot of the web page (including address bar and extension icons) (required):
![2018-05-10_074013](https://user-images.githubusercontent.com/2828165/39854545-6f0dd8d0-5428-11e8-8792-e58886400fea.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2018-05-10_074034](https://user-images.githubusercontent.com/2828165/39854555-768af1ba-5428-11e8-8066-b8577b690eda.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.47+Nano Defender 14.10

**Your filter lists (Required):**
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
**Ads (2)**
Adblock Warning Removal List​
EasyList
**Privacy (1)**
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
**Regions, languages (4)**
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

**Your custom filters (Required if you have any):**
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment]
@okiehsch
