### ISSUE TITLE
file-upload.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#931]
**Test link**: https://www.file-upload.com/iq0x1yufxamx

There is a timer of 30 seconds in free download. possible to patch?

**Comment by jspenguin2017** [comment]
If I recall right this is validated on server side.

**Comment by jspenguin2017** [comment]
Yea it's validated on server side: 
![image](https://user-images.githubusercontent.com/7283682/39959158-077a4eca-55cb-11e8-931f-9b156bb94d31.png)
