### ISSUE TITLE
confused about firefox version

### ISSUE THREAD

**Issue by Francois-dag** [jspenguin2017/uBlockProtector#932]
Hugo,

I'm a bit confused about the firefox version of your ublockProtector. I'm currently installing the
krystian3w release (https://github.com/krystian3w/NanoDefenderFirefox/releases) and by now I've
just discovered that your are requesting maintainers on your page (https://jspenguin2017.github.io/uBlockProtector/).
Sounds strange to me, any infos ?
By now, the krystian3w is self signed and get a "DEV" icon within the last firefox ...

Cheers.

François

**Comment by jspenguin2017** [comment]
You can install any version you'd like, but I only support and update the official build: https://github.com/jspenguin2017/uBlockProtector/releases

I'm looking for maintainer that can produce signed official builds, they need to: 
- Use the new build engine and produce optimized build
- Accept platform-specific issues and pull request changes to platform scripts

If you see "DEV" it means the build is not optimized.

**Comment by Francois-dag** [comment]
Thanks a lot, may be you need to inform on your page about this kind of not optimized builds !

**Comment by jspenguin2017** [comment]
Yea... The performance difference is minimal, the big problem is that a lot of unofficial builds are signing Chrome builds and hoping that it works, which it does for most cases, but not always.

**Comment by ghajini** [comment]
.xpi for Firefox android

**Comment by xhiddle** [comment]
@jspenguin2017  
Does this fork qualify :

https://github.com/LiCybora/NanoDefenderFirefox

Its xpi are hosted on AMO also.

**Comment by jspenguin2017** [comment]
@xhiddle Yes, that is the official port.
