### ISSUE TITLE
o2.pl

### ISSUE THREAD

**Issue by HateAds** [jspenguin2017/uBlockProtector#933]
Ads in the video player.

### Test link (required):
https://www.o2.pl/artykul/ojciec-gwalcil-corke-i-jej-przyjaciolki-wypedzal-demony-6251785164191361a

### Screenshot of the web page (including address bar and extension icons) (required):
![1](https://user-images.githubusercontent.com/29756590/40016377-6b19079a-57b6-11e8-8650-f2518135a0ab.png)

### Screenshot of the console (press F12 to bring up the console) (required):
![console 1](https://user-images.githubusercontent.com/29756590/40016419-890d7d1c-57b6-11e8-86a7-14dc4a4e4a79.png)
![console 2](https://user-images.githubusercontent.com/29756590/40016431-8d398a8e-57b6-11e8-836d-8a0989eaed3d.png)

### Environment (Required):
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 66.0.3359.170 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.48 + Nano Defender 14.23

### Your filter lists (Required):
Nano Defender Integration
Nano filters
Nano filters – Timer bypassing (sometimes works)
Nano filters – Whitelist
uBlock filters
uBlock filters – Badware risks
uBlock filters – Privacy
uBlock filters – Resource abuse
uBlock filters – Unbreak
Adblock Warning Removal List
EasyList
EasyPrivacy
Malware Domain List
Malware domains​
Peter Lowe’s Ad and tracking server list
POL: Official Polish filters for AdBlock, uBlock Origin & AdGuard​

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
@MajkiIT 
`||wpimg.pl^$media,redirect=noopmp3-0.1s,domain=o2.pl`

**Comment by MajkiIT** [comment]
@okiehsch Thanks a lot

**Comment by HateAds** [comment]
Thanks guys, fixed.
