### ISSUE TITLE
nano defender waterfox?

### ISSUE THREAD

**Issue by mradzkii** [jspenguin2017/uBlockProtector#934]
none of the latest nano releases support waterfox?

**Comment by jspenguin2017** [comment]
The Firefox build should work fine.

**Comment by mradzkii** [comment]
no it don't work, that's why im saying i can't get any of em to install, incompatible issue

**Comment by gabri25ele** [comment]
Nano Defender in Waterfox

![immagine](https://user-images.githubusercontent.com/33927879/40103995-66712d82-58ef-11e8-80ec-230fc2637773.png)
