### ISSUE TITLE
vivads.net

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#937]
### Test link (required):
http://vivads.net/my

### Screenshot of the web page (including address bar and extension icons) (required):
![2018-05-16_212201](https://user-images.githubusercontent.com/2828165/40139162-4bd75856-594f-11e8-864a-9b27e8d7d54d.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![2018-05-16_212222](https://user-images.githubusercontent.com/2828165/40139173-55ec26d2-594f-11e8-9145-a568d596cdfc.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.48+Nano Defender 14.28

**Your filter lists (Required):**
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
**Ads (2)**
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
**Regions, languages (4)**
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

**Your custom filters (Required if you have any):**
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment]
I can't reproduce.

**Comment by titosalah** [comment]
@jspenguin2017 why bro ?? work for you

**Comment by jspenguin2017** [comment]
I see `@@||vivads.net^$generichide` in uBlock filters which fixes it. Make sure to update your filters.
