### ISSUE TITLE
Nano Defender could not be installed because it is not compatible with Waterfox 56.2.0

### ISSUE THREAD

**Issue by melnation-com** [jspenguin2017/uBlockProtector#938]
![Alt Text](https://snag.gy/yS6OBr.jpg)

tried both the dev versions and public release versions

https://github.com/krystian3w/NanoDefenderFirefox/releases
https://github.com/jspenguin2017/uBlockProtector/releases

site I used this for http://anonymz.com/?https://3dzone.link/

**Comment by AldegarDespoina** [comment]
I'm pretty sure it's a bug on the latest version of Waterfox (56.2.0) because on the previous version 56.1.0 it totally works fine.

**Comment by melnation-com** [comment]
yeah it totally worked fine before smooth as silk then the genius Waterfox who updates every 2.5 mos. decided to update now instead, I just barely enjoyed this plugin for 42 hrs., now I'm back being blocked again, gonna test

**Comment by AldegarDespoina** [comment]
Found a solution...

type: **about:config** in the address bar

Add:

Right Click > New >Boolean > **extensions.checkCompatibility.56.2** > set to false

**Comment by jspenguin2017** [comment]
The Firefox build requires new API from Firefox 57, can you try the Chrome build until Waterfox catches up?

**Comment by melnation-com** [comment]
Thanks @AldegarDespoina , I was gonna do my own fix by simply reverting back to 56.1.0, since I cant find any installers specifically on that version, so I checked their url download

https://storage-waterfox.netdna-ssl.com/releases/win64/installer/Waterfox%2056.2.0%20Setup.exe

changed to this (replaced 2.0 to 1.0)

https://storage-waterfox.netdna-ssl.com/releases/win64/installer/Waterfox%2056.1.0%20Setup.exe
-----------------------------------------------------------------------------------------------------------

@jspenguin2017 Thanks for the info, funny it worked on my Waterfox 56.1.0 but whatever.

**Comment by jspenguin2017** [comment]
Nano Defender is highly modular, so if a small part crashes, other parts will usually keep working like normal. If you don't have new API from Firefox 57, then the partial solution for `uplynk.com` won't work.

**Comment by melnation-com** [comment]
Okay , they've blocked ublock protector or nano defender again, tried both the dev versions and public release versions.

https://github.com/krystian3w/NanoDefenderFirefox/releases
https://github.com/jspenguin2017/uBlockProtector/releases

Waterfox 56.2.0

**Comment by melnation-com** [comment]
But Session Manager doesn't work on 57 anymore https://addons.mozilla.org/en-US/firefox/addon/session-manager/reviews/

**Comment by jspenguin2017** [comment]
Again, I need new API from Firefox 57, it's up to you to choose what to use. You can also use the Chrome build which does not reference the new Firefox APIs.
