### ISSUE TITLE
ignore

### ISSUE THREAD

**Issue by 1145141919** [jspenguin2017/uBlockProtector#939]
### Test link (required):
 http://dl.ccbluex.net/download/skip/index.php?target=TGlxdWlkQm91bmNlLzEuOC9nb2QvTGlxdWlkQm91bmNlMS44LjktYjQ4LnppcA==

### Screenshot of the web page (including address bar and extension icons) (required):
]](https://gyazo.com/b3196b5e3fcaa9499a6de3eb68052535)

### Screenshot of the console (press `F12` to bring up the console) (required):
   [https://gyazo.com/c9b8628f6578165934255d561b933013](url)

### Environment (Required):

- Operating System and Version: Windows10 Home
- Browser and Version: Chrome 66.0.3359.181 (Official Build) （64bit）

- Adblocker and Version: Nano Defender 14.31 Nano Adblocker v1.0.0.49

#### Your filter lists (Required):
    [https://gyazo.com/b3196b5e3fcaa9499a6de3eb68052535](url)

**Comment by jspenguin2017** [comment]
Duplicate of https://github.com/jspenguin2017/uBlockProtector/issues/940
