### ISSUE TITLE
dl.ccbluex.net

### ISSUE THREAD

**Issue by 1145141919** [jspenguin2017/uBlockProtector#940]
### Test link (required):

`http://dl.ccbluex.net/download/skip/index.php?target=TGlxdWlkQm91bmNlLzEuOC9nb2QvTGlxdWlkQm91bmNlMS44LjktYjQ4LnppcA==`

and

`http://dl.ccbluex.net/download/index.php?file=TGlxdWlkQm91bmNlLzEuOC9nb2QvTGlxdWlkQm91bmNlMS44LjktYjQ4LnppcA==`

### Screenshot of the web page (including address bar and extension icons) (required):

https://gyazo.com/f2580311894b4900fefa275bfc9df751

and

https://gyazo.com/74415d564d14471f183565af4379bf1e

### Screenshot of the console (press `F12` to bring up the console) (required):

https://gyazo.com/c9b8628f6578165934255d561b933013

and

https://gyazo.com/924f3f38774c4bf884ce80dfe5ce2c8b

### Environment (Required):

- Operating System and Version:  Windows10 Home
- Browser and Version:  Chrome 66.0.3359.181 (Official Build) （64bit）
- Adblocker and Version: Nano Defender 14.31 Nano Adblocker v1.0.0.49

#### Your filter lists (Required):

https://gyazo.com/b3196b5e3fcaa9499a6de3eb68052535

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by timmyrs** [comment]
https://github.com/hellshltd/Universal-Bypass/blob/master/bypasses/file/dl.ccbluex.net.js

You're welcome.

**Comment by okiehsch** [comment]
@jspenguin2017 does
`ccbluex.net##script:inject(set-constant.js, passed, true)`
work consistently on your end?
I ask because I got the adblock message one time even with this filter enabled.
If you have the same issue I can use
`ccbluex.net##.banner:style(height: 1px !important)`

**Comment by jspenguin2017** [comment]
Just the first rule works on my end.

**Comment by okiehsch** [comment]
Fixed.
