### ISSUE TITLE
htmlpublish.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#943]
Test link : http://www.htmlpublish.com/convert-pdf-to-html/success-p.aspx?zip=DocStorage/65658305/bcl_65658305.htm&app=pdf2word

Screenshot - 
![screenshot_11](https://user-images.githubusercontent.com/18257605/40707292-e775f452-640d-11e8-8b03-39d0f901d623.png)

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
