### ISSUE TITLE
godmode-trader.de

### ISSUE THREAD

**Issue by AlleSchonWeg** [jspenguin2017/uBlockProtector#944]
### Screenshot of the web page (including address bar and extension icons) (required):
![unbenannt](https://user-images.githubusercontent.com/6727366/40718207-88b59c72-640f-11e8-8b2a-8ab4fb8ed4ea.PNG)

### Environment (Required):
- Operating System and Version: Win 10
- Browser and Version: Chrome 66.0.3359.181 (Offizieller Build) (64-Bit)
- Adblocker and Version: uBlock Origin 1.16.8

#### Your filter lists (Required):
uBlock-eigene Filterlisten (5/7)
uBlock filters ​​​​​5.968 benutzt aus 5.970​​​​
uBlock filters – Badware risks​​​​​ 11 benutzt aus 11​​​​
uBlock filters – Privacy ​​​​​96 benutzt aus 97​​​​
uBlock filters – Resource abuse​​​​​ 57 benutzt aus 259​​​​
uBlock filters – Unbreak ​​​​​439 benutzt aus 439​​​​
Werbung (2/4)
Adblock Warning Removal List ​​​​​433 benutzt aus 439​​​​
EasyList​​​​​82.308 benutzt aus 82.452​​​​
Privatsphäre (1/3)
EasyPrivacy​​​​​ 14.898 benutzt aus 15.077​​​​
Domains mit Schadsoftware (2/4)
Malware Domain List​​​​​ 1.116 benutzt aus 1.131​​​​
Malware domains 22.330 benutzt aus 22.330​​​​
Belästigungen (0/5)
Verschiedene Zwecke (1/4)
Peter Lowe’s Ad and tracking server list ​​​​​2.635 benutzt aus 2.639​​​​
Regionen, Sprachen (1/36)
DEU: EasyList Germany​​​​​ 9.394 benutzt aus 9.414​​​​
Benutzerdefiniert (3/3)
Nano Defender Integration ​​​​​2.641 benutzt aus 2.750​​​​
Nano filters​​​​​ 85 benutzt aus 86​​​​
Nano filters - Whitelist​​​​​0 benutzt aus 0​​​​

**Comment by jspenguin2017** [comment]
Is this hard anti-adblock? What is `quotepush`? 

@okiehsch

**Comment by AlleSchonWeg** [comment]
Hi,
i think quotepush are live stock prices.

**Comment by okiehsch** [comment]
Fixed, thx.
The message states that all "live stock price updates"  will be disabled unless you disable your adblocking software, so it is a hard anti-adblock script.

**Comment by AlleSchonWeg** [comment]
anti-adblock is back again on godmode-trader :(

**Comment by jspenguin2017** [comment]
Seems to be just annoyance. Does anything broken? Or the one-time overlay is the only problem?

**Comment by okiehsch** [comment]
Fixed.
