### ISSUE TITLE
download.hr

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#946]
### Test link (required):
https://www.download.hr/review-pyload.html

### Screenshot of the console (press `F12` to bring up the console) (required):
![capture](https://user-images.githubusercontent.com/15007183/40836296-29fcd636-6564-11e8-8cc1-2b184dbca7c3.PNG)

### Environment (Required):

- Operating System and Version: win7pro
- Browser and Version: Chrome Version 66.0.3359.181 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.16.8

#### Your filter lists (Required):
stock ubo + pl filters

**Comment by jspenguin2017** [comment]
@okiehsch FYI annoyance

**Comment by okiehsch** [comment]
Fixed.
