### ISSUE TITLE
myfavoritecontent.com

### ISSUE THREAD

**Issue by coachq127** [jspenguin2017/uBlockProtector#947]
### Test link (required):

https://www.myfavoritecontent.com/list/25-simple-ideas-you-can-use-today-to-help-prevent-alzheimers-disease/Pf039dfdd
### Screenshot of the web page (including address bar and extension icons) (required):

http://prntscr.com/jppwzs
### Screenshot of the console (press `F12` to bring up the console) (required):

http://prntscr.com/jppx4l
### Explain what was not right (optional if obvious):
Adblocker detected,  and timer likely not bypassed.  (There's a timer between pages.

### Reproduction steps (optional if trivial):
Just go to the page and a messenge will pop up saying that adblock was detected.

### Environment (Required):

- Operating System and Version: Windows 10
- Browser and Version:  Latest Chrome
- Adblocker and Version: Nano Defender (Lastest)

#### Your filter lists (Required):

All default.

#### Your custom filters (Required if you have any):

N/A
### Add everything else that you believe to be useful below (optional):
Please fix the timer as well as the anti-adblock.  Thanks!

**Comment by jspenguin2017** [comment]
@okiehsch FYI annoyance

**Comment by okiehsch** [comment]
Added, thx.
