### ISSUE TITLE
prem.link

### ISSUE THREAD

**Issue by beenmoov** [jspenguin2017/uBlockProtector#948]
![screenshot-prem link-2018 06 02-10-48-53](https://user-images.githubusercontent.com/22501834/40872180-cc85f952-6652-11e8-9236-0cee7846b1be.png)

**Comment by jspenguin2017** [comment]
I need a test link.

**Comment by ghajini** [comment]
**unable to reproduce**
requires prem.link account.
user name= binkrass, password= alter123

tesst link for leeching on site=
http://www.dailymotion.com/video/x6em8to

**Comment by jspenguin2017** [comment]
Can't reproduce neither. 
![image](https://user-images.githubusercontent.com/7283682/40878992-8817acda-6656-11e8-9b9c-7005568311a5.png)

**Comment by beenmoov** [comment]
thx it has been solved
