### ISSUE TITLE
douploads.com, filebebo.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#949]
Test Link: https://douploads.com/otqrbgqeyohu

Request:

Patch 15 sec timer?
Untick the `Download our offers` by default, because it's just ads.

--------------------------

Test Link: https://filebebo.com/d/82j0s82yzksf
Patch 10 sec timer?

**Comment by jspenguin2017** [comment]
`douploads.com` validates the timer on server side. 

---

@okiehsch Timer skipping for `filebebo.com`: 
```
filebebo.com##script:inject(nano-setTimeout-booster.js)
```

**Comment by okiehsch** [comment]
Added, thx.

**Comment by Zhangsun321** [comment]
get jdownloader...   the best fix for all those annoying file storage sites!

**Comment by jspenguin2017** [comment]
For unticking the checkbox, I opened another issue for it: https://github.com/NanoAdblocker/NanoFilters/issues/99
