### ISSUE TITLE
kgw.com

### ISSUE THREAD

**Issue by 3dsboy08** [jspenguin2017/uBlockProtector#950]
### Screenshot of the web page (including address bar and extension icons) (required):
![image](https://user-images.githubusercontent.com/14914815/41124566-60cb8070-6a70-11e8-836b-e42a5d86017e.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
![image](https://user-images.githubusercontent.com/14914815/41124599-7ba2f96e-6a70-11e8-9997-22d871bd8911.png)

### Explain what was not right (optional if obvious):
Sets page contents to blank, I am guessing its some sort of anti-adblock detection as it says so in the console and the issue does not happen with Nano Adblocker disabled.

### Reproduction steps (optional if trivial):
Go to page.

### Environment (Required):

- Operating System and Version: Windows 10 x64
- Browser and Version: Chrome 66
- Adblocker and Version: Nano Adblocker + Nano Defender, latest version.

#### Your filter lists (Required): Defaults from Nano Adblocker.
![image](https://user-images.githubusercontent.com/14914815/41124823-288fee48-6a71-11e8-9954-28f5a82ff247.png)

#### Your custom filters (Required if you have any):
None.

### Add everything else that you believe to be useful below (optional):
None.

**Comment by jspenguin2017** [comment]
It gives me 403, probably GeoLock. Which country are you in?

**Comment by 3dsboy08** [comment]
United States, try a western location (California/San Fran) in your VPN.
