### ISSUE TITLE
techradar.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#952]
### Test link (required):
https://www.techradar.com/

### Screenshot of the console (press `F12` to bring up the console) (required):
![capture](https://user-images.githubusercontent.com/15007183/41498157-1a4c7f62-7134-11e8-82cf-cfab04459db8.PNG)

### Environment (Required):

- Operating System and Version: win7pro
- Browser and Version: Chrome Version 67.0.3396.87 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.16.10

#### Your filter lists (Required):
stock ubo + pl list

**Comment by melnation-com** [comment]
It's abandoned now, atleast that's what said in the release section

**Comment by jspenguin2017** [comment]
I thought it was already fixed. Update your filters?

**Comment by xxcriticxx** [comment]
fixed updating filters did it
