### ISSUE TITLE
How to use two resource urls at the same time?

### ISSUE THREAD

**Issue by mozkan007** [jspenguin2017/uBlockProtector#960]
Hi, this is not an issue, I just wonder that how can I use the resource urls below together at the same time on Ublock Origin?

-https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/resources.txt
-https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoFilters/NanoResources.txt

You said that you can merge manually resources on the Ublockprotector info page but I do not know how I can do this.

**Comment by jspenguin2017** [comment]
You don't need to load uBO's resource manually, it is built-in.
