### ISSUE TITLE
techradar.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#962]
### Test link (required):
https://www.techradar.com/news/amazon-prime-day-2018-date-leaked-36-hours-of-deals-start-midday-on-july-16th

### Screenshot of the console (press `F12` to bring up the console) (required):
![capture](https://user-images.githubusercontent.com/15007183/42214133-a2812c28-7e88-11e8-8869-a4b152a5a9ec.PNG)

### Environment (Required):

- Operating System and Version: win7pro
- Browser and Version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.16.10

#### Your filter lists (Required):
reg ubo + pl filters

**Comment by xxcriticxx** [comment]
updating filters helped again. why do i have to update manually if i have it set to automatic?

**Comment by jspenguin2017** [comment]
Can't reproduce. It's a problem on your side, is the extension storage reset by something?

**Comment by xxcriticxx** [comment]
i use plugin that clears cookies + browsing history

**Comment by jspenguin2017** [comment]
Either way, since you are using uBO, it's not my problem.

**Comment by jspenguin2017** [comment]
Either way, you are using uBO, post to their issues tracker.
