### ISSUE TITLE
phillymag.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#963]
### Test link (required):
https://www.phillymag.com/welcome/3009121/single/https%3A%2F%2Fwww.phillymag.com%2Fticket%2F2015%2F09%2F05%2Fbradley-cooper-steve-cookies%3Fpam-referer%3Dhttps%253A%252F%252Fwww.google.com%252F/

### Screenshot of the console (press `F12` to bring up the console) (required):
![capture](https://user-images.githubusercontent.com/15007183/42330836-00f2e20a-8042-11e8-8866-e21da8d22858.PNG)

### Environment (Required):

- Operating System and Version: win7pro
- Browser and Version: chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.16.12

#### Your filter lists (Required):
ubo stock + pl list 

### Add everything else that you believe to be useful below (optional):

adblock message disappears by itself

**Comment by jspenguin2017** [comment]
`phillymag.com##.gtp-ad`

FYI @okiehsch
