### ISSUE TITLE
webmd.com

### ISSUE THREAD

**Issue by ghajini** [jspenguin2017/uBlockProtector#964]
@jspenguin2017(now you will say ping is not required :bowtie:) @gorhill
i am prevented from posting at `gorhill/ubo extra` repo (may be locked? repo), that's why iam posting here
:disappointed: :disappointed:
### Test link (required):
https://www.webmd.com/baby/guide/taking-medicine-during-pregnancy#1

### Screenshot of the web page (including address bar and extension icons) (required)
![screenshot 18](https://user-images.githubusercontent.com/20338483/42418876-62d83880-82c7-11e8-9989-c0bf77596928.png)
![screenshot 19](https://user-images.githubusercontent.com/20338483/42418877-63237728-82c7-11e8-9312-7e89a95849dd.png)

### Screenshot of the console (press `F12` to bring up the console) (required):
not possible in case of g00

### Environment (Required):

- Operating System and Version: win10
- Browser and Version: chrome Version 67.0.3396.99 (Official Build) (64-bit)

- Adblocker and Version: nanoadblocker + nanodefender updated

#### Your filter lists (Required):5 autoplay
default settings

### Add everything else that you believe to be useful below (optional):

using decentraleyes and disable html5 autoplay

**Comment by gorhill** [comment]
> i am prevented from posting at gorhill/ubo extra repo (may be locked? repo)

No you are not, uBO-Extra has never been restricted, except for the wiki pages.
