### ISSUE TITLE
multifilemirror.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#965]
### Test link (required):
https://multifilemirror.com/xfccpj77aiq2/repository.podpis-1.4.2.zip.html

### Screenshot of the console (press `F12` to bring up the console) (required):
![capture](https://user-images.githubusercontent.com/15007183/42425524-b16b0aac-82ec-11e8-8526-8e9a5a1d811a.PNG)

### Environment (Required):

- Operating System and Version: win7pro
- Browser and Version: Chrome Version 67.0.3396.99 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.16.12

#### Your filter lists (Required):
stock ubo + pl filter list

**Comment by jspenguin2017** [comment]
FYI @okiehsch

**Comment by okiehsch** [comment]
Fixed.
