### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by lukjan32** [jspenguin2017/uBlockProtector#966]
there is a blockade on player.pl, I have opera 54 and ublock origins

**Comment by jspenguin2017** [comment]
Fill the template.

**Comment by lukjan32** [comment]
![1](https://user-images.githubusercontent.com/17565773/42513437-3ad5ad40-8457-11e8-81a8-31d5d169e41b.jpg)

**Comment by jspenguin2017** [comment]
**Fill the template.**
