### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by lukjan32** [jspenguin2017/uBlockProtector#967]
there is a blockade on player.pl

![1](https://user-images.githubusercontent.com/17565773/42528641-6fc37dfa-847c-11e8-884b-1a0675d5a8ef.jpg)

the wheel is spinning all the time.

here they are advertising before and during the material.

I have windows 10.
opera 54.
ublock origins.

**Comment by jspenguin2017** [comment]
It's working fine for me. Please check troubleshooting tips [here](https://jspenguin2017.github.io/uBlockProtector/#troubleshooting), if that doesn't work, I need: 
- The country that you're in
- The full list of extension that you have installed
- The full list of filters in uBO

**Comment by lukjan32** [comment]
![list](https://user-images.githubusercontent.com/17565773/42554830-9db6f92a-84e6-11e8-8ef1-f8128bc38c28.jpg)

Here are my filters.
the latest versions.
I'm from Poland

from Poland, they also did not help

**Comment by jspenguin2017** [comment]
I also need to know: 
- The complete list of extensions that you have installed, including their version
- The complete list of your custom filter rules

**Comment by lukjan32** [comment]
I have only ublock origins 1.16.6

**Comment by jspenguin2017** [comment]
This is issues tracker for Nano Defender, if you are only using uBO, report the problem to uAssets.

**Comment by lukjan32** [comment]
I reported, they did not help. Nano defender, install does not go to the opera.

**Comment by jspenguin2017** [comment]
I thought Opera can install extensions from Chrome Web Store.

**Comment by lukjan32** [comment]
maybe, but a red icon appears at the bottom.

**Comment by krystian3w** [comment]
Backup [passwords](https://forums.opera.com/topic/21433/import-and-export-passwords-from-or-to-a-file/3) and bookmarks and Unistall Opera by Revo:

- https://portableapps.com/apps/utilities/revo_uninstaller_portable
- https://www.revouninstaller.com/download-free-portable.php

**Comment by lukjan32** [comment]
will not help

**Comment by lain566** [comment]
Nano Defender can be installed on Opera
https://addons.opera.com/extensions/details/install-chrome-extensions/

![acerca_de_opera_-_opera_2018-07-12_14-49-55](https://user-images.githubusercontent.com/27441315/42634384-5ebf00a2-85e3-11e8-9b8b-0f755d137e96.png)

**Comment by lukjan32** [comment]
![1](https://user-images.githubusercontent.com/17565773/42635350-26ff7ce8-85e6-11e8-80c4-df1e05e7abb5.jpg)
![2](https://user-images.githubusercontent.com/17565773/42635355-2b49143a-85e6-11e8-9f9e-02e0086d9bf9.jpg)

**Comment by jspenguin2017** [comment]
I don't know, try reinstall your browser.

**Comment by lukjan32** [comment]
okay, I'll try

**Comment by lain566** [comment]
@lukjan32 You have to enable Developer mode in Extensions

![42635355-2b49143a-85e6-11e8-9f9e-02e0086d9bf9](https://user-images.githubusercontent.com/27441315/42636456-27265996-85e9-11e8-83fe-2be69680b74e.jpg)

**Comment by lukjan32** [comment]
also, you can not re-install
