### ISSUE TITLE
iosgods.com

### ISSUE THREAD

**Issue by Dibbyo456** [jspenguin2017/uBlockProtector#968]
Test link: https://iosgods.com/topic/72108-how-to-get-iosgods-deb-hacks-working-with-electra-110-1131/

![screenshot_11](https://user-images.githubusercontent.com/18257605/42733617-f808b468-8851-11e8-97a1-0ce1a31b0bbb.png)

**Comment by jspenguin2017** [comment]
FYI @okiehsch

**Comment by okiehsch** [comment]
Fixed.
