### ISSUE TITLE
Reek + userscript vs Nano Defender

### ISSUE THREAD

**Issue by bryce-lynch** [jspenguin2017/uBlockProtector#969]
reek's anti-adblock-killer has not been updated since 2016, but it also employs an userscript in addition to the list. I was wondering how does Nano Defender compare to it? Is reek's script still useful/needed for a more effective protection?

**Comment by SkeletalDemise** [comment]
No. As you said, it hasn't been updated since late 2016. Most, if not all of it's solutions are probably long broken/not working by now. Whereas Nano Defender is actively updated.

**Comment by xlollomanx** [comment]
reek is abandoned since many months, nano defender do the same job. If you have nano adblocker + nano defender this works much better than any script

**Comment by bryce-lynch** [comment]
Ok, thanks for your replies. My only concern now is that for the Firefox version I have to install an unofficial, forked beta unlisted from AMO, and I can't even build it myself with NanoBuild as "packaging for firefox is disabled". Well, c'est la vie...

**Comment by LiCybora** [comment]
> I can't even build it myself with NanoBuild as "packaging for firefox is disabled"

You can. What you are forbidden is using NanoBuild for publishing on AMO. The command `node . --firefox --pack` will works and packs zip file(s) which can be used for installation.

**Comment by jspenguin2017** [comment]
You can use what you want, but unless you are using a supported setup, it's up to you to solve any problems you have. 

-----

Packaging requires Mozilla's Node module, which contains a vulnerability that Mozilla isn't fixing, that's why packaging is disabled. It does not prevent you from building Firefox builds. 
![image](https://user-images.githubusercontent.com/7283682/43036669-289b4be8-8cc3-11e8-9f9a-62dbdac2b09f.png)

**Comment by LiCybora** [comment]
> Packaging requires Mozilla's Node module, which contains a vulnerability that Mozilla isn't fixing,

Isn't sign-addon 0.3.1 fixed it? (at least, claimed by Mozilla guys. Correct me if I am wrong.)

**Comment by jspenguin2017** [comment]
Actually yes, I totally missed that. But that still have nothing to do with building the extension, only publishing to AMO.

**Comment by bryce-lynch** [comment]
Thank you for your explanations.
