### ISSUE TITLE
freephonenum.com

### ISSUE THREAD

**Issue by titosalah** [jspenguin2017/uBlockProtector#971]
### Test link (required):
https://freephonenum.com/

### Screenshot of the web page (including address bar and extension icons) (required):
![2018-07-24_105205](https://user-images.githubusercontent.com/2828165/43127490-e5e33878-8f2f-11e8-8356-5739dc02ad0d.png)

### Screenshot of the console (press `F12` to bring up the console) (required):

![2018-07-24_105333](https://user-images.githubusercontent.com/2828165/43127499-ed621fa6-8f2f-11e8-97c7-c668ac57ea63.png)

**Environment (Required):**
Operating System and Version: WIN 7 SP1 64BIT
Browser and Version: Chrome Version 67.0.3396.79 (Official Build) (64-bit)
Adblocker and Version: Nano Adblocker 1.0.0.58+Nano Defender 15.0.0.18

**Your filter lists (Required):**
My filters​​​​​
Nano Defender Integration​​​
Nano filters​
Nano filters – Timer bypassing (sometimes works)​
Nano filters – Whitelist​​​​​
uBlock filters​
uBlock filters – Badware risks
uBlock filters – Privacy​​​​​
uBlock filters – Resource abuse
uBlock filters – Unbreak
Ads (2)
Adblock Warning Removal List​
EasyList
Privacy (1)
EasyPrivacy​
Malware Domain List​​​​​
Malware domains​
Peter Lowe’s Ad and tracking server list
Regions, languages (4)
ARA: Liste AR
IRN: Adblock-Iran​
RUS: Adguard Russian Filter​
RUS: RU AdList​

**Your custom filters (Required if you have any):**
https://raw.githubusercontent.com/ZeroDot1/CoinBlockerLists/master/list_browser.txt

**Comment by jspenguin2017** [comment]
@okiehsch

**Comment by okiehsch** [comment]
Fixed.
