### ISSUE TITLE
emurom.net

### ISSUE THREAD

**Issue by IoanPaleru** [jspenguin2017/uBlockProtector#972]
https://www.emurom.net/us/emulation/arcade-pcb-roms/detail-20863-hydro.thunder.html

![emurom net](https://user-images.githubusercontent.com/35790889/43201206-ceeed58a-8fe5-11e8-9580-92bbe05261a2.jpg)

![emurom net console](https://user-images.githubusercontent.com/35790889/43201260-fda89c9e-8fe5-11e8-9f9b-e36073ee2eeb.jpg)

There's an adblocker detected message that says "Nous avons détecté un bloqueur de publicité sur votre navigateur. Veuillez le desactiver pour avoir accès aux téléchargements du site." which asks you to deactivate the adblocker to have access to downloads on the site. Is there a way to fix that? Thanks.

Windows 7 home premium 64 bit
Waterfox 56.2.2 (64-bit)
uBlock Origin 1.16.14
Nano Defender 15.0.0.16

**Comment by jspenguin2017** [comment]
@okiehsch FYI annoyance.

**Comment by okiehsch** [comment]
Fixed.

**Comment by IoanPaleru** [comment]
Ok, thank you.
