### ISSUE TITLE
pgatour.com, newatlas.com

### ISSUE THREAD

**Issue by xxcriticxx** [jspenguin2017/uBlockProtector#974]
### Test link (required):
https://www.pgatour.com/

### Screenshot of the console (press `F12` to bring up the console) (required):
![capture](https://user-images.githubusercontent.com/15007183/43429285-985e891c-9430-11e8-85eb-6910edf5eedb.PNG)

### Environment (Required):

- Operating System and Version: win7pro
- Browser and Version: Chrome Version 68.0.3440.75 (Official Build) (64-bit)
- Adblocker and Version: ubo 1.16.14

#### Your filter lists (Required):
pl filter + ubo stock

**Comment by jspenguin2017** [comment]
@okiehsch FYI. Annoyance.

**Comment by okiehsch** [comment]
Fixed.

**Comment by jspenguin2017** [comment]
I can reproduce on `https://newatlas.com/` but not `patch.com`.

**Comment by okiehsch** [comment]
`patch.com` geoblocks me, so if you say cou can't reproduce I will remove the entry.

**Comment by jspenguin2017** [comment]
I don't see it defining `admiral`, I'm not sure if it'll be different in another region though. 
![image](https://user-images.githubusercontent.com/7283682/43431523-6ecc642a-942b-11e8-8cd6-beb5dbcfd099.png)

**Comment by jspenguin2017** [comment]
Tried with US VPN, still can't reproduce.

**Comment by okiehsch** [comment]
I have removed `patch.com`. https://github.com/uBlockOrigin/uAssets/commit/938bbe28e56f1b198398528db7b6e3d33acea558
