### ISSUE TITLE
tvplay.tv3.lt

### ISSUE THREAD

**Issue by sangas** [jspenguin2017/uBlockProtector#977]
### Test link (required):
https://tvplay.tv3.lt/vedes-ir-turi-vaiku/vedes-ir-turi-vaiku-10278194/

### Screenshot of the web page (including address bar and extension icons) (required):
![image](https://user-images.githubusercontent.com/10050905/43541604-75e2f5c2-95d3-11e8-9af2-dd56a1f07961.png)

### Explain what was not right (optional if obvious):
For the first time it plays video without ads. When trying watch another video it shows Ad Blocker message. After few hours, again first video is playing without ads.

### Environment (Required):

- Operating System and Version: Windows 10 Pro x64
- Browser and Version: Chrome Version 68.0.3440.84 (Official Build) (64-bit)
- Adblocker and Version: uBlock Origin v1.16.14

#### Your filter lists (Required):

![image](https://user-images.githubusercontent.com/10050905/43542140-e6e52a1e-95d4-11e8-8fba-87a3ac04af40.png)

**Comment by jspenguin2017** [comment]
Can't reproduce, works fine for me. 
![image](https://user-images.githubusercontent.com/7283682/43554965-bdb6bae2-95b4-11e8-9d77-dbc0b060835a.png)
