### ISSUE TITLE
itavisen.no

### ISSUE THREAD

**Issue by THEtomaso** [jspenguin2017/uBlockProtector#978]
### Affected site:
`https://itavisen.no/`

### Issue:
Embeded videos are blocked.

### Problem filter:
uBlock Protector List (a.k.a. 'Nano Defender Integration')

### Problem rule:
`||sixscissors.com^$third-party`

### Page Screenshot (unblocked video):

![filterissue-itavisen3](https://user-images.githubusercontent.com/9382674/43742222-9e7fa8fe-99c0-11e8-8341-939c81328039.jpg)

### Console Screenshot (all other filters disabled):

![filterissue-itavisen4](https://user-images.githubusercontent.com/9382674/43742234-a51755d6-99c0-11e8-8a3a-a76eaa9e4d8c.jpg)

### Possible fix:
`@@||sixscissors.com^$third-party,domain=itavisen.no`

--

- OS/version: Windows 8.1 Pro (x64)
- Browser/version: Pale Moon v27.9.4 (x64)
- Adblock Extension/version: uBlock Origin v1.16.4.4 (XUL)

**Comment by jspenguin2017** [comment]
@DandelionSprout FYI. I don't know if there is another filter blocking that domain, it is one of Admiral's domains.
