### ISSUE TITLE
I could add ! Title: ! Author: to make it look better in the filter lists - uBlockProtectorList.txt

### ISSUE THREAD

**Issue by MS-PC** [jspenguin2017/uBlockProtector#981]
I could add to make it look better in the filter lists:
```
! Title: uBlock Protector
! Author: jspenguin2017
```
In the filter list: uBlockProtectorList.txt

**Comment by jspenguin2017** [comment]
Hi, that file is intended for Nano Filters build scripts, do not use. 
Get the proper filter here: https://cdn.rawgit.com/NanoAdblocker/NanoFilters/master/NanoMirror/NanoDefender.txt
