### ISSUE TITLE
Nano defender filter lists not loading

### ISSUE THREAD

**Issue by bobsage123** [jspenguin2017/uBlockProtector#998]
Updated to the new filter lists here - https://jspenguin2017.github.io/uBlockProtector/#extra-installation-steps-for-ublock-origin

But they all list 0 out of 0 on ublock origin. Have purged all caches and updated with the same result.

https://i.imgur.com/0oIWtbb.png

**Comment by jspenguin2017** [comment]
I can't reproduce, it works fine for me: 
![image](https://user-images.githubusercontent.com/7283682/47323595-b7bddd00-d619-11e8-8190-276304d7c962.png)

**Comment by bobsage123** [comment]
That's odd, have tried several times removing and re-adding them.

What happens if you remove and re-add them?

**Comment by jspenguin2017** [comment]
Still works. Tested links on my homepage.

**Comment by bobsage123** [comment]
I'll give it a day, maybe it will work itself out.

**Comment by bobsage123** [comment]
Finally figured out what was blocking it from updating.

This line from RUS: RU AdList 

`|xyz^$third-party,xmlhttprequest,domain=~anidub.com|~avtomaty-i-bonusy.com|~csgoreports.com|~cvid.kiev.ua|~estream.to|~funtik.tv|~hentaiz.org|~kinosklad.biz|~kristinita.ru|~magicfilm.net|~matchat.online|~my.mail.ru|~nccg.ru|~newdeaf-online.net|~online.animedia.tv|~roadhub.ru|~shamancoal.com|~soccer365.ru|~streetbee.io|~streetbee.ru|~telegafilm.ga|~vk.com`

**Comment by jspenguin2017** [comment]
Extension background page should be whitelisted by default, you might have touched some settings that you shouldn't.

**Comment by bobsage123** [comment]
Not sure, can't seem to find anything related to this. Oh well, it's fixed.
